/*****************************************************************************
*  Copyright Statement:   
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
#ifndef _TLG1100_H
#define _TLG1100_H

#include "gpio_drv.h"

/* OUTPUT DEBUG INFO. BY UART */
//#define OUTPUT_DEBUG_INFO
/*UNI@bw_20070614 重新整理地区列表并将巴西和阿根廷放到n制式里*/
typedef enum
{
/* PAL 制式  */
	ANALOG_TV_PAL_START,	
	
	ANALOG_TV_CHINA_START=ANALOG_TV_PAL_START,
     	ANALOG_TV_AREA_CHINA=ANALOG_TV_CHINA_START,
     	ANALOG_TV_CHINA_END=ANALOG_TV_AREA_CHINA,

	ANALOG_TV_SHENZHEN_START,
     	ANALOG_TV_AREA_SHENZHEN=ANALOG_TV_SHENZHEN_START,
     	ANALOG_TV_SHENZHEN_END=ANALOG_TV_AREA_SHENZHEN,

	ANALOG_TV_EUROPE_START,
	ANALOG_TV_AREA_EUROPE=ANALOG_TV_EUROPE_START,		//欧洲地区包涵国家和地区
	ANALOG_TV_AREA_TURKEY,
	ANALOG_TV_AREA_UAE,
	ANALOG_TV_AREA_AFGHANISTAN,
	ANALOG_TV_AREA_SINGAPORE,
	ANALOG_TV_AREA_THAILAND,
	ANALOG_TV_AREA_CAMBODIA,
	ANALOG_TV_AREA_INDONESIA,
	ANALOG_TV_AREA_MALAYSIA,
	ANALOG_TV_AREA_MYANMAR,
	ANALOG_TV_AREA_LAOS,
	ANALOG_TV_AREA_SPAIN,
	ANALOG_TV_AREA_PORTUGAL,
	ANALOG_TV_AREA_INDIA,
	ANALOG_TV_AREA_PAKISTAN,
	ANALOG_TV_EUROPE_END=ANALOG_TV_AREA_PAKISTAN,

	ANALOG_TV_VIETNAM_START,
	ANALOG_TV_AREA_VIETNAM=ANALOG_TV_VIETNAM_START,		//越南
	ANALOG_TV_VIETNAM_END=ANALOG_TV_AREA_VIETNAM,

	ANALOG_TV_ARGENTINA_START,
	ANALOG_TV_AREA_ARGENTINA=ANALOG_TV_ARGENTINA_START,	//阿根廷
	ANALOG_TV_ARGENTINA_END=ANALOG_TV_AREA_ARGENTINA,
	
	ANALOG_TV_HONGKONG_START,	//英国包涵国家地区
	ANALOG_TV_AREA_HONGKONG=ANALOG_TV_HONGKONG_START,	
	ANALOG_TV_AREA_ENGLAND,
	ANALOG_TV_AREA_SOUTH_AFRICA,
	ANALOG_TV_HONGKONG_END=ANALOG_TV_AREA_SOUTH_AFRICA,
	
	ANALOG_TV_PAL_END=ANALOG_TV_HONGKONG_END,
	
/* NTSL 制式  */

	ANLAOG_TV_NTSL_START,	//nts格式开始
	
	ANALOG_TV_AMERICA_START=ANLAOG_TV_NTSL_START,	//美国地区包涵国家
	ANALOG_TV_AREA_AMERICA=ANALOG_TV_AMERICA_START,	
	ANALOG_TV_AREA_CANADA,
	ANALOG_TV_AREA_KOREA,
	ANALOG_TV_AREA_TAIWAN,
	ANALOG_TV_AREA_MEXICO,
	ANALOG_TV_AREA_CHILE,
	ANALOG_TV_AREA_VENEZUELA,
	ANALOG_TV_AREA_PHILIPPINES,
	ANALOG_TV_AMERICA_END=ANALOG_TV_AREA_PHILIPPINES,

	ANALOG_TV_BRAZIL_START,
	ANALOG_TV_AREA_BRAZIL=ANALOG_TV_BRAZIL_START,
	ANALOG_TV_BRAZIL_END=ANALOG_TV_AREA_BRAZIL,
	
	ANALOG_TV_JAPAN_START,
	ANALOG_TV_AREA_JAPAN=ANALOG_TV_JAPAN_START,		//日本地区
	ANALOG_TV_JAPAN_END=ANALOG_TV_AREA_JAPAN,
	
	ANALOG_TV_NTSL_END=ANALOG_TV_JAPAN_END,
	
	ANALOG_TV_AREA_TOTALNUM
	
}AREA_FORMAT;

	
//#define ANALOG_TV_TEST_PATTERN_MODE

#define  I2C_DELAY_UNIT        12

// config sensor callback function 
void analog_tv_func_config(void);

/*analog tv QVGA Scan mode is progressive*/
#define  ANALOG_TV_QVGA_WIDTH					       (0x160) /*352*/
#define  ANALOG_TV_QVGA_HEIGHT					(0xe8) /*232*/
#define  ANALOG_TV_PERIOD_PIXEL_NUMS				(640) /*390*/
#define  ANALOG_TV_PERIOD_LINE_NUMS				(480) /*625//1250//NTSC:1050*/
#define ANALOG_TV_QVGA_INSERTED_PIXELS		       (0x10) /*16//NTSC:120*/
#define ANALOG_TV_QVGA_INSERTED_LINES			(0x08) /*8//NTSC:18*/


#endif
