/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2007
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   SATResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file is intends for SAT resource definitions
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef __SAT_RES_DEF_H__
#define __SAT_RES_DEF_H__

#include "MMIDataType.h"    /* for resource base */

/***************************************************************************** 
 * Typedef for Resource Enum
 *****************************************************************************/
/* Screen IDs */
typedef enum
{
    SCR_ID_SAT_MAINMENU = SAT_BASE + 1,
    SCR_ID_SAT_SUBMENU = SAT_BASE + 1,
    SCR_ID_SAT_DISPLAYTEXT = SAT_BASE + 1,
    SCR_ID_SAT_GETINPUT = SAT_BASE + 1,
    SCR_ID_SAT_GETINKEY = SAT_BASE + 1,
    SCR_ID_SAT_CMCALLBACK = SAT_BASE + 1,
    SCR_ID_SAT_SENDSMS = SAT_BASE + 1,
    SCR_ID_SAT_SENDSS = SAT_BASE + 1,
    SCR_ID_SAT_SENDUSSD = SAT_BASE + 1,
    SCR_ID_SAT_PLAYTONE = SAT_BASE + 1,
    SCR_ID_SAT_WAITSCREEN = SAT_BASE + 1,
    SCR_ID_SAT_SEND_SMS_CONF = SAT_BASE + 1,
    SCR_ID_SAT_LAUNCH_BROWSER_CONF = SAT_BASE + 1,
    SCR_ID_SAT_SEND_DTMF_CONF = SAT_BASE + 1,
    SCR_ID_SAT_SENDDTMF = SAT_BASE + 1,
    SCR_ID_SAT_SEND_AT_CMD = SAT_BASE + 1,
    SCR_ID_SAT_HISTORY = SAT_BASE + 1,

    SAT_OPEN_CHANNEL_CONF_SCREENID = SAT_BASE + 1,
    SAT_OPEN_CHANNEL_SCREENID = SAT_BASE + 1,
    SAT_CLOSE_CHANNEL_SCREENID = SAT_BASE + 1,
    SAT_SEND_DATA_CONF_SCREENID = SAT_BASE + 1,
    SAT_SEND_DATA_SCREENID = SAT_BASE + 1,
    SAT_RECV_DATA_CONF_SCREENID = SAT_BASE + 1,
    SAT_RECV_DATA_SCREENID = SAT_BASE + 1,

    /* diamond, 2005/12/12 Display SS reponse */
    SCR_ID_SAT_DISPLAY_SS,

    SAT_SCR_INPUT_METHOD_AND_DONE,
    SCR_ID_SAT_END
} SAT_SCR_ID_ENUM;

/* String IDs */
typedef enum
{
    SAT_WAIT_STRING_ID = SAT_BASE + 1,
    SAT_GET_INPUT_LENGTH_NOT_ENOUGH,
    SAT_SETUP_CALL_CONF_STRING_ID,
    SAT_SEND_SMS_CONF_STRING_ID,
    SAT_SEND_SMS_STRING_ID,
    SAT_SMS_ERROR_STRING_ID,
    SAT_SMS_SUCCESS_STRING_ID,
    SAT_SEND_SS_STRING_ID,
    SAT_SS_ERROR_STRING_ID,
    SAT_SS_SUCCESS_STRING_ID,
    SAT_SEND_USSD_STRING_ID,
    SAT_USSD_ERROR_STRING_ID,
    SAT_USSD_SUCCESS_STRING_ID,
    SAT_USSD_ABORT_STRING_ID,
    SAT_SEND_DTMF_CONF_STRING_ID,
    SAT_SEND_DTMF_STRING_ID,
    SAT_DTMF_ERROR_STRING_ID,
    SAT_DTMF_SUCCESS_STRING_ID,
    SAT_LAUNCH_BROWSER_CONF_STRING_ID,  /* diamond, 2005/01/11 LAUNCH BROWSER confirmation string */
    SAT_NEXT_ACTION_REFRESH_STRING_ID,
    SAT_NEXT_ACTION_MORE_TIME_STRING_ID,
    SAT_NEXT_ACTION_POLL_INTERVAL_STRING_ID,
    SAT_NEXT_ACTION_POLLING_OFF_STRING_ID,
    SAT_NEXT_ACTION_SETUP_EVENT_LIST_STRING_ID,
    SAT_NEXT_ACTION_SETUP_CALL_STRING_ID,
    SAT_NEXT_ACTION_SEND_SS_STRING_ID,
    SAT_NEXT_ACTION_SEND_USSD_STRING_ID,
    SAT_NEXT_ACTION_SEND_SMS_STRING_ID,
    SAT_NEXT_ACTION_SEND_DTMF_STRING_ID,
    SAT_NEXT_ACTION_LAUNCH_BROWSER_STRING_ID,
    SAT_NEXT_ACTION_PLAY_TONE_STRING_ID,
    SAT_NEXT_ACTION_DISPLAY_TEXT_STRING_ID,
    SAT_NEXT_ACTION_GET_INKEY_STRING_ID,
    SAT_NEXT_ACTION_GET_INPUT_STRING_ID,
    SAT_NEXT_ACTION_SELECT_ITEM_STRING_ID,
    SAT_NEXT_ACTION_SETUP_MENU_STRING_ID,
    SAT_NEXT_ACTION_PROVIDE_LOCAL_INFO_STRING_ID,
    SAT_NEXT_ACTION_TIMER_MANAGEMENT_STRING_ID,
    SAT_NEXT_ACTION_SETUP_IDLE_TEXT_STRING_ID,
    SAT_NEXT_ACTION_PERFORM_CARD_APDU_STRING_ID,
    SAT_NEXT_ACTION_POWER_ON_CARD_STRING_ID,
    SAT_NEXT_ACTION_POWER_OFF_CARD_STRING_ID,
    SAT_NEXT_ACTION_GET_READER_STATUS_STRING_ID,
    SAT_NEXT_ACTION_RUN_AT_COMMAND_STRING_ID,
    SAT_NEXT_ACTION_LANGUAGE_NOTIFICATION_STRING_ID,
    SAT_NEXT_ACTION_OPEN_CHANNEL_STRING_ID,
    SAT_NEXT_ACTION_CLOSE_CHANNEL_STRING_ID,
    SAT_NEXT_ACTION_RECEIVE_DATA_STRING_ID,
    SAT_NEXT_ACTION_SEND_DATA_STRING_ID,
    SAT_NEXT_ACTION_GET_CHANNEL_STATUS_STRING_ID,
    SAT_NEXT_ACTION_RESERVED_FOR_TIA_STRING_ID,
    SAT_NEXT_ACTION_END_SESSION_STRING_ID,
#ifdef __SATCE__
    SAT_OPEN_CHANNEL_STRING_ID,
    SAT_OPEN_CHANNEL_CONF_STRING_ID,
    SAT_OPEN_CHANNEL_SUCCESS_STRING_ID,
    SAT_OPEN_CHANNEL_FAIL_STRING_ID,

    SAT_SEND_DATA_STRING_ID,
    SAT_SEND_DATA_CONF_STRING_ID,
    SAT_SEND_DATA_SUCCESS_STRING_ID,
    SAT_SEND_DATA_FAIL_STRING_ID,

    SAT_RECV_DATA_STRING_ID,
    SAT_RECV_DATA_CONF_STRING_ID,
    SAT_RECV_DATA_SUCCESS_STRING_ID,
    SAT_RECV_DATA_FAIL_STRING_ID,
#endif /* __SATCE__ */ 
    SAT_PLAY_TONE_STRING_ID,
    SAT_NUM_CHANGED_BY_SIM_STRING_ID,
    SAT_MENU_STRING_ID
} SAT_STR_ID_ENUM;

/* Image IDs */
typedef enum
{
    SAT_WAIT_IMAGE_ID = SAT_BASE + 1,
    SAT_TITLE_IMAGE_ID,
#if (defined __MMI_DUAL_SIM_SINGLE_CALL__) || (defined __MMI_DUAL_SIM_MASTER__)
    SAT_TITLE_IMAGE_ID_2,
#endif /* (defined __MMI_DUAL_SIM_SINGLE_CALL__) || (defined __MMI_DUAL_SIM_MASTER__) */
    SAT_IMG_ID_END
} SAT_IMG_ID_ENUM;

#endif /*__SAT_RES_DEF_H__ */

