/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 * CallSetUpEnum.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   <file description>.
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *============================================================================== 
 *******************************************************************************/

/**
 * Copyright Notice
 * ?2002 - 2002, Pixtel Communications, Inc., 1489 42rd Ave. W.,
 * Vancouver, B.C. V6M 4K8 Canada. All Rights Reserved.
 *  (It is illegal to remove this copyright notice from this software or any
 *  portion of it)
 */
/**************************************************************

   FILENAME : Calls_Defs.h

   PURPOSE     : Call application 

   REMARKS     : nil

   AUTHOR      : PixTel

   DATE     : Jan 15,02

**************************************************************/
#ifndef _PIXTEL_CALLSETUPENUMS_H
#define _PIXTEL_CALLSETUPENUMS_H

typedef enum
{
    STR_CALL_SETUP_REQ_CAPTION = CALL_BASE_NEW + 1,
    /* STR_CALL_SETUP_REQ_LSK, */
    STR_CALL_SETUP_TEXT,
    STR_SCR8094_MNGCALL_CALWAIT_MENU_CAPTION,
    STR_SCR8094_MNGCALL_CALWAIT_MENU_ON,
    /* STR_SCR8094_MNGCALL_CALWAIT_MENU_OFF         , */
    STR_SCR8094_MNGCALL_CALWAIT_MENU_QUERY,
    STR_SCR8095_MNGCALL_CALLWAIT_BUSY_CAPTION,
    STR_SCR8095_MNGCALL_CALLWAIT_BUSY_TEXT,
    STR_SCR8096_MNGCALL_CALLWAIT_ON_SUCCESS_CAP,
    STR_SCR8096_MNGCALL_CALLWAIT_ON_SUCCESS_TEXT,
    STR_SCR8097_MNGCALL_CALLWAIT_ON_FAIL_CAPTION,
    STR_SCR8096_MNGCALL_CALLWAIT_ON,
    STR_SCR8097_MNGCALL_CALLWAIT_ON_FAIL_TEXT,
    STR_SCR8098_MNGCALL_CALLWAIT_OFF_SUCCESS_CAPTION,
    STR_SCR8098_MNGCALL_CALLWAIT_OFF_SUCCESS_TEXT,
    /* STR_SCR8099_MNGCALL_CALLWAIT_OFF_FAIL_CAPTION                        , */
    STR_SCR8099_MNGCALL_CALLWAIT_OFF_FAIL_TEXT,
    STR_SCR8100_MNGCALL_CALLWAIT_ON_STATUS_TEXT,
    STR_SCR8101_MNGCALL_CALLWAIT_OFF_STATUS_CAPTION,
    STR_SCR8101_MNGCALL_CALLWAIT_OFF_STATUS_TEXT,
    STR_SCR8093_MNGCALL_MENU_CAPTION,
    STR_SCR8093_MNGCALL_MENU_CUG,
    STR_MENU8238_MNGCALL_CALLFWD_VOICE,
    STR_MENU8238_MNGCALL_CALLFWD_FAX,
    STR_MENU8238_MNGCALL_CALLFWD_DATA,
    STR_MENU8238_MNGCALL_CALLFWD_CAPTION,
    STR_MENU8239_CALFWD_VOICECALL_OPTION,
    STR_MENU8239_CALFWD_VOICECALL_UNREACHABLE,
    STR_MENU8239_CALFWD_VOICECALL_NOANSWER,
    STR_MENU8239_CALFWD_VOICECALL_ALLCOND,
    STR_MENU8239_CALFWD_VOICECALL_NOANSWER_OPTIONS,
    STR_MENU8239_CALFWD_VOICECALL_BUSY,
    STR_MENU8239_CALFWD_VOICECALL_UNCONDITIONALY,
    STR_MENU8240_MNGCALL_CALLFWD_FWD_OPTION,
    STR_MENU8240_MNGCALL_CALLFWD_FWD_ON,
    /* STR_MENU8240_MNGCALL_CALLFWD_FWD_OFF         , */
    STR_MENU8240_MNGCALL_CALLFWD_FWD_QUERY,
    STR_SCR8106_MNGCALL_CALLFWD_ACTIVATE_ON_SUCC_CAP,
    /* STR_SCR8107_MNGCALL_CALLFWD_ACTIVATE_ON_FAIL_CAP     , */
    STR_SCR8108_MNGCALL_CALLFWD_QUERY_RSP_FAIL_CAPTION,
    STR_SCR8108_MNGCALL_CALLFWD_QUERY_RSP_FAIL_TEXT,
    STR_CALL_FWD_ENTER_NUM_CAP,
    SCR_CALL_FWD_ENTER_NO_ANSWER_TIME_CAP,
    STR_MENU_CALL_FWD_CANCELALL,
    STR_05_SECONDS,
    STR_10_SECONDS,
    STR_15_SECONDS,
    STR_20_SECONDS,
    STR_25_SECONDS,
    STR_30_SECONDS,
    STR_MENU_CALL_BARRING_OUTGOING,
    STR_MENU_CALL_BARRING_INCOMING,
    STR_MENU_CALL_BARRING_CANCELALL,
    STR_MENU_CALL_BARRING_CHANGEPASS,
    STR_SCR_CALL_BARRING_MAIN_CAPTION,
    STR_MENU_CALL_BARRING,
    STR_BARRING_OUTGOING_CALL_CAPTION,
    STR_MENU_BARRING_OUTGOING_ALLCALLS,
    STR_MENU_BARRING_OUTGOING_INTERCALL,
    STR_MENU_BARRING_OUTGOING_INTEREXCEPTHOME,
    STR_MENU_BARRING_INCOMING_ALLCALLS,
    STR_MENU_BARRING_INCOMING_ROAMING,
    STR_MENU_BARRING_ACTIVATE,
    /* STR_MENU_BARRING_DEACTIVATE                  , */
    STR_MENU_BARRING_QUERY,
    STR_SCR_ACTIVATE_DEACTIVATE_CAP,
    STR_BARRING_PASSWORD_CAP,
    STR_BARRING_ACIVATE_CAP,
    STR_BARRING_ACTIVATE_TEXT,
    STR_BARRING_DEACTIVATE_TEXT,
    STR_BARRING_INCOMING_CAP,
    STR_MENU_BARRING_OUT_CALLS_MAIN,
    STR_MENU_BARRING_INCOMING_MAIN,
    STR_MENU_BARRING_OPTION,
    STR_MENU_CALLER_ID,
    STR_BARRING_DEACTIVATE_CAP,
    STR_CLI_SET_NETWORK,
    STR_CLI_HIDE_ID,
    STR_CLI_SEND_ID,
    STR_CALLER_ID_TITLE,
    STR_CLIP_STATUS_ACT_TXT,
    STR_CLIP_STATUS_NACT_TXT,
    STR_CLIR_STATUS_ACT_PERMANENTLY_TXT,
    STR_CLIR_STATUS_ACT_DEFAULT_RESTRICT_TXT,
    STR_CLIR_STATUS_ACT_DEFAULT_ALLOW_TXT,
    STR_CLIR_STATUS_NACT_TXT,
    //STR_CLI_UNKNOWN_ERROR,
    //STR_CLIR_SUCCESS_TEXT,
    STR_COLP_STATUS_ACT_TXT,
    STR_COLP_STATUS_NACT_TXT,
    STR_COLR_STATUS_ACT_TXT,
    STR_COLR_STATUS_NACT_TXT,
    STR_CNAP_STATUS_ACT_TXT,
    STR_CNAP_STATUS_NACT_TXT,
    STR_CCBS_STATUS_TITLE,
    STR_CCBS_STATUS_ACT_TXT,
    STR_CCBS_STATUS_NACT_TXT,
    STR_LSW_LINE1,
    STR_LSW_LINE2,
    STR_LINE_SWITCH,
    STR_LINE_SET_TITLE,
    STR_LINE1_SET_ERR,
    STR_SETTING_LINE_SEL,
    /* STR_REQ_ABORT_CAPTION, */
    STR_CALL_DIVERT_ACTIVATE_VOICEFWD_UNREACHABLE,
    STR_CALL_DIVERT_ACTIVATE_VOICEFWD_NOANSWER,
    STR_CALL_DIVERT_ACTIVATE_VOICEFWD_BUSY,
    STR_CALL_DIVERT_ACTIVATE_VOICEFWD_UNCONDITIONAL,
    STR_CALL_DIVERT_ACTIVATE_DATA_FWD,
    STR_CALL_DIVERT_ACTIVATE_FAX_FWD,
    STR_CALL_DIVERT_DEACTIVATE_VOICEFWD_UNREACHABLE,
    STR_CALL_DIVERT_DEACTIVATE_VOICEFWD_NOANSWER,
    STR_CALL_DIVERT_DEACTIVATE_VOICEFWD_BUSY,
    STR_CALL_DIVERT_DEACTIVATE_VOICEFWD_UNCONDITIONAL,
    STR_CALL_DIVERT_DEACTIVATE_DATA_FWD,
    STR_CALL_DIVERT_DEACTIVATE_FAX_FWD,
    STR_ID_CALFWD_TO_OPTION,
    STR_ID_CALFWD_TO_NEW_NUMBER,
    STR_ID_CALFWD_TO_VM,
    STR_CALL_AVTIVATE_ERROR,
    STR_CALL_DEACTIVATE_ERROR,
    STR_OLD_BARRINGPASS_CAP,
    STR_NEW_BARRINGPASS_CAP,
    STR_CONFIRM_BARRINGPASS_CAP,
    STR_CANCEL_ALL_SUCCESS_TEXT,
    STR_CANCEL_ALL_ERROR_TEXT,
    STR_CHANGE_PSW_SUCCESS_TEXT,
    STR_CHANGE_PSW_ERROR_TEXT,
    STR_ACTIVATE_BARRING_OUTGOING_ALLCALLS,
    STR_ACTIVATE_BARRING_OUTGOING_INTERCALL,
    STR_ACTIVATE_BARRING_OUTGOING_INTEREXCEPTHOME,
    STR_ACTIVATE_BARRING_INCOMING_ALLCALLS,
    STR_ACTIVATE_BARRING_INCOMING_ROAMING,
    STR_DEACTIVATE_BARRING_OUTGOING_ALLCALLS,
    STR_DEACTIVATE_BARRING_OUTGOING_INTERCALL,
    STR_DEACTIVATE_BARRING_OUTGOING_INTEREXCEPTHOME,
    STR_DEACTIVATE_BARRING_INCOMING_ALLCALLS,
    STR_DEACTIVATE_BARRING_INCOMING_ROAMING,
    STR_HASH_VALUE,
    STR_CANCEL_ALL_DIVERT,
    STR_CLIR_STATUS_ACT_TXT,
    STR_MENU_SETTING_CALL_TIME_DISPLAY,
    STR_MENU9140_AUTO_REDIAL,
    STR_SETTING_CALL_REMINDER,
    /* STR_SETTING_CR_OFF, */
    STR_SETTING_CR_SING,
    STR_SETTING_CR_PERIOD,
    STR_SETTING_CALL_CLOSED_GP,
    STR_BAOC_A,
    STR_BOIC_A,
    STR_BOICEXHC_A,
    STR_BAIC_A,
    STR_BAICROAM_A,
    STR_BAC_A,
    STR_BOC_A,
    STR_BIC_A,
    STR_DEFAULT_A,
    STR_ACTIVATED,
    STR_DEACTIVATED,
    STR_NOT_PROVIDED,
    STR_SECONDS,
    STR_BOTH_LINES,
    /* STR_NOT_DONE, */
    STR_BAOC_D,
    STR_BOIC_D,
    STR_BOICEXHC_D,
    STR_BAIC_D,
    STR_BAICROAM_D,
    STR_BAC_D,
    STR_BOC_D,
    STR_BIC_D,
    STR_L4_ALL_TELESERVICES,
    STR_L4_TELEPHONY,
    STR_L4_ALL_DATA_TELESERVICES,
    STR_L4_FACSIMILE_SERVICES,
    STR_SHORT_MESSAGE_SERVICES,
    STR_L4_ALL_TELESERVICES_EXCEPT_SMS,
    STR_L4_VOICE_GROUP_CALL_SERVICE,
    STR_L4_VOICE_BROADCAST_SERVICE,
    STR_L4_ALL_BEARER_SERVICES,
    STR_L4_ALL_ASYNC_SERVICES,
    STR_L4_ALL_SYNC_SERVICES,
    STR_L4_ALL_DATA_CIRCUIT_SYNC,
    STR_L4_ALL_DATA_CIRCUIT_ASYNC,
    STR_L4_ALL_GPRS_BEARER_SERVICES,
    STR_L4_BS_ALLPADACCESSCA_SERVICES,
    STR_L4_BS_ALLDATAPDS_SERVICES,
    STR_UNKNOWN_CAUSE,
    STR_MENU_SETTINGS_ABOUT,
    STR_RESTORE_PHONE,
    STR_RESTORE_SUCCESS,
    //STR_GROUPLIST_EDIT,
    //STR_CUG_DONE_OPTION_ID,
    //STR_CUG_INPUT_METHOD_OPTION_ID,
    //STR_GROUPLIST_ADD,
    STR_GROUPLIST_ADD_INDEX,
    STR_GROUPLIST_EDIT_INDEX,
    //STR_GROUPLIST_ACTIVATE,
    //STR_GROUPLIST_DEACTIVATE,
    STR_GROUPLIST_ACTIVATED,
    STR_GROUPLIST_DEACTIVATED,
    //STR_GROUPLIST_NOT_ACTIVATED,
    //STR_GROUPLIST_NOT_DEACTIVATED,
    STR_GROUPLIST_INVALID_INDEX,
    STR_GROUPLIST_DELETE,
    //STR_GROUPLIST_DELETED,
    //STR_GROUPLIST_DELETE_CONFIRM,
    STR_GROUPLIST_CAPTION,
    MAIN_MENU_GROUPLIST_TEXT,
    STR_GROUPLIST_OPTION_CAPTION,
    STR_MENU_SETTING_POWER_SAVING,
    //STR_MENU_POWER_SAVING_OFF,
    //STR_MENU_POWER_SAVING_ON,

    /* IP Number */
    STR_SETTING_IP_NUMBER,
    STR_SETTING_IP_NUM_ACT,
    STR_SETTING_IP_NUM_EDIT,
    /* Start by Julia */
    /* Black List */
    STR_SETTING_BLACK_LIST,
    STR_SETTING_BLACK_LIST_MODE,
    STR_SETTING_BLACK_LIST_NUM,
    /* End by Julia */
    /* manage main call str end */
    /* call fwd str start */
    STR_L4_CFU,
    STR_L4_CFB,
    STR_L4_CFNRY,
    STR_L4_CFNRC,
    STR_L4_CFA,
    STR_L4_CFC,
    STR_FWD_UNKNOWN_SERVICE,
    STR_TO,
    STR_L4_CFU_D,
    STR_L4_CFB_D,
    STR_L4_CFNRY_D,
    STR_L4_CFNRC_D,
    STR_L4_CFA_D,
    STR_L4_CFC_D,
    STR_ID_CALLFWD_VIDEO_ALL,
    STR_ID_CALLFWD_VIDEO_UNREACHABLE,
    STR_ID_CALLFWD_VIDEO_NOANSWER,
    STR_ID_CALLFWD_VIDEO_BUSY,
    STR_ID_CALLFWD_VIDEO_ALL_COND,
    STR_ID_CALLFWD_VOICE_UNREACHABLE,
    STR_ID_CALLFWD_VOICE_NOANSWER,
    STR_ID_CALLFWD_VOICE_BUSY,
    STR_ID_CALLFWD_VOICE_ALL_COND
} CALL_SETUP_STRINGS;

typedef enum
{
    IMG_SCR_BARRING_INCOMING_LSK = CALL_BASE_NEW + 1,
    IMG_SCR_BARRING_INCOMING_RSK,
    IMG_BARRING_ACIVATE_CAP,
    IMG_BARRING_DEACTIVATE_CAP,
    IMG_SCR8103_CAPTION,
    IMG_SCR8105_CAPTION,
    IMG_SCR8106_CAPTION,
    IMG_SCR8107_CAPTION,
    IMG_SCR8108_CAPTION,
    IMG_CALL_FWD_ENTER_NUM_LSK,
    IMG_CALL_FWD_ENTER_NUM_RSK,
    IMG_SCR_CALL_SETUP_REQ_CAP,
    IMG_SCR_CALL_SETUP_REQ_LSK,
    IMG_SCR8095_CAPTION,
    IMG_SCR8095_TEXT,
    IMG_SCR8096_CAPTION,
    IMG_SCR8097_CAPTION,
    IMG_SCR8098_CAPTION,
    IMG_SCR8099_CAPTION,
    IMG_SCR8100_CAPTION,
    IMG_SCR8101_CAPTION,
    IMG_CALLER_ID_TITLE_ICN,
    IMG_CLIP_STATUS_TITLE,
    IMG_CLIR_STATUS_TITLE,
    IMG_CLI_HIDE_ID,
    IMG_LSW_TITLE,
    IMG_LSW_LINE1,
    IMG_LSW_LINE2,
    IMG_LINE_SET_TITLE,
    IMG_CALLSETUP_MAIN_MENU,
    IMG_CLIP_SETUP_REQ_LSK_ERR,
    IMG_BARING_CAP
} CALL_SETUP_IMG;

typedef enum
{
    SCR_ID_CALLSET_BARRING_MAIN = CALL_BASE_NEW + 1,
    SCR_ID_CALLSET_BARRING_OUT,
    SCR_ID_CALLSET_BARRING_IN,
    SCR_ID_CALLSET_BARRING_OPTION,
    SCR_ID_CALLSET_BARRING_PASS,
    SCR_BARRING_ACTIVATE,
    SCR_BARRING_DEACTIVATE,
    SCR_ID_CALLSET_FORWARD_MAIN,
    SCR8103_MNGCALL_CALLFWD_VOICECALL_OPTION,
    SCR_ID_CALLSET_FORWARD_OPTIONS,
    SCR8105_MNGCALL_CALLFWD_BUSY_SCREEN,
    SCR8106_MNGCALL_CALLFWD_ACTIVATE_ON_SUCCESS,
    SCR8107_MNGCALL_CALLFWD_ACTIVATE_ON_FAIL,
    SCR8108_MNGCALL_CALLFWD_QUERY_RSP_FAIL,
    SCR_ID_CALLSET_FORWARD_NUMBER,
    SCR_ID_CALFWD_TO_OPTION,
    SCR_ID_CALLSET_FORWARD_NO_ANS_TIME,
    SCR_CALL_SET_UP_REQUESTING,
    SCR_ID_CALLSET_WAITING_MAIN,
    SCR8095_MNGCALL_CALLWAIT_BUSY,
    SCR8096_MNGCALL_CALLWAIT_ON_SUCCESS,
    SCR8097_MNGCALL_CALLWAIT_ON_FAILURE,
    SCR8098_MNGCALL_CALLWAIT_OFF_SUCCESS,
    SCR8099_MNGCALL_CALLWAIT_OFF_FAILURE,
    SCR8100_MNGCALL_CALLWAIT_ON_STATUS,
    SCR8101_MNGCALL_CALLWAIT_OFF_STATUS,
    SCR_ID_CALLSET_MAIN,
    SCR_ID_CALLSET_CALLER_ID_MAIN,
    SCR_CALL_BARRING_RESULT,
    SCR_CALL_FORWARDING_RESULT,
    SCR_ID_CALLSET_GENERAL_SS_RESULT,
    ITEM_SCR_LINE_SWITCH,
    SCR_ID_CALLSET_BARRING_OLD_PASS,
    SCR_ID_CALLSET_BARRING_CHANGE_PASS_RESULT,
    SCR_ID_CALLSET_BARRING_NEW_PASS,
    SCR_ID_CALLSET_BARRING_CFRM_PASS,
    SCR_SETTING_IP_NUMBER,
    SCR_SETTING_IP_NUM_OPN,
    SCR_SETTING_IP_NUM_EDIT,
    /* Start by Julia */
    SCR_SETTING_BLACK_LIST,
    SCR_SETTING_BLACK_LIST_NUM
        /* End by Julia */
} CALL_SETUP_SCR;

#endif /* _PIXTEL_CALLSETUPENUMS_H */ 

