/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2007
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  SettingResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *  Resource definitions.
 *
 *  Author:
 * -------
 *  Xiangjun Dan
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/

#ifndef SETTINGRESDEF_H
#define SETTINGRESDEF_H

#include "MMI_features.h"   

#include "MMIDataType.h"    /* for resource base */

/***************************************************************************** 
 * Typedef for Resource Enum
 *****************************************************************************/
/* Screen IDs */
typedef enum 
{
    SCR9000_SETTINGS = SETTINGS_BASE,
    /* add new screen ID below this line */    
    
    SCR_ID_SECSET_MAIN,
    SCR_ID_SECSET_PHONE_LOCK,

    SCR9022_AUTO_KEYPAD_LOCK,

    SCR_ID_SECSET_PIN2,
    SCR_ID_SECSET_BAR_DIAL,
    SCR_ID_SECSET_SIM_LOCK_PIN1,
    SCR_ID_SECSET_CHANGE_PASSWORD,
    SCR9027_PIN2,
    SCR9028_PIN1,
    SCR_ID_SECSET_CHANGEPW_OLD_PWD,
    SCR_ID_SECSET_CHANGEPW_NEW_PWD,
    SCR_ID_SECSET_CHANGEPW_CFM_PWD,
    SCR9032_SUCCESS,
    SCR9033_AUTO_REDIAL,
    SCR9027_PIN21,

    SCR_ID_SECSET_AKPL_TIME,

    SCR9028_PIN1_CAPTION,
    SCR_SETTING_CALL_TIME_DISPLAY,
    SCR_SETTING_MENU_TREE,
    SCR_ID_SECSET_FDN_LIST,
    SCR8055_SERVICE_OFF,
    SCR_ID_SECSET_FDN_OPTION,
    SCR8057_FDL_VIEW_DETAILS,
    SCR_ID_SECSET_FDN_DETAILS,
    SCR8059_FDL_ADD_NUMBER_DETAILS,
    SCR8060_FDL_NO_LIST,
    SCR8061_FDL_ENTRY_SAVE,
    SCR8062_FDL_ENTRY_NOT_SAVE,
    SCR8063_FDL_SCREEN_IN_PROGRESS,
    SCR8064_FDL_SCREEN_OVERWRITE,
    SCR8065_FDL_DELETE_CONFIRM,
    SCR8066_FDL_DELETE_NOTE,
    SCR8067_FDL_DELETE_ALL_NOTE,
    SCR_ID_SECSET_FDNBDN_SAVING,
    SCR_ID_SECSET_FDNBDN_DELETING,
    SCR_ID_SECSET_FDNBDN_WAITING,
    SCR_RESTORE,
    SCR_RESTORE_PROCESSING,
    SCR8077_BDL_SCREEN,
    SCR8078_BDL_SERVICE_OFF,
    SCR_ID_SECSET_BDN_LIST,
    SCR_ID_SECSET_BDN_OPTION,
    SCR_ID_SECSET_BDN_DETAILS,
    SCR8083_BDL_ADD_NUMBER,
    SCR8084_BDL_OVERWRITE,
    SCR8085_BDLFDL_DUPLICATE,
    SCR8086_BDL_ENTRY_SAVE,
    SCR8087_BDL_ENTRY_NOTSAVE,
    SCR8088_BDL_SCREEN_IN_PROGRESS,
    SCR8089_BDL_SCREEN_VIEW_DETAILS,
    SCR_ID_SECSET_BDN_DEL_CONFIRM,
    SCR8091_BDL_DELETED_ENTRY,
    SCR8092_BDL_FAILURE_DELETE,
    SCR_SETTING_RESTORE_CONFIRM,
    SCR_ID_SECSET_PUK1,
    SCR_ID_SECSET_PUK2,
    SCR_ID_SECSET_PUK_NEW_PIN1,
    SCR_ID_SECSET_PUK2_NEW_PIN2,
    SCR_ID_SECSET_PUK_CONFIRM_PIN1,
    SCR_ID_SECSET_PUK2_CONFIRM_PIN2,
    SCR_ID_SECSET_FIX_DIAL,
    SCR_ID_CALLSET_CUG_OPTIONS,
    SCR_ID_CALLSET_CUG_MAIN,
    SCR_ID_CALLSET_CUG_ADD_LIST,
    SCR_ID_CALLSET_CUG_EDIT_LIST,
    SCR_ID_CALLSET_CUG_ADD_LIST_INDEX,
    SCR_ID_CALLSET_CUG_EDIT_LIST_INDEX,
    SCR_ID_CALLSET_CUG_DEL_LIST_CNRM,
    SCR_ID_CALLSET_CUG_EDIT_OPTIONS,
    SCR_POPUP_GROUPLIST,
    SCR_ID_CALLSET_CTR,
    SCR_ID_CALLSET_CTR_TIME,
    SCR_SETTING_CTR_TIME_DONE,
    SCR_SECSET_FDN_SAVE_CONFIRM,
    SCR_ID_SECSET_FDN_DEL_CONFIRM,
    SCR_SETTING_PIN2_BLOCKED,
    SCR_DATETIME_DUMMY,

    SCR_ID_SETTING_SOUND_EFFECT,
    SCR_ID_SETTING_AUDIO_EFFECT,

    SCR_ID_SETTING_AUDIO_EQUALIZER_OPTIONS,
    SCR_ID_SETTING_AUDIO_EQUALIZER_OPTIONS_EDIT,
    SCR_ID_AUDIO_EQUALIZER_SETTING_NAME_EDIT,
    SCR_ID_AUDIO_EQUALIZER_SETTING_NAME_EDIT_OPTION,

    SCR_INPUT_METHOD_SELECTION,

    SCR_SECSET_BDN_SAVE_CONFIRM,
    
    /* add new screen ID above this line */
    SCR_ID_SETTING_END
} SCR_ID_SETTING_ENUM;

typedef enum 
{
    SCR9003_INITIALSETUP = PHONE_SETUP_BASE,
    /* add new screen ID below this line */
        
    SCR_DISP_SETUP,
    SCR9146_WELCOME_TEXT,
    SCR9146_WELCOME_TEXT_ON,
    SCR9041_TIMEANDDATE,
    SCR9042_SETTIME,
    SCR9043_SETTIMEFORMAT,
    SCR9044_SETDATE,
    SCR9045_SETDATEFORMAT,
    SCR9051_24HOURS,
    SCR9052_AM_PM,
    SCR9061_DATE_MONTH,
    SCR9062_DATE_MONTH_YEAR,
    SCR9063_MONTH_DATE_YEAR,
    SCR9064_DATE_MONTH_YEAR2,
    SCR_SETTING_POWER_ON_WITH_ALARM,
    SCR_SETTING_SPEED_DIAL,
    SCR_SETTING_CONTRAST_LEVEL,
    SCR_SETTING_SCHEDULE_POWER,
    SCR_ID_PHNSET_SET_DT,
    SETTINGS_SET_TIME_FORMAT_SCREENID,
    /* __MMI_SEPARATE_DT_SETTING__ */
    SCR_ID_PHNSET_SET_DATEANDFORMAT,
    SCR_ID_PHNSET_SET_TIMEANDFORMAT,
    /* __MMI_SEPARATE_DT_SETTING__ */
    SETTINGS_SETHOMECITY_SCREENID,
    SCR_IDLE_SCR_DISP,
    SCR_IDLE_SCR_DISP_WP_PREVIEW,
    SCR_MAINMENU_STYLE,
    SCR_DEDICATED_KEYS,
    SCR_EDIT_DEDICATED_KEYS,

    SCR_DEF_ENCODING_TYPE,

    SCR_HANDWRITING_SETTING,
    SCR_CALIBRATION_SETTING,

	SCR_ID_PHNSET_UART_SETUP,
	SCR_ID_PHNSET_UART_REBOOT_PROCESSING,

    SCR_CALIBRATION_CONTROL_AREA_TESTING,

    SCR_ID_SETTING_TVOUT,
    SCR_ID_SETTING_TVOUT_SETTING,
    SCR_ID_SETTING_TVOUT_ADJUST,

    SCR_SPEED_PHONELIST,

    SCR_ID_PHNSET_FONT_SIZE,

    SCR_ID_PHNSET_GPIO_SETTING,
    SCR_ID_PHNSET_GPIO_LED,
    SCR_ID_PHNSET_GPIO_BACKLITE,
    SCR_ID_PHNSET_GPIO_COVER_CLOSE,

    SCR_ID_PHNSET_PREFERRED_WRITING_LANG,

    SCR_ID_PHNSET_MIXED_LANG,

    /* add new screen ID above this line */
    SCR_ID_PHNSET_END
} SCR_ID_PHNSET_ENUM;

typedef enum 
{
    SCR_LANGUAGE_SELECTION = LANG_SETTINGS_BASE,
    /* add new screen ID below this line */
    
    /* add new screen ID above this line */
    SCR_ID_SETTING_LANGUAGE_END
} SCR_ID_SETTING_LANGUAGE_ENUM;


/* diamond, 2005/07/05 Flight mode */
typedef enum 
{
    SCR_FLIGHT_MODE_SELECTION = FLIGHT_MODE_BASE,
    /* add new screen ID below this line */
        
    SCR_FLIGHT_MODE_QUERY,
    SCR_FLIGHT_MODE_IDLE,
    SCR_FLIGHT_MODE_PROGRESS,
    SCR_FLIGHT_MODE_LOGO,

    /* add new screen ID above this line */    
    SCR_ID_FLOGHT_MODE_END
} SCR_ID_FLIGHT_MODE_ENUM;
/* end, diamond */

typedef enum 
{
    STR_MENU9100_CALL_SETTING = SETTINGS_BASE,
    /* add new string ID below this line */    
    
    STR_SCR9000_SETTINGS_CAPTION,
    STR_POWER_SAVE_TIMER_CAPTION,
    STR_SETTING_RESTORE_CONFIRM,
    STR_SETTING_RESTORE_PROCESSING,
    STR_SETTING_YES,
    STR_SETTING_WRONG,
    /* micha0616 */
    STR_SETTING_BLOCK,
    STR_CTR_REM,
    STR_SETTING_CR_RANGE1,
    STR_SETTING_CR_RANGE2,
    STR_SETTING_CR_RANGE3,
    STR_ID_SETTING_SOUND_EFFECT,
    STR_ID_SETTING_AUDIO_EFFECT,
    STR_ID_SETTING_AUDIO_EQUALIZER,
    STR_ID_SETTING_AUDIO_EQUALIZER_CAPTION,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_1,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_2,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_3,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_4,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_5,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_6,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_7,
    STR_ID_SETTING_AUDIO_EQUALIZER_SET_8,
    STR_ID_SETTING_AUDIO_EQUALIZER_REST_FACT_DEFAULT,
    STR_ID_SETTING_AUDIO_EQUALIZER_SETTING_RENAME,
    STR_ID_SETTING_AUDIO_EQUALIZER_SETTIN_NAME_EDIT_TITLE,
    STR_ID_SETTING_AUDIO_EQUALIZER_SETTING_INVALID_NAME,
    STR_ID_SETTING_AUDIO_REVERB_EFFECT,
    STR_ID_SETTING_AUDIO_REVERB_EFFECT_SET1,
    STR_ID_SETTING_AUDIO_REVERB_EFFECT_SET2,
    STR_ID_SETTING_AUDIO_REVERB_EFFECT_SET3,
    STR_ID_SETTING_AUDIO_REVERB_EFFECT_SET4,
    STR_ID_SETTING_AUDIO_REVERB_EFFECT_SET5,
    STR_ID_SETTING_AUDIO_REVERB_EFFECT_SET6,
    STR_ID_SETTING_AUDIO_SURROUND_EFFECT,
    STR_ID_SETTING_AUDIO_SURROUND_PLUG_EAPHONE,
    STR_ID_SETTING_AUDIO_SURROUND_MODE1,
    STR_ID_SETTING_AUDIO_SURROUND_MODE2,
    STR_ID_SETTING_AUDIO_EFFECT_NO_COEXIST,
    STR_MENU_INPUT_METHOD,
    STR_INPUT_METHOD_MULTITAP_U_ABC,
    STR_INPUT_METHOD_MULTITAP_L_ABC,
    STR_INPUT_METHOD_SMART_U_ABC,
    STR_INPUT_METHOD_SMART_L_ABC,
    STR_INPUT_METHOD_SMART_FIRST_U_ABC,
    STR_INPUT_METHOD_NUMERIC,
    STR_INPUT_METHOD_MULTITAP_BPMF,
    STR_INPUT_METHOD_BPMF,
    STR_INPUT_METHOD_TR_STROKE,
    STR_INPUT_METHOD_MULTITAP_PINYIN,
    STR_INPUT_METHOD_PINYIN,
    STR_INPUT_METHOD_SM_STROKE,
    STR_INPUT_METHOD_MULTITAP_U_SPANISH,
    STR_INPUT_METHOD_MULTITAP_L_SPANISH,
    STR_INPUT_METHOD_SMART_U_SPANISH,
    STR_INPUT_METHOD_SMART_L_SPANISH,
    STR_INPUT_METHOD_MULTITAP_U_DANISH,
    STR_INPUT_METHOD_MULTITAP_L_DANISH,
    STR_INPUT_METHOD_SMART_U_DANISH,
    STR_INPUT_METHOD_SMART_L_DANISH,
    STR_INPUT_METHOD_MULTITAP_U_POLISH,
    STR_INPUT_METHOD_MULTITAP_L_POLISH,
    STR_INPUT_METHOD_SMART_U_POLISH,
    STR_INPUT_METHOD_SMART_L_POLISH,
    STR_INPUT_METHOD_MULTITAP_U_FRENCH,
    STR_INPUT_METHOD_MULTITAP_L_FRENCH,
    STR_INPUT_METHOD_SMART_U_FRENCH,
    STR_INPUT_METHOD_SMART_L_FRENCH,
    STR_INPUT_METHOD_MULTITAP_U_GERMAN,
    STR_INPUT_METHOD_MULTITAP_L_GERMAN,
    STR_INPUT_METHOD_SMART_U_GERMAN,
    STR_INPUT_METHOD_SMART_L_GERMAN,
    STR_INPUT_METHOD_MULTITAP_U_ITALIAN,
    STR_INPUT_METHOD_MULTITAP_L_ITALIAN,
    STR_INPUT_METHOD_SMART_U_ITALIAN,
    STR_INPUT_METHOD_SMART_L_ITALIAN,
    STR_INPUT_METHOD_MULTITAP_U_RUSSIAN,
    STR_INPUT_METHOD_MULTITAP_L_RUSSIAN,
    STR_INPUT_METHOD_SMART_U_RUSSIAN,
    STR_INPUT_METHOD_SMART_L_RUSSIAN,
    STR_INPUT_METHOD_MULTITAP_U_BULGARIAN,
    STR_INPUT_METHOD_MULTITAP_L_BULGARIAN,
    STR_INPUT_METHOD_SMART_U_BULGARIAN,
    STR_INPUT_METHOD_SMART_L_BULGARIAN,
    STR_INPUT_METHOD_MULTITAP_U_UKRAINIAN,
    STR_INPUT_METHOD_MULTITAP_L_UKRAINIAN,
    STR_INPUT_METHOD_SMART_U_UKRAINIAN,
    STR_INPUT_METHOD_SMART_L_UKRAINIAN,
    STR_INPUT_METHOD_MULTITAP_U_TURKISH,
    STR_INPUT_METHOD_MULTITAP_L_TURKISH,
    STR_INPUT_METHOD_SMART_U_TURKISH,
    STR_INPUT_METHOD_SMART_L_TURKISH,
    STR_INPUT_METHOD_MULTITAP_U_PORTUGUESE,
    STR_INPUT_METHOD_MULTITAP_L_PORTUGUESE,
    STR_INPUT_METHOD_SMART_U_PORTUGUESE,
    STR_INPUT_METHOD_SMART_L_PORTUGUESE,
    STR_INPUT_METHOD_MULTITAP_U_INDONESIAN,
    STR_INPUT_METHOD_MULTITAP_L_INDONESIAN,
    STR_INPUT_METHOD_SMART_U_INDONESIAN,
    STR_INPUT_METHOD_SMART_L_INDONESIAN,
    STR_INPUT_METHOD_MULTITAP_U_CZECH,
    STR_INPUT_METHOD_MULTITAP_L_CZECH,
    STR_INPUT_METHOD_SMART_U_CZECH,
    STR_INPUT_METHOD_SMART_L_CZECH,
    STR_INPUT_METHOD_MULTITAP_U_MALAY,
    STR_INPUT_METHOD_MULTITAP_L_MALAY,
    STR_INPUT_METHOD_SMART_U_MALAY,
    STR_INPUT_METHOD_SMART_L_MALAY,
    STR_INPUT_METHOD_MULTITAP_U_VIETNAMESE,
    STR_INPUT_METHOD_MULTITAP_L_VIETNAMESE,
    STR_INPUT_METHOD_SMART_U_VIETNAMESE,
    STR_INPUT_METHOD_SMART_L_VIETNAMESE,
    STR_INPUT_METHOD_MULTITAP_THAI,
    STR_INPUT_METHOD_SMART_THAI,
    #if defined(__MMI_ZI_HINDI__) || defined(__MMI_T9_HINDI__)
    STR_INPUT_METHOD_SMART_HINDI,
    #endif
    #if defined (__MMI_MULTITAP_ARABIC__)
    STR_INPUT_METHOD_MULTITAP_ARABIC,
    #endif
    #if defined(__MMI_LANG_ARABIC__)
    STR_INPUT_METHOD_ARABIC_NUMERIC,
    #endif
    #if defined(__MMI_ZI_ARABIC__) || defined(__MMI_T9_ARABIC__)
    STR_INPUT_METHOD_SMART_ARABIC,
	#endif
    STR_INPUT_METHOD_MULTITAP_PERSIAN,
    STR_INPUT_METHOD_SMART_PERSIAN,
#if defined (__MMI_MULTITAP_URDU__)
    STR_INPUT_METHOD_MULTITAP_URDU,
#endif
#if defined(__MMI_ZI_URDU__) 
    STR_INPUT_METHOD_SMART_URDU,
#endif
    STR_INPUT_METHOD_MULTITAP_HEBREW,
    STR_INPUT_METHOD_SMART_HEBREW,
	#if defined (__MMI_MULTITAP_HINDI__)
    STR_INPUT_METHOD_MULTITAP_HINDI,
	#endif
    STR_INPUT_METHOD_MULTITAP_U_FINNISH,
    STR_INPUT_METHOD_MULTITAP_L_FINNISH,
    STR_INPUT_METHOD_SMART_U_FINNISH,
    STR_INPUT_METHOD_SMART_L_FINNISH,
    STR_INPUT_METHOD_MULTITAP_U_HUNGARIAN,
    STR_INPUT_METHOD_MULTITAP_L_HUNGARIAN,
    STR_INPUT_METHOD_SMART_U_HUNGARIAN,
    STR_INPUT_METHOD_SMART_L_HUNGARIAN,
    STR_INPUT_METHOD_MULTITAP_U_SLOVAK,
    STR_INPUT_METHOD_MULTITAP_L_SLOVAK,
    STR_INPUT_METHOD_SMART_U_SLOVAK,
    STR_INPUT_METHOD_SMART_L_SLOVAK,
    STR_INPUT_METHOD_MULTITAP_U_DUTCH,
    STR_INPUT_METHOD_MULTITAP_L_DUTCH,
    STR_INPUT_METHOD_SMART_U_DUTCH,
    STR_INPUT_METHOD_SMART_L_DUTCH,
    STR_INPUT_METHOD_MULTITAP_U_NORWEGIAN,
    STR_INPUT_METHOD_MULTITAP_L_NORWEGIAN,
    STR_INPUT_METHOD_SMART_U_NORWEGIAN,
    STR_INPUT_METHOD_SMART_L_NORWEGIAN,
    STR_INPUT_METHOD_MULTITAP_U_SWEDISH,
    STR_INPUT_METHOD_MULTITAP_L_SWEDISH,
    STR_INPUT_METHOD_SMART_U_SWEDISH,
    STR_INPUT_METHOD_SMART_L_SWEDISH,
    STR_INPUT_METHOD_MULTITAP_U_CROATIAN,
    STR_INPUT_METHOD_MULTITAP_L_CROATIAN,
    STR_INPUT_METHOD_SMART_U_CROATIAN,
    STR_INPUT_METHOD_SMART_L_CROATIAN,
    STR_INPUT_METHOD_MULTITAP_U_ROMANIAN,
    STR_INPUT_METHOD_MULTITAP_L_ROMANIAN,
    STR_INPUT_METHOD_SMART_U_ROMANIAN,
    STR_INPUT_METHOD_SMART_L_ROMANIAN,
    STR_INPUT_METHOD_MULTITAP_U_SLOVENIAN,
    STR_INPUT_METHOD_MULTITAP_L_SLOVENIAN,
    STR_INPUT_METHOD_SMART_U_SLOVENIAN,
    STR_INPUT_METHOD_SMART_L_SLOVENIAN,
    STR_INPUT_METHOD_MULTITAP_U_GREEK,
    STR_INPUT_METHOD_MULTITAP_L_GREEK,
    STR_INPUT_METHOD_SMART_U_GREEK,
    STR_INPUT_METHOD_SMART_L_GREEK,

#ifdef __MMI_CHANGABLE_FONT__
    STR_ID_PHNSET_FONT_SIZE,
    STR_ID_PHNSET_FONT_SIZE_THEME_DEFAULT,
    STR_ID_PHNSET_FONT_SIZE_SMALL,
    STR_ID_PHNSET_FONT_SIZE_MEDIUM,
    STR_ID_PHNSET_FONT_SIZE_LARGE,
#endif /* __MMI_CHANGABLE_FONT__ */ 
    STR_ID_PHNSET_GPIO_SETTING,
    STR_ID_PHNSET_GPIO_LED,
    STR_ID_PHNSET_GPIO_BACKLITE,
    STR_ID_PHNSET_GPIO_BACKLITE_LEVEL,
    STR_ID_PHNSET_GPIO_BACKLITE_HF_TIME,
    STR_ID_PHNSET_GPIO_COVER_CLOSE,
    STR_ID_PHNSET_GPIO_COVER_CLOSE_BACK_TO_IDLE,
    STR_ID_PHNSET_GPIO_COVER_CLOSE_REJECT_CALL,
    STR_ID_PHNSET_GPIO_COVER_CLOSE_KEYPAD_LOCK,
    //STR_ID_PHNSET_GPIO_SUCCESS,

	#if defined (__MMI_MULTITAP_MARATHI__)
    STR_INPUT_METHOD_MULTITAP_MARATHI,
	#endif
#if defined(__MMI_ZI_MARATHI__) 
    STR_INPUT_METHOD_SMART_MARATHI,
#endif
#if defined (__MMI_MULTITAP_TAMIL__)
	STR_INPUT_METHOD_MULTITAP_TAMIL,
#endif
#if defined(__MMI_ZI_TAMIL__) 
    STR_INPUT_METHOD_SMART_TAMIL,
#endif
#if defined (__MMI_MULTITAP_BENGALI__)
	STR_INPUT_METHOD_MULTITAP_BENGALI,
#endif
#if defined(__MMI_ZI_BENGALI__) 
    STR_INPUT_METHOD_SMART_BENGALI,
#endif
#if defined (__MMI_LANG_PUNJABI__)
	STR_INPUT_METHOD_MULTITAP_PUNJABI,
#endif
#if defined(__MMI_ZI_PUNJABI__) 
    STR_INPUT_METHOD_SMART_PUNJABI,
#endif
#if defined (__MMI_LANG_TELUGU__)
    STR_INPUT_METHOD_MULTITAP_TELUGU,
#endif
#if defined(__MMI_ZI_TELUGU__) 
    STR_INPUT_METHOD_SMART_TELUGU,
#endif
#if defined(__MMI_PREFER_WRITING_LANG__) || defined(__MMI_MIXED_LANG_SUPPORT__)
    STR_ID_PHNSET_PREFERED_WRITING_LANG,
#if defined(__MMI_MIXED_LANG_SUPPORT__)
    STR_ID_PHNSET_PREFERED_WRITING_LANG_MAIN,
    STR_ID_PHNSET_PREFERED_WRITING_LANG_SUB,
#endif /* defined(__MMI_MIXED_LANG_SUPPORT__) */
#endif /* defined(__MMI_PREFER_WRITING_LANG__) */

    STR_ID_SETTING_END
} STR_ID_SETTING_ENUM;

typedef enum
{
    STR_MENU9102_INITIAL_SETUP = PHONE_SETUP_BASE,
    /* add new string ID below this line */
    
    STR_DISP_SETUP,
    STR_MENU9141_TIME_AND_DATE,
    STR_SETTIME_UNFINISHED,
    STR_MENU9142_SETHOMECITY,
    STR_ID_PHNSET_SET_DT,
    /* __MMI_SEPARATE_DT_SETTING__ */
    STR_ID_PHNSET_SET_DATEANDFORMAT,
    STR_ID_PHNSET_SET_TIMEANDFORMAT,
    /* __MMI_SEPARATE_DT_SETTING__ */
    STR_ID_PHNSET_SET_DST,
    STR_MENU9144_SETTIMEANDDATEFORMAT,
    STR_ENTER_TIME_FORMAT_DISP_CAPTION,
    STR_ENTER_DATE_FORMAT_DISP_CAPTION,
    STR_TIME_FORMAT_CAPTION,
    STR_DATE_FORMAT_CAPTION,
    STR_DATE_TIME_SET_FORMAT_CAPTION,
    STR_SCR_SPEED_DIAL_MAIN_CAPTION,
    STR_SCR_SPEED_DIAL_LIST_CAPTION,
    STR_SPEEDDIAL_NO_NUM_TODIAL_TEXT,
    STR_DD_MMM_YYYY_H,
    STR_DD_MM_YYYY_S,
    STR_MM_DD_YYYY_S,
    STR_YYYY_MM_DD_S,
    STR_YYYY_MM_DD_H,
    STR_MMM_DD_YYYY,
    STR_MENU9146_WELCOME_TEXT,
    STR_SCR9051_24HOURS_CAPTION,
    STR_SCR9051_24HOURS_MESSAGE,
    STR_SCR_WELCOME_LSK,
    STR_SCR_WELCOME_RSK,
    STR_MENU_SETTING_AUTO_UPDATE_DT_TIME,
    STR_MENU_SETTING_SPEED_DIAL,
    STR_MENU_SETTING_CONTRAST_LEVEL,
#if defined(__MMI_NITZ__)
    STR_MENU_SETTING_MENU_TREE,
#endif 
    STR_MENU_SETTING_SCHEDULE_POWER,
    STR_MENU_SETTING_SCHEDULE_POWER_SET1,
    STR_MENU_SETTING_SCHEDULE_POWER_SET2,
    STR_MENU_SETTING_SCH_POW_SET1_POW_ON,
    STR_MENU_SETTING_SCH_POW_SET1_POW_OFF,
    STR_OWN_NO,
    /* Lisen 0921-1 */
#if defined(__MMI_OPERATOR_NAME_MENU__)
    STR_OPN,
#endif 
    STR_MAINMENU_STYLE,
    STR_MAINMENU_STYLE_MATRIX,
    STR_MAINMENU_STYLE_PAGE,
    STR_MAINMENU_STYLE_CIRCULAR,
    STR_MAINMENU_STYLE_ROTATE,
    STR_MAINMENU_STYLE_LIST,
    /* PMT NEERAJ START 20050616 */
    STR_MAINMENU_STYLE_TAB,
    /* PMT NEERAJ END 20050616 */
    STR_IDLE_SCR_DISP,
    STR_SPEED_DIAL_STATUS,
    STR_SPEED_DIAL_LIST,
    STR_EDIT,
    STR_DONE,
    STR_SETTING_WALLPAPER,
    STR_SETTING_WALLPAPER_SUB,
    STR_MENU_SETTING_SCREEN_SVR,
    STR_SETTING_POWER_ON_DISPLAY,   /* "Power On Display" */
    STR_SETTING_POWER_OFF_DISPLAY,  /* "Power Off Display" */
    STR_SETTING_SHOW_DT_TIME,
    STR_SETTING_SPEED_STATUS,
    STR_SETTING_MAIN_LCD,
    STR_SETTING_SUB_LCD,
    STR_MENU9146_ON,
    STR_MENU9146_OFF,
#if defined(__MMI_DEDICATED_KEY_SHORTCUTS__)
    STR_DEDICATED_KEY,
    STR_DEDICATED_UP_KEY,
    STR_DEDICATED_DOWN,
    STR_DEDICATED_LEFT,
    STR_DEDICATED_RIGHT,
#endif /* defined(__MMI_DEDICATED_KEY_SHORTCUTS__) */ 
#if defined(__MMI_SET_DEF_ENCODING_TYPE__)
    STR_DEF_ENCODING_TYPE_TITLE,
    STR_DEF_ENCODING_TYPE_BIG5,
    STR_DEF_ENCODING_TYPE_GB2312,
    STR_DEF_ENCODING_TYPE_GB18030,
    STR_DEF_ENCODING_TYPE_UCS2,
#endif /* defined(__MMI_SET_DEF_ENCODING_TYPE__) */ 

#if defined(__MMI_TOUCH_SCREEN__) || defined(__MMI_HANDWRITING_PAD__)
    STR_HANDWRITING_SETTING,
    STR_CALIBRATION_SETTING,
    STR_HANDWRITING_PEN_SPEED,
    STR_HANDWRITING_PEN_COLOR,
    STR_HANDWRITING_FAST,           /* Don't change the order of these three strings */
    STR_HANDWRITING_MEDIUM,
    STR_HANDWRITING_SLOW,
    STR_CALIBRATION_WELCOME_TEXT,
    STR_CALIBRATION_TOP_LEFT_TEXT,  /* Don't change the order of these three strings */
    STR_CALIBRATION_BOTTOM_RIGHT_TEXT,
    STR_CALIBRATION_CENTER_TEXT,

#ifdef __MMI_HANDWRITING_PAD__
    STR_TEST_CONTROL_AREA_WELCOME_TEXT,
#endif 

#endif /* defined(__MMI_TOUCH_SCREEN__) || defined(__MMI_HANDWRITING_PAD__) */ 

#ifdef __MMI_TVOUT__
    STR_ID_SETTING_TVOUT,
    STR_ID_SETTING_TVOUT_SETTING,
    STR_ID_SETTING_TVOUT_FORMAT,
    STR_ID_SETTING_TVOUT_FORMAT_PAL,
    STR_ID_SETTING_TVOUT_FORMAT_NTSC,
    STR_ID_SETTING_TVOUT_FORMAT_PALM,
    STR_ID_SETTING_TVOUT_FORMAT_PALC,
    STR_ID_SETTING_TVOUT_AUD_PATH,
    STR_ID_SETTING_TVOUT_AUD_PATH_BOTH,
    STR_ID_SETTING_TVOUT_AUD_PATH_TV,
    STR_ID_SETTING_TVOUT_ADJUST,
    STR_ID_SETTING_TVOUT_ADJUST_Y_GAMMA,
    STR_ID_SETTING_TVOUT_ADJUST_U,
    STR_ID_SETTING_TVOUT_ADJUST_V,
    STR_ID_SETTING_TVOUT_PLUG_IN,
    STR_ID_SETTING_TVOUT_PLUG_OUT,
    STR_ID_SETTING_TVOUT_NOT_READY,
#endif /* __MMI_TVOUT__ */ 

    STR_24,
    STR_12,

    /* Cylen 0926, customize display char */
    /* Wallpaper */
    STR_WALLPAPER_CAPTION,
    STR_WALLPAPER_FIX,
    STR_WALLPAPER_ROTATE,
    STR_WALLPAPER_SYSTEM,
    STR_WALLPAPER_DOWNLOAD,
    STR_ID_PHNSET_WP_AVATAR,
    STR_WALLPAPER_SELECT_CAPTION,
    STR_IDLE_WP_DECODE_ERR,
#if defined(__MMI_UI_TECHNO_IDLESCREEN_BAR__)
    STR_ID_IDLE_CLOCK_TYPE,
#endif 
    STR_ID_DISPCHAR_THEME_WALLPAPER,
#ifdef __MMI_THEMES_V2_SUPPORT__
    STR_ID_DISPCHAR_THEME_SCREENSAVER,
#endif 
    /* Screensaver */
    STR_SCR_SCREENSAVER_CAPTION,
    STR_SCR_SCREENSAVER_SETTINGS,
    SCR_SCREENSAVER_SETTING_CAPTION,
    STR_SCR_SCREENSAVER_SYSTEM,
    STR_SCR_SCREENSAVER_DOWNLOAD,
    STR_ID_PHNSET_SS_AVATAR,
    STR_SCREENSAVER_EMPTY,
    STR_SCREENSAVER_5SEC,
    STR_SCREENSAVER_15SEC,
    STR_SCREENSAVER_30SEC,
    STR_SCREENSAVER_1MINUTE,
    STR_SCREENSAVER_STATUS,
    STR_SCREENSAVER_WAITING,
    STR_IDLE_SS_DECODE_ERR,
    STR_ID_WP_FRAME_ERR,
    STR_SCREENSAVER_DISPLAY_TIME,
    /* Power on/off display */
    //STR_ID_PHNSET_ON_OFF_CAPTION,
    STR_ID_PHNSET_ON_OFF_SYSTEM,
    STR_ID_PHNSET_ON_OFF_DOWNLOAD,
    STR_ID_PHNSET_ON_OFF_AVATAR,
    //STR_ID_PHNSET_ON_OFF_BAD_FILE,
    STR_ID_PHNSET_ON_OFF_SELECT_CAPTION,
    /* IMAGE Strings */
    STR_ID_PHNSET_DISPCHAR_INVALID_PATH,
    STR_ID_PHNSET_DISPCHAR_IMGID_START,
    STR_ID_PHNSET_DISPCHAR_IMGID_0 = STR_ID_PHNSET_DISPCHAR_IMGID_START,
    STR_ID_PHNSET_DISPCHAR_IMGID_1,
    STR_ID_PHNSET_DISPCHAR_IMGID_2,
    STR_ID_PHNSET_DISPCHAR_IMGID_3,
    STR_ID_PHNSET_DISPCHAR_IMGID_4,
    STR_ID_PHNSET_DISPCHAR_IMGID_5,
    STR_ID_PHNSET_DISPCHAR_IMGID_6,
    STR_ID_PHNSET_DISPCHAR_IMGID_7,
    STR_ID_PHNSET_DISPCHAR_IMGID_8,
    STR_ID_PHNSET_DISPCHAR_IMGID_9,
    STR_ID_PHNSET_DISPCHAR_IMGID_10,
    STR_ID_PHNSET_DISPCHAR_IMGID_11,
    STR_ID_PHNSET_DISPCHAR_IMGID_12,
    STR_ID_PHNSET_DISPCHAR_IMGID_13,
    STR_ID_PHNSET_DISPCHAR_IMGID_14,
    STR_ID_PHNSET_DISPCHAR_IMGID_15,
    STR_ID_PHNSET_DISPCHAR_IMGID,
    /* ANIMATION IDs */
    STR_ID_PHNSET_DISPCHAR_ANMID_START,
    STR_ID_PHNSET_DISPCHAR_ANMID_0 = STR_ID_PHNSET_DISPCHAR_ANMID_START,
    STR_ID_PHNSET_DISPCHAR_ANMID_1,
    STR_ID_PHNSET_DISPCHAR_ANMID_2,
    STR_ID_PHNSET_DISPCHAR_ANMID_3,
    STR_ID_PHNSET_DISPCHAR_ANMID_4,
    STR_ID_PHNSET_DISPCHAR_ANMID_5,
    STR_ID_PHNSET_DISPCHAR_ANMID_6,
    STR_ID_PHNSET_DISPCHAR_ANMID_7,
    STR_ID_PHNSET_DISPCHAR_ANMID_8,
    STR_ID_PHNSET_DISPCHAR_ANMID_9,
    STR_ID_PHNSET_DISPCHAR_ANMID_10,
    STR_ID_PHNSET_DISPCHAR_ANMID_11,
    STR_ID_PHNSET_DISPCHAR_ANMID_12,
    STR_ID_PHNSET_DISPCHAR_ANMID_13,
    STR_ID_PHNSET_DISPCHAR_ANMID_14,
    STR_ID_PHNSET_DISPCHAR_ANMID_15,
    STR_ID_PHNSET_DISPCHAR_ANMID,
    /* VIDEO IDs */
    STR_ID_PHNSET_DISPCHAR_VDOID_START,
    STR_ID_PHNSET_DISPCHAR_VDOID_0 = STR_ID_PHNSET_DISPCHAR_VDOID_START,
    STR_ID_PHNSET_DISPCHAR_VDOID_1,
    STR_ID_PHNSET_DISPCHAR_VDOID_2,
    STR_ID_PHNSET_DISPCHAR_VDOID_3,
    STR_ID_PHNSET_DISPCHAR_VDOID_4,
    STR_ID_PHNSET_DISPCHAR_VDOID_5,
    STR_ID_PHNSET_DISPCHAR_VDOID_6,
    STR_ID_PHNSET_DISPCHAR_VDOID_7,
    STR_ID_PHNSET_DISPCHAR_VDOID_8,
    STR_ID_PHNSET_DISPCHAR_VDOID_9,
    STR_ID_PHNSET_DISPCHAR_VDOID_10,
    STR_ID_PHNSET_DISPCHAR_VDOID_11,
    STR_ID_PHNSET_DISPCHAR_VDOID_12,
    STR_ID_PHNSET_DISPCHAR_VDOID_13,
    STR_ID_PHNSET_DISPCHAR_VDOID_14,
    STR_ID_PHNSET_DISPCHAR_VDOID_15,
    STR_ID_PHNSET_DISPCHAR_VDOID,

    STR_ID_PHNSET_DISPCHAR_ANALOG,
    STR_ID_PHNSET_DISPCHAR_DIGITAL,
    STR_ID_DISPCHAR_SWFLASH_START,
    STR_ID_DISPCHAR_SWFLASH_0 = STR_ID_DISPCHAR_SWFLASH_START,
    STR_ID_DISPCHAR_SWFLASH_1,
    STR_ID_DISPCHAR_SWFLASHID,
    
    STR_ID_PHNSET_DISPCHAR_MAX,

	STR_ID_PHNSET_UART_SETUP_TITLE,
	STR_ID_PHNSET_UART_REBOOT,
	STR_ID_PHNSET_UART_SETUP_REBOOT_PROCESSING,
    STRING_MTPNP_UART_SIM1,
    STRING_MTPNP_UART_SIM2,
    STR_ID_SETTING_SAVE_ASK,
    STR_ID_SETTING_DELETE_ASK,
    STR_ID_SETTING_SAVING,
    STR_ID_SETTING_DELETING,

    /* add new string ID above this line */
    STR_ID_PHNSET_END
} STR_ID_PHNSET_ENUM;

typedef enum 
{
	  STR_MENU9101_SECURITY = SECURITY_SETUP_BASE,
	  /* add new string ID below this line */
	  
    STR_SCR8079_BDL_VIEW_LIST_CAPTION,
    STR_PASS_TRIALS_REMAIN,
    STR_FDL_NOT_READY,
    STR_BDL_NOT_READY,
    STR_FDL_IS_ON,
    STR_FDL_IS_OFF,
    STR_BDL_IS_ON,
    STR_BDL_IS_OFF,
    STR_SETTING_STORAGE_FULL,
    STR_SETTING_CODE_VERIFIED,
    STR_SETTING_PIN_BLK,
    STR_SETTING_PIN2_BLK,
    STR_SETTING_PIN2_BLK2,
    STR_INVALID_PINPUKPLOCK_LENGTH,
    STR_SETTING_SOS,
    STR_SETTING_SIM_LOCK,
    STR_SETTING_SIM_UNLOCK,
    STR_SETTING_PHONE_LOCK,
    STR_SETTING_PHONE_UNLOCK,
    STR_SETTING_OLD_PIN,
    STR_SETTING_NEW_PIN,
    STR_SETTING_OLD_PIN2,
    STR_SETTING_NEW_PIN2,
    STR_DIFF_PIN,
    STR_DIFF_PIN2,
    STR_DIFF_PHONE,
    STR_WRONG_PIN,
    STR_PIN_CHANGE,
    STR_WRONG_PIN2,
    STR_PIN2_CHANGE,
    STR_WRONG_PHONE,
    STR_PHONE_CHANGE,
    STR_SETTING_ENTER_PUK2,
    STR_SETTING_ENTER_NEW_PIN2,
    STR_SETTING_WRONG_PUK2,
    STR_SETTING_WRONG_PUK,
    STR_SETTING_PIN2_BLOCK_TITLE,
    STR_SETTING_PIN2_BLOCK_MSG,
    STR_NEW_PIN1,
    STR_ENABLE_PIN,
    STR_SETTING_PUK,
    STR_SETTING_FDL_MODE,
    STR_SETTING_FDL_LIST,
    STR_NO_FDL,
    STR_SETTING_BDL_MODE,
    STR_SETTING_BDL_LIST,
    STR_SETTING_FDL_NAME,
    STR_SETTING_FDL_NUMBER,
    STR_SETTING_FDL_EDIT_ENTRY,
    STR_MENU_RESTORE,
    STR_SCR8054_CALL_FDL_CAPTION,
    STR_MENU9165_PHONE_LOCK,
#ifdef __MMI_AUTO_KEYPAD_LOCK__
    STR_MENU9166_AUTO_KEYPAD_LOCK,
#endif 
    STR_MENU9167_FIXED_DIAL,
    STR_MENU9168_BARRED_DAIL,
    STR_MENU9169_SIM_LOCK,
    STR_MENU9170_CHANGE_PASSWORD,
    STR_MENU9173_CP_PHONE_LOCK,
    STR_MENU9174_CP_PIN1,
    STR_MENU9175_CP_PIN2,
    STR_ID_CERTIFICATE_MANAGER,
#ifdef __MMI_AUTO_KEYPAD_LOCK__
    STR_MENU9177_AKPL_OFF,
    STR9178_AKPL_TIME_5,
    STR9178_AKPL_TIME_30,
    STR9178_AKPL_TIME_60,
    STR9178_AKPL_TIME_2,
#endif /* __MMI_AUTO_KEYPAD_LOCK__ */ 
    STR_SCR9002_SECURITY_CAPTION,
    STR_SCR9026_CHANGE_PASSWORD_CAPTION,
    STR_SCR9027_PIN2_CAPTION,
    STR_SCR9029_CURRENT_PW_CAPTION,
    STR_SCR9030_NEW_PW_CAPTION,
    STR_SCR9031_CONFIRM_PW_CAPTION,
    STR_SCR9028_PIN1_CAPTION,
    STR_ID_PIN_NOT_SUPPORT,
    STR_ID_PIN2_NOT_SUPPORT,
    STR_ID_SECSET_UNSPECIFIED_ERROR,
    STR_ID_SECSET_DELETE_ASK,
    STR_ID_SECSET_SAVE_ASK,
    
    /* add new string ID above this line */
    STR_ID_SETTINGS_SECURITY_SETUP_END
} STR_ID_SETTINGS_SECURITY_SETUP_ENUM;

typedef enum 
{
    STR_MENU_LANGUAGE = LANG_SETTINGS_BASE,
    /* add new string ID below this line */
    
    STR_LANGUAGESCR_AUTO,
    
    /* add new string ID above this line */
    STR_ID_SETTING_LANGUAGE_END
} STR_ID_SETTING_LANGUAGE_ENUM;

/* diamond, 2005/07/05 Flight mode */
typedef enum 
{
    STR_MENU_FLIGHT_MODE = FLIGHT_MODE_BASE,    /* menu text */
    /* add new string ID below this line */
    
    STR_FLIGHT_MODE_NORMAL,                         /* selection text */
    STR_FLIGHT_MODE_SILENT,                         /* selection text */
    STR_FLIGHT_MODE_QUERY,                          /* selection text */
    STR_FLIGHT_MODE_CONFIRM,                        /* confirmation text */
    STR_FLIGHT_MODE_PROGRESS,                        /* progressing text */
    
    /* add new string ID above this line */
    STR_ID_FLIGHT_MODE_END
} STR_ID_FLIGHT_MODE_ENUM;
/* end, diamond */

typedef enum 
{
    IMG_MENU9140_AUTO_REDIAL = SETTINGS_BASE,
    /* add new image ID below this line */
    
    IMG_SCR9001_CALL_SETTING_CAPTION,
    IMG_SCR9001_CALL_SETTING_LSK,
    IMG_SCR9001_CALL_SETTING_RSK,
    IMG_SCR9033_AUTO_REDIAL_CAPTION,
    IMG_SCR9033_AUTO_REDIAL_LSK,
    IMG_SCR9033_AUTO_REDIAL_RSK,
    IMG104_SCR8054_LSK,
    IMG_SCR8055_SERVICE_OFF,
    IMG_SETTING_CALL_SETUP,
    IMG_SETTING_SECURITY,
    IMG_SETTING_NETWORK,
    IMG_SETTING_STORE,
    IMG_SCR_SETTING_CAPTION,
    IMG_SETTING_BARRED_DIAL,
    IMG_SETTING_FIXED_DIAL,
#ifdef __MMI_SOUND_EFFECT__
    IMG_ID_SETTING_SOUND_EFFECT,
    IMG_ID_SETTING_AUDIO_EQUALIZER,
    IMG_ID_SETTING_AUDIO_REVERB_EFFECT,
    IMG_ID_SETTING_AUDIO_SURROUND_EFFECT,
#endif /* __MMI_SOUND_EFFECT__ */ 
#ifndef __MMI_SUBLCD__
    IMG_CONTRAST_BACKGROUND,
#endif 
    IMG_GROUPLIST_NO_IMAGE,
    IMG_SETTING_SHORTCUT,
    
    /* add new image ID above this line */
    IMG_ID_SETTING_END
} IMG_ID_SETTING_ENUM;

typedef enum 
{
    IMG_MENU9102_INITIAL_SETUP = PHONE_SETUP_BASE,
    /* add new image ID below this line */
    
    IMG_SETTING_DISP,
    IMG_MENU9141_TIME_AND_DATE,
    IMG_MENU9142_SETTIME,
    IMG_MENU9143_SETTIMEFORMAT,
    IMG_MENU9144_SETDATE,
    IMG_MENU9145_SETDATEFORMAT,
    IMG_MENU9151_24HOURS,
    IMG_MENU9152_AM_PM,
    IMG_MENU9161_DATE_MONTH,
    IMG_MENU9162_DATE_MONTH_YEAR,
    IMG_MENU9163_MONTH_DATE_YEAR,
    IMG_MENU9164_DATE_MONTH_YEAR2,
    IMG_SCR9003_INITIALSETUP_CAPTION,
    IMG_SCR9003_INITIALSETUP_LSK,
    IMG_SCR9003_INITIALSETUP_RSK,
    IMG_SCR9041_TIMEANDDATE_CAPTION,
    IMG_SCR9041_TIMEANDDATE_LSK,
    IMG_SCR9041_TIMEANDDATE_RSK,
    IMG_SCR9042_SETTIME_CAPTION,
    IMG_SCR9042_SETTIME_LSK,
    IMG_SCR9042_SETTIME_RSK,
    IMG_SCR9043_SETTIMEFORMAT_CAPTION,
    IMG_SCR9043_SETTIMEFORMAT_LSK,
    IMG_SCR9043_SETTIMEFORMAT_RSK,
    IMG_SCR9044_SETDATE_CAPTION,
    IMG_SCR9044_SETDATE_LSK,
    IMG_SCR9044_SETDATE_RSK,
    IMG_SCR9045_SETDATEFORMAT_CAPTION,
    IMG_SCR9045_SETDATEFORMAT_LSK,
    IMG_SCR9045_SETDATEFORMAT_RSK,
    IMG_SCR9051_24HOURS_CAPTION,
    IMG_SCR9051_24HOURS_LSK,
    IMG_SCR9051_24HOURS_RSK,
    IMG_SCR9051_24HOURS_MESSAGE,
    IMG_SCR9052_AM_PM_CAPTION,
    IMG_SCR9052_AM_PM_LSK,
    IMG_SCR9052_AM_PM_RSK,
    IMG_SCR9052_AM_PM_MESSAGE,
    IMG_SCR9061_DATE_MONTH_CAPTION,
    IMG_SCR9061_DATE_MONTH_LSK,
    IMG_SCR9061_DATE_MONTH_RSK,
    IMG_SCR9061_DATE_MONTH_MESSAGE,
    IMG_SCR9062_DATE_MONTH_YEAR_CAPTION,
    IMG_SCR9062_DATE_MONTH_YEAR_LSK,
    IMG_SCR9062_DATE_MONTH_YEAR_RSK,
    IMG_SCR9062_DATE_MONTH_YEAR_MESSAGE,
    IMG_SCR9063_MONTH_DATE_YEAR_CAPTION,
    IMG_SCR9063_MONTH_DATE_YEAR_LSK,
    IMG_SCR9063_MONTH_DATE_YEAR_RSK,
    IMG_SCR9063_MONTH_DATE_YEAR_MESSAGE,
    IMG_SCR9064_DATE_MONTH_YEAR2_CAPTION,
    IMG_SCR9064_DATE_MONTH_YEAR2_LSK,
    IMG_SCR9064_DATE_MONTH_YEAR2_RSK,
    IMG_SCR9064_DATE_MONTH_YEAR2_MESSAGE,
    IMG_SETTING_PHONE,
    IMG_TIME_AND_DATE_BLANK,
    IMG_DATE_TIME_SET_FORMAT_CAPTION,
    IMG_MENU9142_SETHOMECITY,

#if defined(__MMI_TOUCH_SCREEN__) || defined(__MMI_HANDWRITING_PAD__)
    IMG_CALIBRATION_MENU_ICON,
    IMG_CALIBRATION_TOP_LEFT,   /* Don't change the order of these three images */
    IMG_CALIBRAION_BOTTOM_RIGHT,
    IMG_CALIBRATION_CENTER,
#endif /* defined(__MMI_TOUCH_SCREEN__) || defined(__MMI_HANDWRITING_PAD__) */ 
    IMG_SETTING_GREET_TEXT,
    IMG_SETTING_GREET_STATUS,

#ifdef __MMI_TVOUT__
    IMG_ID_POPUP_TVOUT,
#endif 

    /* add new image ID above this line */
    IMG_ID_PNONE_SETUP_END
} IMG_ID_PHONE_SETUP_ENUM;

typedef enum 
{
    IMG_MENU_LANGUAGE = LANG_SETTINGS_BASE,
    /* add new image ID below this line */
    
    /* add new image ID above this line */
    IMG_ID_SETTING_LANGUAGE_END
} IMG_ID_SETTING_LANGUAGE_ENUM;

/* diamond, 2005/07/05 Flight mode */
typedef enum 
{
    IMG_MENU_FLIGHT_MODE = FLIGHT_MODE_BASE,
    /* add new image ID below this line */
    
    IMG_FLIGHT_MODE_PROGRESS,

    /* add new image ID above this line */
    IMG_ID_FLIGHT_MODE_END
} IMG_ID_FLIGHT_MODE_ENUM;

/* end, diamond */


#define     FACTORY_RESTORE_DEFAULT_CURRENT_SCREENSVER_ID         SCREENSAVER_BASE

#define     FACTORY_RESTORE_DEFAULT_FUNANDGAMES_SETWALLPAPER_ID      WALLPAPER_BASE

#endif /* SETTINGRESDEF_H */ 
