/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * DataAccount.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file is intends for ¡K.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

 /**
 * Copyright Notice
 * ?2002 - 2003, Pixtel Communications, Inc., 1489 43rd Ave. W.,
 * Vancouver, B.C. V6M 4K8 Canada. All Rights Reserved.
 *  (It is illegal to remove this copyright notice from this software or any
 *  portion of it)
 */

#ifndef _PIXTEL_DATA_ACCOUNT_H
#define _PIXTEL_DATA_ACCOUNT_H

typedef enum
{
    SCR_ID_DTCNT_LIST = DATA_ACCOUNT_BASE + 1,
    SCR_ID_DTCNT_EDIT,
    SCR_ID_DTCNT_NOTIFICATION,
    SCR_ID_DTCNT_IN_PROGRESS,
    SCR_ID_DTCNT_MAIN,
#ifdef __MMI_GPRS_FEATURES__
    SCR_ID_DTCNT_GPRS_LIST,
    SCR_ID_DTCNT_GPRS_EDIT,
    SCR_ID_DTCNT_GPRS_NOTIFICATION,
#endif /* __MMI_GPRS_FEATURES__ */ 
#ifdef __MMI_WLAN_FEATURES__
    SCR_ID_DTCNT_WLAN_MAIN,
    SCR_ID_DTCNT_WLAN_CONN_STATUS,
    SCR_ID_DTCNT_WLAN_SETTINGS,
    SCR_ID_DTCNT_WLAN_TCPIP_SETTINGS,
    SCR_ID_DTCNT_WLAN_NETWORK_SETTINGS,
    SCR_ID_DTCNT_WLAN_NETWORK_SETTINGS_OPT,
    SCR_ID_DTCNT_WLAN_FIND_NETWORK_OPT,
    SCR_ID_DTCNT_WLAN_NETWORK_EDIT,
    SCR_ID_DTCNT_WLAN_NETWORK_PRIORITY,
    SCR_ID_DTCNT_WLAN_NETWORK_OPERATION_MODE,
    SCR_ID_DTCNT_WLAN_NETWORK_AUTH_MODE,
    SCR_ID_DTCNT_WLAN_NETWORK_ENCRYPT_MODE,
    SCR_ID_DTCNT_WLAN_WPA_PASSPHRASE,
    SCR_ID_DTCNT_WLAN_WPA_PASSPHRASE_OPT,
    SCR_ID_DTCNT_WLAN_WEP_SETTINGS,
    SCR_ID_DTCNT_WLAN_WEP_KEY_ID,
    SCR_ID_DTCNT_WLAN_WEP_KEY_LEN,
    SCR_ID_DTCNT_WLAN_WEP_KEY_FORMAT,
    SCR_ID_DTCNT_WLAN_PROCESSING,
    SCR_ID_DTCNT_WLAN_ABORTING,
    SCR_ID_DTCNT_WLAN_SCAN_PROCESSING,
    SCR_ID_DTCNT_WLAN_SCAN_RESULT,
    SCR_ID_DTCNT_WLAN_NETWORK_LIST,
    SCR_ID_DTCNT_WLAN_NETWORK_DETAILS,
    SCR_ID_DTCNT_WLAN_EAP_TYPE,
    SCR_ID_DTCNT_WLAN_EAP_TYPE_OPT,
    SCR_ID_DTCNT_WLAN_USER_INFO,
    SCR_ID_DTCNT_WLAN_EAP_TLS_SETTINGS,
    SCR_ID_DTCNT_WLAN_EAP_PEAP_SETTINGS,
    SCR_ID_DTCNT_WLAN_EAP_PEAP_SETTINGS_EAP_TYPE,
    SCR_ID_DTCNT_WLAN_EAP_PEAP_SETTINGS_EAP_TYPE_OPT,
    SCR_ID_DTCNT_WLAN_EAP_TTLS_SETTINGS,
    SCR_ID_DTCNT_WLAN_EAP_TTLS_SETTINGS_TUNNELED_AUTH_PROTOCOL,
    SCR_ID_DTCNT_WLAN_EAP_TTLS_SETTINGS_TUNNELED_AUTH_PROTOCOL_OPT,
    SCR_ID_DTCNT_WLAN_PASSPHRASE_INPUT,
    SCR_ID_DTCNT_WLAN_PASSPHRASE_INPUT_OPT,
    SCR_ID_DTCNT_WLAN_IPADDR_CONFILICT_IND,
    SCR_ID_DTCNT_WLAN_EMPTY,
#if defined(__MMI_WLAN_OTAP_OMAEXT__) || defined(__MMI_WLAN_OTAP_DMP__)
    SCR_ID_DTCNT_WLAN_INSTALL_PROFILE,
    SCR_ID_DTCNT_WLAN_REPLACE_PROFILE,
#endif /* defined(__MMI_WLAN_OTAP_OMAEXT__) || defined(__MMI_WLAN_OTAP_DMP__) */
#endif /* __MMI_WLAN_FEATURES__ */
#ifdef __MMI_CCA_SUPPORT__
    SCR_ID_DTCNT_OTA_MAIN,
#endif /* __MMI_CCA_SUPPORT__ */
#ifdef OBIGO_Q03C
    SCR_ID_DTCNT_LIST_BY_APP,
    SCR_ID_DTCNT_LIST_CONFIRM,
#endif /*OBIGO_Q03C*/
//#ifdef __CBM_ALWAYS_ASK_FEATURE__
    SCR_ID_DTCNT_LIST_DUAL_SIM,
    SCR_ID_DTCNT_LIST_ALWAYS_ASK,
//#endif /* __CBM_ALWAYS_ASK_FEATURE__ */
    SCR_ID_DTCNT_POPUP
} SCR_DATA_ACCOUNT;

typedef enum
{
    IMG_ID_DTCNT_MAIN = DATA_ACCOUNT_BASE + 1,
    IMG_ID_DTCNT_CAPTION,
    IMG_ID_DTCNT_LSK_EDIT,
    IMG_ID_DTCNT_LSK_OK,
    IMG_ID_DTCNT_RSK_BACK,
    IMG_ID_DTCNT_AC_NAME,
    IMG_ID_DTCNT_DIAL_NUM,
    IMG_ID_DTCNT_USER_NAME,
    IMG_ID_DTCNT_PASSWD,
    IMG_ID_DTCNT_DIAL_TYPE,
    IMG_ID_DTCNT_DATA_RATE,
    IMG_ID_DTCNT_DNS_ADDRESS,
#ifdef __MMI_GPRS_FEATURES__
    IMG_ID_DTCNT_GPRS_AC_NAME,
    IMG_ID_DTCNT_GPRS_APN,
    IMG_ID_DTCNT_GPRS_USER_NAME,
    IMG_ID_DTCNT_GPRS_PASSWD,
    IMG_ID_DTCNT_GPRS_CONNTYPE,
#endif /* __MMI_GPRS_FEATURES__ */ 
#ifdef __MMI_WLAN_FEATURES__
    IMG_ID_DTCNT_WLAN_POPUP_CONNECT,
    IMG_ID_DTCNT_WLAN_POPUP_SEARCH,
    IMG_ID_DTCNT_WLAN_STATION,
    IMG_ID_DTCNT_WLAN_SECURED_STATION,
    IMG_ID_DTCNT_WLAN_ADHOC,
    IMG_ID_DTCNT_WLAN_SIGNAL0,
    IMG_ID_DTCNT_WLAN_SIGNAL1,
    IMG_ID_DTCNT_WLAN_SIGNAL2,
    IMG_ID_DTCNT_WLAN_SIGNAL3,
    IMG_ID_DTCNT_WLAN_STATUS_DISCONNECT,
    IMG_ID_DTCNT_WLAN_STATUS_SCANNING,
    IMG_ID_DTCNT_WLAN_STATUS_CONNECT1,
    IMG_ID_DTCNT_WLAN_STATUS_CONNECT2,
    IMG_ID_DTCNT_WLAN_STATUS_CONNECT3,
    IMG_ID_DTCNT_WLAN_STATUS_CONNECT4,
    IMG_ID_DTCNT_WLAN_STATUS_CONNECT5,
    IMG_ID_DTCNT_WLAN_STATUS_CONNECT6,
#endif /* __MMI_WLAN_FEATURES__ */ 
    IMG_ID_DTCNT_SAVE,
    IMG_ID_DTCNT_IN_PROGRESS
} IMG_DATA_ACCOUNT;

typedef enum
{
    STR_ID_DTCNT_MAIN = DATA_ACCOUNT_BASE + 1,
    STR_ID_DTCNT_CAPTION,
    /* STR_ID_DTCNT_LSK_EDIT, */
    STR_ID_DTCNT_RSK_BACK,
    STR_ID_DTCNT_EMPTY,
    STR_ID_DTCNT_RENAME,
    STR_ID_DTCNT_DIAL_NUMBER,
    STR_ID_DTCNT_USER_NAME,
    STR_ID_DTCNT_PASSWD,
    STR_ID_DTCNT_DIAL_TYPE,
    STR_ID_DTCNT_DATA_RATE,
    STR_ID_DTCNT_DNS_ADDRESS,
    STR_ID_DTCNT_EDIT,
#ifdef OBIGO_Q03C
    STR_ID_DTCNT_SELECT_GSM_CSD,
#endif/*OBIGO_Q03C*/
//#ifdef __CBM_ALWAYS_ASK_FEAUTURE__
    STR_ID_DTCNT_ALWAYS_ASK,
    STR_ID_DTCNT_SIM1,
    STR_ID_DTCNT_SIM2,
    STR_ID_DTCNT_WIFI_SEARCH,
    STR_ID_DTCNT_SEARCH,
    STR_ID_DTCNT_CONNECT,
//#endif /* __CBM_ALWAYS_ASK_FEAUTURE__ */
    //STR_ID_DTCNT_SAVE_QUERY,
#ifdef __MMI_GPRS_FEATURES__
    STR_ID_DTCNT_GPRS_PAP_AUTH,
    STR_ID_DTCNT_GPRS_CHAP_AUTH,
    STR_ID_DTCNT_GPRS_APN,
    STR_ID_DTCNT_GPRS_AUTH_TYP,
#ifdef OBIGO_Q03C
    STR_ID_DTCNT_BEARER_GPRS_CSD,
    STR_ID_DTCNT_SELECT_GPRS,
#endif /*OBIGO_Q03C*/
#endif /* __MMI_GPRS_FEATURES__ */ 
#ifdef __MMI_WLAN_FEATURES__
    STR_ID_DTCNT_WLAN_ERROR_PROFILE_FULL,
    STR_ID_DTCNT_WLAN_ERROR_INVALID_SSID,
    STR_ID_DTCNT_WLAN_ERROR_NAME_INUSE,
    STR_ID_DTCNT_WLAN_ERROR_INVALID_NAME,
    STR_ID_DTCNT_WLAN_ERROR_AUTH_FAIL,
    STR_ID_DTCNT_WLAN_ERROR_CONNECT_FAIL,
    STR_ID_DTCNT_WLAN_ERROR_INVALID_KEY,
    STR_ID_DTCNT_WLAN_ERROR_INVALID_PASSPHRASE,
    STR_ID_DTCNT_WLAN_ERROR_FILE_OPEN_FAILED,
    STR_ID_DTCNT_WLAN_ERROR_IP_CONFLICT,
    STR_ID_DTCNT_WLAN_ERROR_ONE_EAP_NEEDED,
    STR_ID_DTCNT_WLAN_ERROR_NO_AUTH_SETTING,
    STR_ID_DTCNT_WLAN_ERROR_DEFINE_NETWORK_FIRST,
    STR_ID_DTCNT_WLAN_POWER,
    STR_ID_DTCNT_WLAN_POWER_ON,
    STR_ID_DTCNT_WLAN_POWER_OFF,
    STR_ID_DTCNT_WLAN_CONN_STATUS,
    STR_ID_DTCNT_WLAN_SETTINGS,
    STR_ID_DTCNT_WLAN_NETWORK_SETTINGS,
    STR_ID_DTCNT_WLAN_NETWORK_SETTINGS_OPT_PRIORITY,
    STR_ID_DTCNT_WLAN_TCPIP_SETTINGS,
    STR_ID_DTCNT_WLAN_FIND_NETWORK,
    STR_ID_DTCNT_WLAN_SCAN_RESULT,
    STR_ID_DTCNT_WLAN_USE_DHCP,
    STR_ID_DTCNT_WLAN_IPADDR,
    STR_ID_DTCNT_WLAN_NETMASK,
    STR_ID_DTCNT_WLAN_GATEWAY,
    STR_ID_DTCNT_WLAN_DNS1,
    STR_ID_DTCNT_WLAN_DNS2,
    STR_ID_DTCNT_WLAN_NAME,
    STR_ID_DTCNT_WLAN_SSID,
    STR_ID_DTCNT_WLAN_MACADDR,
    STR_ID_DTCNT_WLAN_BSSID,
    STR_ID_DTCNT_WLAN_CHANNEL,
    STR_ID_DTCNT_WLAN_ADHOC_CHANNEL,
    STR_ID_DTCNT_WLAN_SIGNAL_STRENGTH,
    STR_ID_DTCNT_WLAN_SIGNAL_LEVEL0,
    STR_ID_DTCNT_WLAN_SIGNAL_LEVEL1,
    STR_ID_DTCNT_WLAN_SIGNAL_LEVEL2,
    STR_ID_DTCNT_WLAN_SIGNAL_LEVEL3,
    STR_ID_DTCNT_WLAN_SIGNAL_LEVEL4,
    STR_ID_DTCNT_WLAN_SECURITY,
    STR_ID_DTCNT_WLAN_LINK_SPEED,
    STR_ID_DTCNT_WLAN_NETWORK_TYPE,
    STR_ID_DTCNT_WLAN_AUTH_MODE,
    STR_ID_DTCNT_WLAN_SECURITY_SETTINGS,
    STR_ID_DTCNT_WLAN_ENCRYPT_MODE,
    STR_ID_DTCNT_WLAN_NETWORK_TYPE_INFRA,
    STR_ID_DTCNT_WLAN_NETWORK_TYPE_ADHOC,
    STR_ID_DTCNT_WLAN_NETWORK_TYPE_AUTO,
    STR_ID_DTCNT_WLAN_AUTH_MODE_OPEN,
    STR_ID_DTCNT_WLAN_AUTH_MODE_SHARED,
    STR_ID_DTCNT_WLAN_AUTH_MODE_IEEE8021X,
    STR_ID_DTCNT_WLAN_AUTH_MODE_WPA,
    STR_ID_DTCNT_WLAN_AUTH_MODE_WPAPSK,
    STR_ID_DTCNT_WLAN_AUTH_MODE_WPANONE,
    STR_ID_DTCNT_WLAN_ENCRYPT_MODE_NONE,
    STR_ID_DTCNT_WLAN_ENCRYPT_MODE_WEP,
    STR_ID_DTCNT_WLAN_ENCRYPT_MODE_TKIP,
    STR_ID_DTCNT_WLAN_ENCRYPT_MODE_AES,
    STR_ID_DTCNT_WLAN_WEP_KEY_ID,
    STR_ID_DTCNT_WLAN_WEP_KEY_ID1,
    STR_ID_DTCNT_WLAN_WEP_KEY_ID2,
    STR_ID_DTCNT_WLAN_WEP_KEY_ID3,
    STR_ID_DTCNT_WLAN_WEP_KEY_ID4,
    STR_ID_DTCNT_WLAN_WEP_KEY_SETTINGS,
    STR_ID_DTCNT_WLAN_WEP_KEY_ENCRYPT,
    STR_ID_DTCNT_WLAN_WEP_KEY_ENCRYPT_64,
    STR_ID_DTCNT_WLAN_WEP_KEY_ENCRYPT_128,
    STR_ID_DTCNT_WLAN_WEP_KEY_ENCRYPT_256,
    STR_ID_DTCNT_WLAN_WEP_KEY_FORMAT,
    STR_ID_DTCNT_WLAN_WEP_KEY_FORMAT_ASCII,
    STR_ID_DTCNT_WLAN_WEP_KEY_FORMAT_HEX,
    STR_ID_DTCNT_WLAN_WEP_KEY,
    STR_ID_DTCNT_WLAN_DISCONNECT,
    STR_ID_DTCNT_WLAN_PROCESSING,
    STR_ID_DTCNT_WLAN_OVERWRITE,
    STR_ID_DTCNT_WLAN_OVERWRITE_CONFIRM,
    STR_ID_DTCNT_WLAN_CLEAR_CONFIRM,
    STR_ID_DTCNT_WLAN_NEW_ACCESS_POINT,
    STR_ID_DTCNT_WLAN_DEFINE_ACCESS_POINT,
    STR_ID_DTCNT_WLAN_NETWORK_DETAILS,
    STR_ID_DTCNT_WLAN_FINDING_NETWORK,
    STR_ID_DTCNT_WLAN_CONFIGURE,
    STR_ID_DTCNT_WLAN_RESCAN_NETWORK,
    STR_ID_DTCNT_WLAN_EAP,
    STR_ID_DTCNT_WLAN_EAP_TYPES,
    STR_ID_DTCNT_WLAN_EAP_TLS,
    STR_ID_DTCNT_WLAN_EAP_MD5,
    STR_ID_DTCNT_WLAN_EAP_PEAP,
    STR_ID_DTCNT_WLAN_EAP_TTLS,
    STR_ID_DTCNT_WLAN_EAP_SIM,
    STR_ID_DTCNT_WLAN_EAP_FAST,
    STR_ID_DTCNT_WLAN_EAP_GTC,
    STR_ID_DTCNT_WLAN_EAP_MSCHAP2,
    STR_ID_DTCNT_WLAN_PAP,
    STR_ID_DTCNT_WLAN_CHAP,
    STR_ID_DTCNT_WLAN_MSCHAP,
    STR_ID_DTCNT_WLAN_MSCHAP2,
    STR_ID_DTCNT_WLAN_WPA_PASSPHRASE,
    STR_ID_DTCNT_WLAN_USER_CERT,
    STR_ID_DTCNT_WLAN_PRIV_KEY,
    STR_ID_DTCNT_WLAN_PRIV_KEY_PASSWD,
    STR_ID_DTCNT_WLAN_CA_CERT,
    STR_ID_DTCNT_WLAN_USER_INFO,
    STR_ID_DTCNT_WLAN_TUNNELED_AUTH_PROTOCOL,
    STR_ID_DTCNT_WLAN_EAP_TLS_SETTINGS,
    STR_ID_DTCNT_WLAN_EAP_PEAP_SETTINGS,
    STR_ID_DTCNT_WLAN_EAP_TTLS_SETTINGS,
    STR_ID_DTCNT_WLAN_ALLOW_PEAP_0,
    STR_ID_DTCNT_WLAN_ALLOW_PEAP_1,
    STR_ID_DTCNT_WLAN_USE_ANONYMOUS,
    STR_ID_WLAN_ERROR_FILE_OPEN_FAIL,
    STR_ID_WLAN_ERROR_FILE_TOO_BIG,
    STR_ID_DTCNT_WLAN_CHANGE_INFRA_PRIORITY,
    STR_ID_DTCNT_WLAN_CHANGE_ADHOC_PRIORITY,
    STR_ID_DTCNT_WLAN_CONNECTING_NO_EDIT,
    STR_ID_DTCNT_WLAN_CONNECTING_NO_DEL,
#if defined(__MMI_WLAN_OTAP_OMAEXT__) || defined(__MMI_WLAN_OTAP_DMP__)
    STR_ID_DTCNT_WLAN_ERROR_NO_PROFILES,
    STR_ID_DTCNT_WLAN_ERROR_PROFILE_IN_USE,
    STR_ID_DTCNT_WLAN_SKIP_INVALID_PROFILES,
    STR_ID_DTCNT_WLAN_AUTO_RENAME_PROFILE,
    STR_ID_DTCNT_WLAN_INSTALL_PROFILE,
    STR_ID_DTCNT_WLAN_REPLACE_PROFILE,
    STR_ID_DTCNT_WLAN_REPLACE_CONFIRM,
#endif /* defined(__MMI_WLAN_OTAP_OMAEXT__) || defined(__MMI_WLAN_OTAP_DMP__) */
#endif /* __MMI_WLAN_FEATURES__ */ 
    STR_ID_DTCNT_ANALOGUE_STR,
    STR_ID_DTCNT_ISDN_STR,
    STR_ID_DTCNT_RATE_STR_ONE,
    STR_ID_DTCNT_RATE_STR_TWO,
    STR_ID_DTCNT_RATE_STR_THREE,
    STR_ID_DTCNT_NAME,
    STR_ID_DTCNT_NAME_ONE,
    STR_ID_DTCNT_NAME_TWO,
    STR_ID_DTCNT_NAME_THREE,
    STR_ID_DTCNT_NAME_FOUR,
    STR_ID_DTCNT_NAME_FIVE,
    /* micha1230 */
    STR_ID_DTCNT_NAME_SIX,
    STR_ID_DTCNT_NAME_SEVEN,
    STR_ID_DTCNT_NAME_EIGHT,
    STR_ID_DTCNT_NAME_NINE,
    STR_ID_DTCNT_NAME_TEN
} STR_DATA_ACCOUNT;

#endif /* _PIXTEL_DATA_ACCOUNT_H */ 

