/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * SoundRecorderDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file is for sound recorder.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#ifndef SOUND_RECORDER_RESDEF_H
#define SOUND_RECORDER_RESDEF_H

#include "MMI_features.h"   /* add if you use any compile options defined in MMI_features.h */

#ifdef __MMI_SOUND_RECORDER__

#include "MMIDataType.h"    /* for resource base */

typedef enum
{
    STR_ID_SNDREC_START_STRING_BASE = SOUND_RECORDER_BASE + 1,
    STR_ID_SNDREC_MAIN,

    STR_ID_SNDREC_OPTION,
    STR_ID_SNDREC_RECORD,
    STR_ID_SNDREC_PLAY,
    STR_ID_SNDREC_APPEND,
    STR_ID_SNDREC_RENAME,
    STR_ID_SNDREC_DELETE,
    STR_ID_SNDREC_DELETE_ALL,
    STR_ID_SNDREC_DELETE_ALL_PHONE,
    STR_ID_SNDREC_DELETE_ALL_CARD,
    STR_ID_SNDREC_SETTINGS,
    STR_ID_SNDREC_ADD_TO_RING,

    STR_ID_SNDREC_RENAME_OPTION,
    STR_ID_SNDREC_OPTION_SAVE,
    STR_ID_SNDREC_OPTION_INPUT_METHOD,

    STR_ID_SNDREC_SETTINGS_STORAGE,
	STR_ID_SNDREC_SMS_RECORD_TIMEOUT,

    STR_ID_SNDREC_SETTINGS_FORMAT,
    STR_ID_SNDREC_SETTINGS_AMR,
    STR_ID_SNDREC_SETTINGS_WAV,
    STR_ID_SNDREC_SETTINGS_AMRWB,
    STR_ID_SNDREC_SETTINGS_VM,

    STR_ID_SNDREC_PAUSE,
    STR_ID_SNDREC_RESUME,
    STR_ID_SNDREC_STOP,

    STR_ID_SNDREC_QUERY_ABORT,

    STR_ID_SNDREC_OPEN_FILE_ERROR,
    STR_ID_SNDREC_NO_CARD,
    STR_ID_SNDREC_COMMAND_ERROR,
    STR_ID_SNDREC_DEVICE_BUSY,
    STR_ID_SNDREC_WRITE_PROTECTION_ERROR,

    STR_ID_SNDREC_ERROR,
    STR_ID_SNDREC_AVAILABLE,

    STR_ID_SNDREC_BAD_FORMAT,
    STR_ID_SNDREC_INVALID_FORMAT,

    STR_ID_SNDREC_AUTO_RECORD_ON,
    STR_ID_SNDREC_SETTING_QUALITY,
    STR_ID_SNDREC_QUALITY_LOW,
    STR_ID_SNDREC_QUALITY_HIGH,

#ifdef __MMI_SOUND_RECORDER_STYLE_X__
    STR_ID_SNDREC_NEW_RECORD,
    STR_ID_SNDREC_LIST,
#endif /* __MMI_SOUND_RECORDER_STYLE_X__ */ 
    STR_ID_SNDREC_UNSUPPORTED_FREQ,
    STR_ID_SNDREC_SAVE_AUDIO,

    NO_OF_STR_ID_SNDREC
} sndrec_str_ids_enum;

typedef enum
{
    IMG_ID_SNDREC_START_IMAGE_BASE = SOUND_RECORDER_BASE + 1,
    IMG_ID_SNDREC_MAIN,

    IMG_ID_SNDREC_OPTION,
    IMG_ID_SNDREC_RECORD,
    IMG_ID_SNDREC_PLAY,
    IMG_ID_SNDREC_APPEND,
    IMG_ID_SNDREC_RENAME,
    IMG_ID_SNDREC_DELETE,
    IMG_ID_SNDREC_DELETE_ALL,
    IMG_ID_SNDREC_DELETE_ALL_PHONE,
    IMG_ID_SNDREC_DELETE_ALL_CARD,
    IMG_ID_SNDREC_SETTINGS,
    IMG_ID_SNDREC_ADD_TO_RING,

    IMG_ID_SNDREC_RENAME_OPTION,
    IMG_ID_SNDREC_OPTION_SAVE,
    IMG_ID_SNDREC_OPTION_INPUT_METHOD,

    IMG_ID_SNDREC_SETTINGS_STORAGE,
    IMG_ID_SNDREC_SETTINGS_FORMAT,
    IMG_ID_SNDREC_SETTINGS_QUALITY,
    //IMG_ID_SNDREC_SETTINGS_PHONE,
    //IMG_ID_SNDREC_SETTINGS_CARD,
    IMG_ID_SNDREC_SETTINGS_AMR,
    IMG_ID_SNDREC_SETTINGS_WAV,

    IMG_ID_SNDREC_RECORDING,
    IMG_ID_SNDREC_RECORDING_PAUSED,
    IMG_ID_SNDREC_PLAYING,
    IMG_ID_SNDREC_PLAYING_PAUSED,

#ifdef __MMI_SOUND_RECORDER_STYLE_X__
    IMG_ID_SNDREC_NEW_RECORD,
    IMG_ID_SNDREC_LIST,
#endif /* __MMI_SOUND_RECORDER_STYLE_X__ */ 
    NO_OF_IMG_ID_SNDREC
} sndrec_img_ids_enum;

typedef enum
{
    SCR_ID_SNDREC_START_BASE = SOUND_RECORDER_BASE + 1,
    SCR_ID_SNDREC_MAIN,

    SCR_ID_SNDREC_OPTION,
    SCR_ID_SNDREC_RECORD,
    SCR_ID_SNDREC_RECORD_PAUSED,
    SCR_ID_SNDREC_PLAY,
    SCR_ID_SNDREC_PLAY_PAUSED,
    SCR_ID_SNDREC_APPEND,
    SCR_ID_SNDREC_RENAME,
    SCR_ID_SNDREC_SETTINGS,

    SCR_ID_SNDREC_RENAME_OPTION,

    SCR_ID_SNDREC_SETTINGS_SAVE_QUERY,

    NO_OF_SCR_ID_SNDREC
} sndrec_scr_ids_enum;

#endif 
#endif /* SOUND_RECORDER_RESDEF_H */ 

