/*
 * Generated by Drv CodeGen for MT6225. Copyright MediaTek Inc. (C) 2006.
 * Tue Aug 12 19:29:24 2008
 * Do Not Modify the File.
 */

#ifdef __CUST_NEW__
#include "eint.h"


const unsigned char AUX_EINT_NO = 0;
const unsigned char TOUCH_PANEL_EINT_NO = 1;
const unsigned char CHR_USB_EINT_NO = 2;
const unsigned char BT_EINT_NO = 3;
const unsigned char SYNC_LCM_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char SWDBG_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char CHRDET_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char MOTION_SENSOR_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char CLAMDET_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char USB_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char WIFI_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char MELODY_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char OTG_IDPIN_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char EXTRA_A_KEY_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char EXTRA_B_KEY_EINT_NO = EINT_CHANNEL_NOT_EXIST;
const unsigned char LSD_MSDCCD_EINT_NO = EINT_CHANNEL_NOT_EXIST;

#if defined(__DIRECTION_SENSOR_SUPPORT__)
/* 2009.4.14 added by hongzhe.liu for motion sensor + */
const unsigned char MOTION_SENSOR_EINT_NO1 = EINT_CHANNEL_NOT_EXIST;
const unsigned char MOTION_SENSOR_EINT_NO2 = EINT_CHANNEL_NOT_EXIST; 
/* 2009.4.14 added by hongzhe.liu for motion sensor - */
#endif

#endif /* __CUST_NEW__ */


