/*
 * Generated by Drv CodeGen for MT6225. Copyright MediaTek Inc. (C) 2006.
 * Tue Aug 12 19:29:24 2008
 * Do Not Modify the File.
 */

#ifndef _EINT_DRV_H
#define _EINT_DRV_H


#define EINT0_DEBOUNCE_TIME_DELAY 50
#define EINT1_DEBOUNCE_TIME_DELAY 0
#define EINT2_DEBOUNCE_TIME_DELAY 50
#define EINT3_DEBOUNCE_TIME_DELAY 50
#define EINT4_DEBOUNCE_TIME_DELAY 0
#define EINT5_DEBOUNCE_TIME_DELAY 0
/* 2009.04.14 modified by hongzhe.liu for motion sensor + */
#define EINT6_DEBOUNCE_TIME_DELAY 50
#define EINT7_DEBOUNCE_TIME_DELAY 50
/* 2009.04.14 modified by hongzhe.liu for motion sensor - */

#endif /* _GPIO_DRV_H */


