/*
 * Generated by Drv CodeGen for MT6225. Copyright MediaTek Inc. (C) 2006.
 * Tue Aug 12 19:29:24 2008
 * Do Not Modify the File.
 */

#ifdef __CUST_NEW__
#include "gpio_drv.h"

#if (defined PCB_N65_V1P0)


/* touch panel */
const char gpio_tp_spi_clk_pin = GPIO_PORT_0;
const char gpio_tp_spi_dout_pin = GPIO_PORT_4;
const char gpio_tp_spi_din_pin = GPIO_PORT_5;
const char gpio_tp_spi_cs_pin = GPIO_PORT_32;
const char gpio_tp_spi_busy_pin = GPIO_PORT_47;

/* fm radio */
const char gpio_fm_32k = GPIO_PORT_26;
const char gpio_fm_i2c_sda_pin = GPIO_PORT_8 ;
const char gpio_fm_i2c_scl_pin =  GPIO_PORT_9 ;



/* camera */
const char gpio_sccb_serial_clk_pin = GPIO_PORT_8;
const char gpio_sccb_serial_data_pin = GPIO_PORT_9;

const char gpio_camera_module_power_pin = 0xff;

const char gpio_camera_power_en_pin = GPO_PORT_3;
const char gpio_camera_reset_pin = GPIO_PORT_10;
const char gpio_camera_cmpdn_pin = GPIO_PORT_11;

const char gpio_camera_power_en_pin_2 = GPO_PORT_3;
const char gpio_camera_reset_pin_2 = GPIO_PORT_10 ;
const char gpio_camera_cmpdn_pin_2 = GPIO_PORT_40 ;

/* lcm backlight */
const char gpio_led_mainbl_en_pin = GPIO_PORT_25; 

/* key backlight */
const char gpio_led_keybl_en_pin = 0xff;

/* vibrator */
const char gpio_vibrator_en_pin = GPIO_PORT_27;

/* audio amplifier ldo enable */
//const char gpio_afe_amplifier_pin = 0xFF;
const char gpio_afe_l_aw8145_ctrl_pin_1 = GPIO_PORT_30;
const char gpio_afe_l_aw8145_ctrl_pin_2 = GPIO_PORT_46;

const char gpio_afe_r_aw8145_ctrl_pin_1 = GPIO_PORT_43;
const char gpio_afe_r_aw8145_ctrl_pin_2 = GPIO_PORT_7;

/* mt6302 */
const char gpio_MT6302_clk_pin = GPIO_PORT_29;
const char gpio_MT6302_dat_pin = GPIO_PORT_31;
const char gpio_MT6302_cs_pin = GPIO_PORT_33;

/* charger control */
const char gpio_bmt_chr_ctrl_pin = GPIO_PORT_35;

/* usb ldo enable */
const char gpio_usb_enable_pin = GPIO_PORT_48;

/* bluetooth */
const char gpio_bt_wakeup_pin = GPIO_PORT_34;
const char gpio_bt_reset_pin = GPIO_PORT_34;
const char gpio_bt_power_pin = GPIO_PORT_37;
const char gpio_bt_urxd3_pin = GPIO_PORT_49;
const char gpio_bt_utxd3_pin = GPIO_PORT_50;
const char gpio_bt_urts3_pin = 0xff;
const char gpio_bt_ucts3_pin = 0xff;
const char gpio_bt_pcmclk_pin = GPIO_PORT_51;
const char gpio_bt_pcmout_pin = GPIO_PORT_52;
const char gpio_bt_pcmin_pin = GPIO_PORT_53;
const char gpio_bt_pcmsync_pin = GPIO_PORT_54;
const char gpio_bt_32k_pin = GPO_PORT_2;

#if defined(ANALOG_TV_TLG1100)
const char gpio_tlg1100_power_en = GPO_PORT_3;
const char gpio_tlg1100_reset_pin = GPIO_PORT_10;
const char gpio_tlg1100_i2c_scl = GPIO_PORT_8;
const char gpio_tlg1100_i2c_sda = GPIO_PORT_9;
#endif

#if defined(G_SENSOR_SUPPORT)
//const char gpio_G_int_pin         = GPIO_PORT_2;
const char gpio_G_i2c_sda_pin = GPIO_PORT_41 ;
const char gpio_G_i2c_scl_pin   = GPIO_PORT_2;
#endif


#if defined(HORSERACE_SUPPORT)
/* horse race */
const char gpio_horserace_power_en_pin   = GPO_PORT_3;
const char gpio_horserace_clk_pin            	= GPIO_PORT_6 ;
const char gpio_horserace_sdin_pin		= GPIO_PORT_1;
const char gpio_horserace_latch_pin		= GPIO_PORT_3;
#endif

#if defined(DOUBLE_BATTERY_SUPPORT)
const char gpio_ent4_pin 	= 0xff ;
const char gpio_power_sw_pin = 0xff ;
const char gpio_chr_sw_pin      = 0xff ;
#endif


/* flashlight */
const char gpio_flashlight_en_pin = GPIO_PORT_39;

/* photo_flashlight  */
const char gpio_photo_flashlight_en_pin = 0xff;

/* lamp Counterfeit Money  */
const char gpio_counterfeit_money_lamp_en_pin = GPIO_PORT_38;

/*Output for default variable names*/
const char gpio_wifi_enable_pin = 0xff;
const char gpio_wifi_eint_enable_pin = 0xff;
const char gpio_wifi_32k_pin = 0xff;
const char gpio_gps_power_pin = 0xff;
const char gpio_gps_standby_pin = 0xff;
const char gpio_gps_32k_pin = 0xff;
const char gpio_gps_utxd_pin = 0xff;
const char gpio_gps_urxd_pin = 0xff;
const char gpio_gps_urts_pin = 0xff;
const char gpio_gps_ucts_pin = 0xff;


#elif (defined PCB_N65_V2P0)







/* touch panel */
const char gpio_tp_spi_clk_pin = GPIO_PORT_0;
const char gpio_tp_spi_dout_pin = GPIO_PORT_4;
const char gpio_tp_spi_din_pin = GPIO_PORT_5;
const char gpio_tp_spi_cs_pin = GPIO_PORT_32;
const char gpio_tp_spi_busy_pin = GPIO_PORT_47;

/* fm radio */
const char gpio_fm_32k = GPIO_PORT_26;
const char gpio_fm_i2c_sda_pin = GPIO_PORT_8 ;
const char gpio_fm_i2c_scl_pin =  GPIO_PORT_9 ;



/* camera */
const char gpio_sccb_serial_clk_pin = GPIO_PORT_8;
const char gpio_sccb_serial_data_pin = GPIO_PORT_9;

const char gpio_camera_module_power_pin = 0xff;

const char gpio_camera_power_en_pin = GPO_PORT_3;
const char gpio_camera_reset_pin = GPIO_PORT_10;
const char gpio_camera_cmpdn_pin = GPIO_PORT_11;

const char gpio_camera_power_en_pin_2 = GPO_PORT_3;
const char gpio_camera_reset_pin_2 = GPIO_PORT_10 ;
const char gpio_camera_cmpdn_pin_2 = GPIO_PORT_40 ;

/* lcm backlight */
const char gpio_led_mainbl_en_pin = GPIO_PORT_25; 

/* vibrator */
const char gpio_vibrator_en_pin = GPIO_PORT_27;

/* audio amplifier ldo enable */
const char gpio_afe_amplifier_pin = GPIO_PORT_30;

#if 0
const char gpio_afe_l_aw8145_ctrl_pin_1 = GPIO_PORT_30;
const char gpio_afe_l_aw8145_ctrl_pin_2 = GPIO_PORT_46;

const char gpio_afe_r_aw8145_ctrl_pin_1 = GPIO_PORT_43;
const char gpio_afe_r_aw8145_ctrl_pin_2 = GPIO_PORT_7;
#endif

/* mt6302 */
const char gpio_MT6302_clk_pin = GPIO_PORT_29;
const char gpio_MT6302_dat_pin = GPIO_PORT_31;
const char gpio_MT6302_cs_pin = GPIO_PORT_33;

/* charger control */
const char gpio_bmt_chr_ctrl_pin = GPIO_PORT_35;

/* usb ldo enable */
const char gpio_usb_enable_pin = GPIO_PORT_48;

/* bluetooth */
const char gpio_bt_wakeup_pin = GPIO_PORT_34;
const char gpio_bt_reset_pin = GPIO_PORT_34;
const char gpio_bt_power_pin = GPIO_PORT_37;
const char gpio_bt_urxd3_pin = GPIO_PORT_49;
const char gpio_bt_utxd3_pin = GPIO_PORT_50;
const char gpio_bt_urts3_pin = 0xff;
const char gpio_bt_ucts3_pin = 0xff;
const char gpio_bt_pcmclk_pin = GPIO_PORT_51;
const char gpio_bt_pcmout_pin = GPIO_PORT_52;
const char gpio_bt_pcmin_pin = GPIO_PORT_53;
const char gpio_bt_pcmsync_pin = GPIO_PORT_54;
const char gpio_bt_32k_pin = GPO_PORT_2;

#if defined(ANALOG_TV_TLG1100)
const char gpio_tlg1100_power_en = GPO_PORT_3;
const char gpio_tlg1100_reset_pin = GPIO_PORT_10;
const char gpio_tlg1100_i2c_scl = GPIO_PORT_8;
const char gpio_tlg1100_i2c_sda = GPIO_PORT_9;
#elif defined(ANALOG_TV_TLG1120)
const char gpio_tlg1120_power_en = GPO_PORT_3;
const char gpio_tlg1120_reset_pin = GPIO_PORT_10;
const char gpio_tlg1120_i2c_scl = GPIO_PORT_8;
const char gpio_tlg1120_i2c_sda = GPIO_PORT_9;
#endif

#if defined(G_SENSOR_SUPPORT)
//const char gpio_G_int_pin         = GPIO_PORT_2;
const char gpio_G_i2c_sda_pin = GPIO_PORT_41 ;
const char gpio_G_i2c_scl_pin   = GPIO_PORT_2;
#endif


#if defined(HORSERACE_SUPPORT)
/* horse race */
const char gpio_horserace_power_en_pin   = GPO_PORT_3;
const char gpio_horserace_clk_pin            	= GPIO_PORT_6 ;
const char gpio_horserace_sdin_pin		= GPIO_PORT_1;
const char gpio_horserace_latch_pin		= GPIO_PORT_3;
/* key backlight */
const char gpio_led_keybl_en_pin = 0xff;
/* photo_flashlight  */
const char gpio_photo_flashlight_en_pin = 0xff;
#else
/* key backlight */
const char gpio_led_keybl_en_pin = GPIO_PORT_6;
/* photo_flashlight  */
const char gpio_photo_flashlight_en_pin = GPIO_PORT_46;
#endif

#if defined(DOUBLE_BATTERY_SUPPORT)
const char gpio_ent4_pin 	= 0xff ;
const char gpio_power_sw_pin = 0xff ;
const char gpio_chr_sw_pin      = 0xff ;
#endif

/* flashlight */
const char gpio_flashlight_en_pin = GPIO_PORT_39;

/* lamp Counterfeit Money  */
const char gpio_counterfeit_money_lamp_en_pin = GPIO_PORT_38;

/*Output for default variable names*/
const char gpio_wifi_enable_pin = 0xff;
const char gpio_wifi_eint_enable_pin = 0xff;
const char gpio_wifi_32k_pin = 0xff;
const char gpio_gps_power_pin = 0xff;
const char gpio_gps_standby_pin = 0xff;
const char gpio_gps_32k_pin = 0xff;
const char gpio_gps_utxd_pin = 0xff;
const char gpio_gps_urxd_pin = 0xff;
const char gpio_gps_urts_pin = 0xff;
const char gpio_gps_ucts_pin = 0xff;










#endif /* PCB_N65_VXPX */


#endif /* __CUST_NEW__ */


