/*
 * Generated by Drv CodeGen for MT6225. Copyright MediaTek Inc. (C) 2006.
 * Tue Aug 12 19:29:24 2008
 * Do Not Modify the File.
 */

#ifdef __CUST_NEW__
#include "kal_release.h"
#include "gpio_drv.h"
#include "custom_em.h"
#include "custom_equipment.h"


const kal_uint8 GPIO_LABELID_MAX = 4;
kal_uint8 EmGpioIdxMenu2Tbl[4];
const unsigned char netname[][MAX_NETNAME_TEXT] = {
"GPIO7#",
"GPIO#2",
"GPIO#0",
"GPIO#1",
};
GPIO_MAP_ENTRY gpio_map_tbl[] = {
{GPIO_VALID, GPIO_PORT_7, netname[0], NULL},
{GPIO_VALID, GPIO_PORT_25, netname[1], NULL},
{GPIO_VALID, GPIO_PORT_26, netname[2], NULL},
{GPIO_VALID, GPIO_PORT_27, netname[3], NULL},
};


const kal_uint8 EINT_LABELID_MAX = 4;
const unsigned char eintname[][MAX_NETNAME_TEXT] = {
"Aux",
"Touchpanel",
"Charger",
"Bluetooth",
};
GPIO_MAP_ENTRY eint_map_tbl[] = {
{GPIO_VALID, 0, eintname[0], NULL},
{GPIO_VALID, 1, eintname[1], NULL},
{GPIO_VALID, 2, eintname[2], NULL},
{GPIO_VALID, 3, eintname[3], NULL},
};


const kal_uint8 ADC_LABELID_MAX = 3;
const unsigned char adcname[][MAX_NETNAME_TEXT] = {
"VBAT",
"Current",
"VAUX",
};
GPIO_MAP_ENTRY adc_map_tbl[] = {
{GPIO_VALID, 0, adcname[0], NULL},
{GPIO_VALID, 1, adcname[1], NULL},
{GPIO_VALID, 5, adcname[2], NULL},
};


#endif /* __CUST_NEW__ */


