/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
 /*******************************************************************************
 *  Copyright Statement:
 *  --------------------
 *  This software is protected by Copyright and the information contained
 *  herein is confidential. The software may not be copied and the information
 *  contained herein may not be used or disclosed except with the written
 *  permission of MediaTek Inc. (C) 2001
 *
 *******************************************************************************/

 /*******************************************************************************
 * Filename:
 * ---------
 *   l4.sap
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   l4 related message identity definition
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

/********************************************************************************
*  Copyright Statement:
*  --------------------
*
*  This product has been developed using a protocol stack
*  developed by Sasken Communication Technologies Limited.
*
********************************************************************************/


/*---------------L4_MSG_CODE_BEGIN---------------------------*/
	/*--------------- L4C_MSG_CODE_BEGIN------------------------*/
	MSG_TAG_L4C_FIRST_CNF_MSG = MSG_ID_L4C_CODE_BEGIN,
	MSG_ID_L4CCSM_CC_STARTUP_CNF = MSG_TAG_L4C_FIRST_CNF_MSG,
	MSG_ID_L4CCSM_CC_ACM_RESET_CNF,
	MSG_ID_L4CCSM_CC_ACMMAX_SET_CNF,
	MSG_ID_L4CCSM_CC_CRSS_CNF,
	MSG_ID_L4CCSM_CC_CALL_DEFLECTION_CNF,
	MSG_ID_L4CCSM_CC_START_DTMF_CNF,
	MSG_ID_L4CCSM_CC_STOP_DTMF_CNF,
	MSG_ID_L4CCSM_CC_CALL_ACCEPT_CNF,
	MSG_ID_L4CCSM_CC_CALL_MODIFY_CNF,
	MSG_ID_L4CCSM_CC_CALL_SETUP_CNF,
	MSG_ID_L4CCSM_CC_CALL_DISC_CNF,
   MSG_ID_L4CCSM_CC_EMERGENCY_CALL_SETUP_CNF, /* not implemented yet */
   MSG_ID_L4CCSM_CC_SET_CSD_PROF_CNF,
   MSG_ID_L4CCSM_CC_SAT_SETUP_CNF,
   MSG_ID_L4CCSM_CC_SAT_SEND_DTMF_CNF,
   MSG_ID_L4CCSM_CC_UPDATE_ALS_CNF,

   MSG_ID_L4CCSM_CISS_STARTUP_CNF,
	MSG_ID_L4CCSM_CISS_SS_PARSE_CNF,
   MSG_ID_L4CCSM_CISS_CF_END_CNF,
   MSG_ID_L4CCSM_CISS_CW_END_CNF,
   MSG_ID_L4CCSM_CISS_CB_END_CNF,
   MSG_ID_L4CCSM_CISS_EMLPP_END_CNF,
   MSG_ID_L4CCSM_CISS_CLI_END_CNF,
   MSG_ID_L4CCSM_CISS_CCBS_END_CNF,
   MSG_ID_L4CCSM_CISS_PUSSR_END_CNF,
   MSG_ID_L4CCSM_CISS_USSR_END_CNF,           /* not implemented yet */
   MSG_ID_L4CCSM_CISS_USSN_END_CNF,
   MSG_ID_L4CCSM_CISS_SIM_END_CNF,

   MSG_ID_L4CUEM_SET_PROFILE_CNF,
	MSG_ID_L4CUEM_STARTUP_CNF,
   MSG_ID_L4CUEM_SET_AUDIO_PROFILE_CNF,
   MSG_ID_L4CUEM_SET_AUDIO_PARAM_CNF,
   MSG_ID_L4CUEM_SET_HW_LEVEL_CNF,
   MSG_ID_L4CUEM_AUDIO_PLAY_BY_NAME_CNF,
   MSG_ID_L4CUEM_AUDIO_STOP_BY_NAME_CNF,
   MSG_ID_L4CUEM_AUDIO_PLAY_BY_STRING_CNF,
   MSG_ID_L4CUEM_AUDIO_STOP_BY_STRING_CNF,
   MSG_ID_L4CUEM_VM_RECORD_CNF,  /* voice memo related */
   MSG_ID_L4CUEM_VM_PLAY_CNF,
   MSG_ID_L4CUEM_VM_STOP_CNF,
   MSG_ID_L4CUEM_VM_DELETE_CNF,
   MSG_ID_L4CUEM_VM_ABORT_CNF,
   MSG_ID_L4CUEM_VM_PAUSE_CNF,
   MSG_ID_L4CUEM_VM_RESUME_CNF,
   MSG_ID_L4CUEM_VM_APPEND_CNF,
   MSG_ID_L4CUEM_VM_GET_INFO_CNF,
   MSG_ID_L4CUEM_VM_RENAME_CNF,


   MSG_ID_L4CRAC_ACT_CNF,
   MSG_ID_L4CRAC_REG_CNF,
   MSG_ID_L4CRAC_PS_REG_CNF,
   MSG_ID_L4CRAC_DEREG_CNF,
   MSG_ID_L4CRAC_PLMN_LIST_CNF,
   MSG_ID_L4CRAC_CLASS_CHANGE_CNF,
   MSG_ID_L4CRAC_SET_PREFERRED_BAND_CNF, //tommy 030610 add for band selection
   MSG_ID_L4CRAC_RFOFF_CNF,
#ifdef __MTK_3G_MRAT_ARCH__ /* for RAC2 */   
   MSG_ID_L4CRAC_PLMN_SEARCH_CNF,
   MSG_ID_L4CRAC_SET_RAT_MODE_CNF,
   MSG_ID_L4CRAC_PLMN_LIST_STOP_CNF,
   MSG_ID_L4CRAC_SET_PREFER_RAT_CNF,
#else /* for RAC */
	 MSG_ID_L4CRAC_PLMN_SEL_CNF,
#endif        

   MSG_ID_L4CPHB_INIT_LN_CNF,
	MSG_ID_L4CPHB_STARTUP_CNF,
	MSG_ID_L4CPHB_SEARCH_CNF,
   MSG_ID_L4CPHB_READ_CNF,
   MSG_ID_L4CPHB_WRITE_CNF,
	MSG_ID_L4CPHB_DELETE_CNF,
	MSG_ID_L4CPHB_READ_LN_CNF,
	MSG_ID_L4CPHB_WRITE_LN_CNF,
	MSG_ID_L4CPHB_DELETE_LN_CNF,
	MSG_ID_L4CPHB_APPROVE_CNF,
	MSG_ID_L4CPHB_SYNC_CNF,
	MSG_ID_L4CPHB_READ_EMAIL_CNF,
	MSG_ID_L4CPHB_SET_GRP_CNF,
	MSG_ID_L4CPHB_WRITE_USIM_CNF,

	MSG_ID_L4CSMU_START_CNF,
	MSG_ID_L4CSMU_SECURITY_CNF,
	MSG_ID_L4CSMU_SET_PERSONALIZATION_CNF, /* SML */
	MSG_ID_L4CSMU_SML_STATUS_CNF, /* SML */
	MSG_ID_L4CSMU_PLMN_SEL_WRITE_CNF,
	MSG_ID_L4CSMU_SIM_ACCESS_CNF,
	MSG_ID_L4CSMU_PUCT_WRITE_CNF,
   MSG_ID_L4CSMU_CSP_READ_CNF,

   MSG_ID_L4CSMU_DIAL_MODE_CNF,
	MSG_ID_L4CSMU_PUCT_READ_CNF,
	MSG_ID_SAT_MENU_SELECT_CNF,
	/* Benson 04212004 SATcE */
	// mtk01616_070530 remove obsolete code
	/*	
	MSG_ID_L4CSAT_OPEN_CHANNEL_CNF,
	MSG_ID_L4CSAT_SEND_DATA_CNF,
	MSG_ID_L4CSAT_RECV_DATA_CNF,
	*/
	MSG_ID_L4CSMU_SAT_OPEN_CHANNEL_CNF,
	
	/* SATcE End */
   MSG_ID_L4CSMSAL_INIT_CNF,
   MSG_ID_L4CSMSAL_READ_CNF,
   MSG_ID_L4CSMSAL_SEND_CNF,
   MSG_ID_L4CSMSAL_WRITE_CNF,
   MSG_ID_L4CSMSAL_DELETE_CNF,
   MSG_ID_L4CSMSAL_SEND_FROM_STORAGE_CNF,
   //MSG_ID_L4CSMSAL_SET_PARAMETER_CNF,
   MSG_ID_L4CSMSAL_SEND_ABORT_CNF,
   MSG_ID_L4CSMSAL_SAT_SEND_CNF,
   MSG_ID_L4CSMSAL_CB_UPDATE_CNF,
   MSG_ID_L4CSMSAL_SET_COMMON_PARA_CNF,
   MSG_ID_L4CSMSAL_SET_PROFILE_PARA_CNF,
   MSG_ID_L4CSMSAL_COPY_MSG_CNF,
   MSG_ID_L4CSMSAL_SET_STATUS_CNF,

	MSG_ID_TCM_PDP_ACTIVATE_CNF,
	MSG_ID_TCM_PDP_ACTIVATE_REJ,
	MSG_ID_TCM_PDP_DEACTIVATE_CNF,
	MSG_ID_TCM_PDP_MODIFY_CNF,
	MSG_ID_TCM_PDP_MODIFY_REJ,
	MSG_ID_L4CTCM_START_CNF,
	MSG_ID_L4CTCM_SET_PRI_PDP_INFO_CNF,
	MSG_ID_L4CTCM_SET_SEC_PDP_INFO_CNF,
	MSG_ID_L4CTCM_SET_QOS_INFO_CNF,
	MSG_ID_L4CTCM_SET_EQOS_INFO_CNF, /* CH_Liang 2005/08/04 R99 feature */
	MSG_ID_L4CTCM_SET_TFT_INFO_CNF,
	MSG_ID_L4CTCM_SET_GPRS_STATISTICS_INFO_CNF,
	MSG_ID_L4CTCM_SET_PPP_AUTH_CNF, //tommy add 031015 for danny 
	MSG_ID_L4CTCM_UNDEFINE_PDP_INFO_CNF, //mtk00714 w0633: AT definition

	MSG_ID_L4CPPP_ACTIVATE_CNF,
	MSG_ID_L4CPPP_DEACTIVATE_CNF,
   MSG_ID_L4CPPP_RESUME_CNF,
   	MSG_ID_L4CABM_SET_GPRS_ACCOUNT_INFO_CNF, //modify in W04.11 for change gprs account from tcm to abm
   	MSG_ID_L4CABM_GET_GPRS_ACCOUNT_INFO_CNF,
    	MSG_ID_L4CABM_START_CNF, //modify in W04.11 for ask abm start after phonebook startup
    
   MSG_ID_L4CPPP_CSD_ACTIVATE_CNF,
   MSG_ID_L4CPPP_CSD_DEACTIVATE_CNF,

    



  MSG_ID_L4C_T30_TX_MSG_CNF, //erica add for FAX
   MSG_ID_L4C_T30_RX_MSG_CNF,
   MSG_ID_L4C_T30_RW_PARAM_CNF,
   MSG_ID_L4C_T30_TX_BCS_CNF,
   MSG_ID_L4C_T30_RX_BCS_CNF,
   MSG_ID_L4C_T30_TX_SILENCE_CNF,
   MSG_ID_L4C_T30_RX_SILENCE_CNF,
   MSG_ID_L4C_T30_RW_STR_PARAM_CNF,
   MSG_ID_L4C_T30_TX_PPM_CNF, //Robert add

   MSG_ID_L4C_OPEN_UART_PORT_CNF,
   MSG_ID_L4C_CLOSE_UART_PORT_CNF,

   MSG_ID_L4CWAP_PROF_ACCESS_CNF, //tommy add for profile access confirm message ID

   /*MSG from DT*/
   MSG_ID_L4CDT_DOWNLOAD_CNF,
   MSG_ID_L4CDT_UPLOAD_CNF,
   MSG_ID_L4CDT_FILELIST_CNF,
   MSG_TAG_L4C_LAST_CNF_MSG = MSG_ID_L4CDT_FILELIST_CNF,


   MSG_TAG_L4C_FIRST_IND_MSG,
   /* Rex Modify becasue conflict with driver message id
   MSG_ID_UART_READY_TO_WRITE_IND = L4C_FIRST_IND_MSG,
   MSG_ID_UART_READY_TO_READ_IND,
   */

	MSG_ID_L4CCSM_CC_ATTACH_IND = MSG_TAG_L4C_FIRST_IND_MSG,
	MSG_ID_L4CCSM_CC_DETACH_IND,
	MSG_ID_L4CCSM_CC_CCM_IND,
	MSG_ID_L4CCSM_CC_CALL_MODIFY_IND,
	MSG_ID_L4CCSM_CC_CALL_SETUP_IND,
	MSG_ID_L4CCSM_CC_CALL_ALERT_IND,
	MSG_ID_L4CCSM_CC_CALL_CONNECT_IND,
	MSG_ID_L4CCSM_CC_CALL_DISC_IND,
	MSG_ID_L4CCSM_CC_CALL_REL_IND,
   MSG_ID_L4CCSM_CC_PROGRESS_IND,
	MSG_ID_L4CCSM_CC_CALL_PROC_IND,
	MSG_ID_L4CCSM_CC_NOTIFY_SS_IND,
	MSG_ID_L4CCSM_CC_AUTO_DTMF_START_IND,
	MSG_ID_L4CCSM_CC_AUTO_DTMF_COMPLETE_IND,
	MSG_ID_L4CCSM_CC_CCBS_CALL_DEACTIVATE_IND,
	MSG_ID_L4CCSM_CC_CALL_PREEMPT_IND,
	MSG_ID_L4CCSM_CC_UART_TRANSFER_IND,
	MSG_ID_L4CCSM_CC_CSD_EST_IND,
	MSG_ID_L4CCSM_CPHS_DISPLAY_ALS_IND, /* tommy 030722 add for ripple CPHS feature*/
	MSG_ID_L4CCSM_CC_CALL_INFO_IND, /* tommy add 031002 for aux turn off loudspeaker and adc pool */
	MSG_ID_L4CCSM_CC_CPI_IND, //mtk00714 add 20041210 for +ECPI
	MSG_ID_L4CCSM_CC_CALL_SYNC_IND, /*mtk00924 add 050727 for indicate MMI to get call info*/
	MSG_ID_L4CCSM_CC_VIDEO_CALL_STATUS_IND,	
	MSG_ID_L4CCSM_CISS_USSR_BEGIN_IND,
	MSG_ID_L4CCSM_CISS_USSN_BEGIN_IND,
	MSG_ID_L4CCSM_CISS_USSR_FAC_IND,
	MSG_ID_L4CCSM_CISS_USSN_FAC_IND,
	MSG_ID_L4CCSM_CISS_CB_FAC_IND,
        MSG_ID_L4CCSM_CPHS_DISPLAY_CFU_IND, /* tommy 030602 add for paul CPHS feature*/

   MSG_ID_L4CUEM_VM_RECORD_FINISH_IND,
   MSG_ID_L4CUEM_VM_PLAY_FINISH_IND,


	//MSG_ID_L4CRAC_REG_IND,
	MSG_ID_L4CRAC_REG_STATE_IND,
	MSG_ID_L4CRAC_RX_LEVEL_IND,
	MSG_ID_L4CRAC_NW_INFO_IND,
	MSG_ID_L4CRAC_CIPHER_IND,
	MSG_ID_L4CRAC_HZ_CELL_INFO_UPDATE_IND, /* CH_Liang 2005.05.31 Homezone feature */
	MSG_ID_L4CRAC_HZ_DEDICATED_MODE_IND,
	MSG_ID_L4CRAC_HZ_PKT_TRANSFER_MODE_IND,
	MSG_ID_L4CRAC_SEARCH_NORMAL_FINISH_IND,
	MSG_ID_L4CRAC_MMRR_SERVICE_STATUS_IND,	// for solving emergecy call issue in Gemini
/* SIM BEGIN */	
	MSG_ID_L4CSMU_SECURITY_IND,
	MSG_ID_L4CSMU_MMRR_READY_IND, // 030822 tommy add for power on enhance for Paul	
	MSG_ID_L4CSMU_MMI_INFO_IND, // 030609 tommy add for CPHS feature for Paul

/* SAT BEGIN */	
   MSG_ID_SAT_DSPL_TEXT_IND,
   MSG_ID_SAT_GET_INKEY_IND,
   MSG_ID_SAT_GET_INPUT_IND,
   MSG_ID_SAT_SETUP_MENU_IND,
   MSG_ID_SAT_SELECT_ITEM_IND,
   MSG_ID_SAT_PLAY_TONE_IND,
   MSG_ID_SAT_SETUP_CALL_IND,
   MSG_ID_SAT_SEND_SMS_IND,
   MSG_ID_SAT_SEND_SS_IND,
   MSG_ID_SAT_SEND_USSD_IND,
   MSG_ID_SAT_MMI_INFO_IND,
/* tommy 030602 add for paul new indication */
   MSG_ID_SAT_SETUP_IDLE_DSPL_IND, 
   MSG_ID_SAT_RUN_AT_COMMAND_IND,
   MSG_ID_SAT_SEND_DTMF_IND,
   MSG_ID_SAT_LANG_NOTIFY_IND,
   MSG_ID_SAT_LAUNCH_BROWSER_IND,
   MSG_ID_SAT_NO_OTHER_CMD_IND,
   /* Benson 04212004 SATcE */
   	// mtk01616_070530 remove obsolete code
/*
   MSG_ID_L4CSAT_OPEN_CHANNEL_IND,
   MSG_ID_L4CSAT_CLOSE_CHANNEL_IND,
   MSG_ID_L4CSAT_SEND_DATA_IND,
   MSG_ID_L4CSAT_RECV_DATA_IND,
   MSG_ID_L4CSAT_SET_GPRS_DATA_ACCOUNT_IND,
   MSG_ID_L4CSAT_CSM_OPEN_CSD_IND,
   MSG_ID_L4CSAT_CC_CALL_DISC_IND,

   */
   /* End Benson SATcE */
 //mtk01616_070530 begin
MSG_ID_L4CSMU_SAT_SET_CSD_PROF_IND,
MSG_ID_L4CSMU_SAT_SET_GPRS_PROF_IND,
MSG_ID_L4CSMU_SAT_OPEN_CHANNEL_IND,
MSG_ID_L4CSMU_SAT_CLOSE_CHANNEL_IND,
MSG_ID_L4CSMU_SAT_SEND_DATA_IND,
MSG_ID_L4CSMU_SAT_RECV_DATA_IND,
MSG_ID_L4CSMU_SAT_NOTIFY_MMI_IND,
 //mtk01616_070530 end

	MSG_ID_L4CSMSAL_CB_MSG_TEXT_IND,
	MSG_ID_L4CSMSAL_CB_MSG_PDU_IND,
	MSG_ID_L4CSMSAL_CB_DL_IND,
	MSG_ID_L4CSMSAL_MEM_FULL_IND,
   MSG_ID_L4CSMSAL_MEM_EXCEED_IND,
   MSG_ID_L4CSMSAL_MEM_AVAILABLE_IND,
   MSG_ID_L4CSMSAL_MSG_WAITING_IND,
   MSG_ID_L4CSMSAL_NEW_MSG_PDU_IND,
   MSG_ID_L4CSMSAL_NEW_MSG_TEXT_IND,
   MSG_ID_L4CSMSAL_NEW_MSG_INDEX_IND,
   MSG_ID_L4CSMSAL_APP_DATA_IND,
   MSG_ID_L4CSMSAL_SYNC_MSG_IND,
   MSG_ID_L4CSMSAL_STARTUP_READ_MSG_IND,
   MSG_ID_L4CSMSAL_STARTUP_BEGIN_IND,
   MSG_ID_L4CSMSAL_STARTUP_FINISH_IND,
   MSG_ID_L4CSMSAL_FDN_CHECK_IND,
   MSG_ID_L4CSMSAL_HZ_CB_MSG_IND, /* temp use */
   MSG_ID_L4CSMSAL_CB_GS_CHANGE_IND,

	MSG_ID_L4C_T30_READY_IND, //erica add for FAX
	MSG_ID_L4C_T30_TRANSFER_UART_IND,
	MSG_ID_L4C_T30_REPORT_PARAM_IND,
	MSG_ID_L4C_T30_TX_BCS_IND,
	MSG_ID_L4C_T30_VOICE_MODE_IND,

	MSG_ID_TCM_PDP_ACTIVATE_IND,
	MSG_ID_TCM_PDP_DEACTIVATE_IND,
	MSG_ID_TCM_MOBILITY_STATUS_IND,
	MSG_ID_TCM_EVENT_REP_IND,

	MSG_ID_L4CPPP_DEACTIVATE_IND,
   MSG_ID_L4CPPP_ESCAPE_IND,
   MSG_ID_L4CPPP_CSD_DEACTIVATE_IND,

  MSG_ID_L4CPHB_STARTUP_BEGIN_IND,
   MSG_ID_L4CPHB_STARTUP_READ_IND,
	MSG_ID_L4CPHB_STARTUP_PHASE1_IND,
	MSG_ID_L4CPHB_STARTUP_READ_ANR_IND,
	MSG_ID_L4CPHB_STARTUP_READ_EMAIL_IND,
        MSG_ID_L4CPHB_STARTUP_READ_GAS_IND,
        MSG_ID_L4CPHB_STARTUP_READ_GRP_IND,

   MSG_ID_FLC_STATUS_REPORT_IND,

   /*DT BEGIN*/
   MSG_ID_L4CDT_UART_TRANSFER_IND,
	MSG_TAG_L4C_LAST_IND_MSG = MSG_ID_L4CDT_UART_TRANSFER_IND,

   MSG_TAG_L4C_FIRST_REQ_MSG,
   MSG_ID_L4C_PS_ABM_SETUP_REQ = MSG_TAG_L4C_FIRST_REQ_MSG,
   MSG_ID_L4C_PS_ABM_DISC_REQ,
   MSG_ID_L4C_CC_ABM_SETUP_REQ,
   MSG_ID_L4C_CC_ABM_DISC_REQ,
   MSG_ID_ABM_L4C_GET_CSD_CALL_NUM_REQ,
   MSG_ID_L4C_OPEN_UART_PORT_REQ,
   MSG_ID_L4C_CLOSE_UART_PORT_REQ,

   MSG_TAG_L4C_LAST_REQ_MSG = MSG_ID_L4C_CLOSE_UART_PORT_REQ,

	MSG_ID_L4C_CODE_END = MSG_TAG_L4C_LAST_REQ_MSG,
	/*--------------- L4C_MSG_CODE_END--------------------------*/


	/*--------------- TCM_MSG_CODE_BEGIN------------------------*/
	MSG_TAG_FIRST_CNTXT_DATA_MSG = MSG_ID_TCM_CODE_BEGIN,
	MSG_ID_TAF_EXT_PDP_ACTIVATE_IND = MSG_TAG_FIRST_CNTXT_DATA_MSG,
	MSG_ID_TCM_PDP_ACTIVATE_REQ,
	MSG_ID_SMREG_PDP_ACTIVATE_IND,
	MSG_ID_SMREG_PDP_ACTIVATE_CNF,
	MSG_ID_SMREG_PDP_ACTIVATE_REJ,
	MSG_ID_SMREG_PDP_ACTIVATE_SEC_CNF,
	MSG_ID_SMREG_PDP_ACTIVATE_SEC_REJ,
	MSG_ID_TCM_PDP_ACTIVATE_REJ_RSP,
	MSG_ID_TCM_TIMER_EXPIRY,
	MSG_ID_TCM_PDP_MODIFY_REQ,
	MSG_ID_SMREG_PDP_MODIFY_IND,
	MSG_ID_SMREG_PDP_MODIFY_CNF,
	MSG_ID_SMREG_PDP_MODIFY_REJ,
	MSG_ID_TCM_PDP_DEACTIVATE_REQ,
	MSG_ID_TAF_EXT_PDP_DEACTIVATE_IND,
	MSG_ID_SMREG_PDP_DEACTIVATE_IND,
	MSG_ID_SMREG_PDP_DEACTIVATE_CNF,
	MSG_ID_TAF_LINK_FREE_IND,	
#ifdef __MTK_3G_MRAT_ARCH__
	MSG_TAG_LAST_CNTXT_DATA_MSG = MSG_ID_TAF_LINK_FREE_IND,
#endif
	MSG_ID_TAF_DATA_IND,
	MSG_ID_TCPIP_TCM_DATA_REQ,
	MSG_ID_SN_DATA_IND,
	MSG_ID_SN_UNITDATA_IND,	
#ifndef __MTK_3G_MRAT_ARCH__
	MSG_TAG_LAST_CNTXT_DATA_MSG = MSG_ID_SN_UNITDATA_IND,
#endif

	/* new tcm msg */
	MSG_ID_L4CTCM_START_REQ,
	MSG_ID_L4CTCM_SET_PRI_PDP_INFO_REQ,
	MSG_ID_L4CTCM_SET_SEC_PDP_INFO_REQ,
	MSG_ID_L4CTCM_SET_QOS_INFO_REQ,
	MSG_ID_L4CTCM_SET_EQOS_INFO_REQ, /* CH_Liang 2005/08/04 R99 feature */
	MSG_ID_L4CTCM_SET_TFT_INFO_REQ,
	MSG_ID_L4CTCM_SET_GPRS_STATISTICS_INFO_REQ,
	MSG_ID_L4CTCM_SET_PPP_AUTH_INFO_REQ,
	MSG_ID_L4CTCM_UNDEFINE_PDP_INFO_REQ, //mtk00714 w0633: AT definition

      /* Jeff Wu 2007-03-03: RATDM -> TCM */
	MSG_ID_SMREG_PDP_PRESERVE_IND,	//erica __SM_3G__
	MSG_ID_SMREG_PDP_REESTABLISH_IND,	//erica __SM_3G__	
	MSG_ID_TCM_RATDM_DATA_IND,
	MSG_ID_TCM_CODE_END = MSG_ID_TCM_RATDM_DATA_IND,
	/*--------------- TCM_MSG_CODE_END--------------------------*/

	/*-----------------CSM_MSG_CODE_BEGIN-----------------------*/
	MSG_ID_MNCC_SETUP_IND = MSG_ID_CSM_CODE_BEGIN,
	MSG_ID_MNCC_SETUP_CNF,
	MSG_ID_MNCC_SETUP_COMPL_IND,
	MSG_ID_MNCC_REJ_IND,
	MSG_ID_MNCC_CALL_PROC_IND,
	MSG_ID_MNCC_PROGRESS_IND,
	MSG_ID_MNCC_ALERT_IND,
	MSG_ID_MNCC_NOTIFY_IND,
	MSG_ID_MNCC_DISC_IND,
	MSG_ID_MNCC_REL_IND,
	MSG_ID_MNCC_REL_CNF,
	MSG_ID_MNCC_FACILITY_IND,
	MSG_ID_MNCC_START_DTMF_CNF,
	MSG_ID_MNCC_STOP_DTMF_CNF,
	MSG_ID_MNCC_MODIFY_IND,
	MSG_ID_MNCC_MODIFY_CNF,
	MSG_ID_MNCC_SYNC_IND,
	MSG_ID_MNCC_RAT_IND,	
	MSG_ID_MNCC_HOLD_CNF,
	MSG_ID_MNCC_RETRIEVE_CNF,
	MSG_ID_MNCC_USER_INFO_IND,
	MSG_ID_MNCC_CONGESTION_CTRL_IND,
	MSG_ID_MNCC_CCBS_EST_IND,
	MSG_ID_MNCC_CCBS_RECALL_IND,
	MSG_ID_MNCC_AOC_IND,
	MSG_ID_MNCC_SIG_CON_REEST_IND,
	MSG_ID_MNCC_SIG_CON_REEST_CNF,

   	MSG_ID_L4CCSM_CC_STARTUP_REQ,
   	MSG_ID_L4CCSM_CC_ACM_RESET_REQ,
	MSG_ID_L4CCSM_CC_ACMMAX_SET_REQ,
	MSG_ID_L4CCSM_CC_CALL_DEFLECTION_REQ,
	MSG_ID_L4CCSM_CC_CRSS_REQ,
	MSG_ID_L4CCSM_CC_CALL_ACCEPT_REQ,
	MSG_ID_L4CCSM_CC_CALL_DISC_REQ,
	MSG_ID_L4CCSM_CC_CALL_MODIFY_REQ,
	MSG_ID_L4CCSM_CC_CALL_SETUP_REQ,
	MSG_ID_L4CCSM_CC_AUTO_DTMF_START_REQ,
	MSG_ID_L4CCSM_CC_EMERGENCY_CALL_SETUP_REQ,
	MSG_ID_L4CCSM_CC_START_DTMF_REQ,
	MSG_ID_L4CCSM_CC_STOP_DTMF_REQ,
	MSG_ID_L4CCSM_CC_SAT_SETUP_REQ,
	MSG_ID_L4CCSM_CC_SAT_SEND_DTMF_REQ,
	MSG_ID_L4CCSM_CC_SAT_ABORT_DTMF_REQ,
	MSG_ID_L4CCSM_CC_SET_CSD_PROF_REQ,
	MSG_ID_L4CCSM_CC_UPDATE_ALS_REQ,
	MSG_ID_L4CCSM_CC_UART_TRANSFER_REQ,
	MSG_ID_L4CCSM_CC_REL_COMP_REQ,

	MSG_ID_SAT_CALL_CTRL_BY_SIM_CNF,

	MSG_ID_CSM_TDT_ACTIVATE_CNF,
	MSG_ID_CSM_TDT_DEACTIVATE_CNF,
	MSG_ID_CSM_TDT_ESC_ON_IND,
	MSG_ID_CSM_TDT_DISC_IND,
	MSG_ID_CSM_L2R_ACTIVATE_CNF,
	MSG_ID_CSM_L2R_DEACTIVATE_CNF,
	MSG_ID_CSM_L2R_XID_IND,
	MSG_ID_CSM_L2R_DISC_IND,
	MSG_ID_CSM_L2R_ESC_ON_IND,

   MSG_ID_CSM_T30_ACTIVATE_CNF,
   MSG_ID_CSM_T30_DEACTIVATE_CNF,
   MSG_ID_CSM_T30_FAX_RATE_CNF,
   MSG_ID_CSM_T30_DISC_IND,

   MSG_ID_L4CCSM_CISS_STARTUP_REQ,
   MSG_ID_L4CCSM_CISS_SS_PARSE_REQ,
   MSG_ID_L4CCSM_CISS_CF_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_CW_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_CB_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_EMLPP_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_CLI_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_CCBS_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_PUSSR_BEGIN_REQ,
   MSG_ID_L4CCSM_CISS_CB_FAC_RES,
   MSG_ID_L4CCSM_CISS_USSR_FAC_RES,
   MSG_ID_L4CCSM_CISS_USSN_FAC_RES,
   MSG_ID_L4CCSM_CISS_END_RES,
   MSG_ID_MNSS_BEGIN_IND,
   MSG_ID_MNSS_FAC_IND,
   MSG_ID_MNSS_END_IND,
   MSG_ID_SAT_SS_CTRL_BY_SIM_CNF,

   MSG_ID_CSM_TIMER_EXPIRY,
   MSG_ID_CSM_CODE_END  = MSG_ID_CSM_TIMER_EXPIRY,
	/*-----------------CSM_MSG_CODE_END-------------------------*/

	/*--------------- SMSAL_MSG_CODE_BEGIN----------------------*/
	MSG_ID_L4CSMSAL_INIT_REQ = MSG_ID_SMSAL_CODE_BEGIN,
	MSG_ID_L4CSMSAL_DE_INIT_REQ,
	MSG_ID_L4CSMSAL_DELETE_REQ,
	MSG_ID_L4CSMSAL_DE_PERSONALIZATION_ACK,
	MSG_ID_L4CSMSAL_READ_REQ,
	MSG_ID_L4CSMSAL_WRITE_REQ,
	MSG_ID_L4CSMSAL_SEND_REQ,
	MSG_ID_L4CSMSAL_SEND_FROM_STORAGE_REQ,
	MSG_ID_L4CSMSAL_SEND_ABORT,
	MSG_ID_L4CSMSAL_SET_PARAMETER_REQ,
	MSG_ID_L4CSMSAL_SET_COMMON_PARA_REQ,
	MSG_ID_L4CSMSAL_SET_PROFILE_PARA_REQ,
        MSG_ID_L4CSMSAL_SAT_SEND_REQ, /* SAT MO SMS */
        MSG_ID_L4CSMSAL_STARTUP_READ_NEXT_REQ,
        MSG_ID_L4CSMSAL_FDN_CHECK_RSP,
        MSG_ID_L4CSMSAL_COPY_MSG_REQ,
        MSG_ID_L4CSMSAL_SET_STATUS_REQ,


	/* MSGS FROM SMS */
	MSG_ID_SMS_DELIVER,
	MSG_ID_SMS_SUBMIT_REPORT_ACK,
	MSG_ID_SMS_SUBMIT_REPORT_NACK,
	MSG_ID_SMS_STATUS_REPORT,
	MSG_ID_SMS_SUBMIT_ABORT_CNF,
	MSG_ID_SMS_MEM_AVL_NOTIF_CNF,
	MSG_ID_SMS_MORE_MSG_SEND_IND,
	MSG_ID_SMSAL_TST_DELIVER,

	/* MSGS FROM SIM -- for SAT */
	MSG_ID_SAT_SMS_DL_CNF,
	MSG_ID_SAT_CB_DL_CNF,
        MSG_ID_SAT_SEND_SMS_CTRL_BY_SIM_CNF,

	MSG_ID_L4CSMSAL_CBCH_REQ,
	MSG_ID_L4CSMSAL_CB_UPDATE_REQ,
        MSG_ID_L4CSMSAL_HZ_CB_ACT_REQ,
        MSG_ID_SMSAL_AS_CB_PAGE_IND,
        MSG_ID_SMSAL_AS_CB_GS_CHANGE_IND,

#if defined(__MTK_3G_MRAT_ARCH__)
        MSG_ID_SMSAL_RATCM_CB_DATA_IND,
        MSG_ID_SMSAL_RATCM_CB_RECONFIG_IND,
#endif
	
	/* MSGS FROM SOC */
	MSG_ID_SMSAL_SOC_REG_PORT_REQ,
	MSG_ID_SMSAL_CODE_END = MSG_ID_SMSAL_SOC_REG_PORT_REQ,
	/*------------------ SMSAL_MSG_CODE_END --------------------*/

	/*------------------------SMU_MSG_CODE_BEGIN ---------------*/
	MSG_ID_L4CSMU_START_REQ = MSG_ID_SMU_CODE_BEGIN,
	MSG_ID_L4CSMU_SECURITY_REQ,
	MSG_ID_L4CSMU_SET_PERSONALIZATION_REQ, /* SML */
	MSG_ID_L4CSMU_SML_STATUS_REQ, /* SML */
	MSG_ID_L4CSMU_PLMN_SEL_WRITE_REQ,
	MSG_ID_L4CSMU_SIM_ACCESS_REQ,
	MSG_ID_L4CSMU_PUCT_WRITE_REQ,
	MSG_ID_L4CSMU_PUCT_READ_REQ,
	MSG_ID_L4CSMU_CSP_READ_REQ,
	MSG_ID_L4CSMU_DIAL_MODE_REQ,
	/*Benson 04212004 SATcE */
////	MSG_ID_L4CSAT_OPEN_CHANNEL_REQ,
////	MSG_ID_L4CSAT_SEND_DATA_REQ,
////	MSG_ID_L4CSAT_RECV_DATA_REQ,
        MSG_ID_FLC_STK_UL_APPDU_RESUME,
	MSG_ID_L4CSAT_SET_GPRS_DATA_ACCOUNT_RES,
	MSG_ID_L4CSAT_CSM_OPEN_CSD_RES,
	MSG_ID_L4CSAT_CC_CALL_DISC_RES,
	MSG_ID_L4CSAT_CSM_BEARER_INFO_IND_REQ,
	MSG_ID_L4CSAT_CC_CALL_DISC_IND_REQ,
	/*End SATcE*/	
        //mtk01616_070530 begin
       MSG_ID_L4CSMU_SAT_OPEN_CHANNEL_REQ,
       MSG_ID_L4CSMU_SAT_SEND_DATA_REQ,
       MSG_ID_L4CSMU_SAT_RECV_DATA_REQ,
       MSG_ID_L4CSMU_SAT_BEARER_PARA_REQ, // update csd or gprs bearer parameter for SIM
       MSG_ID_L4CSMU_SAT_SET_CSD_PROF_RES,
       MSG_ID_L4CSMU_SAT_SET_GPRS_PROF_RES,
       //mtk01616_070530 end

	MSG_ID_SMU_CODE_END = MSG_ID_L4CSAT_CC_CALL_DISC_RES,
	/*------------------------SMU_MSG_CODE_END -----------------*/

	/*------------------------UEM_MSG_CODE_BEGIN ---------------*/
	MSG_ID_DRVUEM_AUDIO_PLAY_FINISH_IND = MSG_ID_UEM_CODE_BEGIN,
	MSG_ID_DRVUEM_KEYPAD_IND,
	MSG_ID_DRVUEM_POWER_ON_IND,
	MSG_ID_DRVUEM_PMIC_IND,
	MSG_ID_DRVUEM_GPIO_DETECT_IND,
	MSG_ID_DRVUEM_RTC_PERIOD_IND,
#ifdef __USB_ENABLE__
    MSG_ID_DRVUEM_USBDETECT_IND,
#endif /* __USB_ENABLE__ */
	MSG_ID_L4CUEM_AUDIO_PLAY_BY_NAME_REQ,
	MSG_ID_L4CUEM_AUDIO_STOP_BY_NAME_REQ,
	MSG_ID_L4CUEM_AUDIO_PLAY_BY_STRING_REQ,
	MSG_ID_L4CUEM_AUDIO_STOP_BY_STRING_REQ,
	MSG_ID_L4CUEM_SET_PROFILE_REQ,
	MSG_ID_L4CUEM_STARTUP_REQ,
	MSG_ID_L4CUEM_SET_AUDIO_PROFILE_REQ,
	MSG_ID_L4CUEM_SET_AUDIO_PARAM_REQ,
	MSG_ID_L4CUEM_SET_HW_LEVEL_REQ,
   MSG_ID_L4CUEM_VM_RECORD_REQ,  /* voice memo related */
   MSG_ID_L4CUEM_VM_PLAY_REQ,
   MSG_ID_L4CUEM_VM_RENAME_REQ,
   MSG_ID_L4CUEM_VM_STOP_REQ,
   MSG_ID_L4CUEM_VM_DELETE_REQ,
   MSG_ID_L4CUEM_VM_ABORT_REQ,
   MSG_ID_L4CUEM_VM_PAUSE_REQ,
   MSG_ID_L4CUEM_VM_RESUME_REQ,
   MSG_ID_L4CUEM_VM_APPEND_REQ,
   MSG_ID_L4CUEM_VM_GET_INFO_REQ,
	MSG_ID_UEM_CODE_END = MSG_ID_L4CUEM_VM_GET_INFO_REQ,
	/*------------------------UEM_MSG_CODE_END -----------------*/

	/*------------------------RAC_MSG_CODE_BEGIN----------------*/
   MSG_ID_L4CRAC_ACT_REQ = MSG_ID_RAC_CODE_BEGIN,
   MSG_ID_L4CRAC_REG_REQ,
   MSG_ID_L4CRAC_PS_REG_REQ,
   MSG_ID_L4CRAC_DEREG_REQ,
   MSG_ID_L4CRAC_PLMN_LIST_REQ,
   MSG_ID_L4CRAC_CLASS_CHANGE_REQ,
   MSG_ID_L4CRAC_ABORT_LIST_REQ,
   MSG_ID_L4CRAC_SET_PREFERRED_BAND_REQ, //tommy add for band selection for vito
   MSG_ID_L4CRAC_RFOFF_REQ, /* Ripple */
   MSG_ID_L4CRAC_SIM_STATUS_UPDATE_REQ,
#ifdef __MTK_3G_MRAT_ARCH__ /* for RAC2 */      
   MSG_ID_L4CRAC_PLMN_SEARCH_REQ ,
   MSG_ID_L4CRAC_SET_RAT_MODE_REQ,
   MSG_ID_L4CRAC_PLMN_LIST_STOP_REQ,
   MSG_ID_L4CRAC_SET_PREFER_RAT_REQ,
#else /* for RAC */
   MSG_ID_L4CRAC_PLMN_SEL_REQ ,
#endif

   MSG_ID_GMMREG_ATTACH_CNF,
   MSG_ID_GMMREG_ATTACH_REJ,
   MSG_ID_GMMREG_DETACH_CNF,
   MSG_ID_GMMREG_DETACH_IND,
   MSG_ID_GMMREG_PLMN_LIST_IND,
   MSG_ID_GMMREG_NW_INFO_IND,
   MSG_ID_GMMREG_STATUS_IND,
   MSG_ID_GMMREG_CELL_INFO_UPDATE_IND,
   MSG_ID_GMMREG_PS_SERVICE_INFO_IND, /* For GPRS MMI information. */
   MSG_ID_GMMREG_CIPHER_IND, 
   MSG_ID_GMMREG_RFOFF_CNF, /* Ripple */
   MSG_ID_GMMREG_DEDICATED_MODE_IND, /* CH_Liang 2005/05/31 Homezone feature */
   MSG_ID_GMMREG_SEARCH_NORMAL_FINISH_IND, //__GEMINI__
   MSG_ID_GMMREG_RR_SERVICE_STATUS_IND,  //__GEMINI__ ,20080217
   /* 3G */   
   MSG_ID_GMMREG_SET_RAT_MODE_CNF, /* for MONZA */
   MSG_ID_GMMREG_PLMN_SEARCH_CNF, /* for MONZA */
   MSG_ID_GMMREG_PLMN_LIST_CNF, /* for MONZA */
   MSG_ID_GMMREG_PLMN_LIST_STOP_CNF, /* for MONZA */
   MSG_ID_GMMREG_BAND_SEL_CNF,

   MSG_ID_MMIAS_CELL_POWER_LEVEL_IND,
   MSG_ID_MMIAS_PKT_TRANSFER_MODE_IND, /*Byron: 2005/06/07/: send the pkt transfer mode indication to RAC*/
   MSG_ID_RAC_CODE_END = MSG_ID_MMIAS_PKT_TRANSFER_MODE_IND,

	/*------------------------RAC_MSG_CODE_END -----------------*/
	/*------------------------USAT_MSG_CODE_BEGIN --------------*/
	/*------------------------USAT_MSG_CODE_END ----------------*/
	/*------------------------PHB_MSG_CODE_BEGIN ---------------*/
	MSG_ID_L4CPHB_STARTUP_REQ = MSG_ID_PHB_CODE_BEGIN,
	MSG_ID_L4CPHB_INIT_LN_REQ,
	MSG_ID_L4CPHB_READ_REQ,
	MSG_ID_L4CPHB_ADD_REQ,
	MSG_ID_L4CPHB_UPDATE_REQ,
	MSG_ID_L4CPHB_DELETE_REQ,
	MSG_ID_L4CPHB_SEARCH_REQ,
	MSG_ID_L4CPHB_APPROVE_REQ,
	MSG_ID_L4CPHB_READ_LN_REQ,
	MSG_ID_L4CPHB_WRITE_LN_REQ,
	MSG_ID_L4CPHB_DELETE_LN_REQ,
	MSG_ID_L4CPHB_SYNC_REQ,
	MSG_ID_L4CPHB_STARTUP_READ_NEXT_REQ,
	MSG_ID_L4CPHB_WRITE_REQ,
	
	MSG_ID_L4CPHB_STARTUP_READ_NEXT_USIM_FIELD_REQ,
	MSG_ID_L4CPHB_READ_EMAIL_REQ,
	MSG_ID_L4CPHB_SET_GRP_REQ,	
        MSG_ID_L4CPHB_WRITE_USIM_REQ,

	MSG_ID_PHB_CODE_END = MSG_ID_L4CPHB_WRITE_USIM_REQ,
	/*------------------------PHB_MSG_CODE_END -----------------*/
	/*------------------------ENG_MSG_CODE_BEGIN ---------------*/
	/*------------------------ENG_MSG_CODE_END -----------------*/

   /*---------------L4_MSG_CODE_END---------------------*/


