/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*------------------------POC_MSG_CODE_BEGIN ---------------*/

   /* MSG FROM MMI */   
   MSG_ID_POC_REGISTER_REQ = POC_MSG_CODE_BEGIN,
   MSG_ID_POC_SETTING_REQ,
   MSG_ID_POC_TALK_INVITE_REQ,
   MSG_ID_POC_TALK_ANSWER_REQ,
   MSG_ID_POC_TALK_DISCONNECT_REQ,
   MSG_ID_POC_TALK_STATUS_SUBSCRIBE_REQ,  
   MSG_ID_POC_TALK_STATUS_NOTIFY_RES,
   MSG_ID_POC_FLOOR_TAKE_REQ,
   MSG_ID_POC_FLOOR_RELEASE_REQ,
   MSG_ID_POC_GROUP_INIT_REQ,
   MSG_ID_POC_GROUP_DEINIT_REQ,
   MSG_ID_POC_GET_GROUP_LIST_REQ,
   MSG_ID_POC_CREATE_GROUP_LIST_REQ,
   MSG_ID_POC_DEL_GROUP_LIST_REQ,
   MSG_ID_POC_UPDATE_GROUP_ENTRY_REQ,
   MSG_ID_POC_DEL_GROUP_ENTRY_REQ,
   MSG_ID_POC_GET_TALK_GROUP_LIST_REQ,
   MSG_ID_POC_CREATE_TALK_GROUP_LIST_REQ,
   MSG_ID_POC_DEL_TALK_GROUP_LIST_REQ,
   MSG_ID_POC_UPDATE_TALK_GROUP_ENTRY_REQ,
   MSG_ID_POC_DEL_TALK_GROUP_ENTRY_REQ,
   MSG_ID_POC_UPDATE_TALK_GROUP_PARAM_REQ,
   MSG_ID_POC_MEDIA_START_ENCODE_REQ,
   MSG_ID_POC_MEDIA_STOP_ENCODE_REQ,
   MSG_ID_POC_MEDIA_START_DECODE_REQ,
   MSG_ID_POC_MEDIA_STOP_DECODE_REQ,
   MSG_ID_POC_SEND_PERSONAL_ALERT_REQ,
   MSG_ID_POC_PRESENCE_SUBSCRIBE_REQ,
   MSG_ID_POC_PRESENCE_NOTIFY_RES,
   MSG_ID_POC_PRESENCE_PUBLISH_REQ,
      
   /* MSG TO MMI */   
   MSG_ID_POC_REGISTER_RSP,
   MSG_ID_POC_REGISTER_IND,
   MSG_ID_POC_SETTING_RSP,
   MSG_ID_POC_TALK_PROGRESS_IND,   
   MSG_ID_POC_TALK_INVITE_RSP,   
   MSG_ID_POC_TALK_CONNECT_IND,
   MSG_ID_POC_TALK_RING_IND,
   MSG_ID_POC_TALK_ANSWER_RSP,               
   MSG_ID_POC_TALK_DISCONNECT_RSP,
   MSG_ID_POC_TALK_DISCONNECT_IND,
   MSG_ID_POC_TALK_STATUS_SUBSCRIBE_RSP,
   MSG_ID_POC_TALK_STATUS_NOTIFY_IND,   
   MSG_ID_POC_FLOOR_GRANT_IND,
   MSG_ID_POC_FLOOR_TAKEN_IND,
   MSG_ID_POC_FLOOR_DENY_IND,
   MSG_ID_POC_FLOOR_IDLE_IND,
   MSG_ID_POC_FLOOR_REVOKE_IND,
   MSG_ID_POC_GROUP_INIT_RSP,
   MSG_ID_POC_GROUP_DEINIT_RSP,
   MSG_ID_POC_GET_GROUP_LIST_RSP,
   MSG_ID_POC_CREATE_GROUP_LIST_RSP,
   MSG_ID_POC_DEL_GROUP_LIST_RSP,
   MSG_ID_POC_UPDATE_GROUP_ENTRY_RSP,
   MSG_ID_POC_DEL_GROUP_ENTRY_RSP,
   MSG_ID_POC_GET_TALK_GROUP_LIST_RSP,
   MSG_ID_POC_CREATE_TALK_GROUP_LIST_RSP,
   MSG_ID_POC_DEL_TALK_GROUP_LIST_RSP,
   MSG_ID_POC_UPDATE_TALK_GROUP_ENTRY_RSP,
   MSG_ID_POC_DEL_TALK_GROUP_ENTRY_RSP,
   MSG_ID_POC_UPDATE_TALK_GROUP_PARAM_RSP,
   MSG_ID_POC_MEDIA_START_ENCODE_RSP,
   MSG_ID_POC_MEDIA_STOP_ENCODE_RSP,
   MSG_ID_POC_MEDIA_START_DECODE_RSP,
   MSG_ID_POC_MEDIA_STOP_DECODE_RSP,   
   MSG_ID_POC_NEW_PERSONAL_ALERT_IND,
   MSG_ID_POC_PRESENCE_SUBSCRIBE_RSP,
   MSG_ID_POC_PRESENCE_NOTIFY_IND,
   MSG_ID_POC_PRESENCE_PUBLISH_RSP,
   MSG_ID_POC_PRESENCE_PUBLISH_IND,
   MSG_ID_POC_SEND_PERSONAL_ALERT_RSP,
   
   /* MSG FROM L1 */
   MSG_ID_POC_MEDIA_ENCODED_IND,
/*------------------- POC_MSG_CODE_END----------------------*/
