/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *  MobileTVPlayerDefs.h
 *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  Mobile TV Player Applications v0.1
 *
 * Author:
 * -------
 * -------
 *                      
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

/****************************************************************************
* Include Files                                                                
*****************************************************************************/
#ifndef _MMI_MOBILE_TV_PLAYER_RES_DEF_H_
#define _MMI_MOBILE_TV_PLAYER_RES_DEF_H_

#define MMI_MOBILE_TV_PLAYER_BAND_TOTAL_COUNT              (STR_ID_MOBILE_TV_PLAYER_BAND_END-STR_ID_MOBILE_TV_PLAYER_BAND_START-1)

/***************************************************************************** 
* Screen ID enum
*****************************************************************************/
typedef enum
{
    SCR_ID_MOBILE_TV_PLAYER_APP = MOBILE_TV_PLAYER_BASE + 1,
    SCR_ID_MOBILE_TV_PLAYER_OPTION_MENU,
    SCR_ID_MOBILE_TV_PLAYER_OPTION_MENU_SETTING,
    SCR_ID_MOBILE_TV_PLAYER_CHANNEL_LIST,
    SCR_ID_MOBILE_TV_PLAYER_STORAGE,
    SCR_ID_MOBILE_TV_PLAYER_BAND,

    SCR_ID_MOBILE_TV_PLAYER_CHANNEL_LIST_OPTION,

    SCR_ID_MOBILE_TV_PLAYER_DISCARDING,
    SCR_ID_MOBILE_TV_PLAYER_SAVING,
    SCR_ID_MOBILE_TV_PLAYER_INITIALIZING,
    SCR_ID_MOBILE_TV_PLAYER_INIT_CHANNEL_LIST,

    SCR_ID_MOBILE_TV_PLAYER_TOTAL_COUNT
} mobile_tv_player_scr_id_enum;

/***************************************************************************** 
* String ID enum
*****************************************************************************/
typedef enum
{
    STR_ID_MOBILE_TV_PLAYER_APP_NAME = MOBILE_TV_PLAYER_BASE + 1,

    STR_ID_MOBILE_TV_PLAYER_CHANNEL_LIST,
    STR_ID_MOBILE_TV_PLAYER_SETTING,
    STR_ID_MOBILE_TV_PLAYER_STORAGE,
    STR_ID_MOBILE_TV_PLAYER_BAND,
    STR_ID_MOBILE_TV_PLAYER_PLAY,
    STR_ID_MOBILE_TV_PLAYER_UPDATE_LIST,

    /* settings */
    STR_ID_MOBILE_TV_PLAYER_SETTING_BRIGHTNESS,
    STR_ID_MOBILE_TV_PLAYER_SETTING_CONTRAST,
    STR_ID_MOBILE_TV_PLAYER_SETTING_PLAY_SPEED,

    STR_ID_MTV_PLAYER_PLAY_SPEED_10X,
    STR_ID_MTV_PLAYER_PLAY_SPEED_20X,
    STR_ID_MTV_PLAYER_PLAY_SPEED_5X,
   
    
    STR_ID_MOBILE_TV_PLAYER_ADJUST_START,
    STR_ID_MOBILE_TV_PLAYER_ADJUST_N5,
    STR_ID_MOBILE_TV_PLAYER_ADJUST_N4,
    STR_ID_MOBILE_TV_PLAYER_ADJUST_N3,
    STR_ID_MOBILE_TV_PLAYER_ADJUST_N2,
    STR_ID_MOBILE_TV_PLAYER_ADJUST_N1,
    STR_ID_MOBILE_TV_PLAYER_ADJUST_0,
    STR_ID_MOBILE_TV_PLAYER_ADJUST_P1,
    STR_ID_MOBILE_TV_PLAYER_ADJUST_P2,
    STR_ID_MOBILE_TV_PLAYER_ADJUST_P3,
    STR_ID_MOBILE_TV_PLAYER_ADJUST_P4,
    STR_ID_MOBILE_TV_PLAYER_ADJUST_P5,

    STR_ID_MOBILE_TV_PLAYER_SAVE_UNSAVED_RECORDING,
    STR_ID_MOBILE_TV_PLAYER_DISCARDING,
    STR_ID_MOBILE_TV_PLAYER_NOTIFY_SAVING,
    STR_ID_MOBILE_TV_PLAYER_NOTIFY_SAVE_FILE_ERROR,
    
    STR_ID_MOBILE_TV_PLAYER_NOTIFY_STORAGE_NOT_READY,
    STR_ID_MOBILE_TV_PLAYER_NOTIFY_WRITE_PROTECTION,
    STR_ID_MOBILE_TV_PLAYER_NOTIFY_HW_NOT_READY,
    STR_ID_MOBILE_TV_PLAYER_NOTIFY_ERROR,
    STR_ID_MOBILE_TV_PLAYER_NOTIFY_NO_CHANNELS_SCANNED,
    STR_ID_MOBILE_TV_PLAYER_NOTIFY_RECORDER_ERROR,

    STR_ID_MOBILE_TV_PLAYER_NOTIFY_INITIALIZING,
    STR_ID_MOBILE_TV_PLAYER_NOTIFY_INITIALIZING_ERROR,

    STR_ID_MOBILE_TV_PLAYER_TOTAL_COUNT
} mobile_tv_player_str_id_enum;

/***************** BAND *******************/
typedef enum
{
    STR_ID_MOBILE_TV_PLAYER_BAND_START = STR_ID_MOBILE_TV_PLAYER_TOTAL_COUNT,
    STR_ID_MOBILE_TV_PLAYER_BAND_TAIWAN,
    STR_ID_MOBILE_TV_PLAYER_BAND_KOREA,
    STR_ID_MOBILE_TV_PLAYER_BAND_CHINA,
    STR_ID_MOBILE_TV_PLAYER_BAND_JAPAN,
    STR_ID_MOBILE_TV_PLAYER_BAND_END
} mmi_mtv_player_band_id_enum;



/***************************************************************************** 
* Image ID enum
*****************************************************************************/
typedef enum
{
    IMG_ID_MOBILE_TV_PLAYER_APP_ICON = MOBILE_TV_PLAYER_BASE + 1,

    IMG_ID_MOBILE_TV_PLAYER_BG,
    IMG_ID_MOBILE_TV_PLAYER_BG_H,
    
    IMG_ID_MOBILE_TV_LOADING,
    /***********************************************************
    * Common Icon
    ***********************************************************/
    IMG_ID_MTV_PLAYER_CHANNEL_NEXT_UP,
    IMG_ID_MTV_PLAYER_CHANNEL_NEXT_DOWN,
    IMG_ID_MTV_PLAYER_CHANNEL_NEXT_UP_H,
    IMG_ID_MTV_PLAYER_CHANNEL_NEXT_DOWN_H,

    IMG_ID_MTV_PLAYER_CHANNEL_PREV_UP,
    IMG_ID_MTV_PLAYER_CHANNEL_PREV_DOWN,
    IMG_ID_MTV_PLAYER_CHANNEL_PREV_UP_H,
    IMG_ID_MTV_PLAYER_CHANNEL_PREV_DOWN_H,

    IMG_ID_MTV_PLAYER_FULLSCREEN_UP,
    IMG_ID_MTV_PLAYER_FULLSCREEN_DOWN,
    IMG_ID_MTV_PLAYER_FULLSCREEN_UP_H,
    IMG_ID_MTV_PLAYER_FULLSCREEN_DOWN_H,

    IMG_ID_MTV_PLAYER_INTERACTION_UP,
    IMG_ID_MTV_PLAYER_INTERACTION_DOWN,
    IMG_ID_MTV_PLAYER_INTERACTION_UP_H,
    IMG_ID_MTV_PLAYER_INTERACTION_DOWN_H,

    IMG_ID_MTV_PLAYER_PAUSE_UP,
    IMG_ID_MTV_PLAYER_PAUSE_DOWN,
    IMG_ID_MTV_PLAYER_PAUSE_UP_H,
    IMG_ID_MTV_PLAYER_PAUSE_DOWN_H,

    IMG_ID_MTV_PLAYER_PLAY_UP,
    IMG_ID_MTV_PLAYER_PLAY_DOWN,
    IMG_ID_MTV_PLAYER_PLAY_UP_H,
    IMG_ID_MTV_PLAYER_PLAY_DOWN_H,

    IMG_ID_MTV_PLAYER_STOP_UP,
    IMG_ID_MTV_PLAYER_STOP_DOWN,
    IMG_ID_MTV_PLAYER_STOP_UP_H,
    IMG_ID_MTV_PLAYER_STOP_DOWN_H,

    IMG_ID_MTV_PLAYER_FORWARD_UP,
    IMG_ID_MTV_PLAYER_FORWARD_DOWN,
    IMG_ID_MTV_PLAYER_FORWARD_UP_H,
    IMG_ID_MTV_PLAYER_FORWARD_DOWN_H,

    IMG_ID_MTV_PLAYER_REWIND_UP,
    IMG_ID_MTV_PLAYER_REWIND_DOWN,
    IMG_ID_MTV_PLAYER_REWIND_UP_H,
    IMG_ID_MTV_PLAYER_REWIND_DOWN_H,

    IMG_ID_MTV_PLAYER_RECORD_UP,
    IMG_ID_MTV_PLAYER_RECORD_DOWN,
    IMG_ID_MTV_PLAYER_RECORD_UP_H,
    IMG_ID_MTV_PLAYER_RECORD_DOWN_H,

    IMG_ID_MTV_PLAYER_VOL_INC_UP,
    IMG_ID_MTV_PLAYER_VOL_INC_DOWN,
    IMG_ID_MTV_PLAYER_VOL_INC_UP_H,
    IMG_ID_MTV_PLAYER_VOL_INC_DOWN_H,

    IMG_ID_MTV_PLAYER_VOL_DEC_UP,
    IMG_ID_MTV_PLAYER_VOL_DEC_DOWN,
    IMG_ID_MTV_PLAYER_VOL_DEC_UP_H,
    IMG_ID_MTV_PLAYER_VOL_DEC_DOWN_H,

    IMG_ID_MTV_PROGRESS_IND,
    IMG_ID_MTV_PROGRESS_FILL,
    IMG_ID_MTV_PROGRESS_BAR,
    IMG_ID_MTV_PROGRESS_IND_H,
    IMG_ID_MTV_PROGRESS_FILL_H,
    IMG_ID_MTV_PROGRESS_BAR_H,

    IMG_ID_MTV_PLAYER_NUM_0,
    IMG_ID_MTV_PLAYER_NUM_1,
    IMG_ID_MTV_PLAYER_NUM_2,
    IMG_ID_MTV_PLAYER_NUM_3,
    IMG_ID_MTV_PLAYER_NUM_4,
    IMG_ID_MTV_PLAYER_NUM_5,
    IMG_ID_MTV_PLAYER_NUM_6,
    IMG_ID_MTV_PLAYER_NUM_7,
    IMG_ID_MTV_PLAYER_NUM_8,
    IMG_ID_MTV_PLAYER_NUM_9,


    IMG_ID_MOBILE_TV_PLAYER_TOTAL_COUNT
} mobile_tv_player_img_id_enum;

typedef enum
{
    IMG_ID_MTV_PLAYER_PLAY_SPEED_10X = IMG_ID_MOBILE_TV_PLAYER_TOTAL_COUNT,
    IMG_ID_MTV_PLAYER_PLAY_SPEED_20X,
    IMG_ID_MTV_PLAYER_PLAY_SPEED_5X,
    
    IMG_ID_MTV_PLAYER_PLAY_SPEED_TOTAL_COUNT
} mobile_tv_player_play_speed_enum;

typedef enum
{
    IMG_ID_MTV_PLAYER_PLAY_SPEED_10X_H = IMG_ID_MTV_PLAYER_PLAY_SPEED_TOTAL_COUNT,
    IMG_ID_MTV_PLAYER_PLAY_SPEED_20X_H,
    IMG_ID_MTV_PLAYER_PLAY_SPEED_5X_H,
    
    IMG_ID_MTV_PLAYER_PLAY_SPEED_H_TOTAL_COUNT
} mobile_tv_player_play_speed_h_enum;

typedef enum
{
    IMG_ID_MTV_PLAYER_VOL_LEVEL_1 = IMG_ID_MTV_PLAYER_PLAY_SPEED_H_TOTAL_COUNT,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_2,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_3,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_4,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_5,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_6,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_7,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_8,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_9,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_10,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_11,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_12,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_13,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_14,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_15,
    IMG_ID_MTV_PLAYER_VOL_LEVEL_16,
    IMG_ID_MTV_PLAYER_VOL_MUTE,
    IMG_ID_MTV_PLAYER_VOL_TOTAL_COUNT
} mobile_tv_player_vol_enum;

typedef enum
{
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_1 = IMG_ID_MTV_PLAYER_VOL_TOTAL_COUNT,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_2,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_3,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_4,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_5,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_6,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_7,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_8,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_9,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_10,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_11,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_12,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_13,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_14,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_15,
    IMG_ID_MTV_PLAYER_VOL_H_LEVEL_16,
    IMG_ID_MTV_PLAYER_VOL_H_MUTE,
    IMG_ID_MTV_PLAYER_VOL_H_TOTAL_COUNT
} mobile_tv_player_vol_h_enum;

typedef enum
{
    IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_1 = IMG_ID_MTV_PLAYER_VOL_H_TOTAL_COUNT,
    IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_2,
    IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_3,
    IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_4,

    IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_TOTAL_COUNT
}mobile_tv_player_signal_level_enum;



#endif /* _MMI_MOBILE_TV_PLAYER_RES_DEF_H_ */

