#include "CustDataRes.h" 
#include "CustNFBProgressImg.h" 
const U8* nfb_progress_images[]={
(U8*)&__MAINLCD__UIELEMENT__PROGRESSBAR__PROGRESS_BAR_PBM,
(U8*)&__MAINLCD__UIELEMENT__PROGRESSBAR__0_PBM,
(U8*)&__MAINLCD__UIELEMENT__PROGRESSBAR__1_PBM,
(U8*)&__MAINLCD__UIELEMENT__PROGRESSBAR__2_PBM,
(U8*)&__MAINLCD__UIELEMENT__PROGRESSBAR__3_PBM,
(U8*)&__MAINLCD__UIELEMENT__PROGRESSBAR__4_PBM,
(U8*)&__MAINLCD__UIELEMENT__PROGRESSBAR__5_PBM,
(U8*)&__MAINLCD__UIELEMENT__PROGRESSBAR__6_PBM,
(U8*)&__MAINLCD__UIELEMENT__PROGRESSBAR__7_PBM,
(U8*)&__MAINLCD__UIELEMENT__PROGRESSBAR__8_PBM,
(U8*)&__MAINLCD__UIELEMENT__PROGRESSBAR__9_PBM,
(U8*)&__MAINLCD__UIELEMENT__PROGRESSBAR__PERCENT_PBM,

};
