/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   wgui_virtual_keyboard.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Virtual keyboard - WGUI integration
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

/*
 * This file contains internal UI component API, and is intended to be used by category screen module only. 
 * It's not recommended to be included in application code directly. 
 * For application developers, please include category screen header files instead (e.g., wgui_categories.h).
*/


#ifndef __WGUI_VIRTUAL_KEYBOARD_H__
#define __WGUI_VIRTUAL_KEYBOARD_H__

#include "gui_virtual_keyboard.h"
#include "wgui.h"

#ifdef __MMI_MAINLCD_240X320__

#define  MMI_VKBD_MATRIX_KEY_WIDTH              19
#define  MMI_VKBD_MATRIX_KEY_HEIGHT             19
#define  MMI_VKBD_MATRIX_KEY_H_GAP              1
#define  MMI_VKBD_MATRIX_KEY_V_GAP              1

#define  MATRIX_WIDTH(col)       ((col)*(MMI_VKBD_MATRIX_KEY_WIDTH+MMI_VKBD_MATRIX_KEY_H_GAP) - MMI_VKBD_MATRIX_KEY_H_GAP)
#define  MATRIX_HEIGHT(row)      ((row)*(MMI_VKBD_MATRIX_KEY_HEIGHT+MMI_VKBD_MATRIX_KEY_V_GAP) - MMI_VKBD_MATRIX_KEY_V_GAP)

#define  MATRIX_WIDTH_EXT(col, key_width, h_gap)   ( (col) * ((key_width) + (h_gap)) - (h_gap) )
#define  MATRIX_HEIGHT_EXT(row, key_height, v_gap) ( (row) * ((key_height) + (v_gap)) - (v_gap) )

#define  MMI_VKBD_STANDARD_WIDTH                240
#define  MMI_VKBD_STANDARD_HEIGHT               63
/* matrix layout at the left side */
#define  MMI_VKBD_STANDARD_MATRIX_COLUMN        7
#define  MMI_VKBD_STANDARD_MATRIX_ROW           3
#define  MMI_VKBD_STANDARD_MATRIX_X             1
#define  MMI_VKBD_STANDARD_MATRIX_Y             2
#define  MMI_VKBD_STANDARD_MATRIX_WIDTH         MATRIX_WIDTH(7)
#define  MMI_VKBD_STANDARD_MATRIX_HEIGHT        MATRIX_HEIGHT(3)

#define  MMI_VKBD_EXTENDED_WIDTH                240
#define  MMI_VKBD_EXTENDED_HEIGHT               83
/* matrix layout at the left side */
#define  MMI_VKBD_EXTENDED_MATRIX_COLUMN        8
#define  MMI_VKBD_EXTENDED_MATRIX_ROW           4
#define  MMI_VKBD_EXTENDED_MATRIX_X             1
#define  MMI_VKBD_EXTENDED_MATRIX_Y             2
#define  MMI_VKBD_EXTENDED_MATRIX_WIDTH         MATRIX_WIDTH(8)
#define  MMI_VKBD_EXTENDED_MATRIX_HEIGHT        MATRIX_HEIGHT(4)

#define  MMI_VKBD_TRAY_WIDTH                    240
#define  MMI_VKBD_TRAY_HEIGHT                   23
/* matrix layout at the left side */
#define  MMI_VKBD_TRAY_MATRIX_COLUMN            5
#define  MMI_VKBD_TRAY_MATRIX_ROW               1
#define  MMI_VKBD_TRAY_MATRIX_X                 1
#define  MMI_VKBD_TRAY_MATRIX_Y                 2
#define  MMI_VKBD_TRAY_MATRIX_WIDTH             MATRIX_WIDTH(5)
#define  MMI_VKBD_TRAY_MATRIX_HEIGHT            MATRIX_HEIGHT(1)

#define  MMI_VKBD_NUMBER_WIDTH                  240
#define  MMI_VKBD_NUMBER_HEIGHT                 43
/* matrix layout at the left side */
#define  MMI_VKBD_NUMBER_MATRIX_COLUMN          8
#define  MMI_VKBD_NUMBER_MATRIX_ROW             2
#define  MMI_VKBD_NUMBER_MATRIX_X               1
#define  MMI_VKBD_NUMBER_MATRIX_Y               2
#define  MMI_VKBD_NUMBER_MATRIX_WIDTH           MATRIX_WIDTH(8)
#define  MMI_VKBD_NUMBER_MATRIX_HEIGHT          MATRIX_HEIGHT(2)

#define  MMI_VKBD_PINYIN_WIDTH                  240
#define  MMI_VKBD_PINYIN_HEIGHT                 83
/* matrix layout at the left-bottom */
#define  MMI_VKBD_PINYIN_MATRIX_COLUMN          9
#define  MMI_VKBD_PINYIN_MATRIX_ROW             3
#define  MMI_VKBD_PINYIN_MATRIX_X               1
#define  MMI_VKBD_PINYIN_MATRIX_Y               22
#define  MMI_VKBD_PINYIN_MATRIX_WIDTH           MATRIX_WIDTH(9)
#define  MMI_VKBD_PINYIN_MATRIX_HEIGHT          MATRIX_HEIGHT(3)

#define  MMI_VKBD_BOPOMO_WIDTH                  240
#define  MMI_VKBD_BOPOMO_HEIGHT                 83
/* matrix layout at the left-bottom */
#define  MMI_VKBD_BOPOMO_MATRIX_COLUMN          10
#define  MMI_VKBD_BOPOMO_MATRIX_ROW             3
#define  MMI_VKBD_BOPOMO_MATRIX_X               1
#define  MMI_VKBD_BOPOMO_MATRIX_Y               22
#define  MMI_VKBD_BOPOMO_MATRIX_WIDTH           MATRIX_WIDTH(10)
#define  MMI_VKBD_BOPOMO_MATRIX_HEIGHT          MATRIX_HEIGHT(3)


#define  MMI_VKBD_CZECH_WIDTH                  240        
#define  MMI_VKBD_CZECH_HEIGHT                 83
/* matrix layout at the left-bottom */
#define  MMI_VKBD_CZECH_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_CZECH_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_CZECH_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_CZECH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_CZECH_MATRIX_COLUMN          7
#define  MMI_VKBD_CZECH_MATRIX_ROW             4
#define  MMI_VKBD_CZECH_MATRIX_X               1
#define  MMI_VKBD_CZECH_MATRIX_Y               2
#define  MMI_VKBD_CZECH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_CZECH_MATRIX_COLUMN, MMI_VKBD_CZECH_MATRIX_KEY_WIDTH, MMI_VKBD_CZECH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_CZECH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_CZECH_MATRIX_ROW, MMI_VKBD_CZECH_MATRIX_KEY_HEIGHT, MMI_VKBD_CZECH_MATRIX_KEY_V_GAP)


#define  MMI_VKBD_HEBREW_WIDTH                  240        
#define  MMI_VKBD_HEBREW_HEIGHT                 63
/* matrix layout at the left-bottom */
#define  MMI_VKBD_HEBREW_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_HEBREW_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_HEBREW_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_HEBREW_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_HEBREW_MATRIX_COLUMN          8
#define  MMI_VKBD_HEBREW_MATRIX_ROW             3
#define  MMI_VKBD_HEBREW_MATRIX_X               1
#define  MMI_VKBD_HEBREW_MATRIX_Y               2
#define  MMI_VKBD_HEBREW_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_HEBREW_MATRIX_COLUMN, MMI_VKBD_HEBREW_MATRIX_KEY_WIDTH, MMI_VKBD_HEBREW_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_HEBREW_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_HEBREW_MATRIX_ROW, MMI_VKBD_HEBREW_MATRIX_KEY_HEIGHT, MMI_VKBD_HEBREW_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_FARSI_WIDTH                  240        
#define  MMI_VKBD_FARSI_HEIGHT                 83
/* matrix layout at the left-bottom */
#define  MMI_VKBD_FARSI_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_FARSI_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_FARSI_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_FARSI_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_FARSI_MATRIX_COLUMN          9
#define  MMI_VKBD_FARSI_MATRIX_ROW             4
#define  MMI_VKBD_FARSI_MATRIX_X               1
#define  MMI_VKBD_FARSI_MATRIX_Y               2
#define  MMI_VKBD_FARSI_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_FARSI_MATRIX_COLUMN, MMI_VKBD_FARSI_MATRIX_KEY_WIDTH, MMI_VKBD_FARSI_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_FARSI_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_FARSI_MATRIX_ROW, MMI_VKBD_FARSI_MATRIX_KEY_HEIGHT, MMI_VKBD_FARSI_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_FARSI_SYMBOL_WIDTH                  240        
#define  MMI_VKBD_FARSI_SYMBOL_HEIGHT                 103
/* matrix layout at the left-bottom */
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_COLUMN          9
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_ROW             5
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_X               1
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_Y               2
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_FARSI_SYMBOL_MATRIX_COLUMN, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_WIDTH, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_FARSI_SYMBOL_MATRIX_ROW, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_HEIGHT, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_GREEK_WIDTH                  240        
#define  MMI_VKBD_GREEK_HEIGHT                 63
/* matrix layout at the left-bottom */
#define  MMI_VKBD_GREEK_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_GREEK_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_GREEK_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_GREEK_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_GREEK_MATRIX_COLUMN          7
#define  MMI_VKBD_GREEK_MATRIX_ROW             3
#define  MMI_VKBD_GREEK_MATRIX_X               1
#define  MMI_VKBD_GREEK_MATRIX_Y               2
#define  MMI_VKBD_GREEK_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_GREEK_MATRIX_COLUMN, MMI_VKBD_GREEK_MATRIX_KEY_WIDTH, MMI_VKBD_GREEK_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_GREEK_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_GREEK_MATRIX_ROW, MMI_VKBD_GREEK_MATRIX_KEY_HEIGHT, MMI_VKBD_GREEK_MATRIX_KEY_V_GAP)


#define  MMI_VKBD_BULGARIAN_WIDTH                  240        
#define  MMI_VKBD_BULGARIAN_HEIGHT                 83
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_BULGARIAN_MATRIX_COLUMN          7
#define  MMI_VKBD_BULGARIAN_MATRIX_ROW             4
#define  MMI_VKBD_BULGARIAN_MATRIX_X               1
#define  MMI_VKBD_BULGARIAN_MATRIX_Y               2
#define  MMI_VKBD_BULGARIAN_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_BULGARIAN_MATRIX_COLUMN, MMI_VKBD_BULGARIAN_MATRIX_KEY_WIDTH, MMI_VKBD_BULGARIAN_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_BULGARIAN_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_BULGARIAN_MATRIX_ROW, MMI_VKBD_BULGARIAN_MATRIX_KEY_HEIGHT, MMI_VKBD_BULGARIAN_MATRIX_KEY_V_GAP)


#define  MMI_VKBD_DANISH_WIDTH                  240        
#define  MMI_VKBD_DANISH_HEIGHT                 63
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_DANISH_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_DANISH_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_DANISH_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_DANISH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_DANISH_MATRIX_COLUMN          7
#define  MMI_VKBD_DANISH_MATRIX_ROW             3
#define  MMI_VKBD_DANISH_MATRIX_X               1
#define  MMI_VKBD_DANISH_MATRIX_Y               2
#define  MMI_VKBD_DANISH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_DANISH_MATRIX_COLUMN, MMI_VKBD_DANISH_MATRIX_KEY_WIDTH, MMI_VKBD_DANISH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_DANISH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_DANISH_MATRIX_ROW, MMI_VKBD_DANISH_MATRIX_KEY_HEIGHT, MMI_VKBD_DANISH_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_HUNGARIAN_WIDTH                  240        
#define  MMI_VKBD_HUNGARIAN_HEIGHT                 83
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_HUNGARIAN_MATRIX_COLUMN          7
#define  MMI_VKBD_HUNGARIAN_MATRIX_ROW             4
#define  MMI_VKBD_HUNGARIAN_MATRIX_X               1
#define  MMI_VKBD_HUNGARIAN_MATRIX_Y               2
#define  MMI_VKBD_HUNGARIAN_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_HUNGARIAN_MATRIX_COLUMN, MMI_VKBD_HUNGARIAN_MATRIX_KEY_WIDTH, MMI_VKBD_HUNGARIAN_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_HUNGARIAN_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_HUNGARIAN_MATRIX_ROW, MMI_VKBD_HUNGARIAN_MATRIX_KEY_HEIGHT, MMI_VKBD_HUNGARIAN_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_FINNISH_WIDTH                  240        
#define  MMI_VKBD_FINNISH_HEIGHT                 63
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_FINNISH_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_FINNISH_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_FINNISH_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_FINNISH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_FINNISH_MATRIX_COLUMN          8
#define  MMI_VKBD_FINNISH_MATRIX_ROW             3
#define  MMI_VKBD_FINNISH_MATRIX_X               1
#define  MMI_VKBD_FINNISH_MATRIX_Y               2
#define  MMI_VKBD_FINNISH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_FINNISH_MATRIX_COLUMN, MMI_VKBD_FINNISH_MATRIX_KEY_WIDTH, MMI_VKBD_FINNISH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_FINNISH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_FINNISH_MATRIX_ROW, MMI_VKBD_FINNISH_MATRIX_KEY_HEIGHT, MMI_VKBD_FINNISH_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_POLISH_WIDTH                  240        
#define  MMI_VKBD_POLISH_HEIGHT                 83
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_POLISH_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_POLISH_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_POLISH_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_POLISH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_POLISH_MATRIX_COLUMN          7
#define  MMI_VKBD_POLISH_MATRIX_ROW             4
#define  MMI_VKBD_POLISH_MATRIX_X               1
#define  MMI_VKBD_POLISH_MATRIX_Y               2
#define  MMI_VKBD_POLISH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_POLISH_MATRIX_COLUMN, MMI_VKBD_POLISH_MATRIX_KEY_WIDTH, MMI_VKBD_POLISH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_POLISH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_POLISH_MATRIX_ROW, MMI_VKBD_POLISH_MATRIX_KEY_HEIGHT, MMI_VKBD_POLISH_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_VIETNAMESE_WIDTH                  240        
#define  MMI_VKBD_VIETNAMESE_HEIGHT                 83
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_VIETNAMESE_MATRIX_COLUMN          5   
#define  MMI_VKBD_VIETNAMESE_MATRIX_ROW             4
#define  MMI_VKBD_VIETNAMESE_MATRIX_X               1
#define  MMI_VKBD_VIETNAMESE_MATRIX_Y               2
#define  MMI_VKBD_VIETNAMESE_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_VIETNAMESE_MATRIX_COLUMN, MMI_VKBD_VIETNAMESE_MATRIX_KEY_WIDTH, MMI_VKBD_VIETNAMESE_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_VIETNAMESE_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_VIETNAMESE_MATRIX_ROW, MMI_VKBD_VIETNAMESE_MATRIX_KEY_HEIGHT, MMI_VKBD_VIETNAMESE_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_ARABIC_WIDTH                  240        
#define  MMI_VKBD_ARABIC_HEIGHT                 83
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_ARABIC_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_ARABIC_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_ARABIC_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_ARABIC_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_ARABIC_MATRIX_COLUMN          5   
#define  MMI_VKBD_ARABIC_MATRIX_ROW             4
#define  MMI_VKBD_ARABIC_MATRIX_X               1
#define  MMI_VKBD_ARABIC_MATRIX_Y               2
#define  MMI_VKBD_ARABIC_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_ARABIC_MATRIX_COLUMN, MMI_VKBD_ARABIC_MATRIX_KEY_WIDTH, MMI_VKBD_ARABIC_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_ARABIC_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_ARABIC_MATRIX_ROW, MMI_VKBD_ARABIC_MATRIX_KEY_HEIGHT, MMI_VKBD_ARABIC_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_THAI_WIDTH                  240        
#define  MMI_VKBD_THAI_HEIGHT                 83
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_THAI_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_THAI_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_THAI_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_THAI_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_THAI_MATRIX_COLUMN          10   
#define  MMI_VKBD_THAI_MATRIX_ROW             4
#define  MMI_VKBD_THAI_MATRIX_X               1
#define  MMI_VKBD_THAI_MATRIX_Y               2
#define  MMI_VKBD_THAI_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_THAI_MATRIX_COLUMN, MMI_VKBD_THAI_MATRIX_KEY_WIDTH, MMI_VKBD_THAI_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_THAI_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_THAI_MATRIX_ROW, MMI_VKBD_THAI_MATRIX_KEY_HEIGHT, MMI_VKBD_THAI_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_ARABIC_SYMBOL_WIDTH                  240        
#define  MMI_VKBD_ARABIC_SYMBOL_HEIGHT                 83
/* matrix layout at the left-bottom */
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_COLUMN          5
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_ROW             4
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_X               1
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_Y               2
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_ARABIC_SYMBOL_MATRIX_COLUMN, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_WIDTH, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_ARABIC_SYMBOL_MATRIX_ROW, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_HEIGHT, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_UKRAINIAN_WIDTH                  240        
#define  MMI_VKBD_UKRAINIAN_HEIGHT                 83
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_WIDTH       19
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_HEIGHT      19
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_UKRAINIAN_MATRIX_COLUMN          5   
#define  MMI_VKBD_UKRAINIAN_MATRIX_ROW             4
#define  MMI_VKBD_UKRAINIAN_MATRIX_X               1
#define  MMI_VKBD_UKRAINIAN_MATRIX_Y               2
#define  MMI_VKBD_UKRAINIAN_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_UKRAINIAN_MATRIX_COLUMN, MMI_VKBD_UKRAINIAN_MATRIX_KEY_WIDTH, MMI_VKBD_UKRAINIAN_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_UKRAINIAN_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_UKRAINIAN_MATRIX_ROW, MMI_VKBD_UKRAINIAN_MATRIX_KEY_HEIGHT, MMI_VKBD_UKRAINIAN_MATRIX_KEY_V_GAP)

#elif defined(__MMI_MAINLCD_176X220__)

#define  MMI_VKBD_MATRIX_KEY_WIDTH              14
#define  MMI_VKBD_MATRIX_KEY_HEIGHT             14
#define  MMI_VKBD_MATRIX_KEY_H_GAP              1
#define  MMI_VKBD_MATRIX_KEY_V_GAP              1

#define  MATRIX_WIDTH(col)       ((col)*(MMI_VKBD_MATRIX_KEY_WIDTH+MMI_VKBD_MATRIX_KEY_H_GAP) - MMI_VKBD_MATRIX_KEY_H_GAP)
#define  MATRIX_HEIGHT(row)      ((row)*(MMI_VKBD_MATRIX_KEY_HEIGHT+MMI_VKBD_MATRIX_KEY_V_GAP) - MMI_VKBD_MATRIX_KEY_V_GAP)

#define  MATRIX_WIDTH_EXT(col, key_width, h_gap)   ( (col) * ((key_width) + (h_gap)) - (h_gap) )
#define  MATRIX_HEIGHT_EXT(row, key_height, v_gap) ( (row) * ((key_height) + (v_gap)) - (v_gap) )

#define  MMI_VKBD_STANDARD_WIDTH                176
#define  MMI_VKBD_STANDARD_HEIGHT               46
/* matrix layout at the left side */
#define  MMI_VKBD_STANDARD_MATRIX_COLUMN        7
#define  MMI_VKBD_STANDARD_MATRIX_ROW           3
#define  MMI_VKBD_STANDARD_MATRIX_X             1
#define  MMI_VKBD_STANDARD_MATRIX_Y             1
#define  MMI_VKBD_STANDARD_MATRIX_WIDTH         MATRIX_WIDTH(7)
#define  MMI_VKBD_STANDARD_MATRIX_HEIGHT        MATRIX_HEIGHT(3)

#define  MMI_VKBD_EXTENDED_WIDTH                176
#define  MMI_VKBD_EXTENDED_HEIGHT               61
/* matrix layout at the left side */
#define  MMI_VKBD_EXTENDED_MATRIX_COLUMN        8
#define  MMI_VKBD_EXTENDED_MATRIX_ROW           4
#define  MMI_VKBD_EXTENDED_MATRIX_X             1
#define  MMI_VKBD_EXTENDED_MATRIX_Y             1
#define  MMI_VKBD_EXTENDED_MATRIX_WIDTH         MATRIX_WIDTH(8)
#define  MMI_VKBD_EXTENDED_MATRIX_HEIGHT        MATRIX_HEIGHT(4)

#define  MMI_VKBD_TRAY_WIDTH                    176
#define  MMI_VKBD_TRAY_HEIGHT                   16
/* matrix layout at the left side */
#define  MMI_VKBD_TRAY_MATRIX_COLUMN            5
#define  MMI_VKBD_TRAY_MATRIX_ROW               1
#define  MMI_VKBD_TRAY_MATRIX_X                 1
#define  MMI_VKBD_TRAY_MATRIX_Y                 1
#define  MMI_VKBD_TRAY_MATRIX_WIDTH             MATRIX_WIDTH(5)
#define  MMI_VKBD_TRAY_MATRIX_HEIGHT            MATRIX_HEIGHT(1)

#define  MMI_VKBD_NUMBER_WIDTH                  176
#define  MMI_VKBD_NUMBER_HEIGHT                 31
/* matrix layout at the left side */
#define  MMI_VKBD_NUMBER_MATRIX_COLUMN          8
#define  MMI_VKBD_NUMBER_MATRIX_ROW             2
#define  MMI_VKBD_NUMBER_MATRIX_X               1
#define  MMI_VKBD_NUMBER_MATRIX_Y               1
#define  MMI_VKBD_NUMBER_MATRIX_WIDTH           MATRIX_WIDTH(8)
#define  MMI_VKBD_NUMBER_MATRIX_HEIGHT          MATRIX_HEIGHT(2)

#define  MMI_VKBD_PINYIN_WIDTH                  176
#define  MMI_VKBD_PINYIN_HEIGHT                 61
/* matrix layout at the left-bottom */
#define  MMI_VKBD_PINYIN_MATRIX_COLUMN          9
#define  MMI_VKBD_PINYIN_MATRIX_ROW             3
#define  MMI_VKBD_PINYIN_MATRIX_X               1
#define  MMI_VKBD_PINYIN_MATRIX_Y               16
#define  MMI_VKBD_PINYIN_MATRIX_WIDTH           MATRIX_WIDTH(9)
#define  MMI_VKBD_PINYIN_MATRIX_HEIGHT          MATRIX_HEIGHT(3)

#define  MMI_VKBD_BOPOMO_WIDTH                  176
#define  MMI_VKBD_BOPOMO_HEIGHT                 61
/* matrix layout at the left-bottom */
#define  MMI_VKBD_BOPOMO_MATRIX_COLUMN          10
#define  MMI_VKBD_BOPOMO_MATRIX_ROW             3
#define  MMI_VKBD_BOPOMO_MATRIX_X               1
#define  MMI_VKBD_BOPOMO_MATRIX_Y               16
#define  MMI_VKBD_BOPOMO_MATRIX_WIDTH           MATRIX_WIDTH(10)
#define  MMI_VKBD_BOPOMO_MATRIX_HEIGHT          MATRIX_HEIGHT(3)

#define  MMI_VKBD_CZECH_WIDTH                  176
#define  MMI_VKBD_CZECH_HEIGHT                 61
/* matrix layout at the left-bottom */
#define  MMI_VKBD_CZECH_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_CZECH_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_CZECH_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_CZECH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_CZECH_MATRIX_COLUMN          7
#define  MMI_VKBD_CZECH_MATRIX_ROW             4
#define  MMI_VKBD_CZECH_MATRIX_X               4
#define  MMI_VKBD_CZECH_MATRIX_Y               1
#define  MMI_VKBD_CZECH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_CZECH_MATRIX_COLUMN, MMI_VKBD_CZECH_MATRIX_KEY_WIDTH, MMI_VKBD_CZECH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_CZECH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_CZECH_MATRIX_ROW, MMI_VKBD_CZECH_MATRIX_KEY_HEIGHT, MMI_VKBD_CZECH_MATRIX_KEY_V_GAP)


#define  MMI_VKBD_HEBREW_WIDTH                  176        
#define  MMI_VKBD_HEBREW_HEIGHT                 46
/* matrix layout at the left-bottom */
#define  MMI_VKBD_HEBREW_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_HEBREW_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_HEBREW_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_HEBREW_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_HEBREW_MATRIX_COLUMN          8
#define  MMI_VKBD_HEBREW_MATRIX_ROW             3
#define  MMI_VKBD_HEBREW_MATRIX_X               1
#define  MMI_VKBD_HEBREW_MATRIX_Y               1
#define  MMI_VKBD_HEBREW_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_HEBREW_MATRIX_COLUMN, MMI_VKBD_HEBREW_MATRIX_KEY_WIDTH, MMI_VKBD_HEBREW_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_HEBREW_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_HEBREW_MATRIX_ROW, MMI_VKBD_HEBREW_MATRIX_KEY_HEIGHT, MMI_VKBD_HEBREW_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_FARSI_WIDTH                  176        
#define  MMI_VKBD_FARSI_HEIGHT                 61
/* matrix layout at the left-bottom */
#define  MMI_VKBD_FARSI_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_FARSI_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_FARSI_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_FARSI_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_FARSI_MATRIX_COLUMN          9
#define  MMI_VKBD_FARSI_MATRIX_ROW             4
#define  MMI_VKBD_FARSI_MATRIX_X               4
#define  MMI_VKBD_FARSI_MATRIX_Y               1
#define  MMI_VKBD_FARSI_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_FARSI_MATRIX_COLUMN, MMI_VKBD_FARSI_MATRIX_KEY_WIDTH, MMI_VKBD_FARSI_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_FARSI_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_FARSI_MATRIX_ROW, MMI_VKBD_FARSI_MATRIX_KEY_HEIGHT, MMI_VKBD_FARSI_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_FARSI_SYMBOL_WIDTH                  176        
#define  MMI_VKBD_FARSI_SYMBOL_HEIGHT                 76
/* matrix layout at the left-bottom */
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_COLUMN          9
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_ROW             5
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_X               4
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_Y               1
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_FARSI_SYMBOL_MATRIX_COLUMN, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_WIDTH, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_FARSI_SYMBOL_MATRIX_ROW, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_HEIGHT, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_GREEK_WIDTH                  176        
#define  MMI_VKBD_GREEK_HEIGHT                 46
/* matrix layout at the left-bottom */
#define  MMI_VKBD_GREEK_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_GREEK_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_GREEK_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_GREEK_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_GREEK_MATRIX_COLUMN          7
#define  MMI_VKBD_GREEK_MATRIX_ROW             3
#define  MMI_VKBD_GREEK_MATRIX_X               1
#define  MMI_VKBD_GREEK_MATRIX_Y               1
#define  MMI_VKBD_GREEK_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_GREEK_MATRIX_COLUMN, MMI_VKBD_GREEK_MATRIX_KEY_WIDTH, MMI_VKBD_GREEK_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_GREEK_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_GREEK_MATRIX_ROW, MMI_VKBD_GREEK_MATRIX_KEY_HEIGHT, MMI_VKBD_GREEK_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_BULGARIAN_WIDTH                  176       
#define  MMI_VKBD_BULGARIAN_HEIGHT                 61
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_BULGARIAN_MATRIX_COLUMN          7
#define  MMI_VKBD_BULGARIAN_MATRIX_ROW             4
#define  MMI_VKBD_BULGARIAN_MATRIX_X               0
#define  MMI_VKBD_BULGARIAN_MATRIX_Y               1
#define  MMI_VKBD_BULGARIAN_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_BULGARIAN_MATRIX_COLUMN, MMI_VKBD_BULGARIAN_MATRIX_KEY_WIDTH, MMI_VKBD_BULGARIAN_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_BULGARIAN_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_BULGARIAN_MATRIX_ROW, MMI_VKBD_BULGARIAN_MATRIX_KEY_HEIGHT, MMI_VKBD_BULGARIAN_MATRIX_KEY_V_GAP)


#define  MMI_VKBD_DANISH_WIDTH                  176        
#define  MMI_VKBD_DANISH_HEIGHT                 46
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_DANISH_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_DANISH_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_DANISH_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_DANISH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_DANISH_MATRIX_COLUMN          7
#define  MMI_VKBD_DANISH_MATRIX_ROW             3
#define  MMI_VKBD_DANISH_MATRIX_X               1
#define  MMI_VKBD_DANISH_MATRIX_Y               1
#define  MMI_VKBD_DANISH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_DANISH_MATRIX_COLUMN, MMI_VKBD_DANISH_MATRIX_KEY_WIDTH, MMI_VKBD_DANISH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_DANISH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_DANISH_MATRIX_ROW, MMI_VKBD_DANISH_MATRIX_KEY_HEIGHT, MMI_VKBD_DANISH_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_HUNGARIAN_WIDTH                  176        
#define  MMI_VKBD_HUNGARIAN_HEIGHT                 64
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_HUNGARIAN_MATRIX_COLUMN          7
#define  MMI_VKBD_HUNGARIAN_MATRIX_ROW             4
#define  MMI_VKBD_HUNGARIAN_MATRIX_X               4
#define  MMI_VKBD_HUNGARIAN_MATRIX_Y               1
#define  MMI_VKBD_HUNGARIAN_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_HUNGARIAN_MATRIX_COLUMN, MMI_VKBD_HUNGARIAN_MATRIX_KEY_WIDTH, MMI_VKBD_HUNGARIAN_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_HUNGARIAN_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_HUNGARIAN_MATRIX_ROW, MMI_VKBD_HUNGARIAN_MATRIX_KEY_HEIGHT, MMI_VKBD_HUNGARIAN_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_FINNISH_WIDTH                  176        
#define  MMI_VKBD_FINNISH_HEIGHT                 46
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_FINNISH_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_FINNISH_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_FINNISH_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_FINNISH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_FINNISH_MATRIX_COLUMN          8
#define  MMI_VKBD_FINNISH_MATRIX_ROW             3
#define  MMI_VKBD_FINNISH_MATRIX_X               1
#define  MMI_VKBD_FINNISH_MATRIX_Y               1
#define  MMI_VKBD_FINNISH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_FINNISH_MATRIX_COLUMN, MMI_VKBD_FINNISH_MATRIX_KEY_WIDTH, MMI_VKBD_FINNISH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_FINNISH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_FINNISH_MATRIX_ROW, MMI_VKBD_FINNISH_MATRIX_KEY_HEIGHT, MMI_VKBD_FINNISH_MATRIX_KEY_V_GAP)


#define  MMI_VKBD_POLISH_WIDTH                  176        
#define  MMI_VKBD_POLISH_HEIGHT                 61
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_POLISH_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_POLISH_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_POLISH_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_POLISH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_POLISH_MATRIX_COLUMN          7
#define  MMI_VKBD_POLISH_MATRIX_ROW             4
#define  MMI_VKBD_POLISH_MATRIX_X               1
#define  MMI_VKBD_POLISH_MATRIX_Y               1
#define  MMI_VKBD_POLISH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_POLISH_MATRIX_COLUMN, MMI_VKBD_POLISH_MATRIX_KEY_WIDTH, MMI_VKBD_POLISH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_POLISH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_POLISH_MATRIX_ROW, MMI_VKBD_POLISH_MATRIX_KEY_HEIGHT, MMI_VKBD_POLISH_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_VIETNAMESE_WIDTH                  176        
#define  MMI_VKBD_VIETNAMESE_HEIGHT                 61
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_VIETNAMESE_MATRIX_COLUMN          5   
#define  MMI_VKBD_VIETNAMESE_MATRIX_ROW             4
#define  MMI_VKBD_VIETNAMESE_MATRIX_X               0
#define  MMI_VKBD_VIETNAMESE_MATRIX_Y               1
#define  MMI_VKBD_VIETNAMESE_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_VIETNAMESE_MATRIX_COLUMN, MMI_VKBD_VIETNAMESE_MATRIX_KEY_WIDTH, MMI_VKBD_VIETNAMESE_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_VIETNAMESE_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_VIETNAMESE_MATRIX_ROW, MMI_VKBD_VIETNAMESE_MATRIX_KEY_HEIGHT, MMI_VKBD_VIETNAMESE_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_ARABIC_WIDTH                  176        
#define  MMI_VKBD_ARABIC_HEIGHT                 61
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_ARABIC_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_ARABIC_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_ARABIC_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_ARABIC_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_ARABIC_MATRIX_COLUMN          5   
#define  MMI_VKBD_ARABIC_MATRIX_ROW             4
#define  MMI_VKBD_ARABIC_MATRIX_X               1
#define  MMI_VKBD_ARABIC_MATRIX_Y               1
#define  MMI_VKBD_ARABIC_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_ARABIC_MATRIX_COLUMN, MMI_VKBD_ARABIC_MATRIX_KEY_WIDTH, MMI_VKBD_ARABIC_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_ARABIC_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_ARABIC_MATRIX_ROW, MMI_VKBD_ARABIC_MATRIX_KEY_HEIGHT, MMI_VKBD_ARABIC_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_THAI_WIDTH                  176        
#define  MMI_VKBD_THAI_HEIGHT                 61
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_THAI_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_THAI_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_THAI_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_THAI_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_THAI_MATRIX_COLUMN          10   
#define  MMI_VKBD_THAI_MATRIX_ROW             4
#define  MMI_VKBD_THAI_MATRIX_X               0
#define  MMI_VKBD_THAI_MATRIX_Y               1
#define  MMI_VKBD_THAI_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_THAI_MATRIX_COLUMN, MMI_VKBD_THAI_MATRIX_KEY_WIDTH, MMI_VKBD_THAI_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_THAI_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_THAI_MATRIX_ROW, MMI_VKBD_THAI_MATRIX_KEY_HEIGHT, MMI_VKBD_THAI_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_ARABIC_SYMBOL_WIDTH                  176        
#define  MMI_VKBD_ARABIC_SYMBOL_HEIGHT                 61
/* matrix layout at the left-bottom */
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_COLUMN          5
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_ROW             4
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_X               4
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_Y               1
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_ARABIC_SYMBOL_MATRIX_COLUMN, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_WIDTH, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_ARABIC_SYMBOL_MATRIX_ROW, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_HEIGHT, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_UKRAINIAN_WIDTH                  176        
#define  MMI_VKBD_UKRAINIAN_HEIGHT                 61
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_UKRAINIAN_MATRIX_COLUMN          5   
#define  MMI_VKBD_UKRAINIAN_MATRIX_ROW             4
#define  MMI_VKBD_UKRAINIAN_MATRIX_X               4
#define  MMI_VKBD_UKRAINIAN_MATRIX_Y               1
#define  MMI_VKBD_UKRAINIAN_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_UKRAINIAN_MATRIX_COLUMN, MMI_VKBD_UKRAINIAN_MATRIX_KEY_WIDTH, MMI_VKBD_UKRAINIAN_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_UKRAINIAN_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_UKRAINIAN_MATRIX_ROW, MMI_VKBD_UKRAINIAN_MATRIX_KEY_HEIGHT, MMI_VKBD_UKRAINIAN_MATRIX_KEY_V_GAP)

#elif defined (__MMI_MAINLCD_320X240__)  

#define  MMI_VKBD_MATRIX_KEY_WIDTH              25
#define  MMI_VKBD_MATRIX_KEY_HEIGHT             19
#define  MMI_VKBD_MATRIX_KEY_H_GAP              1
#define  MMI_VKBD_MATRIX_KEY_V_GAP              1

#define  MATRIX_WIDTH(col)       ((col)*(MMI_VKBD_MATRIX_KEY_WIDTH+MMI_VKBD_MATRIX_KEY_H_GAP) - MMI_VKBD_MATRIX_KEY_H_GAP)
#define  MATRIX_HEIGHT(row)      ((row)*(MMI_VKBD_MATRIX_KEY_HEIGHT+MMI_VKBD_MATRIX_KEY_V_GAP) - MMI_VKBD_MATRIX_KEY_V_GAP)

#define  MATRIX_WIDTH_EXT(col, key_width, h_gap)   ( (col) * ((key_width) + (h_gap)) - (h_gap) )
#define  MATRIX_HEIGHT_EXT(row, key_height, v_gap) ( (row) * ((key_height) + (v_gap)) - (v_gap) )


#define  MMI_VKBD_STANDARD_WIDTH                320
#define  MMI_VKBD_STANDARD_HEIGHT               63
/* matrix layout at the left side */
#define  MMI_VKBD_STANDARD_MATRIX_COLUMN        7
#define  MMI_VKBD_STANDARD_MATRIX_ROW           3
#define  MMI_VKBD_STANDARD_MATRIX_X             1
#define  MMI_VKBD_STANDARD_MATRIX_Y             2
#define  MMI_VKBD_STANDARD_MATRIX_WIDTH         MATRIX_WIDTH(7)
#define  MMI_VKBD_STANDARD_MATRIX_HEIGHT        MATRIX_HEIGHT(3)

#define  MMI_VKBD_EXTENDED_WIDTH                320
#define  MMI_VKBD_EXTENDED_HEIGHT               83
/* matrix layout at the left side */
#define  MMI_VKBD_EXTENDED_MATRIX_COLUMN        8
#define  MMI_VKBD_EXTENDED_MATRIX_ROW           4
#define  MMI_VKBD_EXTENDED_MATRIX_X             1
#define  MMI_VKBD_EXTENDED_MATRIX_Y             2
#define  MMI_VKBD_EXTENDED_MATRIX_WIDTH         MATRIX_WIDTH(8)
#define  MMI_VKBD_EXTENDED_MATRIX_HEIGHT        MATRIX_HEIGHT(4)

#define  MMI_VKBD_TRAY_WIDTH                    320
#define  MMI_VKBD_TRAY_HEIGHT                   23
/* matrix layout at the left side */
#define  MMI_VKBD_TRAY_MATRIX_COLUMN            5
#define  MMI_VKBD_TRAY_MATRIX_ROW               1
#define  MMI_VKBD_TRAY_MATRIX_X                 1
#define  MMI_VKBD_TRAY_MATRIX_Y                 2
#define  MMI_VKBD_TRAY_MATRIX_WIDTH             MATRIX_WIDTH(5)
#define  MMI_VKBD_TRAY_MATRIX_HEIGHT            MATRIX_HEIGHT(1)

#define  MMI_VKBD_NUMBER_WIDTH                  320
#define  MMI_VKBD_NUMBER_HEIGHT                 43
/* matrix layout at the left side */
#define  MMI_VKBD_NUMBER_MATRIX_COLUMN          8
#define  MMI_VKBD_NUMBER_MATRIX_ROW             2
#define  MMI_VKBD_NUMBER_MATRIX_X               1
#define  MMI_VKBD_NUMBER_MATRIX_Y               2
#define  MMI_VKBD_NUMBER_MATRIX_WIDTH           MATRIX_WIDTH(8)
#define  MMI_VKBD_NUMBER_MATRIX_HEIGHT          MATRIX_HEIGHT(2)

#define  MMI_VKBD_PINYIN_WIDTH                  320
#define  MMI_VKBD_PINYIN_HEIGHT                 83
/* matrix layout at the left-bottom */
#define  MMI_VKBD_PINYIN_MATRIX_COLUMN          9
#define  MMI_VKBD_PINYIN_MATRIX_ROW             3
#define  MMI_VKBD_PINYIN_MATRIX_X               1
#define  MMI_VKBD_PINYIN_MATRIX_Y               22
#define  MMI_VKBD_PINYIN_MATRIX_WIDTH           MATRIX_WIDTH(9)
#define  MMI_VKBD_PINYIN_MATRIX_HEIGHT          MATRIX_HEIGHT(3)

#define  MMI_VKBD_BOPOMO_WIDTH                  320
#define  MMI_VKBD_BOPOMO_HEIGHT                 83
/* matrix layout at the left-bottom */
#define  MMI_VKBD_BOPOMO_MATRIX_COLUMN          10
#define  MMI_VKBD_BOPOMO_MATRIX_ROW             3
#define  MMI_VKBD_BOPOMO_MATRIX_X               1
#define  MMI_VKBD_BOPOMO_MATRIX_Y               22
#define  MMI_VKBD_BOPOMO_MATRIX_WIDTH           MATRIX_WIDTH(10)
#define  MMI_VKBD_BOPOMO_MATRIX_HEIGHT          MATRIX_HEIGHT(3)

#define  MMI_VKBD_CZECH_WIDTH                  176
#define  MMI_VKBD_CZECH_HEIGHT                 61
/* matrix layout at the left-bottom */
#define  MMI_VKBD_CZECH_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_CZECH_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_CZECH_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_CZECH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_CZECH_MATRIX_COLUMN          7
#define  MMI_VKBD_CZECH_MATRIX_ROW             4
#define  MMI_VKBD_CZECH_MATRIX_X               4
#define  MMI_VKBD_CZECH_MATRIX_Y               1
#define  MMI_VKBD_CZECH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_CZECH_MATRIX_COLUMN, MMI_VKBD_CZECH_MATRIX_KEY_WIDTH, MMI_VKBD_CZECH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_CZECH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_CZECH_MATRIX_ROW, MMI_VKBD_CZECH_MATRIX_KEY_HEIGHT, MMI_VKBD_CZECH_MATRIX_KEY_V_GAP)


#define  MMI_VKBD_HEBREW_WIDTH                  176        
#define  MMI_VKBD_HEBREW_HEIGHT                 46
/* matrix layout at the left-bottom */
#define  MMI_VKBD_HEBREW_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_HEBREW_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_HEBREW_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_HEBREW_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_HEBREW_MATRIX_COLUMN          8
#define  MMI_VKBD_HEBREW_MATRIX_ROW             3
#define  MMI_VKBD_HEBREW_MATRIX_X               1
#define  MMI_VKBD_HEBREW_MATRIX_Y               1
#define  MMI_VKBD_HEBREW_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_HEBREW_MATRIX_COLUMN, MMI_VKBD_HEBREW_MATRIX_KEY_WIDTH, MMI_VKBD_HEBREW_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_HEBREW_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_HEBREW_MATRIX_ROW, MMI_VKBD_HEBREW_MATRIX_KEY_HEIGHT, MMI_VKBD_HEBREW_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_FARSI_WIDTH                  176        
#define  MMI_VKBD_FARSI_HEIGHT                 61
/* matrix layout at the left-bottom */
#define  MMI_VKBD_FARSI_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_FARSI_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_FARSI_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_FARSI_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_FARSI_MATRIX_COLUMN          9
#define  MMI_VKBD_FARSI_MATRIX_ROW             4
#define  MMI_VKBD_FARSI_MATRIX_X               4
#define  MMI_VKBD_FARSI_MATRIX_Y               1
#define  MMI_VKBD_FARSI_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_FARSI_MATRIX_COLUMN, MMI_VKBD_FARSI_MATRIX_KEY_WIDTH, MMI_VKBD_FARSI_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_FARSI_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_FARSI_MATRIX_ROW, MMI_VKBD_FARSI_MATRIX_KEY_HEIGHT, MMI_VKBD_FARSI_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_FARSI_SYMBOL_WIDTH                  176        
#define  MMI_VKBD_FARSI_SYMBOL_HEIGHT                 76
/* matrix layout at the left-bottom */
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_COLUMN          9
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_ROW             5
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_X               4
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_Y               1
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_FARSI_SYMBOL_MATRIX_COLUMN, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_WIDTH, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_FARSI_SYMBOL_MATRIX_ROW, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_HEIGHT, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_GREEK_WIDTH                  176        
#define  MMI_VKBD_GREEK_HEIGHT                 46
/* matrix layout at the left-bottom */
#define  MMI_VKBD_GREEK_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_GREEK_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_GREEK_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_GREEK_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_GREEK_MATRIX_COLUMN          7
#define  MMI_VKBD_GREEK_MATRIX_ROW             3
#define  MMI_VKBD_GREEK_MATRIX_X               1
#define  MMI_VKBD_GREEK_MATRIX_Y               1
#define  MMI_VKBD_GREEK_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_GREEK_MATRIX_COLUMN, MMI_VKBD_GREEK_MATRIX_KEY_WIDTH, MMI_VKBD_GREEK_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_GREEK_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_GREEK_MATRIX_ROW, MMI_VKBD_GREEK_MATRIX_KEY_HEIGHT, MMI_VKBD_GREEK_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_BULGARIAN_WIDTH                  176       
#define  MMI_VKBD_BULGARIAN_HEIGHT                 61
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_BULGARIAN_MATRIX_COLUMN          7
#define  MMI_VKBD_BULGARIAN_MATRIX_ROW             4
#define  MMI_VKBD_BULGARIAN_MATRIX_X               0
#define  MMI_VKBD_BULGARIAN_MATRIX_Y               1
#define  MMI_VKBD_BULGARIAN_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_BULGARIAN_MATRIX_COLUMN, MMI_VKBD_BULGARIAN_MATRIX_KEY_WIDTH, MMI_VKBD_BULGARIAN_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_BULGARIAN_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_BULGARIAN_MATRIX_ROW, MMI_VKBD_BULGARIAN_MATRIX_KEY_HEIGHT, MMI_VKBD_BULGARIAN_MATRIX_KEY_V_GAP)


#define  MMI_VKBD_DANISH_WIDTH                  176        
#define  MMI_VKBD_DANISH_HEIGHT                 46
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_DANISH_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_DANISH_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_DANISH_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_DANISH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_DANISH_MATRIX_COLUMN          7
#define  MMI_VKBD_DANISH_MATRIX_ROW             3
#define  MMI_VKBD_DANISH_MATRIX_X               1
#define  MMI_VKBD_DANISH_MATRIX_Y               1
#define  MMI_VKBD_DANISH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_DANISH_MATRIX_COLUMN, MMI_VKBD_DANISH_MATRIX_KEY_WIDTH, MMI_VKBD_DANISH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_DANISH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_DANISH_MATRIX_ROW, MMI_VKBD_DANISH_MATRIX_KEY_HEIGHT, MMI_VKBD_DANISH_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_HUNGARIAN_WIDTH                  176        
#define  MMI_VKBD_HUNGARIAN_HEIGHT                 64
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_HUNGARIAN_MATRIX_COLUMN          7
#define  MMI_VKBD_HUNGARIAN_MATRIX_ROW             4
#define  MMI_VKBD_HUNGARIAN_MATRIX_X               4
#define  MMI_VKBD_HUNGARIAN_MATRIX_Y               1
#define  MMI_VKBD_HUNGARIAN_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_HUNGARIAN_MATRIX_COLUMN, MMI_VKBD_HUNGARIAN_MATRIX_KEY_WIDTH, MMI_VKBD_HUNGARIAN_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_HUNGARIAN_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_HUNGARIAN_MATRIX_ROW, MMI_VKBD_HUNGARIAN_MATRIX_KEY_HEIGHT, MMI_VKBD_HUNGARIAN_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_FINNISH_WIDTH                  176        
#define  MMI_VKBD_FINNISH_HEIGHT                 46
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_FINNISH_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_FINNISH_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_FINNISH_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_FINNISH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_FINNISH_MATRIX_COLUMN          8
#define  MMI_VKBD_FINNISH_MATRIX_ROW             3
#define  MMI_VKBD_FINNISH_MATRIX_X               1
#define  MMI_VKBD_FINNISH_MATRIX_Y               1
#define  MMI_VKBD_FINNISH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_FINNISH_MATRIX_COLUMN, MMI_VKBD_FINNISH_MATRIX_KEY_WIDTH, MMI_VKBD_FINNISH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_FINNISH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_FINNISH_MATRIX_ROW, MMI_VKBD_FINNISH_MATRIX_KEY_HEIGHT, MMI_VKBD_FINNISH_MATRIX_KEY_V_GAP)


#define  MMI_VKBD_POLISH_WIDTH                  176        
#define  MMI_VKBD_POLISH_HEIGHT                 61
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_POLISH_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_POLISH_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_POLISH_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_POLISH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_POLISH_MATRIX_COLUMN          7
#define  MMI_VKBD_POLISH_MATRIX_ROW             4
#define  MMI_VKBD_POLISH_MATRIX_X               1
#define  MMI_VKBD_POLISH_MATRIX_Y               1
#define  MMI_VKBD_POLISH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_POLISH_MATRIX_COLUMN, MMI_VKBD_POLISH_MATRIX_KEY_WIDTH, MMI_VKBD_POLISH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_POLISH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_POLISH_MATRIX_ROW, MMI_VKBD_POLISH_MATRIX_KEY_HEIGHT, MMI_VKBD_POLISH_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_VIETNAMESE_WIDTH                  176        
#define  MMI_VKBD_VIETNAMESE_HEIGHT                 61
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_VIETNAMESE_MATRIX_COLUMN          5   
#define  MMI_VKBD_VIETNAMESE_MATRIX_ROW             4
#define  MMI_VKBD_VIETNAMESE_MATRIX_X               0
#define  MMI_VKBD_VIETNAMESE_MATRIX_Y               1
#define  MMI_VKBD_VIETNAMESE_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_VIETNAMESE_MATRIX_COLUMN, MMI_VKBD_VIETNAMESE_MATRIX_KEY_WIDTH, MMI_VKBD_VIETNAMESE_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_VIETNAMESE_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_VIETNAMESE_MATRIX_ROW, MMI_VKBD_VIETNAMESE_MATRIX_KEY_HEIGHT, MMI_VKBD_VIETNAMESE_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_ARABIC_WIDTH                  176        
#define  MMI_VKBD_ARABIC_HEIGHT                 61
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_ARABIC_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_ARABIC_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_ARABIC_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_ARABIC_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_ARABIC_MATRIX_COLUMN          5   
#define  MMI_VKBD_ARABIC_MATRIX_ROW             4
#define  MMI_VKBD_ARABIC_MATRIX_X               1
#define  MMI_VKBD_ARABIC_MATRIX_Y               1
#define  MMI_VKBD_ARABIC_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_ARABIC_MATRIX_COLUMN, MMI_VKBD_ARABIC_MATRIX_KEY_WIDTH, MMI_VKBD_ARABIC_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_ARABIC_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_ARABIC_MATRIX_ROW, MMI_VKBD_ARABIC_MATRIX_KEY_HEIGHT, MMI_VKBD_ARABIC_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_THAI_WIDTH                  176        
#define  MMI_VKBD_THAI_HEIGHT                 61
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_THAI_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_THAI_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_THAI_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_THAI_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_THAI_MATRIX_COLUMN          10   
#define  MMI_VKBD_THAI_MATRIX_ROW             4
#define  MMI_VKBD_THAI_MATRIX_X               0
#define  MMI_VKBD_THAI_MATRIX_Y               1
#define  MMI_VKBD_THAI_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_THAI_MATRIX_COLUMN, MMI_VKBD_THAI_MATRIX_KEY_WIDTH, MMI_VKBD_THAI_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_THAI_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_THAI_MATRIX_ROW, MMI_VKBD_THAI_MATRIX_KEY_HEIGHT, MMI_VKBD_THAI_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_ARABIC_SYMBOL_WIDTH                  176        
#define  MMI_VKBD_ARABIC_SYMBOL_HEIGHT                 61
/* matrix layout at the left-bottom */
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_COLUMN          5
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_ROW             4
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_X               4
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_Y               1
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_ARABIC_SYMBOL_MATRIX_COLUMN, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_WIDTH, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_ARABIC_SYMBOL_MATRIX_ROW, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_HEIGHT, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_UKRAINIAN_WIDTH                  176        
#define  MMI_VKBD_UKRAINIAN_HEIGHT                 61
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_UKRAINIAN_MATRIX_COLUMN          5   
#define  MMI_VKBD_UKRAINIAN_MATRIX_ROW             4
#define  MMI_VKBD_UKRAINIAN_MATRIX_X               4
#define  MMI_VKBD_UKRAINIAN_MATRIX_Y               1
#define  MMI_VKBD_UKRAINIAN_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_UKRAINIAN_MATRIX_COLUMN, MMI_VKBD_UKRAINIAN_MATRIX_KEY_WIDTH, MMI_VKBD_UKRAINIAN_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_UKRAINIAN_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_UKRAINIAN_MATRIX_ROW, MMI_VKBD_UKRAINIAN_MATRIX_KEY_HEIGHT, MMI_VKBD_UKRAINIAN_MATRIX_KEY_V_GAP)

#else /* (__MMI_MAINLCD_128X160__) */

#define  MMI_VKBD_MATRIX_KEY_WIDTH              10
#define  MMI_VKBD_MATRIX_KEY_HEIGHT             10
#define  MMI_VKBD_MATRIX_KEY_H_GAP              1
#define  MMI_VKBD_MATRIX_KEY_V_GAP              1

#define  MATRIX_WIDTH(col)       ((col)*(MMI_VKBD_MATRIX_KEY_WIDTH+MMI_VKBD_MATRIX_KEY_H_GAP) - MMI_VKBD_MATRIX_KEY_H_GAP)
#define  MATRIX_HEIGHT(row)      ((row)*(MMI_VKBD_MATRIX_KEY_HEIGHT+MMI_VKBD_MATRIX_KEY_V_GAP) - MMI_VKBD_MATRIX_KEY_V_GAP)

#define  MATRIX_WIDTH_EXT(col, key_width, h_gap)   ( (col) * ((key_width) + (h_gap)) - (h_gap) )
#define  MATRIX_HEIGHT_EXT(row, key_height, v_gap) ( (row) * ((key_height) + (v_gap)) - (v_gap) )

#define  MMI_VKBD_STANDARD_WIDTH                128
#define  MMI_VKBD_STANDARD_HEIGHT               34
/* matrix layout at the left side */
#define  MMI_VKBD_STANDARD_MATRIX_COLUMN        7
#define  MMI_VKBD_STANDARD_MATRIX_ROW           3
#define  MMI_VKBD_STANDARD_MATRIX_X             1
#define  MMI_VKBD_STANDARD_MATRIX_Y             1
#define  MMI_VKBD_STANDARD_MATRIX_WIDTH         MATRIX_WIDTH(7)
#define  MMI_VKBD_STANDARD_MATRIX_HEIGHT        MATRIX_HEIGHT(3)

#define  MMI_VKBD_EXTENDED_WIDTH                128
#define  MMI_VKBD_EXTENDED_HEIGHT               45
/* matrix layout at the left side */
#define  MMI_VKBD_EXTENDED_MATRIX_COLUMN        8
#define  MMI_VKBD_EXTENDED_MATRIX_ROW           4
#define  MMI_VKBD_EXTENDED_MATRIX_X             1
#define  MMI_VKBD_EXTENDED_MATRIX_Y             1
#define  MMI_VKBD_EXTENDED_MATRIX_WIDTH         MATRIX_WIDTH(8)
#define  MMI_VKBD_EXTENDED_MATRIX_HEIGHT        MATRIX_HEIGHT(4)

#define  MMI_VKBD_TRAY_WIDTH                    128
#define  MMI_VKBD_TRAY_HEIGHT                   12
/* matrix layout at the left side */
#define  MMI_VKBD_TRAY_MATRIX_COLUMN            5
#define  MMI_VKBD_TRAY_MATRIX_ROW               1
#define  MMI_VKBD_TRAY_MATRIX_X                 1
#define  MMI_VKBD_TRAY_MATRIX_Y                 1
#define  MMI_VKBD_TRAY_MATRIX_WIDTH             MATRIX_WIDTH(5)
#define  MMI_VKBD_TRAY_MATRIX_HEIGHT            MATRIX_HEIGHT(1)

#define  MMI_VKBD_NUMBER_WIDTH                  128
#define  MMI_VKBD_NUMBER_HEIGHT                 23
/* matrix layout at the left side */
#define  MMI_VKBD_NUMBER_MATRIX_COLUMN          8
#define  MMI_VKBD_NUMBER_MATRIX_ROW             2
#define  MMI_VKBD_NUMBER_MATRIX_X               1
#define  MMI_VKBD_NUMBER_MATRIX_Y               1
#define  MMI_VKBD_NUMBER_MATRIX_WIDTH           MATRIX_WIDTH(8)
#define  MMI_VKBD_NUMBER_MATRIX_HEIGHT          MATRIX_HEIGHT(2)

#define  MMI_VKBD_PINYIN_WIDTH                  128
#define  MMI_VKBD_PINYIN_HEIGHT                 45
/* matrix layout at the left-bottom */
#define  MMI_VKBD_PINYIN_MATRIX_COLUMN          9
#define  MMI_VKBD_PINYIN_MATRIX_ROW             3
#define  MMI_VKBD_PINYIN_MATRIX_X               1
#define  MMI_VKBD_PINYIN_MATRIX_Y               12
#define  MMI_VKBD_PINYIN_MATRIX_WIDTH           MATRIX_WIDTH(9)
#define  MMI_VKBD_PINYIN_MATRIX_HEIGHT          MATRIX_HEIGHT(3)

#define  MMI_VKBD_BOPOMO_WIDTH                  128
#define  MMI_VKBD_BOPOMO_HEIGHT                 45
/* matrix layout at the left-bottom */
#define  MMI_VKBD_BOPOMO_MATRIX_COLUMN          10
#define  MMI_VKBD_BOPOMO_MATRIX_ROW             3
#define  MMI_VKBD_BOPOMO_MATRIX_X               1
#define  MMI_VKBD_BOPOMO_MATRIX_Y               12
#define  MMI_VKBD_BOPOMO_MATRIX_WIDTH           MATRIX_WIDTH(10)
#define  MMI_VKBD_BOPOMO_MATRIX_HEIGHT          MATRIX_HEIGHT(3)

#define  MMI_VKBD_CZECH_WIDTH                  128
#define  MMI_VKBD_CZECH_HEIGHT                 45
/* matrix layout at the left-bottom */
#define  MMI_VKBD_CZECH_MATRIX_KEY_WIDTH       9
#define  MMI_VKBD_CZECH_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_CZECH_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_CZECH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_CZECH_MATRIX_COLUMN          7
#define  MMI_VKBD_CZECH_MATRIX_ROW             4
#define  MMI_VKBD_CZECH_MATRIX_X               1
#define  MMI_VKBD_CZECH_MATRIX_Y               1
#define  MMI_VKBD_CZECH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_CZECH_MATRIX_COLUMN, MMI_VKBD_CZECH_MATRIX_KEY_WIDTH, MMI_VKBD_CZECH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_CZECH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_CZECH_MATRIX_ROW, MMI_VKBD_CZECH_MATRIX_KEY_HEIGHT, MMI_VKBD_CZECH_MATRIX_KEY_V_GAP)


#define  MMI_VKBD_HEBREW_WIDTH                  128        
#define  MMI_VKBD_HEBREW_HEIGHT                 34
/* matrix layout at the left-bottom */
#define  MMI_VKBD_HEBREW_MATRIX_KEY_WIDTH       9
#define  MMI_VKBD_HEBREW_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_HEBREW_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_HEBREW_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_HEBREW_MATRIX_COLUMN          8
#define  MMI_VKBD_HEBREW_MATRIX_ROW             3
#define  MMI_VKBD_HEBREW_MATRIX_X               1
#define  MMI_VKBD_HEBREW_MATRIX_Y               1
#define  MMI_VKBD_HEBREW_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_HEBREW_MATRIX_COLUMN, MMI_VKBD_HEBREW_MATRIX_KEY_WIDTH, MMI_VKBD_HEBREW_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_HEBREW_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_HEBREW_MATRIX_ROW, MMI_VKBD_HEBREW_MATRIX_KEY_HEIGHT, MMI_VKBD_HEBREW_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_GREEK_WIDTH                  128        
#define  MMI_VKBD_GREEK_HEIGHT                 34
/* matrix layout at the left-bottom */
#define  MMI_VKBD_GREEK_MATRIX_KEY_WIDTH       9
#define  MMI_VKBD_GREEK_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_GREEK_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_GREEK_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_GREEK_MATRIX_COLUMN          7
#define  MMI_VKBD_GREEK_MATRIX_ROW             3
#define  MMI_VKBD_GREEK_MATRIX_X               1
#define  MMI_VKBD_GREEK_MATRIX_Y               1
#define  MMI_VKBD_GREEK_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_GREEK_MATRIX_COLUMN, MMI_VKBD_GREEK_MATRIX_KEY_WIDTH, MMI_VKBD_GREEK_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_GREEK_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_GREEK_MATRIX_ROW, MMI_VKBD_GREEK_MATRIX_KEY_HEIGHT, MMI_VKBD_GREEK_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_BULGARIAN_WIDTH                  128       
#define  MMI_VKBD_BULGARIAN_HEIGHT                 45
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_WIDTH       9
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_BULGARIAN_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_BULGARIAN_MATRIX_COLUMN          7
#define  MMI_VKBD_BULGARIAN_MATRIX_ROW             4
#define  MMI_VKBD_BULGARIAN_MATRIX_X               1
#define  MMI_VKBD_BULGARIAN_MATRIX_Y               1
#define  MMI_VKBD_BULGARIAN_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_BULGARIAN_MATRIX_COLUMN, MMI_VKBD_BULGARIAN_MATRIX_KEY_WIDTH, MMI_VKBD_BULGARIAN_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_BULGARIAN_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_BULGARIAN_MATRIX_ROW, MMI_VKBD_BULGARIAN_MATRIX_KEY_HEIGHT, MMI_VKBD_BULGARIAN_MATRIX_KEY_V_GAP)


#define  MMI_VKBD_DANISH_WIDTH                  128        
#define  MMI_VKBD_DANISH_HEIGHT                 34
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_DANISH_MATRIX_KEY_WIDTH       9
#define  MMI_VKBD_DANISH_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_DANISH_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_DANISH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_DANISH_MATRIX_COLUMN          7
#define  MMI_VKBD_DANISH_MATRIX_ROW             3
#define  MMI_VKBD_DANISH_MATRIX_X               1
#define  MMI_VKBD_DANISH_MATRIX_Y               1
#define  MMI_VKBD_DANISH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_DANISH_MATRIX_COLUMN, MMI_VKBD_DANISH_MATRIX_KEY_WIDTH, MMI_VKBD_DANISH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_DANISH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_DANISH_MATRIX_ROW, MMI_VKBD_DANISH_MATRIX_KEY_HEIGHT, MMI_VKBD_DANISH_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_HUNGARIAN_WIDTH                  128        
#define  MMI_VKBD_HUNGARIAN_HEIGHT                 45
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_WIDTH       9
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_HUNGARIAN_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_HUNGARIAN_MATRIX_COLUMN          7
#define  MMI_VKBD_HUNGARIAN_MATRIX_ROW             4
#define  MMI_VKBD_HUNGARIAN_MATRIX_X               1
#define  MMI_VKBD_HUNGARIAN_MATRIX_Y               1
#define  MMI_VKBD_HUNGARIAN_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_HUNGARIAN_MATRIX_COLUMN, MMI_VKBD_HUNGARIAN_MATRIX_KEY_WIDTH, MMI_VKBD_HUNGARIAN_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_HUNGARIAN_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_HUNGARIAN_MATRIX_ROW, MMI_VKBD_HUNGARIAN_MATRIX_KEY_HEIGHT, MMI_VKBD_HUNGARIAN_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_FINNISH_WIDTH                  128        
#define  MMI_VKBD_FINNISH_HEIGHT                 34
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_FINNISH_MATRIX_KEY_WIDTH       9
#define  MMI_VKBD_FINNISH_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_FINNISH_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_FINNISH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_FINNISH_MATRIX_COLUMN          8
#define  MMI_VKBD_FINNISH_MATRIX_ROW             3
#define  MMI_VKBD_FINNISH_MATRIX_X               1
#define  MMI_VKBD_FINNISH_MATRIX_Y               1
#define  MMI_VKBD_FINNISH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_FINNISH_MATRIX_COLUMN, MMI_VKBD_FINNISH_MATRIX_KEY_WIDTH, MMI_VKBD_FINNISH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_FINNISH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_FINNISH_MATRIX_ROW, MMI_VKBD_FINNISH_MATRIX_KEY_HEIGHT, MMI_VKBD_FINNISH_MATRIX_KEY_V_GAP)


#define  MMI_VKBD_POLISH_WIDTH                  128        
#define  MMI_VKBD_POLISH_HEIGHT                 45
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_POLISH_MATRIX_KEY_WIDTH       10
#define  MMI_VKBD_POLISH_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_POLISH_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_POLISH_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_POLISH_MATRIX_COLUMN          7
#define  MMI_VKBD_POLISH_MATRIX_ROW             4
#define  MMI_VKBD_POLISH_MATRIX_X               1
#define  MMI_VKBD_POLISH_MATRIX_Y               1
#define  MMI_VKBD_POLISH_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_POLISH_MATRIX_COLUMN, MMI_VKBD_POLISH_MATRIX_KEY_WIDTH, MMI_VKBD_POLISH_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_POLISH_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_POLISH_MATRIX_ROW, MMI_VKBD_POLISH_MATRIX_KEY_HEIGHT, MMI_VKBD_POLISH_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_FARSI_WIDTH                  128        
#define  MMI_VKBD_FARSI_HEIGHT                 45
/* matrix layout at the left-bottom */
#define  MMI_VKBD_FARSI_MATRIX_KEY_WIDTH       10
#define  MMI_VKBD_FARSI_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_FARSI_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_FARSI_MATRIX_KEY_V_GAP       0
#define  MMI_VKBD_FARSI_MATRIX_COLUMN          9
#define  MMI_VKBD_FARSI_MATRIX_ROW             4
#define  MMI_VKBD_FARSI_MATRIX_X               1
#define  MMI_VKBD_FARSI_MATRIX_Y               1
#define  MMI_VKBD_FARSI_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_FARSI_MATRIX_COLUMN, MMI_VKBD_FARSI_MATRIX_KEY_WIDTH, MMI_VKBD_FARSI_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_FARSI_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_FARSI_MATRIX_ROW, MMI_VKBD_FARSI_MATRIX_KEY_HEIGHT, MMI_VKBD_FARSI_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_FARSI_SYMBOL_WIDTH                  128        
#define  MMI_VKBD_FARSI_SYMBOL_HEIGHT                 76
/* matrix layout at the left-bottom */
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_WIDTH       14
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_HEIGHT      14
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_H_GAP       0
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_COLUMN          9
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_ROW             5
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_X               4
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_Y               1
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_FARSI_SYMBOL_MATRIX_COLUMN, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_WIDTH, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_FARSI_SYMBOL_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_FARSI_SYMBOL_MATRIX_ROW, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_HEIGHT, MMI_VKBD_FARSI_SYMBOL_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_VIETNAMESE_WIDTH                  128        
#define  MMI_VKBD_VIETNAMESE_HEIGHT                 45
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_WIDTH       10
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_VIETNAMESE_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_VIETNAMESE_MATRIX_COLUMN          5   
#define  MMI_VKBD_VIETNAMESE_MATRIX_ROW             4
#define  MMI_VKBD_VIETNAMESE_MATRIX_X               1
#define  MMI_VKBD_VIETNAMESE_MATRIX_Y               1
#define  MMI_VKBD_VIETNAMESE_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_VIETNAMESE_MATRIX_COLUMN, MMI_VKBD_VIETNAMESE_MATRIX_KEY_WIDTH, MMI_VKBD_VIETNAMESE_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_VIETNAMESE_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_VIETNAMESE_MATRIX_ROW, MMI_VKBD_VIETNAMESE_MATRIX_KEY_HEIGHT, MMI_VKBD_VIETNAMESE_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_ARABIC_WIDTH                  128        
#define  MMI_VKBD_ARABIC_HEIGHT                 45
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_ARABIC_MATRIX_KEY_WIDTH       10
#define  MMI_VKBD_ARABIC_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_ARABIC_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_ARABIC_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_ARABIC_MATRIX_COLUMN          5   
#define  MMI_VKBD_ARABIC_MATRIX_ROW             4
#define  MMI_VKBD_ARABIC_MATRIX_X               1
#define  MMI_VKBD_ARABIC_MATRIX_Y               1
#define  MMI_VKBD_ARABIC_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_ARABIC_MATRIX_COLUMN, MMI_VKBD_ARABIC_MATRIX_KEY_WIDTH, MMI_VKBD_ARABIC_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_ARABIC_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_ARABIC_MATRIX_ROW, MMI_VKBD_ARABIC_MATRIX_KEY_HEIGHT, MMI_VKBD_ARABIC_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_THAI_WIDTH                  128        
#define  MMI_VKBD_THAI_HEIGHT                 45
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_THAI_MATRIX_KEY_WIDTH       9
#define  MMI_VKBD_THAI_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_THAI_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_THAI_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_THAI_MATRIX_COLUMN          10   
#define  MMI_VKBD_THAI_MATRIX_ROW             4
#define  MMI_VKBD_THAI_MATRIX_X               1
#define  MMI_VKBD_THAI_MATRIX_Y               1
#define  MMI_VKBD_THAI_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_THAI_MATRIX_COLUMN, MMI_VKBD_THAI_MATRIX_KEY_WIDTH, MMI_VKBD_THAI_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_THAI_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_THAI_MATRIX_ROW, MMI_VKBD_THAI_MATRIX_KEY_HEIGHT, MMI_VKBD_THAI_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_ARABIC_SYMBOL_WIDTH                  128        
#define  MMI_VKBD_ARABIC_SYMBOL_HEIGHT                 45
/* matrix layout at the left-bottom */
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_WIDTH       10
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_COLUMN          5
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_ROW             4
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_X               1
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_Y               1
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_ARABIC_SYMBOL_MATRIX_COLUMN, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_WIDTH, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_ARABIC_SYMBOL_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_ARABIC_SYMBOL_MATRIX_ROW, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_HEIGHT, MMI_VKBD_ARABIC_SYMBOL_MATRIX_KEY_V_GAP)

#define  MMI_VKBD_UKRAINIAN_WIDTH                  128        
#define  MMI_VKBD_UKRAINIAN_HEIGHT                 45
    /* matrix layout at the left-bottom */
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_WIDTH       10
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_HEIGHT      10
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_H_GAP       1
#define  MMI_VKBD_UKRAINIAN_MATRIX_KEY_V_GAP       1
#define  MMI_VKBD_UKRAINIAN_MATRIX_COLUMN          5   
#define  MMI_VKBD_UKRAINIAN_MATRIX_ROW             4
#define  MMI_VKBD_UKRAINIAN_MATRIX_X               1
#define  MMI_VKBD_UKRAINIAN_MATRIX_Y               1
#define  MMI_VKBD_UKRAINIAN_MATRIX_WIDTH           MATRIX_WIDTH_EXT(MMI_VKBD_UKRAINIAN_MATRIX_COLUMN, MMI_VKBD_UKRAINIAN_MATRIX_KEY_WIDTH, MMI_VKBD_UKRAINIAN_MATRIX_KEY_H_GAP)
#define  MMI_VKBD_UKRAINIAN_MATRIX_HEIGHT          MATRIX_HEIGHT_EXT(MMI_VKBD_UKRAINIAN_MATRIX_ROW, MMI_VKBD_UKRAINIAN_MATRIX_KEY_HEIGHT, MMI_VKBD_UKRAINIAN_MATRIX_KEY_V_GAP)

#endif /* __MMI_MAINLCD_240X320__ */ 

extern virtual_keyboard MMI_virtual_keyboard;
extern const gui_keyboard_lang_map_struct MMI_virtual_keyboard_language_map[];
extern const gui_dead_key_map_struct gui_dead_key_symbol_table[];

extern S32 MMI_virtual_keyboard_bitmap_cache_size;

extern void create_virtual_keyboard(void);

extern void wgui_virtual_keyboard_set_global_multi_block_mode(MMI_BOOL enabled);

extern void wgui_setup_virtual_keyboard(gui_virtual_keyboard_language_enum lang_type);
extern void wgui_close_virtual_keyboard(void);
extern void wgui_set_virtual_keyboard_display_area(const U8 *string, BOOL redraw);
extern void wgui_get_virtual_keyboard_size(S32 *width, S32 *height);
extern void wgui_set_virtual_keyboard_allowed_characters(const UI_character_type *allowed_chars);
extern void wgui_set_virtual_keyboard_disabled_list(
                const UI_character_type *disabled_chars,
                const gui_virtual_keyboard_pen_enum *disabled_symbols);
extern void wgui_move_virtual_keyboard(S32 x, S32 y);
extern void wgui_show_virtual_keyboard(void);
extern void wgui_greyscale_virtual_keyboard(void);

#endif /* __WGUI_VIRTUAL_KEYBOARD_H__ */ 

