/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2007
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   SimDetectionResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file is intends for SIM detection resource definitions
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef __SIM_DETECTION_RES_DEF_H__
#define __SIM_DETECTION_RES_DEF_H__

#include "MMIDataType.h"    /* for resource base */

/***************************************************************************** 
 * Typedef for Resource Enum
 *****************************************************************************/
/* Screen IDs */
typedef enum
{
    SCR_ENTER_PIN = SIM_DETECTION_BASE,
    SCR_NO_SERVICE,
    SCR_SIM_OPTION,
    SCR_SIM_INSERTION,
    SCR_PUK_BLOCKED,
    SCR_SIM_BLOCK,
    SCR_ENTER_PUK,
    SCR_ENTER_CONFIRM_PIN,
    SCR_ENTER_NEW_PIN,
    SCR_ENTER_PHONELOCK,
    SCR_DIAL_SOS_NUM,
    SCR_MAKE_SOS_CALL,
    SCR_BOOTUP_POPUP,
    SCR_SSC_ENTER_PUK,
    SCR_POP_UP_HISTORY,
    SCR_CODE_VERIFY,
    APHORISM_SCREEN_ID,
    WELCOME_SCREEN_ID,
    SCR_INVALID_SIM_INFO,
    SCR_NAND_FLASH_CHECK,
    SCR_NAND_CHECK_PROCESSING,
    SCR_BOOTUP_CHECK_DISK,
    SCR_ID_PASSWORD_INPUT_DUMMY,
    SCR_ID_SIM_DETECTION_END
} SIM_DETECTION_SCR_ID_ENUM;

/* String IDs */
typedef enum
{
    STR_ENTER_PIN_MSG = SIM_DETECTION_BASE,
    STR_PIN_BLOCKED_MSG,
    STR_ENTER_PUK_MSG,
    STR_INCORRECT_PIN,
    STR_PIN_BLOCKED_PUK,
    STR_DIAL_EMERGENCY_NUMBER,
    STR_ENTER_NEW_PIN_MSG,
    STR_RSK_SOS,
    STR_ENTER_PIN_AGAIN_MSG,
    STR_PIN_DONOT_MATCH,
    STR_ENTER_PHONELOCK_MSG,
    STR_SUBLCD_ENTER_PHONELOCK_MSG,
    STR_INCORRECT_PUK,
    STR_INCORRECT_PHONELOCK,
    STR_CLEAR_FOR_CATEGORY5_DUMMY,
    STR_NO_SERVICE_RUNNING_TEXT,
    STR_INVALID_PINPUKPLOCK_LENGTH_RUNNING_TEXT,
    STR_SIM_OPTION,
    STR_SIM_OPTION_CAPTION,
    STR_SIM_INSERTION_MSG,
    STR_SUBLCD_SIM_INSERTION_MSG,
    STR_SIM_ACCESS_ERROR_MSG,
    STR_SUBLCD_SIM_ACCESS_ERROR_MSG,
    STR_SIM_INVALID_SIM_TITLE,
    STR_SIM_INVALID_SIM_TXT,
    STR_SIM_INVALID_SIM_SELECT_NETWORK_TXT,
    STR_APHORISM_TEXT,
    STR_WELCOME_SCR_TEXT,
    STR_SUBLCD_ENTER_PIN_MSG,
    STR_SUBLCD_ENTER_PUK_MSG,
    STR_NOT_SOS_NUMBER,
    STR_CODE_VERIFIED,
    STR_INCORRECT_SSC,
    STR_LIMITED_SERVICE,
    STR_NO_SERVICE,
    STR_SIM_BLOCK_MSG,
    STR_SUBLCD_SIM_BLOCK_MSG,

    STR_APHORISM_TEXT_1,
    STR_APHORISM_TEXT_2,
    STR_APHORISM_TEXT_3,
    STR_APHORISM_TEXT_4,
    STR_APHORISM_TEXT_5,
    STR_APHORISM_TEXT_6,
    STR_APHORISM_TEXT_7,
    STR_APHORISM_TEXT_8,
    STR_APHORISM_TEXT_9,
    STR_APHORISM_TEXT_10,
    STR_APHORISM_TEXT_11,
    STR_APHORISM_TEXT_12,
    STR_APHORISM_TEXT_13,
    STR_APHORISM_TEXT_14,
    STR_APHORISM_TEXT_15,
    STR_APHORISM_TEXT_16,
    STR_APHORISM_TEXT_17,
    STR_APHORISM_TEXT_18,
    STR_APHORISM_TEXT_19,
    STR_APHORISM_TEXT_20,
    STR_APHORISM_TEXT_21,
    STR_APHORISM_TEXT_22,
    STR_APHORISM_TEXT_23,
    STR_APHORISM_TEXT_24,
    STR_APHORISM_TEXT_25,
    STR_APHORISM_TEXT_26,
    STR_APHORISM_TEXT_27,
    STR_APHORISM_TEXT_28,
    STR_APHORISM_TEXT_29,
    STR_APHORISM_TEXT_30,
    STR_APHORISM_TEXT_31,
    STR_APHORISM_TEXT_32,
    STR_APHORISM_TEXT_33,
    STR_APHORISM_TEXT_34,
    STR_APHORISM_TEXT_35,

    STR_NAND_CHECK_TITLE,
    STR_NAND_CHECK,
    STR_NAND_CHECK_PROCESSING,
    STR_ID_SIM_REFRESH,
    STR_ID_NAND_QUOTA_OVER_DISK,
    STR_ID_NAND_QUOTA_USAGE_WARNING,
    STR_ID_NAND_DEVICE_NOT_SUPPORTED,
    STR_ID_NAND_USER_DRIVE_CORRUPT,
    STR_ID_NAND_SYSTEM_DRIVE_CORRUPT,
    STR_ID_NAND_VERSION_MISMATCH,

    STR_ID_SIM_DETECTION_END
} SIM_DETECTION_STR_ID_ENUM;

/* Image IDs */
typedef enum
{
    IMG_ENTER_PIN_CAPTION = SIM_DETECTION_BASE,
    IMG_ENTER_PIN_AGAIN_MSG,
    IMG_ENTER_PUK_CAPTION,
    IMG_ENTER_NEW_PIN_FIRST_TIME_CAPTION,
    IMG_ENTER_NEW_PIN_SECOND_TIME_CAPTION,
    IMG_ENTER_PHONE_LOCK_CAPTION,

    IMG_ID_OPTION_MENU_PHONEBOOK_ICON,
    IMG_ID_OPTION_MENU_MESSAGES_ICON,
    IMG_ID_OPTION_MENU_FUNANDGAMES_ICON,
    IMG_ID_OPTION_MENU_ORGANIZER_ICON,
    IMG_ID_OPTION_MENU_SETTINGS_ICON,
    IMG_ID_OPTION_MENU_PROFILES_ICON,
    IMG_ID_OPTION_MENU_SHORTCUTS_ICON,
    IMG_ID_OPTION_MENU_SERVICES_ICON,
    IMG_ID_OPTION_MENU_CALL_HISTORY_ICON,
    IMG_ID_OPTION_MENU_MULTIMEDIA_ICON,
    IMG_ID_OPTION_MENU_FILEMNGR_ICON,
    IMG_ID_OPTION_MENU_EXTRA_ICON,

    IMG_SUBLCD_POWER_ON_SCR,
    IMG_APHORISM_SCR,
    IMG_WELCOME_SCR,
    IMG_ID_SIM_DETECTION_END
} SIM_DETECTION_IMG_ID_ENUM;

#endif /*__SIM_DETECTION_RES_DEF_H__ */

