/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 * JBrowserResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file is contains enums for screen, image and strings.
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/

#ifndef _JBROWSERRESDEF_H
#define _JBROWSERRESDEF_H

#include "MMI_features.h"
#if defined (JATAAYU_SUPPORT) && defined (WAP_SUPPORT)

#include "MMIDataType.h"

/* Image ID's */
typedef enum
{
    IMG_ID_BRW_WAP = JATAAYU_BROWSER_BASE,
    /* add new image ID below this line */
    IMG_ID_BRW_CONNECTION_STATUS_CSD,
    IMG_ID_BRW_CONNECTION_STATUS_GPRS,
    IMG_ID_BRW_HOMEPAGE,
    IMG_ID_BRW_BOOKMARKS,
    IMG_ID_BRW_RECENT_PAGES,
    IMG_ID_BRW_ENTER_ADDRESS,
    IMG_ID_BRW_SERVICE_INBOX,
    IMG_ID_BRW_SETTINGS,
    IMG_ID_BRW_PUSH_READ,
    IMG_ID_BRW_PUSH_UNREAD,
    IMG_ID_BRW_PUSH_EXPIRED_READ,
    IMG_ID_BRW_PUSH_EXPIRED_UNREAD,
    IMG_ID_BRW_SAT_WAIT,
    IMG_ID_BRW_CONNECTION_STATUS_CSD_STATIC,
    IMG_ID_BRW_CONNECTION_STATUS_GPRS_STATIC,
    IMG_ID_BRW_SPLASH_SCREEN,
    IMG_ID_BRW_AUTH_USER_NAME,
    IMG_ID_BRW_AUTH_PASSWD,
#ifdef __MMI_JATAAYU_BRW_OFFLINE_PAGES__
    IMG_ID_BRW_SAVED_PAGES,
#endif 
    /* add new image ID above this line */
    IMG_ID_BRW_END
} IMG_ID_JATAAYU_BRW_ENUM;

/* String ID's */
typedef enum
{
    STR_ID_BRW_WAP = JATAAYU_BROWSER_BASE,
    /* add new string ID below this line */
    STR_ID_BRW_INTERNET_SERVICES,
    STR_ID_BRW_BOOKMARKS,
    STR_ID_BRW_OPTION,
    STR_ID_BRW_EDIT_BOOKMARK,
    STR_ID_BRW_ADD_BOOKMARK,
    STR_ID_BRW_RECENT_PAGES,
    STR_ID_BRW_ENTER_ADDRESS,
    STR_ID_BRW_SERVICE_INBOX,
    STR_ID_BRW_READ_OPTION,
    STR_ID_BRW_SETTINGS,
    STR_ID_BRW_SELECT_PROFILE,
    STR_ID_BRW_EDIT_PROFILE,
    STR_ID_BRW_DATA_ACCOUNT,
    STR_ID_BRW_GSM_DATA_ACCOUNT,
    STR_ID_BRW_GPRS_DATA_ACCOUNT,
    STR_ID_BRW_CONNECTION_TYPE,
    STR_ID_BRW_EDIT,
    STR_ID_BRW_CERTIFICATE_NAMES,
    STR_ID_BRW_CERTIFICATE,
    STR_ID_BRW_HOMEPAGE,
    STR_ID_BRW_GOTO,
    STR_ID_BRW_DELETE,
    STR_ID_BRW_DELETE_ALL,
    STR_ID_BRW_DELETE_ALL_INBOX,
    STR_ID_BRW_SET_AS_HOMEPAGE,
    STR_ID_BRW_TITLE,
    STR_ID_BRW_ADDRESS,
    STR_ID_BRW_READ,
    STR_ID_BRW_ACCEPT,
    STR_ID_BRW_BROWSER_OPTIONS,
    STR_ID_BRW_SERVICE_MESSAGES,
    STR_ID_BRW_CLEAR_CACHE,
    STR_ID_BRW_CLEAR_COOKIES,
#ifdef __MMI_JATAAYU_BRW_SECURITY_SETTING__
    STR_ID_BRW_SECURITY_SETTING,
#endif 
    STR_ID_BRW_CLEAR_ENTER_ADDR_LIST,
    STR_ID_BRW_ACTIVATE_PROFILE,
    STR_ID_BRW_RENAME_PROFILE,
    STR_ID_BRW_USER_NAME,
    STR_ID_BRW_PASSWORD,
    STR_ID_BRW_GSM_DATA,
    STR_ID_BRW_GPRS,
    STR_ID_BRW_CONNECTION_ORIENTED,
    STR_ID_BRW_CONNECTIONLESS,
    STR_ID_BRW_HTTP,
    STR_ID_BRW_TIMEOUT,
    STR_ID_BRW_SHOW_IMAGES,
    STR_ID_BRW_SHOW_HISTORY_AS,
    STR_ID_BRW_SHOW_HISTORY_AS_OPTION_TITLE,
    STR_ID_BRW_SHOW_HISTORY_AS_OPTION_URL,
    STR_ID_BRW_GO_TO_HOMEPAGE,
    STR_ID_BRW_REFRESH,
    STR_ID_BRW_SAVE_IMAGE_AS,
    STR_ID_BRW_SET_AS_WALLPAPER,
    STR_ID_BRW_SEND_IMAGE,
    STR_ID_BRW_OPEN_IMAGE,
    STR_ID_BRW_EDIT_IMAGE,
    STR_ID_BRW_VIA_MULTIMEDIA,
    STR_ID_BRW_VIA_INFRARED,
    STR_ID_BRW_VIEW,
    STR_ID_BRW_MESSAGE,
    STR_ID_BRW_SERVICE_MESSAGE_RCVD,
    STR_ID_BRW_EMPTY,
    STR_ID_BRW_BOOKMARK_FULL,
    STR_ID_BRW_DELETED,
    STR_ID_BRW_SAVED,
    STR_ID_BRW_DELETE_BOOKMARK,
    STR_ID_BRW_SAVE_BOOKMARK,
    STR_ID_BRW_DELETE_ALL_BOOKMARK,
    STR_ID_BRW_NO_HISTORY,
    STR_ID_BRW_INVALID_URL,
    STR_ID_BRW_DELETE_CACHE,
    STR_ID_BRW_DELETE_COOKIES,
    STR_ID_BRW_DELETE_ENTER_ADDR_LIST,
    STR_ID_BRW_GOTO_HOMEPAGE,
    STR_ID_BRW_DO_ELEMENT,
    STR_ID_BRW_FILENAME_EMPTY,
    STR_ID_BRW_FILE_ALREADY_EXISTS,
    STR_ID_BRW_SUBMIT,
    STR_ID_BRW_EXIT,
    STR_ID_BRW_INPUT_METHOD,
    STR_ID_BRW_JBROWSER,
    STR_ID_BRW_AUTHENTICATION,
    STR_ID_BRW_PLEASE_WAIT,
    STR_ID_BRW_DOWNLOADING,
    STR_ID_BRW_DOWNLOAD_ABORTED,
    STR_ID_BRW_DOWNLOAD_QUERY,
    STR_ID_BRW_CONTENT_TYPE,
    STR_ID_BRW_CONTENT_SIZE,
    STR_ID_BRW_BYTES_RECEIVED,
    STR_ID_BRW_KB_RECEIVED,
    STR_ID_BRW_DOWNLOADED,
    STR_ID_BRW_BYTES,
    STR_ID_BRW_KB,
    STR_ID_BRW_INVALID_TIMEOUT,
    STR_ID_BRW_DOWNLOAD,
    STR_ID_BRW_WAP_NOT_READY,
    STR_ID_BRW_MAKE_CALL,
    STR_ID_BRW_ADD_ENTRY,
    STR_ID_BRW_URL_LEN_EXCEED,
    STR_ID_BRW_FILE_SYSTEM_ERROR,
    STR_ID_BRW_FILE_SYSTEM_FULL,
    STR_ID_BRW_FILE_SAVE_FAILED,
    STR_ID_BRW_PUSH_EXPIRES,
    STR_ID_BRW_PUSH_URL,
    STR_ID_BRW_PUSH_MESSAGE,
    STR_ID_BRW_DELETE_RECENT_PAGE_ENTRY,
    STR_ID_BRW_DELETE_ALL_RECENT_PAGE_ENTRY,
    STR_ID_BRW_PROMPT_MESSAGE,
    STR_ID_BRW_SHOW_ADDRESS_LIST_AS,
    STR_ID_BRW_IMAGE_SELECTION,
    STR_ID_BRW_ENTER_ADR_GOTO,
    STR_ID_BRW_ENTER_ADR_EDIT,
    STR_ID_BRW_ENTER_ADR_ADD_TO_BOOKMARK,
    STR_ID_BRW_ENTER_ADR_DELETE,
    STR_ID_BRW_ENTER_ADR_DELETE_ALL,
    STR_ID_BRW_PUSH_INBOX_MODIFIED,
    STR_ID_BRW_PUSH_MEMORY_NOT_ENOUGH,
    STR_ID_BRW_SEND_SMS,
    STR_ID_BRW_LAUNCH_RTSP_APPLICATION,
    STR_ID_BRW_LAUNCH_EGE_APPLICATION,
    STR_ID_BRW_PUSH_EXPIRED,
    STR_ID_BRW_LONG_IDLE_DISCONNECTED,
    STR_ID_BRW_CANNOT_CONNECT,
    STR_ID_BRW_REN_PAGE_EDIT,
    STR_ID_BRW_REN_PAGE_SELECT,
#ifdef __MMI_JATAAYU_BRW_ADVANCED_RENDERED_PAGE_OPTIONS__
    STR_ID_BRW_CURRENT_URL,
    STR_ID_BRW_DISPLAY_CURRENT_URL,
    STR_ID_BRW_SEND_LINK_VIA_SMS,
#endif /* __MMI_JATAAYU_BRW_ADVANCED_RENDERED_PAGE_OPTIONS__ */ 
#ifdef __MMI_JATAAYU_BRW_OFFLINE_PAGES__
    STR_ID_BRW_OFFLINE_PAGES_SAVED_PAGES,
    STR_ID_BRW_OFFLINE_PAGES_OPTIONS,
    STR_ID_BRW_OFFLINE_PAGES_OPTION_GOTO,
    STR_ID_BRW_OFFLINE_PAGES_OPTION_RENAME,
    STR_ID_BRW_OFFLINE_PAGES_OPTION_PAGE_INFO,
    STR_ID_BRW_OFFLINE_PAGES_REPLACE_FILE,
    STR_ID_BRW_OFFLINE_PAGES_FULL,
    STR_ID_BRW_OFFLINE_PAGES_EDIT_FILENAME,
    STR_ID_BRW_OFFLINE_PAGES_DELETE_SAVED_PAGE,
    STR_ID_BRW_OFFLINE_PAGES_DELETE_ALL_SAVED_PAGES,
    STR_ID_BRW_OFFLINE_PAGES_INVALID_FILENAME,
    STR_ID_BRW_OFFLINE_PAGES_FILE_NOT_FOUND,
    STR_ID_BRW_OFFLINE_PAGES_CREATED_TIME,
    STR_ID_BRW_OFFLINE_PAGES_READ_ONLY,
    STR_ID_BRW_OFFLINE_PAGES_DELETING,
#endif /* __MMI_JATAAYU_BRW_OFFLINE_PAGES__ */ 
#if defined WAP_SEC_SUPPORT
    STR_ID_BRW_CONFIRM_SWITCH_TO_NONSECURE,
    STR_ID_BRW_CONFIRM_SWITCH_TO_SECURE,
    STR_ID_BRW_CONFIRM_POST_DATA_IN_NONSECURE,
    STR_ID_BRW_CLASS_THREE_AUTHENTICATION_FAILED,
    STR_ID_BRW_CLASS_TWO_AUTHENTICATION_FAILED,
    STR_ID_BRW_VIEW_CERTIFICATE,
    STR_ID_BRW_CHOOSE_CERTIFICATE,
    STR_ID_BRW_SELECT_USER_CERTIFICATE,
    STR_ID_BRW_LIST_USER_CERTIFICATES,
    STR_ID_BRW_ERROR_CREATING_FILE,
#endif /* defined WAP_SEC_SUPPORT */ 
    /* add new string ID above this line */
    STR_ID_BRW_END
} STR_ID_JATAAYU_BRW_ENUM;

/* Screen ID's */
typedef enum
{
    SCR_ID_BRW_INTERNET_SERVICES = JATAAYU_BROWSER_BASE,
    /* add new screen ID below this line */
    SCR_ID_BRW_JBROWSER_MAIN,
    SCR_ID_BRW_BOOKMARKS,
    SCR_ID_BRW_BOOKMARK_OPTIONS,
    SCR_ID_BRW_ADD_BOOKMARK,
    SCR_ID_BRW_RECENT_PAGES,
    SCR_ID_BRW_RECENT_PAGE_OPTIONS,
    SCR_ID_BRW_ENTER_ADDRESS,
    SCR_ID_BRW_ENTER_URL,
    SCR_ID_BRW_SERVICE_INBOX,
    SCR_ID_BRW_SERVICE_INBOX_OPTIONS,
    SCR_ID_BRW_READ_SERVICE_MESSAGE,
    SCR_ID_BRW_PUSH_MESSAGE_READ_OPTIONS,
    SCR_ID_BRW_SETTINGS,
    SCR_ID_BRW_BROWSER_OPTIONS,
    SCR_ID_BRW_RENDERED_PAGE_OPTIONS,
    SCR_ID_BRW_AUTHENTICATION,
    SCR_ID_BRW_TRANSITION_ANIMATION,
    SCR_ID_BRW_WAP_NOT_READY,
    SCR_ID_BRW_WAP_DOWNLOAD_PROGRESS,
    SCR_ID_BRW_WAP_DOWNLOAD_CONFIRM,
    SCR_ID_BRW_NEW_PUSH_MESSAGE_IND,
    SCR_ID_BRW_WAP_PROMPT_INPUT_SCREEN,
    SCR_ID_BRW_WAP_ALERT_SCREEN,
    SCR_ID_BRW_WAP_CONFIRM_SCREEN,
    SCR_ID_BRW_ENTER_ADDRESS_OPTIONS,
    SCR_ID_BRW_WAP_PROMPT_EDITOR_SCREEN,
    SCR_ID_BRW_DELETE_RECENT_PAGE_SCREEN,
    SCR_ID_BRW_LONG_IDLE_DISCONNECTED,
#ifdef __MMI_JATAAYU_BRW_ADVANCED_RENDERED_PAGE_OPTIONS__
    SCR_ID_BRW_CURRENT_URL,
#endif 
#ifdef __MMI_JATAAYU_BRW_OFFLINE_PAGES__
    SCR_ID_BRW_OFFLINE_PAGES_ENTER_NAME,
    SCR_ID_BRW_OFFLINE_PAGES_OPTIONS,
    SCR_ID_BRW_OFFLINE_PAGES_LIST,
    SCR_ID_BRW_OFFLINE_PAGES_PAGE_INFO,
    SCR_ID_BRW_OFFLINE_PAGES_ENTER_NEW_NAME,
    SCR_ID_BRW_OFFLINE_PAGES_EDIT_OPTION,
    SCR_ID_BRW_OFFLINE_PAGES_PROGRESS_SCREEN,
    SCR_ID_BRW_OFFLINE_PAGES_SHOW_NOTIFICATION,
#endif /* __MMI_JATAAYU_BRW_OFFLINE_PAGES__ */ 
#if defined WAP_SEC_SUPPORT
    SCR_ID_BRW_SELECT_USER_CERTIFICATE,
#endif 
    /* add new screen ID above this line */
    SCR_ID_BRW_END
} SCR_ID_JATAAYU_BRW_ENUM;

#endif /* defined (JATAAYU_SUPPORT) && defined (WAP_SUPPORT) */ 

#endif /* _JBROWSERRESDEF_H */ 

