/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   CameraMenuItems.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Camera menu items id define. 
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/

   /******** Start of ID ********/

    MENU_ID_CAMERA_APP,
    /* option menu */
    MENU_ID_CAMERA_OPTION,
    MENU_ID_CAMERA_SUBLCD_OPTION,
    MENU_ID_CAMERA_SUBLCD_PREVIEW,
    MENU_ID_CAMERA_SUBLCD_FLASH,
    MENU_ID_CAMERA_SUBLCD_FLASH_ON,
    MENU_ID_CAMERA_SUBLCD_FLASH_OFF,
    MENU_ID_CAMERA_SUBLCD_EXIT,
    MENU_ID_CAMERA_TO_IMGVIEW,
    MENU_ID_CAMERA_CAMERA_SETTING,
    MENU_ID_CAMERA_IMAGE_SETTING,
    MENU_ID_CAMERA_EFFECT_SETTING,
    MENU_ID_CAMERA_ADD_FRAME, MENU_ID_CAMERA_SELF_CAPTURE, MENU_ID_CAMERA_STORAGE, MENU_ID_CAMERA_RESTORE_DEFAULT,
    /* White Balance */
    MENU_ID_CAMERA_WB,
    MENU_ID_CAMERA_WB_AUTO,
    MENU_ID_CAMERA_WB_DAYLIGHT,
    MENU_ID_CAMERA_WB_TUNGSTEN,
    MENU_ID_CAMERA_WB_FLUORESCENT,
    MENU_ID_CAMERA_WB_CLOUD,
    MENU_ID_CAMERA_WB_INCANDESCENCE,
    MENU_ID_CAMERA_WB_MANUAL,
    MENU_ID_CAMERA_AUTOFOCUS_METERING,
    MENU_ID_CAMERA_AUTOFOCUS_1_ZONE,
    MENU_ID_CAMERA_AUTOFOCUS_3_ZONE,
    MENU_ID_CAMERA_AUTOFOCUS_5_ZONE,
    MENU_ID_CAMERA_AUTOFOCUS_MODE,
    MENU_ID_CAMERA_AUTOFOCUS_MODE_AUTO,
    MENU_ID_CAMERA_AUTOFOCUS_MODE_MACRO, MENU_ID_CAMERA_AUTOFOCUS_MODE_INFINITE, MENU_ID_CAMERA_AUTOFOCUS_MODE_MANUAL,
    /* Effect Setting */
    MENU_ID_CAMERA_EFFECT_NORMAL,
    MENU_ID_CAMERA_EFFECT_GRAYSCALE,
    MENU_ID_CAMERA_EFFECT_SEPIA,
    MENU_ID_CAMERA_EFFECT_SEPIA_GREEN,
    MENU_ID_CAMERA_EFFECT_SEPIA_BLUE,
    MENU_ID_CAMERA_EFFECT_COLOR_INVERT,
    MENU_ID_CAMERA_EFFECT_GRAY_INVERT,
    MENU_ID_CAMERA_EFFECT_BLACKBOARD,
    MENU_ID_CAMERA_EFFECT_WHITEBOARD,
    MENU_ID_CAMERA_EFFECT_COPPER_CARVING,
    MENU_ID_CAMERA_EFFECT_BLUE_CARVING,
    MENU_ID_CAMERA_EFFECT_EMBOSSMENT,
    MENU_ID_CAMERA_EFFECT_CONTRAST,
    MENU_ID_CAMERA_EFFECT_JEAN,
    MENU_ID_CAMERA_EFFECT_SKETCH,
    MENU_ID_CAMERA_EFFECT_OIL,
    MENU_ID_CAMERA_EFFECT_CUSTOM_FX_1,
    MENU_ID_CAMERA_EFFECT_CUSTOM_FX_2,
    MENU_ID_CAMERA_EFFECT_CUSTOM_FX_3,
    MENU_ID_CAMERA_EFFECT_CUSTOM_FX_SET_OPTION,
    MENU_ID_CAMERA_EFFECT_CUSTOM_FX_SET,
    MENU_ID_CAMERA_EFFECT_CUSTOM_FX_EDIT_EFFECT,
    MENU_ID_CAMERA_EFFECT_CUSTOM_FX_EDIT_OPTION,
    MENU_ID_CAMERA_EFFECT_CUSTOM_FX_EDIT_SAVE, MENU_ID_CAMERA_EFFECT_CUSTOM_FX_EDIT_RESTORE_DEFAULT,
    /* DSC Mode */
    MENU_ID_CAMERA_DSC_MODE,
    MENU_ID_CAMERA_DSC_MODE_AUTO,
    MENU_ID_CAMERA_DSC_MODE_SHUTTER_PRI,
    MENU_ID_CAMERA_DSC_MODE_APERTURE_PRI,
    MENU_ID_CAMERA_DSC_MODE_PORTRAIT,
    MENU_ID_CAMERA_DSC_MODE_LANDSCAPE,
    MENU_ID_CAMERA_DSC_MODE_SPORT,
    MENU_ID_CAMERA_DSC_MODE_FLOWER, 
    MENU_ID_CAMERA_DSC_MODE_NIGHT, 

    MENU_ID_CAMERA_ISO,
    MENU_ID_CAMERA_ISO_AUTO,
    MENU_ID_CAMERA_ISO_100,
    MENU_ID_CAMERA_ISO_200,
    MENU_ID_CAMERA_ISO_400,
    /* Add Frame */
    MENU_ID_CAMERA_ADD_FRAME_NORMAL,
    MENU_ID_CAMERA_ADD_FRAME_TILESHOT,
    MENU_ID_CAMERA_ADD_FRAME_COLOR_IDX,
    MENU_ID_CAMERA_ADD_FRAME_OFF,
    MENU_ID_CAMERA_ADD_FRAME_1,
    MENU_ID_CAMERA_ADD_FRAME_2,
    MENU_ID_CAMERA_ADD_FRAME_3,
    MENU_ID_CAMERA_ADD_FRAME_4,
    MENU_ID_CAMERA_ADD_FRAME_5,
    MENU_ID_CAMERA_ADD_FRAME_6,
    MENU_ID_CAMERA_ADD_FRAME_7,
    MENU_ID_CAMERA_ADD_FRAME_8,
    MENU_ID_CAMERA_ADD_FRAME_9,
    MENU_ID_CAMERA_ADD_FRAME_10,
    MENU_ID_CAMERA_ADD_FRAME_CUSTOM_1,
    MENU_ID_CAMERA_ADD_FRAME_CUSTOM_2,
    MENU_ID_CAMERA_ADD_FRAME_CUSTOM_3,
    MENU_ID_CAMERA_ADD_FRAME_CUSTOM_4,
    MENU_ID_CAMERA_ADD_FRAME_CUSTOM_5,
    MENU_ID_CAMERA_ADD_FRAME_OPTION,
    MENU_ID_CAMERA_ADD_FRAME_VIEW,
    MENU_ID_CAMERA_ADD_FRAME_SET, MENU_ID_CAMERA_ADD_FRAME_DE_ASSOCIATE, MENU_ID_CAMERA_ADD_FRAME_REPLACE,
    /* Cont shot */
    MENU_ID_CAMERA_CONT_SHOT_OFF,
    MENU_ID_CAMERA_CONT_SHOT_1,
    MENU_ID_CAMERA_CONT_SHOT_2,
    MENU_ID_CAMERA_CONT_SHOT_3, MENU_ID_CAMERA_CONT_SHOT_BURST, MENU_ID_CAMERA_CONT_SHOT_TILE,
    /* Delay timer */
    MENU_ID_CAMERA_DELAY_TIMER_OFF,
    MENU_ID_CAMERA_DELAY_TIMER_1, MENU_ID_CAMERA_DELAY_TIMER_2, MENU_ID_CAMERA_DELAY_TIMER_3,
    /* Storage */
    MENU_ID_CAMERA_STORAGE_PHONE, MENU_ID_CAMERA_STORAGE_MEMORY_CARD,
   /******** End of ID ********/

