
/*******************************************************************************
 * Copyright(C) 2005 MobileSoft Technology (NanJing) Co.,LTD.,
 * All rights reserved.
 * This is unpublished proprietary source code of MobileSoft Technology
 *
 * The copyright notice above does not evidence any actual or intended
 * publication of such source code  
 *******************************************************************************
 */
/*========================================================================
 * Module Name: CmsWapMmsMenuItems.h
 *
 * Module Function: 
 *     Author Name: 
 *     Create Date: 08/25/2005
 *
 *========================================================================
 */
#ifdef CMS_NEW_APP
/*以下是移软彩信浏览器部分菜单资源，请同步时注意*/
WAP_MENU_LOCALLINK_MENU_ID,
WAP_MENU_HOMEPAGE_MENU_ID, 
WAP_MENU_BOOKMARK_MENU_ID, 
WAP_MENU_NEWLINK_MENU_ID, 
WAP_MENU_HISTORY_MENU_ID, 
WAP_MENU_OFFLINE_MENU_ID,
WAP_MENU_SETTINGS_MENU_ID,

WAP_MENU_PUSHBOX_MENU_ID,

WAPOPTION_MAIN_MENU,

WAPBOOKMARKOPTION_MAIN_MENU,
WAPEMPTYBOOKMARKOPTION_MAIN_MENU,
WAPPUSHBOXOPTION_MAIN_MENU,
WAPHISTORYOPTION_MAIN_MENU,
WAPOFFLINEOPTION_MAIN_MENU,

WAP_OPTION_MENU_GOTOLINK_MENU_ID,
WAP_OPTION_MENU_BROWSERHOMEPAGE_MENU_ID,
WAP_OPTION_MENU_BACK_MENU_ID,
WAP_OPTION_MENU_URL_MENU_ID,
WAP_OPTION_MENU_REFRESH_MENU_ID,
WAP_OPTION_MENU_SAVEHOMEPAGE_MENU_ID,
WAP_OPTION_MENU_SAVECURRENTPAGE_MENU_ID,
WAP_OPTION_MENU_BOOK_MENU_ID,
WAP_OPTION_MENU_NEWLINK_MENU_ID,
WAP_OPTION_MENU_PUSHBOX_MENU_ID,
WAP_OPTION_MENU_BROWSEREXIT_MENU_ID,

WAP_BOOKMARKOPTION_MENU_LINK_MENU_ID,
WAP_BOOKMARKOPTION_MENU_EDIT_MENU_ID,

WAP_BOOKMARKOPTION_MENU_ADD_MENU_ID,
WAP_BOOKMARKOPTION_MENU_ADDURL_MENU_ID,
WAP_BOOKMARKOPTION_MENU_ADDTITLE_MENU_ID,
WAP_BOOKMARKOPTION_MENU_ADDFINISH_MENU_ID,

WAP_BOOKMARKOPTION_MENU_DELETEALL_MENU_ID,
WAP_BOOKMARKOPTION_MENU_DELETE_MENU_ID,
WAP_HISTORYOPTION_MENU_DELETE_MENU_ID,
WAP_HISTORYOPTION_MENU_DELETEALL_MENU_ID,

WAP_PUSHBOXOPTION_MENU_LINK_MENU_ID,
WAP_PUSHBOXOPTION_MENU_DELETE_MENU_ID,
WAP_PUSHBOXOPTION_MENU_DELETEALL_MENU_ID,

WAP_OFFLINEOPTION_MENU_LINK_MENU_ID,
WAP_OFFLINEOPTION_MENU_DELETE_MENU_ID,
WAP_OFFLINEOPTION_MENU_DELETEALL_MENU_ID,

WAP_SETTINGS_MENU_CLEARINPUTHISTOY_MENU_ID,
WAP_SETTINGS_MENU_CLEARPAGEHISTOY_MENU_ID,
WAP_SETTINGS_MENU_CLEARCACHE_MENU_ID,
WAP_SETTINGS_MENU_CLEARCOOKIE_MENU_ID,
WAP_SETTINGS_MENU_SETPUSHMESSAGE_MENU_ID,

WAP_SETTINGS_MENU_SETHOMEPAGE_MENU_ID,
WAP_SETTINGS_MENU_SETGATEWAY_MENU_ID,
WAP_SETTINGS_MENU_SETIMAGE_MENU_ID,
WAP_SETTINGS_MENU_SETBGMUSIC_MENU_ID,
WAP_SETTINGS_MENU_SETCERTIFICATES_MENU_ID,
WAP_SETTINGS_MENU_SETCONNECTMODE_MENU_ID,

/*Service List*/
WAP_SETTINGS_MENU_SERVICE_ID_MENU_ID,
WAP_SETTINGS_MENU_SERVICE_OPTIONS_MENU_ID,
WAP_SETTINGS_MENU_SERVICE_SET_MENU_ID,
WAP_SETTINGS_MENU_SERVICE_EDIT_MENU_ID,
WAP_SETTINGS_MENU_SERVICE_MODIFY_ID_MENU_ID,

WAP_SETTINGS_MENU_SETIMAGEOFF_MENU_ID,
WAP_SETTINGS_MENU_SETIMAGEON_MENU_ID,

WAP_SETTINGS_MENU_SETBGMUSICOFF_MENU_ID,
WAP_SETTINGS_MENU_SETBGMUSICON_MENU_ID,

WAP_SETTINGS_MENU_SETPUSHMESSAGEOFF_MENU_ID,
WAP_SETTINGS_MENU_SETPUSHMESSAGEON_MENU_ID,

WAP_SETTINGS_MENU_SETWAPGATEWAY_MENU_ID,
WAP_SETTINGS_MENU_SETWAPPORT_MENU_ID,

WAP_SETTINGS_MENU_SETNETACC_MENU_ID,

WAP_SETTINGS_MENU_SETGSMNETACC_MENU_ID,
WAP_SETTINGS_MENU_SETGSMNETACC1_MENU_ID,
WAP_SETTINGS_MENU_SETGSMNETACC2_MENU_ID,
WAP_SETTINGS_MENU_SETGSMNETACC3_MENU_ID,
WAP_SETTINGS_MENU_SETGSMNETACC4_MENU_ID,
WAP_SETTINGS_MENU_SETGSMNETACC5_MENU_ID,

WAP_SETTINGS_MENU_SETGPRSNETACC_MENU_ID,
WAP_SETTINGS_MENU_SETGPRSNETACC1_MENU_ID,
WAP_SETTINGS_MENU_SETGPRSNETACC2_MENU_ID,
WAP_SETTINGS_MENU_SETGPRSNETACC3_MENU_ID,
WAP_SETTINGS_MENU_SETGPRSNETACC4_MENU_ID,
WAP_SETTINGS_MENU_SETGPRSNETACC5_MENU_ID,

WAP_NEWLINK_MENU_INPUTURL_MENU_ID,
WAP_NEWLINK_MENU_HISTORY_MENU_ID,


/*-----MMS MENU---------*/
MMS_MENU_WMESSAGE_MENUID,
MMS_MENU_INBOX_MENUID,
MMS_MENU_OUTBOX_MENUID,
MMS_MENU_DRAFTBOX_MENUID,
/*-----MMS TEMPLATE Begin---------*/
MMS_MENU_TEMPLATES_MENUID,
MMS_TEMPLATES_TITLE_01_MENUID,
MMS_TEMPLATES_TITLE_02_MENUID,
MMS_TEMPLATES_TITLE_03_MENUID,
MMS_TEMPLATES_TITLE_04_MENUID,
MMS_TEMPLATES_TITLE_05_MENUID,
MMS_TEMPLATES_OPTION_MENUID,
MMS_TEMPLATE_OPTION_VIEW_MENUID,
MMS_TEMPLATE_OPTION_PROPERTIES_MENUID,
MMS_TEMPLATE_OPTION_WRITE_MENUID,
/*-----MMS TEMPLATE End---------*/
MMS_MENU_EMPTY_BOX_MENUID,
MMS_MENU_MSG_SETTINGS_MENUID,
MMS_MENU_MEMORY_STATUS_MENUID,
SMSMMS_MENU_WMESSAGE_MENUID,
SMSMMS_MENU_TEMPLATES_MENUID,
SMSMMS_MENU_SETTING_MENUID,
SMSMMS_MENU_MEMORY_STATUS_MENUID,

MMS_WMESSAGE_TO_MENUID,
MMS_WMESSAGE_CC_MENUID,
MMS_WMESSAGE_BCC_MENUID,
MMS_WMESSAGE_SUBJECT_MENUID,
MMS_WMESSAGE_CONTENT_MENUID,
MMS_SEND_OPTIONS_MENUID,

MMS_SEND_OPTIONS_SEND_MENUID,
MMS_SEND_OPTIONS_VIEW_MENUID,
MMS_SEND_OPTIONS_SAVE_MENUID,
MMS_SEND_OPTIONS_SEND_SAVE_MENUID,


MMS_SENDTO_OPTIONS_MENUID,
MMS_SENDTO_OPTIONS_ADD_NUMBER_MENUID,
MMS_SENDTO_OPTIONS_ADD_EMAIL_MENUID,
MMS_SENDTO_OPTIONS_AMEND_MENUID,
MMS_SENDTO_OPTIONS_DELETE_MENUID,
MMS_SENDTO_OPTIONS_DELETE_ALL_MENUID,

MMS_WMESSAGE_CONTENT_OPTIONS_MENUID,
MMS_CONTENT_OPTIONS_EDIT_TEXT_MENUID,
MMS_CONTENT_OPTIONS_INSERTNEWFRAME_MENUID,
MMS_CONTENT_OPTIONS_ADDIMAGE_MENUID,
MMS_CONTENT_OPTIONS_ADDMUSIC_MENUID,

MMS_CONTENT_OPTIONS_MUSICTIMESETTING_MENUID,	
MMS_CONTENT_OPTIONS_DELCURRENTIMAGE_MENUID,
MMS_CONTENT_OPTIONS_DELCURRENTMUSIC_MENUID,
MMS_CONTENT_OPTIONS_DELCURRENTFRAME_MENUID,
MMS_CONTENT_OPTIONS_EMPTYTEXT_MENUID,


MMS_INBOX_OPTIONS1_MENUID,
MMS_INBOX_OPTIONS2_MENUID,

MMS_INBOX_WAP_OPTIONS_MENUID,
MMS_INBOX_OPTIONS_PLAY_MENUID,
MMS_INBOX_OPTIONS_REPLY_MENUID,
MMS_INBOX_OPTIONS_DETAILS_MENUID,
MMS_INBOX_OPTIONS_FORWARD_MENUID,
MMS_INBOX_OPTIONS_SAVE_IMAGE_MENUID,
MMS_INBOX_OPTIONS_SAVE_MUSIC_MENUID,
MMS_INBOX_OPTIONS_GET_DETAILS_MENUID,
MMS_INBOX_OPTIONS_DELETE_MENUID,
MMS_INBOX_OPTIONS_DELETE_ALL_MENUID,
MMS_INBOX_OPTIONS_DOWNLOAD_MENUID,
MMS_INBOX_OPTIONS_PUSH_DELETE_MENUID,
MMS_INBOX_OPTIONS_PUSH_DELETE_ALL_MENUID,
MMS_INBOX_OPTIONS_PUSH_DETAILS_MENUID,
MMS_NEXT_SLIDE_MENUID,
MMS_PREV_SLIDE_MENUID,

MMS_INBOX_OPTIONS_MMS_REPLY_MENUID,
MMS_INBOX_OPTIONS_SMS_REPLY_MENUID,

MMS_INBOX_OPTIONS_DIAL_NUMBER_MENUID,
MMS_INBOX_OPTIONS_SAVE_NUMBER_MENUID,
MMS_INBOX_WAP_OPTIONS_LINK,
MMS_INBOX_WAP_OPTIONS_DELETE,
MMS_INBOX_WAP_OPTIONS_DELETE_ALL,

MMS_OUTBOX_OPTIONS_MENUID,
MMS_OUTBOX_OPTIONS_SEND_MENUID,
MMS_OUTBOX_OPTIONS_FORWARD_MENUID,
MMS_OUTBOX_OPTIONS_PLAY_MENUID,
MMS_OUTBOX_OPTIONS_DETAIL_MENUID,
MMS_OUTBOX_OPTIONS_DELETE_MENUID,
MMS_OUTBOX_OPTIONS_DELETE_ALL_MENUID,

MMS_DRAFTBOX_OPTIONS_MENUID,
MMS_DRAFTBOX_OPTIONS_SEND_MENUID,
MMS_DRAFTBOX_OPTIONS_PLAY_MENUID,
MMS_DRAFTBOX_OPTIONS_EDIT_MENUID,
MMS_DRAFTBOX_OPTIONS_DETAIL_MENUID,
MMS_DRAFTBOX_OPTIONS_DELETE_MENUID,
MMS_DRAFTBOX_OPTIONS_DELETE_ALL_MENUID,
MMS_DRAFTBOX_OPTIONS_SEND_SAVE_MENUID,

MMS_MENU_EMPTY_INBOX_MENUID,
MMS_MENU_EMPTY_OUTBOX_MENUID,
MMS_MENU_EMPTY_DRAFTBOX_MENUID,
MMS_MENU_EMPTY_ALLBOX_MENUID,

MMS_SEND_SETTINGS_MENUID,
MMS_RETRIEVING_SETTINGS_MENUID,
MMS_EDIT_SETTING_OPTION_MENUID,

MMS_MSG_SETTINGS_SERVICE_OPTION_MENUID,
MMS_MSG_SETTINGS_SERVICE_SET_MENUID,
MMS_MSG_SETTINGS_SERVICE_EDIT_MENUID,
MMS_MMSC_SETTINGS_MENUID,
MMS_NET_SETTINGS_MENUID,
MMS_INBOX_OPTIONS_SAVE_ACCESSORY_MENUID,
/*以上是移软彩信浏览器部分菜单资源，请同步时注意*/
#endif 