/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * EMMenuItems.h
 *
 * Project:
 * --------
 * 
 *
 * Description:
 * ------------
 *    This file is for Engineer Mode Menu IDs
 *
 * Author:
 * -------
 * -------
*****************************************************************************/
ENGINEER_MODE_MENUID,
    EM_NETWORK_SETTING_MENUID,
    EM_NETWORK_INFO_MENUID,
    EM_BAND_SEL_MENUID,
    EM_NETWORK_PREFER_RAT_MENUID,
    EM_NETWORK_CELL_LOCK_MENUID,
    EM_NETWORK_NETWORK_EVENT_MENUID,
    EM_NETWORK_NW_EVENT_START_MENUID,    
    EM_NETWORK_NW_EVENT_FILTER_MENUID,    
    EM_NETWORK_NW_EVENT_SETTING_MENUID,        
    
    EM_AUDIO_MENUID,
    EM_DEVICE_MENUID,
    EM_GPRS_ACT_MENUID,
    EM_GPRS_1stPDP_MENUID,
    EM_GPRS_2ndPDP_MENUID,    
    
    EM_AUD_SET_VOLUME_MENUID,
    EM_AUD_FIR_MENUID,
    EM_AUD_SPEECH_MENUID,
    EM_AUD_SIDE_TONE_MENUID,
    EM_AUD_KEY_TONE_MENUID,
    EM_AUD_CALL_TONE_MENUID,
    EM_AUD_MELODY_MENUID,
    EM_AUD_SOUND_MENUID,
    EM_AUD_MICROPHONE_MENUID,
    EM_AUD_RING_TONE_MENUID,
    EM_AUD_SET_MODE_MENUID,
    EM_AUD_NORMAL_MODE_MENUID,
    EM_AUD_LOUDSP_MODE_MENUID,
    EM_AUD_HEADSET_MODE_MENUID,
    EM_AUD_SPEECH_ENHANCEMENT_MENUID,
    EM_AUD_SPH_ENH_COMMON_PARA_MENUID,
    EM_AUD_SPH_ENH_NORMAL_MODE_MENUID,
    EM_AUD_SPH_ENH_HEADSET_MODE_MENUID,
    EM_AUD_SPH_ENH_LOUDSPK_MODE_MENUID,
    EM_AUD_SPH_ENH_BT_EARPHONE_MODE_MENUID,
    EM_AUD_SPH_ENH_BT_CORDLESS_MODE_MENUID,
    EM_AUD_SPH_ENH_AUX1_MODE_MENUID,
    EM_AUD_SPH_ENH_AUX2_MODE_MENUID,
    EM_AUD_SPH_ENH_AUX3_MODE_MENUID,
    EM_AUD_SET_MAX_SWING_MENUID,
    EM_AUD_VOLUME_0_MENUID,
    EM_AUD_VOLUME_1_MENUID,
    EM_AUD_VOLUME_2_MENUID,
    EM_AUD_VOLUME_3_MENUID,
    EM_AUD_VOLUME_4_MENUID,
    EM_AUD_VOLUME_5_MENUID,
    EM_AUD_VOLUME_6_MENUID,
    EM_AUD_VOLUME_16_LINEAR_MENUID,
    EM_AUD_TV_OUT_MENUID,    
    EM_AUD_DEBUG_INFO_MENUID,
    EM_AUD_AUTO_VM_SETTING_MENUID,
    EM_DEV_LCD_MENU_ID,
    EM_DEV_LCD_SET_CONSTRAST_MENU_ID,
    EM_DEV_LCD_SET_BIAS_MENU_ID,
    EM_DEV_LCD_SET_LINERATE_MENU_ID,
    EM_DEV_LCD_SET_TEMPERATURE_MENU_ID,
    EM_DEV_LCD_SET_COLOR_MENU_ID,
    EM_DEV_LCD_DISPLAY_DEMO_PIC_MENU_ID,
    EM_DEV_GPIO_MENU_ID,
    EM_DEV_EXT_CAMERA_MENU_ID,
    EM_DEV_EXT_CAMERA_WRITE_MENU_ID,
    EM_DEV_EXT_CAMERA_READ_MENU_ID,
    EM_DEV_GPIO_LIST_MENU_ID,
    EM_DEV_GPIO_SET_MENU_ID,
    EM_DEV_GPO_SET_MENU_ID,
    EM_DEV_GPIO_LIST_0_MENU_ID,
    EM_DEV_GPIO_LIST_1_MENU_ID,
    EM_DEV_GPIO_LIST_2_MENU_ID,
    EM_DEV_GPIO_LIST_3_MENU_ID,
    EM_DEV_GPIO_LIST_4_MENU_ID,
    EM_DEV_GPIO_LIST_5_MENU_ID,
    EM_DEV_GPIO_LIST_6_MENU_ID,
    EM_DEV_GPIO_LIST_7_MENU_ID,
    EM_DEV_PWM_MENU_ID,
    EM_DEV_PWM_SET_1_MENU_ID,
    EM_DEV_PWM_SET_2_MENU_ID,
    EM_DEV_PWM_SET_3_MENU_ID,
    EM_DEV_EINT_MENU_ID,
    EM_DEV_ADC_MENU_ID,
    EM_DEV_CONTRAST_MENUID,
    EM_DEV_VIBRATOR_MENUID,
    EM_DEV_LCD_MAIN_MENU_ID,
    EM_DEV_LCD_SUB_MENU_ID,
    EM_DEV_MAIN_LCD_LED_MENUID,
    EM_DEV_SUB_LCD_LED_MENUID,
    EM_DEV_KEYPAD_LED_MENUID,
    EM_DEV_STATUS_LED_R_MENUID,
    EM_DEV_STATUS_LED_G_MENUID,
    EM_DEV_STATUS_LED_B_MENUID,
    EM_DEV_SET_UART_MENUID,
    EM_DEV_UART_SETTING_MENUID,
    EM_DEV_UART_POWER_ONOFF_MENUID,    
    EM_DEV_INLINE_CONFIG_UART_MENUID,
    EM_DEV_KEYPAD_MENUID,
    EM_DEV_HW_LEVEL_MENUID,
    EM_DEV_HW_LEVEL_MLCD_CON_MENUID,
    EM_DEV_HW_LEVEL_SLCD_CON_MENUID,
    EM_DEV_HW_LEVEL_BATTERY_MENUID,
    EM_DEV_HW_LEVEL_PWM1_MENUID,
    EM_DEV_HW_LEVEL_PWM2_MENUID,
    EM_DEV_HW_LEVEL_PWM3_MENUID,
    EM_DEV_CLAM_MENUID,
    EM_DEV_UART_1_MENUID,
    EM_DEV_UART_2_MENUID,
    EM_DEV_DEFAULT_USB_APP_MENUID,
    EM_DEV_DEFAULT_USB_DATA_MENUID,
    EM_DEV_DEFAULT_USB_DEBUG_MENUID,
    EM_DEV_DEFAULT_USB_TST_MENUID,
    EM_DEV_SLEEPMODE_MENUID,
    EM_DEV_SLEEPMODE_ON_MENUID,
    EM_DEV_SLEEPMODE_OFF_MENUID,
    EM_GPRS_AUTO_ATTACH_MENUID,
    EM_GPRS_ACTIVATE_PDP_MENUID,
    EM_GPRS_ACTIVATE_2ND_PDP_MENUID,
    EM_GPRS_ACTIVATE_2ND_PDP_PRIMARY_MENUID,
    EM_GPRS_ACTIVATE_2ND_PDP_SENCOND_MENUID,
    EM_GPRS_DEACTIVATE_PDP_MENUID,
    EM_GPRS_SEND_DATA_MENUID,
    EM_GPRS_SEND_DATA_NORM_MENUID,
    EM_GPRS_SEND_DATA_HDR_MENUID,
    EM_GPRS_PING_MENUID,
    EM_GPRS_PING_RSP_MENUID,
    EM_BAND_900_MENUID,
    EM_BAND_1800_MENUID,
    EM_BAND_DUAL_MENUID,
    EM_BAND_1900_MENUID,
    EM_BAND_850_MENUID,
    EM_MISC_MENUID,
    EM_AUTO_ANSWER_MENUID,
    EM_HIGHSPEED_SIM_MENUID,
    EM_BACKLIGHT_MENUID,
    EM_SERIAL_PORT_EN_MENUID,
    EM_WAP_MENUID,
    EM_WAP_ENABLE_DEBUG_MENUID,
    EM_WAP_OFFLINE_PAGE_MENUID,
    EM_WAP_USER_AGENT_MENUID,
    EM_WAP_USER_AGENT_MAUI_E800_MENUID,
    EM_WAP_USER_AGENT_SONY_P800_MENUID,
    EM_WAP_USER_AGENT_NOKIA_7250i_MENUID,
    EM_WAP_USER_AGENT_SHARP_GX21_MENUID,
    EM_WAP_USER_AGENT_SONY_T610_MENUID,
    EM_WAP_USER_AGENT_SAMSUNG_MENUID,
    EM_WAP_ACCEPT_HEADER_MENUID,
    EM_WAP_ACCEPT_HEADER_WAP121_MENUID,
    EM_WAP_ACCEPT_HEADER_WAP20_MENUID,
    EM_WAP_ACCEPT_HEADER_WML_MENUID,
    EM_WAP_ACCEPT_HEADER_XHTML_MENUID,
    EM_WAP_ACCEPT_HEADER_HTML_MENUID,
    EM_WAP_MMS_VERSION_MENUID,
    EM_WAP_MMS_VERSION_MMS_DEFAULT_MENUID,
    EM_WAP_MMS_VERSION_MMS10_MENUID,
    EM_WAP_MMS_VERSION_MMS11_MENUID,
    EM_WAP_MMS_VERSION_MMS12_MENUID,
    EM_POWER_ON_DURATION_MENUID,
    EM_J2ME_TCK_MENUID,
    EM_AUTO_TEST_SETTING_MENUID,
    EM_AUTO_TEST_OPTIONS_MENUID,
    EM_AUTO_TEST_ADD_MENUID,
    EM_AUTO_TEST_ENTER_PRIORITY_MENUID,
    EM_AUTO_TEST_CHANGE_PRIORITY_MENUID,
    EM_AUTO_TEST_REMOVE_MENUID,
    EM_AUTO_RESET_MENUID,
    EM_PWR_DOWN_CONTROL_MENUID,
    EM_SW_PATCH_MENUID,
    EM_FRM_PROFILING_MENUID,
    EM_UI_BENCHMARK_MENUID,
    EM_DEBUG_INFO_MENUID,
    EM_SYS_STATS_MENUID,
    EM_WRITE_SYS_STATS_MENUID,
    EM_SAVING_STAT_PWROFF_MENUID,
    EM_BT_MENUID,
    EM_BT_GENERNAL_TEST_MENUID,
    EM_BT_GET_CHIP_VERSION_MENUID,
    EM_BT_ENTRY_TSMOD_MENUID,
    EM_BT_ENTRY_FW_VERSION_MENUID,
    EM_BT_ENTRY_ADD_SCO_LNK_MENUID,
    EM_BT_ENTRY_RMV_SCO_LNK_MENUID,
    EM_BT_ENTRY_TEST_MENUID,
    EM_BT_DEBUG_TRACE_MENUID,
    EM_BT_ADD_AUDIO_CONNECTION_MENUID,
    EM_BT_REMOVE_AUDIO_CONNECTION_MENUID,
    EM_BT_ENTRY_LOOPBACK_MENUID,
    EM_BT_EXIT_TEST_MODE_MENUID,
    EM_BT_AVRCP_CMD_LIST_MENUID,
    EM_FS_TRACE_MENUID,
    EM_LAST_EXCEPTION_MENUID,
    EM_AMR_MENUID,
    EM_SOCKET_MENUID,
    EM_SOCKET_DNS_MENUID,
    EM_SOCKET_HTTP_MENUID,
    EM_SOCKET_ECHO_MENUID,
    EM_SOCKET_DATE_MENUID,
    EM_SOCKET_TRACERT_MENUID,

    /* BEGIN OF IPERF */
    EM_SOCKET_IPERF_MENUID,
    EM_SOCKET_IPERF_TCP_MENUID,
    EM_SOCKET_IPERF_UDP_MENUID,
    /* END OF IPERF */

    EM_SOCKET_DNS_OPTION_MENUID,
    EM_SOCKET_DNS_DONE_MENUID,
    EM_SOCKET_DNS_INPUT_METHOD_MENUID,
    EM_SOCKET_HTTP_OPTION_MENUID,
    EM_SOCKET_HTTP_DONE_MENUID,
    EM_SOCKET_HTTP_INPUT_METHOD_MENUID,
    EM_TOUCHSCREEN_MENUID,
    EM_TOUCHSCREEN_TEST_OPTION_MENUID,
    EM_TOUCHSCREEN_TEST_STATISTICS_MENUID,
    EM_TOUCHSCREEN_TEST_EXIT_MENUID,
    EM_MMI_DEBUG_MENUID,
    EM_MEMORY_DUMP_MENUID,
    EM_SWDBG_MENUID,
    EM_SWDBG_OFF_MENUID,
    EM_SWDBG_DSP_L1_PS_MENUID,
    EM_SWDBG_DSP_PS_MENUID,
    EM_SWDBG_L1_PS_MENUID,
    EM_SWDBG_MCU_MENUID,
    EM_SWDBG_MCU_DSP_MENUID,
    EM_SWDBG_MCU_DSP_IRDBG_MENUID,
    EM_SWDBG_DSP_L1_MENUID,
    EM_SWDBG_RESET_MENUID,
    EM_RAM_TEST_MENUID,
    EM_NAND_FORMAT_MENUID,
    EM_DEV_TVOUT_SETTING_MENUID,
    EM_DEV_TVOUT_SETTING_SWITCH_MENUID,
    EM_DEV_TVOUT_SETTING_TUNNING_MENUID,
    EM_VIDEO_HI_BITRATE_MENUID,
    EM_DEV_PMIC_6318_MENU_ID,
    EM_DEV_PMIC_6318_REGISTER_EDITOR_MENU_ID,
    EM_MISC_CELL_RESELECTION_MENUID,
    EM_MISC_FIXED_GAIN_FOR_HELIOS2_MENUID,
    EM_DEV_PMIC_6318_CHARGER_STATUS_MENU_ID,
    EM_DEV_PMIC_6318_SET_CHARGER_MENU_ID,
    EM_DEV_PMIC_6318_SET_CHARGER_CHREN_MENU_ID,
    EM_DEV_PMIC_6318_SET_CHARGER_AC_CURRENT_MENU_ID,
    EM_DEV_PMIC_6318_SET_CHARGER_USB_CHREN_MENU_ID,
    EM_DEV_PMIC_6318_SET_CHARGER_USB_CURRENT_MENU_ID,
    EM_DEV_PMIC_6318_RGB_MENU_ID,
    EM_DEV_PMIC_6318_RGB_R_MENU_ID,
    EM_DEV_PMIC_6318_RGB_R_CURRENT_MENU_ID,
    EM_DEV_PMIC_6318_RGB_G_MENU_ID,
    EM_DEV_PMIC_6318_RGB_G_CURRENT_MENU_ID,
    EM_DEV_PMIC_6318_RGB_B_MENU_ID,
    EM_DEV_PMIC_6318_RGB_B_CURRENT_MENU_ID,
    EM_DEV_PMIC_6318_KP_LED_MENU_ID,
    EM_DEV_PMIC_6318_KP_ENABLE_MENU_ID,
    EM_DEV_PMIC_6318_KP_DUTY_OPTION_MENU_ID,
    EM_DEV_PMIC_6318_KP_DIM_CLOCK_MENU_ID,
    EM_DEV_PMIC_6318_KP_CHR_PUMP_EN_MENU_ID,
    EM_DEV_PMIC_6318_KP_CHR_PUMP_CURRENT_MENU_ID,
    EM_DEV_PMIC_6318_BL_LED_MENU_ID,
    EM_DEV_PMIC_6318_BL_ENABLE_MENU_ID,
    EM_DEV_PMIC_6318_BL_DUTY_OPTION_MENU_ID,
    EM_DEV_PMIC_6318_BL_DIM_CLOCK_MENU_ID,
    EM_DEV_PMIC_6318_BL_DIM_BYPASS_MENU_ID,
    EM_DEV_PMIC_6318_AUDIO_MENU_ID,
    EM_DEV_PMIC_6318_AUDIO_SPEAKER_ENABLE_MENU_ID,
    EM_DEV_PMIC_6318_AUDIO_SPEAKER_GAIN_MENU_ID,
    EM_DEV_PMIC_6318_MISC_MENU_ID, 
    /* LCM BL Setting */
    EM_DEV_PMIC_6318_LCM_BL_SETTING_MENU_ID, 
    EM_DEV_DCMMODE_MENUID, 
    EM_DEV_UART_ONOFF_MENUID,
    /* profiling tool */
    MENU_ID_EM_PROFILING,
    MENU_ID_EM_PROFILING_MULTIMEDIA,
    MENU_ID_EM_PROFILING_AUTO_PLAY,
    MENU_ID_EM_PROFILING_VDOPLY,
    MENU_ID_EM_PROFILING_VDOPLY_START,
    MENU_ID_EM_PROFILING_VDOPLY_SETTING,
    MENU_ID_EM_PROFILING_VDOREC,
    MENU_ID_EM_PROFILING_VDOREC_START,
    MENU_ID_EM_PROFILING_VDOREC_SETTING,
    MENU_ID_EM_PROFILING_CAMERA,
    MENU_ID_EM_PROFILING_CAMERA_START,
    MENU_ID_EM_PROFILING_CAMERA_SETTING, EM_DEVICE_USB_MENNUID, EM_DEVICE_USB_OTG_SRP_MENNUID,
    MENU_ID_EM_PROFILING_IMAGE_DECODE,  /*Cathy ADD EM IMAGE DECODE*/
    MENU_ID_EM_PROFILING_IMAGE_DECODE_FOLDER,  /*Cathy ADD EM IMAGE DECODE*/
    MENU_ID_EM_PROFILING_IMAGE_DECODE_FOLDER_ROTATE,  /*Cathy ADD EM IMAGE DECODE*/

    /* RF Test Tool */
    EM_RF_TEST_TOOL_MENUID,
    /* GSM */
    EM_RF_TEST_GSM_MENUID,
    EM_RF_GSM_TX_TEST_MENUID,
    EM_RF_GSM_RX_TEST_MENUID,
    EM_RF_GSM_POWER_SCAN_MENUID,
    /* WiFi */
    EM_RF_TEST_WIFI_MENUID,
    /* WiFi TX */
    EM_RF_WIFI_TX_TESTS_MENUID,
    EM_RF_WIFI_TX_DAC_OFFSET_MENUID,
    EM_RF_WIFI_TX_OUTPUT_POWER_MENUID,
    EM_RF_WIFI_TX_CARRIER_SUPP_MENUID,   
    EM_RF_WIFI_TX_LOCAL_FREQUENCY_MENUID,      
    EM_RF_WIFI_TX_CONT_PKT_TX_MENUID,         
    /* WiFi Rx */
    EM_RF_WIFI_CONT_PKT_RX_MENUID,
    /* WiFi Power Save */
    EM_RF_WIFI_POWER_SAVE_MENUID,
    /* WiFi Register Access */
    EM_RF_WIFI_REGISTER_ACCESS_MENUID,   
    EM_RF_WIFI_REGISTER_MCR_MENUID,         
    EM_RF_WIFI_REGISTER_BBCR_MENUID,            
    EM_RF_WIFI_REGISTER_EEPROM_MENUID,               
   
    EM_DEVICE_FM_RADIO_MENU_ID,
    EM_DEVICE_FM_RADIO_MONO_MENU_ID,
    EM_DEVICE_FM_RADIO_STEREO_MENU_ID,
    EM_DEVICE_FM_RADIO_RSSI_MENU_ID,
    EM_DEVICE_FM_RADIO_IF_COUNT_DELTA_MENU_ID,
    EM_DEVICE_FM_RADIO_RSSI_INFO_MENU_ID,
   
    EM_DEVICE_RTC_XOSC_MENU_ID,
   
    EM_VOIP_MENNUID,
    EM_VOIP_SETTINGS_MENU_ID,
    EM_VOIP_SIP_SUPPORTED_MENU_ID,
    EM_VOIP_SIP_REQUIRE_MENU_ID,

    EM_VOIP_LOG_MENU_ID,
    EM_VOIP_LOG_VIEW_MENU_ID,
    EM_VOIP_LOG_SETTINGS_MENU_ID,
    
    EM_VOIP_LOG_OPTION_MENU_ID,
    EM_VOIP_LOG_OPTION_VIEW_MENU_ID,
    EM_VOIP_LOG_OPTION_DELETE_MENU_ID,
    EM_VOIP_LOG_OPTION_DELETE_ALL_MENU_ID,

    /* MT6223 Debug Mode */
    EM_MISC_MT_6223_DEBUG_MODE_MENU_ID,

    /* LSD Slower */
    EM_MISC_LSD_SLOWER_MENU_ID,
    
    /* BT RF Test */
    EM_DEVICE_BT_RF_TEST_MENUID,
    
    EM_DEVICE_BT_RF_TEST_TX_MENUID,
    EM_DEVICE_BT_RF_TEST_RX_MENUID,
    EM_DEVICE_BT_RF_TEST_BD_ADDR_MENUID,
    EM_DEVICE_BT_RF_TEST_MODE_MENUID,
    
    /* Cascading Menu */
    EM_MISC_CASCADE_MENU_MENU_ID,

