/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * FMMenuItems.h
 *
 * Project:
 * --------
 * 
 *
 * Description:
 * ------------
 *    This file is for Factory Mode Menu IDs
 *
 * Author:
 * -------
 * -------
*****************************************************************************/
//MTK: Robin, added for Factory Mode
//Lisen 0630
MENU_ID_FM_ROOT,
    MENU_ID_FM_VERSION,
    MENU_ID_FM_RESOURCE_BIN,
    MENU_ID_FM_RESOURCE_LANGPACK,
    MENU_ID_FM_RESOURCE_CUSTPACK,
    MENU_ID_FM_BBCHIP_VER,
    MENU_ID_FM_DSPCODE_VER,
    MENU_ID_FM_DSPATCH_VER,
    MENU_ID_FM_SW_SUMMARY,
    MENU_ID_FM_SW_VER,
    MENU_ID_FM_HW_VER,
    MENU_ID_FM_MELODY_VER,
    MENU_ID_FM_ISN,
    MENU_ID_FM_BUILD_TIME,
    MENU_ID_FM_LED,
    MENU_ID_FM_LCD,
    MENU_ID_FM_LCD_AUTO,
    MENU_ID_FM_LCD_R,
    MENU_ID_FM_LCD_G,
    MENU_ID_FM_LCD_B,
    MENU_ID_FM_LCD_W,
    MENU_ID_FM_LCD_BLACK,
    MENU_ID_FM_LCD_CONTRAST,
    MENU_ID_FM_LCD_CONTRAST_MAINLCD,
    MENU_ID_FM_LCD_CONTRAST_SUBLCD,
    MENU_ID_FM_KEYPAD,
    MENU_ID_FM_LOUDSPK,
    MENU_ID_FM_EACHLOOP,
    MENU_ID_FM_VIBRATOR,
    MENU_ID_FM_ADC,
    MENU_ID_FM_RECEIVER,
    MENU_ID_FM_RTC,
    MENU_ID_FM_HEADSET, MENU_ID_FM_CHARGER, MENU_ID_FM_RINGTONE, MENU_ID_FM_PARALLEL_LINE, MENU_ID_FM_N_CROSS_M,
    /* MTK: Robin end */
    MENU_ID_FM_AUTO_TEST_ROOT,
    MENU_ID_FM_AUTO_TEST_REPORT,
    MENU_ID_FM_AUTO_TEST_SUMMARY,
    MENU_ID_FM_AUTO_TEST_RESULT,
    MENU_ID_FM_AUTO_TEST_START,
    MENU_ID_FM_MEMORY_CARD,
    MENU_ID_FM_NAND_FLASH,
    MENU_ID_FM_CAMERA,
    MENU_ID_FM_CAMERA_SENSOR_SETTING,
    MENU_ID_FM_CAMERA_ISP_SETTING,
    MENU_ID_FM_CAMERA_SAVE_TO_NVRAM, MENU_ID_FM_CAMERA_RESTORE_DEFAULT, MENU_ID_FM_MTBF, MENU_ID_FM_UART,

    MENU_ID_FM_FMRADIO,

