/***********************************************
File name : MTPNP_AD_Menudef.h
Contents : dual sim menu define
History : Create by : Zhang Nan, Aug 2, 2007
************************************************/
/* #ifdef __MERCURY_MASTER__ */
MENU_MTPNP_SETTING,

MENU_MTPNP_HELPINFO,

/* engineer/factory mode begin */
MENU_MTPNP_EM_SET_OP_SIDE,
MENU_MTPNP_EM_DUALMODE,
MENU_EM_CHK_RSSI,
MENU_EM_CALLBACK_PSN,
MENU_EM_ASSERT_SLAVE,
MENU_MTPNP_FM_COMM,
MENU_MTPNP_FM_MIC,
MENU_MTPNP_FM_SPEAKER,
MENU_MTPNP_FM_RECEIVER,
MENU_MTPNP_FM_HEADSET,
/* engineer/factory mode end */

/* dual mode setting begin */
MENU_MTPNP_DM_SETTING,
MENU_MTPNP_DM_DUALCARD,
MENU_MTPNP_DM_CARD1,
MENU_MTPNP_DM_CARD2,
MENU_MTPNP_DM_FLIGHT,
#ifdef __DM_PWR_ON_QUERY_SUPPORT__
MENU_MTPNP_DM_QUERY,
#endif /* __DM_PWR_ON_QUERY_SUPPORT__ */
/* dual mode setting end */

/* startup option begin */
#ifdef __DM_PWR_ON_QUERY_SUPPORT__
MENU_MTPNP_QUERY,

MENU_MTPNP_QUERY_SEL_DUALCARD,
MENU_MTPNP_QUERY_SEL_CARD1,
MENU_MTPNP_QUERY_SEL_CARD2,
MENU_MTPNP_QUERY_SEL_FLIGHT,
#endif /* __DM_PWR_ON_QUERY_SUPPORT__ */
/* startup option end */

/* call setting begin */
MENU_MTPNP_DM_CALL_SETTING,
MENU_MTPNP_CALL_SETTING,
MENU_MTPNP_CALL_ID,
MENU_MTPNP_CALL_ID_AUTO,
MENU_MTPNP_CALL_ID_SHOW_ID,
MENU_MTPNP_CALL_ID_HIDE_ID,
MENU_MTPNP_CALL_WAIT,
MENU_MTPNP_CALL_FORWARD,
MENU_MTPNP_CALL_BARRING,
MENU_MTPNP_LINE_SWITCH,
MENU_MTPNP_LSW_LN1,
MENU_MTPNP_LSW_LN2,
/* call setting end */

/* call history begin */
MENU_MTPNP_DM_CALL_HISTORY,
MENU_MTPNP_CALL_HISTORY,
MENU_MTPNP_CALL_HISTORY_MISSED,
MENU_MTPNP_CALL_HISTORY_DIALED,
MENU_MTPNP_CALL_HISTORY_RECVD,
MENU_MTPNP_CALL_HISTORY_DELETE,
MENU_MTPNP_CALL_HISTORY_CALLTIME,
MENU_MTPNP_CALL_HISTORY_CALLCOST,
MENU_MTPNP_CALL_HISTORY_SMSCOUNTER,
MENU_MTPNP_CALL_HISTORY_GPRSCOUNTER,
MENU_MTPNP_CALL_HISTORY_SENT,
MENU_MTPNP_CALL_HISTORY_RECEIVED,
MENU_MTPNP_DELLOG_MISSED_CALLS,
MENU_MTPNP_DELLOG_DIALED_CALLS, 
MENU_MTPNP_DELLOG_RECEIVED_CALLS, 
MENU_MTPNP_ALL_CALLS,
MENU_MTPNP_LAST_CALL_TIME, 
MENU_MTPNP_CALL_OUT_TIME,
MENU_MTPNP_CALL_IN_TIME, 
MENU_MTPNP_ALL_CALL_TIME, 
MENU_MTPNP_CALL_COST_LASTCALL,
MENU_MTPNP_CALL_COST_ALLCOST,
MENU_MTPNP_CALL_COST_RESETCOUNTER,
MENU_MTPNP_CALL_COST_MAXCOUNT,
MENU_MTPNP_CALL_COST_PRICEUNIT,
MENU_MTPNP_CALL_HISTORY_GPRS_LASTSENT,
MENU_MTPNP_CALL_HISTORY_GPRS_LASTRECEIVED,
MENU_MTPNP_CALL_HISTORY_GPRS_ALLSENT,
MENU_MTPNP_CALL_HISTORY_GPRS_ALLRECEIVED,
MENU_MTPNP_CALL_HISTORY_GPRS_RESETCOUNTER,

MENU_MTPNP_RECEIVED_CALL_LIST_OPTIONS, 
MENU_MTPNP_RECEIVED_CALL_MENU_INFO,
MENU_MTPNP_RECEIVED_CALL_MENU_DELETE,
MENU_MTPNP_RECEIVED_CALL_MENU_SAVE,
MENU_MTPNP_RECEIVED_CALL_MENU_CALL,
MENU_MTPNP_RECEIVED_CALL_MENU_EDIT,
MENU_MTPNP_RECEIVED_CALL_MENU_SENDSMS,
MENU_MTPNP_RECEIVED_CALL_MENU_SENDMMS,
MENU_MTPNP_DIALED_CALL_LIST_OPTIONS, 
MENU_MTPNP_DIALED_CALL_MENU_INFO,
MENU_MTPNP_DIALED_CALL_MENU_DELETE,
MENU_MTPNP_DIALED_CALL_MENU_SAVE, 
MENU_MTPNP_DIALED_CALL_MENU_CALL,
MENU_MTPNP_DIALED_CALL_MENU_EDIT,
MENU_MTPNP_DIALED_CALL_MENU_SENDSMS,
MENU_MTPNP_DIALED_CALL_MENU_SENDMMS,
MENU_MTPNP_MISSED_CALL_LIST_OPTIONS, 
MENU_MTPNP_MISSED_CALL_MENU_INFO,
MENU_MTPNP_MISSED_CALL_MENU_DELETE,
MENU_MTPNP_MISSED_CALL_MENU_SAVE, 
MENU_MTPNP_MISSED_CALL_MENU_CALL,
MENU_MTPNP_MISSED_CALL_MENU_EDIT,
MENU_MTPNP_MISSED_CALL_MENU_SENDSMS,
MENU_MTPNP_MISSED_CALL_MENU_SENDMMS,
MENU_MTPNP_MISSED_CALL_NOTIFY,
MENU_MTPNP_MISSED_CALL_NOTIFY_MASTER,
MENU_MTPNP_MISSED_CALL_NOTIFY_SLAVE,

MENU_MTPNP_SIM1_RECEIVED_NUM_CALL,
MENU_MTPNP_SIM1_DIALED_NUM_CALL,
MENU_MTPNP_SIM1_MISSED_NUM_CALL,

MENU_ID_CHIST_DUAL_CARD_MIXED_CALL_LOG,
MENU_ID_CHIST_DUAL_CARD_MIXED_CALL_LOG_MASTER,
MENU_ID_CHIST_DUAL_CARD_MIXED_CALL_LOG_SLAVE,

/* call history end */

/* ip dial begin */
MENU_MTPNP_IP_NUM_ACTIVATE,
/* ip dial end */

/* phone setting begin */
MENU_MTPNP_PHONE_SETTING,
/* phone setting end */

/* card2 msisdn begin */
MENU_MTPNP_CARD2_PHBEXTRA,
MENU_MTPNP_DM_SHOW_OWNER_NUMBER,
MENU_MTPNP_SHOW_CARD2_OWNER_NUMBER,
/* card2 msidsn end */

/* phb extra number begin */
MENU_MTPNP_CARD2_OWNER_NUMBER,
MENU_MTPNP_CARD2_OWNER_NUMBER_OPTION,
MENU_MTPNP_CARD2_OWNER_NUMBER_ERASE,
MENU_MTPNP_CARD2_OWNER_NUMBER_EDIT,
MENU_MTPNP_CARD2_SDL_NUMBER,
MENU_MTPNP_CARD2_SOS_NUMBER,
/* phb extra number end */

/* adn begin */
MENU_MTPNP_PB_ADD_SIM2,
MENU_MTPNP_PB_DELALL_SIM2,
MENU_MTPNP_PB_COPY_SIM2TOPHONE,
MENU_MTPNP_PB_MOVE_SIM2TOPHONE,
MENU_MTPNP_PB_COPY_PHONETOSIM2,
MENU_MTPNP_PB_MOVE_PHONETOSIM2,
MENU_MTPNP_PB_COPY_SIM2TOSIM1,
MENU_MTPNP_PB_MOVE_SIM2TOSIM1,
MENU_MTPNP_PB_COPY_SIM1TOSIM2,
MENU_MTPNP_PB_MOVE_SIM1TOSIM2,
MENU_MTPNP_PB_COPY_SIM1TOPHONE,
MENU_MTPNP_PB_MOVE_SIM1TOPHONE,
MENU_MTPNP_PB_COPY_PHONETOSIM1,
MENU_MTPNP_PB_MOVE_PHONETOSIM1,

MENU_MTPNP_PB_COPYALL_SIM2TOPHONE,	
MENU_MTPNP_PB_COPYALL_PHONETOSIM2,
MENU_MTPNP_PB_COPYALL_SIM1TOSIM2,		
MENU_MTPNP_PB_COPYALL_SIM2TOSIM1,
MENU_MTPNP_PB_PRE_STORAGE_SIM2,
MENU_MTPNP_PHB_NLF_SIM2,

MENU_MTPNP_PHB_OPTION_IP_DIAL_SIM1,
MENU_MTPNP_PHB_OPTION_IP_DIAL_SIM2,
/* adn end */

/* fdn begin */
MENU_MTPNP_FDN_MAIN,
MENU_MTPNP_MENU_FDN_MODE,
MENU_MTPNP_MENU_FDN_LIST,
MENU_MTPNP_FDN_NAME,
MENU_MTPNP_FDN_NUMBER,
MENU_MTPNP_FDN_VIEW_OPTIONS_MAIN,
MENU_MTPNP_FDN_VIEW_OPTIONS_ADD,
MENU_MTPNP_FDN_VIEW_OPTIONS_EDIT,
MENU_MTPNP_FDN_VIEW_OPTIONS_DELETE,
/* fdn end */

/* plmn begin */
MENU_MTPNP_DM_NETWORK_SETUP,
MENU_MTPNP_NETWORK_SETUP,
MENU_MTPNP_SELECTION_MODE,
MENU_MTPNP_PREFERRED_NETWORKS,
MENU_MTPNP_GPRS_CONNECTION,
MENU_MTPNP_SELECTION_MODE_MANUAL,
MENU_MTPNP_SELECTION_MODE_AUTOMATIC,
MENU_MTPNP_SELECTION_MODE_CHOICE,
MITEM_MTPNP_PRF_NWK_OPTIONS_PSEUDO,
MITEM_MTPNP_PRR_NWK_ADD,
MITEM_MTPNP_PRR_NWK_NEW,
MITEM_MTPNP_PRR_NWK_DELETE,
MITEM_MTPNP_PRR_NWK_EDIT,
MENU_MTPNP_ADD_FROM_LIST_OPTIONS,
MENU_MTPNP_ADD_FROM_LIST_DONE,
MENU_MTPNP_ADD_FROM_LIST_SORT_BY_DEFAULT,
MENU_MTPNP_ADD_FROM_LIST_SORT_BY_ALPHABET,
/* plmn end */

/* cell broadcast messages begin */
MENU_MTPNP_DM_CB_MESSAGES,
MENU_MTPNP_CB_MESSAGES,
MITEM_MTPNP_CB_SERVICE,
MITEM_MTPNP_CB_READ_MESSAGE,
MITEM_MTPNP_CB_CHANNELS,
MITEM_MTPNP_CB_LANGUAGE,
MITEM_MTPNP_CB_CHANNEL_ENBL_OPTIONS,
MITEM_MTPNP_CB_CHANNEL_ADD,
MITEM_MTPNP_CB_CHANNEL_EDIT,
MITEM_MTPNP_CB_CHANNEL_DELETE,
MITEM_MTPNP_CB_CHANNEL_SELECT,
/* cell broadcast messages end */

/* voice mail begin */
MENU_MTPNP_DM_VMAIL,
MENU_MTPNP_VMAIL,
MITEM_MTPNP_VOICE_MAIL_OPTION,
MITEM_MTPNP_VM_EDIT,
MITEM_MTPNP_VM_CONNECT_TO_VOICE,
/* voice mail end */

/* message setup begin */
MENU_MTPNP_DM_MSG_SETTINGS,
MENU_MTPNP_MSG_SETTINGS_MENUID,
MENU_MTPNP_PROFILE_SETTING,
MENU_MTPNP_COMMONSETTING,
MENU_MTPNP_MEMSTATUS,
MENU_MTPNP_PREFEREDSTORAGE,
MENU_MTPNP_PREFEREDSTORAGE_SIM,
MENU_MTPNP_PREFEREDSTORAGE_ME,
/* message setup end */

/* vcard begin */
MENU_MTPNP_VCARD_RECV_OPTION_TO_SIM,
/* vcard end */

/* sms begin */
MENU_MTPNP_EMS_ED_OPT_DONE,
MENU_MTPNP_OUTBOX_OPT_SEND_SMS,
MENU_MTPNP_MSGBOX_OPT_MASTER_FORWARD,
MENU_MTPNP_MSGBOX_OPT_SLAVE_FORWARD,
MENU_MTPNP_SMS_MASTER_INBOX_DELETE_ALL,
MENU_MTPNP_SMS_SLAVE_INBOX_DELETE_ALL,
MENU_MTPNP_SMS_MASTER_OUTBOX_DELETE_ALL,
MENU_MTPNP_SMS_SLAVE_OUTBOX_DELETE_ALL,
MENU_MTPNP_SMS_MASTER_DRAFTBOX_DELETE_ALL,
MENU_MTPNP_SMS_SLAVE_DRAFTBOX_DELETE_ALL,
/* sms end */

/* sms show begin */
MENU_MTPNP_SMS_MASTER_INBOX,
MENU_MTPNP_SMS_SLAVE_INBOX,
MENU_MTPNP_SMS_MASTER_OUTBOX,
MENU_MTPNP_SMS_SLAVE_OUTBOX,
MENU_MTPNP_SMS_SHOW_STYLE,
MENU_MTPNP_SMS_SHOW_MIXED,
MENU_MTPNP_SMS_SHOW_DIVIDED,
/* sms feature: support selce item */
MENU_MTPNP_SMS_SELECT_OPTION,
MENU_MTPNP_SMS_SELECT_SIM1_OPTION,
MENU_MTPNP_SMS_SELECT_SIM2_OPTION,
/* sms feature: support selce item when save sms from other module */
MENU_MTPNP_SMS_SELECT_SAVE_OPTION,
MENU_MTPNP_SMS_SELECT_SAVE_SIM1_OPTION,
MENU_MTPNP_SMS_SELECT_SAVE_SIM2_OPTION,
/* sms show end */

/* chat begin */
#ifdef __MMI_MESSAGES_CHAT__
MENU_MTPNP_CHARSTART_MASTER_NEW,
MENU_MTPNP_CHARSTART_SLAVE_NEW,
#endif /* __MMI_MESSAGES_CHAT__ */
/* chat begin */

SLAVE_MITEM_DG_END_ALL,

/* security setting begin */
MENU_MTPNP_DM_SECURITY_SETTING,
MENU_MTPNP_SECURITY_SETTING,
MENU_MTPNP_SIM_LOCK,
MENU_MTPNP_CHANGE_PASSWORD,
MENU_MTPNP_CP_PIN1,
MENU_MTPNP_CP_PIN2,
/* security setting end */

SLAVE_MITEM_INC_ACT_OPT_HOLD_ACT,
SLAVE_MITEM_INC_ACT_OPT_END_ACT,
SLAVE_MITEM_INC_HLD_OPT_RTRV,
SLAVE_MITEM_INC_HLD_OPT_END,
SLAVE_MITEM_IMA_OPT_HOLD_CONF,
SLAVE_MITEM_IMA_OPT_SPLIT,
SLAVE_MITEM_IMA_OPT_END_ONE_ACT,
SLAVE_MITEM_IMA_OPT_END_ALL_ACT,
SLAVE_MITEM_INC_MHLD_OPT_RTRV,
SLAVE_MITEM_INC_MHLD_OPT_END,
SLAVE_MITEM_IAH_OPT_SWAP,
SLAVE_MITEM_IAH_OPT_CONFER,
SLAVE_MITEM_IAH_OPT_END_ACT,
SLAVE_MITEM_IAH_OPT_END_HLD,
SLAVE_MITEM_IAH_OPT_END_ALL,
SLAVE_MITEM2019_CM_ALL_ACTIVE_END,
SLAVE_MITEM_IAMH_ALL_HELD_END,
SLAVE_NON_ACTIVE_CALL_NET_ACTIVE_MASTER,
SLAVE_NON_ACTIVE_CALL_NET_ACTIVE_SLAVE,
SLAVE_MENU_CALL_MASTER_INCOMING_REJECT,
SLAVE_MENU_CALL_INCOMING_OPT_ANSWER_SLAVE,
SLAVE_MENU_CALL_INCOMING_OPT_REJECT_SLAVE,
SLAVE_MENU_CALL_INCOMING_OPTION,
SLAVE_MENU_CM_INCOMING_AND_ACTIVE_MIX_OPTION,
SLAVE_MITEM_CM_SINGLE_MASTER_CALL_SWAP,
SLAVE_MITEM_CM_SINGLE_ACTIVE_LSKOPTIONS,
SLAVE_MITEM_CM_SINGLE_SLAVE_CALL_SWAP,
SLAVE_MITEM_CM_SINGLE_ACTIVE_LSK_ENDCALL,
SLAVE_MITEM_CM_SINGLE_ACTIVE_LSK_PB,
SLAVE_MITEM_CM_SINGLE_ACTIVE_LSK_SMS,
SLAVE_MITEM_CM_SINGLE_ACTIVE_LSK_DTMF,
SLAVE_NON_ACTIVE_CALL_NET_PARENT,
SLAVE_MENU_CC_MO_SELETECT_NET,
SLAVE_MENU_CC_MO_SELETECT_NET_CARD1,
SLAVE_MENU_CC_MO_SELETECT_NET_CARD2,
SLAVE_MENU_CC_CSK_SELETECT_CARD,
SLAVE_MENU_CC_CSK_SELETECT_CARD1,
SLAVE_MENU_CC_CSK_SELETECT_CARD2,
SLAVE_MENU_CALL_INCOMING_OPT_CARD1_IP_DIALBACK,
SLAVE_MENU_CALL_INCOMING_OPT_CARD2_IP_DIALBACK,
SLAVE_MENU_CALL_INCOMING_OPT_ACCEPT,
SLAVE_MENU_CALL_INCOMING_OPT_REJECT,
SLAVE_MENU_CALL_INCOMING_OPT_CARD1_DIALBACK,
SLAVE_MENU_CALL_INCOMING_OPT_CARD2_DIALBACK,
SLAVE_MENU_CALL_INCOMING_MIX_OPTION,
SLAVE_MENU_CALL_INCOMING_MIX_OPT_ACCEPT_BOTH,
SLAVE_MENU_CALL_INCOMING_MIX_OPT_REJECT_BOTH,
SLAVE_MENU_CALL_INCOMING_MIX_OPT_ACCEPTCARD1,
SLAVE_MENU_CALL_INCOMING_MIX_OPT_ACCEPTCARD2,
MENU_MTPNP_SELECT_CARD,
MENU_MTPNP_SELECT_CARD_1SELECTED,
MENU_MTPNP_SELECT_CARD_2SELECTED,

/* ucm begin */
MENU_ID_UCM_NEW_CALL_OPTION_DIAL_SIM2,
/* ucm end */

/* #endif */ /* __MERCURY_MASTER__ */

