/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * VRSDMenuItems.h
 *
 * Project:
 * --------
 * 
 *
 * Description:
 * ------------
 *    This file is for voice recognition related Menu IDs
 *
 * Author:
 * -------
 * -------
*****************************************************************************/
/* Main Menu */
MENU_ID_VRSD_APP,
    MENU_ID_VRSD_MAIN_MENU,
    MENU_ID_VRSD_RCG,
    MENU_ID_VRSD_DIAL,
    MENU_ID_VRSD_REDIAL,
    MENU_ID_VRSD_PROFILE, MENU_ID_VRSD_AUD_PLAYER, MENU_ID_VRSD_SHORTCUT, MENU_ID_VRSD_DELETE_ALL, MENU_ID_VRSD_STATUS,
    /* Voice Dial */
    MENU_ID_VRSD_DIAL_PHB_OPTION,
    MENU_ID_VRSD_DIAL_MAIN_MENU,
    MENU_ID_VRSD_DIAL_MAIN_ADD, MENU_ID_VRSD_DIAL_MAIN_CHANGE, MENU_ID_VRSD_DIAL_MAIN_DELETE,
    /* Voice Profile */
    MENU_ID_VRSD_PROFILE_MODE1,
    MENU_ID_VRSD_PROFILE_MODE2,
    MENU_ID_VRSD_PROFILE_MODE3, MENU_ID_VRSD_PROFILE_MODE4, MENU_ID_VRSD_PROFILE_MODE5, MENU_ID_VRSD_PROFILE_MODE6,
    /* Voice Shortcut */
    MENU_ID_VRSD_SHORTCUT_MAIN_MENU,
    MENU_ID_VRSD_SHORTCUT_MAIN_ADD, MENU_ID_VRSD_SHORTCUT_MAIN_CHANGE, MENU_ID_VRSD_SHORTCUT_MAIN_DELETE,
    /* Delete All Menu */
    MENU_ID_VRSD_DELETE_ALL_ALL,
    MENU_ID_VRSD_DELETE_ALL_DIAL,
    MENU_ID_VRSD_DELETE_ALL_REDIAL,
    MENU_ID_VRSD_DELETE_ALL_PROFILE, MENU_ID_VRSD_DELETE_ALL_AUDPLAYER, MENU_ID_VRSD_DELETE_ALL_SHORTCUT,

