/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  CSBMenuItems.h
 *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  
 *
 * Author:
 * -------
 *  
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/

	CSB_MENUID,
	CSB_VIEW_MENUID,
	CSB_SEARCH_MENUID,
	CSB_TESTOOL_MENUID,
	CSB_START_VIEW_MENUID,
	CSB_START_VIEW_X_MENUID,
	CSB_VIEW_OPTIONS_MENUID,
	CSB_VIEW_OPTIONS_VIEW_MODE_MENUID,
	CSB_VIEW_OPTIONS_MODE_SETTINGS_MENUID,
	
	CSB_OPTIONS_VIEW_MODE_AUTO_MENUID,
	CSB_OPTIONS_VIEW_MODE_MANUAL_MENUID,
	CSB_OPTIONS_SETTING_AUTO_MODE_TIME_MENUID,
	CSB_OPTIONS_SETTING_MANUAL_MODE_MENUID,
	
	CSB_SETTING_MANUAL_MODE_INTERACTIVE_MENUID,
	CSB_SETTING_MANUAL_MODE_NONINTERACTIVE_MENUID,
	
	CSB_SEARCH_CONTROL_MENUID,
	CSB_SEARCH_APP_MENUID,
	CSB_SEARCH_SCREENID_MENUID,

	CSB_TESTOOL_RUN_MENUID,
	CSB_TESTOOL_SET_LOC_MENUID,
	CSB_TESTOOL_VIEW_IMAGES_MENUID,

	CSB_CONTROL_CALL_MENUID,
	CSB_CONTROL_COLOR_PKR_MENUID,
	CSB_CONTROL_EDITOR_MENUID,
	CSB_CONTROL_EDITOR_LIST_MENUID,
	CSB_CONTROL_EDITOR_POPUP_MENUID,
	CSB_CONTROL_IDLE_SCREEN_MENUID,
	CSB_CONTROL_IMAGE_VWR_MENUID,
	CSB_CONTROL_LIST_MENUID,
	CSB_CONTROL_MATRIX_MENUID,
	CSB_CONTROL_POPUP_MENUID,
	CSB_CONTROL_PROGRESS_MENUID,
	CSB_CONTROL_SLIDER_MENUID,
	CSB_CONTROL_SUBLCD_MENUID,
	CSB_CONTROL_RADIO_BUTTON_MENUID,
	CSB_CONTROL_CHECK_BOX_MENUID,
	CSB_CONTROL_PANEL_MENUID,//052907 CSB

	CSB_APP_CALLS_MENUID,
	CSB_APP_EDITOR_MENUID,
	CSB_APP_ENGG_MODE_MENUID,
	CSB_APP_EXTRA_MENUID,
	CSB_APP_FUN_AND_GAMES_MENUID,
	CSB_APP_FILE_MANAGER_MENUID,
	CSB_APP_MESSAGES_MENUID,
	CSB_APP_MISC_MENUID,
	CSB_APP_MULTIMEDIA_MENUID,
	CSB_APP_ORGANIZER_MENUID,
	CSB_APP_PHONEBOOK_MENUID,
	CSB_APP_PROFILE_MENUID,
	CSB_APP_SERVICES_MENUID,
	CSB_APP_SHORTCUT_MENUID,
	CSB_APP_SETTINGS_MENUID,
	CSB_APP_WAP_MENUID,
	CSB_APP_UNUSED_MENUID,
	CSB_APP_HID_MENUID,//052907 CSB
		
	CSB_DUMMY_PARENT_MENUID,
	CSB_DUMMY_CHILD1_MENUID,
	CSB_DUMMY_CHILD2_MENUID,
	CSB_DUMMY_CHILD3_MENUID,
	CSB_DUMMY_CHILD4_MENUID,
	CSB_DUMMY_CHILD5_MENUID,
	CSB_DUMMY_CHILD6_MENUID,
	CSB_DUMMY_CHILD7_MENUID,
