/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  FileManagerMenuItems.h
 *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  
 *
 * Author:
 * -------
 *  
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/

MENU_FMGR_NAND_FLASH,
    MENU_FMGR_NOR_FLASH,
    MENU_FMGR_REM_DEVICE,
    MITEM_FMGR_DRIVE_OPTIONS,
    MITEM_FMGR_APP_DRIVE_OPTIONS,
    MENU_FMGR_DRIVE_OPEN,
    MENU_FMGR_DRIVE_FORMAT,
    MENU_FMGR_DRIVE_CHECK,
    MENU_FMGR_DRIVE_UNMOUNT,
    MENU_FMGR_SELECT_DONE,
    MITEM_FMGR_FOLDER_OPTIONS,
    MITEM_FMGR_APP_FOLDER_OPTIONS,
    MENU_FMGR_FOLDER_CREATE,
    MITEM_FMGR_TREE_OPTIONS,
    MENU_FMGR_TREE_OPEN,
    MENU_FMGR_TREE_SELECT,
    MITEM_FMGR_IMG_TYPE_OPTIONS,
    MITEM_FMGR_JPG_IMG_TYPE_OPTIONS,
    MITEM_FMGR_AUD_TYPE_OPTIONS,
    MITEM_FMGR_VID_TYPE_OPTIONS,
    MITEM_FMGR_EXE_TYPE_OPTIONS,
    MITEM_FMGR_GEN_TYPE_OPTIONS,
    MITEM_FMGR_THEME_TYPE_OPTIONS,
    MITEM_FMGR_APP_THEME_TYPE_OPTIONS,
    MITEM_FMGR_EBOOK_TYPE_OPTIONS,
	MITEM_FMGR_EBOOK_NO_FWD_TYPE_OPTIONS,
    MITEM_FMGR_EBOOK_NFO_TYPE_OPTIONS,
    MITEM_FMGR_APP_EBOOK_TYPE_OPTIONS,
    MITEM_FMGR_APP_EBOOK_NO_FWD_TYPE_OPTIONS,
    
    MITEM_FMGR_APP_IMG_TYPE_OPTIONS,
    MITEM_FMGR_APP_AUD_TYPE_OPTIONS,
    MITEM_FMGR_APP_VID_TYPE_OPTIONS,
    MITEM_FMGR_APP_EXE_TYPE_OPTIONS,
    MITEM_FMGR_APP_TYPE_OPTIONS,
    MITEM_FMGR_DRM_IMG_TYPE_OPTIONS,
    MITEM_FMGR_DRM_AUD_TYPE_OPTIONS,
    MITEM_FMGR_DRM_VID_TYPE_OPTIONS,
    MITEM_FMGR_DRM_EXE_TYPE_OPTIONS,
    MITEM_FMGR_DRM_GEN_TYPE_OPTIONS,
    MITEM_FMGR_DA_IMG_TYPE_OPTIONS,
    MITEM_FMGR_DA_AUD_TYPE_OPTIONS,
    MITEM_FMGR_DA_VID_TYPE_OPTIONS,
    MITEM_FMGR_DA_EXE_TYPE_OPTIONS,
    MITEM_FMGR_DA_THM_TYPE_OPTIONS,
    MITEM_FMGR_DA_EBK_TYPE_OPTIONS,
    MITEM_FMGR_DA_QRV_TYPE_OPTIONS,

    MITEM_FMGR_IMG_TYPE_NO_SIM_OPTIONS,
    MITEM_FMGR_AUD_TYPE_NO_FWD_OPTIONS,
    MITEM_FMGR_VID_TYPE_NO_SIM_OPTIONS,
    MITEM_FMGR_EXE_TYPE_NO_SIM_OPTIONS,
    MITEM_FMGR_GEN_TYPE_NO_SIM_OPTIONS,
    MENU_FMGR_ACTIVATE_THEME,
    MENU_FMGR_THEME_DELETE,
    MENU_FMGR_IMG_OPTION_VIEW,
    MENU_FMGR_IMG_OPTION_EDIT,
    MENU_FMGR_AUD_OPTION_PLAY,
    MENU_FMGR_VID_OPTION_PLAY,
    MENU_FMGR_EXE_OPTION_EXECUTE,
    MENU_FMGR_EBK_OPTION_OPEN,
    MENU_FMGR_GEN_OPTION_OPEN,
    MENU_FMGR_GEN_OPTION_SORT,
    MENU_FMGR_FWD_OPTION_IMG,
    MENU_FMGR_FWD_OPTION_IMG_DRM,
    MENU_FMGR_FWD_OPTION_AUD,
    MENU_FMGR_FWD_OPTION_AUD_NO_SIM,
    MENU_FMGR_FWD_OPTION_VID,
    MENU_FMGR_FWD_OPTION_VID_NO_FWD_OUT,
    MENU_FMGR_FWD_OPTION_VID_NO_SIM,
    MENU_FMGR_FWD_OPTION_VCARD,
    MENU_FMGR_FWD_OPTION_VCARD_NO_SIM,
    MENU_FMGR_FWD_OPTION_VCAL,
    MENU_FMGR_FWD_OPTION_VCAL_NO_SIM,
    MENU_FMGR_FWD_OPTION_MFH,
    MENU_FMGR_FWD_OPTION_GEN,
    MENU_FMGR_DA_FWD_OPTION_IMG,
    MENU_FMGR_DA_FWD_OPTION_AUD,
    MENU_FMGR_DA_FWD_OPTION_VID,
    MENU_FMGR_DA_FWD_OPTION_VCARD,
    MENU_FMGR_DA_FWD_OPTION_VCAL,
    MENU_FMGR_DA_FWD_OPTION_GEN,
    MENU_FMGR_DA_OPTION_FORWARD,

    MENU_FMGR_DA_MULTI_ODF_TYPE_OPTIONS,

    MENU_FMGR_GEN_OPTION_FORWARD,
    MENU_FMGR_GEN_OPTION_DETAIL,
    MENU_FMGR_GEN_OPTION_JPG_DETAIL,
    MENU_FMGR_GEN_OPTION_RENAME,
    MENU_FMGR_GEN_OPTION_DELETE,
    MENU_FMGR_GEN_OPTION_DELETE_ALL,
    MENU_FMGR_GEN_OPTION_COPY,
    MENU_FMGR_GEN_OPTION_MOVE,
    MENU_FMGR_FWD_WALLPAPER,
    MENU_FMGR_FWD_SUB_WALLPAPER,
    MENU_FMGR_FWD_SCREENSAVER,
    MENU_FMGR_FWD_POWER_ON,
    MENU_FMGR_FWD_POWER_OFF,
    MENU_FMGR_FWD_PHB,
    MENU_FMGR_FWD_TODOLIST,
    MENU_FMGR_FWD_SMS,
    MENU_FMGR_FWD_MMS,
    MENU_FMGR_FWD_EMS,
    MENU_FMGR_FWD_EMAIL,
    MENU_FMGR_FWD_IRDA,
    MENU_FMGR_FWD_BT,
    MENU_FMGR_FWD_PROFILE,
    MENU_FMGR_FWD_BGSOUND,
    MENU_FMGR_SORT_BY_NAME,
    MENU_FMGR_SORT_BY_TYPE,
    MENU_FMGR_SORT_BY_TIME,
    MENU_FMGR_SORT_BY_SIZE,
    MENU_FMGR_SORT_NONE, 
    
    MITEM_FMGR_EDITOR_OPTION, 
    MENU_FMGR_EDITOR_DONE, 
    MENU_FMGR_INPUT_METHOD,

    MITEM_FMGR_DRM_RIGHTS_OPTIONS,
    MENU_FMGR_DRM_RIGHTS_DETAIL,
    MENU_FMGR_DRM_RIGHTS_DELETE_ALL_EXPIRED,

    MENU_FMGR_BOOKMARK_FILE_TYPE_OPTIONS,
    MENU_FMGR_BOOKMARK_FILE_TYPE_NO_SIM_OPTIONS,
    MENU_FMGR_BOOKMARK_FILE_OPEN,

    MENU_FMGR_GEN_OPTION_PRINT,
    MENU_FMGR_PRINT_PICTBRIGE,
    MENU_FMGR_PRINT_BLUETOOTH,

    MENU_FMGR_DRM_OPTION_MUL_ODF_OPEN,
    MENU_FMGR_DRM_ODF_TYPE_OPTIONS,
    MENU_FMGR_DRM_ODF_NO_FWD_TYPE_OPTIONS,
    MENU_FMGR_APP_DRM_ODF_TYPE_OPTIONS,

    MITEM_FMGR_MUL_ODF_IMG_TYPE_OPTIONS,
    MITEM_FMGR_MUL_ODF_IMG_TYPE_NO_SIM_OPTIONS,
    MITEM_FMGR_MUL_ODF_AUD_TYPE_OPTIONS,
    MITEM_FMGR_MUL_ODF_AUD_TYPE_NO_SIM_OPTIONS,
    MITEM_FMGR_MUL_ODF_VID_TYPE_OPTIONS,
    MITEM_FMGR_MUL_ODF_VID_TYPE_NO_SIM_OPTIONS,
    MITEM_FMGR_MUL_ODF_EXE_TYPE_OPTIONS,
    MITEM_FMGR_MUL_ODF_EXE_TYPE_NO_SIM_OPTIONS,
    MITEM_FMGR_MUL_ODF_THM_TYPE_OPTIONS,
    MITEM_FMGR_MUL_ODF_THM_TYPE_NO_SIM_OPTIONS,
    MITEM_FMGR_MUL_ODF_EBK_TYPE_OPTIONS,
    MITEM_FMGR_MUL_ODF_EBK_TYPE_NO_SIM_OPTIONS,
    MITEM_FMGR_MUL_ODF_GEN_TYPE_OPTIONS,

    MENU_FMGR_VBOOKMARK_NO_FWD_TYPE_OPTIONS,
    MENU_FMGR_VBOOKMARK_TYPE_OPTIONS,
    MENU_FMGR_DA_VBOOKMARK_TYPE_OPTIONS,
    MENU_FMGR_VBOOKMARK_OPTION_GOTO,
    MENU_FMGR_VBOOKMARK_OPTION_OPEN,
