/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * vObjectsMenuItems.h
 *
 * Project:
 * --------
 * 
 *
 * Description:
 * ------------
 *    This file is for vObjects related Menu IDs
 *
 * Author:
 * -------
 * -------
*****************************************************************************/
MENU_ID_VCARD_FORWARD_OPTION,
    MENU_ID_VCARD_FORWARD_SMS,
    MENU_ID_VCARD_FORWARD_MMS,
    MENU_ID_VCARD_FORWARD_IRDA,
    MENU_ID_VCARD_FORWARD_EMAIL,
    MENU_ID_VCARD_FORWARD_FMGR,
    MENU_ID_VCARD_FORWARD_BT,
    MENU_ID_VCARD_ENTER_FILENAME_OPT,
    MENU_ID_VCARD_ENTER_FILENAME_OPT_DONE,
    MENU_ID_VCARD_ENTER_FILENAME_OPT_INPUT_METHOD,
    MENU_ID_VCARD_RECV_OPTION,
    MENU_ID_VCARD_RECV_OPTION_TO_SIM,
    MENU_ID_VCARD_RECV_OPTION_TO_PHONE,
    MENU_ID_VCARD_RECV_OPTION_FMGR,
    MENU_VCLNDR_FORWARD,
    MENU_VCLNDR_FORWARE_NO_SIM,
    MENU_VCLNDR_SEND_BY_SMS,
    MENU_VCLNDR_SEND_BY_MMS,
    MENU_VCLNDR_SEND_BY_IRDA,
    MENU_VCLNDR_SEND_BY_EMAIL,
    MENU_VCLNDR_SEND_BY_FILEMGR,
    MENU_VCLNDR_SEND_BY_BT,
    MENU_VCLNDR_FILENAME_OPT,
    MENU_VCLNDR_OPT_DONE,
    MENU_VCLNDR_OPT_INPUT_METHOD, MENU_VCLNDR_RECV_OPTION, MENU_VCLNDR_RECV_OPT_TDL, MENU_VCLNDR_RECV_OPT_FMGR,
    MENU_ID_VBKM_RECV_OPTION,
    MENU_ID_VBKM_RECV_OPTION_VIEW, 
    MENU_ID_VBKM_RECV_OPTION_SAVE_TO_FMGR, 
    MENU_ID_VBKM_RECV_OPTION_SAVE_TO_BOOKMARK,

