/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   VdoPlyResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Video Player Resource Define
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/
#ifndef VDO_PLY_RES_DEF_H
#define VDO_PLY_RES_DEF_H


/***************************************************************************** 
 * Image
 *****************************************************************************/
typedef enum
{
    IMG_ID_VDOPLY_APP_ICON = VDOPLY_BASE + 1,
    IMG_ID_VDOPLY_SUBLCD_ICON,

   /********** OSD **********/
    IMG_ID_VDOPLY_OSD_BG,
    IMG_ID_VDOPLY_OSD_BUTTOM_BAR_BG,

    /* play speed */
    IMG_ID_VDOPLY_OSD_SPEED_START,
    IMG_ID_VDOPLY_OSD_SPEED_50,
    IMG_ID_VDOPLY_OSD_SPEED_75,
    IMG_ID_VDOPLY_OSD_SPEED_100,
    IMG_ID_VDOPLY_OSD_SPEED_125,
    IMG_ID_VDOPLY_OSD_SPEED_150,
    IMG_ID_VDOPLY_OSD_SPEED_200,
    IMG_ID_VDOPLY_OSD_SPEED_400,
    IMG_ID_VDOPLY_OSD_SPEED_800,
    IMG_ID_VDOPLY_OSD_SPEED_FWD,
    IMG_ID_VDOPLY_OSD_SPEED_BWD,
    IMG_ID_VDOPLY_OSD_SPEED_UNDEF,

    /* volumn */
    IMG_ID_VDOPLY_OSD_VOLUME_START,
    IMG_ID_VDOPLY_OSD_VOLUME_1,
    IMG_ID_VDOPLY_OSD_VOLUME_2,
    IMG_ID_VDOPLY_OSD_VOLUME_3,
    IMG_ID_VDOPLY_OSD_VOLUME_4,
    IMG_ID_VDOPLY_OSD_VOLUME_5,
    IMG_ID_VDOPLY_OSD_VOLUME_6,
    IMG_ID_VDOPLY_OSD_VOLUME_7,
    IMG_ID_VDOPLY_OSD_VOLUME_8,
    IMG_ID_VDOPLY_OSD_VOLUME_9,
    IMG_ID_VDOPLY_OSD_VOLUME_10,
    IMG_ID_VDOPLY_OSD_VOLUME_11,
    IMG_ID_VDOPLY_OSD_VOLUME_12,
    IMG_ID_VDOPLY_OSD_VOLUME_13,
    IMG_ID_VDOPLY_OSD_VOLUME_14,
    IMG_ID_VDOPLY_OSD_VOLUME_15,
    IMG_ID_VDOPLY_OSD_VOLUME_16,
    IMG_ID_VDOPLY_OSD_VOLUME_MUTE,

    /* progress */
    IMG_ID_VDOPLY_OSD_PROGRESS_FILL,
    IMG_ID_VDOPLY_OSD_PROGRESS_EMPTY,
    IMG_ID_VDOPLY_OSD_PROGRESS_BUFFER,
    IMG_ID_VDOPLY_OSD_PROGRESS_DIS,

    /* loading */
    IMG_ID_VDOPLY_OSD_LOADING_BG,
    IMG_ID_VDOPLY_OSD_LOADING_FILL,
    IMG_ID_VDOPLY_OSD_LOADING_EMPTY,

    /* connecting */
    IMG_ID_VDOPLY_OSD_CONNECTING,
    
    /* bt connecting */
    IMG_ID_VDOPLY_OSD_BT_CONNECTING,

    /* opening */
    IMG_ID_VDOPLY_OSD_OPENING,    

    /* snapshoting */
    IMG_ID_VDOPLY_OSD_SNAPSHOTING,

    /* audio only animation */
    IMG_ID_VDOPLY_OSD_AUD_ONLY_ANIM,

    /* timer */
    IMG_ID_VDOPLY_OSD_TIMER_0,
    IMG_ID_VDOPLY_OSD_TIMER_1,
    IMG_ID_VDOPLY_OSD_TIMER_2,
    IMG_ID_VDOPLY_OSD_TIMER_3,
    IMG_ID_VDOPLY_OSD_TIMER_4,
    IMG_ID_VDOPLY_OSD_TIMER_5,
    IMG_ID_VDOPLY_OSD_TIMER_6,
    IMG_ID_VDOPLY_OSD_TIMER_7,
    IMG_ID_VDOPLY_OSD_TIMER_8,
    IMG_ID_VDOPLY_OSD_TIMER_9,
    IMG_ID_VDOPLY_OSD_TIMER_COL,
    IMG_ID_VDOPLY_OSD_TIMER_BG,
    
   /********** Fullscreen OSD **********/
    IMG_ID_VDOPLY_FULLSCR_OSD_BG,

    /* play speed */
    IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_START,
    IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_50,
    IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_75,
    IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_100,
    IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_125,
    IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_150,
    IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_200,
    IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_400,
    IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_800,
    IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_FWD,
    IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_BWD,
    IMG_ID_VDOPLY_FULLSCR_OSD_SPEED_UNDEF,

    /* volumn */
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_START,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_1,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_2,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_3,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_4,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_5,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_6,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_7,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_8,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_9,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_10,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_11,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_12,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_13,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_14,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_15,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_16,
    IMG_ID_VDOPLY_FULLSCR_OSD_VOLUME_MUTE,

    /* progress */
    IMG_ID_VDOPLY_FULLSCR_OSD_PROGRESS_FILL,
    IMG_ID_VDOPLY_FULLSCR_OSD_PROGRESS_EMPTY,
    IMG_ID_VDOPLY_FULLSCR_OSD_PROGRESS_BUFFER,
    IMG_ID_VDOPLY_FULLSCR_OSD_PROGRESS_DIS,
    
    /* timer */
    IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_0,
    IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_1,
    IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_2,
    IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_3,
    IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_4,
    IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_5,
    IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_6,
    IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_7,
    IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_8,
    IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_9,
    IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_COL,
    IMG_ID_VDOPLY_FULLSCR_OSD_TIMER_BG,

    IMG_ID_VDOPLY_FULLSCR_OSD_CK_PLAY,
    IMG_ID_VDOPLY_FULLSCR_OSD_CK_PLAY_SEL,
    IMG_ID_VDOPLY_FULLSCR_OSD_CK_PLAY_DIS,    
    IMG_ID_VDOPLY_FULLSCR_OSD_CK_PAUSE,
    IMG_ID_VDOPLY_FULLSCR_OSD_CK_PAUSE_SEL,
    IMG_ID_VDOPLY_FULLSCR_OSD_CK_PAUSE_DIS,
    IMG_ID_VDOPLY_FULLSCR_OSD_CK_RESUME,
    IMG_ID_VDOPLY_FULLSCR_OSD_CK_RESUME_SEL,
    IMG_ID_VDOPLY_FULLSCR_OSD_CK_RESUME_DIS,    

   /********** Touch Screen OSD **********/
    IMG_ID_VDOPLY_TOUCH_OSD_SPEED_INC,
    IMG_ID_VDOPLY_TOUCH_OSD_SPEED_INC_SEL,
    IMG_ID_VDOPLY_TOUCH_OSD_SPEED_INC_DIS,
    IMG_ID_VDOPLY_TOUCH_OSD_SPEED_DEC,
    IMG_ID_VDOPLY_TOUCH_OSD_SPEED_DEC_SEL,
    IMG_ID_VDOPLY_TOUCH_OSD_SPEED_DEC_DIS,
    IMG_ID_VDOPLY_TOUCH_OSD_VOLUME_INC,
    IMG_ID_VDOPLY_TOUCH_OSD_VOLUME_INC_SEL,
    IMG_ID_VDOPLY_TOUCH_OSD_VOLUME_INC_DIS,
    IMG_ID_VDOPLY_TOUCH_OSD_VOLUME_DEC,
    IMG_ID_VDOPLY_TOUCH_OSD_VOLUME_DEC_SEL,
    IMG_ID_VDOPLY_TOUCH_OSD_VOLUME_DEC_DIS,
    IMG_ID_VDOPLY_TOUCH_OSD_PROGRESS_INC,
    IMG_ID_VDOPLY_TOUCH_OSD_PROGRESS_INC_SEL,
    IMG_ID_VDOPLY_TOUCH_OSD_PROGRESS_INC_DIS,
    IMG_ID_VDOPLY_TOUCH_OSD_PROGRESS_DEC,
    IMG_ID_VDOPLY_TOUCH_OSD_PROGRESS_DEC_SEL,
    IMG_ID_VDOPLY_TOUCH_OSD_PROGRESS_DEC_DIS,
    IMG_ID_VDOPLY_TOUCH_OSD_SNAPSHOT,
    IMG_ID_VDOPLY_TOUCH_OSD_SNAPSHOT_SEL,
    IMG_ID_VDOPLY_TOUCH_OSD_SNAPSHOT_DIS,    
    IMG_ID_VDOPLY_TOUCH_OSD_FULLSCREEN,
    IMG_ID_VDOPLY_TOUCH_OSD_FULLSCREEN_SEL,
    IMG_ID_VDOPLY_TOUCH_OSD_FULLSCREEN_DIS,

    IMG_ID_VDOPLY_TOUCH_FULL_OSD_SPEED_INC,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_SPEED_INC_SEL,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_SPEED_INC_DIS,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_SPEED_DEC,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_SPEED_DEC_SEL,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_SPEED_DEC_DIS,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_VOLUME_INC,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_VOLUME_INC_SEL,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_VOLUME_INC_DIS,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_VOLUME_DEC,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_VOLUME_DEC_SEL,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_VOLUME_DEC_DIS,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_PROGRESS_INC,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_PROGRESS_INC_SEL,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_PROGRESS_INC_DIS,    
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_PROGRESS_DEC,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_PROGRESS_DEC_SEL,
    IMG_ID_VDOPLY_TOUCH_FULL_OSD_PROGRESS_DEC_DIS,    

    /* softkey image */
    IMG_ID_VDOPLY_RSK_BACK,
    IMG_ID_VDOPLY_RSK_BACK_SEL,
    IMG_ID_VDOPLY_RSK_STOP,
    IMG_ID_VDOPLY_RSK_STOP_SEL,
    IMG_ID_VDOPLY_LSK_PLAY,
    IMG_ID_VDOPLY_LSK_PLAY_SEL,
    IMG_ID_VDOPLY_LSK_PAUSE,
    IMG_ID_VDOPLY_LSK_PAUSE_SEL,
    IMG_ID_VDOPLY_LSK_RESUME,
    IMG_ID_VDOPLY_LSK_RESUME_SEL,
    IMG_ID_VDOPLY_LSK_OPTION,
    IMG_ID_VDOPLY_LSK_OPTION_SEL,

    /* softkey c-key action */
    IMG_ID_VDOPLY_CK_PLAY,
    IMG_ID_VDOPLY_CK_PLAY_SEL,
    IMG_ID_VDOPLY_CK_PLAY_DIS,    
    IMG_ID_VDOPLY_CK_PAUSE,
    IMG_ID_VDOPLY_CK_PAUSE_SEL,
    IMG_ID_VDOPLY_CK_PAUSE_DIS,    
    IMG_ID_VDOPLY_CK_RESUME,
    IMG_ID_VDOPLY_CK_RESUME_SEL,
    IMG_ID_VDOPLY_CK_RESUME_DIS,    

    IMG_ID_VDOPLY_TOTAL_COUNT
} mmi_vdoply_img_id_enum;


/* tmp */
typedef enum
{
    IMG_ID_VT_TITLE_BG = VDOPLY_BASE + 200,   
    IMG_ID_VT_BODY_BG,
    IMG_ID_VT_TIME_PANEL,
    IMG_ID_VT_CTRL_PANEL,
    IMG_ID_VT_SOFTKEY_BG,

    IMG_ID_VT_MAIN_WND_LOCAL,
    IMG_ID_VT_MAIN_WND_PEER,    
    IMG_ID_VT_SUB_WND_LOCAL,
    IMG_ID_VT_SUB_WND_PEER,    

    IMG_ID_VT_CAMERA_OFF,
    IMG_ID_VT_CAMERA_OFF_PRESS,   
    IMG_ID_VT_CAMERA_OFF_DISABLE,
    IMG_ID_VT_CAMERA_ON,
    IMG_ID_VT_CAMERA_ON_PRESS,    
    IMG_ID_VT_CAMERA_ON_DISABLE,
    IMG_ID_VT_CAMERA_FRONT,
    IMG_ID_VT_CAMERA_FRONT_PRESS,
    IMG_ID_VT_CAMERA_FRONT_DISABLE,    
    IMG_ID_VT_CAMERA_BACK,
    IMG_ID_VT_CAMERA_BACK_PRESS,
    IMG_ID_VT_CAMERA_BACK_DISABLE,    
    IMG_ID_VT_MIC_ON,
    IMG_ID_VT_MIC_ON_PRESS,    
    IMG_ID_VT_MIC_ON_DISABLE,        
    IMG_ID_VT_MIC_OFF,
    IMG_ID_VT_MIC_OFF_PRESS,    
    IMG_ID_VT_MIC_OFF_DISABLE,        
    IMG_ID_VT_SPEAKER_ON,
    IMG_ID_VT_SPEAKER_ON_PRESS,    
    IMG_ID_VT_SPEAKER_ON_DISABLE,        
    IMG_ID_VT_SPEAKER_OFF,
    IMG_ID_VT_SPEAKER_OFF_PRESS,
    IMG_ID_VT_SPEAKER_OFF_DISABLE,    
    IMG_ID_VT_AUD_REC_ON,
    IMG_ID_VT_AUD_REC_ON_PRESS,
    IMG_ID_VT_AUD_REC_ON_DISABLE,    
    IMG_ID_VT_AUD_REC_OFF,
    IMG_ID_VT_AUD_REC_OFF_PRESS,
    IMG_ID_VT_AUD_REC_OFF_DISABLE,    
    IMG_ID_VT_EV,
    IMG_ID_VT_EV_PRESS,
    IMG_ID_VT_EV_DISABLE,    
    IMG_ID_VT_ZOOM,
    IMG_ID_VT_ZOOM_PRESS,
    IMG_ID_VT_ZOOM_DISABLE,    
    IMG_ID_VT_SNAPSHOT,
    IMG_ID_VT_SNAPSHOT_PRESS,
    IMG_ID_VT_SNAPSHOT_DISABLE,    
    
    IMG_ID_VT_ZOOM_IN,
    IMG_ID_VT_ZOOM_IN_PRESS,
    IMG_ID_VT_ZOOM_OUT,
    IMG_ID_VT_ZOOM_OUT_PRESS,
    IMG_ID_VT_EV_INC,
    IMG_ID_VT_EV_INC_PRESS,
    IMG_ID_VT_EV_DEC,
    IMG_ID_VT_EV_DEC_PRESS,
    IMG_ID_VT_VOL_UP,
    IMG_ID_VT_VOL_UP_PRESS,
    IMG_ID_VT_VOL_DOWN,
    IMG_ID_VT_VOL_DOWN_PRESS,
    
    IMG_ID_VT_SCROLL_BAR,
    IMG_ID_VT_SCROLL_SLIDER,    
    IMG_ID_VT_SCROLL_EV,
    IMG_ID_VT_SCROLL_ZOOM,
    IMG_ID_VT_SCROLL_VOL,    
    
    IMG_ID_VT_MEMORY,  
    IMG_ID_VT_TIME,

    IMG_ID_VT_SNAPSHOTING,

    /* last image element */
    IMG_ID_VT_END
} mmi_vt_img_enum;


/***************************************************************************** 
 * String
 *****************************************************************************/
typedef enum
{
    /* app */
    STR_ID_VDOPLY_APP_NAME = VDOPLY_BASE + 1,

    /* menu */
    STR_ID_VDOPLY_STORAGE,
    STR_ID_VDOPLY_STORAGE_PHONE,
    STR_ID_VDOPLY_STORAGE_MEMORY_CARD,

    STR_ID_VDOPLY_NETWORK,
    STR_ID_VDOPLY_NETWORK_DATA_ACCOUNT,
    STR_ID_VDOPLY_NETWORK_PROXY,
    STR_ID_VDOPLY_NETWORK_UDP_PORT,

    STR_ID_VDOPLY_PROXY,
    STR_ID_VDOPLY_PROXY_ADDR,
    STR_ID_VDOPLY_PROXY_PORT,    

    STR_ID_VDOPLY_LOWEST_UDP_PORT,    
    STR_ID_VDOPLY_HIGHEST_UDP_PORT,

    STR_ID_VDOPLY_STREAMING_URL,
    STR_ID_VDOPLY_INPUT_URL,
    STR_ID_VDOPLY_PREDEFINED_URL,  
    STR_ID_VDOPLY_HISTORY_URL,  

    STR_ID_VDOPLY_HISTORY_PLAY,      
    STR_ID_VDOPLY_HISTORY_REMOVE,
    
    STR_ID_VDOPLY_OPTION_VIDEO_SETTING,    
    STR_ID_VDOPLY_OPTION_SAVE_CONNECTION,   
    STR_ID_VDOPLY_EDIT_FILENAME,

    /* player */
    STR_ID_VDOPLY_PLAY,
    STR_ID_VDOPLY_STOP,
    STR_ID_VDOPLY_PAUSE,
    STR_ID_VDOPLY_RESUME,
    STR_ID_VDOPLY_CONNECT,

    /* adjust */
    STR_ID_VDOPLY_BRIGHTNESS,
    STR_ID_VDOPLY_CONTRAST,
    STR_ID_VDOPLY_AUTO_REPEAT,

    STR_ID_VDOPLY_ADJUST_START,
    STR_ID_VDOPLY_ADJUST_N5,
    STR_ID_VDOPLY_ADJUST_N4,
    STR_ID_VDOPLY_ADJUST_N3,
    STR_ID_VDOPLY_ADJUST_N2,
    STR_ID_VDOPLY_ADJUST_N1,
    STR_ID_VDOPLY_ADJUST_0,
    STR_ID_VDOPLY_ADJUST_P1,
    STR_ID_VDOPLY_ADJUST_P2,
    STR_ID_VDOPLY_ADJUST_P3,
    STR_ID_VDOPLY_ADJUST_P4,
    STR_ID_VDOPLY_ADJUST_P5,
    STR_ID_VDOPLY_ADJUST_END,

    /* Notify */
    STR_ID_VDOPLY_NOTIFY_STORAGE_NOT_READY,
    STR_ID_VDOPLY_NOTIFY_INVALID_VIDEO_FILE,
    STR_ID_VDOPLY_NOTIFY_WRITE_PROTECTION,
    STR_ID_VDOPLY_NOTIFY_SNAPSHOT_FAILED,
    STR_ID_VDOPLY_NOTIFY_TEMINATE_PDL,
    STR_ID_VDOPLY_NOTIFY_PDL_TERMINATED,
    STR_ID_VDOPLY_NOTIFY_CONNECT_FAILED,
    STR_ID_VDOPLY_NOTIFY_PLAY_FAILED,
    STR_ID_VDOPLY_NOTIFY_INVALID_URL,
    STR_ID_VDOPLY_NOTIFY_INVALID_SETTING,    
    STR_ID_VDOPLY_NOTIFY_NETWORK_ERROR,
    STR_ID_VDOPLY_NOTIFY_INVALID_RESOLUTION,
    STR_ID_VDOPLY_NOTIFY_OVERWRITE_FILE,
    STR_ID_VDOPLY_NOTIFY_BT_IS_WORKING,
    STR_ID_VDOPLY_NOTIFY_REMOVE_URL_CONFIRM,
    STR_ID_VDOPLY_NOTIFY_HISTORY_REMOVED,    
    
    STR_ID_VDOPLY_END
} mmi_vdoply_str_id_enum;


/***************************************************************************** 
 * Screen
 *****************************************************************************/
typedef enum
{
    SCR_ID_VDOPLY_START = VDOPLY_BASE + 1,    
        
    SCR_ID_VDOPLY_APP, 
    SCR_ID_VDOPLY_PLAYER,
    SCR_ID_VDOPLY_OPTION,
    SCR_ID_VDOPLY_STORAGE,
    SCR_ID_VDOPLY_NETWORK,
    SCR_ID_VDOPLY_NETWORK_PROXY,        
    SCR_ID_VDOPLY_NETWORK_UDP_PORT,        
    SCR_ID_VDOPLY_VIDEO_SETTING,    
    SCR_ID_VDOPLY_ADJUST_OPTION,
    SCR_ID_VDOPLY_STREAMING_URL,
    SCR_ID_VDOPLY_PREDEFINED_URL,    
    SCR_ID_VDOPLY_HISTORY_URL,        
    SCR_ID_VDOPLY_HISTORY_OPTION,            
    SCR_ID_VDOPLY_URL_EDITOR,
    SCR_ID_VDOPLY_URL_EDITOR_OPTION,
    SCR_ID_VDOPLY_STREAM_EDITOR,
    SCR_ID_VDOPLY_STREAM_EDITOR_OPTION,
    
    SCR_ID_VDOPLY_END
    
} mmi_vdoply_scr_id_enum;

/* tmp */
typedef enum
{
    SCR_ID_VT_CALL_SCR = VDOPLY_BASE + 30
    
} mmi_vt_scr_id_enum;


#endif 
