//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mtk_simulator.rc
//
#define IDC_MYICON                      2
#define IDD_PCSIMULATOR_DIALOG          102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_PCSIMULATOR                 107
#define IDI_L_MTK                       107
#define IDI_SMALL                       108
#define IDI_S_MTK                       108
#define IDC_PCSIMULATOR                 109
#define IDC_MTK_SIMULATOR               109
#define IDS_MODE_STANDARD               112
#define IDS_MODE_ENHANCED               113
#define IDS_MODE_WLO                    114
#define IDS_MODE_UNDEF                  115
#define IDS_COMPREFIX                   116
#define IDS_BAUD110                     117
#define IDS_BAUD300                     118
#define IDS_BAUD600                     119
#define IDS_BAUD1200                    120
#define IDS_BAUD2400                    121
#define IDS_BAUD4800                    122
#define IDS_BAUD9600                    123
#define IDS_BAUD14400                   124
#define IDS_BAUD19200                   125
#define IDS_BAUD38400                   126
#define IDS_BAUD56000                   127
#define IDR_MAINFRAME                   128
#define IDS_BAUD128000                  128
#define IDS_BAUD256000                  129
#define IDS_PARITYNONE                  130
#define IDS_PARITYEVEN                  131
#define IDS_PARITYODD                   132
#define IDS_PARITYMARK                  133
#define IDS_PARITYSPACE                 134
#define IDS_ONESTOPBIT                  135
#define IDS_ONE5STOPBITS                136
#define IDS_TWOSTOPBITS                 137
#define IDS_BYLINE                      138
#define IDB_BITMAP1                     141
#define IDB_BITMAP2                     142
#define IDB_BITMAP3                     143
#define IDB_BITMAP4                     144
#define IDB_BITMAP5                     145
#define IDB_BITMAP6                     146
#define IDB_BITMAP7                     147
#define IDB_BITMAP8                     148
#define IDB_BITMAP9                     149
#define IDB_BITMAP10                    150
#define IDB_BITMAP11                    151
#define IDB_BITMAP12                    152
#define IDB_BITMAP13                    153
#define IDB_BITMAP14                    154
#define IDB_BITMAP15                    155
#define IDB_BITMAP16                    156
#define IDB_BITMAP17                    157
#define IDB_BITMAP18                    158
#define IDB_BITMAP19                    159
#define IDB_BITMAP20                    160
#define IDB_BITMAP21                    161
#define IDB_BITMAP22                    162
#define TTYACCEL                        166
#define TTYBITMAP                       168
#define TTYICON                         169
#define IDM_CONNECT                     170
#define TTYMENU                         171
#define IDM_DISCONNECT                  172
#define SETTINGSDLGBOX                  172
#define IDM_SETTINGS                    173
#define IDB_BTN1                        174
#define IDM_SENDBLOCK                   175
#define IDB_BTN2                        175
#define IDB_BTN3                        176
#define IDB_BTN4                        177
#define IDB_BTN5                        178
#define IDB_BTN6                        179
#define IDB_BTN7                        180
#define IDB_BTN8                        181
#define IDB_BTN9                        182
#define IDB_BTNSTAR                     183
#define IDB_BTNHASH                     184
#define IDB_BTN0                        185
#define IDB_BITMAP_UP                   187
#define IDB_BITMAP_DOWN                 188
#define IDB_BITMAP_LEFT                 189
#define IDB_BITMAP_RIGHT                190
#define IDB_BITMAP_MENU                 191
#define IDB_BITMAP_LSK                  192
#define IDB_BITMAP_RSK                  193
#define IDB_BITMAP_CALL                 194
#define IDB_BITMAP_END                  195
#define IDB_BITMAP_FUNC                 196
#define IDB_BITMAP_CLEAR                197
#define IDB_BITMAP_POWER                198
#define IDB_BITMAP_VUP                  200
#define IDB_BITMAP_VDOWN                201
#define IDB_BITMAP23                    202
#define IDD_ABOUTICON                   210
#define IDD_TITLELINE                   211
#define IDD_VERSION                     212
#define IDD_BYLINE                      213
#define IDD_WINDOWSMODE                 214
#define IDD_FREEMEM                     215
#define IDD_RESOURCES                   216
#define IDD_PORTCB                      220
#define IDD_BAUDCB                      221
#define IDD_DATABITSCB                  222
#define IDD_PARITYCB                    223
#define IDD_STOPBITSCB                  224
#define IDD_DTRDSR                      225
#define IDD_RTSCTS                      226
#define IDD_XONXOFF                     227
#define IDD_AUTOWRAP                    228
#define IDD_NEWLINE                     229
#define IDD_LOCALECHO                   230
#define IDD_FONT                        231
#define IDD_USECNRECEIVE                232
#define IDD_DISPLAYERRORS               233
#define IDD_OK                          234
#define IDD_CANCEL                      235
#define ABOUTDLGBOX                     236
#define IDM_CAPDIR                      32774
#define IDM_TOGCAP                      32775
#define IDM_SIGNALTOOL                  32776
#define IDM_SAVE_WIN_POS                32777
#define IDM_WIN_POS_STORE               32777
#define IDM_FDI                         32778
#define IDM_ERASE_NVRAM                 32779
#define ID_CHARGER_IN                   32780
#define ID_DOWNLOAD                     32782
#define ID_BACKUP_NVRAM                 32783
#define ID_RESTORE_NVRAM                32784
#define ID_POST_DATA                    32785
#define ID_SET_CHANNEL                  32786
#define ID_SEND_SMS                     32787
#define ID_SEND_SMS_MULTI               32788
#define ID_JAS_SENDSMS_BINARY           32790
#define ID_GSM_INCOMINGCALLRING         32791
#define ID_FS_SAVE_JAVA                 32793
#define ID_GSM_TIMEALARM                32794
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        203
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
