include custom_option.txt
include custom_include.txt
PLUTO_INC =  \
	 -I "../customerinc"  \
	 -I "../../MMI/PoC/PoCInc"  \
	 -I "../../MMI/DebugLevels/DebugLevelInc"  \
	 -I "../../MMI/Calls/CallsInc"  \
	 -I "../../MMI/ChatApp/ChatAppInc"  \
	 -I "../../MMI/EmailApp/EmailAppInc"  \
	 -I "../../MMI/IMPS/IMPSInc"  \
	 -I "../../MMI/Inc"  \
	 -I "../../MMI/Inc/ImgID"  \
	 -I "../../MMI/Inc/MenuID"  \
	 -I "../../MMI/Inc/StringID"  \
	 -I "../../MtkApp/MtkAppInc"  \
	 -I "../../MtkApp/EngineerMode/EngineerModeInc"  \
	 -I "../../MtkApp/Connectivity/ConnectivityInc"  \
	 -I "../../MtkApp/SoundRecorder/SoundRecorderInc"  \
	 -I "../../MtkApp/AudioPlayer/AudioPlayerInc"  \
	 -I "../../MtkApp/ABRepeater/ABRepeaterInc"  \
	 -I "../../MtkApp/mmiapi/include"  \
	 -I "../../MMI/Framework/osl/oslinc"  \
	 -I "../../MMI/CallManagement/CommonFiles/CommonInc"  \
	 -I "../../MMI/CallManagement/OutgoingCallManagement/OutgoingInc"  \
	 -I "../../MMI/CallManagement/IncomingCallManagement/IncomingInc"  \
	 -I "../../MMI/GSMCallApplication/CommonFiles/CommonInc"  \
	 -I "../../MMI/GSMCallApplication/OutgoingCallManagement/OutgoingInc"  \
	 -I "../../MMI/GSMCallApplication/IncomingCallManagement/IncomingInc"  \
	 -I "../../MMI/Setting/SettingInc"  \
	 -I "../../MMI/PhoneBook/PhoneBookInc"  \
	 -I "../../MMI/CommonScreens/CommonScreensInc"  \
	 -I "../../MMI/Framework/CommonFiles/CommonInc"	\
	 -I "../../MMI/Framework/Tasks/TasksInc"  \
	 -I "../../MMI/Framework/EventHandling/EventsInc"  \
	 -I "../../MMI/Framework/History/HistoryInc"  \
	 -I "../../MMI/Framework/MemManager/MemManagerInc"  \
	 -I "../../MMI/DataAccount/DataAccountInc"  \
	 -I "../../MMI/FunAndGames/FunAndGamesInc"  \
	 -I "../../MMI/gui/gui_inc"  \
	 -I "../../MMI/DateTime/DateTimeInc"  \
	 -I "../../MMI/MiscFramework/MiscFrameworkInc"  \
	 -I "../../MMI/Help/HelpInc"  \
	 -I "../../MMI/IdleScreen/IdleScreenInc"  \
	 -I "../../MMI/Messages/MessagesInc"  \
	 -I "../../MMI/NITZHandler/NITZInc"  \
	 -I "../../MMI/PROFILES/ProfilesInc"  \
	 -I "../../MMI/SAT/SATInc"  \
	 -I "../../MMI/SSC/SSCInc"  \
	 -I "../../MMI/Organizer/OrganizerInc"  \
	 -I "../../MMI/Extra/ExtraInc"  \
	 -I "../../MMI/JataayuApp\jBrowserMMI\jBrowserMMIInc"  \
	 -I "../../MMI/UnifiedMMS/MMSApp/MMSAppInc"  \
	 -I "../../MMI/JataayuApp\jCommonModules\jProvisioning\jProvisioningInc"  \
	 -I "../../MMI/JataayuApp\jCommonModules\jProfileHandler\jProfileHandlerInc"  \
	 -I "../../MMI/JataayuApp\jMMSMMI\jMMSMMIInc"  \
	 -I "../../MMI/Customer/CustResource"  \
	 -I "../../MMI/FontData"  \
	 -I "../../MMI/debuglevels/DebugLevelInc"  \
	 -I "../../MMI/MainMenu/MainMenuInc"  \
	 -I "../../MMI/ems/emsinc"  \
	 -I "../../MMI/Dictionary/DictInc"  \
	 -I "../../MMI/Framework/NVRAMManager/NVRAMManagerInc"  \
         -I "../../MMI/EbookReader/EbookInc"  \
         -I "../../MMI/VoIP/VoIPInc"  \
         -I "../../MMI/UCM/UCMInc"  \
	 -I "../../../kal/include"  \
	 -I "../../../ps/interfaces/enum"  \
	 -I "../../../ps/l4/include"  \
	 -I "../../../ps/gen/mcd"  \
	 -I "../../../ps/interfaces/local_inc"  \
	 -I "../../MMI/CPHS/CPHSInc"  \
	 -I "../../MMI/audio/audioinc"  \
	 -I "."  \
	 -I "../../../custom/audio/MT6208_CEVB"  \
	 -I "../Customize"  \
	 -I "../.."  \
	 -I "../../../custom/audio/CHICAGO2003_BB"  \
	 -I "../../../custom/audio/KLM2003_BB"  \
	 -I "../../../interface/mmi"  \
	 -I "../../MTkApp/Camera/CameraInc"	\
	 -I "../../MTkApp/Video/VideoInc"	\
	 -I "../../MTkApp/FileMgr/FileMgrInc" \
	 -I "../../../j2me/interface" \
	 -I "../../../j2me/jam/include" \
	 -I "../../MTkApp/GDI/GDIInc" \
	 -I "../../../fmt\include" \
	 -I "../../MTkApp/vObjects/vObjectInc" \
	 -I "../../MMI/Stopwatch/StopwatchInc"  \
	 -I "../../MTkApp/FMRadio/FMRadioInc"  \
	 -I "../../MTkApp/FMScheduleRec/FMScheduleRecInc"  \
	 -I "../../MTkApp/VRSD/VRSDInc" \
	 -I "../../MTkApp/VRSI/VRSIInc" \
	 -I "../../MTkApp/PhotoEditor\PhotoEditorInc" \
	 -I "../../MTkApp/BGSound/BGSoundInc" \
	 -I "../../MMI/Resource\Inc" \
 	 -I "../../../vendor/wap/jataayu4/adaptation/mmi/srcs/include" \
	 -I "../../MtkApp\JavaAgency\JavaAgencyInc" \
	 -I "../../MMI/UnifiedMessage/UnifiedMessageInc" \
	 -I "../../MtkApp/DLAgent/DLAgentInc" \
	 -I "../../MTkApp/BarcodeReader/BarcodeReaderInc" \
	 -I "../../MTkApp/SWFlash/SWFlashInc" \
	 -I "../../MTkApp/SyncML/SyncMLInc" \
	 -I "../../MMI/UnifiedComposer/UnifiedComposerInc" \
	 -I "../../MtkApp/VideoEditor/VideoEditorInc" \
	 -I "../../MTkApp/DeviceManagement/DeviceManagementInc" \
	 -I "../../MtkApp/CentralConfigAgent/CentralConfigAgentInc" \
	 -I "../../MTkApp/Avatar/AvatarInc" \
         -I "../../MtkApp/CSBrowser/CSBrowserInc" \
	 -I "../../MtkApp/PictBridge/PictBridgeInc" \
	 -I "../../MMI/BrowserApp/Browser/BrowserInc" \
	 -I "../../MMI/BrowserApp/Profile/ProfileInc" \
	 -I "../../MMI/BrowserApp/PushInbox/PushInboxInc"  \
	 -I "../../MTkApp/RightsMgr/RightsMgrInc" \
	 -I "../../MtkApp/DMUIApp/DMUIAppInc" \
	 -I "../../MMI/MobileService/MobileServiceInc" \
	 -I "../../MMI/CustomerService/CustomerServiceInc" \
	 -I "../../../vendor/langlearn/app/inc" \
	 -I "../../MTkApp/MyFavorite/MyFavoriteInc"

INC = $(PLUTO_INC) ${CUSTOM_INC}

MTK_DEFS = \
	-D "__MULTI_BIN_LOAD__" \
	-D "__EXE_DLL__"

SHARE_DEFS = \
	-D "WIN32"\
	-D "_DEBUG"\
	-D "_WINDOWS"\
	-D "_MBCS"\
	-D "_CONSOLE"\
	-D "__UCS2_ENCODING"\
	-D "MMI_ON_WIN32"\
	-D "__RESOURCE_GEN_"\
	-D "_L4_COMMON_STRUCT_H"\
	-D "DEVELOPER_BUILD_FIRST_PASS"\
	-D "__EM_MODE__"\
	-D "_AFXDLL"\
	-D "__MOD_SMSAL__"\
	-D "__SAT__"\
	-D "SHORTCUTS_APP"\
	-D "__POPULATE_ENGINE_"\
	-D "DEBUG_WINDOW"\
	-D "VM_SUPPORT" \
	-D "_WINERROR_H" \
	${CUSTOM_OPTION}

DEFINE = $(MTK_DEFS) $(SHARE_DEFS)

MMI_FEATURES_H = ../../MMI/Inc/MMI_features.h
ENUM_LIST_H = ./enum_list.h

OBJECTS = $(PLUTOMMI_OBJS) $(RES_OBJS) $(MTK_OBJS)

PLUTOMMI_OBJS = \
	CustResDeclare.o\
	PopulateRes.o\
	WriteRes.o\
	ResBytestream.o\
	BMPLoader.o\
	ABMLoader.o\
	bmp2ems.o\
	GIFLoader.o\
	ImageGetDimension.o\

MTK_OBJS = \
    mtk_resgenerator.o\
    str_merge.o\
    FontRes.o

RES_SOURCES = $(patsubst ../Res_MMI/%, %,$(wildcard ../Res_MMI/*.c))

RES_OBJS = $(patsubst %.c,%.o,$(RES_SOURCES))

PLMNCREATE_OBJS = plmncreate.o

INC_PATH_LIST = $(patsubst "%",%,$(filter "%",$(PLUTO_INC)))

H_LIST = $(filter-out %enum_list.h,$(foreach list, $(INC_PATH_LIST), $(wildcard $(list)/*.h)))

	

.SUFFIXES: .o .cpp .c

plmncreate.o: plmncreate.c $(H_LIST)
	@echo Compiling $< & \
	gcc $(DEFINE) $(INC) -g -w -c $< -o $@

%.o: %.c $(H_LIST)
	@echo Compiling $< & \
	gcc $(DEFINE) $(INC) -g -w -c $< -o $@

.cpp.o:
	@echo Compiling $< & \
	g++ $(DEFINE) $(INC) -g -w -c $< -o $@
#gcc $(DEFINE) $(INC) -dD -E -c $< -o $@

VPATH=../Res_MMI:.:../CustResource:../../MMI/Resource:../../MMI/MiscFramework/MiscFrameworkSrc
mtk_resgenerator.exe: $(OBJECTS)
	@echo Linking $< & \
	gcc -g -o mtk_resgenerator  $(OBJECTS) 

plmncreate.exe: $(PLMNCREATE_OBJS)
	@echo Linking $< & \
	gcc -g -o plmncreate  $(PLMNCREATE_OBJS)

#Debug/ResGenerator.obj Debug/ResGeneratorDoc.obj Debug/ResGeneratorView.obj Debug/MainFrm.obj Debug/DebugInit.obj Debug/Debug.obj
