/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *  RightsMgrResDef.h
 *
 * Project:
 * --------
 *  PlutoMMI
 *
 * Description:
 * ------------
 *  Resource definition of Rights Manager
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *          HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#ifndef __RIGHTSMGRRESDEF_H__
#define __RIGHTSMGRRESDEF_H__

typedef enum
{
    SCR_ID_RMGR_MAIN = RMGR_BASE,

    SCR_ID_RMGR_LIST_RO_MAIN,
    SCR_ID_RMGR_LIST_RO_OPTION,
    SCR_ID_RMGR_LIST_RO_DELETE,
    SCR_ID_RMGR_LIST_RO_DETAIL,

    SCR_ID_RMGR_WHITE_LIST_MAIN,
    SCR_ID_RMGR_WHITE_LIST_OPTION,
    SCR_ID_RMGR_WHITE_LIST_EDIT,
    SCR_ID_RMGR_WHITE_LIST_EDIT_OPTION,
    SCR_ID_RMGR_WHITE_LIST_CLEAN,

    SCR_ID_RMGR_GEN_INFO_MAIN,

    SCR_ID_RMGR_PROGRESS,

    SCR_ID_RMGR_DB_PROC,

    SCR_ID_DRM_AUTH,
    SCR_ID_DRM_SHOW_PERCENTAGE,
    SCR_ID_DRM_GET_CONFIRM,
    SCR_ID_DRM_NOTIFY_INFO,

    SCR_ID_DRM_PROCESSING_START,
    SCR_ID_DRM_START_REGISTER_AGENT,
    SCR_ID_DRM_START_ACQUIRE_RO,
    SCR_ID_DRM_START_DOMAIN_JOIN,
    SCR_ID_DRM_START_DOMAIN_LEAVE,
    SCR_ID_DRM_START_PREVIEW_DOWNLOAD,
    SCR_ID_DRM_START_SILENT_DOWNLOAD,
    SCR_ID_DRM_START_TIME_SYNC,
    SCR_ID_DRM_PROCESSING_END,

    SCR_ID_DRM_ACTIVATE_PROCESS,

    SCR_ID_RMGR_END
} mmi_rmgr_screen_id_enum;

typedef enum
{
    STR_ID_RMGR = RMGR_BASE,
    STR_ID_RMGR_LIST_RO,
    STR_ID_RMGR_INFO,
    STR_ID_RMGR_WHITE_LIST,
    STR_ID_RMGR_TRANS,
    STR_ID_RMGR_DB_PROC,
    STR_ID_RMGR_SWEEP,
    STR_ID_RMGR_BACKUP,
    STR_ID_RMGR_RESTORE,    
    STR_ID_RMGR_CERMGR,
    /* list ro */
    STR_ID_RMGR_LIST_RO_DETAIL,

    /* general info */
    STR_ID_RMGR_VERSION,
    STR_ID_RMGR_TIME,
    STR_ID_RMGR_STATUS,
    
    /* sweep */
    STR_ID_RMGR_SWEEP_REMOVE_RIGHTS,

    /* white list */
    STR_ID_RMGR_WHITE_LIST_EDIT_ENTER_ADDRESS,
    STR_ID_RMGR_WHITE_LIST_EMPTY,

    /* detail */
    STR_ID_RMGR_DETAIL_RIGHT,
    STR_ID_RMGR_DETAIL_PROTECTED,
    STR_ID_RMGR_DETAIL_UNPROTECTED,
    STR_ID_RMGR_DETAIL_UNLIMITED,
    STR_ID_RMGR_DETAIL_COUNT,
    STR_ID_RMGR_DETAIL_START,
    STR_ID_RMGR_DETAIL_END,
    STR_ID_RMGR_DETAIL_ACCUMULATED,
    STR_ID_RMGR_DETAIL_TIMEDCOUNT,    
    STR_ID_RMGR_DETAIL_TIMEDCOUNT_TIME,
    STR_ID_RMGR_DETAIL_SEC,
    STR_ID_RMGR_SHARED_RO,
    STR_ID_RMGR_SUMMARY,
    STR_ID_RMGR_MULTI_PART,

    /* DRM task */
    STR_ID_DRM_REGISTRATION_SUCCESS,
    STR_ID_DRM_RO_ACQUISITION_SUCCESS,
    STR_ID_DRM_DOMAIN_JOIN_SUCCESS,
    STR_ID_DRM_DOMAIN_LEAVE_SUCCESS,
    STR_ID_DRM_REG_FAILED,
    STR_ID_DRM_ROAP_XML_ERROR,
    STR_ID_DRM_ROAP_CANCELLED,
    STR_ID_DRM_ROAP_GENERAL_ERROR,
    STR_ID_DRM_ROAP_SOCKET_ERROR,
    STR_ID_DRM_ROAP_HOST_NOT_FOUND,
    STR_ID_DRM_ROAP_NOT_EXPECTED,
    STR_ID_DRM_NOT_IN_DOMAIN,
    STR_ID_DRM_DOMAIN_JOIN_FAILED,
    STR_ID_DRM_DOMAIN_LEAVE_FAILED,
    STR_ID_DRM_ROAP_GENERAL_FAILURE,
    STR_ID_DRM_ROAP_UNHANDLED_EXC,
    STR_ID_DRM_DB_ROLLBACK,
    STR_ID_DRM_ROAP_UNKNOWN_ERROR,
    STR_ID_DRM_ERROR_CODE,
    STR_ID_DRM_NOT_REGISTERED,
    STR_ID_DRM_RIGHTS_ISSUER,
    STR_ID_DRM_ALLOW_REGISTER,
    STR_ID_DRM_URL,
    STR_ID_DRM_ALLOW_JOIN,
    STR_ID_DRM_ALLOW_DOMAIN_LEAVE,
    STR_ID_DRM_DOMAIN,
    STR_ID_DRM_UNKNOWN,
    STR_ID_DRM_CONTENT,
    STR_ID_DRM_GOTO_RI,
    STR_ID_DRM_GOTO_RI_DOMAIN,
    STR_ID_DRM_ALLOW_PREVIEW_DOWNLOAD,
    STR_ID_DRM_ALLOW_SILENT_DOWNLOAD,
    STR_ID_DRM_BECAME_PLAYABLE,
    STR_ID_DRM_NOTE_FUTURERIGHTS,
    STR_ID_DRM_NOTE_VALIDRIGHTS,
    STR_ID_DRM_SERVER_ERRORMESSAGE,
    STR_ID_DRM_ERROR_REDIRECT_URL,
    STR_ID_DRM_BROWSE_REGISTER,
    STR_ID_DRM_ALLOW_TIMESYNC,
    STR_ID_DRM_IS_DEVICETIME_CORRECT,
    STR_ID_DRM_TIMEBASED_NOT_PLAYABLE,
    STR_ID_DRM_ADDITIONAL_RIGHTS,

    STR_ID_DRM_NOT_FOUND,
    STR_ID_DRM_NO_MEMORY,
    STR_ID_DRM_NOT_SUPPORTED,
    STR_ID_DRM_INVALID_PARAMETER,
    STR_ID_DRM_KEY_NOT_FOUND,
    STR_ID_DRM_CERT_NOT_FOUND,
    STR_ID_DRM_INVALID_KEY,
    STR_ID_DRM_CERT_EXPIRED,
    STR_ID_DRM_INVALID_CERT,
    STR_ID_DRM_INVALID_RO,
    STR_ID_DRM_DOMAIN_EXPIRED,
    STR_ID_DRM_NEED_DOMAIN_UPGD,
    STR_ID_DRM_INVALID_DRMTIME,
    STR_ID_DRM_DB_GENERAL_ERROR,
    STR_ID_DRM_INVALID_FILE_FORMAT,
    STR_ID_DRM_NO_RIGHTS,
    STR_ID_DRM_NETWORK_ERROR,
    STR_ID_DRM_DATABASE_ERROR,
    STR_ID_DRM_TIME_UNTRUSTED,

    STR_ID_DRM_START_REGISTER_AGENT,
    STR_ID_DRM_START_ACQUIRE_RO,
    STR_ID_DRM_START_DOMAIN_JOIN,
    STR_ID_DRM_START_DOMAIN_LEAVE,
    STR_ID_DRM_START_PREVIEW_DOWNLOAD,
    STR_ID_DRM_START_SILENT_DOWNLOAD,
    STR_ID_DRM_START_TIME_SYNC,

    STR_ID_DRM_REGISTER,
    STR_ID_DRM_ACQUIRE,
    STR_ID_DRM_JOIN,
    STR_ID_DRM_LEAVE,
    /* permission */
    STR_ID_DRM_PLAY,
    STR_ID_DRM_DISPLAY,
    STR_ID_DRM_EXECUTE,
    STR_ID_DRM_PRINT,
    STR_ID_DRM_EXPORT,

    
    STR_ID_RMGR_END
} mmi_rmgr_string_id_enum;

typedef enum
{
    IMG_ID_RMGR_ICON = RMGR_BASE,
    IMG_ID_RMGR_END
} mmi_rmgr_image_id_enum;

#endif /* __RIGHTSMGRRESDEF_H__ */ 

