/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * UserProfilesResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   UserProfile Resource Definitions
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef _USER_PROFILES_RESDEF_H
#define _USER_PROFILES_RESDEF_H

#include "Kal_non_specific_general_types.h"
#include "custom_equipment.h"

typedef enum
{
    STR_PROFILE_OPTION_CAPTION = PROFILES_BASE + 1,
    STR_PROFILES_GENERAL,
    STR_PROFILES_MEETING,
    STR_PROFILES_CAR,
    STR_PROFILES_OUTDOOR,
    STR_PROFILES_INDOOR,
    STR_PROFILES_HEADSET,
#ifdef __MMI_BT_PROFILE__    
    STR_PROFILES_BT,
#endif
    STR_PROFILES_SAVE_ASK,
    STR_GENERAL_ACTIVATE_MESSAGE,
    STR_MEETING_ACTIVATE_MESSAGE,
    STR_INDOOR_ACTIVATE_MESSAGE,
    STR_HEADSET_ACTIVATE_MESSAGE,
    STR_CAR_ACTIVATE_MESSAGE,
    STR_OUTDOOR_ACTIVATE_MESSAGE,
    STR_PROFILES_OPTION_ACTIVATE,
    STR_PROFILES_OPTION_CUSTOMIZE,
    STR_PROFILE_CAPTION,
    STR_PROFILE_CUSTOMIZE_CAPTION,
    STR_SILENT_ACTIVATE_MESSAGE,
    STR_SILENT_DEACTIVATE_MESSAGE,
    STR_VOLUME_LEVEL,
    STR_MT_CALL_ALERT_TYPE,
    STR_RING_TYPE,
    STR_TONE_SETUP,
    STR_CALL_TIME_REMINDER,
    STR_ANSEWRING_MODE,
    STR_LOUD_SPEAKER,
    STR_FONT_SIZE,
    STR_EXTRA_TONE,
    STR_VIBRATION_ONLY,
    STR_VIBRATION_AND_RING,
    STR_VIBRATION_THEN_RING,
    STR_RING,
#ifdef __MMI_CONNECT_NOTICE__
    STR_CONNECT_NOTICE,
    STR_NOTICE_NONE,
    STR_NOTICE_TONE_ONLY,
    STR_NOTICE_VIB_ONLY,
    STR_NOTICE_TONE_AND_VIB,
#endif /* __MMI_CONNECT_NOTICE__ */ 
    STR_VOLUME_LEVEL_CAPTION,
    STR_CALL_ALERT_CAPTION,
    STR_RING_TYPE_SINGLE,
    STR_RING_TYPE_REPEAT,
    STR_RING_TYPE_ASCENDNG,
    STR_RING_TYPE_CAPTION,
    STR_RING_VOLUME_LEVEL,
    STR_KEYPAD_VOLUME_LEVEL,
    STR_NORMAL_ANSEWRING_MODE,
    STR_ANYKEY_ANSEWRING_MODE,
    STR_AUTO_ANSEWRING_MODE,
    STR_ANSEWRING_MODE_CAPTION,
    STR_LOUD_SPEAKER_CAPTION,
    STR_LOUD_SPEAKER_ON,
    STR_LOUD_SPEAKER_OFF,
    
#if !defined(HARDWARE_LED_NOT_SUPPORT)    
    STR_LIGHT_STATUS,
    STR_LIGHT_STATUS_CAPTION,
    STR_LIGHT_STATUS_NONE,
    STR_LIGHT_STATUS_COLOR1,
    STR_LIGHT_STATUS_COLOR2,
    STR_LIGHT_STATUS_COLOR3,
    STR_LIGHT_STATUS_COLOR4,
    STR_LIGHT_STATUS_COLOR5,
    STR_LIGHT_STATUS_COLOR6,
#endif
    STR_CALL_TIME_REMINDER_CAPTION,
    STR_CALL_TIME_REMINDER_OFF,
    STR_CALL_TIME_REMINDER_SINGLE,
    STR_CALL_TIME_REMINDER_REPEAT,
    STR_TONE_FILE_NOT_EXIST,
    STR_TONE_SETUP_RING_TONE,
    STR_TONE_SETUP_SIM1_VOICE_RING_TONE,
    STR_TONE_SETUP_SIM2_VOICE_RING_TONE,
    STR_TONE_SETUP_VOICE_RING_TONE,
    STR_TONE_SETUP_VIDEO_RING_TONE,
    STR_TONE_SETUP_SIM1_RING_TONE,
    STR_TONE_SETUP_SIM2_RING_TONE,
    STR_TONE_SETUP_VDIEO_RING_TONE_EXT_SET,
    STR_TONE_SETUP_RING_TONE_PHB_EXT_SET,
    STR_TONE_SETUP_RING_TONE_EXT_SET,
    STR_TONE_SETUP_RING_TONE_EXT_DEL,
    STR_TONE_SETUP_RING_TONE_EXT_ADD,
    STR_TONE_SETUP_ALARM_TONE_EXT_SET,
    STR_TONE_SETUP_ALARM_TONE_EXT_DEL,
    STR_TONE_SETUP_ALARM_TONE_EXT_ADD,
    STR_TONE_SETUP_POWERON_TONE,
    STR_TONE_SETUP_POWEROFF_TONE,
    STR_TONE_SETUP_COVEROPEN_TONE,
    STR_TONE_SETUP_COVERCLOSE_TONE,
    STR_TONE_SETUP_MESSAGE_TONE,
    STR_TONE_SETUP_SIM1_MESSAGE_TONE,
    STR_TONE_SETUP_SIM2_MESSAGE_TONE,
    STR_TONE_SETUP_KEYPAD_TONE,
    STR_TONE_SETUP_WARNING_TONE,
    STR_PROFILES_RING_TONE_SETUP_CAPTION,
    STR_PROFILES_SIM1_VOICE_RING_TONE_SETUP_CAPTION,
    STR_PROFILES_SIM2_VOICE_RING_TONE_SETUP_CAPTION,
    STR_PROFILES_VOICE_RING_TONE_SETUP_CAPTION,
    STR_PROFILES_VIDEO_RING_TONE_SETUP_CAPTION,
    STR_PROFILES_SIM1_RING_TONE_SETUP_CAPTION,
    STR_PROFILES_SIM2_RING_TONE_SETUP_CAPTION,
#ifdef __MMI_PROFILE_EXTMELODY_SUPPORT__    
    STR_PROFILES_RING_TONE_SETUP_DRV_PHONE,
    STR_PROFILES_RING_TONE_SETUP_DRV_CARD,
    STR_PROFILES_RING_TONE_SETUP_LISTFULL,
    STR_PROFILES_RING_TONE_SETUP_DUPLICATED,
    STR_PROFILES_RING_TONE_SETUP_NAMETOOLONG,
    STR_PROFILES_RING_TONE_SETUP_FILETOOLARGE,
#endif
    STR_POWERON_TONE_SETUP_CAPTION,
    STR_POWEROFF_TONE_SETUP_CAPTION,
    STR_COVEROPEN_TONE_CAPTION,

    STR_COVERCLOSE_TONE_CAPTION,
    STR_MESSAGE_TONE_CAPTION,
    STR_SIM1_MESSAGE_TONE_CAPTION,
    STR_SIM2_MESSAGE_TONE_CAPTION,
    STR_KEYPAD_TONE_SILENT,
    STR_KEYPAD_TONE_CLICK,
    STR_KEYPAD_TONE_TONE,
#if defined(__MMI_HUMAN_VOICE_KEYPAD_TONE__)
    STR_KEYPAD_TONE_HUMAN_VOICE_1,
    STR_KEYPAD_TONE_HUMAN_VOICE_2,
    STR_KEYPAD_TONE_HUMAN_VOICE_3,
    STR_KEYPAD_TONE_HUMAN_VOICE_4,
    STR_KEYPAD_TONE_HUMAN_VOICE_5,
    STR_KEYPAD_TONE_HUMAN_VOICE_6,
#endif /* defined(__MMI_HUMAN_VOICE_KEYPAD_TONE__) */ 
#if defined(__MMI_CUST_KEYPAD_TONE__)
    STR_KEYPAD_TONE_CUST_1,
    STR_KEYPAD_TONE_CUST_2,
    STR_KEYPAD_TONE_CUST_3,
    STR_KEYPAD_TONE_CUST_4,
    STR_KEYPAD_TONE_CUST_5,
    STR_KEYPAD_TONE_CUST_6,
#endif /* defined(__MMI_CUST_KEYPAD_TONE__) */ 

    STR_KEYPAD_TONE_CAPTION,
#ifndef __MMI_ALM_CUSTOMIZE_TONE__    
    STR_TONE_SETUP_ALARM_TONE,
#endif
    STR_ALARM_TONE_CAPTION,
    STR_EXTRA_TONE_CAPTION,
    STR_EXTRA_TONE_ERROR,
    STR_EXTRA_TONE_CONNECT,
    STR_COMMON_VOLUME_LEVEL_CAPTION,

    STR_SILENT,
    STR_LOUD_SP_ON_MESSAGE,
    STR_LOUD_SP_OFF_MESSAGE,
    STR_ANSWERINGMODE_MESSAGE,
    STR_CALL_TIME_REMINDER_OFF_MESSAGE,
    STR_CALL_TIME_REMINDER_SINGLE_MESSAGE,
    STR_CALL_TIME_REMINDER_REPEAT_MESSAGE,
    STR_ALARM_SILENT_MESSAGE,
    STR_ALARM_CLICK_MESSAGE,
    STR_POWER_ON_TONE1_MESSAGE,
    STR_POWER_ON_TONE2_MESSAGE,
    STR_POWER_ON_TONE3_MESSAGE,
    STR_LCD_ON_MESSAGE,
    STR_LCD_OFF_MESSAGE,
    STR_NO_COLOR_MESSAGE,
    STR_COLOR1_MESSAGE,
    STR_COLOR2_MESSAGE,
    STR_COLOR3_MESSAGE,

    STR_PROFILES_TONE_SETUP_CAPTION,
    STR_EXTRA_TONE_CAMPON,
    STR_COLOR4_MESSAGE,
    STR_COLOR5_MESSAGE,
    STR_COLOR6_MESSAGE,
    STR_GENERAL_RESTORED_MESSAGE,
    STR_MEETING_RESTORED_MESSAGE,
    STR_OUTDOOR_RESTORED_MESSAGE,
    STR_INDOOR_RESTORED_MESSAGE,
    STR_COMMON_VOLUME_LEVEL_KEY_CAPTION,
    STR_COMMON_VOLUME_LEVEL_RING_CAPTION,
    STR_PROFILES_RING,
    STR_PROFILES_MIDI,
    STR_PROFILES_SILENT,
    STR_PROFILES_TONE,
    STR_DEFAULT_VOLUME_CAPTION,
    STR_KEY_TONE_VOLUME_CAPTION,

    STR_PROFILES_CANNOT_CHANGE_SILENT_MODE_SETTING,

#if defined(__MMI_INTELLIGENT_CALL_ALERT__)
    STR_PROFILES_INTELLIGENT_CALL_ALERT,
#endif 

    /* for customizing ring tone name */
    STR_PROFILES_RING_1,
    STR_PROFILES_RING_2,
    STR_PROFILES_RING_3,
    STR_PROFILES_RING_4,
    STR_PROFILES_RING_5,
    STR_PROFILES_RING_6,
    STR_PROFILES_RING_7,
    STR_PROFILES_RING_8,
    STR_PROFILES_RING_9,
    STR_PROFILES_RING_10,

    STR_PROFILES_MIDI_1,
    STR_PROFILES_MIDI_2,
    STR_PROFILES_MIDI_3,
    STR_PROFILES_MIDI_4,
    STR_PROFILES_MIDI_5,
    STR_PROFILES_MIDI_6,
    STR_PROFILES_MIDI_7,
    STR_PROFILES_MIDI_8,
    STR_PROFILES_MIDI_9,
    STR_PROFILES_MIDI_10,
    STR_PROFILES_MIDI_11,
    STR_PROFILES_MIDI_12,
    STR_PROFILES_MIDI_13,
    STR_PROFILES_MIDI_14,
    STR_PROFILES_MIDI_15,
    STR_PROFILES_MIDI_16,
    STR_PROFILES_MIDI_17,
    STR_PROFILES_MIDI_18,
    STR_PROFILES_MIDI_19,
    STR_PROFILES_MIDI_20,
    STR_PROFILES_MIDI_21,
    STR_PROFILES_MIDI_22,
    STR_PROFILES_MIDI_23,
    STR_PROFILES_MIDI_24,
    STR_PROFILES_MIDI_25,
    STR_PROFILES_MIDI_26,
    STR_PROFILES_MIDI_27,
    STR_PROFILES_MIDI_28,
    STR_PROFILES_MIDI_29,
    STR_PROFILES_MIDI_30,
    STR_PROFILES_MIDI_31,
    STR_PROFILES_MIDI_32,
    STR_PROFILES_MIDI_33,
    STR_PROFILES_MIDI_34,
    STR_PROFILES_MIDI_35,
    STR_PROFILES_MIDI_36,
    STR_PROFILES_MIDI_37,
    STR_PROFILES_MIDI_38,
    STR_PROFILES_MIDI_39,
    STR_PROFILES_MIDI_40,
    /* Leo add for DLT */
    STR_PROFILES_CURR_THEME
        /* Leo end */
} STR_PROFILES_LIST;

typedef enum
{
    SCR_PROFILES = PROFILES_BASE + 1,
    SCR_PROFILES_OPTIONS,
    SCR_PROFILES_ACTIVATE_OPTIONS,
    SCR_PROFILES_CUSTOMIZE,
    SCR_PROFILES_VOLUME_LEVEL,
    SCR_PROFILES_CALL_ALERT,
    SCR_PROFILES_INTELLIGENT_CALL_ALERT,
    SCR_PROFILES_RING_TYPE,
    SCR_PROFILES_CONNECT_NOTICE,
    SCR_PROFILES_COMMON_VOLUME_LEVEL,
    SCR_PROFILES_ANSWERING_MODE,
    SCR_PROFILES_LOUD_SPEAKER,
    SCR_PROFILES_LIGHT,
    SCR_PROFILES_LCD_BACKLIGHT,
    SCR_PROFILES_SET_TIMER,
    SCR_PROFILES_STATUS,
    SCR_PROFILES_CALLTIME_REMINDER,
    SCR_PROFILES_TONE_SETUP,
    SCR_PROFILES_RING_TONE_SETUP,
    SCR_PROFILES_CARD2_RING_TONE_SETUP,
    SCR_PROFILES_VIDEO_CALL_RING_TONE_SETUP,
    SCR_POWERON_TONE_SETUP,
    SCR_POWEROFF_TONE_SETUP,
    SCR_COVEROPEN_TONE_SETUP,
    SCR_COVERCLOSE_TONE_SETUP,
    SCR_MESSAGE_TONE_SETUP,
    SCR_CARD2_MESSAGE_TONE_SETUP,
    SCR_KEYPAD_TONE_SETUP,
    SCR_WARNING_TONE_SETUP,
    SCR_ALARM_TONE_SETUP,
    SCR_EXTRA_TONE_SETUP,
    SCR_ERROR_TONE_SETUP,
    SCR_CONNECT_TONE_SETUP,
    SCR_POPUP_CALLTIME_REMINDER,
    SCR_POPUP_PROFILES,
    SCR_POPUP_PROFILES_QEURY,
    SCR_KEY_TONE_VOLUME
} SCR_PROFILES_LIST;

typedef enum
{
    IMG_PROFILES_GENERAL = PROFILES_BASE + 1,
    IMG_PROFILES_MEETING,
    IMG_PROFILES_CAR,
    IMG_PROFILES_OUTDOOR,
    IMG_PROFILES_INDOOR,
    IMG_PROFILES_HEADSET,
    IMG_PROFILES_BT,
    IMG_PROFILES_TITLEE,
    IMG_PROFILES_NO_IMAGE,
    IMG_PROFILES_ACTIVATED
} IMG_PROFILES_LIST;

#endif /* _PIXCOM_PROFILESENUMS_H */ 

