/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 * JMMSResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file is intends for ¡K.
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/

#ifndef _JMMSRESDEF_H
#define _JMMSRESDEF_H
#include "MMI_features.h"       /* For compile time option */

#if (defined (JATAAYU_SUPPORT) && defined(MMS_SUPPORT))
#include "MMIDataType.h"        /* For BASE values */

/* String IDs */
typedef enum
{
    STR_ID_JMMS_PLAY_AUDIO = JATAAYU_MMS_BASE,
    /* add new string ID below this line */
    STR_ID_JMMS_PLAY_VIDEO,
    STR_ID_JMMS_IMAGE,
    STR_ID_JMMS_AUDIO,
    STR_ID_JMMS_VIDEO,
    STR_ID_JMMS_SLIDE,
    STR_ID_JMMS_NEXT_SLIDE,
    STR_ID_JMMS_PREVIOUS_SLIDE,
    STR_ID_JMMS_SLIDE_LIST,
    STR_ID_JMMS_FILEMGR,

    STR_ID_JMMS_INSERT,
    STR_ID_JMMS_ATTACHEMNT_VCARD,
    STR_ID_JMMS_ATTACHEMNT_VCALENDAR,
    STR_ID_JMMS_ATTACHMENT,
    STR_ID_JMMS_ATTACHEMNT_INSERT_VCARD_PHB,
    STR_ID_JMMS_ATTACHEMNT_INSERT_MY_VCARD,
#ifdef __MMI_TODOLIST__
    STR_ID_JMMS_ATTACHEMNT_INSERT_VCALENDAR_TODO_LIST,
#endif 
    STR_ID_JMMS_ATTACHEMNT_INSERT_VCARD_PHB_NAME_EMPTY,
    STR_ID_JMMS_ATTACHEMNT_INSERT_VCARD_PHB_INVALID_NAME,
    STR_ID_JMMS_ATTACHEMNT_INSERT_VCALENDAR_TODO_LIST_INVALID_NAME,
    STR_ID_JMMS_EDIT_CONTENT_INSERT_PHB_INVALID_NUMBER,
    STR_ID_JMMS_EDIT_CONTENT_REPLACE,
    STR_ID_JMMS_GOTO,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS,
    STR_ID_JMMS_EDIT_CONTENT_PREVIEW,
    STR_ID_JMMS_EDIT_CONTENT_INSERT_CONTACT,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS_SLIDE_TIME,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS_TEXT,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS_SMIL,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS_TEXT_SIZE,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS_TEXT_ITALIC,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS_TEXT_BOLD,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS_TEXT_COLOR,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS_SMIL_TEXT_TIME,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS_SMIL_IMAGE_TIME,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS_SMIL_AUDIO_TIME,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS_SMIL_VIDEO_TIME,
    STR_ID_JMMS_EDIT_CONTENT_SETTINGS_SMIL_BGCOLOR,
    STR_ID_JMMS_DURATION,
    STR_ID_JMMS_TEXT_SETTINGS_SIZE_SMALL,
    STR_ID_JMMS_TEXT_SETTINGS_SIZE_MEDIUM,
    STR_ID_JMMS_TEXT_SETTINGS_SIZE_LARGE,
    STR_ID_JMMS_TEXT_SETTINGS_COLOR1,
    STR_ID_JMMS_TEXT_SETTINGS_COLOR2,
    STR_ID_JMMS_TEXT_SETTINGS_COLOR3,
    STR_ID_JMMS_TEXT_SETTINGS_COLOR4,
    STR_ID_JMMS_TEXT_SETTINGS_COLOR5,
    STR_ID_JMMS_TEXT_SETTINGS_CUSTOM,
    STR_ID_JMMS_SMIL_SETTINGS_START_TIME,
    STR_ID_JMMS_EDIT_CONTENT_SLIDE_TIMINGS_ZERO_ERROR,
    STR_ID_JMMS_EDIT_CONTENT_MAX_SLIDE_REACHED,
    STR_ID_JMMS_TOO_MANY_SLIDES,
    STR_ID_JMMS_OUT_OF_MEMORY,
    STR_ID_JMMS_INVALID_PAGE_INDEX,
    STR_ID_JMMS_INVALID_MEDIA_ID,
    STR_ID_JMMS_TEXT_NOT_INSERTED,
    STR_ID_JMMS_IMAGE_NOT_INSERTED,
    STR_ID_JMMS_AUDIO_NOT_INSERTED,
    STR_ID_JMMS_VIDEO_NOT_INSERTED,
    STR_ID_JMMS_RESTRICTED_MODE_MEDIA,
    STR_ID_JMMS_WARNING_MODE_MEDIA,
    STR_ID_JMMS_MEDIA_REPLY_CHARGE_LIMIT,
    STR_ID_JMMS_MAX_MSG_REACHED,
#ifdef __DRM_SUPPORT__
    STR_ID_JMMS_ADD_MEDIA_AS_DRM,
#endif 
    STR_ID_JMMS_INVALID_MESSAGE_HANDLE,
    STR_ID_JMMS_AUDIO_EXISTS_NEW_SLIDE,
    STR_ID_JMMS_IMAGE_EXISTS_NEW_SLIDE,
    STR_ID_JMMS_VIDEO_EXISTS_NEW_SLIDE,
    STR_ID_JMMS_SAME_MEDIA_EXISTS_NEW_SLIDE,
    STR_ID_JMMS_INVALID_MEDIA_TYPE,
    STR_ID_JMMS_INVALID_MEDIA_INFO,
    STR_ID_JMMS_INVALID_POINTER,
    STR_ID_ERROR_CREATE_MEDIA_FILE,
    STR_ID_JMMS_MMS_ERR_RESTRICTED_CONTENT_CLASS,
    STR_ID_JMMS_EDIT_CONTENT_QUERY_RESTRICTED_MODE,
    STR_ID_JMMS_MMS_ERR_WARNING_CONTENT_CLASS,
    STR_ID_JMMS_MMS_REGION_TEXT,
    STR_ID_JMMS_EDIT_SLIDE_TIME,
    STR_ID_JMMS_EDIT_TEXT_COLOR,
    STR_ID_JMMS_EDIT_CONTENT_EDIT_MEDIA_TIME,
    STR_ID_JMMS_RC_INVALID_MEDIA,
    STR_ID_JMMS_RC_INVALID_SIZE,
    STR_ID_JMMS_RC_INVALID_TIME,
    STR_ID_JMMS_VIEW_PAUSE,
    STR_ID_JMMS_VIEW_RESUME,
    STR_ID_JMMS_VIEW_STOP,
    STR_ID_JMMS_VIEW_EXIT,
    STR_ID_JMMS_VIEW_OPTION_PLAY_MMS,
    STR_ID_JMMS_VIEW_OPTION_VIEW_ATTACHMENTS,
    STR_ID_JMMS_VIEW_OPTION_SAVE_AUDIO_AS,
    STR_ID_JMMS_VIEW_OPTION_SAVE_VIDEO_AS,
    STR_ID_JMMS_VIEW_OPTION_SAVE_IMAGE_AS,
    STR_ID_JMMS_VIEW_DEFAULT_REPLY_STRING,
    STR_ID_JMMS_VIEW_DEFAULT_FORWARD_STRING,
    STR_ID_JMMS_BLANK_MMS,
    STR_ID_JMMS_REPLAY,
    STR_ID_JMMS_SAVE_AS,
    STR_ID_JMMS_FILE_ALREADY_EXISTS,
    STR_ID_JMMS_PARSING_MMS,
    STR_ID_JMMS_DELETING_MMS,
    STR_ID_JMMS_PLEASE_WAIT,
    STR_ID_JMMS_NO_SLIDE_ONLY_ATTAHMENT,
    STR_ID_JMMS_FORWARD_LOCK_DRM,
    STR_ID_JMMS_FORWARD_LOCK_DRM_CANT_EDIT,
    STR_ID_JMMS_VIEW_REPLY_CHARGING,
    STR_ID_JMMS_VIEW_RC_TEXT_ONLY,
    STR_ID_JMMS_VIEW_RC_SIZE,
    STR_ID_JMMS_VIEW_RC_TIME,
    STR_ID_MMS_PARSING_FAIL,
    STR_ID_MMS_PARSING_SUCCESS,
    STR_ID_JMMS_WRITE_MESSAGE,
    STR_ID_JMMS_INBOX,
    STR_ID_JMMS_OUTBOX,
    STR_ID_JMMS_SENT,
    STR_ID_PROGRESS_SENDING,
    STR_ID_JMMS_DRAFTS,
    STR_ID_JMMS_TEMPLATES,
    STR_ID_JMMS_MMS_SETTINGS,
    STR_ID_JMMS_INBOX_OPTIONS_REPLY_ALL,
#ifdef __MMI_JATAAYU_MMS_REPLY_BY_SMS__
    STR_ID_JMMS_INBOX_OPTIONS_REPLY_BY_SMS,
#endif /* __MMI_JATAAYU_MMS_REPLY_BY_SMS__ */ 
    STR_ID_JMMS_OPTIONS_USE_DETAILS,
    STR_ID_JMMS_OPTIONS_PROPERTIES,
    STR_ID_JMMS_OPTIONS_FORWARD,
    STR_ID_JMMS_OPTIONS_USE_DETAILS_NUMBER,
    STR_ID_JMMS_OPTIONS_USE_DETAILS_EMAIL,
    STR_ID_JMMS_OPTIONS_USE_DETAILS_NUMBER_LIST,
    STR_ID_JMMS_OPTIONS_USE_DETAILS_EMAIL_LIST,
#ifdef __MMI_UNIFIED_MESSAGE__
    STR_ID_JMMS_USE_DETAILS_ADDRESSES_SAVE_TO_PHONEBOOK,
#else /* __MMI_UNIFIED_MESSAGE__ */ 
    STR_ID_JMMS_USE_DETAILS_ADDRESSES_ADD_TO_CONTACT,
    STR_ID_JMMS_USE_DETAILS_ADDRESSES_CALL,
#endif /* __MMI_UNIFIED_MESSAGE__ */ 
    STR_ID_JMMS_USE_DETAILS_NO_NUMBER,
    STR_ID_JMMS_USE_DETAILS_NO_EMAIL_ID,
    STR_ID_JMMS_OPTIONS_SENT_TO_OTHER,
    STR_ID_JMMS_OPTIONS_MOVE_TO_DRAFTS,
    STR_ID_JMMS_OUTBOX_OPTIONS_RESEND,
    STR_ID_JMMS_DRAFTS_OPTIONS_EDIT_MESSAGE,
    STR_ID_NO_SUBJECT,
    STR_ID_MESSAGE_SETTINGS_COMPOSE,
    STR_ID_MESSAGE_SETTINGS_SENDING,
    STR_ID_MESSAGE_SETTINGS_RETRIEVAL,
    STR_ID_MESSAGE_SETTINGS_EDIT_PROFILE,
    STR_ID_MESSAGE_SETTINGS_MEMORY_STATUS,
    STR_ID_SETTINGS_DEFAULT_SLIDE_TIMING,
#ifndef __MMI_UNIFIED_COMPOSER__
    STR_ID_SETTINGS_LAYOUT,
    STR_ID_SETTINGS_POTRAIT,
    STR_ID_SETTINGS_LANDSCAPE,
#ifdef __DRM_SUPPORT__
    STR_ID_SETTINGS_ADD_DRM,
#endif 
#endif /* __MMI_UNIFIED_COMPOSER__ */ 
    STR_ID_SETTINGS_CREATION_MODES,
    STR_ID_SETTINGS_RESTRICTED,
#ifndef __MMI_UNIFIED_COMPOSER__
    STR_ID_SETTINGS_WARNING,
#endif /* __MMI_UNIFIED_COMPOSER__ */
    STR_ID_SETTINGS_FREE,
    STR_ID_SETTINGS_MAX_NUM_PAGES,
    STR_ID_SETTINGS_BEST_PAGE_DURATION,
    STR_ID_SETTINGS_AUTO_SIGNATURE,
    STR_ID_AUTO_SIGNATURE_ERROR_TOO_MANY_SLIDES,
    STR_ID_AUTO_SIGNATURE_ERROR_SIZE_TOO_LARGE,
    STR_ID_SETTINGS_EDIT,
    STR_ID_SETTINGS_EDIT_CONTENT,
    STR_ID_SETTINGS_IMAGE_RESIZE,
    STR_ID_SETTINGS_160_X_120,
    STR_ID_SETTINGS_320_X_240,
    STR_ID_SETTINGS_640_X_480,
    STR_ID_JMMS_IMAGE_RESIZE_FAILED,
    STR_ID_JMMS_FAILED_RESOURCES_EXHAUSTED,
    STR_ID_JMMS_STORAGE_FULL,
    STR_ID_JMMS_IMAGE_RESIZE_LIMIT,
    STR_ID_SETTINGS_VALIDITY_PERIOD,
    STR_ID_JMMS_MAXIMUM,
    STR_ID_SETTINGS_1_HR,
    STR_ID_SETTINGS_12_HRS,
    STR_ID_SETTINGS_1_DAY,
    STR_ID_SETTINGS_1_WEEK,
    STR_ID_SETTINGS_READ_REPORT,
    STR_ID_SETTINGS_PRIORITY,
    STR_ID_SETTINGS_LOW,
    STR_ID_SETTINGS_HIGH,
    STR_ID_SETTINGS_DELIVERY_TIME,
    STR_ID_SETTINGS_IMMEDIATE,
    STR_ID_SETTINGS_24_HRS,
    STR_ID_SETTINGS_HIDE_SENDER,
    STR_ID_SETTINGS_HOME_NETWORK,
    STR_ID_SETTINGS_ROAMING,
    STR_ID_SETTINGS_FILTERS,
    STR_ID_SETTINGS_ON_REQUEST,
    STR_ID_SETTINGS_SEND,
    STR_ID_SETTINGS_NEVER_SEND,
    STR_ID_SETTINGS_ANNONYMOUS,
    STR_ID_SETTINGS_MAX_MSG_SIZE,
    STR_ID_SETTINGS_ADVERTISMENT,
    STR_ID_SETTINGS_ALLOW,
    STR_ID_SETTINGS_REJECT,
    STR_ID_SETTINGS_DEFFERED,
    STR_ID_SETTINGS_AS_HOME,
    STR_ID_SETTINGS_ON,
    STR_ID_SETTINGS_OFF,
    STR_ID_MAX_PAGES_LIMIT,
    STR_ID_SLIDE_TIME_ZERO_ERROR,
    STR_ID_AUTO_SIGN_ERROR,
    STR_ID_SETTINGS_REPLY_CHARGING,
    STR_ID_SETTINGS_REQUEST_TYPE,
    STR_ID_SETTINGS_REQUEST_TYPE_FULL_MMS,
    STR_ID_SETTINGS_REQUEST_TYPE_ONLY_TEXT,
    STR_ID_SETTINGS_REPLY_DEADLINE,
    STR_ID_SETTINGS_REPLY_CHARGE_SIZE,
    STR_ID_SETTINGS_REPLY_DEADLINE_ERROR,
    STR_ID_SETTINGS_REPLY_CHARGE_SIZE_ERROR,
    STR_ID_MAX_MSG_SIZE_LIMT,
    STR_ID_WRITE_MMS_TO,
    STR_ID_WRITE_MMS_CC,
    STR_ID_WRITE_MMS_BCC,
    STR_ID_WRITE_MMS_SUBJECT,
    STR_ID_WRITE_MMS_EDIT_CONTENT,
    STR_ID_WRITE_MMS_ADD_NUMBER,
    STR_ID_WRITE_MMS_ADD_EMAIL,
    STR_ID_WRITE_MMS_EDIT,
    STR_ID_WRITE_MMS_RECIPIENTS,
    STR_ID_WRITE_MMS_TO_BLANK_CAPTION,
    STR_ID_WRITE_MMS_CC_BLANK_CAPTION,
    STR_ID_WRITE_MMS_BCC_BLANK_CAPTION,
    STR_ID_JMMS_SEARCH,
    STR_ID_MAX_ADDRESS_LIMIT,
    STR_ID_MAX_ATTACHMENT_LIMIT,
    STR_ID_JMMS_MEDIA_RESOLUTION_EXCEEDED,
    STR_ID_JMMS_EMAIL_ADDRESS_ALREADY_EXIST,
    STR_ID_JMMS_ADDRESS_ALREADY_EXIST,
    STR_ID_JMMS_INPUT_FORMAT_ERROR,
    STR_ID_JMMS_ADD_BLANK_SLIDE,
    STR_ID_JMMS_ADD_DEFAULT_CHARACTERS,
    STR_ID_JMMS_BLANK_SLIDE_STRING,
    STR_ID_JMMS_WRITE_MMS_SEND_ONLY,
    STR_ID_JMMS_WRITE_MMS_SAVE_AND_SEND,
    STR_ID_JMMS_WRITE_MMS_SEND_OPTIONS,
    STR_ID_JMMS_WRITE_MMS_EXIT,
    STR_ID_JMMS_REPLACE_MMS,
    STR_ID_JMMS_SLIDES,
    STR_ID_JMMS_FILES,
    STR_ID_JMMS_RECIPIENTS,
    STR_ID_JMMS_PHB_LIMIT_EXCEEDED,
    STR_ID_JMMS_UNABLE_PARSE_PUSH,
    STR_ID_JMMS_ERROR_MMS_SENT,
    STR_ID_JMMS_SUCCESS_MMS_SENT,
    STR_ID_JMMS_UNABLE_PARSE_SENT_RESPONSE,
    STR_ID_JMMS_UNKNOWN_COMM_STATE,
    STR_ID_JMMS_COMM_ABORTED,
    STR_ID_JMMS_BYTES_KB_RECIEVED,
    STR_ID_JMMS_COMM_ABORTED_MMS_STORED,
    STR_ID_JMMS_COMM_ABORTED_AND_FAIL_STORE_MEMORY,
    STR_ID_JMMS_COMM_ABORTED_AND_FAIL_STORE_MEM_FULL,
    STR_ID_JMMS_COMM_ABORTED_AND_FAIL_STORE,
    STR_ID_JMMS_MEMORY_FULL,
    STR_ID_JMMS_FROM,
    STR_ID_JMMS_SUBJECT,
    STR_ID_JMMS_PRIORITY,
    STR_ID_JMMS_PLAY,
    STR_ID_JMMS_READ_NEW_MMS,
    STR_ID_JMMS_DOWNLOAD_NEW_MMS,
    STR_ID_JMMS_NEW_MMS,
    STR_ID_JMMS_CC,
    STR_ID_JMMS_DATE,
    STR_ID_JMMS_DELIVERY_STATUS_EXPIRED,
    STR_ID_JMMS_DELIVERY_STATUS_RETRIEVED,
    STR_ID_JMMS_DELIVERY_STATUS_REJECTED,
    STR_ID_JMMS_DELIVERY_STATUS_DEFFERED,
    STR_ID_JMMS_DELIVERY_STATUS_UNRECOGNISED,
    STR_ID_JMMS_DELIVERY_STATUS_INDETERMINATE,
    STR_ID_JMMS_DELIVERY_STATUS_FORWARDED,
    STR_ID_JMMS_DELIVERY_STATUS_UNREACHABLE,
    STR_ID_JMMS_TO,
    STR_ID_JMMS_STATUS,
    STR_ID_JMMS_DELIVERY_REPORT,
    STR_ID_JMMS_MMS_DOWNLOADING,
    STR_ID_JMMS_ERROR_MMS_DOWNLAOD,
    STR_ID_JMMS_READ_REPORT_READ,
    STR_ID_JMMS_READ_REPORT_DELETED,
    STR_ID_JMMS_READ_REPORT_DELETE_MSG,
    STR_ID_JMMS_UNKNOWN,
    STR_ID_JMMS_READ_REPORT_REQUEST,
    STR_ID_JMMS_READ_REPORT_MSG,
    STR_ID_JMMS_READ_REPORT_MSG_ID,
    STR_ID_JMMS_READ_REPORT_MSG_SUBJECT,
    STR_ID_JMMS_SUCCESS_READ_REPORT_SENT,
    STR_ID_JMMS_ERROR_READ_REPORT_SENT,
    STR_ID_JMMS_ERROR_MMS_SAVING,
    STR_ID_JMMS_ERROR_DELIVERY_SAVING,
    STR_ID_JMMS_ERROR_NEW_MMS_NOTIF_SAVING,
    STR_ID_JMMS_NEW_MMS_NOT_SAVED,
    STR_ID_JMMS_MMS_SENT_NOT_SAVE,
    STR_ID_JMMS_ERROR_MMS_SENT_AND_FAIL_STORE,
    STR_ID_JMMS_ERROR_MMS_SENT_AND_STORED,
    STR_ID_JMMS_ERROR_GET_MSG_LIST,
    STR_ID_JMMS_LOADING_MMS,
    STR_ID_JMMS_ERROR_MMS_DELETE,
    STR_ID_JMMS_DELETE_ALL_MMS_CONFIRM,
    STR_ID_JMMS_DELETE_ALL_UM_INBOX,
#ifdef __MMI_MMS_DELETE_ALL_READ_REPORT__
    STR_ID_JMMS_CONFIRM_DELETE_READ_ALL,
#endif /*__MMI_MMS_DELETE_ALL_READ_REPORT__*/
#ifdef __MMI_MMS_DELETE_ALL_DELIVERY_REPORT__
    STR_ID_JMMS_CONFIRM_DELETE_DELIVERY_ALL,
#endif /*__MMI_MMS_DELETE_ALL_DELIVERY_REPORT__*/
    STR_ID_JMMS_DELETE_ALL_UM_OUTBOX,
    STR_ID_JMMS_DELETE_ALL_UM_SENT,
    STR_ID_JMMS_DELETE_ALL_UM_DRAFTS,
    STR_ID_JMMS_FAILED_TO_DISPLAY_JSR_MMS,
    STR_ID_JMMS_EXPIRE_TIME,
    STR_ID_JMMS_HRS,
    STR_ID_JMMS_MINS,
    STR_ID_JMMS_SIZE,
    STR_ID_JMMS_KB,
    STR_ID_JMMS_MB,
    STR_ID_JMMS_GB,
    STR_ID_JMMS_BYTES,
    STR_ID_JMMS_WRITE_MMS_BYTES,
    STR_ID_JMMS_DAYS,
    STR_ID_JMMS_MSG_CLASS,
    STR_ID_JMMS_PERSONEL_MSG_CLASS,
    STR_ID_JMMS_INFORMATIONAL_MSG_CLASS,
    STR_ID_JMMS_AUTO_MSG_CLASS,
    STR_ID_JMMS_ERROR_READ_REPORT_SAVING,
    STR_ID_JMMS_MESSAGE_ID,
    STR_ID_JMMS_MSGS,
    STR_ID_JMMS_NOT_READY,
    STR_ID_JMMS_BCC,
    STR_ID_JMMS_ERROR_MMS_MOVE,
    STR_ID_JMMS_SUCCESS_MMS_SENT_ONLY,
    STR_ID_JMMS_SAVE_TO_DRAFTS,
    STR_ID_JMMS_TEMPLATES_TITLE_01,
    STR_ID_JMMS_TEMPLATES_TITLE_02,
    STR_ID_JMMS_TEMPLATES_TITLE_03,
    STR_ID_JMMS_TEMPLATES_TITLE_04,
    STR_ID_JMMS_TEMPLATES_TITLE_05,
    STR_ID_JMMS_TEMPLATES_TITLE_06,
    STR_ID_JMMS_TEMPLATES_TITLE_07,
    STR_ID_JMMS_TEMPLATES_TITLE_08,
    STR_ID_JMMS_TEMPLATES_TITLE_09,
    STR_ID_JMMS_TEMPLATES_TITLE_10,
    STR_ID_JMMS_MMS_DOWNLAOD_SUCCESS,
    STR_ID_JMMS_ERROR_ADDR_UNRESOLVED,
    STR_ID_JMMS_ERROR_NETWORK_PROBLEM,
    STR_ID_JMMS_ERROR_INVALID_MSG,
    STR_ID_JMMS_ERROR_REPLY_CHARGING,
    STR_ID_JMMS_ERROR_ADDR_HIDING,
    STR_ID_JMMS_ERROR_WRONG_CONTENT_TYPE,
    STR_ID_JMMS_ERROR_REDIRECTION,
    STR_ID_JMMS_ERROR_CLIENT,
    STR_ID_JMMS_ERROR_SERVER,
    STR_ID_JMMS_SAVE_SUCCESS,
    STR_ID_JMMS_SAVING_MMS,
    STR_ID_JMMS_SETTINGS_MESSAGE_STATUS_TOTAL,
    STR_ID_JMMS_SETTINGS_MESSAGE_STATUS_USAGE,
    STR_ID_JMMS_APPLICATION_ID,
    STR_ID_JMMS_REPLY_TO_APPLICATION_ID,
    STR_ID_JMMS_NEW_JAVA_MMS,
    STR_ID_JMMS_CONNECTING,
    STR_ID_JMMS_RETRY,
    STR_ID_JMMS_ERROR_SERVER_DENIED,
    STR_ID_JMMS_NOTF_IN_USE,
    STR_ID_JMMS_ERROR_MMS_MEMORY_FULL,
    STR_ID_JMMS_ERROR_MMS_SENT_AND_FAIL_STORE_MEMORY,
    STR_ID_JMMS_MMS_SENT_NOT_SAVE_MEMORY,
    STR_ID_JMMS_MEMORY_LIMIT_REACH,
    STR_ID_JMMS_ERROR_MMS_DOWNLAOD_STORE_FUL,
    STR_ID_JMMS_MEMORY_ERROR_DELIVERY_SAVING,
    STR_ID_JMMS_MEMORY_ERROR_READ_REPORT_SAVING,
    STR_ID_JMMS_NEW_MMS_MEMORY_NOT_SAVED,
    STR_ID_JMMS_MEMORY_ERROR_NEW_MMS_NOTIF_SAVING,
    STR_ID_JMMS_NEW_MMS_NOTIFICATION,
    STR_ID_JMMS_MEMORY_FULL_REACH,
    STR_ID_JMMS_ERROR_MMS_SENT_AND_FAIL_STORE_MEM_FULL,
    STR_ID_JMMS_MMS_SENT_NOT_SAVE_MEMORY_FULL,
    STR_ID_SETTINGS_FREE_SPACE,
    STR_ID_JMMS_ERROR_MMS_SENT_STORE_FUL,
    STR_ID_JMMS_STORAGE_ERROR_READ_REPORT_SENT,
    STR_ID_JMMS_SLIDE_TIME_EXCEED,
    STR_ID_JMMS_MEDIA_TIME_EXCEED,
    STR_ID_JMMS_ENTER_MEDIA_DURATION,
    STR_ID_JMMS_CORRUPTED_MEDIA_FILE,
    STR_ID_JMMS_PRESENTATION_NOT_SET,
    STR_ID_JMMS_SMIL_REGION_NOT_SET,
    STR_ID_JMMS_SMIL_INVALID_ROOTLAYOUT,
    STR_ID_JMMS_INVALID_RENDERING_RECT,
    STR_ID_JMMS_CORRUPTED_CONTENT,
    STR_ID_JMMS_STORE_INVALID_HANDLE,
    STR_ID_JMMS_INVALID_FOLDER_NAME,
    STR_ID_JMMS_FOLDER_ALREADY_EXIST,
    STR_ID_JMMS_ACTIVE_FOLDER_NOT_SET,
    STR_ID_JMMS_FOLDER_NOT_FOUND,
    STR_ID_JMMS_INVALID_MSG_INDEX,
    STR_ID_JMMS_FILE_CORRUPTED,
    STR_ID_JMMS_OPTIONS_MSG_SIZE_EXCEED,
    STR_ID_JMMS_OPTIONS_SAVE_OBJECTS,
    STR_ID_JMMS_SAVE_OBJECT_OPTIONS_SAVE_IMAGE_AS,
    STR_ID_JMMS_SAVE_OBJECT_OPTIONS_SAVE_AUDIO_AS,
    STR_ID_JMMS_SAVE_OBJECT_OPTIONS_SAVE_VIDEO_AS,
    STR_ID_JMMS_SAVE_OBJECT_OPTIONS_SAVE_ATTACHMENT_AS,
    STR_ID_JMMS_MODE_MAX_MSG_SIZE_REACHED_NEED_DELETE,
#ifdef __MMI_UNIFIED_MESSAGE__
    STR_ID_JMMS_LACK_RECIPENTS,
#endif 
    STR_ID_JMMS_MAX_INDIVIDUAL_MEDIA_SIZE,
    STR_ID_JMMS_FILE_SYSTEM_ERROR,
    STR_ID_JMMS_FILE_SYSTEM_FULL,
    STR_ID_JMMS_EMPTY_FILE,
    STR_ID_JMMS_LARGE_TEXT_MMS,
    STR_ID_JMMS_MMS_RECEIVED,
    STR_ID_JMMS_KILO_BYTES,
    STR_ID_JMMS_META_PRESENTATION_INFO,
#ifdef __MMI_MMS_DELETE_ALL_READ_REPORT__
    STR_ID_JMMS_INBOX_OPTIONS_DELETE_READ_ALL,
#endif /*__MMI_MMS_DELETE_ALL_READ_REPORT__*/
#ifdef __MMI_MMS_DELETE_ALL_DELIVERY_REPORT__
    STR_ID_JMMS_INBOX_OPTIONS_DELETE_DELIVERY_ALL,
#endif /*__MMI_MMS_DELETE_ALL_DELIVERY_REPORT__*/
    STR_ID_JMMS_MMS_MSG_EXPIRED,
    STR_ID_JMMS_MMS_SIZE_EXCEEDS,
#ifdef __MMI_JATAAYU_MMS_ADD_NUMBER_BY_GROUP__
    STR_ID_WRITE_MMS_ADD_NUMBER_BY_GROUP,
    STR_ID_WRITE_MMS_ADD_EMAIL_ADDRESS_BY_GROUP,
    STR_ID_JMMS_SOME_NUMBERS_ALREADY_EXIST,
    STR_ID_JMMS_ALL_NUMBERS_ALREADY_EXIST,
    STR_ID_JMMS_SOME_EMAILS_ALREADY_EXIST,
    STR_ID_JMMS_ALL_EMAILS_ALREADY_EXIST,
    STR_ID_JMMS_ALL_NUMBERS_COULD_NOT_BE_ADDED,
    STR_ID_JMMS_ALL_EMAILS_COULD_NOT_BE_ADDED,
#endif /* __MMI_JATAAYU_MMS_ADD_NUMBER_BY_GROUP__ */ 

    /* Put all your string ids above this point */
    STR_ID_JMMS_END
} STR_ID_JATAAYU_MMS_ENUM;

/* Screen IDs */
typedef enum
{
    SCR_ID_JMMS_ATTACHMENT_OPTIONS = JATAAYU_MMS_BASE,
    /* add new screen ID below this line */
    SCR_ID_JMMS_ATTACHMENT_INSERT,
    SCR_ID_JMMS_ATTACHMENT_DELETE,
    SCR_ID_JMMS_ATTACHMENT_VCARD,
    SCR_ID_JMMS_ATTACHMENT_VCALENDAR,
    SCR_ID_JMMS_EDIT_CONTENT_OPTIONS,
    SCR_ID_JMMS_EDIT_CONTENT_INSERT,
    SCR_ID_JMMS_EDIT_CONTENT_DELETE,
    SCR_ID_JMMS_EDIT_CONTENT_REPLACE,
    SCR_ID_JMMS_EDIT_CONTENT_GOTO,
    SCR_ID_JMMS_EDIT_CONTENT_SETTINGS,
    SCR_ID_JMMS_EDIT_CONTENT_SLIDE_TIME,
    SCR_ID_JMMS_EDIT_CONTENT_TEXT_SETTINGS,
    SCR_ID_JMMS_EDIT_CONTENT_SMIL_SETTINGS,
    SCR_ID_JMMS_CUSTOM_COLOR,
    SCR_ID_JMMS_SMIL_SETTINGS_TEXT_TIMINGS,
    SCR_ID_JMMS_SMIL_SETTINGS_IMAGE_TIMINGS,
    SCR_ID_JMMS_SMIL_SETTINGS_AUDIO_TIMINGS,
    SCR_ID_JMMS_SMIL_SETTINGS_VIDEO_TIMINGS,
    SCR_ID_JMMS_SMIL_SETTINGS_MEDIA_TIMINGS_DURATION,
    SCR_ID_JMMS_SMIL_SETTINGS_BG_COLOR,
    SCR_ID_JMMS_EDIT_CONTENT,
    SCR_ID_JMMS_PREVIEW_OPTIONS,
    SCR_ID_JMMS_VIEW_OPTIONS,
    SCR_ID_JMMS_VIEW_GOTO,
    SCR_ID_JMMS_VIEW_GOTO_SLIDE_LIST,
    SCR_ID_JMMS_DELETE_ATTACHMENT,
    SCR_ID_JMMS_VIEW,
    SCR_ID_JMMS_AUDIO_PLAY,
    SCR_ID_JMMS_VIDEO_PLAY,
    SCR_ID_JMMS_PREVIEW,
    SCR_ID_JMMS_VIEW_ATTACHMENT,
    SCR_ID_JMMS_ENTER_FILENAME,
    SCR_ID_JMMS_FILE_SAVE_OPTIONS,
    SCR_ID_JMMS_WAP_NOT_READY,

    /* Manish */
    SCR_ID_JMMS_MAIN_MENU,

    SCR_ID_JMMS_INBOX,  /* Inbox screens */
    SCR_ID_JMMS_INBOX_OPTIONS,
    SCR_ID_JMMS_INBOX_OPTIONS_USE_DETAILS,
    SCR_ID_JMMS_INBOX_OPTIONS_USE_DETAILS_ADDRESSES,
    SCR_ID_JMMS_INBOX_OPTIONS_USE_DETAILS_ADDRESSES_OPTIONS,

    SCR_ID_JMMS_OUTBOX, /* Outbox screeens */
    SCR_ID_JMMS_OUTBOX_OPTIONS,
    SCR_ID_JMMS_OUTBOX_OPTIONS_USE_DETAILS,
    SCR_ID_JMMS_OUTBOX_OPTIONS_USE_DETAILS_ADDRESSES,
    SCR_ID_JMMS_OUTBOX_OPTIONS_USE_DETAILS_ADDRESSES_OPTIONS,

    SCR_ID_JMMS_SENT,   /* Sent screeens */
    SCR_ID_JMMS_SENT_OPTIONS,
    SCR_ID_JMMS_SENT_OPTIONS_USE_DETAILS,
    SCR_ID_JMMS_SENT_OPTIONS_USE_DETAILS_ADDRESSES,
    SCR_ID_JMMS_SENT_OPTIONS_USE_DETAILS_ADDRESSES_OPTIONS,

    SCR_ID_JMMS_DRAFTS, /* Drafts screeens */
    SCR_ID_JMMS_DRAFTS_OPTIONS,
    SCR_ID_JMMS_DRAFTS_OPTIONS_USE_DETAILS,
    SCR_ID_JMMS_DRAFTS_OPTIONS_USE_DETAILS_ADDRESSES,
    SCR_ID_JMMS_DRAFTS_OPTIONS_USE_DETAILS_ADDRESSES_OPTIONS,

    SCR_ID_JMMS_TEMPLATES,          /* Templates screeens */
    SCR_ID_JMMS_TEMPLATES_OPTIONS,
    SCR_ID_JMMS_TEMPLATES_VIEW_OPTIONS,
    SCR_ID_JMMS_MESSAGE_SETTINGS,   /* mms settings */
    SCR_ID_JMMS_COMPOSE_SETTINGS,
    SCR_ID_JMMS_SENDING_SETTINGS,
    SCR_ID_JMMS_SENDING_REPLY_CHARGING_SETTINGS,
    SCR_ID_JMMS_RETRIEVAL_SETTINGS,
    SCR_ID_JMMS_RETRIEVAL_FILTERS_SETTINGS,
    SCR_ID_JMMS_WRITE_MMS,
    SCR_ID_JMMS_WRITE_MMS_HISTORY,
    SCR_ID_WRITE_MMS_ADDRESSES_OPTION,
    SCR_ID_JMMS_WRITE_MMS_ADD_NUMBER_EDITOR,
    SCR_ID_JMMS_WRITE_MMS_ADD_EMAIL_EDITOR,
    SCR_ID_JMMS_WRITE_MMS_ADD_SUBJECT_EDITOR,
    SCR_ID_JMMS_ADDRESS_LIST,
    SCR_ID_WRITE_MMS_DONE_OPTIONS,
    SCR_ID_JMMS_PROGRESS,
    SCR_ID_JMMS_TEMPLATES_CREATION_PROGRESS,
    SCR_ID_JMMS_SAVING_PROGRESS,
    SCR_ID_JMMS_PARSING_PROGRESS,
    SCR_ID_JMMS_PARSING_FAIL_SCREEN,
    SCR_ID_JMMS_PARSING_SUCCESS_SCREEN,
    SCR_ID_JMMS_NEW_MMS,
    SCR_ID_JMMS_NEW_MMS_IND,
    SCR_ID_JMMS_GET_MSGS_PROGRESS_SCREEN,
    SCR_ID_JMMS_GET_MSGS_ERROR_SCREEN,
    SCR_ID_JMMS_NOTIFICATION_PROPERTIES,
    SCR_ID_JMMS_RETRIEVED_MMS_PROPERTIES,
    /* PMT VIKAS START 20060325 */
    SCR_ID_JMMS_MMS_MESSAGE_STATUS,
    /* PMT VIKAS END 20060325 */
    SCR_ID_JMMS_MSG_SAVING_PROGRESS_SCREEN,
    SCR_ID_JMMS_SAVE_MSG_STATUS_SCREEN,
    SCR_ID_JMMS_POP_SCREEN,
    SCR_ID_JMMS_READ_REPORT_QUERY,
    SCR_ID_JMMS_SAVE_OBJECT,
    SCR_ID_JMMS_DELETING_PROGRESS,
    /* HIMANSHU 05122006 START */
    SCR_ID_JMMS_IMAGE_RESIZE_TRANSITION,
    /* HIMANSHU 05122006 END */
    /* add new screen ID above this line */
    SCR_ID_JMMS_END
} SCR_ID_JATAAYU_MMS_ENUM;

/* Image IDs */
typedef enum
{
    IMG_ID_JMMS_EDIT_CONTENT_ATTACHMENT = JATAAYU_MMS_BASE,
    /* add new image ID below this line */
    IMG_ID_JMMS_EDIT_CONTENT_AUDIO,
    // sandeep for unused resource removal
    //  IMG_ID_JMMS_EDIT_CONTENT_VIDEO,
    /* PMT VIKAS START 20060502 */
    // sandeep for unused resource removal
    //  IMG_ID_JMMS_SMIL_EDITOR_FRAME,
    IMG_ID_JMMS_SMIL_EDITOR_PIC_ICON,
    IMG_ID_JMMS_SMIL_EDITOR_VIDEO_ICON,
    //PMT VIKAS END 20060502
    ///manish
    //      IMG_MESSAGE_JMMS_MENUENTRY, 
    IMG_ID_JMMS_WRITE_MESSAGE,
    IMG_ID_JMMS_INBOX,
    IMG_ID_JMMS_OUTBOX,
    IMG_ID_JMMS_SENT,
    IMG_ID_JMMS_DRAFTS,
    IMG_ID_JMMS_TEMPLATES,
    IMG_ID_JMMS_SETTINGS,
    IMG_ID_WRITE_MMS_TO,
    IMG_ID_WRITE_MMS_CC,
    IMG_ID_WRITE_MMS_BCC,
    IMG_ID_WRITE_MMS_SUBJECT,
    IMG_ID_WRITE_MMS_EDIT_CONTENT,
    IMG_ID_WRITE_MMS_ATTACHMENT,
#ifdef __MMI_UNIFIED_MESSAGE__
    IMG_ID_JMMS_MMS_WITH_ATTACHMENT,
    IMG_ID_JMMS_MMS_WITHOUT_ATTACHMENT,
#endif /* __MMI_UNIFIED_MESSAGE__ */ 
    IMG_ID_JMMS_NEW_MMS_READ,
    IMG_ID_JMMS_NEW_MMS_UNREAD,
    IMG_ID_JMMS_DELIVERY_READ,
    IMG_ID_JMMS_DELIVERY_UNREAD,
    IMG_ID_JMMS_READ_REPORT_READ,
    IMG_ID_JMMS_READ_REPORT_UNREAD,
    IMG_ID_JMMS_MMS_NOTIFICATION,
    IMG_ID_JMMS_JAVA_MMS,
    IMG_ID_JMMS_SENT_MMS,
    IMG_ID_JMMS_TEMPLATE_MMS,
    IMG_ID_JMMS_PROGRESS,
    IMG_ID_JMMS_PROGRESS_FULL,
    IMG_ID_JMMS_NEW_MESSAGE_NOTIFICATION_MSG,
    /* /Templates ImageIds */
    IMG_ID_JMMS_TEMPLATES_01,
    IMG_ID_JMMS_TEMPLATES_02,
    IMG_ID_JMMS_TEMPLATES_03,
    IMG_ID_JMMS_TEMPLATES_04,
    IMG_ID_JMMS_TEMPLATES_05,
    IMG_ID_JMMS_TEMPLATES_06,
    IMG_ID_JMMS_TEMPLATES_07,
    IMG_ID_JMMS_TEMPLATES_08,
    IMG_ID_JMMS_TEMPLATES_09,
    IMG_ID_JMMS_TEMPLATES_10,
    IMG_ID_JMMS_ATTACHMENT_LIST,
    IMG_ID_JMMS_USE_DETAILS_IMAGE,
    /* add new image ID above this line */
    IMG_ID_JMMS_END
} IMG_ID_JATAAYU_MMS_ENUM;

/* Main Menu items */
typedef enum
{
    JMMS_WRITE_MESSAGE,
    JMMS_INBOX,
    JMMS_OUTBOX,
    JMMS_SENT,
    JMMS_DRAFTS,
    JMMS_TEMPLATES,
    JMMS_SETTINGS,
    NUM_JMMS_MAIN_MENU_ITEMS
} JMMS_MAIN_MENU_ENUM;

#endif /* (defined (JATAAYU_SUPPORT) && defined(MMS_SUPPORT)) */ 
#endif /* _JMMSRESDEF_H */ 

