/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *	mmiapi_sap.h
 *
 * Project:
 * --------
 *	MAUI
 *
 * Description:
 * ------------
 *	MMI related message identity definition
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 * 				HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/
 	MSG_ID_MMIAPI_ACTION_REGISTER_IND = MSG_ID_MMIAPI_CODE_BEGIN,
	MSG_ID_MMIAPI_ACTION_NOTIFY_IND,
	MSG_ID_MMIAPI_UNREAD_PUSH_ICON_IND,
	MSG_ID_MMIAPI_MMS_IND,
	MSG_ID_MMIAPI_DEVICE_GET_CTRL_REQ,
	MSG_ID_MMIAPI_DEVICE_GET_CTRL_RSP,
	MSG_ID_MMIAPI_DEVICE_PLAY_REQ,
	MSG_ID_MMIAPI_DEVICE_PLAY_RSP,

	// Remote procedure call
	MSG_ID_MMIAPI_REMOTE_PROC_CALL_REQ,

	// Short message Service
	MSG_ID_MMIAPI_SMS_SEND_REQ,
	MSG_ID_MMIAPI_SMS_SEND_RSP,

	MSG_ID_MMIAPI_SMS_IND,
	
	MSG_ID_MMIAPI_SMS_REGISTER_PORT_REQ,
	MSG_ID_MMIAPI_SMS_REGISTER_PORT_RSP,

	MSG_ID_MMIAPI_SMS_CHECK_INCOMING_MSG_REQ,
	MSG_ID_MMIAPI_SMS_CHECK_INCOMING_MSG_RSP,

	MSG_ID_MMIAPI_SMS_GET_INCOMING_MSG_TIMESTAMP_REQ,
	MSG_ID_MMIAPI_SMS_GET_INCOMING_MSG_TIMESTAMP_RSP,

	MSG_ID_MMIAPI_SMS_GET_INCOMING_MSG_ADDRESS_REQ,
	MSG_ID_MMIAPI_SMS_GET_INCOMING_MSG_ADDRESS_RSP,

	MSG_ID_MMIAPI_SMS_GET_INCOMING_MSG_REQ,
	MSG_ID_MMIAPI_SMS_GET_INCOMING_MSG_RSP,
	
	MSG_ID_MMIAPI_SMS_GET_HOST_ADDRESS_REQ,
	MSG_ID_MMIAPI_SMS_GET_HOST_ADDRESS_RSP,

	// UI service
	MSG_ID_MMIAPI_UI_ENTER_FULLSCREEN_EDITOR_REQ,
	MSG_ID_MMIAPI_UI_ENTER_FULLSCREEN_EDITOR_RSP,
	MSG_ID_MMIAPI_UI_ENTER_IDLE_SCREEN_REQ,
	MSG_ID_MMIAPI_UI_ENTER_IDLE_SCREEN_RSP,
	MSG_ID_MMI_READY_TO_IDLE_SCREEN_IND,

	MSG_ID_MMIAPI_BACKLIGHT_CONTROL_REQ,
	MSG_ID_MMIAPI_BACKLIGHT_CONTROL_RSP,

	MSG_ID_MMIAPI_LED_CONTROL_REQ,
	MSG_ID_MMIAPI_LED_CONTROL_RSP,

	MSG_ID_MMI_SHOW_ASM_DIALOG_REQ,
	MSG_ID_MDI_MOTION_DATA_STATE_RSP,
	MSG_ID_MMI_VDOPLY_RTSP_URL_REQ,

	MSG_ID_MMI_UM_READY_IND,
	MSG_ID_MMI_UM_GET_MSG_NUM_REQ,
	MSG_ID_MMI_UM_GET_MSG_NUM_RSP,
	MSG_ID_MMI_UM_GET_LIST_REQ,
	MSG_ID_MMI_UM_GET_LIST_RSP,
	MSG_ID_MMI_UM_GET_MSG_INFO_REQ,
	MSG_ID_MMI_UM_GET_MSG_INFO_RSP,
	MSG_ID_MMI_UM_DELETE_FOLDER_REQ,
	MSG_ID_MMI_UM_DELETE_FOLDER_RSP,
	MSG_ID_MMI_UM_NEW_MSG_IND,
	MSG_ID_MMI_UM_DELETE_ALL_IND,
	MSG_ID_MMI_UM_DELETE_ALL_RES,
	MSG_ID_MMI_UM_HIGHLIGHT_MSG_IND,
	MSG_ID_MMI_UM_HIGHLIGHT_DECIDED_BY_UM_IND,
	MSG_ID_MMI_UM_REFRESH_IND,
	MSG_ID_MMI_UM_CANCEL_NEW_MSG_IND,
	MSG_ID_MMI_DA_GET_FILE_IND,
	MSG_ID_MMI_DA_GET_FILE_RSP,
    MSG_ID_MMI_DA_DISPATCH_FILE_REQ,
    MSG_ID_MMI_DA_DISPATCH_FILE_RSP,
    MSG_ID_MMI_DA_DOWNLOAD_INFO_IND,
    MSG_ID_MMI_DA_WAP_NOTIFY_IND,
	MSG_ID_MMI_JATAAYU_QUEUE_RECV_IND,    

	MSG_ID_MDI_SWFLASH_DL_SOCKET_IND,
	MSG_ID_MDI_SWFLASH_PL_AUDIO_IND,

    MSG_ID_MMI_GDD_IMG_CODEC_EVENT_IND,
    MSG_ID_MMI_GDC_IMG_CODEC_CALLBACK_IND,

	MSG_ID_MMI_MAKE_CALL_REQ_IND,

    MSG_ID_MMI_CCA_APP_CONFIGURE_IND,
    MSG_ID_MMI_CCA_APP_CONFIGURE_RSP,
    MSG_ID_MMI_CCA_SOURCE_NEW_DOC_IND,
    MSG_ID_MMI_CCA_SOURCE_NEW_DOC_RSP,
    MSG_ID_MMI_CCA_SOURCE_UI_INVALID_SETTING_IND,
    MSG_ID_MMI_CCA_SOURCE_UI_NEW_SETTING_IND,
    MSG_ID_MMI_CCA_SOURCE_UI_NEW_SETTING_RSP,
    MSG_ID_MMI_CCA_SOURCE_UI_AUTH_IND,
    MSG_ID_MMI_CCA_SOURCE_UI_AUTH_RSP,
    MSG_ID_MMI_CCA_NEW_DOC_CONTINUE_IND,
    MSG_ID_MMI_CCA_GET_PROF_IND,
    MSG_ID_MMI_CCA_GET_PROF_RSP,
    MSG_ID_MMI_CCA_APP_GET_PROF_IND,
    MSG_ID_MMI_CCA_APP_GET_PROF_RSP,
    MSG_ID_MMI_CCA_UPDATE_PROF_IND,
    MSG_ID_MMI_CCA_UPDATE_PROF_RSP,
    MSG_ID_MMI_CCA_APP_UPDATE_PROF_IND,
    MSG_ID_MMI_CCA_APP_UPDATE_PROF_RSP,

    /* PictBridge */
    MSG_ID_MMI_PICT_BRIDGE_PENDING_EVENT,

    /* Battery info query */
    MSG_ID_MMIAPI_GET_BATTERY_LEVEL_REQ,
    MSG_ID_MMIAPI_GET_BATTERY_LEVEL_RSP,

    MSG_ID_MMIAPI_BATTERY_LEVEL_NOTIFY_START_REQ,
    MSG_ID_MMIAPI_BATTERY_LEVEL_NOTIFY_START_RSP,

    MSG_ID_MMIAPI_BATTERY_LEVEL_NOTIFY_IND,

    MSG_ID_MMIAPI_BATTERY_LEVEL_NOTIFY_STOP_REQ,
    MSG_ID_MMIAPI_BATTERY_LEVEL_NOTIFY_STOP_RSP,
    
    MSG_ID_MMI_PS_DTCNT_LIST_IND,
    MSG_ID_MMI_PS_DTCNT_LIST_RSP,

    /* 3G324M */
    MSG_ID_MDI_VT_LOOPBACK_ACTIVATE_REQ,
	MSG_ID_MDI_VT_LOOPBACK_DEACTIVATE_REQ,

	MSG_ID_MMIAPI_CODE_END,


