/*=====================================================================

 Copyright (c) 2001-2002 MobileSoft Corporation

    All Rights Reserved.

    $Logfile: cmsmaptable.h

    $Revision:

    $vision:       1.00

    $Date:         07/21/2002

    $Author:       hulf

	$Declare: 
	This document contains information proprietary to MobileSoft  
 Technology (Nanjing),  Corp.    Transmittal, receipt, or possession 
 of this document does not express, license, or imply any rights to 
 use, sell, design, or manufacture from this information. No reproduction, 
 publication, or disclosure of this information, in whole or in part, 
 shall be made without prior written authorization from an officer of 
 MobileSoft Technology (NanJing), Corp.

 

Abstract:

 

Modified By:

 

Environment: 

 

Revision History:

 

=====================================================================*/

#ifndef CMSMAPTABLE_H
#define CMSMAPTABLE_H


#include "Cms_MMSSmil.h"

/********************* Constans *************************/

#define b_MaxGIlength 16

/********************* Structures ***********************/

typedef CMS_MMS_U8 b_GI[b_MaxGIlength];

typedef struct b_GIMapping
  {
     b_GI		b_htmlGI;
	 CMS_MMS_S8		doctype;
	 //CENT_FILL_FIELD3
     CMS_MMS_U32		b_ThotType;
  }b_GIMapping;

typedef struct b_AttributeMapping
{
     CMS_MMS_U8 				 b_Attribute[25];
	 //CENT_FILL_FIELD3
     CMS_MMS_U32		         b_doctype;
     CMS_MMS_U32			  	 b_ThotAttribute;
     
}b_AttributeMapping;

/******************** Element Index Table ******************/

static CMS_MMS_U8 b_HTMLGIMappingInt[]=
{
	    0,//a
		10,//b
		16,//c
		19,//d
		21,//e
		21,//f
		22,//g
		23,//h
		33,//i
		36,//j
		36,//k
		36,//l
		39,//m
		41,//n
		42,//o
		44,//p
		52,//q
		52,//r
		57,//s
		66,//t
		76,//u
		76,//v
		78,//w
		79,//x
		79,//y
		79 //z
};

/************************* Element Mapping Table ******************/

static b_GIMapping    b_HTMLGIMappingTable[] =
{
    {"A",				DOCUMENT_TYPE_WML,	WML_EL_ANCHOR},				//0
    {"A",				DOCUMENT_TYPE_SMIL,	SMIL_EL_ANCHOR},			
//	{"ABBR",			DOCUMENT_TYPE_WML,	WML_EL_ABBR},
	{"ACCESS",			DOCUMENT_TYPE_WML,	WML_EL_ACCESS},				
//	{"ACRONYM",			DOCUMENT_TYPE_WML,	WML_EL_ACRONYM},
//	{"ADDRESS",			DOCUMENT_TYPE_WML,	WML_EL_ADDRESS},
    {"ANCHOR",			DOCUMENT_TYPE_WML,	WML_EL_ANCHOR},				
    {"ANCHOR",			DOCUMENT_TYPE_SMIL,	SMIL_EL_ANCHOR},			
	{"ANIMATE",			DOCUMENT_TYPE_SMIL,	SMIL_EL_ANIMATE},			
	{"ANIMATECOLOR",	DOCUMENT_TYPE_SMIL,	SMIL_EL_ANIMATECOLOR},		
	{"ANIMATEMOTION",	DOCUMENT_TYPE_SMIL,	SMIL_EL_ANIMATEMOTION},		
	{"ANIMATION",		DOCUMENT_TYPE_SMIL,	SMIL_EL_ANIMATION},			
//	{"AREA",			DOCUMENT_TYPE_WML,	WML_EL_AREA},
	{"AUDIO",			DOCUMENT_TYPE_SMIL,	SMIL_EL_AUDIO},				
	{"B",				DOCUMENT_TYPE_WML,	WML_EL_B},					//10
//	{"BASE",			DOCUMENT_TYPE_WML,	WML_EL_BASE},
	{"BIG",				DOCUMENT_TYPE_WML,	WML_EL_BIG},
//  {"BLOCKQUOTE",		DOCUMENT_TYPE_WML,	WML_EL_BLOKEQUOTE},
	{"BODY",			DOCUMENT_TYPE_WML,	WML_EL_BODY},				
	{"BODY",			DOCUMENT_TYPE_SMIL,	SMIL_EL_BODY},				
    {"BR/",				DOCUMENT_TYPE_WML,	WML_EL_BR},					
	{"BRUSH",			DOCUMENT_TYPE_SMIL,	SMIL_EL_BRUSH},				
//  {"CAPTION",			DOCUMENT_TYPE_WML,	WML_EL_CAPTION},
    {"CARD",			DOCUMENT_TYPE_WML,	WML_EL_CARD},				//16
//  {"CITE",			DOCUMENT_TYPE_WML,	WML_EL_CITE},
//  {"CODE",			DOCUMENT_TYPE_WML,	WML_EL_CODE},
	{"CUSTOMATTRIBUTES",DOCUMENT_TYPE_SMIL,	SMIL_EL_CUSTOMATTRIBUTES},	
	{"CUSTOMTEST",		DOCUMENT_TYPE_SMIL,	SMIL_EL_CUSTOMTEST},		
//  {"DD",				DOCUMENT_TYPE_WML,	WML_EL_DD},
//  {"DFN",				DOCUMENT_TYPE_WML,	WML_EL_DFN},
    {"DIV",				DOCUMENT_TYPE_WML,	WML_EL_DIV},				//19
//  {"DL",				DOCUMENT_TYPE_WML,	WML_EL_DEFINITION_LIST},
    {"DO",				DOCUMENT_TYPE_WML,	WML_EL_DO},					
//  {"DT",				DOCUMENT_TYPE_WML,	WML_EL_TERM},
//  {"EM",				DOCUMENT_TYPE_WML,	WML_EL_EMPHASIS},
	{"EXCL",			DOCUMENT_TYPE_SMIL,	SMIL_EL_EXCL},				//21
    {"GO",				DOCUMENT_TYPE_WML,	WML_EL_GO},					//22
//  {"GETVAR",			DOCUMENT_TYPE_WML,	WML_EL_GETVAR},				
	{"H1",				DOCUMENT_TYPE_WML,	WML_EL_H1},					//23
	{"H2",				DOCUMENT_TYPE_WML,	WML_EL_H2},					
	{"H3",				DOCUMENT_TYPE_WML,	WML_EL_H3},					
	{"H4",				DOCUMENT_TYPE_WML,	WML_EL_H4},					
	{"H5",				DOCUMENT_TYPE_WML,	WML_EL_H5},					
	{"H6",				DOCUMENT_TYPE_WML,	WML_EL_H6},					
    {"HEAD",			DOCUMENT_TYPE_WML,	WML_EL_HEAD},				
    {"HEAD",			DOCUMENT_TYPE_SMIL,	SMIL_EL_HEAD},				
	{"HEAD/",			DOCUMENT_TYPE_SMIL,	SMIL_EL_HEAD},	//2003-07-31 longqiangl			
    {"HR",				DOCUMENT_TYPE_WML,	WML_EL_HORIZONTAL_RULE},	
	{"HTML",			DOCUMENT_TYPE_WML,	WML_EL_HTML},				
//  {"I",				DOCUMENT_TYPE_WML,	WML_EL_Italic_text},
    {"IMG",				DOCUMENT_TYPE_WML,	WML_EL_IMG},				//33
    {"IMG",				DOCUMENT_TYPE_SMIL,	SMIL_EL_IMG},				
    {"INPUT",			DOCUMENT_TYPE_WML,	WML_EL_INPUT},				
//  {"KBD",				DOCUMENT_TYPE_WML,	WML_EL_KBD},
	{"LABEL",			DOCUMENT_TYPE_WML,	WML_EL_LABEL},				//36
	{"LAYOUT",			DOCUMENT_TYPE_SMIL,	SMIL_EL_LAYOUT},			
    {"LI",				DOCUMENT_TYPE_WML,	WML_EL_LIST_ITEM},			
//  {"LINK",			DOCUMENT_TYPE_WML,	WML_EL_LINK},
	{"META",			DOCUMENT_TYPE_WML,	WML_EL_META},				//39
	{"META",			DOCUMENT_TYPE_SMIL,	SMIL_EL_META},				
	{"NOOP/",			DOCUMENT_TYPE_WML,	WML_EL_NOOP},				//41
//  {"OBJECT",			DOCUMENT_TYPE_WML,	WML_EL_Object},
//  {"OL",				DOCUMENT_TYPE_WML,	WML_EL_NUMBERED_LIST},
	{"ONEVENT",			DOCUMENT_TYPE_WML,	WML_EL_ONEVENT},			//42
//  {"OPTGROUP",		DOCUMENT_TYPE_WML,	WML_EL_OPTGROUP},
	{"OPTION",			DOCUMENT_TYPE_WML,	WML_EL_OPTION},				
    {"P",				DOCUMENT_TYPE_WML,	WML_EL_PARAGRAPH},			//44
	{"PAR",				DOCUMENT_TYPE_SMIL,	SMIL_EL_PAR},				
	{"PARAM",			DOCUMENT_TYPE_SMIL,	SMIL_EL_PARAM},				
    {"POSTFIELD",		DOCUMENT_TYPE_WML,	WML_EL_POSTFIELD},			
	{"PRE",				DOCUMENT_TYPE_WML,	WML_EL_PREFORMATTED},		
	{"PREFETCH",		DOCUMENT_TYPE_SMIL,	SMIL_EL_PREFETCH},			
    {"PREV/",			DOCUMENT_TYPE_WML,	WML_EL_PREV},				
	{"PRIORITYCLASS",	DOCUMENT_TYPE_SMIL,	SMIL_EL_PRIORITYCLASS},		
//  {"Q",				DOCUMENT_TYPE_WML,	WML_EL_Quotation},
	{"REF",				DOCUMENT_TYPE_SMIL,	SMIL_EL_REF},				//52
	{"REFRESH",			DOCUMENT_TYPE_WML,	WML_EL_REFRESH},			
	{"REGION",			DOCUMENT_TYPE_SMIL,	SMIL_EL_REGION},			
	{"REGPOINT",		DOCUMENT_TYPE_SMIL,	SMIL_EL_REGPOINT},	
	{"ROOT-LAYOUT", DOCUMENT_TYPE_SMIL, SMIL_EL_ROOT_LAYOUT}, // 2003-08-22 
	{"ROOT-LAYOUT/",	DOCUMENT_TYPE_SMIL,	SMIL_EL_ROOT_LAYOUT},		
//  {"SAMP",			DOCUMENT_TYPE_WML,	WML_EL_Sample},
    {"SELECT",			DOCUMENT_TYPE_WML,	WML_EL_SELECT},				//57
	{"SEQ",				DOCUMENT_TYPE_SMIL,	SMIL_EL_SEQ},				
	{"SET",				DOCUMENT_TYPE_SMIL,	SMIL_EL_SET},				
    {"SETVAR",			DOCUMENT_TYPE_WML,	WML_EL_SETVAR},				
	{"SMALL",			DOCUMENT_TYPE_WML,	WML_EL_SMALL},
	{"SMIL",			DOCUMENT_TYPE_SMIL,	SMIL_EL_SMIL},				
	{"SPAN",			DOCUMENT_TYPE_WML,	WML_EL_SPAN},				
//  {"STRONG",			DOCUMENT_TYPE_WML,	WML_EL_Strong},
    {"STYLE",			DOCUMENT_TYPE_WML,	WML_EL_STYLE},				
	{"SWITCH",			DOCUMENT_TYPE_SMIL,	SMIL_EL_SWITCH},			
    {"TABLE",			DOCUMENT_TYPE_WML,	WML_EL_TABLE},				//66
	{"TD",				DOCUMENT_TYPE_WML,	WML_EL_DATA_CELL},			
//  {"TEXTAREA",		DOCUMENT_TYPE_WML,	WML_EL_Text_Area},
	{"TEXT",			DOCUMENT_TYPE_SMIL,	SMIL_EL_TEXT},				
	{"TEXTSTREAM",		DOCUMENT_TYPE_SMIL,	SMIL_EL_TEXTSTREAM},	
//  {"TH",				DOCUMENT_TYPE_WML,	WML_EL_Heading_cell},
    {"TIMER",			DOCUMENT_TYPE_WML,	WML_EL_TIMER},				
    {"TITLE",			DOCUMENT_TYPE_WML,	WML_EL_TITLE},				
	{"TOPLAYOUT",		DOCUMENT_TYPE_SMIL,	SMIL_EL_TOPLAYOUT},			
    {"TR",				DOCUMENT_TYPE_WML,	WML_EL_TABLE_ROW},			
	{"TRANSITION",		DOCUMENT_TYPE_SMIL,	SMIL_EL_TRANSITION},		
	{"TRANSITIONFILTER",DOCUMENT_TYPE_SMIL,	SMIL_EL_TRANSITIONFILTER},	
//  {"U",				DOCUMENT_TYPE_WML,	WML_EL_UNDERLINED_TEXT},
//  {"UL",				DOCUMENT_TYPE_WML,	WML_EL_UNNUMBERED_LIST},
	{"VAR",				DOCUMENT_TYPE_WML,	WML_EL_VARIABLE},			//76
	{"VIDEO",			DOCUMENT_TYPE_SMIL,	SMIL_EL_VIDEO},				
//  {"WIDGET",			DOCUMENT_TYPE_WML,	WML_EL_WIDGET},
	{"WML",				DOCUMENT_TYPE_WML,	WML_EL_WML},				//78
    {"",  0}													//79
};


/************************** Attribute Index Table ******************/

static CMS_MMS_U8 b_HTMLAttributeMappingInt[]=
{
		0,//a
		12,//b
		20,//c
		33,//d
		39,//e
		44,//f
		51,//g
		51,//h
		57,//i
		59,//j
		59,//k
		61,//l
		65,//m
		72,//n
		75,//o
		81,//p
		84,//q
		84,//r
		95,//s
		124,//t
		137,//u
		139,//v
		144,//w
		145,//x
		147,//y
		148 //z
};


/*********************** Attribute Mapping Table *******************/

static b_AttributeMapping b_HTMLAttributeMappingTable[] =
{
	{"ABSTRACT",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_abstract},		//0
	{"ACCELERATE",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_accelerate},
	{"ACCESSKEY",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_accesskey},
	{"ACCUMULATE",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_accumulate},
	{"ACTUATE",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_actuate},
	{"ADDITIVE",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_additive},
	{"ALT",				DOCUMENT_TYPE_WML,	WML_ATTR_ALT},
	{"ALT",				DOCUMENT_TYPE_SMIL,	SMIL_ATTR_alt},
	{"ATTRIBUTENAME",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_attributeName},
	{"ATTRIBUTETYPE",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_attributeType},
	{"AUTHOR",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_author},
	{"AUTOREVERSE",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_autoReverse},
	{"BACKGROUNDCOLOR",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_backgroundColor},	//12
	{"BACKGROUND-COLOR",DOCUMENT_TYPE_SMIL,	SMIL_ATTR_background_color},
	{"BANDWIDTH",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_bandwidth},
	{"BEGIN",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_begin},
	{"BORDERCOLOR",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_borderColor},
	{"BORDERWIDTH",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_borderWidth},
	{"BOTTOM",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_bottom},
	{"BY",				DOCUMENT_TYPE_SMIL,	SMIL_ATTR_by},
	{"CALCMODE",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_calcMode},		//20
	{"CLASS",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_class},
	{"CLIPBEGIN",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_clipBegin},
	{"CLIP-BEGIN",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_clip_begin},
	{"CLIPEND",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_clipEnd},
	{"CLIP-END",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_clip_end},
	{"CLOSE",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_close},
	{"COLOR",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_color},
	{"CONTENT",			DOCUMENT_TYPE_WML,	WML_ATTR_meta_content},
	{"CONTENT",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_content},
	{"COORDS",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_coords},
	{"COPYRIGHT",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_copyright},
	{"CUSTOMTEST",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_customTest},
	{"DECELERATE",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_decelerate},		//33
	{"DEFAULTSTATE",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_defaultState},
	{"DESTINATIONLEVEL",DOCUMENT_TYPE_SMIL,	SMIL_ATTR_destinationLevel},
	{"DESTINATIONPLAYSTATE",DOCUMENT_TYPE_SMIL,SMIL_ATTR_destinationPlaystate},
	{"DIRECTION",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_direction},
	{"DUR",				DOCUMENT_TYPE_SMIL,	SMIL_ATTR_dur},
	{"END",				DOCUMENT_TYPE_SMIL,	SMIL_ATTR_end},				//39
	{"ENDPROGRESS",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_endProgress},
	{"ENDSYNC",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_endsync},
	{"ERASE",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_erase},
	{"EXTERNAL",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_external},
	{"FADECOLOR",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_fadeColor},		//44
	{"FILL",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_fill},
	{"FILLDEFAULT",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_fillDefault},
	{"FILLTRANSITION",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_fillTransition},
	{"FIT",				DOCUMENT_TYPE_SMIL,	SMIL_ATTR_fit},
	{"FRAGMENT",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_fragment},
	{"FROM",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_from},
	{"HEIGHT",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_height},			//51
	{"HIGHER",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_higher},
	{"HORZREPEAT",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_horzRepeat},
	{"HREF",			DOCUMENT_TYPE_WML,	WML_ATTR_HREF_},
	{"HREF",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_href},
	{"HTTP-EQUIV",		DOCUMENT_TYPE_WML,	WML_ATTR_HTTP_EQUIV},
	{"ID",				DOCUMENT_TYPE_WML,	WML_ATTR_ID},				// 57
	{"ID",				DOCUMENT_TYPE_SMIL,	SMIL_ATTR_id},
	{"KEYSPLINES",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_keySplines},		//59
	{"KEYTIMES",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_keyTimes},
	{"LABEL",			DOCUMENT_TYPE_WML,	WML_ATTR_label},			//61
	{"LEFT",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_left},
	{"LONGDESC",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_longdesc},
	{"LOWER",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_lower},
	{"MAX",				DOCUMENT_TYPE_SMIL,	SMIL_ATTR_max},				//65
	{"MEDIAREPEAT",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_mediaRepeat},
	{"MEDIASIZE",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_mediaSize},
	{"MEDIATIME",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_mediaTime},
	{"METHOD",			DOCUMENT_TYPE_WML,	WML_ATTR_METHOD},
	{"MIN",				DOCUMENT_TYPE_SMIL,	SMIL_ATTR_min},
	{"MODE",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_mode},
	{"NAME",			DOCUMENT_TYPE_WML,	WML_ATTR_NAME},				//72
	{"NAME",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_name},
	{"NOHREF",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_nohref},
	{"ONENTERBACKWARD",	DOCUMENT_TYPE_WML,	WML_ATTR_onenterbackward},//75
	{"ONTIMER",			DOCUMENT_TYPE_WML,	WML_ATTR_ontimer},
	{"OPEN",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_open},
	{"OPTIONAL",		DOCUMENT_TYPE_WML,	WML_ATTR_DO_optional},
	{"ORIGIN",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_origin},
	{"OVERRIDE",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_override},
	{"PATH",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_path},			//81
	{"PAUSEDISPLAY",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_pauseDisplay},
	{"PEERS",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_peers},
	{"READINDEX",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_readIndex},		//84
	{"REGALIGN",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_regAlign},
	{"REGION",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_region},
	{"REGIONNAME",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_regionName},
	{"REGPOINT",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_regPoint},
	{"REPEAT",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_repeat},
	{"REPEATCOUNT",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_repeatCount},
	{"REPEATDUR",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_repeatDur},
	{"RESTART",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_restart},
	{"RESTARTDEFAULT",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_restartDefault},
	{"RIGHT",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_right},
	{"SHAPE",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_shape},			//95
	{"SHOW",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_show},
	{"SHOWBACKGROUND",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_showBackground},
	{"SKIP-CONTENT",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_skip_content},
	{"SOUNDLEVEL",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_soundLevel},
	{"SOURCELEVEL",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_sourceLevel},
	{"SOURCEPLAYSTATE",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_sourcePlaystate},
	{"SPEED",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_speed},
	{"SRC",				DOCUMENT_TYPE_WML,	WML_ATTR_SRC},
	{"SRC",				DOCUMENT_TYPE_SMIL,	SMIL_ATTR_src},
	{"STARTPROGRESS",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_startProgress},
	{"SUBTYPE",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_subtype},
	{"SYNCBEHAVIOR",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_syncBehavior},
	{"SYNCBEHAVIORDEFAULT",DOCUMENT_TYPE_SMIL,SMIL_ATTR_syncBehaviorDefault},
	{"SYNCMASTER",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_syncMaster},
	{"SYNCTOLERANCE",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_syncTolerance},
	{"SYNCTOLERANCEDEFAULT",DOCUMENT_TYPE_SMIL,SMIL_ATTR_syncToleranceDefault},
	{"SYSTEMAUDIODESC",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_systemAudioDesc},
	{"SYSTEMBITRATE",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_systemBitrate},
	{"SYSTEMCAPTIONS",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_systemCaptions},
	{"SYSTEMCOMPONENT",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_systemComponent},
	{"SYSTEMCPU",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_systemCPU},
	{"SYSTEMLANGUAGE",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_systemLanguage},
	{"SYSTEMOPERATINGSYSTEM",DOCUMENT_TYPE_SMIL,SMIL_ATTR_systemOperatingSystem},
	{"SYSTEM-OVERDUB-OR-CAPTION",DOCUMENT_TYPE_SMIL,SMIL_ATTR_system_overdub_or_caption},
	{"SYSTEMOVERDUBORSUBTITLE",DOCUMENT_TYPE_SMIL,SMIL_ATTR_systemOverdubOrSubtitle},
	{"SYSTEMREQUIRED",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_systemRequired},
	{"SYSTEMSCREENDEPTH",DOCUMENT_TYPE_SMIL,	SMIL_ATTR_systemScreenDepth},
	{"SYSTEMSCREENSIZE",DOCUMENT_TYPE_SMIL,	SMIL_ATTR_systemScreenSize},
	{"TABINDEX",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_tabindex},		//124
	{"TARGET",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_target},
	{"TARGETELEMENT",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_targetElement},
	{"TIMEACTION",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_timeAction},
	{"TIMECONTAINER",	DOCUMENT_TYPE_SMIL,	SMIL_ATTR_timeContainer},
	{"TITLE",			DOCUMENT_TYPE_WML,	WML_ATTR_Title},
	{"TITLE",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_title},
	{"TO",				DOCUMENT_TYPE_SMIL,	SMIL_ATTR_to},
	{"TOP",				DOCUMENT_TYPE_SMIL,	SMIL_ATTR_top},
	{"TRANSIN",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_transIn},
	{"TRANSOUT",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_transOut},
	{"TYPE",			DOCUMENT_TYPE_WML,	WML_ATTR_TYPE},
	{"TYPE",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_type},
	{"UID",				DOCUMENT_TYPE_SMIL,	SMIL_ATTR_uid},				//137
	{"URL",				DOCUMENT_TYPE_WML,	WML_ATTR_URL},
	{"VALUE",			DOCUMENT_TYPE_WML,	WML_ATTR_Value_},			//139
	{"VALUE",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_value},
	{"VALUES",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_values},
	{"VALUETYPE",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_valuetype},
	{"VERTREPEAT",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_vertRepeat},
	{"WIDTH",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_width},			//144
	{"XML:LANG",		DOCUMENT_TYPE_SMIL,	SMIL_ATTR_lang},			//145
	{"XMLNS",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_xmlns},
	{"Z-INDEX",			DOCUMENT_TYPE_SMIL,	SMIL_ATTR_z_index},			//147
	{"",				0,			0}							//148
};


#endif
