#ifndef _RESOURCE_SHORTCUTS_H
#define _RESOURCE_SHORTCUTS_H

#include "MMI_features.h"
#ifndef __DISABLE_SHORTCUTS_IMPL__

#include "GlobalMenuItems.h"
#include "PixtelDataTypes.h"
#include "ShortcutsStruct.h"
#ifndef __MMI_DUAL_SIM_MASTER__
#define SHCT_MAX_CANDI_LIST	50
#else
#define SHCT_MAX_CANDI_LIST      60
#endif
#define SHCT_MAX_SEL_LIST 	10

const U8 shct_max_list_cand    = SHCT_MAX_CANDI_LIST;
const U8 shct_list_default 	 =	SHCT_MAX_SEL_LIST;

/*Candidate List*/
const shct_item_struct gShctCandList[SHCT_MAX_CANDI_LIST]=
{
		{0, MITEM101_PBOOK_SEARCH_ENTRY},         
		{0, MITEM102_PBOOK_NEW_ENTRY},
		{0, MITEM109_PBOOK_CALLER_GROUPS},
#ifndef __MMI_DUAL_SIM_MASTER__
		{1, MITEM105_PBOOK_OWNER_NUMBER},
#else
		{45, MITEM105_PBOOK_OWNER_NUMBER}, /* 0x01 || 0x04 || 0x08 || 0x20 */
		{53, MENU_MTPNP_CARD2_OWNER_NUMBER}, /* 0x01 || 0x04 || 0x10 || 0x20 */
#endif		
		{0, MITEM1101_PBOOK_MEMORY_STATUS},
#ifndef __MMI_DUAL_SIM_MASTER__		
		{5, MITEM1102_PBOOK_STORAGE_LOCATION}, /* 0x01||0x04*/
#else
		{37, MITEM1102_PBOOK_STORAGE_LOCATION}, /* 0x01||0x04||0x20 */
#endif		
		{5, MENU9146_WELCOME_TEXT}, /* 0x01||0x04 */		
		{0, MENU_VOLUME_LEVEL},
		{0, MENU_SETTING_PREFERED_INPUT_METHOD},
		{0, MENU_SETTING_DEF_ENCODING_TYPE},
#ifndef __MMI_DUAL_SIM_MASTER__		
		{1, MENU8237_SCR8093_MNGCALL_MENU_FWD},
#else 
		{9, MENU_ID_UCM_CALL_SETTING_SIM1}, /* 0x01||0x08 */
		{17, MENU_MTPNP_CALL_SETTING}, /* 0x01||0x10 */
#endif
		{64, MENU_SETTING_WALLPAPER}, /* 0x40 cannot be excuted if idle screen is not present */
		{64, MENU_SETTING_SCR_SVR}, /* 0x40 cannot be excuted if idle screen is not present */
		{0, MENU_SETTING_CONTRAST_LEVEL},
		{0, MENU_SETTING_SCHEDULE_POWER},
		{0, MENU9165_PHONE_LOCK},
		{0, MENU3104_VOICE_MEMO},
		{0, MENU3101_THEMES},
		{0, MAIN_MENU_PROFILES_MENUID},
		{0, MENU_MT_CALL_ALERT_TYPE},
		{0, MENU_TONE_SETUP},
#ifndef __MMI_DUAL_SIM_MASTER__
		{3, MENU8101_RECEIVED_CALLS},
#else
		{9,  MENU8101_RECEIVED_CALLS}, /*  0x01||0x08 */
		{17, MENU_MTPNP_CALL_HISTORY_RECVD}, /* 0x01||0x10 */
#endif		
#ifndef __MMI_DUAL_SIM_MASTER__
		{3, MENU8102_DIALED_CALLS},
#else	
		{9, MENU8102_DIALED_CALLS}, /* 0x01||0x08 */
		{17, MENU_MTPNP_CALL_HISTORY_DIALED}, /* 0x01||0x10 */
#endif	
#ifndef __MMI_DUAL_SIM_MASTER__
		{3, MENU8103_MISSED_CALLS},
#else
		{9, MENU8103_MISSED_CALLS}, /* 0x01||0x08 */
		{17, MENU_MTPNP_CALL_HISTORY_MISSED}, /* 0x01||0x10 */
#endif
		{0, ORGANIZER_CALENDER_MENU},
		{0, ORGANIZER_TODOLIST_MENU},
		{0, ORGANIZER_ALARM_MENU},
		{0, EXTRA_CALCULATOR_MENU},
		{0, EXTRA_UNITCONVERTOR_MENU},
		{0, EXTRA_CURRENCYCONVERTOR_MENU},
		{0, EXTRA_HEALTH_MENU_BMI},
		{0, EXTRA_HEALTH_MENU_MENSTRUAL},
		{0, MITEM_WORLDCLOCK_BROWSECITY},
		{1, MESSAGES_MENU_WMESSAGE_MENU_ID},
		{1, MESSAGES_MENU_INBOX_MENUID},
		{1, MESSAGES_MENU_OUTBOX_MENUID},
#ifndef 	__MMI_DUAL_SIM_MASTER__	
		{1, MESSAGES_MENU_VMAIL_MENUID},
#else
		{1, MENU_MTPNP_DM_VMAIL},
#endif		
		{3, MENU_ID_IMPS_MAIN},
		{0, AUDIO_PLAYER_MAIN_MENUID},
		{0, MENU3103_RINGTONE_COMPOSER},
		{0, MENU_CONN_BT_MAIN},
		{3, SERVICES_WAP_MENU_ID},
		{1, MESSAGES_MENU_MMS_MENUID},
		{0, MENU_ID_VDOREC_APP},
		{0, MENU_ID_VDOPLY_APP},
		{0, MENU_ID_SNDREC_MAIN},
		{0, MENU_ID_FMRDO_MAIN},
		{0, MENU_ID_IMGVIEW_APP},
        {0, MENU_ID_CAMERA_APP},
        {0, MAIN_MENU_EBOOK_MENUID}
};

/*Default List*/
const shct_item_struct gShctDefaultList[SHCT_MAX_SEL_LIST]=
{
		{1,MITEM102_PBOOK_NEW_ENTRY},
		{1,MITEM101_PBOOK_SEARCH_ENTRY},
		{1,MITEM109_PBOOK_CALLER_GROUPS},
		{1,MITEM105_PBOOK_OWNER_NUMBER},
		{1,MITEM1101_PBOOK_MEMORY_STATUS},
		{1,MITEM1102_PBOOK_STORAGE_LOCATION},
		{1,MENU9146_WELCOME_TEXT},
		{1,MENU_TONE_SETUP},
		{1,MENU_VOLUME_LEVEL},
		{1,ORGANIZER_ALARM_MENU}
};

/*Dedicated List*/
#if defined(__MMI_DEDICATED_KEY_SHORTCUTS__)
#define SHCT_DEFAULT_MENU_ID		0

const U16 gShctDefaultDediList[4]=
{
		AUDIO_PLAYER_MAIN_MENUID,
		ORGANIZER_ALARM_MENU,
		MAIN_MENU_PROFILES_MENUID,
		MENU_TONE_SETUP
};
#endif
#endif
#endif
