/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
*
 * Filename:
 * ---------
 * F1RaceDefs.h
  *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  F1 Race id defines
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

#ifndef GAME_F1RACE_DEFS_H
#define GAME_F1RACE_DEFS_H

/* String ID */
typedef enum
{
    STR_GX_F1RACE_GAME_NAME = GAME_F1RACE_BASE + 1,
    STR_GX_F1RACE_HELP_DESCRIPTION
} F1RACE_STR_IDS;

/* Image ID */
typedef enum
{
    IMG_GX_F1RACE_GAME_ICON = GAME_F1RACE_BASE + 1,
    IMG_GX_F1RACE_PLAYER_CAR,
    IMG_GX_F1RACE_PLAYER_CAR_FLY,
    IMG_GX_F1RACE_PLAYER_CAR_FLY_UP,
    IMG_GX_F1RACE_PLAYER_CAR_FLY_DOWN,
    IMG_GX_F1RACE_PLAYER_CAR_HEAD_LIGHT,
    IMG_GX_F1RACE_PLAYER_CAR_CRASH,

    IMG_GX_F1RACE_OPPOSITE_CAR_0,
    IMG_GX_F1RACE_OPPOSITE_CAR_1,
    IMG_GX_F1RACE_OPPOSITE_CAR_2,
    IMG_GX_F1RACE_OPPOSITE_CAR_3,
    IMG_GX_F1RACE_OPPOSITE_CAR_4,
    IMG_GX_F1RACE_OPPOSITE_CAR_5,
    IMG_GX_F1RACE_OPPOSITE_CAR_6,

    IMG_GX_F1RACE_STATUS_LOGO,
#ifndef __MMI_GAME_MULTI_LANGUAGE_SUPPORT__
    IMG_GX_F1RACE_STATUS_SCORE,
    IMG_GX_F1RACE_STATUS_LEVEL,
#endif
    IMG_GX_F1RACE_STATUS_BOX,
#ifndef __MMI_GAME_MULTI_LANGUAGE_SUPPORT__
    IMG_GX_F1RACE_STATUS_FLY,

    IMG_GX_F1RACE_GOTEXT,
#endif
    IMG_GX_F1RACE_GRADESMAP,
    IMG_GX_F1RACE_GOPIC,

    IMG_GX_F1RACE_NUMBER_0,
    IMG_GX_F1RACE_NUMBER_1,
    IMG_GX_F1RACE_NUMBER_2,
    IMG_GX_F1RACE_NUMBER_3,
    IMG_GX_F1RACE_NUMBER_4,
    IMG_GX_F1RACE_NUMBER_5,
    IMG_GX_F1RACE_NUMBER_6,
    IMG_GX_F1RACE_NUMBER_7,
    IMG_GX_F1RACE_NUMBER_8,
    IMG_GX_F1RACE_NUMBER_9,
#ifdef __MMI_GAME_MULTI_LANGUAGE_SUPPORT__
    //added for multi-language support
    IMG_GX_F1RACE_STATUS_SCORE_LANGUAGE0,
    IMG_GX_F1RACE_STATUS_LEVEL_LANGUAGE0,
    IMG_GX_F1RACE_STATUS_FLY_LANGUAGE0,
    IMG_GX_F1RACE_GOTEXT_LANGUAGE0,
    IMG_GX_F1RACE_STATUS_SCORE_LANGUAGE1,
    IMG_GX_F1RACE_STATUS_LEVEL_LANGUAGE1,
    IMG_GX_F1RACE_STATUS_FLY_LANGUAGE1,
    IMG_GX_F1RACE_GOTEXT_LANGUAGE1,
    IMG_GX_F1RACE_STATUS_SCORE_LANGUAGE2,
    IMG_GX_F1RACE_STATUS_LEVEL_LANGUAGE2,
    IMG_GX_F1RACE_STATUS_FLY_LANGUAGE2,
    IMG_GX_F1RACE_GOTEXT_LANGUAGE2,
    IMG_GX_F1RACE_STATUS_SCORE_LANGUAGE3,
    IMG_GX_F1RACE_STATUS_LEVEL_LANGUAGE3,
    IMG_GX_F1RACE_STATUS_FLY_LANGUAGE3,
    IMG_GX_F1RACE_GOTEXT_LANGUAGE3,
    IMG_GX_F1RACE_STATUS_SCORE_LANGUAGE4,
    IMG_GX_F1RACE_STATUS_LEVEL_LANGUAGE4,
    IMG_GX_F1RACE_STATUS_FLY_LANGUAGE4,
    IMG_GX_F1RACE_GOTEXT_LANGUAGE4,
    IMG_GX_F1RACE_STATUS_SCORE_LANGUAGE5,
    IMG_GX_F1RACE_STATUS_LEVEL_LANGUAGE5,
    IMG_GX_F1RACE_STATUS_FLY_LANGUAGE5,
    IMG_GX_F1RACE_GOTEXT_LANGUAGE5,
    IMG_GX_F1RACE_STATUS_SCORE_LANGUAGE6,
    IMG_GX_F1RACE_STATUS_LEVEL_LANGUAGE6,
    IMG_GX_F1RACE_STATUS_FLY_LANGUAGE6,
    IMG_GX_F1RACE_GOTEXT_LANGUAGE6,
    IMG_GX_F1RACE_STATUS_SCORE_LANGUAGE7,
    IMG_GX_F1RACE_STATUS_LEVEL_LANGUAGE7,
    IMG_GX_F1RACE_STATUS_FLY_LANGUAGE7,
    IMG_GX_F1RACE_GOTEXT_LANGUAGE7,
    IMG_GX_F1RACE_STATUS_SCORE_LANGUAGE8,
    IMG_GX_F1RACE_STATUS_LEVEL_LANGUAGE8,
    IMG_GX_F1RACE_STATUS_FLY_LANGUAGE8,
    IMG_GX_F1RACE_GOTEXT_LANGUAGE8,
    IMG_GX_F1RACE_STATUS_SCORE_LANGUAGE9,
    IMG_GX_F1RACE_STATUS_LEVEL_LANGUAGE9,
    IMG_GX_F1RACE_STATUS_FLY_LANGUAGE9,
    IMG_GX_F1RACE_GOTEXT_LANGUAGE9,
#endif  /* __MMI_GAME_MULTI_LANGUAGE_SUPPORT__ */
    IMG_GX_F1RACE_TOTAL
} F1RACE_IMG_IDS;

#endif /* GAME_F1RACE_DEFS_H */ 

