/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2002
*
*****************************************************************************/
/*****************************************************************************
*
 * Filename:
 * ---------
 * MagicsushiDefs.h
 *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  Game id define Magicsushi.
 *
 * Author:
 * -------
 * -------
 *
 
 ****************************************************************************/
#ifndef GAME_MAGICSUSHI_DEFS_H
#define GAME_MAGICSUSHI_DEFS_H

typedef enum
{
    STR_ID_GX_MAGICSUSHI_GAME_NAME = GAME_MAGICSUSHI_BASE + 1,
    STR_ID_GX_MAGICSUSHI_NEW,
    STR_ID_GX_MAGICSUSHI_RESUME,
    STR_ID_GX_MAGICSUSHI_GRADE,
    STR_ID_GX_MAGICSUSHI_HELP,
    STR_ID_GX_MAGICSUSHI_HELP_DESCRIPTION,
    STR_ID_GX_MAGICSUSHI_COUNT
} mmi_magicsushi_str_id_enum;

/* Image ID */
typedef enum
{
    /* Image */
    IMG_ID_GX_MAGICSUSHI_GAME_ICON = GAME_MAGICSUSHI_BASE + 1,
    IMG_ID_GX_MAGICSUSHI_NUMBER_0,
    IMG_ID_GX_MAGICSUSHI_NUMBER_1,
    IMG_ID_GX_MAGICSUSHI_NUMBER_2,
    IMG_ID_GX_MAGICSUSHI_NUMBER_3,
    IMG_ID_GX_MAGICSUSHI_NUMBER_4,
    IMG_ID_GX_MAGICSUSHI_NUMBER_5,
    IMG_ID_GX_MAGICSUSHI_NUMBER_6,
    IMG_ID_GX_MAGICSUSHI_NUMBER_7,
    IMG_ID_GX_MAGICSUSHI_NUMBER_8,
    IMG_ID_GX_MAGICSUSHI_NUMBER_9,
    IMG_ID_GX_MAGICSUSHI_TYPE_NULL,
    IMG_ID_GX_MAGICSUSHI_TYPE_0,
    IMG_ID_GX_MAGICSUSHI_TYPE_1,
    IMG_ID_GX_MAGICSUSHI_TYPE_2,
    IMG_ID_GX_MAGICSUSHI_TYPE_3,
    IMG_ID_GX_MAGICSUSHI_TYPE_4,
    IMG_ID_GX_MAGICSUSHI_TYPE_5,
    IMG_ID_GX_MAGICSUSHI_TYPE_6,
    IMG_ID_GX_MAGICSUSHI_TYPE_7,
    IMG_ID_GX_MAGICSUSHI_TYPE_MAGIC1,
    IMG_ID_GX_MAGICSUSHI_TYPE_MAGIC2,
    IMG_ID_GX_MAGICSUSHI_TYPE_MAGIC3,
    IMG_ID_GX_MAGICSUSHI_TYPE_NULL2,
    IMG_ID_GX_MAGICSUSHI_SELECTED,
    IMG_ID_GX_MAGICSUSHI_PROGRESS,
    
#ifndef     __MMI_GAME_MULTI_LANGUAGE_SUPPORT__
    IMG_ID_GX_MAGICSUSHI_GAME_BACKGROUND,
    IMG_ID_GX_MAGICSUSHI_GAMEOVER,
    IMG_ID_GX_MAGICSUSHI_UPLEVEL,
    IMG_ID_GX_MAGICSUSHI_NOMOREMOVE,
#else   /*__MMI_GAME_MULTI_LANGUAGE_SUPPORT__*/
    IMG_ID_GX_MAGICSUSHI_BACKGROUND_LANGUAGE0,
    IMG_ID_GX_MAGICSUSHI_GAMEOVER_LANGUAGE0,
    IMG_ID_GX_MAGICSUSHI_UPLEVEL_LANGUAGE0,
    IMG_ID_GX_MAGICSUSHI_NOMOREMOVE_LANGUAGE0,
    IMG_ID_GX_MAGICSUSHI_BACKGROUND_LANGUAGE1,
    IMG_ID_GX_MAGICSUSHI_GAMEOVER_LANGUAGE1,
    IMG_ID_GX_MAGICSUSHI_UPLEVEL_LANGUAGE1,
    IMG_ID_GX_MAGICSUSHI_NOMOREMOVE_LANGUAGE1,
    IMG_ID_GX_MAGICSUSHI_BACKGROUND_LANGUAGE2,
    IMG_ID_GX_MAGICSUSHI_GAMEOVER_LANGUAGE2,
    IMG_ID_GX_MAGICSUSHI_UPLEVEL_LANGUAGE2,
    IMG_ID_GX_MAGICSUSHI_NOMOREMOVE_LANGUAGE2,
    IMG_ID_GX_MAGICSUSHI_BACKGROUND_LANGUAGE3,
    IMG_ID_GX_MAGICSUSHI_GAMEOVER_LANGUAGE3,
    IMG_ID_GX_MAGICSUSHI_UPLEVEL_LANGUAGE3,
    IMG_ID_GX_MAGICSUSHI_NOMOREMOVE_LANGUAGE3,
    IMG_ID_GX_MAGICSUSHI_BACKGROUND_LANGUAGE4,
    IMG_ID_GX_MAGICSUSHI_GAMEOVER_LANGUAGE4,
    IMG_ID_GX_MAGICSUSHI_UPLEVEL_LANGUAGE4,
    IMG_ID_GX_MAGICSUSHI_NOMOREMOVE_LANGUAGE4,
    IMG_ID_GX_MAGICSUSHI_BACKGROUND_LANGUAGE5,
    IMG_ID_GX_MAGICSUSHI_GAMEOVER_LANGUAGE5,
    IMG_ID_GX_MAGICSUSHI_UPLEVEL_LANGUAGE5,
    IMG_ID_GX_MAGICSUSHI_NOMOREMOVE_LANGUAGE5,
    IMG_ID_GX_MAGICSUSHI_BACKGROUND_LANGUAGE6,
    IMG_ID_GX_MAGICSUSHI_GAMEOVER_LANGUAGE6,
    IMG_ID_GX_MAGICSUSHI_UPLEVEL_LANGUAGE6,
    IMG_ID_GX_MAGICSUSHI_NOMOREMOVE_LANGUAGE6,
    IMG_ID_GX_MAGICSUSHI_BACKGROUND_LANGUAGE7,
    IMG_ID_GX_MAGICSUSHI_GAMEOVER_LANGUAGE7,
    IMG_ID_GX_MAGICSUSHI_UPLEVEL_LANGUAGE7,
    IMG_ID_GX_MAGICSUSHI_NOMOREMOVE_LANGUAGE7,
    IMG_ID_GX_MAGICSUSHI_BACKGROUND_LANGUAGE8,
    IMG_ID_GX_MAGICSUSHI_GAMEOVER_LANGUAGE8,
    IMG_ID_GX_MAGICSUSHI_UPLEVEL_LANGUAGE8,
    IMG_ID_GX_MAGICSUSHI_NOMOREMOVE_LANGUAGE8,
    IMG_ID_GX_MAGICSUSHI_BACKGROUND_LANGUAGE9,
    IMG_ID_GX_MAGICSUSHI_GAMEOVER_LANGUAGE9,
    IMG_ID_GX_MAGICSUSHI_UPLEVEL_LANGUAGE9,
    IMG_ID_GX_MAGICSUSHI_NOMOREMOVE_LANGUAGE9,
#endif      /*__MMI_GAME_MULTI_LANGUAGE_SUPPORT__*/

    IMG_ID_GX_MAGICSUSHI_CURSOR,
    IMG_ID_GX_MAGICSUSHI_UP,
    IMG_ID_GX_MAGICSUSHI_DOWN,
    IMG_ID_GX_MAGICSUSHI_COUNT
} mmi_magicsushi_img_id_enum;

#endif /* GAME_MAGICSUSHI_DEFS_H */ 

