/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 * PushInboxResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This defines the String ,screen,& Image ID for push inbox module
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/
/*
 * #ifndef _JPROFILEHANDLERDEFS_H
 * #define _JPROFILEHANDLERDEFS_H
 */
#define __NEWSIMULATOR

#include "MMI_features.h"
#include "MMIDataType.h"
#include "BrowserResDef.h"
#undef __NEWSIMULATOR
#ifdef __MMI_BROWSER_2__

typedef enum
{
   /**** push string ID's****/
    STR_ID_PUSH_INBOX_SETTING = BROWSER_PUSH_BASE + 1,
    STR_ID_PUSH_INBOX_ENABLE_PUSH,
    STR_ID_PUSH_ENABLE_ON,
    STR_ID_PUSH_ENABLE_OFF,
    STR_ID_PUSH_INBOX_TRUST_SETTING,
    STR_ID_PUSH_INBOX_TRUSTED_LIST,
    STR_ID_PUSH_INBOX_TRUST_LIST_DISABLE,
    STR_ID_PUSH_INBOX_TRUST_LIST_ALWAYS,
    STR_ID_PUSH_INBOX_TRUST_LIST_ALWAYS_ASK,
    STR_ID_PUSH_INBOX_TRUST_LIST_ADD_NEW,
    STR_ID_PUSH_INBOX_TRUST_LIST_MODIFY,
    STR_ID_PUSH_INBOX_TRUST_LIST_DELETE,
    STR_ID_PUSH_INBOX_TRUST_LIST_PHONE_NUMBER,
    STR_ID_PUSH_INBOX_TRUST_LIST_IP_ADDRESS,
    STR_ID_PUSH_INBOX_TRUST_LIST_DOMAIN_NAME,
    STR_ID_PUSH_INBOX_SL_SETTING,
    STR_ID_PUSH_INBOX_SL_SETTING_NEVER,
    STR_ID_PUSH_INBOX_SL_SETTING_CONFIRM,
    STR_ID_PUSH_INBOX_SL_SETTING_WITHOUT_CONFIRM,
    STR_ID_PUSH_INBOX_SERVICE_MESSAGE_READ,
    STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE,
    STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE_ALL,
    STR_ID_PUSH_INBOX_SERVICE_MESSAGE_GOTO,
    STR_ID_PUSH_INBOX_ADD_TO_TRUST_LIST,
    STR_ID_PUSH_INBOX_ADD_HOMEPAGE,
    STR_ID_PUSH_INBOX_ADD_BOOKMARK,
   //STR_ID_PUSH_INBOX_SERVICE_MESSAGE_INFO,
    STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY,
    STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY_EMAIL,
    STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY_SMS,
    STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY_MMS,
    STR_ID_PUSH_INBOX_ADD_NEW,
    STR_ID_PUSH_SERVICE_MESSAGE_RCVD,
    STR_ID_BRW_PUSH_CREATED_TIME,
    STR_ID_BRW_PUSH_EXPIRY_TIME,
    STR_ID_PUSH_MESSAGE,
    STR_ID_PUSH_URL,
    STR_ID_BRW_PUSH_PRIORITY,
    STR_ID_BRW_PUSH_PRIORITY_LOW,
    STR_ID_BRW_PUSH_PRIORITY_MEDIUM,
    STR_ID_BRW_PUSH_PRIORITY_HIGH,
    STR_ID_PUSH_MSG_NOT_AVAILABLE,
    STR_ID_PUSH_VALIDATION_FAIL_NEW_MSG,
    STR_ID_PUSH_MSG_LOADING,
    STR_ID_PUSH_TRUST_LIST_FULL,
    STR_ID_PUSH_INBOX,
    STR_ID_PUSH_INBOX_MODIFIED,
    STR_ID_PUSH_INBOX_EMPTY,
    STR_ID_BRW_NEW_PUSH_MESSAGE,
	STR_ID_BRW_NEW_MESSAGE,
    STR_ID_PUSH_SETTING_INVALID_ENTRY,
    STR_ID_PUSH_INBOX_TRUST_LIST_DELETE_ALL,
	STR_ID_BRW_PUSH_VALIDATION_ADDR, 
	STR_ID_BRW_PUSH_SENDER_ADDR,	 
	STR_ID_BRW_PUSH_MESSAGE_EXPIRED,
	STR_ID_PUSH_STORAGE_FULL,
	STR_ID_PUSH_INVALID_SIM,
	STR_ID_PUSH_SAME_ITEM_EXIST
	//STR_ID_PUSH_USB_PLUGGED_IN
} str_push_list_enum;

typedef enum
{
    SCR_ID_PSH_PUSH_SETTING = BROWSER_PUSH_BASE + 1,
    SCR_ID_PSH_PUSH_ENABLE,
    SCR_ID_PSH_SL_SETTING,
    SCR_ID_PSH_TRUST_SETTING,
    SCR_ID_PSH_TRUST_LIST,
    SCR_ID_PSH_ADD_NEW,
    SCR_ID_PSH_SELECT_TRUST_ADDRESS,
    SCR_ID_PSH_ADD_NEW_BY_PHONE_NO,
    SCR_ID_PSH_ADD_NEW_BY_IP_ADDRESS,
    SCR_ID_PSH_ADD_NEW_BY_DOMAIN_NAME,
    SCR_ID_BRW_WAP_PUSH_POPUP_DUMMY_SCREEN,
    SCR_ID_BRW_NEW_PUSH_MESSAGE_IND,
    SCR_ID_BRW_READ_SERVICE_MESSAGE,
    SCR_ID_BRW_READ_SERVICE_MESSAGE_OPTIONS,
    SCR_ID_BRW_INVALID_PUSH_MESSAGE,
    SCR_ID_PUSH_INBOX,
    SCR_ID_PUSH_PROCESSING,
    SCR_ID_BRW_SEND_BY_OPTIONS,
    SCR_ID_UM_MESSAGE_OPTIONS,
    SCR_ID_PUSH_DISPALY_CONFIRMATION,
    SCR_ID_PUSH_SERIVCE_UNKNOWN_ADDR
} scr_push_list_enum;

#endif
