/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *  VoIPResDef.h
 *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  This file defines resource enum, such as string id, image id and screen id.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#ifndef VOIP_DEF_H
#define VOIP_DEF_H
#include "MMIDatatype.h"

#define VOIP_STRING_BASE                    (VOIP_BASE + 1)
#define VOIP_IMAGE_BASE                     (VOIP_BASE + 1)
#define VOIP_SCREEN_BASE                    (VOIP_BASE + 1)

typedef enum
{
    STR_ID_VOIP_MAIN = VOIP_STRING_BASE,
    STR_ID_VOIP_PROCESSING,
    STR_ID_VOIP_LOGIN,
    STR_ID_VOIP_LOGOUT,
    STR_ID_VOIP_LOGIN_OK,
    STR_ID_VOIP_LOGOUT_OK,
    STR_ID_VOIP_LOGOUT_IND,
    STR_ID_VOIP_CONNECT_TO_SERVER,
    STR_ID_VOIP_DISCONNECT_FROM_SERVER,
    STR_ID_VOIP_SUMMARY,
    STR_ID_VOIP_PROF_SETTING,
    STR_ID_VOIP_PROF_EDIT_COMMON,
    STR_ID_VOIP_PROF_EDIT_ACCOUNT,
    STR_ID_VOIP_PROF_EDIT_OUTBOUND,
    STR_ID_VOIP_PROF_EDIT_REGISTER,
    STR_ID_VOIP_PROF_EDIT_NAT,
    STR_ID_VOIP_PROF_COMMON_PROFNAME,
    STR_ID_VOIP_PROF_COMMON_DATAACCOUNT,
    STR_ID_VOIP_PROF_COMMON_AUTOLOGIN,
    STR_ID_VOIP_PROF_COMMON_VMSERVER,
    STR_ID_VOIP_PROF_COMMON_PROF1,
    STR_ID_VOIP_PROF_COMMON_PROF2,
    STR_ID_VOIP_PROF_COMMON_PROF3,
    STR_ID_VOIP_PROF_COMMON_PROF4,
    STR_ID_VOIP_PROF_COMMON_PROF5,
    STR_ID_VOIP_PROF_COMMON_PROF6,
    STR_ID_VOIP_PROF_COMMON_PROF7,
    STR_ID_VOIP_PROF_COMMON_PROF8,
    STR_ID_VOIP_PROF_COMMON_PROF9,
    STR_ID_VOIP_PROF_COMMON_PROF10,
    STR_ID_VOIP_PROF_ACCOUNT_SIPSERVER,
    STR_ID_VOIP_PROF_ACCOUNT_SIPPORT,
    STR_ID_VOIP_PROF_ACCOUNT_DISPNAME,
    STR_ID_VOIP_PROF_USERNAME,
    STR_ID_VOIP_PROF_PASSWORD,
    STR_ID_VOIP_PROF_ACCOUNT_AUTHNAME,
    STR_ID_VOIP_PROF_DEFAULT,
    STR_ID_VOIP_PROF_STATUS,
    STR_ID_VOIP_PROF_OUTBOUND_SERVER,
    STR_ID_VOIP_PROF_OUTBOUND_PORT,
    STR_ID_VOIP_PROF_OUTBOUND_NEVER,
    STR_ID_VOIP_PROF_AUTO,
    STR_ID_VOIP_PROF_OUTBOUND_ALWAYS,
    STR_ID_VOIP_PROF_REGISTER_SERVER,
    STR_ID_VOIP_PROF_REGISTER_PORT,
    STR_ID_VOIP_PROF_NAT_FIREWALL,
    STR_ID_VOIP_PROF_NAT_STUNSERVER,
    STR_ID_VOIP_PROF_NAT_STUNPORT,
    STR_ID_VOIP_PROF_NAT_INTERVAL,
    STR_ID_VOIP_PROF_NAT_STATICNAT,
    STR_ID_VOIP_PROF_NAT_9SEC,
    STR_ID_VOIP_PROF_NAT_15SEC,
    STR_ID_VOIP_PROF_NAT_30SEC,
    STR_ID_VOIP_PROF_NAT_60SEC,
    STR_ID_VOIP_CALL_SETTING,
    STR_ID_VOIP_SETTING_AUTO_ANSWER,
    STR_ID_VOIP_SETTING_AUTO_REJECT,
    STR_ID_VOIP_SETTING_AUTO_REDIAL,
    STR_ID_VOIP_SETTING_HIDE_CALLER_ID,
    STR_ID_VOIP_SETTING_DTMF,
    STR_ID_VOIP_SETTING_SECURE_RTP,
    STR_ID_VOIP_SETTING_COMFORT_NOISE,
    STR_ID_VOIP_SETTING_SET_CODEC_ORDER,
    STR_ID_VOIP_SETTING_PRIORITY,
    STR_ID_VOIP_SETTING_ANYKEY,
    STR_ID_VOIP_SETTING_AUTO,
    STR_ID_VOIP_SETTING_REJECT_UNKNOWN,
    STR_ID_VOIP_SETTING_REJECT_ALL,
    STR_ID_VOIP_SETTING_INBAND,
    STR_ID_VOIP_SETTING_OUTBAND,
    STR_ID_VOIP_SETTING_CODEC1,
    STR_ID_VOIP_SETTING_CODEC2,
    STR_ID_VOIP_SETTING_CODEC3,
    STR_ID_VOIP_SETTING_CODEC4,
    STR_ID_VOIP_SETTING_CODEC5,
    STR_ID_VOIP_SETTING_CODEC6,
    STR_ID_VOIP_SETTING_CODEC7,
    STR_ID_VOIP_SETTING_CODEC8,
    STR_ID_VOIP_SETTING_CODEC9,
    STR_ID_VOIP_SETTING_CODEC10,
    STR_ID_VOIP_NEW_CALL,
    STR_ID_VOIP_DIAL,
    STR_ID_VOIP_SAVE_PHONEBOOK,
    STR_ID_VOIP_INPUT_METHOD,
    STR_ID_VOIP_SOS,
    STR_ID_VOIP_EMERGENCY_NUM,
    STR_ID_VOIP_OPTION_QUERY,
    STR_ID_VOIP_CALLING,
    STR_ID_VOIP_CALL_FORWARDED,
    STR_ID_VOIP_REDIALING,
    STR_ID_VOIP_TIME_UNIT,
    STR_ID_VOIP_RINGING,
    STR_ID_VOIP_ANSWER,
    STR_ID_VOIP_REJECT,
    STR_ID_VOIP_HAND_FREE,
    STR_ID_VOIP_HAND_HELD,
    STR_ID_VOIP_LOUD_SPEAKER_OFF,
    STR_ID_VOIP_LOUD_SPEAKER_ON,
    STR_ID_VOIP_CALL_OPTION,
    STR_ID_VOIP_HOLD_SINGLE,
    STR_ID_VOIP_HOLD_CONFERENCE,
    STR_ID_VOIP_RETRIEVE_SINGLE,
    STR_ID_VOIP_RETRIEVE_CONFERENCE,
    STR_ID_VOIP_SWAP,
    STR_ID_VOIP_CONFERENCE,
    STR_ID_VOIP_SPLIT,
    STR_ID_VOIP_END_SINGLE,
    STR_ID_VOIP_END_CONFERENCE,
    STR_ID_VOIP_END_ALL,
    STR_ID_VOIP_TRANSFER,
    STR_ID_VOIP_REPLACE,
    STR_ID_VOIP_PHONEBOOK,
    STR_ID_VOIP_SOUND_RECORDER,
    STR_ID_VOIP_MUTE,
    STR_ID_VOIP_DTMF,
    STR_ID_VOIP_HOLD_OK,
    STR_ID_VOIP_RETRIEVE_OK,
    STR_ID_VOIP_SWAP_OK,
    STR_ID_VOIP_CONFERENCE_OK,
    STR_ID_VOIP_SPLIT_OK,
    STR_ID_VOIP_TRANSFER_OK,
    STR_ID_VOIP_REPLACE_OK,
    STR_ID_VOIP_CALL_END,
    STR_ID_VOIP_CALL_ABORT,
    STR_ID_VOIP_CALL_REJECT,
    STR_ID_VOIP_USER_BUSY,
    STR_ID_VOIP_USER_NOT_FOUND,
    STR_ID_VOIP_NO_ACTIVATED_PROFILE,
    STR_ID_VOIP_EMPTY_PROFILE_NAME,
    STR_ID_VOIP_EMPTY_SIP_SERVER,
    STR_ID_VOIP_EMPTY_OUTBOUND_SERVER,
    STR_ID_VOIP_EMPTY_REGISTER_SERVER,
    STR_ID_VOIP_EMPTY_STUN_SERVER,
    STR_ID_VOIP_EMPTY_USERNAME,
    STR_ID_VOIP_INVALID_PORT_NUMBER,
    STR_ID_VOIP_INVALID_USERNAME,
    STR_ID_VOIP_INVALID_AUTHNAME,
    STR_ID_VOIP_INVALID_VM_SERVER,
    STR_ID_VOIP_INVALID_IP_ADDRESS,
    STR_ID_VOIP_INVALID_URI,
    STR_ID_VOIP_CANNOT_DIAL_OWNER,
    STR_ID_VOIP_NOT_ALLOW_TO_DIAL,
    STR_ID_VOIP_NOT_ALLOW_TO_HOLD,
    STR_ID_VOIP_REGISTER,
    STR_ID_VOIP_NOT_REGISTER,
    STR_ID_VOIP_ALREADY_REGISTER,
    STR_ID_VOIP_REGISTER_FAIL,
    STR_ID_VOIP_AUTHENTICATION_FAIL,
    STR_ID_VOIP_REQUEST_TIMEOUT,
    STR_ID_VOIP_INVALID_PARAMETER,
    STR_ID_VOIP_NETWORK_DOWN,
    STR_ID_VOIP_NETWORK_ERROR,
    STR_ID_VOIP_NUMBER_MOVE,
    STR_ID_VOIP_ACTION_CONFLICT,
    STR_ID_VOIP_ACTION_INVALID,
    STR_ID_VOIP_ACTION_FORBIDDEN,
    STR_ID_VOIP_CALL_NOT_EXIST,
    STR_ID_VOIP_SWAP_FAIL,
    STR_ID_VOIP_CONFERENCE_FAIL,
    STR_ID_VOIP_SPLIT_FAIL,
    STR_ID_VOIP_TRANSFER_FAIL,
    STR_ID_VOIP_SDP_ERROR,
    STR_ID_VOIP_SIP_ERROR,
    STR_ID_VOIP_DNS_ERROR,
    STR_ID_VOIP_NAT_ERROR,
    STR_ID_VOIP_UNKNOWN_ERROR,
    STR_ID_VOIP_VOICE_MESSAGE,
    STR_ID_VOIP_FAX_MESSAGE,
    STR_ID_VOIP_PAGER_MESSAGE,
    STR_ID_VOIP_MULTIMEDIA_MESSAGE,
    STR_ID_VOIP_TEXT_MESSAGE,
    STR_ID_VOIP_UNKNOWN_MESSAGE,
    STR_ID_VOIP_NEW_MESSAGE,
    STR_ID_VOIP_URGENT_MESSAGE,
    STR_ID_VOIP_MSG_UNIT,
    STR_ID_VOIP_NOT_SUPPORT,
    STR_ID_VOIP_OTAP_ERROR_NO_PROFILES,
    STR_ID_VOIP_OTAP_ERROR_PROFILE_IN_USE,
    STR_ID_VOIP_OTAP_SKIP_INVALID_PROFILES,
    STR_ID_VOIP_OTAP_AUTO_RENAME_PROFILE,
    STR_ID_VOIP_OTAP_INSTALL_PROFILE,
    STR_ID_VOIP_OTAP_REPLACE_PROFILE,
    STR_ID_VOIP_OTAP_REPLACE_CONFIRM,
    STR_ID_VOIP_OTAP_NAME,
    STR_ID_VOIP_TOTAL
} voip_string_enum;

typedef enum
{
    IMG_ID_VOIP_MAIN = VOIP_IMAGE_BASE,
    IMG_ID_VOIP_STATUS_ICON,
    IMG_ID_VOIP_PROF_EDIT_COMMON,
    IMG_ID_VOIP_PROF_COMMON_PROF_NAME,
    IMG_ID_VOIP_PROF_COMMON_DATA_ACCT,
    IMG_ID_VOIP_PROF_COMMON_AUTO_LOGIN,
    IMG_ID_VOIP_PROF_COMMON_VMSERVER,
    IMG_ID_VOIP_PROF_EDIT_ACCOUNT,
    IMG_ID_VOIP_PROF_ACCOUNT_SIP_SERVER,
    IMG_ID_VOIP_PROF_ACCOUNT_SIP_PORT,
    IMG_ID_VOIP_PROF_ACCOUNT_DISPNAME,
    IMG_ID_VOIP_PROF_ACCOUNT_USERNAME,
    IMG_ID_VOIP_PROF_ACCOUNT_PASSWORD,
    IMG_ID_VOIP_PROF_ACCOUNT_AUTHNAME,
    IMG_ID_VOIP_PROF_EDIT_OUTBOUND,
    IMG_ID_VOIP_PROF_OUTBOUND_STATUS,
    IMG_ID_VOIP_PROF_OUTBOUND_SERVER,
    IMG_ID_VOIP_PROF_OUTBOUND_PORT,
    IMG_ID_VOIP_PROF_OUTBOUND_USERNAME,
    IMG_ID_VOIP_PROF_OUTBOUND_PASSWORD,
    IMG_ID_VOIP_PROF_EDIT_REGISTER,
    IMG_ID_VOIP_PROF_REGISTER_STATUS,
    IMG_ID_VOIP_PROF_REGISTER_SERVER,
    IMG_ID_VOIP_PROF_REGISTER_PORT,
    IMG_ID_VOIP_PROF_REGISTER_USERNAME,
    IMG_ID_VOIP_PROF_REGISTER_PASSWORD,
    IMG_ID_VOIP_PROF_EDIT_NAT,
    IMG_ID_VOIP_PROF_NAT_STATUS,
    IMG_ID_VOIP_PROF_NAT_FIREWALL,
    IMG_ID_VOIP_PROF_NAT_STUNSERVER,
    IMG_ID_VOIP_PROF_NAT_STUNPORT,
    IMG_ID_VOIP_PROF_NAT_INTERVAL,
    IMG_ID_VOIP_CALL_EDITOR,
    IMG_ID_VOIP_OUTGOING_CALL,
    IMG_ID_VOIP_INCOMING_CALL,
    IMG_ID_VOIP_CALL_STATE_ACTIVE,
    IMG_ID_VOIP_CALL_STATE_HOLD,
    IMG_ID_VOIP_CALL_ENDED,
    IMG_ID_VOIP_MSG_WAITING,
    IMG_ID_VOIP_TOTAL
} voip_image_enum;

typedef enum
{
    SCR_ID_VOIP_MAIN = (VOIP_BASE + 1), /* for screen id enum parser */
    SCR_ID_VOIP_SUMMARY,
    SCR_ID_VOIP_PROCESSING,
    SCR_ID_VOIP_PROF_SETTING,
    SCR_ID_VOIP_PROF_SETTING_OPTION,
    SCR_ID_VOIP_PROF_EDIT,
    SCR_ID_VOIP_PROF_COMMON,
    SCR_ID_VOIP_PROF_ACCOUNT,
    SCR_ID_VOIP_PROF_OUTBOUND,
    SCR_ID_VOIP_PROF_REGISTER,
    SCR_ID_VOIP_PROF_NAT,
    SCR_ID_VOIP_PROF_EDIT_INLINEITEMS,
    SCR_ID_VOIP_FULL_EDITOR_OPTION,
    SCR_ID_VOIP_CALL_SETTING,
    SCR_ID_VOIP_SETTING_AUTO_ANSWER,
    SCR_ID_VOIP_SETTING_AUTO_REJECT,
    SCR_ID_VOIP_SETTING_AUTO_REDIAL,
    SCR_ID_VOIP_SETTING_HIDE_CALLER_ID,
    SCR_ID_VOIP_SETTING_DTMF,
    SCR_ID_VOIP_SETTING_SECURE_RTP,
    SCR_ID_VOIP_SETTING_COMFORT_NOISE,
    SCR_ID_VOIP_SETTING_SET_CODEC_ORDER,
    SCR_ID_VOIP_SETTING_SET_CODEC_ORDER_OPTION,
    SCR_ID_VOIP_SETTING_GENERAL,
    SCR_ID_VOIP_MARKER,
    SCR_ID_VOIP_CALL_EDITOR,
    SCR_ID_VOIP_CALL_EDITOR_OPTION,
    SCR_ID_VOIP_OUTGOING_CALL,
    SCR_ID_VOIP_REDIALING_CALL,
    SCR_ID_VOIP_INCOMING_CALL,
    SCR_ID_VOIP_IN_CALL,
    SCR_ID_VOIP_DTMF_EDITOR,
    SCR_ID_VOIP_CALL_OPTION,
    SCR_ID_VOIP_TRANSFER,
    SCR_ID_VOIP_TRANSFER_OPTION,
    SCR_ID_VOIP_MULTI_HELD_CALL,
    SCR_ID_VOIP_OPTION_QUERY_EDITOR,
    SCR_ID_VOIP_OPTION_QUERY_RESULT,
    SCR_ID_VOIP_MSG_WAITING,
    SCR_ID_VOIP_OTAP_INSTALL_PROFILE,
    SCR_ID_VOIP_OTAP_REPLACE_PROFILE,
    SCR_ID_VOIP_TOTAL
} voip_screen_enum;
#endif /* VOIP_DEF_H */ 

