/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * EbookResDef.h
 *
 * Project:
 * --------
 * MAUI
 *
 * Description:
 * ------------
 * This file defines resource id for Unit Convertor application.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#ifndef _MMI_EBOOKRESDEF_H
#define  _MMI_EBOOKRESDEF_H

typedef enum
{
    EBOOK_SCREENID = EBOOK_BASE + 1,
    EBOOK_SELECT_DRIVE_SCREEN_ID,
    EBOOK_OPEN_OPTION_SCREENID,
    EBOOK_BOOKSHELF_SCREENID,
    EBOOK_OPEN_SCREENID,
    EBOOK_INFO_SCREENID,
    EBOOK_SEARCH_SCREENID,
    EBOOK_SEARCH_STR_SCREENID,
    EBOOK_JUMPTO_SCREENID,
    EBOOK_SETTINGS_SCREEID,
    EBOOK_BOOK_SETTINGS_SCREENID,
    EBOOK_REMOVE_BOOKMARK_SCREENID,
    EBOOK_GOTO_BOOKMARK_SCREENID,
    EBOOK_BOOK_SETTINGS,
    EBOOK_ADD_BOOK_MARK_SCREEN_ID,
    EBOOK_JUMPTO_SCREEN_ID,
    EBOOK_DUMMY_SCREEN_ID,
    EBOOK_JUMPTO_DONE_SCREEN_ID,
    EBOOK_BOOK_SHELF_SETTINGS_SCREEN_ID,
    EBOOK_BOOK_SETTINGS_SCREEN_ID,
    SCR_ID_EBOOK_WAITSCREEN,
    SCR_ID_EBOOK_FILE_MOVE_WAITSCREEN,
    SCR_EBOOK_ENTER_PERCENTAGE_SCREEN_ID,
    DUMMY_SCREEN_ID,
    SCR_EDIT_BOOK_MARK_NAME,
    EBOOK_HELP_SCREEN
} SCREENID_LIST_EBOOK;

typedef enum
{
    EBOOK_TITLE_STRINGID = EBOOK_BASE + 1,
    EBOOK_DRIVE_SELECT_TYPE,
    STR_SETTINGS_PHONE_MEMORY,
    STR_SETTINGS_CARD_MEMORY,
    STR_SETTINGS_SELECT_MEMORY,
    EBOOK_TITLE_BOOKSHELF,
    EBOOK_BKSLF_OPTION,
    STR_OPEN_CARD_DRV,
    STR_OPEN_PRIVATE_DRV,
    STR_REFRESH_EBOOK,
    STR_OPEN_BOOK_OPTION,
    STR_RENAME_BOOK_OPTIONS,
    STR_OPEN_EBOOK,
    STR_INFO_EBOOK,
    STR_DELETE_EBOOK,
    STR_HELP_EBOOK,
    STR_SETTINGS_EBOOK,
    STR_FIND_EBOOK,
    STR_FIND_NEXT_EBOOK,
    STR_JUMP_EBOOK,
    STR_GOTO_BOOKMARK_EBOOK,
    STR_ADD_BOOKMARK_EBOOK,
    STR_RMV_BOOKMARK_EBOOK,
    STR_BOOK_INFO_EBOOK,
    STR_BOOK_SETTINGS_EBOOK,
    STR_CLOSE_EBOOK,
    STR_SRCH_CASE_EBOOK,
    STR_SRCH_CASEIN_EBOOK,
    STR_JMP_BEG_EBOOK,
    STR_JMP_MID_EBOOK,
    STR_JMP_END_EBOOK,
    STR_JMP_PERCENTAGE_EBOOK,
    STR_SETTINGS_FONT_STYLE,
    STR_SETTINGS_FONT_SIZE,
    STR_SETTINGS_SCROLL_BY,
    STR_SETTINGS_AUTO_SCROLL,
    STR_SETTINGS_AUTO_SCROLL_SPEED,
    STR_SETTINGS_FULL_SCREEN,
    STR_SETTINGS_ENCODING_FORMAT,
    STR_SETTINGS_FONT_STYLE_BOLD,
    STR_SETTINGS_FONT_STYLE_ITALIC,
    STR_SETTINGS_FONT_STYLE_NORMAL,
    STR_SETTINGS_FONT_SIZE_LARGE,
    STR_SETTINGS_FONT_SIZE_SMALL,
    STR_SETTINGS_FONT_SIZE_MEDIUM,
    STR_SETTINGS_SCROLL_BY_PAGE,
    STR_SETTINGS_SCROLL_BY_LINE,
    STR_SETTINGS_AUTO_SCROLL_ON,
    STR_SETTINGS_AUTO_SCROLL_OFF,
    STR_SETTINGS_FULL_SCREEN_ON,
    STR_SETTINGS_FULL_SCREEN_OFF,
    STR_SETTINGS_AUTO_SCROLL_SPEED_1,
    STR_SETTINGS_AUTO_SCROLL_SPEED_2,
    STR_SETTINGS_AUTO_SCROLL_SPEED_3,
    STR_SETTINGS_AUTO_SCROLL_SPEED_4,
    STR_SETTINGS_AUTO_SCROLL_SPEED_5,
    STR_EBOOK_BOOKMARK_ADDED,
    STR_EBOOK_DEFAULT_BOOKMARK,
    STR_DELETED,
    STR_MAX_BOOK_MARK,
    STR_EBOOK_TOUCH_SCREEN_HELP,	
    STR_DELETE_EBOOK_CONFIRM,
    STR_DELETE_BOOK_MARK,
    STR_BOOK_SHELF_REFRESHED,
    STR_DUPLICATE_BOOK_MARK,
    STR_WRONG_PERCENTAGE_VALUE,
    STR_FULL_SCREEN_OFF,
    STR_FULL_SCREEN_ON,
    STR_AUTO_SCROLL_ON,
    STR_AUTO_SCROLL_OFF,
    STR_SETTINGS_ENCODING_FORMAT_UCS2,
    STR_SETTINGS_ENCODING_FORMAT_UTF8,
    /* For File Manager */
    STR_FMGR_EBOOK_OPTION,
    STR_ADD_TO_BOOK_SHELF,
    STR_ERROR_OPENINIG_BOOK,
    STR_ADD_TO_EBOOK_FOLDER,
    STR_OPEN_BOOK_ERROR,
    STR_EBOOK_FORMAT_NOT_SUPPORTED,
    STR_EBOOK_SEARCH_UN_SUCESSFULL,
    STR_WAIT_STRING,
    STR_PERCENTAGE_SCREEN,
    STR_DELETE_ALL_EBOOK,
    STR_RESTORE_DEFAULT,
    STR_SUCESSFULL_RESTORE_DEFAULT,
    STR_UNSUCESSFULL_RESTORE_DEFAULT,
    STR_DELETE_ALL_EBOOK_CONFIRM,
    STR_RESTORE_DEFAULT_SETTINGS,
    STR_EBOOK_WAIT,
    STR_EBOOK_WAIT_FOR_MOVING_FILE,
    STR_CHANGE_CARD_TO_PHONE,
    STR_CHANGE_PHONE_TO_CARD,
    STR_MEMORY_TYPE_CHANGED,
    STR_NO_BOOK_MARK_PRESENT,
    STR_CONFIRM_SAVE_SETTINGS,
    STR_BOOK_MARK_NAME_IS_EMPTY,
    STR_EBOOK_INPUT_METHOD,
    STR_EBOOK_DONE,
    STR_BOOK_TOO_SMALL,
    STR_EBOOK_LIST_LSK_EDIT,
    STR_EBOOK_MEMORY_LESS,
    STR_INCOMPLETE_SEARCH_STRING,
    STR_EBOOK_BOOK_INFO_TITLE,
    STR_EBOOK_BOOK_INFO_SIZE,
    STR_EBOOK_BOOK_INFO_FORMAT,
#ifdef __MMI_CHSET_BIG5__
    STR_SETTINGS_ENCODING_FORMAT_BIG5,
#endif 

#ifdef __MMI_CHSET_GB2312__
    STR_SETTINGS_ENCODING_FORMAT_GB2312,

#endif /* __MMI_CHSET_GB2312__ */ 

#ifdef __MMI_CHSET_TURKISH_ISO__
    STR_SETTINGS_ENCODING_FORMAT_TURKISH_ISO,
#endif 

#ifdef __MMI_CHSET_TURKISH_WIN__
    STR_SETTINGS_ENCODING_FORMAT_TURKISH_WIN,
#endif 
#ifdef __MMI_CHSET_BALTIC_ISO__
    STR_SETTINGS_ENCODING_FORMAT_BALTIC_ISO,
#endif 
#ifdef __MMI_CHSET_BALTIC_WIN__
    STR_SETTINGS_ENCODING_FORMAT_BALTIC_WIN,
#endif 
#ifdef __MMI_CHSET_CEURO_ISO__

    STR_SETTINGS_ENCODING_FORMAT_CUEURO_ISO,
#endif /* __MMI_CHSET_CEURO_ISO__ */ 
#ifdef __MMI_CHSET_CEURO_WIN__
    STR_SETTINGS_ENCODING_FORMAT_CUEURO_WIN,
#endif 
#ifdef __MMI_CHSET_GREEK_ISO__
    STR_SETTINGS_ENCODING_FORMAT_GREEK_ISO,
#endif 
#ifdef __MMI_CHSET_GREEK_WIN__
    STR_SETTINGS_ENCODING_FORMAT_GREEK_WIN,
#endif 
#ifdef __MMI_CHSET_HEBREW_ISO__
    STR_SETTINGS_ENCODING_FORMAT_HEBREW_ISO,
#endif 
#ifdef __MMI_CHSET_LATIN_ISO__
    STR_SETTINGS_ENCODING_FORMAT_LATIN_ISO,
#endif 
#ifdef __MMI_CHSET_NORDIC_ISO__
    STR_SETTINGS_ENCODING_FORMAT_NORDIC_ISO,
#endif 
#ifdef __MMI_CHSET_SEURO_ISO__
    STR_SETTINGS_ENCODING_FORMAT_SEURO_ISO,

#endif /* __MMI_CHSET_SEURO_ISO__ */ 
#ifdef __MMI_CHSET_WESTERN_ISO__
    STR_SETTINGS_ENCODING_FORMAT_WESTERN_ISO,
#endif 
#ifdef __MMI_CHSET_WESTERN_WIN__
    STR_SETTINGS_ENCODING_FORMAT_WESTERN_WIN,
#endif 
#ifdef __MMI_CHSET_ARABIC_ISO__
    STR_SETTINGS_ENCODING_FORMAT_ARABIC_ISO,

#endif /* __MMI_CHSET_ARABIC_ISO__ */ 
#ifdef __MMI_CHSET_ARABIC_WIN__
    STR_SETTINGS_ENCODING_FORMAT_ARABIC_WIN,

#endif /* __MMI_CHSET_ARABIC_WIN__ */ 
#ifdef __MMI_CHSET_HEBREW_WIN__
    STR_SETTINGS_ENCODING_FORMAT_HEBREW_WIN,
#endif 
    STR_USB_IS_PLUGGED_IN,
    STR_EBOOK_SEARCH_INVALID,
#ifdef __MMI_BPP_SUPPORT__
    STR_EBOOK_BPP_PRINT,
    STR_EBOOK_WAIT_FOR_BPP_ENCODING,
#endif /* __MMI_BPP_SUPPORT__ */ 
    STR_EBOOK_DELETE_INQUIRE,
    STR_SCR_EBOOK_TOTAL
} STRINGID_LIST_EBOOK;

typedef enum
{
    MAIN_MENU_EBOOK_ICON = EBOOK_BASE + 1,
    EBOOK_TITLE_IMAGEID,
    IMAGE_EBOOK_WAIT,
    IMG_SCR_EBOOK_TOTAL
} IMAGEID_LIST_EBOOK;
#endif /*_MMI_EBOOKRESDEF_H*/

