/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/**
 *	Copyright Notice
 *	?2002 - 2003, Pixtel Communications, Inc., 1489 43rd Ave. W.,
 *	Vancouver, B.C. V6M 4K8 Canada. All Rights Reserved.
 *  (It is illegal to remove this copyright notice from this software or any
 *  portion of it)
 */

/**************************************************************

	FILENAME	: Res_CallManagement.c

  	PURPOSE		: Populate Resource for CallManagement

	REMARKS		: nil

	AUTHOR		: Yogesh

	DATE		: August-16-2003

**************************************************************/
#include "MMI_features.h"
#include "MMIDataType.h"
#include "CustomCfg.h"


#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif

#include "CallmanagementIdResDef.h"

#if defined(__MMI_BT_SUPPORT__)
#include "ConnectivityResDef.h "
#endif

#if defined(__MMI_BG_SOUND_EFFECT__)
#include "BGSoundResDef.h"
#endif

#if defined(__MMI_UNIFIED_MESSAGE__)
#include "UnifiedMessageResDef.h"
#endif /* __MMI_UNIFIED_MESSAGE__ */

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"

/**************************************************************

	FUNCTION NAME		: PopulateCmRedialScrData()

  	PURPOSE				: To Initialize the resources for Redial screens

	INPUT PARAMETERS	: nil

	OUTPUT PARAMETERS	: nil

	RETURNS				: void

	REMARKS				: nil

**************************************************************/
void PopulateCmRedialScrData(void)
{

}

/**************************************************************

	FUNCTION NAME		: PopulateCmResData()

  	PURPOSE				: To Initialize the resources for the Incoming Call Management

	INPUT PARAMETERS	: nil

	OUTPUT PARAMETERS	: nil

	RETURNS				: void

	REMARKS				: This function sets up the handlers required for event flow and
	                      application management

**************************************************************/
void PopulateCmResData (void)
{
	/* Idle Incoming  Options Menu */

	ADD_APPLICATION_MENUITEM2((MITEM_OPT_PSEUDO,0,
		MITEM_INC_OPT_ANSWER,
		MITEM_INC_OPT_DEFLN,
#if defined(__MMI_BG_SOUND_EFFECT__)
		MENU_ID_BGSND_INC_OPT_EFFECT,
#endif
		MENU_ITEM_END,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));


	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_DEFLN,MITEM_OPT_PSEUDO,
							0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_DEFLN,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_ANSWER, MITEM_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_ANSWER,0));
#if defined(__MMI_BG_SOUND_EFFECT__)
	ADD_APPLICATION_MENUITEM((MENU_ID_BGSND_INC_OPT_EFFECT,MITEM_OPT_PSEUDO,
							0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_ID_BGSND_BG_SOUND, 0));
#endif

	/* Incoming Active Options Menu */

	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_PSEUDO,0,7,
		MITEM_INC_OPT_ANSWER,
		MITEM_INC_ACT_OPT_HOLD_ACT,
		MITEM_INC_ACT_OPT_END_ACT,
		MITEM_INC_OPT_DEFLN,
		MITEM_INC_ACT_OPT_MUTE,
		MITEM_INC_ACT_OPT_LOUDSP,
		MITEM2024_CM_DTMF,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_ANSWER, MITEM_INC_ACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_ANSWER,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_HOLD_ACT, MITEM_INC_ACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_HOLD_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_END_ACT, MITEM_INC_ACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_END_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_DEFLN,MITEM_INC_ACT_OPT_PSEUDO,
							0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_DEFLN,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_MUTE, MITEM_INC_ACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_MUTE,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_INC_ACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));

// MTK amanda add 1201
	ADD_APPLICATION_MENUITEM((MITEM_INC_WAP_OPT_PSEUDO,0,3,
		MITEM_INC_OPT_ANSWER,
		MITEM_INC_ACT_OPT_END_ACT,
		MITEM_INC_OPT_DEFLN,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_ANSWER, MITEM_INC_WAP_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_ANSWER,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_END_ACT, MITEM_INC_WAP_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_END_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_DEFLN,MITEM_INC_WAP_OPT_PSEUDO,
							0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_DEFLN,0));

	/* Incoming Hold Options Menu */

	ADD_APPLICATION_MENUITEM((MITEM_INC_HLD_OPT_PSEUDO,0,6,
				MITEM_INC_OPT_ANSWER,
				MITEM_INC_HLD_OPT_RTRV,
				MITEM_INC_HLD_OPT_END,
				MITEM_INC_OPT_DEFLN,
				MITEM_INC_ACT_OPT_LOUDSP,
				MITEM2024_CM_DTMF,
				SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_ANSWER, MITEM_INC_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_ANSWER,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_HLD_OPT_RTRV, MITEM_INC_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_HLD_OPT_RTRV,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_HLD_OPT_END, MITEM_INC_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_HLD_OPT_END,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_DEFLN,MITEM_INC_HLD_OPT_PSEUDO,
							0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_DEFLN,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_INC_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));


	/* Incoming Multiple Hold Options Menu */

	ADD_APPLICATION_MENUITEM((MITEM_INC_MHLD_OPT_PSEUDO,0,6,
				MITEM_INC_OPT_ANSWER,
				MITEM_INC_MHLD_OPT_RTRV,
				MITEM_INC_MHLD_OPT_END,
				MITEM_INC_OPT_DEFLN,
				MITEM_INC_ACT_OPT_LOUDSP,	
				MITEM2024_CM_DTMF,
				SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_ANSWER, MITEM_INC_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_ANSWER,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_MHLD_OPT_RTRV, MITEM_INC_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_MHLD_OPT_RTRV,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_MHLD_OPT_END, MITEM_INC_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_MHLD_OPT_END,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_DEFLN,MITEM_INC_MHLD_OPT_PSEUDO,
							0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_DEFLN,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_INC_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));

	/* Incoming 1 Active and 1 hold */
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_PSEUDO,0,10,
			MITEM_IAH_OPT_SWAP,
			MITEM_IAH_OPT_CONFER,
			MITEM_IAH_OPT_TRANSFER,
			MITEM_IAH_OPT_END_ACT,
			MITEM_IAH_OPT_END_HLD,
			MITEM_IAH_OPT_END_ALL,
			MITEM_INC_OPT_DEFLN,
			MITEM_INC_ACT_OPT_MUTE,
			MITEM_INC_ACT_OPT_LOUDSP,
			MITEM2024_CM_DTMF,
			SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_SWAP,MITEM_IAH_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_SWAP,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_CONFER,MITEM_IAH_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_CONFER,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_TRANSFER,MITEM_IAH_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_TRANSFER,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_ACT, MITEM_IAH_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_HLD, MITEM_IAH_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_HLD,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_ALL, MITEM_IAH_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_ALL,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_DEFLN,MITEM_IAH_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_DEFLN,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_MUTE, MITEM_IAH_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_MUTE,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_IAH_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));


	/* More than 1 Active 1 Hold and 1 Incoming */
	ADD_APPLICATION_MENUITEM((MITEM_IMAH_OPT_PSEUDO,0,10,
			MITEM_IAH_OPT_SWAP,
			MITEM_IAH_OPT_CONFER,
			MITEM_IAH_OPT_END_HLD,
			MITEM_IMA_OPT_END_ONE_ACT,
			// MTK amanda add 1129
			MITEM2019_CM_ALL_ACTIVE_END,
			MITEM_IAH_OPT_END_ALL,
			MITEM_INC_OPT_DEFLN,
			MITEM_INC_ACT_OPT_MUTE,
			MITEM_INC_ACT_OPT_LOUDSP,
			MITEM2024_CM_DTMF,
			SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_SWAP, MITEM_IMAH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_SWAP,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_CONFER, MITEM_IMAH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_CONFER,0));
	ADD_APPLICATION_MENUITEM((MITEM_IMAH_OPT_END_ONE_ACT, MITEM_IMAH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IMAH_OPT_END_ONE_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_HLD, MITEM_IMAH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_HLD,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_ALL, MITEM_IMAH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_ALL,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_DEFLN,MITEM_IMAH_OPT_PSEUDO,
							0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_DEFLN,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_MUTE, MITEM_IMAH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_MUTE,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_IMAH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));


	/* 1 Active Multiple Hold Incoming Options */
	ADD_APPLICATION_MENUITEM((MITEM_IAMH_OPT_PSEUDO,0,9,
			MITEM_IAH_OPT_SWAP,
			MITEM_IAH_OPT_CONFER,
			MITEM_IAH_OPT_END_ACT,
			MITEM_IAMH_ALL_HELD_END,
			MITEM_IAH_OPT_END_ALL,
			MITEM_INC_OPT_DEFLN,	
			MITEM_INC_ACT_OPT_MUTE,
			MITEM_INC_ACT_OPT_LOUDSP,
			MITEM2024_CM_DTMF,
			SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_SWAP, MITEM_IAMH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_SWAP,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_CONFER, MITEM_IAMH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_CONFER,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_ACT, MITEM_IAMH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAMH_ALL_HELD_END, MITEM_IAMH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAMH_ALL_HELD_END,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_ALL, MITEM_IAMH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_ALL,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_DEFLN,MITEM_IAMH_OPT_PSEUDO,
							0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_DEFLN,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_MUTE, MITEM_IAMH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_MUTE,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_IAMH_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));

	/* Multiple Active 1 Incoming Options */
	ADD_APPLICATION_MENUITEM((MITEM_IMA_OPT_PSEUDO,0,9,
				MITEM_INC_OPT_ANSWER,
				MITEM_IMA_OPT_HOLD_CONF,
				MITEM_IMA_OPT_SPLIT,
				MITEM_IMA_OPT_END_ONE_ACT,
				MITEM_IMA_OPT_END_ALL_ACT,
				MITEM_INC_OPT_DEFLN,
				MITEM_INC_ACT_OPT_MUTE,
				MITEM_INC_ACT_OPT_LOUDSP,
				MITEM2024_CM_DTMF,
				SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_ANSWER, MITEM_IMA_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_ANSWER,0));
	ADD_APPLICATION_MENUITEM((MITEM_IMA_OPT_HOLD_CONF, MITEM_IMA_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IMA_OPT_HOLD_CONF,0));
	ADD_APPLICATION_MENUITEM((MITEM_IMA_OPT_SPLIT, MITEM_IMA_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IMA_OPT_SPLIT,0));
	ADD_APPLICATION_MENUITEM((MITEM_IMA_OPT_END_ONE_ACT, MITEM_IMA_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IMA_OPT_END_ONE_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_IMA_OPT_END_ALL_ACT, MITEM_IMA_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IMA_OPT_END_ALL_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_OPT_DEFLN,MITEM_IMA_OPT_PSEUDO,
							0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_OPT_DEFLN,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_MUTE, MITEM_IMA_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_MUTE,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_IMA_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));
	//single active
	ADD_APPLICATION_MENUITEM((MITEM_CCBS_ACT_OPT_PSEUDO,0,6,
		MITEM_CCBS_OPT_DIAL,
		MITEM_INC_ACT_OPT_HOLD_ACT,
		MITEM_INC_ACT_OPT_END_ACT,
		MITEM_INC_ACT_OPT_MUTE,
		MITEM_INC_ACT_OPT_LOUDSP,
		MITEM2024_CM_DTMF,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_CCBS_OPT_DIAL, MITEM_CCBS_ACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_GLOBAL_DIAL,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_HOLD_ACT, MITEM_CCBS_ACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_HOLD_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_END_ACT, MITEM_CCBS_ACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_END_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_MUTE, MITEM_CCBS_ACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_MUTE,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_CCBS_ACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));

	//single held
	ADD_APPLICATION_MENUITEM((MITEM_CCBS_HLD_OPT_PSEUDO,0,6,
		MITEM_CCBS_OPT_DIAL,
		MITEM_INC_HLD_OPT_RTRV,
		MITEM_INC_HLD_OPT_END,
		MITEM_INC_ACT_OPT_MUTE,
		MITEM_INC_ACT_OPT_LOUDSP,
		MITEM2024_CM_DTMF,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_CCBS_OPT_DIAL, MITEM_CCBS_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_GLOBAL_DIAL,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_HLD_OPT_RTRV, MITEM_CCBS_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_HLD_OPT_RTRV,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_HLD_OPT_END, MITEM_CCBS_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_HLD_OPT_END,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_MUTE, MITEM_CCBS_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_MUTE,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_CCBS_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));

	//multiple active
	ADD_APPLICATION_MENUITEM((MITEM_CCBS_MACT_OPT_PSEUDO,0,8,
				MITEM_CCBS_OPT_DIAL,
				MITEM_IMA_OPT_HOLD_CONF,
				MITEM_IMA_OPT_SPLIT,
				MITEM_IMA_OPT_END_ONE_ACT,
				MITEM_IMA_OPT_END_ALL_ACT,
				MITEM_INC_ACT_OPT_MUTE,
				MITEM_INC_ACT_OPT_LOUDSP,
				MITEM2024_CM_DTMF,
				SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_CCBS_OPT_DIAL, MITEM_CCBS_MACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_GLOBAL_DIAL,0));
	ADD_APPLICATION_MENUITEM((MITEM_IMA_OPT_HOLD_CONF, MITEM_CCBS_MACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IMA_OPT_HOLD_CONF,0));
	ADD_APPLICATION_MENUITEM((MITEM_IMA_OPT_SPLIT, MITEM_CCBS_MACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IMA_OPT_SPLIT,0));
	ADD_APPLICATION_MENUITEM((MITEM_IMA_OPT_END_ONE_ACT, MITEM_CCBS_MACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IMA_OPT_END_ONE_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_IMA_OPT_END_ALL_ACT, MITEM_CCBS_MACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IMA_OPT_END_ALL_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_MUTE, MITEM_CCBS_MACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_MUTE,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_CCBS_MACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));


	//multiple hold
	ADD_APPLICATION_MENUITEM((MITEM_CCBS_MHLD_OPT_PSEUDO,0,5,
				MITEM_CCBS_OPT_DIAL,
				MITEM_INC_MHLD_OPT_RTRV,
				MITEM_INC_MHLD_OPT_END,
				MITEM_INC_ACT_OPT_LOUDSP,	
				MITEM2024_CM_DTMF,
				SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_CCBS_OPT_DIAL, MITEM_CCBS_MACT_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_GLOBAL_DIAL,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_MHLD_OPT_RTRV, MITEM_CCBS_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_MHLD_OPT_RTRV,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_MHLD_OPT_END, MITEM_CCBS_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_MHLD_OPT_END,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_CCBS_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));


	//single active single hold
	ADD_APPLICATION_MENUITEM((MITEM_CCBS_ACT_HLD_OPT_PSEUDO,0,9,
			MITEM_IAH_OPT_SWAP,
			MITEM_IAH_OPT_CONFER,
			MITEM_IAH_OPT_TRANSFER,
			MITEM_IAH_OPT_END_ACT,
			MITEM_IAH_OPT_END_HLD,
			MITEM_IAH_OPT_END_ALL,
			MITEM_INC_ACT_OPT_MUTE,
			MITEM_INC_ACT_OPT_LOUDSP,
			MITEM2024_CM_DTMF,
			SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_SWAP,MITEM_CCBS_ACT_HLD_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_SWAP,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_CONFER,MITEM_CCBS_ACT_HLD_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_CONFER,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_TRANSFER,MITEM_CCBS_ACT_HLD_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_TRANSFER,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_ACT, MITEM_CCBS_ACT_HLD_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_HLD, MITEM_CCBS_ACT_HLD_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_HLD,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_ALL, MITEM_CCBS_ACT_HLD_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_ALL,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_MUTE, MITEM_CCBS_ACT_HLD_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_MUTE,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_CCBS_ACT_HLD_OPT_PSEUDO,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));


	//multiple active single hold
	ADD_APPLICATION_MENUITEM((MITEM_CCBS_MACT_HLD_OPT_PSEUDO,0,8,
			MITEM_IAH_OPT_SWAP,
			MITEM_IAH_OPT_CONFER,
			MITEM_IAH_OPT_END_HLD,
			MITEM_IMAH_OPT_END_ONE_ACT,
			MITEM_IAH_OPT_END_ALL,
			MITEM_INC_ACT_OPT_MUTE,
			MITEM_INC_ACT_OPT_LOUDSP,
			MITEM2024_CM_DTMF,
			SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_SWAP, MITEM_CCBS_MACT_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_SWAP,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_CONFER, MITEM_CCBS_MACT_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_CONFER,0));
	ADD_APPLICATION_MENUITEM((MITEM_IMAH_OPT_END_ONE_ACT, MITEM_CCBS_MACT_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IMAH_OPT_END_ONE_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_HLD, MITEM_CCBS_MACT_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_HLD,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_ALL, MITEM_CCBS_MACT_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_ALL,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_MUTE, MITEM_CCBS_MACT_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_MUTE,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_CCBS_MACT_HLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));


	//single active multiple hold
	ADD_APPLICATION_MENUITEM((MITEM_CCBS_ACT_MHLD_OPT_PSEUDO,0,8,
			MITEM_IAH_OPT_SWAP,
			MITEM_IAH_OPT_CONFER,
			MITEM_IAH_OPT_END_ACT,
			MITEM_IAMH_ALL_HELD_END,
			MITEM_IAH_OPT_END_ALL,
			MITEM_INC_ACT_OPT_MUTE,
			MITEM_INC_ACT_OPT_LOUDSP,
			MITEM2024_CM_DTMF,
			SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_SWAP, MITEM_CCBS_ACT_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_SWAP,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_CONFER, MITEM_CCBS_ACT_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_CONFER,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_ACT, MITEM_CCBS_ACT_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_ACT,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAMH_ALL_HELD_END, MITEM_CCBS_ACT_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAMH_ALL_HELD_END,0));
	ADD_APPLICATION_MENUITEM((MITEM_IAH_OPT_END_ALL, MITEM_CCBS_ACT_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_IAH_OPT_END_ALL,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_MUTE, MITEM_CCBS_ACT_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_MUTE,0));
	ADD_APPLICATION_MENUITEM((MITEM_INC_ACT_OPT_LOUDSP, MITEM_CCBS_ACT_MHLD_OPT_PSEUDO,
							  0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_INC_ACT_OPT_LOUDSP,0));

//String Start
	ADD_APPLICATION_STRING2(STR_MITEM_INC_OPT_DEFLN	,"Deflect","String for option Call Deflection");
	ADD_APPLICATION_STRING2(STR_MITEM_INC_OPT_ANSWER,"Answer","String for option to Answer Call");
	
	ADD_APPLICATION_STRING2(STR_MITEM_INC_ACT_OPT_END_ACT,"End Active","String for option End Active");
	ADD_APPLICATION_STRING2(STR_MITEM_INC_ACT_OPT_HOLD_ACT,"Hold Active","String for option Hold");
	ADD_APPLICATION_STRING2(STR_MITEM_INC_ACT_OPT_MUTE,"Mute/Unmute","String for option mute");
#ifdef __MMI_VOICE_MEMO__
	ADD_APPLICATION_STRING2(STR_MITEM_INC_ACT_OPT_VOICE_MEMO,"Voice Memo","String for option Voice memo");
#endif
#ifdef __MMI_SOUND_RECORDER__
	ADD_APPLICATION_STRING2(STR_MITEM_INC_ACT_OPT_SOUND_RECORDER,"Sound Recorder","String for option Sound Recorder");
#endif
	ADD_APPLICATION_STRING2(STR_MITEM_INC_ACT_OPT_LOUDSP,"H-Free/H-Held","String for option loudspeaker");
	ADD_APPLICATION_STRING2(STR_MITEM_IAMH_ALL_HELD_END , "End All Held","String for End All Held Calls option");

	ADD_APPLICATION_STRING2(STR_MITEM_INC_HLD_OPT_RTRV	,"Retrieve","String for option Retrieve Call");
	ADD_APPLICATION_STRING2(STR_MITEM_INC_HLD_OPT_END	,"End","String for option End Held Call");

//	ADD_APPLICATION_STRING2(STR_INC_MHLD_OPT_PSEUDO	,"Incoming Call","Title String for Screen for Incoming Multiple Hold Options");
	ADD_APPLICATION_STRING2(STR_MITEM_INC_MHLD_OPT_RTRV	,"Retrieve All","String for option Retrieve Call");
	ADD_APPLICATION_STRING2(STR_MITEM_INC_MHLD_OPT_END	,"End All","String for option End Held Call");

	ADD_APPLICATION_STRING2(STR_MITEM_IAH_OPT_SWAP , "Swap","String for Swap Calls option");
	ADD_APPLICATION_STRING2(STR_MITEM_IAH_OPT_CONFER , "Conference","String for starting conference Call option");
	ADD_APPLICATION_STRING2(STR_MITEM_IAH_OPT_TRANSFER , "Transfer","String for Call Transfer option");
	ADD_APPLICATION_STRING2(STR_MITEM_IAH_OPT_END_ACT	,"End Active","String for option End Active");
	ADD_APPLICATION_STRING2(STR_MITEM_IAH_OPT_END_HLD	,"End Held","String for option End Held");
	ADD_APPLICATION_STRING2(STR_MITEM_IAH_OPT_END_ALL	,"End All","String for option End All");

	  
	ADD_APPLICATION_STRING2(STR_MITEM_IMA_OPT_END_ALL_ACT	,"End All","String for End All Active");	
	
	ADD_APPLICATION_STRING2(STR_MITEM_IMA_OPT_END_ONE_ACT	,"End Single","String for End One Active");
	ADD_APPLICATION_STRING2(STR_MITEM_IMA_OPT_HOLD_CONF	,"Hold All","String for End One Active");
	ADD_APPLICATION_STRING2(STR_MITEM_IMA_OPT_SPLIT	,"Split","String for Split");

	ADD_APPLICATION_STRING2(STR_MITEM_IMAH_OPT_END_ONE_ACT	,"End All Active","String for End All Active");

	ADD_APPLICATION_STRING2(INC_SCR_RSK_MUTE_STR,"Silence","RSK String For Silence");
	ADD_APPLICATION_STRING2(INC_SCR_RSK_REJECT_STR	,"Reject","RSK String For Reject");

	ADD_APPLICATION_STRING2(INC_SCR_RSK_DROP_STR	,"Reject","RSK String For Drop");

	ADD_APPLICATION_STRING2(INC_SCR_NFY_STR	,"Incoming Call","String for option Incoming Call");

	/*******CCBS*******/
	ADD_APPLICATION_STRING2(INC_SCR_NFY_CCBS_STR	,"CCBS Invoke","String for CCBS Invoke");

	// Screen to show choice of Active CAlls to end
	ADD_APPLICATION_STRING2(TITLE_STR_ACT_LIST	,"Current Calls","String for Title Screen For Active Call List");
	// Screen to show Call Deflect
	ADD_APPLICATION_STRING2(CALL_DEFLECT_SEARCH_LSK	,"Search","LSK Search String");

	// Screen to show choice of Held CAlls to end
	ADD_APPLICATION_STRING2(HCL_LSK_STR	,"End","LSK String");
	ADD_APPLICATION_STRING2(TITLE_STR_HLD_LIST	,"Current Calls","String for Title Screen For Held Call List");

	//CCBS
	ADD_APPLICATION_STRING2(STR_NFY_CCBS,"CCBS Available!\nWant to Activate?","String for CCBS Message");
	ADD_APPLICATION_STRING2(CCBS_ACTIVATED_STR, "Activated","CCBS activated Screen");

   // MTK amanda add 1229
   // Redial
   ADD_APPLICATION_STRING2(STR_CM_REDIAL, "Redialing:", "Redial String");
   ADD_APPLICATION_STRING2(STR_CM_REDIAL_TIMES, "time(s)\n", "Number of times");
   ADD_APPLICATION_STRING2(STR_CM_REDIAL_NEXT_ATTEMPT, "Next Attempt in", "Next attempt reminder");
   ADD_APPLICATION_STRING2(STR_CM_REDIAL_SEC, "sec.", "Second");
   ADD_APPLICATION_STRING2(STR_CM_REDIAL_MIN, "min.", "Minute");
   
	/*Error Strings*/
	ADD_APPLICATION_STRING2(INC_SCR_MRK_TITLE	,"Current Calls","Title Screen Marker String");
	ADD_APPLICATION_STRING2(INC_MRK_ERR_STR	,"Error - History is not Coherent","Error String for marker screen");
	ADD_APPLICATION_STRING2(INC_SCR_RSK_STR	,"Reject","RSK String");
//	ADD_APPLICATION_STRING2(ERROR_USER_BUSY					,"User Busy","String for User Busy");
	ADD_APPLICATION_STRING2(ERROR_INVALID_COMMAND			,"Invalid Command","String for Invalid Command");
	ADD_APPLICATION_STRING2(ERROR_FDN_FAIL			,"Fixed Dial Numbers Only","String for FDN Fail");
//	ADD_APPLICATION_STRING2(INCOMING_ERR_RSK_STR			,"Ok","RSK Error String");
	ADD_APPLICATION_STRING2(ERROR_USSD_ABORTED, "Aborted", "USSD Aborted for Incoming Call");
	ADD_APPLICATION_STRING2(INCOMING_UNKNOWN_ERROR		,"Unknown Error","String for Unknown Error");
	ADD_APPLICATION_STRING2(INCOMING_DEFAULT_ERROR		,"Unable to Connect!","String for Default Error");

	ADD_APPLICATION_STRING2(ERROR_UNRECOGNIZED_NUMBER,"Unrecognized Number!","Error String");
	ADD_APPLICATION_STRING2(ERROR_FAIL,"Fail!","Error String");
	ADD_APPLICATION_STRING2(ERROR_NETWORK_FAIL,"Network Fail!","Error String");
	ADD_APPLICATION_STRING2(ERROR_NETWORK_NOT_AVAILABLE,"Network Not Available!!","Error String");
	ADD_APPLICATION_STRING2(ERROR_BUSY_NETWORK,"Network Busy!!","Error String");	
	ADD_APPLICATION_STRING2(ERROR_BARRED_CALL,"Barred Call!","Error String");
	ADD_APPLICATION_STRING2(ERROR_USER_BUSY,"User Busy!","Error String");
	ADD_APPLICATION_STRING2(ERROR_NOT_RESPONDING,"Not Responding!","Error String");
	ADD_APPLICATION_STRING2(ERROR_NO_ANSWER,"No Answer!","Error String");
	ADD_APPLICATION_STRING2(ERROR_ACM_EXCEEDED,"ACM Exceeded!","Error String");
	ADD_APPLICATION_STRING2(ERROR_UNAVAILABLE,"Unavailable!","Error String");
	ADD_APPLICATION_STRING2(ERROR_UNEXPECTED_ERROR,"Unexpected Error!","Error String");
	ADD_APPLICATION_STRING2(ERROR_IMSI_UNKNOWN,"IMSI Unknown!","Error String");
	
	ADD_APPLICATION_STRING2(STR_CALL_ABORTED,"Call Aborted","String - Call Aborted");
	ADD_APPLICATION_STRING2(STR_CALL_ENDED,"Call Ended","String - Call Ended");
	ADD_APPLICATION_STRING2(STR_DTMF_CONFIRMATION,"Send DTMF?\n","String for DTMF confirmation");

	ADD_APPLICATION_STRING2(ERROR_IMEI_ERROR,"IMEI Error!","Error String");
	ADD_APPLICATION_STRING2(ERROR_GPRS_NOT_ALLOWED,"GPRS Not Allowed!","Error String");
	ADD_APPLICATION_STRING2(ERROR_MT_DATA_CALL,"Connect Terminal First!","Error String");	
	ADD_APPLICATION_STRING2(ERROR_NETWORK_NOT_ALLOWED,"Check Operator Services!","Error String");
	ADD_APPLICATION_STRING2(ERROR_COMMAND_NOT_SUPPORTED,"Command Not Supported!","Error String");
	ADD_APPLICATION_STRING2(ERROR_DATA_ERROR,"Data Error!","Error String");
	ADD_APPLICATION_STRING2(ERROR_MESSAGE_TYPE_ERROR,"Message Type Error!","Error String");
	ADD_APPLICATION_STRING2(ERROR_ACCESS_FAIL,"Access Fail!","Error String");
	ADD_APPLICATION_STRING2(ERROR_TIMER_EXPIRED,"Timer Expired!","Error String");
	
	/* By Mick 2006/12/26*/
	ADD_APPLICATION_STRING2(STR_ID_CALL_IS_FORWARDED,"Call Is Forwarded","Call Is Forwarded");
	ADD_APPLICATION_STRING2(STR_ID_CALL_IS_FORWARDED_CALL,"It Is A Forwarded Call","It Is Forwarded Call");
	
	/* Missed call info */
	//ADD_APPLICATION_STRING2(STR_MISSED_CALL,"Missed Call!","Title String for Screen for one Missed Call");
	//ADD_APPLICATION_STRING2(STR_MISSED_CALLS,"Missed Calls!","Title String for Screen for multiple Missed Calls");
	ADD_APPLICATION_STRING2(STR_UNKNOWN_CALLER,"Unknown Caller\0","String to display in case number is not available");
	
	//ADD_APPLICATION_STRING2(MISSED_LSK_STR,"Read","LSK String");

	/* Notify Screen Macros */
	ADD_APPLICATION_STRING2(TITLE_SCR_NFY,"Notification","String for Notification Screen");
	ADD_APPLICATION_STRING2(STR_TITLE_SCR_USSN_IND,"USSN","Title String for USSN Notification Screen");
	ADD_APPLICATION_STRING2(STR_TITLE_SCR_USSN_MSG,"Information","Title String for USSN Msg Display");
	ADD_APPLICATION_STRING2(STR_TITLE_SCR_USSD_MSG,"Information","Title String for USSD Msg Display");
	ADD_APPLICATION_STRING2(STR_MSG_USSN_IND,"USSN message received, read or not?","Title String for Notification Screen");

	ADD_APPLICATION_STRING2(STR_TITLE_SCR_USSR_IND,"USSR","Title String for USSR Notification Screen");
	ADD_APPLICATION_STRING2(STR_TITLE_SCR_USSR_MSG,"Information","Title String for USSR Msg Display");
	ADD_APPLICATION_STRING2(STR_TITLE_SCR_USSR_EDIT_MSG,"USSR-Edit","Title String for USSR Msg Edit");

	ADD_APPLICATION_STRING2(STR_NFY_CALL_FWDNG_CONDITIONAL,"Call Forwarding On Conditional","String for Call Forwarding Active Conditional");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_FWDNG_UNCONDITIONAL,"Call Forwarding On Unconditional","String for Call Forwarding Active Unconditional");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_FWDED,"Call Forwarded","String for Call Forwarded");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_FWDED_UNCONDITIONAL,"Call Forwarded Unconditional","String for Call Forwarded Unconditional");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_FWDED_CONDITIONAL,"Call Forwarded Conditional","String for Call Forwarded Conditional");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_BUSY_FORWARDED,"Call Busy Forwarded","String for Call Busy Forwarded");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_FWDED_NOREPLY,"Call Forwarded on Not Reply","String for Call Forwarded on No reply");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_FWDED_NOT_REACHABLE,"Call Forwarded on Not Reachable","String for Call Forwarded on Not Reachable");


	ADD_APPLICATION_STRING2(STR_NFY_CALL_ALL_BARRED,"All Calls Barred","String for Call Barring");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_ALL_OUTGOING_BARRED,"Outgoing Call Barred","String for Outgoing Call Barring");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_ALL_INCOMING_BARRED,"Incoming Call Barred","String for Incoming Call Barring");

	ADD_APPLICATION_STRING2(STR_NFY_CALL_WTG,"Waiting Call","String for Call Waiting");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_HLD,"Call Held","String for Call Held");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_RTVD,"Call Retrieved","String for Call Retrieved");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_SWAP,"Call Swapped","String for Call Swapped");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_CONF,"Conference Call","String for Conference Call");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_SPLIT,"Call Split","String for Call Split");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_CUG,"Closed User Group","String for Closed User Group");
	ADD_APPLICATION_STRING2(STR_NFY_CALL_CTFAC,"Call Transfer Active","String for Call Transfer Active");

//Image Start

	ADD_APPLICATION_IMAGE2(ACT_LIST_TITLE_ICN,	CUST_IMG_BASE_PATH"\\\\EmptyImage.bmp","Active Call List Title Icon");

	ADD_APPLICATION_IMAGE2(IMAGE_CCBS_ACTIVATED,CUST_IMG_PATH"\\\\MainLCD\\\\Warningpage\\\\PopUpPage\\\\PP_ACT"__MMI_RES_TYPE_POPUP_SCREEN__,"CCBS activated");
	ADD_APPLICATION_IMAGE2(IMG_CM_STATE_SINGLE_ACTIVE	,	CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Outgoing\\\\CL_SACT.GIF","Icon for Call Connected");
	ADD_APPLICATION_IMAGE2(IMG_CM_STATE_SINGLE_HOLD	,	CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Outgoing\\\\CL_SHOLD.GIF","Icon for Held Call");
	// Start by Julia: Drop call refinement
	ADD_APPLICATION_IMAGE2(IMG_CM_STATE_SINGLE_DISCONNECTING, CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Outgoing\\\\CL_ENDCALL.BMP", "Icon for Disconnecting Call");
	// End by Julia
	ADD_APPLICATION_IMAGE2(IMG_CM_STATE_ACTIVE	,	CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Outgoing\\\\CL_ACT.BMP","Icon for Call Connected");
	ADD_APPLICATION_IMAGE2(IMG_CM_STATE_HOLD	,	CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Outgoing\\\\CL_HOLD.BMP","Icon for Held Call");
	// Start by Julia: Drop call refinement
	ADD_APPLICATION_IMAGE2(IMG_CM_STATE_DISCONNECTING, CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Outgoing\\\\CL_ENDCALL.BMP", "Icon for Disconnecting Call");
	// End by Julia
	ADD_APPLICATION_IMAGE2(IMG_ICN_TEMP	,	CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Incoming\\\\CL_incom.gif","Temporary Icon");
	ADD_APPLICATION_IMAGE2(IMG_FAX_CALL_CONNECT	,	CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Outgoing\\\\CL_FAX.GIF","Icon for fax Call Connected");
	ADD_APPLICATION_IMAGE2(IMG_DATA_CALL_CONNECT	,	CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Outgoing\\\\CL_MOD.GIF","Icon for data Call Connected");
	/* Notify Screen Macros */
	
	PopulateCmOutResData();
	PopulateCmRedialScrData();
#ifdef __CTM_SUPPORT__	
	PopulateCTMResourceData();
#endif	
}

/**************************************************************

	FUNCTION NAME		: PopulateCmOutResData()

  	PURPOSE				: To Initialize the resources for the Outgoing Call Management

	INPUT PARAMETERS	: nil

	OUTPUT PARAMETERS	: nil

	RETURNS				: void

	REMARKS				: This function generates the resources required for the
						  outgoingcall screen,Active screen and for there options menuitems.

**************************************************************/
void PopulateCmOutResData(void)
{

   ADD_APPLICATION_MENUITEM((MITEM2001_CM_SINGLE_DATA_LSKOPTIONS,0,3,
		MITEM2011_CM_END,
		MITEM2031_CM_PBOOK,
		MITEM2032_CM_SMS,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1002_LSK));


ADD_APPLICATION_MENUITEM2((MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,0,
		MITEM2010_CM_ACTIVE_HOLD,
		MITEM2011_CM_END,
		MITEM2021_CM_NEWCALL,
		MITEM2031_CM_PBOOK,
		MITEM2032_CM_SMS,
#ifdef __MMI_VOICE_MEMO__
		MITEM2022_CM_VOICE_MEMO,
#endif		
#ifdef __MMI_SOUND_RECORDER__
		MITEM2026_CM_SOUND_RECORDER,
#endif		
		MITEM2020_CM_MUTE,		
		MITEM2024_CM_DTMF,
#if defined(__MMI_BG_SOUND_EFFECT__)
		MENU_ID_BGSND_CM_OPT_EFFECT,
#endif		
#if defined(__MMI_BT_SUPPORT__)
	/*************************************************/
	/** Notice!!! The voice transfer menu item      **/
	/**  should be the last one in the option menu  **/
	/*************************************************/
		MITEM_CM_BT_CONNECT_LAST_HEADSET, /* Configure Default Headset */
		MITEM_CM_BT_SETPATH,
#endif
#ifdef __CTM_SUPPORT__		
		MITEM2027_CM_CTM,
#endif		
		MENU_ITEM_END,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1002_LSK));

	/**************************************************
	Options for Hold 
	**************************************************/

		ADD_APPLICATION_MENUITEM((MITEM2002_CM_SINGLE_HOLD_LSKOPTIONS,0,
		6,
		MITEM2012_CM_HELD_RETRIEVE,
		MITEM2011_CM_END,
		MITEM2021_CM_NEWCALL,
		MITEM2031_CM_PBOOK,
		MITEM2032_CM_SMS,
		MITEM2024_CM_DTMF,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1002_LSK));

	ADD_APPLICATION_MENUITEM2((MITEM2003_CM_S_ACTIVE_S_HOLD_LSKOPTIONS,0,
		MITEM2014_CM_CALL_SWAP,	
		MITEM2015_CM_CALL_CONFER,
		MITEM2017_CM_CALL_TRANSFER,	
		MITEM2011_CM_END_SINGLE,
		MITEM2016_CM_ALL_CALL_END,
		MITEM2031_CM_PBOOK,	
		MITEM2032_CM_SMS,
#ifdef __MMI_VOICE_MEMO__
		MITEM2022_CM_VOICE_MEMO,
#endif		
#ifdef __MMI_SOUND_RECORDER__
		MITEM2026_CM_SOUND_RECORDER,
#endif		
		MITEM2020_CM_MUTE,		
		MITEM2024_CM_DTMF,
#if defined(__MMI_BG_SOUND_EFFECT__)
		MENU_ID_BGSND_CM_OPT_EFFECT,
#endif		
#if defined(__MMI_BT_SUPPORT__)
	/*************************************************/
	/** Notice!!! The voice transfer menu item      **/
	/**  should be the last one in the option menu  **/
	/*************************************************/
		MITEM_CM_BT_CONNECT_LAST_HEADSET, /* Configure Default Headset */
		MITEM_CM_BT_SETPATH,
#endif
#ifdef __CTM_SUPPORT__		
		MITEM2027_CM_CTM,
#endif		
		MENU_ITEM_END,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1002_LSK));


	ADD_APPLICATION_MENUITEM2((MITEM2004_CM_M_ACTIVE_LSKOPTIONS,0,
		MITEM2018_CM_CALL_SPLIT,
		MITEM2011_CM_END_SINGLE,
		MITEM2010_CM_M_ACTIVE_HOLD,	
		MITEM2011_CM_END_ALL,
		MITEM2021_CM_NEWCALL,
		MITEM2031_CM_PBOOK,	
		MITEM2032_CM_SMS,
#ifdef __MMI_VOICE_MEMO__
		MITEM2022_CM_VOICE_MEMO,
#endif		
#ifdef __MMI_SOUND_RECORDER__
		MITEM2026_CM_SOUND_RECORDER,
#endif		
		MITEM2020_CM_MUTE,
		MITEM2024_CM_DTMF,
#if defined(__MMI_BG_SOUND_EFFECT__)
		MENU_ID_BGSND_CM_OPT_EFFECT,
#endif		
#if defined(__MMI_BT_SUPPORT__)
	/*************************************************/
	/** Notice!!! The voice transfer menu item      **/
	/**  should be the last one in the option menu  **/
	/*************************************************/
		MITEM_CM_BT_CONNECT_LAST_HEADSET, /* Configure Default Headset */
		MITEM_CM_BT_SETPATH,
#endif
#ifdef __CTM_SUPPORT__		
		MITEM2027_CM_CTM,
#endif		
		MENU_ITEM_END,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1002_LSK));

   	ADD_APPLICATION_MENUITEM((MITEM2005_CM_M_HOLD_LSKOPTIONS,0,
		6,
		MITEM2012_CM_M_HELD_RETRIEVE,
		MITEM2011_CM_END_ALL,
		MITEM2021_CM_NEWCALL,
		MITEM2031_CM_PBOOK,	
		MITEM2032_CM_SMS,
		MITEM2024_CM_DTMF,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1002_LSK));
		
	ADD_APPLICATION_MENUITEM2((MITEM2006_CM_M_ACTIVE_S_HOLD_LSKOPTIONS,0,
		MITEM2014_CM_CALL_SWAP,	
		MITEM2015_CM_CALL_CONFER,
		MITEM2011_CM_END_SINGLE,
		MITEM2019_CM_ALL_ACTIVE_END,
		MITEM2016_CM_ALL_CALL_END,
		MITEM2031_CM_PBOOK,
		MITEM2032_CM_SMS,
#ifdef __MMI_VOICE_MEMO__
		MITEM2022_CM_VOICE_MEMO,
#endif		
#ifdef __MMI_SOUND_RECORDER__
		MITEM2026_CM_SOUND_RECORDER,
#endif		
		MITEM2020_CM_MUTE,
                MITEM2024_CM_DTMF,
#if defined(__MMI_BG_SOUND_EFFECT__)
		MENU_ID_BGSND_CM_OPT_EFFECT,
#endif
#if defined(__MMI_BT_SUPPORT__)
	/*************************************************/
	/** Notice!!! The voice transfer menu item      **/
	/**  should be the last one in the option menu  **/
	/*************************************************/
		MITEM_CM_BT_CONNECT_LAST_HEADSET, /* Configure Default Headset */
		MITEM_CM_BT_SETPATH,
#endif
#ifdef __CTM_SUPPORT__		
		MITEM2027_CM_CTM,
#endif		
		MENU_ITEM_END,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1002_LSK));
			
	ADD_APPLICATION_MENUITEM2((MITEM2007_CM_S_ACTIVE_M_HOLD_LSKOPTIONS,0,
		MITEM2014_CM_CALL_SWAP,	
		MITEM2015_CM_CALL_CONFER,
		MITEM2011_CM_S_ACTIVE_END,
		MITEM2020_CM_ALL_HELD_END,
		MITEM2016_CM_ALL_CALL_END,	
		MITEM2031_CM_PBOOK,	
		MITEM2032_CM_SMS,
#ifdef __MMI_VOICE_MEMO__
		MITEM2022_CM_VOICE_MEMO,
#endif		
#ifdef __MMI_SOUND_RECORDER__
		MITEM2026_CM_SOUND_RECORDER,
#endif		
		MITEM2020_CM_MUTE,
                MITEM2024_CM_DTMF,
#if defined(__MMI_BG_SOUND_EFFECT__)
		MENU_ID_BGSND_CM_OPT_EFFECT,
#endif		
#if defined(__MMI_BT_SUPPORT__)
	/*************************************************/
	/** Notice!!! The voice transfer menu item      **/
	/**  should be the last one in the option menu  **/
	/*************************************************/
		MITEM_CM_BT_CONNECT_LAST_HEADSET, /* Configure Default Headset */
		MITEM_CM_BT_SETPATH,
#endif
#ifdef __CTM_SUPPORT__		
		MITEM2027_CM_CTM,
#endif		
		MENU_ITEM_END,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1002_LSK));

	/**************************************************
		Call Hold, Incoming Waiting For answer
	**************************************************/	

	ADD_APPLICATION_MENUITEM((MITEM2008_CM_WAIT_S_HOLD_LSKOPTIONS,0,3,
		MITEM2017_CM_CALL_TRANSFER,
		MITEM2050_CM_END_HELD_ENDALL_HELD,
		MITEM2016_CM_ALL_CALL_END,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1001_LSK));

   // MTK amanda add 1222
   ADD_APPLICATION_MENUITEM((MITEM2008_CM_WAIT_M_HOLD_LSKOPTIONS,0,2,
		MITEM2050_CM_END_HELD_ENDALL_HELD,
		MITEM2016_CM_ALL_CALL_END,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1001_LSK));

	ADD_APPLICATION_MENUITEM((MITEM2008_CM_INC_S_HOLD_LSKOPTIONS,0,5,
		MITEM2017_CM_CALL_TRANSFER,
		MITEM2050_CM_END_HELD_ENDALL_HELD,
		MITEM2016_CM_ALL_CALL_END,
		MITEM_OUTGOING_REJECT,
		MITEM2011_CM_INC_END_SINGLE,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1001_LSK));

   // MTK amanda add 1222
   ADD_APPLICATION_MENUITEM((MITEM2008_CM_INC_M_HOLD_LSKOPTIONS,0,4,
		MITEM2050_CM_END_HELD_ENDALL_HELD,
		MITEM2016_CM_ALL_CALL_END,
		MITEM_OUTGOING_REJECT,
		MITEM2011_CM_INC_END_SINGLE,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1001_LSK));

	//For Call Transfer Not Enabled
/*	ADD_APPLICATION_MENUITEM((MITEM2008_CM_WAIT_S_HOLD_NO_CT_LSKOPTIONS,0,2,
		MITEM2050_CM_END_HELD_ENDALL_HELD,
		MITEM2016_CM_ALL_CALL_END,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_GLOBAL_OPTIONS,IMG_SCR1001_LSK));
*/

	/**************************************************
		Call Active, Outgoing Waiting For answer
	**************************************************/	
	
	ADD_APPLICATION_MENUITEM((MITEM2008_CM_WAIT_ACT_LSKOPTIONS,0,2,
		MITEM2017_CM_CALL_TRANSFER,
		MITEM2016_CM_ALL_CALL_END,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1001_LSK));

   // MTK amanda add 1222
	ADD_APPLICATION_MENUITEM((MITEM2008_CM_WAIT_MACT_LSKOPTIONS,0,1,
		MITEM2016_CM_ALL_CALL_END,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1001_LSK));

	ADD_APPLICATION_MENUITEM((MITEM2008_CM_INC_ACT_LSKOPTIONS,0,4,
		MITEM2017_CM_CALL_TRANSFER,
		MITEM2016_CM_ALL_CALL_END,
		MITEM_OUTGOING_REJECT,
		MITEM2011_CM_INC_END_SINGLE,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1001_LSK));

	ADD_APPLICATION_MENUITEM((MITEM2008_CM_INC_LSKOPTIONS,0,2,
		MITEM2016_CM_ALL_CALL_END,
		MITEM_OUTGOING_REJECT,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1001_LSK));

   // MTK amanda add 1222
   ADD_APPLICATION_MENUITEM((MITEM2008_CM_INC_MACT_LSKOPTIONS,0,3,
		MITEM2016_CM_ALL_CALL_END,
		MITEM_OUTGOING_REJECT,
		MITEM2011_CM_INC_END_SINGLE,
		SHOW,NONMOVEABLE|INSERTABLE,DISP_LIST,STR_SCR1002_CAPTION,IMG_SCR1001_LSK));
   
	ADD_APPLICATION_MENUITEM((MITEM2050_CM_END_HELD_ENDALL_HELD,MITEM2008_CM_WAIT_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2050_CM_END_HELD_ENDALL_HELD,IMG_MITEM2050_CM_END_HELD_ENDALL_HELD));

	ADD_APPLICATION_MENUITEM((MITEM2010_CM_ACTIVE_HOLD,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2010_CM_ACTIVE_HOLD,IMG_MITEM2010_CM_ACTIVE_HOLD));

	ADD_APPLICATION_MENUITEM((MITEM2010_CM_M_ACTIVE_HOLD,MITEM2004_CM_M_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2010_CM_M_ACTIVE_HOLD,IMG_MITEM2010_CM_M_ACTIVE_HOLD));

	ADD_APPLICATION_MENUITEM((MITEM2011_CM_S_ACTIVE_END,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2011_CM_S_ACTIVE_END,IMG_MITEM2011_CM_S_ACTIVE_END));

	ADD_APPLICATION_MENUITEM((MITEM2011_CM_END,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2011_CM_END,IMG_MITEM2011_CM_END));

	ADD_APPLICATION_MENUITEM((MITEM2011_CM_END_ALL,MITEM2004_CM_M_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2011_CM_END_ALL,IMG_MITEM2011_CM_END_ALL));

	ADD_APPLICATION_MENUITEM((MITEM2011_CM_S_ACTIVE_END_RETRIEVE,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2011_CM_S_ACTIVE_END_RETRIEVE,IMG_MITEM2011_CM_S_ACTIVE_END_RETRIEVE));

	ADD_APPLICATION_MENUITEM((MITEM2012_CM_HELD_RETRIEVE,MITEM2002_CM_SINGLE_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2012_CM_HELD_RETRIEVE,IMG_MITEM2012_CM_HELD_RETRIEVE));
		
	ADD_APPLICATION_MENUITEM((MITEM2012_CM_M_HELD_RETRIEVE,MITEM2005_CM_M_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2012_CM_M_HELD_RETRIEVE,IMG_MITEM2012_CM_M_HELD_RETRIEVE));

	ADD_APPLICATION_MENUITEM((MITEM2013_CM_S_HELD_END,MITEM2002_CM_SINGLE_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2013_CM_S_HELD_END,IMG_MITEM2013_CM_S_HELD_END));

	ADD_APPLICATION_MENUITEM((MITEM2014_CM_CALL_SWAP,MITEM2003_CM_S_ACTIVE_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2014_CM_CALL_SWAP,IMG_MITEM2014_CM_CALL_SWAP));

	ADD_APPLICATION_MENUITEM((MITEM2015_CM_CALL_CONFER,MITEM2003_CM_S_ACTIVE_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2015_CM_CALL_CONFER,IMG_MITEM2015_CM_CALL_CONFER));

	ADD_APPLICATION_MENUITEM((MITEM2016_CM_ALL_CALL_END,MITEM2003_CM_S_ACTIVE_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2016_CM_ALL_CALL_END,IMG_MITEM2016_CM_ALL_CALL_END));

	ADD_APPLICATION_MENUITEM((MITEM2011_CM_END_SINGLE,MITEM2003_CM_S_ACTIVE_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2011_CM_END_SINGLE,IMG_MITEM2011_CM_END_SINGLE));

   // MTK amanda add 1229
	ADD_APPLICATION_MENUITEM((MITEM2011_CM_INC_END_SINGLE,MITEM2003_CM_S_ACTIVE_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2011_CM_END_SINGLE,IMG_MITEM2011_CM_END_SINGLE));

	ADD_APPLICATION_MENUITEM((MITEM_OUTGOING_REJECT, MITEM2008_CM_INC_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_REJECT,IMG_MITEM2011_CM_END_SINGLE));

	ADD_APPLICATION_MENUITEM((MITEM2017_CM_CALL_TRANSFER,MITEM2003_CM_S_ACTIVE_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2017_CM_CALL_TRANSFER,IMG_MITEM2017_CM_CALL_TRANSFER));

	ADD_APPLICATION_MENUITEM((MITEM2018_CM_CALL_SPLIT,MITEM2004_CM_M_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2018_CM_CALL_SPLIT,IMG_MITEM2018_CM_CALL_SPLIT));

	ADD_APPLICATION_MENUITEM((MITEM2011_CM_S_END,MITEM2004_CM_M_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2011_CM_S_END,IMG_MITEM2011_CM_S_END));

	ADD_APPLICATION_MENUITEM((MITEM2019_CM_ALL_ACTIVE_END,MITEM2004_CM_M_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2019_CM_ALL_ACTIVE_END,IMG_MITEM2019_CM_ALL_ACTIVE_END));

	ADD_APPLICATION_MENUITEM((MITEM2020_CM_ALL_HELD_END,MITEM2005_CM_M_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2020_CM_ALL_HELD_END,IMG_MITEM2020_CM_ALL_HELD_END));

	ADD_APPLICATION_MENUITEM((MITEM2031_CM_PBOOK,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2031_CM_PBOOK,IMG_MITEM2031_CM_PBOOK));

#ifdef __MMI_UNIFIED_MESSAGE__
	ADD_APPLICATION_MENUITEM((MITEM2032_CM_SMS,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_UM_MAIN_MENU_TITLE_ID,IMG_MITEM2032_CM_SMS));
#else /*__MMI_UNIFIED_MESSAGE__ */
	ADD_APPLICATION_MENUITEM((MITEM2032_CM_SMS,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2032_CM_SMS,IMG_MITEM2032_CM_SMS));
#endif /* __MMI_UNIFIED_MESSAGE__ */

	ADD_APPLICATION_MENUITEM((MITEM2041_CM_DROP,MITEM2008_CM_WAIT_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2041_CM_DROP,IMG_MITEM2041_CM_DROP));

	ADD_APPLICATION_MENUITEM((MITEM2020_CM_MUTE,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2020_CM_MUTE,IMG_MITEM2020_CM_MUTE));

	ADD_APPLICATION_MENUITEM((MITEM2021_CM_NEWCALL,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2021_CM_NEWCALL,IMG_MITEM2021_CM_NEWCALL));

//MTK: Brian added for voice memo in call
#ifndef __MMI_VOICE_MEMO__
	ADD_APPLICATION_MENUITEM((MITEM2022_CM_VOICE_MEMO,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2022_CM_VOICE_MEMO,IMG_MITEM2022_CM_VOICE_MEMO));
#endif
#ifdef __MMI_SOUND_RECORDER__
	ADD_APPLICATION_MENUITEM((MITEM2026_CM_SOUND_RECORDER,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2026_CM_SOUND_RECORDER,IMG_MITEM2026_CM_SOUND_RECORDER));
#endif

#if defined(__MMI_BT_SUPPORT__)
	/* Configure Default Headset */
	ADD_APPLICATION_MENUITEM((MITEM_CM_BT_CONNECT_LAST_HEADSET,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_BT_CONNECT_LAST_HEADSET,IMG_BT_CONNECT_LAST_HEADSET));
	ADD_APPLICATION_MENUITEM((MITEM_CM_BT_CONNECT_LAST_HEADSET,MITEM2003_CM_S_ACTIVE_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_BT_CONNECT_LAST_HEADSET,IMG_BT_CONNECT_LAST_HEADSET));
	ADD_APPLICATION_MENUITEM((MITEM_CM_BT_CONNECT_LAST_HEADSET,MITEM2004_CM_M_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_BT_CONNECT_LAST_HEADSET,IMG_BT_CONNECT_LAST_HEADSET));
	ADD_APPLICATION_MENUITEM((MITEM_CM_BT_CONNECT_LAST_HEADSET,MITEM2006_CM_M_ACTIVE_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_BT_CONNECT_LAST_HEADSET,IMG_BT_CONNECT_LAST_HEADSET));
	ADD_APPLICATION_MENUITEM((MITEM_CM_BT_CONNECT_LAST_HEADSET,MITEM2007_CM_S_ACTIVE_M_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_BT_CONNECT_LAST_HEADSET,IMG_BT_CONNECT_LAST_HEADSET));

	ADD_APPLICATION_MENUITEM((MITEM_CM_BT_SETPATH,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_BT_CM_SETPATH,IMG_BT_CM_SETPATH));
	ADD_APPLICATION_MENUITEM((MITEM_CM_BT_SETPATH,MITEM2003_CM_S_ACTIVE_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_BT_CM_SETPATH,IMG_BT_CM_SETPATH));
	ADD_APPLICATION_MENUITEM((MITEM_CM_BT_SETPATH,MITEM2004_CM_M_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_BT_CM_SETPATH,IMG_BT_CM_SETPATH));
	ADD_APPLICATION_MENUITEM((MITEM_CM_BT_SETPATH,MITEM2006_CM_M_ACTIVE_S_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_BT_CM_SETPATH,IMG_BT_CM_SETPATH));
	ADD_APPLICATION_MENUITEM((MITEM_CM_BT_SETPATH,MITEM2007_CM_S_ACTIVE_M_HOLD_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_BT_CM_SETPATH,IMG_BT_CM_SETPATH));
#endif
//MTK brian end

	ADD_APPLICATION_MENUITEM((MITEM2023_CM_LOUDSP,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2023_CM_LOUDSP,IMG_MITEM2023_CM_LOUDSP));

	
	ADD_APPLICATION_MENUITEM((MITEM2024_CM_DTMF,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2024_CM_DTMF,IMG_MITEM2024_CM_DTMF));
		

   // MTK amanda add for data call
   ADD_APPLICATION_MENUITEM((MITEM2011_CM_S_ACTIVE_END,MITEM2001_CM_SINGLE_DATA_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2011_CM_S_ACTIVE_END,IMG_MITEM2011_CM_S_ACTIVE_END));

   ADD_APPLICATION_MENUITEM((MITEM2031_CM_PBOOK,MITEM2001_CM_SINGLE_DATA_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2031_CM_PBOOK,IMG_MITEM2031_CM_PBOOK));

#ifdef __MMI_UNIFIED_MESSAGE__
	ADD_APPLICATION_MENUITEM((MITEM2032_CM_SMS,MITEM2001_CM_SINGLE_DATA_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_UM_MAIN_MENU_TITLE_ID,IMG_MITEM2032_CM_SMS));
#else /*__MMI_UNIFIED_MESSAGE__ */
	ADD_APPLICATION_MENUITEM((MITEM2032_CM_SMS,MITEM2001_CM_SINGLE_DATA_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2032_CM_SMS,IMG_MITEM2032_CM_SMS));
#endif /* __MMI_UNIFIED_MESSAGE__ */

#if defined(__MMI_BG_SOUND_EFFECT__)
	ADD_APPLICATION_MENUITEM((MENU_ID_BGSND_CM_OPT_EFFECT,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,3,
		MENU_ID_BGSND_CM_OPT_STATUS,
		MENU_ID_BGSND_CM_OPT_SETTING,
		MENU_ID_BGSND_CM_OPT_LIST,
		SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_ID_BGSND_BG_SOUND,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BGSND_CM_OPT_STATUS,MENU_ID_BGSND_CM_OPT_EFFECT,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_ID_BGSND_STATUS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BGSND_CM_OPT_SETTING,MENU_ID_BGSND_CM_OPT_EFFECT,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_ID_BGSND_PLAYBACK_SETUP,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BGSND_CM_OPT_LIST,MENU_ID_BGSND_CM_OPT_EFFECT,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_ID_BGSND_EFFECT_LIST,0));
#endif

	ADD_APPLICATION_STRING2(STR_USSD_REQ_DISP_SCR, "Please Wait","Display string for USSD req screen");
	ADD_APPLICATION_STRING2(STR_USSD_REQ_CAPTION, "Sending Request","Display Caption for USSD req screen");
	
	ADD_APPLICATION_STRING2(STR_SCR1001_RUNNING , "Calling...","Display string for outgoing call screen");
	ADD_APPLICATION_STRING2(STR_SCR1001_IP_CALLING , "IP Calling...","Display string for outgoing call screen");	
	
	ADD_APPLICATION_STRING2(OUT_SCR_NFY_STR	,"Outgoing Call","String for option Outgoing Call");

	ADD_APPLICATION_STRING2(STR_SCR1002_LOUDSP_H_FREE_RSK , "H-Free","RSK for active Loud Speaker On");
	ADD_APPLICATION_STRING2(STR_SCR1002_LOUDSP_H_HELD_RSK , "H-Held","RSK for active Loud Speaker Off");

	ADD_APPLICATION_STRING2(STR_SCR1002_RETRIEVE_RSK , "Retrieve","RSK for hold retrieve");

	ADD_APPLICATION_STRING2(STR_SCR1005_CAPTION, "Call Status","Caption for Hold request success screen");

	ADD_APPLICATION_STRING2(STR_SCR1006_CAPTION, "Call Status","Caption for Retrieve success screen");

	ADD_APPLICATION_STRING2(STR_SCR1007_CAPTION, "Call Status","Caption for Swap success screen");

	ADD_APPLICATION_STRING2(STR_SCR1008_CAPTION, "Call Status","Caption for Conference success screen");

	ADD_APPLICATION_STRING2(STR_SCR1009_CAPTION, "Call List","Caption for Calls (Active/Hold) List screen");

	ADD_APPLICATION_STRING2(STR_SCR1010_CAPTION, "Call Status","Caption for Split call success screen");


	ADD_APPLICATION_STRING2(STR_SCR1002_CAPTION	,"Call Menu","Title String for Screen for Outgoing Options");
	
	//MenuItems Strings

	ADD_APPLICATION_STRING2(STR_MITEM2010_CM_ACTIVE_HOLD , "Hold","String for hold option");
	ADD_APPLICATION_STRING2(STR_MITEM2010_CM_M_ACTIVE_HOLD , "Hold All","String for hold option");

	ADD_APPLICATION_STRING2(STR_MITEM2011_CM_S_ACTIVE_END , "End Active","String for End Active option");
	ADD_APPLICATION_STRING2(STR_MITEM2011_CM_END , "End","String for End option");
	ADD_APPLICATION_STRING2(STR_MITEM2011_CM_END_ALL , "End All","String for End option");

	ADD_APPLICATION_STRING2(STR_MITEM2011_CM_S_END , "End Single","String for End Active option");

	ADD_APPLICATION_STRING2(STR_MITEM2011_CM_S_ACTIVE_END_RETRIEVE , "End Active,Then Retrieve","String for End Active Then Retrieve option");

	ADD_APPLICATION_STRING2(STR_MITEM2020_CM_MUTE , "Mute","String for mute option");
	ADD_APPLICATION_STRING2(STR_MITEM2021_CM_NEWCALL , "New Call","String for New Call option");
	ADD_APPLICATION_STRING2(STR_MITEM2031_CM_PBOOK , "Phone Book","String for Phonebook option in CM");
	ADD_APPLICATION_STRING2(STR_MITEM2032_CM_SMS , "Message","String for SMS option in CM");
#ifdef __MMI_VOICE_MEMO__
	ADD_APPLICATION_STRING2(STR_MITEM2022_CM_VOICE_MEMO , "Voice Memo","String for Voice Memo option");
#endif
#ifdef __MMI_SOUND_RECORDER__
	ADD_APPLICATION_STRING2(STR_MITEM2026_CM_SOUND_RECORDER , "Sound Recorder","String for Sound Recorder option");
#endif
	ADD_APPLICATION_STRING2(STR_MITEM2023_CM_LOUDSP , "Loud Sp/Handset","String for Loud Speaker option");
	ADD_APPLICATION_STRING2(STR_MITEM2050_CM_END_HELD_ENDALL_HELD , "End Held/End All Held","String for End Held/End All Held option");
	

	ADD_APPLICATION_STRING2(STR_MITEM2024_CM_DTMF , "DTMF","String for DTMF option");


	ADD_APPLICATION_STRING2(STR_MITEM2012_CM_HELD_RETRIEVE , "Retrieve","String for Retrieve Call option");
	ADD_APPLICATION_STRING2(STR_MITEM2012_CM_M_HELD_RETRIEVE , "Retrieve All","String for Retrieve Call option");

	ADD_APPLICATION_STRING2(STR_MITEM2013_CM_S_HELD_END , "End Held","String for End Held Call option");
	ADD_APPLICATION_STRING2(STR_MITEM2014_CM_CALL_SWAP , "Swap","String for Swap Calls option");
	ADD_APPLICATION_STRING2(STR_MITEM2015_CM_CALL_CONFER , "Conference","String for starting conference Call option");
	ADD_APPLICATION_STRING2(STR_MITEM2016_CM_ALL_CALL_END , "End All","String for End All Calls option");

	ADD_APPLICATION_STRING2(STR_MITEM2011_CM_END_SINGLE , "End Single","String for End Single Call option");
	ADD_APPLICATION_STRING2(STR_REJECT , "Reject","String for Reject Call option");
	
	ADD_APPLICATION_STRING2(STR_MITEM2017_CM_CALL_TRANSFER , "Transfer","String for Call Transfer option");
	ADD_APPLICATION_STRING2(STR_MITEM2018_CM_CALL_SPLIT , "Split","String for Split Call option");
	ADD_APPLICATION_STRING2(STR_MITEM2019_CM_ALL_ACTIVE_END , "End All Active","String for End All Active Calls option");
	ADD_APPLICATION_STRING2(STR_MITEM2020_CM_ALL_HELD_END , "End All Held","String for End All Held Calls option");

	ADD_APPLICATION_STRING2(STR_MITEM2041_CM_DROP , "Drop","String for Drop Call option");

	ADD_APPLICATION_STRING2(STR_NFY_LOUDSPEAKER_ON,"LoudSp is turned on","String for LoudSp is turned on");
	ADD_APPLICATION_STRING2(STR_NFY_LOUDSPEAKER_OFF,"LoudSp is turned off","String for LoudSp is turned off");
	ADD_APPLICATION_STRING2(STR_DTMF_SCR_DISPLAY_ID , "Input","Caption for DTMF input screen");
	ADD_APPLICATION_STRING2(DTMF_RSK_STR , "Back/Clear","RSK for DTMF input screen");
	ADD_APPLICATION_STRING2(STR_ECT_NFY_CAPTION, "ECT Status","Caption for ECT notify screen");
	ADD_APPLICATION_STRING2(STR_ACTION_DONE, "Done","action done Screen");

        ADD_APPLICATION_STRING2(STR_CNAP_IND, "Name Modification","CNAP SS indication");

	ADD_APPLICATION_IMAGE2(IMG_CM_STATE_OUTGOING	,	CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Connect\\\\CL_NET.GIF","Image for USSD request screen");
	ADD_APPLICATION_IMAGE2(IMG_CM_STATE_CONNECTED	,	CUST_IMG_PATH"\\\\SUBLCD\\\\Active\\\\Call\\\\SB_CALL.bmp","Image of Call Connected -In Call");
	ADD_APPLICATION_IMAGE2(IMG_CM_STATE_ENDED,CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\ended\\\\CL_END"__MMI_RES_TYPE_POPUP_SCREEN__,"Image of Call Ended");
	ADD_APPLICATION_IMAGE2(IMG_CM_ICON_MULTI_LINE1	,	CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Outgoing\\\\CL_Aline1.bmp","Image of Line 1");
	ADD_APPLICATION_IMAGE2(IMG_CM_ICON_MULTI_LINE2	,	CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Outgoing\\\\CL_Aline1.bmp","Image of Line 2");

	ADD_APPLICATION_IMAGE2(IMG_CM_ICON_LINE1	,	CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Outgoing\\\\CL_line1.bmp","Image of Line 1");
	ADD_APPLICATION_IMAGE2(IMG_CM_ICON_LINE2	,	CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Outgoing\\\\CL_line2.bmp","Image of Line 2");

//micha0725 change SS requesting image 
	ADD_APPLICATION_IMAGE2(IMG_CM_SS_OUTGOING,		CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\Progress\\\\PROGRESS"__MMI_RES_TYPE_POPUP_SCREEN__,"Image for SS request screen");
	ADD_APPLICATION_IMAGE2(IMG_CM_SUBLCD_CALLING	,	CUST_IMG_PATH"\\\\SUBLCD\\\\Active\\\\Call\\\\SB_MOMT.GIF","Sub-LCD image of calling");
//	ADD_APPLICATION_IMAGE2(IMG_ERROR_NOTIFY, CUST_IMG_PATH"\\\\MainLCD\\\\Warningpage\\\\PopUpPage\\\\PP_UNF.gif","Error Image");
//	ADD_APPLICATION_IMAGE2(IMG_UNFINISHED_NOTIFY,CUST_IMG_PATH"\\\\MainLCD\\\\Warningpage\\\\PopUpPage\\\\PP_UNF.gif","CCBS activated");

	ADD_APPLICATION_IMAGE2(DTMF_LSK_ICN	,	CUST_IMG_BASE_PATH"\\\\EmptyImage.bmp","LSK icon for DTMF");
	ADD_APPLICATION_IMAGE2(DTMF_RSK_ICN	,	CUST_IMG_BASE_PATH"\\\\EmptyImage.bmp","RSK icon for DTMF");

	ADD_APPLICATION_IMAGE2(IMG_ECT_NFY_CAPTION, CUST_IMG_BASE_PATH"\\\\EmptyImage.bmp","Caption image for ECT notification");
	ADD_APPLICATION_IMAGE2(IMG_ECT_NFY_LSK, CUST_IMG_BASE_PATH"\\\\EmptyImage.bmp","LSK image for ECT notification screen");

	ADD_APPLICATION_IMAGE2(PHONE_MUTE_ICON, CUST_IMG_BASE_PATH"\\\\EmptyImage.bmp","Status Icon for Muting the phone");
	
	ADD_APPLICATION_IMAGE2(IMG_ERROR_NOTIFY, CUST_IMG_PATH"\\\\MainLCD\\\\Warningpage\\\\PopUpPage\\\\PP_ERR"__MMI_RES_TYPE_POPUP_SCREEN__,"Error Image");
	ADD_APPLICATION_IMAGE2(IMG_UNFINISHED_NOTIFY,CUST_IMG_PATH"\\\\MainLCD\\\\Warningpage\\\\PopUpPage\\\\PP_UNF"__MMI_RES_TYPE_POPUP_SCREEN__,"CCBS activated");
	
}

/**************************************************************

	FUNCTION NAME		: PopulateCTMResourceData()

  	PURPOSE				: To Initialize the resources for Redial screens

	INPUT PARAMETERS	: nil

	OUTPUT PARAMETERS	: nil

	RETURNS				: void

	REMARKS				: nil

**************************************************************/
#ifdef __CTM_SUPPORT__
void PopulateCTMResourceData(coid)
{
	ADD_APPLICATION_MENUITEM((MITEM2027_CM_CTM,MITEM2001_CM_SINGLE_ACTIVE_LSKOPTIONS,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM2027_CM_CTM,0));
	
	ADD_APPLICATION_MENUITEM((MITEM_CTM_EDITOR_OPTION,0,
		2,
		MITEM_CTM_EDITOR_DONE,
		MITEM_CTM_INPUT_METHOD,
		SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_GLOBAL_OPTIONS,0));

	ADD_APPLICATION_MENUITEM((MITEM_CTM_EDITOR_DONE,MITEM_CTM_EDITOR_OPTION,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_GLOBAL_DONE,0));
	ADD_APPLICATION_MENUITEM((MITEM_CTM_INPUT_METHOD,MITEM_CTM_EDITOR_OPTION,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_GLOBAL_INPUT_METHOD,0));

	ADD_APPLICATION_MENUITEM((MITEM_CTM_MENU,0,
		2,
		MITEM_CTM_MODE,
		MITEM_CTM_SETTING,
		SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_CTM_MENU,0));

	ADD_APPLICATION_MENUITEM((MITEM_CTM_MODE,MITEM_CTM_MENU,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_CTM_MODE,0));

#ifdef __MMI_CTM_AUTO_CONNECT__
	ADD_APPLICATION_MENUITEM((MITEM_CTM_SETTING,MITEM_CTM_MENU,
		5,
		MITEM_CTM_SETTING_BAUDOT,
		MITEM_CTM_SETTING_HCO,
		MITEM_CTM_SETTING_VCO,
		MITEM_CTM_SETTING_MANUAL_DIRECT,
		MITEM_CTM_SETTING_AUTO_DIRECT,
		SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_CTM_SETTING,0));
#else
	ADD_APPLICATION_MENUITEM((MITEM_CTM_SETTING,MITEM_CTM_MENU,
		4,
		MITEM_CTM_SETTING_BAUDOT,
		MITEM_CTM_SETTING_HCO,
		MITEM_CTM_SETTING_VCO,
		MITEM_CTM_SETTING_MANUAL_DIRECT,
		SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_CTM_SETTING,0));
#endif

	ADD_APPLICATION_MENUITEM((MITEM_CTM_SETTING_AUTO_DIRECT,MITEM_CTM_SETTING,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_CTM_AUTO,0));
	ADD_APPLICATION_MENUITEM((MITEM_CTM_SETTING_MANUAL_DIRECT,MITEM_CTM_SETTING,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_CTM_MANUAL,0));
	ADD_APPLICATION_MENUITEM((MITEM_CTM_SETTING_BAUDOT,MITEM_CTM_SETTING,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_CTM_BAUDOT,0));
	ADD_APPLICATION_MENUITEM((MITEM_CTM_SETTING_HCO,MITEM_CTM_SETTING,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_CTM_HCO,0));
	ADD_APPLICATION_MENUITEM((MITEM_CTM_SETTING_VCO,MITEM_CTM_SETTING,
		0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MITEM_CTM_VCO,0));

	ADD_APPLICATION_STRING2(STR_MITEM2027_CM_CTM , "CTM Connect","String for CTM option");	

	ADD_APPLICATION_STRING2(STR_CTM_CONNECTING , "Connecting","String for CTM option");	
	ADD_APPLICATION_STRING2(STR_CTM_CHAT , "Chat","String for CTM chat");	
	ADD_APPLICATION_STRING2(STR_CTM_REMOTE , "Remote Said","String for CTM remote words");	
	ADD_APPLICATION_STRING2(STR_CTM_LOCAL , "I Said","String for CTM local words");	

	ADD_APPLICATION_STRING2(STR_MITEM_CTM_MENU , "Text Phone","String for CTM menu");	
	ADD_APPLICATION_STRING2(STR_MITEM_CTM_MODE , "Mode","String for CTM mode");	
	ADD_APPLICATION_STRING2(STR_MITEM_CTM_SETTING , "Setting","String for CTM setting");		

	ADD_APPLICATION_STRING2(STR_MITEM_CTM_AUTO , "Auto Connect","String for auto CTM");	
	ADD_APPLICATION_STRING2(STR_MITEM_CTM_MANUAL , "Manual Connect","String for manual CTM");	
	ADD_APPLICATION_STRING2(STR_MITEM_CTM_BAUDOT , "TTY Device","String for tty");		
	ADD_APPLICATION_STRING2(STR_MITEM_CTM_HCO , "TTY HCO","String for tty hco");		
	ADD_APPLICATION_STRING2(STR_MITEM_CTM_VCO , "TTY VCO","String for tty vco");		

	ADD_APPLICATION_STRING2(STR_CTM_ON_SELECTED , "CTM mode on!","String for CTM on");	
	ADD_APPLICATION_STRING2(STR_CTM_OFF_SELECTED , "CTM mode off!","String for CTM off");	
	ADD_APPLICATION_STRING2(STR_CTM_TTY_TO_HEADSET , "TTY switched to earphone!","String for earphone");	
	ADD_APPLICATION_STRING2(STR_CTM_HEADSET_TO_TTY , "Earphone switched to TTY!","String for TTY");	
	ADD_APPLICATION_STRING2(STR_CTM_TTY_PLUG_IN , "TTY plug in!","String for TTY in");	
	ADD_APPLICATION_STRING2(STR_CTM_TTY_PLUG_OUT , "TTY plug out!","String for TTY out");	
}
#endif

#endif


