/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * Res_vObjects.C
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file is intends for populating resource of vObjects.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#ifndef _RES_VOBJECTS_C
#define _RES_VOBJECTS_C
#include "MMI_features.h"

#include "CustomCfg.h"
#include "vObjectsResDef.h"
#include "PhoneBookResDef.h"

#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif


#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"

#ifdef __MMI_DUAL_SIM_MASTER__
#include "MTPNP_AD_resdef.h"
#endif	/* __MMI_DUAL_SIM_MASTER__ */

/*****************************************************************************
* FUNCTION
*  PopulatevObjectRes
* DESCRIPTION
*   Populate resource data for vobjects.
*
* PARAMETERS
* 
* RETURNS
*  
* GLOBALS AFFECTED
*   
*****************************************************************************/
void PopulatevObjectRes(void)
{
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_RECV_VCARD	,"Receive vCard"	,"receive vcard message");	
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_RECV_VCLNDR	,"Receive vCalender"	,"receive vcalendar message");	
#ifdef __MMI_VBOOKMARK__
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_RECV_VBKM	,"Receive vBookmark"	,"receive vbookmark message");	
#endif /* __MMI_VBOOKMARK__ */	
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_CANCEL_QUERY	,"Cancel?"	,"key message");	
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_FORWARD_TO_SMS	,"SMS"	,"Through SMS option");
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_FORWARD_TO_MMS	,"MMS"	,"Through MMI option");
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_FORWARD_TO_IRDA	,"IrDA"	,"Through Irda option");
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_FORWARD_TO_EMAIL	,"Email"	,"Through Email option");	
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_FORWARD_TO_FILE_MGR	,"File Manager"	,"Save To file option");
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_FORWARD_TO_BT	,"Send by Blue Tooth"	,"Save To file option");
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_FILENAME	,"Filename"	,"Filename caption");
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_INPUT_METHOD	,"Input Method"	,"Input Method option");
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_DUPLICATE_FILENAME	,"Duplicate Filename!" ,"Duplicated Filename!");
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_INVALID_FILENAME	,"Invalid Filename!" ,"Invalid Filename!");
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_EMPTY_FILENAME	,"Empty Filename!" ,"Empty Filename!");
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_FORMAT_NOT_SUPPORT	,"Unsupported Format!" ,"Unsupported Format!");
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_FILE_PATH_TOO_LONG	,"File Path Too Long!" ,"File Path Too Long!");	
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_FUNC_NOT_SUPPORTED	,"Not Supported" ,"Not Supported");	
	ADD_APPLICATION_STRING2(STR_ID_VOBJ_UNFINISHED	,"Unfinished!" ,"Unfinished Message!");	
	ADD_APPLICATION_STRING2(STR_ID_VCARD_SAVE_TO_SIM	,"save to sim" ,"save to sim");	
	ADD_APPLICATION_STRING2(STR_ID_VCARD_SAVE_TO_PHONE	,"save to phone" ,"save to phone");	

#ifdef __MMI_VCARD__
	PopulatevCardRes();
#endif

#ifdef __MMI_VCALENDAR__
	PopulatevCalendarRes();
#endif

#ifdef __MMI_VBOOKMARK__
	PopulatevBookmarkRes();
#endif /* __MMI_VBOOKMARK__ */
}

/*****************************************************************************
* FUNCTION
*  PopulatevCardRes
* DESCRIPTION
*   Populate resource data for vcard.
*
* PARAMETERS
* 
* RETURNS
*  
* GLOBALS AFFECTED
*   
*****************************************************************************/
#ifdef __MMI_VCARD__
void PopulatevCardRes(void)
{
	/*vCard - SubMenu of Send Current Entry and Send My Card*/
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_FORWARD_OPTION,0,MENU_ID_VOBJ_TOTAL,
#if !defined(__MMI_MESSAGES_NO_SEND_BY_SMS_OPTION__)
		MENU_ID_VCARD_FORWARD_SMS,
#endif
#if defined(__MMI_MMS__)
		MENU_ID_VCARD_FORWARD_MMS,
#endif
#if  defined(__MMI_IRDA_SUPPORT__)	 
		MENU_ID_VCARD_FORWARD_IRDA,
#endif		
#ifdef __MMI_OPP_SUPPORT__
		MENU_ID_VCARD_FORWARD_BT,
#endif
#if  defined(EMAIL_APP_SUPPORT)
		MENU_ID_VCARD_FORWARD_EMAIL,
#endif	
#if  defined(__MMI_FILE_MANAGER__)
		MENU_ID_VCARD_FORWARD_FMGR,
#endif
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));

#if !defined(__MMI_MESSAGES_NO_SEND_BY_SMS_OPTION__)
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_FORWARD_SMS,MENU_ID_VCARD_FORWARD_OPTION,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_VOBJ_FORWARD_TO_SMS, IMG_GLOBAL_DEFAULT));
#endif
 
#if defined(__MMI_MMS__)
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_FORWARD_MMS,MENU_ID_VCARD_FORWARD_OPTION,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_VOBJ_FORWARD_TO_MMS,0));	
#endif

#if  defined(__MMI_IRDA_SUPPORT__)	 
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_FORWARD_IRDA,MENU_ID_VCARD_FORWARD_OPTION,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_VOBJ_FORWARD_TO_IRDA, IMG_GLOBAL_DEFAULT));
#endif

#if  defined(EMAIL_APP_SUPPORT)
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_FORWARD_EMAIL,MENU_ID_VCARD_FORWARD_OPTION,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_VOBJ_FORWARD_TO_EMAIL,0));	
#endif

#if  defined(__MMI_FILE_MANAGER__)
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_FORWARD_FMGR,MENU_ID_VCARD_FORWARD_OPTION,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_VOBJ_FORWARD_TO_FILE_MGR, IMG_GLOBAL_DEFAULT));
#endif

#ifdef __MMI_OPP_SUPPORT__
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_FORWARD_BT, MENU_ID_VCARD_FORWARD_OPTION,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_VOBJ_FORWARD_TO_BT, IMG_GLOBAL_DEFAULT));
#endif

	/*vcard - save to file manager enter filename option*/
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_ENTER_FILENAME_OPT, 0,
		2,
		MENU_ID_VCARD_ENTER_FILENAME_OPT_DONE,
		MENU_ID_VCARD_ENTER_FILENAME_OPT_INPUT_METHOD,
		SHOW,NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_ENTER_FILENAME_OPT_DONE, MENU_ID_VCARD_ENTER_FILENAME_OPT,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_GLOBAL_DONE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_ENTER_FILENAME_OPT_INPUT_METHOD, MENU_ID_VCARD_ENTER_FILENAME_OPT,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_ID_VOBJ_INPUT_METHOD, 0));
	
	/*vcard - receive vcard operation option.*/
#ifdef __MMI_DUAL_SIM_MASTER__
#if defined(__MMI_FILE_MANAGER__) && defined(__FS_MOVE_SUPPORT__)	
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_RECV_OPTION, 0,4,
		MENU_ID_VCARD_RECV_OPTION_TO_SIM,
		MENU_MTPNP_VCARD_RECV_OPTION_TO_SIM,
		MENU_ID_VCARD_RECV_OPTION_TO_PHONE,
		MENU_ID_VCARD_RECV_OPTION_FMGR,
		SHOW,NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS, 0));
#else
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_RECV_OPTION, 0,3,
		MENU_ID_VCARD_RECV_OPTION_TO_SIM,
		MENU_MTPNP_VCARD_RECV_OPTION_TO_SIM,
		MENU_ID_VCARD_RECV_OPTION_TO_PHONE,
		SHOW,NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS, 0));

#endif
#else   /* __MMI_DUAL_SIM_MASTER__ */
#if defined(__MMI_FILE_MANAGER__) && defined(__FS_MOVE_SUPPORT__)	
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_RECV_OPTION, 0,3,
		MENU_ID_VCARD_RECV_OPTION_TO_SIM,
		MENU_ID_VCARD_RECV_OPTION_TO_PHONE,
		MENU_ID_VCARD_RECV_OPTION_FMGR,
		SHOW,NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS, 0));
#else
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_RECV_OPTION, 0,2,
		MENU_ID_VCARD_RECV_OPTION_TO_SIM,
		MENU_ID_VCARD_RECV_OPTION_TO_PHONE,
		SHOW,NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS, 0));

#endif  /* defined(__MMI_FILE_MANAGER__) && defined(__FS_MOVE_SUPPORT__) */
#endif /* __MMI_DUAL_SIM_MASTER__ */

	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_RECV_OPTION_TO_SIM, MENU_ID_VCARD_RECV_OPTION,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, 
            #ifdef __MMI_DUAL_SIM_MASTER__
              STRING_MTPNP_VCARD_SAVE_TO_SIM1,
            #else
		STR_ID_VCARD_SAVE_TO_SIM,
            #endif
		0));
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_RECV_OPTION_TO_PHONE, MENU_ID_VCARD_RECV_OPTION,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_ID_VCARD_SAVE_TO_PHONE, 0));
#if  defined(__MMI_FILE_MANAGER__) && defined(__FS_MOVE_SUPPORT__)
	ADD_APPLICATION_MENUITEM((MENU_ID_VCARD_RECV_OPTION_FMGR, MENU_ID_VCARD_RECV_OPTION,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_ID_VOBJ_FORWARD_TO_FILE_MGR, 0));
#endif

	ADD_APPLICATION_STRING2(STR_ID_VCARD_NAME_EMPTY, "Name Empty", "General string for name field empty");

	
}
#endif

/*****************************************************************************
* FUNCTION
*  PopulatevCalendarRes
* DESCRIPTION
*   Populate resource data for vcalendar.
*
* PARAMETERS
* 
* RETURNS
*  
* GLOBALS AFFECTED
*   
*****************************************************************************/
#ifdef __MMI_VCALENDAR__
void PopulatevCalendarRes(void)
{
	ADD_APPLICATION_STRING2(STR_ID_VCLNDR_FORWARD	,"Forward vCalendar"	,"Forward vCalendar");	
	ADD_APPLICATION_STRING2(STR_ID_VCLNDR_SAVE_TO_TDL	,"Save To To Do List" ,"Save To To Do List");	
	ADD_APPLICATION_STRING2(STR_ID_VCLNDR_TASK_FULL	,"Task Full"	,"Task Full");		
	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_FORWARD,MITEM_TODO_LIST_TASK_OPTION_1,MENU_ID_VOBJ_TOTAL,
#if !defined(__MMI_MESSAGES_NO_SEND_BY_SMS_OPTION__)	
		MENU_VCLNDR_SEND_BY_SMS,
#endif
#if defined(__MMI_MMS__)
		MENU_VCLNDR_SEND_BY_MMS,
#endif
#if  defined(__MMI_IRDA_SUPPORT__)
		MENU_VCLNDR_SEND_BY_IRDA,
#endif	
#if  defined(__MMI_OPP_SUPPORT__)
		MENU_VCLNDR_SEND_BY_BT,
#endif
#if  defined(EMAIL_APP_SUPPORT)
		MENU_VCLNDR_SEND_BY_EMAIL,
#endif	
#if  defined(__MMI_FILE_MANAGER__)
		MENU_VCLNDR_SEND_BY_FILEMGR,
#endif
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_VCLNDR_FORWARD,0));	

#if !defined(__MMI_MESSAGES_NO_SEND_BY_SMS_OPTION__)	
	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_SEND_BY_SMS,MENU_VCLNDR_FORWARD,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_VOBJ_FORWARD_TO_SMS,0));
#endif

#if defined(__MMI_MMS__)
	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_SEND_BY_MMS,MENU_VCLNDR_FORWARD,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_VOBJ_FORWARD_TO_MMS,0));	
#endif

#if  defined(__MMI_IRDA_SUPPORT__)
	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_SEND_BY_IRDA,MENU_VCLNDR_FORWARD,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_VOBJ_FORWARD_TO_IRDA,0));	
#endif

#if  defined(EMAIL_APP_SUPPORT)
	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_SEND_BY_EMAIL,MENU_VCLNDR_FORWARD,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_VOBJ_FORWARD_TO_EMAIL,0));	
#endif

#if  defined(__MMI_OPP_SUPPORT__)
	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_SEND_BY_BT,MENU_VCLNDR_FORWARD,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_VOBJ_FORWARD_TO_BT,0));	
#endif

#if  defined(__MMI_FILE_MANAGER__)
	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_SEND_BY_FILEMGR,MENU_VCLNDR_FORWARD,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_VOBJ_FORWARD_TO_FILE_MGR,0));	
#endif
	
	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_FILENAME_OPT, 0,
		2,
		MENU_VCLNDR_OPT_DONE,
		MENU_VCLNDR_OPT_INPUT_METHOD,
		SHOW,NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS, 0));

	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_OPT_DONE, MENU_VCLNDR_FILENAME_OPT,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_GLOBAL_DONE, 0));
	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_OPT_INPUT_METHOD, MENU_VCLNDR_FILENAME_OPT,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_ID_VOBJ_INPUT_METHOD, 0));

	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_RECV_OPTION, 0,VCLNDR_OPT_TOTAL,
		MENU_VCLNDR_RECV_OPT_TDL,
#if defined(__MMI_FILE_MANAGER__) && defined(__FS_MOVE_SUPPORT__)
		MENU_VCLNDR_RECV_OPT_FMGR,
#endif		
		SHOW,NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS, 0));

	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_RECV_OPT_TDL, MENU_VCLNDR_RECV_OPTION,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_ID_VCLNDR_SAVE_TO_TDL, 0));

#if defined(__MMI_FILE_MANAGER__) && defined(__FS_MOVE_SUPPORT__)
	ADD_APPLICATION_MENUITEM((MENU_VCLNDR_RECV_OPT_FMGR, MENU_VCLNDR_RECV_OPTION,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_ID_VOBJ_FORWARD_TO_FILE_MGR, 0));
#endif
}
#endif  // #ifdef __MMI_VCALENDAR__


/*****************************************************************************
* FUNCTION
*  PopulatevBookmarkRes
* DESCRIPTION
*   Populate resource data for vbookmark
*
* PARAMETERS
* 
* RETURNS
*  
* GLOBALS AFFECTED
*   
*****************************************************************************/
#ifdef __MMI_VBOOKMARK__
void PopulatevBookmarkRes(void)
{
	ADD_APPLICATION_MENUITEM((MENU_ID_VBKM_RECV_OPTION, 0, 3,
		MENU_ID_VBKM_RECV_OPTION_VIEW,
		MENU_ID_VBKM_RECV_OPTION_SAVE_TO_FMGR,
		MENU_ID_VBKM_RECV_OPTION_SAVE_TO_BOOKMARK,
		SHOW,NONMOVEABLE,DISP_LIST,0,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_VBKM_RECV_OPTION_VIEW, MENU_ID_VBKM_RECV_OPTION,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_VBKM_VIEW,0));
#if defined(__MMI_FILE_MANAGER__) && defined(__FS_MOVE_SUPPORT__)
	ADD_APPLICATION_MENUITEM((MENU_ID_VBKM_RECV_OPTION_SAVE_TO_FMGR, MENU_ID_VBKM_RECV_OPTION,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_VBKM_SAVE_TO_FMGR,0));
#endif /* defined(__MMI_FILE_MANAGER__) && defined(__FS_MOVE_SUPPORT__) */
	ADD_APPLICATION_MENUITEM((MENU_ID_VBKM_RECV_OPTION_SAVE_TO_BOOKMARK, MENU_ID_VBKM_RECV_OPTION,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_VBKM_SAVE_TO_BOOKMARK,0));

	/* String ID's Start */
	ADD_APPLICATION_STRING2(STR_ID_VBKM_VIEW,"View","View Bookmark");
	ADD_APPLICATION_STRING2(STR_ID_VBKM_SAVE_TO_FMGR,"Save To File Manager","Save To File Manager");
	ADD_APPLICATION_STRING2(STR_ID_VBKM_SAVE_TO_BOOKMARK,"Save To Bookmark","Save To Bookmark");
	/* String ID's End */
}
#endif /* __MMI_VBOOKMARK__ */

#endif

#endif /*END #ifndef _RES_VOBJECTS_C*/
