/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/**
 *	Copyright Notice
 *	?2002 - 2003, Pixtel Communications, Inc., 1489 43rd Ave. W.,
 *	Vancouver, B.C. V6M 4K8 Canada. All Rights Reserved.
 *  (It is illegal to remove this copyright notice from this software or any
 *  portion of it)
 */

/**************************************************************

	FILENAME	: Res_FunAndGames.c

  	PURPOSE		: Populate Resource for FunAndGames

	REMARKS		: nil

	AUTHOR		: Yogesh

	DATE		: August-16-2003

**************************************************************/
#include "MMI_features.h"
#include "CustomCfg.h"

#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif

#include "ComposeRingToneDefs.h"
#include "DownloadDefs.h"
#ifdef __J2ME__
#include "JavaAgencyDef.h"
#include "j2me_custom.h"
#endif
#include "FunAndGamesResDef.h"
#include "ComposeRingToneEngineDefs.h"
#include "GameResDef.h"
#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"



#if defined(__MMI_RING_COMPOSER__) && defined(__MMI_IMELODY_SUPPORT__)
void PopulateComposeRingTone(void)
{
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SELMENU_1,0,
#if defined(__MMI_FILE_MANAGER__)
		7,
#else
		5,
#endif
#if defined(__MMI_FILE_MANAGER__)
		MENU_FMGR_AUD_OPTION_PLAY,
#else
		MENU_COMP_RINGTONE_COMP_SELPLAY,
#endif
		MENU_COMP_RINGTONE_COMP_SELEDIT,
		MENU_COMP_RINGTONE_COMP_SELADD,
#if defined(__MMI_FILE_MANAGER__)
		MENU_FMGR_GEN_OPTION_RENAME,
		MENU_FMGR_GEN_OPTION_DELETE,
		MENU_FMGR_GEN_OPTION_DELETE_ALL,
		MENU_FMGR_GEN_OPTION_FORWARD,
#else
		MENU_COMP_RINGTONE_COMP_SELRENAME,
		MENU_COMP_RINGTONE_COMP_SELDELETE,
#endif
		SHOW,NONMOVEABLE,DISP_LIST,STR_COMPOSER_RINGTONE_SELMENUOPT1,IMG_GLOBAL_OPTIONS));


	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SELPLAY, MENU_COMP_RINGTONE_COMP_SELMENU_1,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMPOSER_RINGTONE_PLAY, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SELEDIT, MENU_COMP_RINGTONE_COMP_SELMENU_1,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMPOSER_RINGTONE_EDIT, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SELADD, MENU_COMP_RINGTONE_COMP_SELMENU_1,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMPOSER_RINGTONE_ADD, 0));
	
 #if !defined(__MMI_FILE_MANAGER__)
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SELRENAME, MENU_COMP_RINGTONE_COMP_SELMENU_1,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMPOSER_RINGTONE_RENAME, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SELDELETE, MENU_COMP_RINGTONE_COMP_SELMENU_1,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMPOSER_RINGTONE_DELETE, 0));

	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SELMENU_2,0,
		4,
		MENU_COMP_RINGTONE_COMP_SELPLAY,
		MENU_COMP_RINGTONE_COMP_SELEDIT,
		MENU_COMP_RINGTONE_COMP_SELRENAME,
		MENU_COMP_RINGTONE_COMP_SELDELETE,
		SHOW,NONMOVEABLE, DISP_LIST,STR_COMPOSER_RINGTONE_SELMENUOPT2,IMG_GLOBAL_OPTIONS));
#endif
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SELPLAY, MENU_COMP_RINGTONE_COMP_SELMENU_2,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMPOSER_RINGTONE_PLAY, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SELEDIT, MENU_COMP_RINGTONE_COMP_SELMENU_2,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMPOSER_RINGTONE_EDIT, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SELRENAME, MENU_COMP_RINGTONE_COMP_SELMENU_2,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMPOSER_RINGTONE_RENAME, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SELDELETE, MENU_COMP_RINGTONE_COMP_SELMENU_2,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMPOSER_RINGTONE_DELETE, 0));

	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_ADDOPT,0,
		4,
		MENU_COMP_RINGTONE_COMP_PLAY,
		MENU_COMP_RINGTONE_COMP_PLAY_SPEED,
		MENU_COMP_RINGTONE_COMP_SEL_INST,
		MENU_COMP_RINGTONE_COMP_SAVE,
		SHOW,NONMOVEABLE, DISP_LIST,STR_COMPOSER_RINGTONE_ADDOPT,IMG_GLOBAL_OPTIONS));

	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_PLAY, MENU_COMP_RINGTONE_COMP_ADDOPT,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMPOSER_RINGTONE_PLAY, 0));

	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_PLAY_SPEED, MENU_COMP_RINGTONE_COMP_ADDOPT,
		3,
		MENU_COMP_RINGTONE_FAST,
		MENU_COMP_RINGTONE_NORMAL,
		MENU_COMP_RINGTONE_SLOW,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMP_RINGTONE_PLAY_SPEED, 0));

	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_FAST, MENU_COMP_RINGTONE_COMP_PLAY_SPEED,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_COMP_RINGTONE_FAST, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_NORMAL, MENU_COMP_RINGTONE_COMP_PLAY_SPEED,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_COMP_RINGTONE_NORMAL, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_SLOW, MENU_COMP_RINGTONE_COMP_PLAY_SPEED,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMP_RINGTONE_SLOW, 0));

// MTK modifed, Max: change instrument 1021
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SEL_INST, MENU_COMP_RINGTONE_COMP_ADDOPT,
		10,
		MENU_COMP_RINGTONE_PIANO,MENU_COMP_RINGTONE_GUITAR,
		MENU_COMP_RINGTONE_VIOLIN,MENU_COMP_RINGTONE_SAXOPHONE,
		MENU_COMP_RINGTONE_STEELDRUMS,MENU_COMP_RINGTONE_FLUTE,
		MENU_COMP_RINGTONE_HARMONICA,MENU_COMP_RINGTONE_TRUMPET,
		MENU_COMP_RINGTONE_MUSICBOX,MENU_COMP_RINGTONE_XYLOPHONE,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMP_RINGTONE_SEL_INST, 0));

	
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_PIANO, MENU_COMP_RINGTONE_COMP_SEL_INST,0,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMP_RINGTONE_PIANO, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_GUITAR, MENU_COMP_RINGTONE_COMP_SEL_INST,0,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMP_RINGTONE_GUITAR, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_VIOLIN, MENU_COMP_RINGTONE_COMP_SEL_INST,0,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMP_RINGTONE_VIOLIN, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_SAXOPHONE, MENU_COMP_RINGTONE_COMP_SEL_INST,0,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMP_RINGTONE_SAXOPHONE, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_STEELDRUMS, MENU_COMP_RINGTONE_COMP_SEL_INST,0,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMP_RINGTONE_STEELDRUMS, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_FLUTE, MENU_COMP_RINGTONE_COMP_SEL_INST,0,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMP_RINGTONE_FLUTE, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_HARMONICA, MENU_COMP_RINGTONE_COMP_SEL_INST,0,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMP_RINGTONE_HARMONICA, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_TRUMPET, MENU_COMP_RINGTONE_COMP_SEL_INST,0,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMP_RINGTONE_TRUMPET, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_MUSICBOX, MENU_COMP_RINGTONE_COMP_SEL_INST,0,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMP_RINGTONE_MUSICBOX, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_XYLOPHONE, MENU_COMP_RINGTONE_COMP_SEL_INST,0,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMP_RINGTONE_XYLOPHONE, 0));
// MTK end
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_COMP_SAVE, MENU3103_RINGTONE_COMPOSER,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMP_RINGTONE_SAVE, 0));

	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_SAVE_TONE,0,
		2,
		MENU_COMP_RINGTONE_DONE,
		MENU_COMP_RINGTONE_INPUTMETHOD,
		SHOW,NONMOVEABLE, DISP_LIST, STR_COMPOSER_RINGTONE_SAVEOPT, 0));

	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_DONE, MENU_COMP_RINGTONE_SAVE_TONE,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_GLOBAL_DONE, 0));
	ADD_APPLICATION_MENUITEM((MENU_COMP_RINGTONE_INPUTMETHOD, MENU_COMP_RINGTONE_SAVE_TONE,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST, STR_COMP_RINGTONE_INPUTMETHOD, 0));

	
	ADD_APPLICATION_STRING2(STR_MENU3103_RINGTONE_COMPOSER,"Melody Compose","Melody Compose");
	ADD_APPLICATION_STRING2(STR_COMPOSER_RINGTONE_SELMENUOPT1,"Option","Ring Tone Select Menu 1");
	ADD_APPLICATION_STRING2(STR_COMPOSER_RINGTONE_SELMENUOPT2,"Option","Ring Tone Select Menu 2");
	ADD_APPLICATION_STRING2(STR_COMPOSER_RINGTONE_ADDOPT,"Option","Ring Tone Add/Edit Option");
	ADD_APPLICATION_STRING2(STR_COMPOSER_RINGTONE_SAVEOPT,"Save","Ring Tone Save Tone Option");
	// MTK modified, Max: to sync display string 1119
	ADD_APPLICATION_STRING2(STR_COMPOSER_RINGTONE_LIST,"Melody Compose","Ring Composer List");
//	ADD_APPLICATION_STRING2(STR_COMPOSER_RINGTONE_LIST,"Ring Composer","Ring Composer List");
	// MTK end
	ADD_APPLICATION_STRING2(STR_COMPOSER_RINGTONE_PLAY,"Play","Play Ring Tone");
	ADD_APPLICATION_STRING2(STR_COMPOSER_RINGTONE_EDIT,"Edit","Edit Ring Tone");
	ADD_APPLICATION_STRING2(STR_COMPOSER_RINGTONE_ADD,"Add","Add New Ring Tone");
	ADD_APPLICATION_STRING2(STR_COMPOSER_RINGTONE_RENAME,"Rename","Rename Ring Tone");
	ADD_APPLICATION_STRING2(STR_COMPOSER_RINGTONE_DELETE,"Delete","Delete Ring Tone");
	ADD_APPLICATION_STRING2(STR_COMPOSER_RINGTONE_PLAYING,"Playing...","Playing Ring Tone");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_DELETED,"Deleted","Deleted Ring Tone");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_PLAY_SPEED,"Play Speed","Adjust Playing Speed");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_SEL_INST,"Select Instrument","Select Playing Instrument");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_SAVE,"Save","Save Added/Edited/Rename Tone");
//	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_SAVED,"Saved","Saved Added/Edited/Rename Tone");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_DUPLICATE,"Duplicate Filename!","Duplicate Melody Filename");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_EMPTYFILENAME,"Empty Filename!","Empty Melody Filename");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_MEMORYFULL,"Memory Full!","Memory Full!");
	
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_FAST,"Fast","Playing Speed Fast");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_NORMAL,"Normal","Playing Speed Normal");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_SLOW,"Slow","Playing Speed Slow");
	
	// MTK modified, Max: change insturment 1021	
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_PIANO,"Piano","Select Instrument Piano");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_GUITAR,"Guitar","Select Instrument Guitar");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_VIOLIN,"Violin","Select Instrument Violin");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_SAXOPHONE,"Saxophone","Select Instrument Saxophone");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_STEELDRUMS,"Steel Drums","Select Instrument Steel Drums");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_FLUTE,"Flute","Select Instrument Flute");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_HARMONICA,"Harmonica","Select Instrument Harmonica");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_TRUMPET,"Trumpet","Select Instrument Trumpet");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_MUSICBOX,"Music Box","Select Instrument Music Box");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_XYLOPHONE,"Xylophone","Select Instrument Xylophone");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_EMPTYRINGTONE,"Empty Ring Tone","Empty Ring tone pop up");
	// MTK end

	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_FILENAME,"Filename","Filename of Ring Tone");
//	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_DONE,"Done","Save Ring Tone Done");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_INPUTMETHOD ,"Input Method","Input Methods");
	//ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_BOPOMOFO,"BoPoMoFo","Save Ring Tone BoPoMoFo");
	//ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_PING_XING,"Ping-Xing","Save Ring Tone Ping-Xing");
	ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_EMPTY,"<Empty>","No Ring Tone");
	ADD_APPLICATION_STRING2(STR_CAP_COMP_RINGTONE_DELETE,"Delete Ring Tone","Title String for Notification");
	//ADD_APPLICATION_STRING2(STR_COMP_RINGTONE_DELETE_CNF,"Do you really want to delete Ring Tone ?","Delete Confirmation");
	ADD_APPLICATION_IMAGE2(IMG_COMP_RINGTONE_PLAY,CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SR_PLAY.GIF","Play Ring Tone");
	ADD_APPLICATION_IMAGE2(IMG_MENU3103_RINGTONE_COMPOSER,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\SB_FRING.PBM","Ringtone composer image");

	PopulateRingComposer();
}
#endif //#if defined(__MMI_RING_COMPOSER__)


//MTK: Paul added for Java
#ifdef __J2ME__
void PopulateJavaRes(void)
{
	ADD_APPLICATION_MENUITEM((MENU_JAVA_EM,MENU3108_JAVA,5,
		MENU_JAVA_EM_NORMAL,
		MENU_JAVA_EM_CLDC_TCK,
		MENU_JAVA_EM_MIDP_TCK,
		MENU_JAVA_EM_WMAPI_TCK,
		MENU_JAVA_EM_MMAPI_TCK,
		SHOW, NONMOVEABLE, DISP_LIST, STR_JAVA_EM,0));

	ADD_APPLICATION_MENUITEM((MENU_JAVA_EM_NORMAL,MENU_JAVA_EM,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_JAVA_EM_NORMAL,0));
	ADD_APPLICATION_MENUITEM((MENU_JAVA_EM_CLDC_TCK,MENU_JAVA_EM,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_JAVA_EM_CLDC_TCK,0));
	ADD_APPLICATION_MENUITEM((MENU_JAVA_EM_MIDP_TCK,MENU_JAVA_EM,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_JAVA_EM_MIDP_TCK,0));
	ADD_APPLICATION_MENUITEM((MENU_JAVA_EM_WMAPI_TCK,MENU_JAVA_EM,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_JAVA_EM_WMAPI_TCK,0));
	ADD_APPLICATION_MENUITEM((MENU_JAVA_EM_MMAPI_TCK,MENU_JAVA_EM,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_JAVA_EM_MMAPI_TCK,0));

// level 1 menu

	ADD_APPLICATION_MENUITEM((MENU_JAVA_APP_MIDS_OPTION,MENU_JAVA,6,
		MENU_JAVA_APP_OPTION_SELECT,
		MENU_JAVA_APP_OPTION_LAUNCH,
		MENU_JAVA_APP_OPTION_UPDATE,
		MENU_JAVA_APP_OPTION_SETTING,
		MENU_JAVA_APP_OPTION_INFO,
		MENU_JAVA_APP_OPTION_DELETE,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS,0));


// level 2 menu
	ADD_APPLICATION_MENUITEM((MENU_JAVA_APP_OPTION_SELECT,MENU_JAVA_APP_MIDS_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_JAVA_APP_OPTION_SELECT,0));
	ADD_APPLICATION_MENUITEM((MENU_JAVA_APP_OPTION_LAUNCH,MENU_JAVA_APP_MIDS_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_JAVA_APP_OPTION_LAUNCH,0));
	ADD_APPLICATION_MENUITEM((MENU_JAVA_APP_OPTION_UPDATE,MENU_JAVA_APP_MIDS_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_JAVA_APP_OPTION_UPDATE,0));
	ADD_APPLICATION_MENUITEM((MENU_JAVA_APP_OPTION_SETTING,MENU_JAVA_APP_MIDS_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_JAVA_APP_OPTION_SETTING,0));
	ADD_APPLICATION_MENUITEM((MENU_JAVA_APP_OPTION_INFO,MENU_JAVA_APP_MIDS_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_JAVA_APP_OPTION_INFO,0));
	ADD_APPLICATION_MENUITEM((MENU_JAVA_APP_OPTION_DELETE,MENU_JAVA_APP_MIDS_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_JAVA_APP_OPTION_DELETE,0));
// strings
	ADD_APPLICATION_STRING2(STR_SCR_JAVA_CAPTION,"Java","STR_SCR_JAVA_CAPTION");

	ADD_APPLICATION_STRING2(STR_JAVA_EM,"Engineer Mode","STR_JAVA_EM");

	ADD_APPLICATION_STRING2(STR_JAVA_APP_OPTION_SELECT,"Select","STR_JAVA_APP_OPTION_SELECT");
	ADD_APPLICATION_STRING2(STR_JAVA_APP_OPTION_LAUNCH,"Launch","STR_JAVA_APP_OPTION_LAUNCH");
	ADD_APPLICATION_STRING2(STR_JAVA_APP_OPTION_UPDATE,"Update","STR_JAVA_APP_OPTION_UPDATE");
	ADD_APPLICATION_STRING2(STR_JAVA_APP_OPTION_SETTING,"Setting","STR_JAVA_APP_OPTION_SETTING");
	ADD_APPLICATION_STRING2(STR_JAVA_APP_OPTION_INFO,"Information","STR_JAVA_APP_OPTION_INFO");
	ADD_APPLICATION_STRING2(STR_JAVA_APP_OPTION_DELETE,"Delete","STR_JAVA_APP_OPTION_DELETE");

	ADD_APPLICATION_STRING2(STR_JAVA_EM_NORMAL,"Normal","STR_JAVA_EM_NORMAL");
	ADD_APPLICATION_STRING2(STR_JAVA_EM_CLDC_TCK,"CLDC TCK","STR_JAVA_EM_CLDC_TCK");
	ADD_APPLICATION_STRING2(STR_JAVA_EM_MIDP_TCK,"MIDP TCK","STR_JAVA_EM_MIDP_TCK");
	ADD_APPLICATION_STRING2(STR_JAVA_EM_WMAPI_TCK,"WMAPI TCK","STR_JAVA_EM_WMAPI_TCK");
	ADD_APPLICATION_STRING2(STR_JAVA_EM_MMAPI_TCK,"MMAPI TCK","STR_JAVA_EM_MMAPI_TCK");

	ADD_APPLICATION_STRING2(STR_JAVA_SETTING_NETWORK_ACCESS,"Network Access","STR_JAVA_SETTING_NETWORK_ACCESS");
	ADD_APPLICATION_STRING2(STR_JAVA_SETTING_AUTO_INVOCATION,"Auto Invocation","STR_JAVA_SETTING_AUTO_INVOCATION");
	ADD_APPLICATION_STRING2(STR_JAVA_SETTING_MESSAGING,"Messaging","STR_JAVA_SETTING_MESSAGING");
	ADD_APPLICATION_STRING2(STR_JAVA_SETTING_MULTIMEDIA,"Multimedia","STR_JAVA_SETTING_MULTIMEDIA");
	ADD_APPLICATION_STRING2(STR_JAVA_SETTING_FILE_READ,"Read user data","STR_JAVA_SETTING_FILE_READ");
	ADD_APPLICATION_STRING2(STR_JAVA_SETTING_FILE_WRITE,"Write user data","STR_JAVA_SETTING_FILE_WRITE");
	ADD_APPLICATION_STRING2(STR_JAVA_SETTING_LOCAL_CONNECTIVITY,"Local connectivity","STR_JAVA_SETTING_LOCAL_CONNECTIVITY");
	
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_NAME,"Name:","STR_JAVA_INFO_NAME");
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_SIZE,"Size:","STR_JAVA_INFO_SIZE");
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_VERSION,"Version:","STR_JAVA_INFO_VERSION");
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_VENDOR,"Vendor:","STR_JAVA_INFO_VENDOR");
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_DESC,"Description:","STR_JAVA_INFO_DESC");
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_WEB,"Website:","STR_JAVA_INFO_WEB");
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_AUTH,"Authorized by:","STR_JAVA_INFO_AUTH");
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_CONN,"Connections:","STR_JAVA_INFO_CONN");
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_BYTE,"Bytes","STR_JAVA_INFO_BYTE");
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_DRM_OBJECT,"[DRM object]","STR_JAVA_INFO_DRM_OBJECT");
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_DRM_COUNT,"Remaining count:","STR_JAVA_INFO_DRM_COUNT");
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_DRM_START,"Valid from:","STR_JAVA_INFO_DRM_START");
	ADD_APPLICATION_STRING2(STR_JAVA_INFO_DRM_END,"Good thru:","STR_JAVA_INFO_DRM_END");

	ADD_APPLICATION_STRING2(STR_JAVA_PERM_USERDENY,"Never","STR_JAVA_PERM_USERDENY");
	ADD_APPLICATION_STRING2(STR_JAVA_PERM_ONESHOT,"Prompt always","STR_JAVA_PERM_ONESHOT");
	ADD_APPLICATION_STRING2(STR_JAVA_PERM_SESSION,"Prompt at first","STR_JAVA_PERM_SESSION");
	ADD_APPLICATION_STRING2(STR_JAVA_PERM_BLANKET,"Prompt once only","STR_JAVA_PERM_BLANKET");
	ADD_APPLICATION_STRING2(STR_JAVA_PERM_BLANKET_GRANTED,"Allow","STR_JAVA_PERM_BLANKET_GRANTED");

	ADD_APPLICATION_STRING2(STR_JAVA_PERM_DMN_OPERATOR,"Operator","STR_JAVA_PERM_DMN_OPERATOR");
	ADD_APPLICATION_STRING2(STR_JAVA_PERM_DMN_MANUFACTURER,"Manufacturer","STR_JAVA_PERM_DMN_MANUFACTURER");
	ADD_APPLICATION_STRING2(STR_JAVA_PERM_DMN_3RDPARTY,"Third Party","STR_JAVA_PERM_DMN_3RDPARTY");
	ADD_APPLICATION_STRING2(STR_JAVA_PERM_DMN_UNTRUSTED,"Untrusted domain","STR_JAVA_PERM_DMN_UNTRUSTED");

	ADD_APPLICATION_STRING2(STR_JAVA_ABORT,"Abort","STR_JAVA_ABORT");
#ifdef JAVA_USE_RESERVE_STRING
	ADD_APPLICATION_STRING2(STR_JAVA_ABORT_ASK,"Abort?","STR_JAVA_ABORT_ASK");
	ADD_APPLICATION_STRING2(STR_JAVA_ABORTING,"Aborting...","STR_JAVA_ABORTING");
#endif
	ADD_APPLICATION_STRING2(STR_JAVA_ABORTED,"Aborted~","STR_JAVA_ABORTED");
	ADD_APPLICATION_STRING2(STR_JAVA_ABORT_FAILED,"Abort failed~","STR_JAVA_ABORT_FAILED");

#ifdef JAVA_USE_RESERVE_STRING
	ADD_APPLICATION_STRING2(STR_JAVA_DOWNLOAD,"Download","STR_JAVA_DOWNLOAD");
#endif
	ADD_APPLICATION_STRING2(STR_JAVA_DOWNLOAD_ASK,"Download?","STR_JAVA_DOWNLOAD_ASK");
	ADD_APPLICATION_STRING2(STR_JAVA_DOWNLOADING,"Downloading...","STR_JAVA_DOWNLOADING");
	ADD_APPLICATION_STRING2(STR_JAVA_DOWNLOADED,"Downloaded~","STR_JAVA_DOWNLOADED");
#ifdef JAVA_USE_RESERVE_STRING
	ADD_APPLICATION_STRING2(STR_JAVA_DOWNLOAD_FAILED,"Download failed~","STR_JAVA_DOWNLOAD_FAILED");
#endif

#ifdef JAVA_USE_RESERVE_STRING
	ADD_APPLICATION_STRING2(STR_JAVA_INSTALL,"Install","STR_JAVA_INSTALL");
    ADD_APPLICATION_STRING2(STR_JAVA_INSTALL_ASK,"Install?","STR_JAVA_INSTALL_ASK");
#endif
	ADD_APPLICATION_STRING2(STR_JAVA_START_INSTALLING,"Start Installing","STR_JAVA_START_INSTALLING");
	ADD_APPLICATION_STRING2(STR_JAVA_VM_INSTALLING,"VM Installing","STR_JAVA_VM_INSTALLING");
	ADD_APPLICATION_STRING2(STR_JAVA_INSTALLED,"Installed~","STR_JAVA_INSTALLED");
#ifdef JAVA_USE_RESERVE_STRING
    ADD_APPLICATION_STRING2(STR_JAVA_INSTALL_FAILED,"Install failed~","STR_JAVA_INSTALL_FAILED");
#endif

	ADD_APPLICATION_STRING2(STR_JAVA_DELETE,"Delete","STR_JAVA_DELETE");
	ADD_APPLICATION_STRING2(STR_JAVA_DELETE_ASK,"?\nOnce removed, all relative data can not be recovered. This suite contains:\n","STR_JAVA_DELETE_ASK");
	ADD_APPLICATION_STRING2(STR_JAVA_DELETING,"Deleting...","STR_JAVA_DELETING");
	ADD_APPLICATION_STRING2(STR_JAVA_DELETED,"Deleted~","STR_JAVA_DELETED");
#ifdef JAVA_USE_RESERVE_STRING
	ADD_APPLICATION_STRING2(STR_JAVA_DELETE_FAILED,"Delete failed~","STR_JAVA_DELETE_FAILED");
#endif

#ifdef JAVA_USE_RESERVE_STRING
	ADD_APPLICATION_STRING2(STR_JAVA_UPDATE,"Update","STR_JAVA_UPDATE");
#endif
	ADD_APPLICATION_STRING2(STR_JAVA_UPDATE_ASK,"Update?","STR_JAVA_UPDATE_ASK");
	ADD_APPLICATION_STRING2(STR_JAVA_START_UPDATING,"Start Updating","STR_JAVA_START_UPDATING");
	ADD_APPLICATION_STRING2(STR_JAVA_UPDATED,"Updated~","STR_JAVA_UPDATED");
#ifdef JAVA_USE_RESERVE_STRING
	ADD_APPLICATION_STRING2(STR_JAVA_UPDATE_FAILED,"Update failed~","STR_JAVA_UPDATE_FAILED");
#endif

	ADD_APPLICATION_STRING2(STR_JAVA_LAUNCH_ASK,"Launch?","STR_JAVA_LAUNCH_ASK");
	ADD_APPLICATION_STRING2(STR_JAVA_KEEP_RMS,"Keep data?","STR_JAVA_KEEP_RMS");
	ADD_APPLICATION_STRING2(STR_JAVA_STOPPED,"Java Application Stopped","STR_JAVA_STOPPED");

	ADD_APPLICATION_STRING2(STR_JAVA_VM_BUSY,"Java engine Busy","STR_JAVA_VM_BUSY");
	ADD_APPLICATION_STRING2(STR_JAVA_WAIT,"Please Wait!","STR_JAVA_WAIT");

	ADD_APPLICATION_STRING2(STR_JAVA_LAUNCH_AFTER_INSTALL,"Will you want to launch this java midlet?","STR_JAVA_LAUNCH_AFTER_INSTALL");
	ADD_APPLICATION_STRING2(STR_JAVA_TERMINATE_DIALOG_TITLE,"Stop or pause ","STR_JAVA_TERMINATE_DIALOG_TITLE");
	ADD_APPLICATION_STRING2(STR_JAVA_RESUME_DIALOG_TITLE,"Stop or resume ","STR_JAVA_RESUME_DIALOG_TITLE");	
	ADD_APPLICATION_STRING2(STR_JAVA_PAUSE,"Pause the java midlet","STR_JAVA_PAUSE");	
	ADD_APPLICATION_STRING2(STR_JAVA_RESUME,"Resume the java midlet","STR_JAVA_RESUME");
	ADD_APPLICATION_STRING2(STR_JAVA_TERMINATE,"Terminate","STR_JAVA_TERMINATE");
	ADD_APPLICATION_STRING2(STR_JAVA_BUSY_FOR_PAUSE_MODE,"Java game is paused. We can't execute another function.","STR_JAVA_BUSY_FOR_PAUSE_MODE");
	ADD_APPLICATION_STRING2(STR_JAVA_STOP_TIMEALARM_FOR_PAUSE_MODE,"Java game is paused. We can't time alarm another java game.","STR_JAVA_STOP_TIMEALARM_FOR_PAUSE_MODE");	
	ADD_APPLICATION_STRING2(STR_JAVA_FORCE_TERMINATE,"The Java program is using critical resources and can not be paused. Do you want to terminate the program?","STR_JAVA_FORCE_TERMINATE");	


	// add by hjf
	ADD_APPLICATION_STRING2(STR_JAVA_START_UPDATE_ASK,"Do you want the update application from internet?","STR_JAVA_UPDATE_ASK");
	ADD_APPLICATION_STRING2(STR_JAVA_PUSH_LAUNCH_ASK,"Do you want to launch pushed MIDlet?","STR_JAVA_PUSH_LAUNCH_ASK");
	ADD_APPLICATION_STRING2(STR_JAVA_RESET_RMS_ASK,"Do you want the new version application to be able to use the information stored by the old version application?","STR_JAVA_RESET_RMS_ASK");

    /* VM error message and installation message added by Justin */	
	ADD_APPLICATION_STRING2(STR_JAVA_ALERT,"The Java application cannot execute","STR_JAVA_ALERT");
	ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_OLD_VERSION,"An OLDER version of midlet has been found. Continuing will replace the version installed on your phone.\n\nCurrently installed: %5\nVersion found: %3\nVendor: %2\nWebsite: %4\n\nWould you like to continue?","STR_JAVA_ERROR_CODE_OLD_VERSION");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_ALREADY_INSTALLED,"This version of midlet has been found. Continuing will replace the version installed on your phone.\n\nCurrently installed: %5\nVersion found: %3\nVendor: %2\nWebsite: %4\n\nWould you like to continue?","STR_JAVA_ERROR_CODE_ALREADY_INSTALLED");
	ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_NEW_VERSION,"A NEWER version of midlet has been found. Continuing will replace the version installed on your phone.\n\nCurrently installed: %5\nVersion found: %3\nVendor: %2\nWebsite: %4\n\nWould you like to continue?","STR_JAVA_ERROR_CODE_NEW_VERSION");
	ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_NOT_FOUND,"AP not found","STR_JAVA_ERROR_CODE_NOT_FOUND");
	ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_INVALID_JAD,"Invalid application file(.jad)","STR_JAVA_ERROR_CODE_INVALID_JAD");
	ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_MISSING_INFO_JAD,"Critical info is missing in JAD","STR_JAVA_ERROR_CODE_MISSING_INFO_JAD");
	ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_MISSING_INFO_JAR,"Critical info is missing in JAR","STR_JAVA_ERROR_CODE_MISSING_INFO");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_DEVICE_INCOMPATIBLE,"The Java AP not supported","STR_JAVA_ERROR_CODE_DEVICE_INCOMPATIBLE");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_JAD_MOVED,"The new version of midlet is not from the same provider as the old version. The download URLs do not match. Do you want to install the new version?\n\nOld URL: %5\nNew URL: %4","STR_JAVA_ERROR_CODE_JAD_MOVED");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_INSUFFICIENT_STORAGE,"More free space is needed for installation","STR_JAVA_ERROR_CODE_INSUFFICIENT_STORAGE1");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_JAR_NOT_FOUND,"JAR not found","STR_JAVA_ERROR_CODE_JAR_NOT_FOUND");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_INVALID_JAR_URL,"Invalid JAR URL","STR_JAVA_ERROR_CODE_INVALID_JAR_URL");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_CORRUPT_JAR,"The JAR file is corrupt","STR_JAVA_ERROR_CODE_CORRUPT_JAR");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_INFO_MISMATCH,"Critical info mismatch(jad, jar)","STR_JAVA_ERROR_CODE_INFO_MISMATCH");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_VERIFY_FAILED,"The AP files cannot verified","STR_JAVA_ERROR_CODE_VERIFY_FAILED");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_AUTHORIZATION_FAILURE,"Does not have permission it requires","STR_JAVA_ERROR_CODE_AUTHORIZATION_FAILURE");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_PUSH_DUP_FAILURE,"A resource is in use by another AP","STR_JAVA_ERROR_CODE_PUSH_DUP_FAILURE");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_PUSH_PROTO_FAILURE,"A network resource is not supported","STR_JAVA_ERROR_CODE_PUSH_PROTO_FAILURE");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_TRUSTED_OVERWRITE_FAILURE,"The new version is not authorized","STR_JAVA_ERROR_CODE_TRUSTED_OVERWRITE_FAILURE");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_DEFAULT_GAME,"Can not update a default AP","STR_JAVA_ERROR_CODE_DEFAULT_GAME");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_DISK_OP_FAILURE,"Network/disk operation failed","STR_JAVA_ERROR_CODE_DISK_OP_FAILURE");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_UNKNOWN_FAILURE,"Install failure","STR_JAVA_ERROR_CODE_UNKNOWN_FAILURE");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_CANCEL,"Operation cancelled","STR_JAVA_ERROR_CODE_CANCEL");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_OVER_MAX_INSTALL,"Over the maximum install limit","STR_JAVA_ERROR_CODE_OVER_MAX_INSTALL");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_POST_ERROR,"Installed, but the application not been confirmed","STR_JAVA_ERROR_CODE_POST_ERROR");
	ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_NO_CARD,"Drive Not Found","STR_JAVA_ERROR_CODE_NO_CARD");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_BT_IN_USE,"Please stop Bluetooth at first","STR_JAVA_ERROR_CODE_BT_IN_USE");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_MIDLET_RUNNING,"MIDlet is runng. Cannot Update now!" , "STR_JAVA_MIDLET_RUNNING")
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_IN_CALL,"In call now. Cannot Install now!" , "STR_JAVA_ERROR_CODE_IN_CALL")
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_WRITE_PROTECTION, "Memory card is locked",   "[Notify-Card locked, cant create folder]");
    ADD_APPLICATION_STRING2(STR_JAVA_ERROR_CODE_MEMORY_INSUFFICIENT,"Insufficient memory! Terminate Java firstly." , "STR_JAVA_ERROR_CODE_MEMORY_INSUFFICIENT")
    ADD_APPLICATION_STRING2(STR_JAVA_PUSH_INSTALL,"To work properly, %1 will need to start itself periodically to receive information. If there is already an application running, %1 will interrupt and that application will exit.","STR_JAVA_PUSH_INSTALL");
    ADD_APPLICATION_STRING2(STR_JAVA_NORMAL_INSTALL,"Are you sure you want to install \"%1\"? \nSize: %2K\nVersion: %3\nVendor: %4\nDescription: %5\nMedia-price: %6\nWebsite:%7","STR_JAVA_NORMAL_INSTALL");
    ADD_APPLICATION_STRING2(STR_JAVA_INSTALL_NA,"No information in the application file.","STR_JAVA_INSTALL_NA");

	ADD_APPLICATION_IMAGE2(IMG_JAVA_POWERED,CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JVLOGO.PBM","IMG_JAVA_POWERED");
	ADD_APPLICATION_IMAGE2(IMG_JAVA_STAR1,CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JVSTAR1.PBM","IMG_JAVA_STAR1");
	ADD_APPLICATION_IMAGE2(IMG_JAVA_STAR2,CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JVSTAR2.PBM","IMG_JAVA_STAR2");
	ADD_APPLICATION_IMAGE2(IMG_JAVA_DONE, CUST_IMG_PATH"\\\\MainLCD\\\\Warningpage\\\\PopUpPage\\\\PP_ACT"__MMI_RES_TYPE_POPUP_SCREEN__, "Activated image");
	ADD_APPLICATION_IMAGE2(IMG_JAVA_ABORT, "..\\\\..\\\\Customer\\\\Images\\\\EmptyImage.bmp", "Cancel image");


	ADD_APPLICATION_STRING2(STR_JAVA_PUSH_BUSY,"The request can not be completed. Please go to idle screen and wait for executing a PUSH program.","STR_JAVA_PUSH_BUSY");		
	
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_SOCKET,        "The application wants to receive information (Socket). This will require the use of airtime which may cost you money. Is this OK?"                     ,"STR_JAVA_PERMISSION_SOCKET")        
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_HTTP,          "The application wants to receive information (HTTP). This will require the use of airtime which may cost you money. Is this OK?"                       ,"STR_JAVA_PERMISSION_HTTP")          
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_HTTPS,         "The application wants to receive information (HTTPS). This will require the use of airtime which may cost you money. Is this OK?"                      ,"STR_JAVA_PERMISSION_HTTPS")         
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_SSL,           "The application wants to receive information (SSL). This will require the use of airtime which may cost you money. Is this OK?"                        ,"STR_JAVA_PERMISSION_SSL")           
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_DATAGRAM,      "The application wants to receive information (Datagram). This will require the use of airtime which may cost you money. Is this OK?"                   ,"STR_JAVA_PERMISSION_DATAGRAM")      
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_SVR_SOCKET,    "The application wants to recieve information (Server socket). This will require the use of airtime which may cost you money. Is this OK?"      ,"STR_JAVA_PERMISSION_SVR_SOCKET")        
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_SVR_DATAGRAM,  "The application wants to recieve information (Datagram server). This will require the use of airtime which may cost you money. Is this OK?"    ,"STR_JAVA_PERMISSION_SVR_DATAGRAM")      
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_COMM,          "The application wants to directly connect to a computer to exchange information(COMM). Is that OK?"                            ,"STR_JAVA_PERMISSION_COMM")          
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_PUSH,          "The application will need to start itself automatically. If there is already an application running, the application will interrupt and that application will exit. Is that OK?"                   ,"STR_JAVA_PERMISSION_PUSH")          
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_SMS,           "The application wants to send text message(s). This could result in charges. Is it OK?"                                  ,"STR_JAVA_PERMISSION_SMS")
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_CBS,           "The application wants to receive text message(s). Is this OK?"                              ,"STR_JAVA_PERMISSION_CBS")           
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_MMS,           "The application wants to send binary message(s) (MMS). This could result in charges. Is it OK?"                                  ,"STR_JAVA_PERMISSION_MMS")
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_RECORD_CTRL,   "The application wants to record a media clip. Is it OK?"                              ,"STR_JAVA_PERMISSION_RECORD_CTRL")
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_SNAPSHOT,      "The application wants to get an image snapshop. Is it OK?"                            ,"STR_JAVA_PERMISSION_SNAPSHOT")
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_FILE_READ,          "The application wants to read files on available disks. Is it OK?"                          ,"STR_JAVA_PERMISSION_FILE_READ");
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_FILE_WRITE,          "The application wants to write or modify files on available disks. Is it OK?"                          ,"STR_JAVA_PERMISSION_FILE_WRITE");
    ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_CONTACT_LIST_READ,    "The application want to read contact list. Is it OK?"  ,"STR_JAVA_PERMISSION_CONTACT_LIST_READ")
    ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_CONTACT_LIST_WRITE,   "The application want to write contact list. Is it OK?" ,"STR_JAVA_PERMISSION_CONTACT_LIST_WRITE")
    ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_EVENT_LIST_READ,      "The application want to read event list. Is it OK?"    ,"STR_JAVA_PERMISSION_EVENT_LIST_READ")
    ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_EVENT_LIST_WRITE,     "The application want to write event list. Is it OK?"   ,"STR_JAVA_PERMISSION_EVENT_LIST_WRITE")
    ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_TODO_LIST_READ,       "The application want to read todo list. Is it OK?"     ,"STR_JAVA_PERMISSION_TODO_LIST_READ")
    ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_TODO_LIST_WRITE,      "The application want to write todo list. Is it OK?"    ,"STR_JAVA_PERMISSION_TODO_LIST_WRITE")
    ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_TELEPHONE,          "The application wants to make a phone call which may cost you money. Is this OK?"                          ,"STR_JAVA_PERMISSION_TELEPHONE");
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_EXCLUSIVE_PUSH,          "The application is alread allowed to access network resource without asking and you are granting the application to start itself automatically at liberty. For security, we'll set the permission of network access to ask every time. Is it OK? (No for keeping the original security settings.)"                          ,"STR_JAVA_PERMISSION_EXCLUSIVE_PUSH");
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_EXCLUSIVE_NET,          "The application is alread allowed to start itself automatically without asking and you are granting the application to access network at liberty. For security, we'll set the permission of auto-invocation to ask every time. Is it OK? (No for keeping the original security settings.)"                          ,"STR_JAVA_PERMISSION_EXCLUSIVE_NET");
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_UNKNOWN,       "OK to do the action?"                            ,"STR_JAVA_PERMISSION_UNKNOWN")
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_TITLE,         "OK to do?"                            			 ,"STR_JAVA_PERMISSION_TITLE")
	ADD_APPLICATION_STRING2(STR_JAVA_PERMISSION_SETTING_FAIL, "Setting not modifiable"                        ,"STR_JAVA_PERMISSION_SETTING_FAIL")

#ifdef __MMI_FOURWAYS_KEY_DISABLE__
	ADD_APPLICATION_STRING2(STR_JAVA_CONFIRM_VIRTUAL_KEYPAD,         "Use virtual keypad in Java Game?"             , "STR_JAVA_CONFIRM_VIRTUAL_KEYPAD")
	ADD_APPLICATION_STRING2(STR_JAVA_CONFIRM_VIRTUAL_KEYPAD_TITLE,   "Virtual Keypad"                               , "STR_JAVA_CONFIRM_VIRTUAL_KEYPAD_TITLE")
#endif

	ADD_APPLICATION_STRING2(STR_JAVA_CONFIRM_BEARER_FALLBACK, "GPRS bearer is not available, do you want to switch to CSD bearer?", "STR_JAVA_CONFIRM_BEARER_FALLBACK")
	ADD_APPLICATION_STRING2(STR_JAVA_CONFIRM_BEARER_FALLBACK_TITLE, "Network Switch", "STR_JAVA_CONFIRM_BEARER_FALLBACK_TITLE")
	
    ADD_APPLICATION_STRING2(STR_JAVA_VM_TERMINATING,                 "Terminating"                                  , "STR_JAVA_VM_TERMINATING")
    ADD_APPLICATION_STRING2(STR_JAVA_NETWORK_SETTING_DEFAULT,        "Default"                                      , "STR_JAVA_NETWORK_SETTING_DEFAULT")
    ADD_APPLICATION_STRING2(STR_JAVA_TERMINATE_JAVA_GAME,       "A Java game is running. Do you want to terminate it now?" , "STR_JAVA_TERMINATE_JAVA_GAME")
    ADD_APPLICATION_STRING2(STR_JAVA_TERMINATE_EUREKA,       "EUREKA is running. Do you want to terminate it now?" , "STR_JAVA_TERMINATE_EUREKA")
    ADD_APPLICATION_STRING2(STR_JAVA_DATE,       "Date" , "STR_JAVA_DATE")
    ADD_APPLICATION_STRING2(STR_JAVA_TIME,       "Time" , "STR_JAVA_TIME")

	ADD_APPLICATION_MENUITEM((
		J2ME_MENU_FULLSCREEN_EDITOR_OPTION,0,2,
		J2ME_MENU_FULLSCREEN_EDITOR_OPTION_DONE,
		J2ME_MENU_FULLSCREEN_EDITOR_OPTION_INPUT_METHOD,
		SHOW, NONMOVEABLE, 
		DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));

	ADD_APPLICATION_MENUITEM((
				J2ME_MENU_FULLSCREEN_EDITOR_OPTION_DONE,
				J2ME_MENU_FULLSCREEN_EDITOR_OPTION,
				0, SHOW, NONMOVEABLE, 
				DISP_LIST,STR_GLOBAL_DONE,NULL));

	ADD_APPLICATION_MENUITEM((
				J2ME_MENU_FULLSCREEN_EDITOR_OPTION_INPUT_METHOD,
				J2ME_MENU_FULLSCREEN_EDITOR_OPTION,
				0, SHOW, NONMOVEABLE, 
				DISP_LIST,STR_GLOBAL_INPUT_METHOD,NULL));
}
#endif /* !__J2ME__ */
//MTK: Paul ended

#if defined(__MMI_RING_COMPOSER__) && defined(__MMI_IMELODY_SUPPORT__)
void PopulateRingComposer(void)
{
		ADD_APPLICATION_MENUITEM((MENU3103_RINGTONE_COMPOSER,MAIN_MENU_MULTIMEDIA_MENUID,
			0, 0,MOVEABLEACROSSPARENT|SHORTCUTABLE,1,STR_MENU3103_RINGTONE_COMPOSER,IMG_MENU3103_RINGTONE_COMPOSER));

	ADD_APPLICATION_IMAGE2(IMG_RING_COMPOSER_BACKGROUND,CUST_IMG_PATH"\\\\MainLCD\\\\ringcomposer\\\\Instrument\\\\R_BG.Gif","IMG RingComposer Background");
	//start vijay 20050402
	ADD_APPLICATION_IMAGE2(IMG_TOUCH_RING_COMPOSER_BACKGROUND,CUST_IMG_PATH"\\\\MainLCD\\\\ringcomposer\\\\Instrument\\\\TH_R_BG.Gif","IMG RingComposer Background");
	//end vijay
	/** ring composer /dot/ image files **/

	ADD_APPLICATION_IMAGE2(	IMG_3BY2_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\WNOTE.bmp","3By 2 Lower Octave");
	ADD_APPLICATION_IMAGE2(	IMG_3BY2_OCT_L_M_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\WNOTEFLA.bmp","3By 2 Lower Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_3BY2_OCT_L_M_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\WNOTESHA.bmp","3By 2 Lower Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_3BY2_OCT_U_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\WNOTE_H.bmp","3By 2 Upper Octave");
	ADD_APPLICATION_IMAGE2(	IMG_3BY2_OCT_U_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\WNOTEFLA_H.bmp","3By 2 Upper Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_3BY2_OCT_U_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\WNOTESHA_H.bmp","3By 2 Upper Octave ");


	ADD_APPLICATION_IMAGE2(	IMG_1_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\WNOTE.bmp","1 Lower Octave");
	ADD_APPLICATION_IMAGE2(	IMG_1_OCT_L_M_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\flat\\\\WNOTE.bmp","1 Lower Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_1_OCT_L_M_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\sharp\\\\NOTE.bmp","1 Lower Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_1_OCT_U_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\WNOTE_H.bmp","1 Upper Octave");
	ADD_APPLICATION_IMAGE2(	IMG_1_OCT_U_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\flat\\\\WNOTE_H.bmp","1 Upper Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_1_OCT_U_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\sharp\\\\note_H.bmp","1 Upper Octave ");


	ADD_APPLICATION_IMAGE2(	IMG_3BY4_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\2NOTE.bmp","3By 4 Lower Octave");
	ADD_APPLICATION_IMAGE2(	IMG_3BY4_OCT_L_M_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\2NOTEFLA.bmp","3By 4 Lower Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_3BY4_OCT_L_M_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\2NOTESHA.bmp","3By 4 Lower Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_3BY4_OCT_U_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\2NOTE_H.bmp","3By 2 Upper Octave");
	ADD_APPLICATION_IMAGE2(	IMG_3BY4_OCT_U_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\2NOTEFLA_H.bmp","3By 2 Upper Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_3BY4_OCT_U_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\2NOTESHA_H.bmp","3By 2 Upper Octave ");


	ADD_APPLICATION_IMAGE2(	IMG_1BY2_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\2NOTE.bmp","1 Lower Octave");
	ADD_APPLICATION_IMAGE2(	IMG_1BY2_OCT_L_M_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\flat\\\\2NOTE.bmp","1 Lower Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_1BY2_OCT_L_M_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\sharp\\\\2NOTE.bmp","1 Lower Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_1BY2_OCT_U_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\2NOTE_H.bmp","1 Upper Octave");
	ADD_APPLICATION_IMAGE2(	IMG_1BY2_OCT_U_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\flat\\\\2NOTE_H.bmp","1 Upper Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_1BY2_OCT_U_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\sharp\\\\2NOTE_H.bmp","1 Upper Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_3BY8_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\4NOTE.bmp","3By 4 Lower Octave");
	ADD_APPLICATION_IMAGE2(	IMG_3BY8_OCT_L_M_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\4NOTEFLA.bmp","3By 4 Lower Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_3BY8_OCT_L_M_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\4NOTESHA.bmp","3By 4 Lower Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_3BY8_OCT_U_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\4NOTE_H.bmp","3By 2 Upper Octave");
	ADD_APPLICATION_IMAGE2(	IMG_3BY8_OCT_U_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\4NOTEFLA_H.bmp","3By 2 Upper Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_3BY8_OCT_U_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\4NOTESHA_H.bmp","3By 2 Upper Octave ");


	ADD_APPLICATION_IMAGE2(	IMG_1BY4_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\4NOTE.bmp","1 Lower Octave");
	ADD_APPLICATION_IMAGE2(	IMG_1BY4_OCT_L_M_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\flat\\\\4NOTE.bmp","1 Lower Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_1BY4_OCT_L_M_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\sharp\\\\4NOTE.bmp","1 Lower Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_1BY4_OCT_U_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\4NOTE_H.bmp","1 Upper Octave");
	ADD_APPLICATION_IMAGE2(	IMG_1BY4_OCT_U_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\flat\\\\4NOTE_H.bmp","1 Upper Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_1BY4_OCT_U_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\sharp\\\\4NOTE_H.bmp","1 Upper Octave ");


	ADD_APPLICATION_IMAGE2(	IMG_3BY16_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\8NOTE.bmp","3By 4 Lower Octave");
	ADD_APPLICATION_IMAGE2(	IMG_3BY16_OCT_L_M_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\8NOTEFLA.bmp","3By 4 Lower Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_3BY16_OCT_L_M_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\8NOTESHA.bmp","3By 4 Lower Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_3BY16_OCT_U_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\8NOTE_H.bmp","3By 2 Upper Octave");
	ADD_APPLICATION_IMAGE2(	IMG_3BY16_OCT_U_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\8NOTEFLA_H.bmp","3By 2 Upper Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_3BY16_OCT_U_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\8NOTESHA_H.bmp","3By 2 Upper Octave ");


	ADD_APPLICATION_IMAGE2(	IMG_1BY8_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\8NOTE.bmp","1 Lower Octave");
	ADD_APPLICATION_IMAGE2(	IMG_1BY8_OCT_L_M_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\flat\\\\8NOTE.bmp","1 Lower Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_1BY8_OCT_L_M_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\sharp\\\\8NOTE.bmp","1 Lower Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_1BY8_OCT_U_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\8NOTE_H.bmp","1 Upper Octave");
	ADD_APPLICATION_IMAGE2(	IMG_1BY8_OCT_U_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\flat\\\\8NOTE_H.bmp","1 Upper Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_1BY8_OCT_U_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\sharp\\\\8NOTE_H.bmp","1 Upper Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_3BY32_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\16NOTE.bmp","3By 4 Lower Octave");
	ADD_APPLICATION_IMAGE2(	IMG_3BY32_OCT_L_M_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\16NOTEFLA.bmp","3By 4 Lower Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_3BY32_OCT_L_M_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\16NOTESHA.bmp","3By 4 Lower Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_3BY32_OCT_U_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\16NOTE_H.bmp","3By 2 Upper Octave");
	ADD_APPLICATION_IMAGE2(	IMG_3BY32_OCT_U_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\16NOTEFLA_H.bmp","3By 2 Upper Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_3BY32_OCT_U_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\16NOTESHA_H.bmp","3By 2 Upper Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_1BY16_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\16NOTE.bmp","1 Lower Octave");
	ADD_APPLICATION_IMAGE2(	IMG_1BY16_OCT_L_M_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\flat\\\\16NOTE.bmp","1 Lower Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_1BY16_OCT_L_M_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\sharp\\\\16NOTE.bmp","1 Lower Octave ");

	ADD_APPLICATION_IMAGE2(	IMG_1BY16_OCT_U_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\16NOTE_H.bmp","1 Upper Octave");
	ADD_APPLICATION_IMAGE2(	IMG_1BY16_OCT_U_F,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\flat\\\\16NOTE_H.bmp","1 Upper Octave ");
	ADD_APPLICATION_IMAGE2(	IMG_1BY16_OCT_U_S,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\sharp\\\\16NOTE_H.bmp","1 Upper Octave ");
	
	
	ADD_APPLICATION_IMAGE2(	IMG_3BY8_OCT_L_M,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\4Rest.bmp","Rest Note");
	ADD_APPLICATION_IMAGE2(	IMG_1BY4_OCT_L_M,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\4Rest.bmp","Rest Note");
	
	ADD_APPLICATION_IMAGE2(	IMG_3BY16_OCT_L_M,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\8Rest.bmp","Rest Note");
	ADD_APPLICATION_IMAGE2(	IMG_1BY8_OCT_L_M,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\8Rest.bmp","Rest Note");
	
	ADD_APPLICATION_IMAGE2(	IMG_3BY32_OCT_L_M,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\dot\\\\16Rest.bmp","Rest Note");
	ADD_APPLICATION_IMAGE2(	IMG_1BY16_OCT_L_M,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\note\\\\16Rest.bmp","Rest Note");

	ADD_APPLICATION_IMAGE2(	IMG_RING_EVENTBL_ON,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\event\\\\BL.bmp","IMG_RING_EVENT1");
	ADD_APPLICATION_IMAGE2(	IMG_RING_EVENTBL_OFF,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\event\\\\BLOFF.bmp","IMG_RING_EVENT1");
	ADD_APPLICATION_IMAGE2(	IMG_RING_EVENTLED_ON,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\event\\\\LIGHT.bmp","IMG_RING_EVENT2");
	ADD_APPLICATION_IMAGE2(	IMG_RING_EVENTLED_OFF,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\event\\\\LIGHT_N.bmp","IMG_RING_EVENT3");
	ADD_APPLICATION_IMAGE2(	IMG_RING_EVENTVIB_ON,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\event\\\\VIB.bmp","IMG_RING_EVENT4");
	ADD_APPLICATION_IMAGE2(	IMG_RING_EVENTVIB_OFF,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\event\\\\VIB_N.bmp","IMG_RING_EVENT5");
	//start vijay 20050331
//#ifdef __MMI_TOUCH_RING_COMPOSER__
	ADD_APPLICATION_IMAGE2(	TOUCH_IMG_1_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\notes\\\\TH_WNOTE.bmp","1 Lower Octave");
	ADD_APPLICATION_IMAGE2(	TOUCH_IMG_1BY2_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\notes\\\\TH_2NOTE.bmp","1 Lower Octave");
	ADD_APPLICATION_IMAGE2(	TOUCH_IMG_1BY4_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\notes\\\\TH_4NOTE.bmp","1 Lower Octave");
	ADD_APPLICATION_IMAGE2(	TOUCH_IMG_1BY8_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\notes\\\\TH_8NOTE.bmp","1 Lower Octave");
	ADD_APPLICATION_IMAGE2(	TOUCH_IMG_1BY16_OCT_L_M_N,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\notes\\\\TH_16NOTE.bmp","1 Lower Octave");
	ADD_APPLICATION_IMAGE2(	TOUCH_IMG_1BY4_OCT_L_M,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\notes\\\\TH_4Rest.bmp","Rest Note");
	ADD_APPLICATION_IMAGE2(	TOUCH_IMG_1BY8_OCT_L_M,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\notes\\\\TH_8Rest.bmp","Rest Note");
	ADD_APPLICATION_IMAGE2(	TOUCH_IMG_1BY16_OCT_L_M,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\notes\\\\TH_16Rest.bmp","Rest Note");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RNGC_HASH,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\notes\\\\TH_HASH.bmp","IMG_RING_HASH");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_P,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\notes\\\\TH_DOWN.bmp","IMG_RING_DOWN");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_DOT,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\notes\\\\TH_DOT.bmp","IMG_RING_DOT");

	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_OK,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\Symbol\\\\OK.bmp","IMG_RING_OK");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_NEXT,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\Symbol\\\\NEXT.bmp","IMG_RING_NEXT");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_PREV,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\Symbol\\\\PREV.bmp","IMG_RING_PREV");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_EDIT,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\Symbol\\\\EDIT.bmp","IMG_RING_EDIT");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_INSERT,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\Symbol\\\\INSERT.bmp","IMG_RING_INSERT");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_PLAY,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\Symbol\\\\PLAY.bmp","IMG_RING_PLAY");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_PAUSE,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\Symbol\\\\PAUSE.bmp","IMG_RING_PAUSE");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_UP,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\Symbol\\\\UP.bmp","IMG_RING_UP");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_DOWN,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\Symbol\\\\DOWN.bmp","IMG_RING_DOWN");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_SELECTION,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\ringbg\\\\TH_selectionarea.bmp","IMG_RING_SELECTION_AREA");
	ADD_APPLICATION_IMAGE2(	IMG_TOUCH_RING_NORMAL,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\ringbg\\\\TH_toolbar.bmp","IMG_RING_NORMAL_TOOLBAR");
//#endif
	//end vijay

	/** instrumnet images **/

	ADD_APPLICATION_IMAGE2(	IMG_RING_INSTRU1,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\instrument\\\\R_DRUM.bmp","IMG_RING_INSTRU1");
	ADD_APPLICATION_IMAGE2(	IMG_RING_INSTRU2,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\instrument\\\\R_FLUTE.bmp","IMG_RING_INSTRU2");
	ADD_APPLICATION_IMAGE2(	IMG_RING_INSTRU3,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\instrument\\\\R_GUITR.bmp","IMG_RING_INSTRU3");
	ADD_APPLICATION_IMAGE2(	IMG_RING_INSTRU4,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\instrument\\\\R_HARM.bmp","IMG_RING_INSTRU4");
	ADD_APPLICATION_IMAGE2(	IMG_RING_INSTRU5,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\instrument\\\\R_MUSBOX.bmp","IMG_RING_INSTRU5");
	ADD_APPLICATION_IMAGE2(	IMG_RING_INSTRU6,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\instrument\\\\R_PIANO.bmp","IMG_RING_INSTRU6");
	ADD_APPLICATION_IMAGE2(	IMG_RING_INSTRU7,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\instrument\\\\R_SAX.bmp","IMG_RING_INSTRU7");
	ADD_APPLICATION_IMAGE2(	IMG_RING_INSTRU8,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\instrument\\\\R_VLION.bmp","IMG_RING_INSTRU8");
	ADD_APPLICATION_IMAGE2(	IMG_RING_INSTRU9,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\instrument\\\\R_TRUM.bmp","IMG_RING_INSTRU9");
	ADD_APPLICATION_IMAGE2(	IMG_RING_INSTRU10,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\instrument\\\\R_XYLO.bmp","IMG_RING_INSTRU10");
/*[~PMT MANISH 20050616*/
#if (defined(__MMI_MAINLCD_240X320__) || defined(__MMI_MAINLCD_320X240__))
	ADD_APPLICATION_IMAGE2( IMG_RING_INSTRU_LEFT_ARROW_UP,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\Arrow\\\\TH_L_UP.bmp","Ring Composer Instrument Select Left Arrow");
	ADD_APPLICATION_IMAGE2( IMG_RING_INSTRU_RIGHT_ARROW_UP,CUST_IMG_PATH"\\\\MainLCD\\\\RingComposer\\\\Touch\\\\Arrow\\\\TH_R_UP.bmp","Ring Composer Instrument Select Right Arrow");
#endif	/* __MMI_MAINLCD_240X320__ */
/*~]*/
	ADD_APPLICATION_STRING2(STR_RING_COMPOSE_TITLE,"Stave" , "Ring Composer caption");
}
#endif //#if defined(__MMI_RING_COMPOSER__)

void populateFunAndGamesMenu(void)
{


	ADD_APPLICATION_STRING2(STR_SCR3000_FUNANDGAMES_CAPTION,"Fun & Games","Menu Theme String");
#ifdef __MMI_OP01_MENU_9MATRIX__
/* under construction !*/
/* under construction !*/
#else /* __MMI_OP01_MENU_9MATRIX__ */
	ADD_APPLICATION_MENUITEM((MENU3105_GAMES,MAIN_MENU_FUNANDGAMES_MENUID,
		0, 	0,MOVEABLEACROSSPARENT|SHORTCUTABLE,1,STR_MENU3105_GAMES,IMG_MENU3105_GAMES));
#endif /* __MMI_OP01_MENU_9MATRIX__ */




#ifdef __MMI_MOTION_APP__
	ADD_APPLICATION_MENUITEM((	MENU_ID_MOTION_APP,
#ifdef __MMI_OP01_MENU_9MATRIX__
/* under construction !*/
#else
										MAIN_MENU_FUNANDGAMES_MENUID,
#endif
										0,	
										0,
										MOVEABLEACROSSPARENT|SHORTCUTABLE,
										1, 
										STR_ID_MOTION_APP, 
										IMG_ID_MOTION_APP));
#endif /* __MMI_MOTION_APP__ */
	
#ifdef __MMI_3D_GAME__
	ADD_APPLICATION_MENUITEM((	MENU_ID_FNG_3D_GAME,
#ifdef __MMI_OP01_MENU_9MATRIX__
/* under construction !*/
#else
										MAIN_MENU_FUNANDGAMES_MENUID,
#endif
										0,	
										0,
										MOVEABLEACROSSPARENT|SHORTCUTABLE,
										1, 
										STR_ID_3D_GAME, 
										IMG_ID_3D_GAME));

#endif /* __MMI_3D_GAME__ */


#ifndef __MMI_VOICE_MEMO__
#ifdef __MMI_OP01_MENU_9MATRIX__
/* under construction !*/
#else
	ADD_APPLICATION_MENUITEM((MENU3104_VOICE_MEMO,MAIN_MENU_FUNANDGAMES_MENUID,0,
#endif
		0,SHORTCUTABLE,1,STR_MENU3104_VOICE_MEMO,IMG_MENU3104_VOICE_MEMO));
#endif
	ADD_APPLICATION_STRING2(STR_MENU3101_THEMES,"Themes","Menu Theme String");

#ifdef __MMI_VOICE_MEMO__
	ADD_APPLICATION_STRING2(STR_MENU3104_VOICE_MEMO,"Voice Memo","Voice Memo menu");
#endif
	
//MTK Leo add
	ADD_APPLICATION_IMAGE2(IMG_MENU3101_THEMES,CUST_IMG_PATH"\\\\MainLCD\\\\Theme\\\\SB_FTH.PBM","Theme images");
	
#if defined(__MMI_RING_COMPOSER__) && defined(__MMI_IMELODY_SUPPORT__)	
#endif

#ifdef __MMI_VOICE_MEMO__
	ADD_APPLICATION_IMAGE2(IMG_MENU3104_VOICE_MEMO,CUST_IMG_PATH"\\\\MainLCD\\\\VoiceMemo\\\\SB_FVOICE.PBM","Voice memo image");
#endif
//MTK Leo end
#ifdef __MMI_THEMES_APPLICATION__
	PopulateThemes();
#endif

#ifdef __MMI_VOICE_MEMO__
   populateVoiceMemoMenu();
#endif

#ifdef __MMI_GAME__
	PopulateGamesRes();
#endif

#ifdef __MMI_3D_GAME__
	Populate3DGameRes();
#endif 

#ifdef __MMI_MOTION_APP__
	PopulateMotionAppRes();
#endif 

#ifdef __J2ME__
	ADD_APPLICATION_STRING2(STR_MENU3108_JAVA,"Java","Java menu");

	ADD_APPLICATION_IMAGE2(IMG_MENU3108_JAVA, CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_FGJAVA.pbm",	"Java icon");

	ADD_APPLICATION_MENUITEM((MENU3108_JAVA,MAIN_MENU_FUNANDGAMES_MENUID,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST, STR_MENU3108_JAVA,IMG_MENU3108_JAVA));

	PopulateJavaRes();
#endif /* __J2ME__ */


#if defined(__J2ME__)
	ADD_APPLICATION_MENUITEM((MENU_ID_FNG_SETTING_JAVA,MAIN_MENU_FUNANDGAMES_MENUID,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST, STR_ID_FNG_SETTING_JAVA,IMG_ID_FNG_SETTING_JAVA));

	ADD_APPLICATION_STRING2(STR_ID_FNG_SETTING_JAVA, "Java Setting", "Java Settings");	
	ADD_APPLICATION_IMAGE2(IMG_ID_FNG_SETTING_JAVA, CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JVST.pbm",	"effect setting");

	ADD_APPLICATION_STRING2(STR_ID_FNG_SETTING_JAVA_AUD, "Java Audio",		"Java Audio setting");
	ADD_APPLICATION_STRING2(STR_ID_FNG_SETTING_JAVA_VIB, "Java Vibration",		"Java Vibration setting");
    ADD_APPLICATION_STRING2(STR_ID_FNG_SETTING_JAVA_NET_ICON, "Java Net Icon",      "Java Network icon setting");

#ifdef __MMI_FOURWAYS_KEY_DISABLE__
    ADD_APPLICATION_STRING2(STR_ID_FNG_SETTING_JAVA_VK, "Java Virtual Keypad",		"Java Virtual Keypad");
#endif
	ADD_APPLICATION_STRING2(STR_ID_FNG_SETTING_JAVA_PROF_ID, "Java Network Profile",	"Java Network Profile");
#ifdef JAVA_SETTING_SHOW_FREE_STORAGE
	ADD_APPLICATION_STRING2(STR_ID_FNG_SETTING_JAVA_STORAGE, "Java Storge Size",	"Java Storge Size");
#endif
	ADD_APPLICATION_STRING2(STR_ID_FNG_SETTING_JAVA_HEAP, "Java Heap Size",	"Java Heap Size");

	ADD_APPLICATION_IMAGE2(IMG_ID_FNG_SETTING_JAVA_AUD, CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JAVAAUD.pbm",		"Java Audio Icon");	
	ADD_APPLICATION_IMAGE2(IMG_ID_FNG_SETTING_JAVA_VIB, CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JAVAVIB.pbm",		"Java Vibration Icon");	
	ADD_APPLICATION_IMAGE2(IMG_ID_FNG_SETTING_JAVA_NET_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JNET.pbm",		"Java Network Icon");
	ADD_APPLICATION_IMAGE2(IMG_ID_FNG_SETTING_JAVA_VK, CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JAVAVK.pbm",		"Java Virtual Keypad Icon");	
	ADD_APPLICATION_IMAGE2(IMG_ID_FNG_SETTING_JAVA_PROF_ID, CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JNET.PBM",	"Java Network Profile Icon");
	ADD_APPLICATION_IMAGE2(IMG_ID_FNG_SETTING_JAVA_STORAGE, CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JDATA.PBM",	"Java Storage Icon");	
	ADD_APPLICATION_IMAGE2(IMG_ID_FNG_SETTING_JAVA_HEAP, CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JHEAP.PBM",	"Java Heap Icon");	
#endif /* __J2ME__ */


/* Java Security Menu Item */
#ifdef __J2ME__
    #ifdef OGDR_SECURITY_SETTING
    ADD_APPLICATION_MENUITEM((MENU_ID_FNG_SECURITY_JAVA,MAIN_MENU_FUNANDGAMES_MENUID,0,
        SHOW, MOVEABLEACROSSPARENT, DISP_LIST, STR_ID_FNG_SECURITY_JAVA,IMG_ID_FNG_SECURITY_JAVA));
    ADD_APPLICATION_STRING2(STR_ID_FNG_SECURITY_JAVA, "Java Default Security", "Java Default Security");
    ADD_APPLICATION_STRING2(STR_ID_FNG_SECURITY_JAVA_RESTORE, "Restore Settings", "Restore Settings");
    ADD_APPLICATION_IMAGE2(IMG_ID_FNG_SECURITY_JAVA, CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JVST.pbm",  "effect setting");
    #endif

    #ifdef __SUPPORT_INFUSIO__
    ADD_APPLICATION_MENUITEM((MENU_ID_FNG_JAVA_EUREKA, MAIN_MENU_FUNANDGAMES_MENUID,0,
        SHOW, MOVEABLEACROSSPARENT, DISP_LIST, STR_ID_FNG_JAVA_EUREKA, IMG_ID_FNG_JAVA_EUREKA));

    ADD_APPLICATION_STRING2(STR_ID_FNG_JAVA_EUREKA, "EurekaClient", "EurekaClient");
    /* SHK: I add Eureka image. Currently, it is the same as Java Heap image. */
    ADD_APPLICATION_IMAGE2(IMG_ID_FNG_JAVA_EUREKA, CUST_IMG_PATH"\\\\MainLCD\\\\JAVA\\\\SB_JHEAP.PBM",  "Java Eureka Icon");
    #endif
#endif /* __J2ME__ */
}
#if defined(__MMI_THEMES_APPLICATION__)

void PopulateThemes(void)
{
#ifdef __MMI_OP01_MENU_9MATRIX__
/* under construction !*/
/* under construction !*/
#else /* __MMI_OP01_MENU_9MATRIX__ */
	ADD_APPLICATION_MENUITEM((MENU3101_THEMES,MAIN_MENU_FUNANDGAMES_MENUID,0,
	    0,MOVEABLEACROSSPARENT|SHORTCUTABLE,1,STR_MENU3101_THEMES,IMG_MENU3101_THEMES));	
#endif /* __MMI_OP01_MENU_9MATRIX__ */

#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__ 
	ADD_APPLICATION_MENUITEM((MENU3001_THEMES_LIST,0,5,
		MENU_THEMES_ACTIVATE,
		MENU3201_UPDATE_PERIOD,
		MENU3202_SET_ORDER,
		MENU_THEMES_DOWNLOAD,
		MENU_THEMES_DELETE,
		SHOW,NONMOVEABLE,1,STR_GLOBAL_OPTIONS,0));//ritesh
	ADD_APPLICATION_MENUITEM((MENU3001_THEMES_LIST_FLIGHTMODE,0,4,
		MENU_THEMES_ACTIVATE,
		MENU3201_UPDATE_PERIOD,
		MENU3202_SET_ORDER,
		MENU_THEMES_DELETE,
		SHOW,NONMOVEABLE,1,STR_GLOBAL_OPTIONS,0));
#else

	ADD_APPLICATION_MENUITEM((MENU3001_THEMES_LIST,0,3,
		MENU_THEMES_ACTIVATE,
		MENU3201_UPDATE_PERIOD,
		MENU3202_SET_ORDER,
		SHOW,NONMOVEABLE,1,STR_SCR3002_THEMES_OPTIONS_CAPTION,0));
#endif

/* Leo add for DLT */
	ADD_APPLICATION_MENUITEM((MENU_THEMES_ACTIVATE,MENU3001_THEMES_LIST,0,
	SHOW,MOVEABLEWITHINPARENT,1,STR_THEMES_ACTIVATE,0));
/* Leo end */

#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__
	ADD_APPLICATION_MENUITEM((MENU_THEMES_DOWNLOAD,MENU3001_THEMES_LIST,3,
	MENU_THEMES_DOWNLOAD_URL_DONE,
	MENU_THEMES_DOWNLOAD_URL_CANCEL,
	MENU_THEMES_DOWNLOAD_URL_INPUT_TYPE,
	SHOW,MOVEABLEWITHINPARENT,1,STR_THEMES_DOWNLOAD,0));

	ADD_APPLICATION_MENUITEM((MENU_THEMES_DELETE,MENU3001_THEMES_LIST,0,
	SHOW,MOVEABLEWITHINPARENT,1,STR_GLOBAL_DELETE,0));
	
	ADD_APPLICATION_MENUITEM((MENU_THEMES_DOWNLOAD_URL_DONE,MENU_THEMES_DOWNLOAD,0,
	SHOW,MOVEABLEWITHINPARENT,1,STR_GLOBAL_DONE,0));

    ADD_APPLICATION_MENUITEM((MENU_THEMES_DOWNLOAD_URL_CANCEL,MENU_THEMES_DOWNLOAD,0,
	SHOW,MOVEABLEWITHINPARENT,1,STR_GLOBAL_CANCEL,0));
	
	ADD_APPLICATION_MENUITEM((MENU_THEMES_DOWNLOAD_URL_INPUT_TYPE,MENU_THEMES_DOWNLOAD,0,
	SHOW,MOVEABLEWITHINPARENT,1,STR_GLOBAL_INPUT_METHOD,0));

#endif

#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__
	ADD_APPLICATION_MENUITEM((MENU3001_THEMES_LIST_1,0,4,
		MENU_THEMES_ACTIVATE,
		MENU3201_UPDATE_PERIOD,
		MENU3202_SET_ORDER,
		MENU_THEMES_DOWNLOAD,
		SHOW,NONMOVEABLE,1,STR_SCR3002_THEMES_OPTIONS_CAPTION,0));
	ADD_APPLICATION_MENUITEM((MENU3001_THEMES_LIST_1_FLIGHTMODE,0,3,
		MENU_THEMES_ACTIVATE,
		MENU3201_UPDATE_PERIOD,
		MENU3202_SET_ORDER,
		SHOW,NONMOVEABLE,1,STR_SCR3002_THEMES_OPTIONS_CAPTION,0));
#endif
	ADD_APPLICATION_MENUITEM((MENU_THEMES_ACTIVATE,MENU3001_THEMES_LIST,0,
	SHOW,NONMOVEABLE,1,STR_THEMES_ACTIVATE,0));


	ADD_APPLICATION_MENUITEM((MENU3201_UPDATE_PERIOD,MENU3001_THEMES_LIST,6,
		MENU3301_UPDATE_OFF,
		MENU3302_UPDATE_HOURLY,
		MENU3303_UPDATE_DAILY,
		MENU3304_UPDATE_WEEKLY,
		MENU_UPDATE_MONTHLY,
		MENU_UPDATE_SEASONALLY,
		SHOW,NONMOVEABLE,1,STR_MENU3201_UPDATE_PERIOD,IMG_MENU3201_UPDATE_PERIOD));

	ADD_APPLICATION_MENUITEM((MENU3202_SET_ORDER,MENU3001_THEMES_LIST,0,
		SHOW,NONMOVEABLE,1,STR_MENU3202_SET_ORDER,IMG_MENU3202_SET_ORDER));

	ADD_APPLICATION_MENUITEM((MENU3301_UPDATE_OFF,MENU3201_UPDATE_PERIOD,0,
	SHOW,NONMOVEABLE,1,STR_MENU3301_UPDATE_OFF,0));

	ADD_APPLICATION_MENUITEM((MENU3302_UPDATE_HOURLY,MENU3201_UPDATE_PERIOD,0,
		SHOW,NONMOVEABLE,1,STR_MENU3302_UPDATE_HOURLY,0));

	ADD_APPLICATION_MENUITEM((MENU3303_UPDATE_DAILY,MENU3201_UPDATE_PERIOD,0,
	SHOW,NONMOVEABLE,1,STR_MENU3303_UPDATE_DAILY,0));

	ADD_APPLICATION_MENUITEM((MENU3304_UPDATE_WEEKLY,MENU3201_UPDATE_PERIOD,0,
		SHOW,NONMOVEABLE,1,STR_MENU3304_UPDATE_WEEKLY,0));

	ADD_APPLICATION_MENUITEM((MENU_UPDATE_MONTHLY,MENU3201_UPDATE_PERIOD,0,
		SHOW,NONMOVEABLE,1,STR_MENU_UPDATE_MONTHLY,IMG_MENU_UPDATE_MONTHLY));

	ADD_APPLICATION_MENUITEM((MENU_UPDATE_SEASONALLY,MENU3201_UPDATE_PERIOD,0,
		SHOW,NONMOVEABLE,1,STR_MENU_UPDATE_SEASONALLY,IMG_MENU_UPDATE_SEASONALLY));

	ADD_APPLICATION_STRING2(STR_MENU_UPDATE_MONTHLY,"Monthly","STR_MENU_UPDATE_MONTHLY");	
	
	ADD_APPLICATION_STRING2(STR_MENU_UPDATE_SEASONALLY,"Seasonally","STR_MENU_UPDATE_SEASONALLY");	
#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__
	ADD_APPLICATION_MENUITEM((MENU_DOWNLOAD_THEMES_STORAGE,0,2,
		MENU_STORAGE_THEMES_PHONE,
		MENU_STORAGE_THEMES_CARD,
		SHOW,MOVEABLEWITHINPARENT,1,STR_SELECT_STORAGE_TITLE_ID,IMG_SELECT_STORAGE_TITLE_ID));

	ADD_APPLICATION_MENUITEM((MENU_STORAGE_THEMES_PHONE,MENU_DOWNLOAD_THEMES_STORAGE,0,
		SHOW,MOVEABLEWITHINPARENT,1,STR_ID_THEME_STORAGE_PHONE,IMG_MENU3202_SET_ORDER));

	ADD_APPLICATION_MENUITEM((MENU_STORAGE_THEMES_CARD,MENU_DOWNLOAD_THEMES_STORAGE,0,
	SHOW,MOVEABLEWITHINPARENT,1,STR_ID_THEME_STORAGE_CARD,0));

	ADD_APPLICATION_MENUITEM ((MENU_THM_DOWNLOAD_INPUT_METHOD_AND_DONE_OPTION_ID, 0, 2,
								MENU_THM_DOWNLOAD_DONE_OPTION_ID,
								MENU_INPUT_METHOD_OPTION_ID,
								HIDE, MOVEABLEWITHINPARENT, DISP_LIST,
								STR_GLOBAL_OPTIONS, 0));
	ADD_APPLICATION_MENUITEM ((MENU_THM_DOWNLOAD_DONE_OPTION_ID,
								MENU_THM_DOWNLOAD_INPUT_METHOD_AND_DONE_OPTION_ID, 0, 
								HIDE, MOVEABLEWITHINPARENT, DISP_LIST,
								STR_GLOBAL_DONE, 0));
	ADD_APPLICATION_MENUITEM ((MENU_INPUT_METHOD_OPTION_ID,
								MENU_THM_DOWNLOAD_INPUT_METHOD_AND_DONE_OPTION_ID, 0, 
								HIDE, MOVEABLEWITHINPARENT, DISP_LIST,
								STR_GLOBAL_INPUT_METHOD, 0));
#endif
	ADD_APPLICATION_STRING2(STR_THEMES_ACTIVATE,"Activate","STR_THEMES_ACTIVATE");	
	ADD_APPLICATION_STRING2(STR_MENU3201_UPDATE_PERIOD,"Update Period","STR_MENU3201_UPDATE_PERIOD");
	ADD_APPLICATION_STRING2(STR_MENU3202_SET_ORDER,"Set Order","STR_MENU3202_SET_ORDER");
#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__
	ADD_APPLICATION_STRING2(STR_THEMES_DOWNLOAD,"Download theme","Download Theme");
	ADD_APPLICATION_STRING2(STR_DOWNLOAD_INFO_TITLE_ID,"Theme Information","string id for Theme Information.");
	ADD_APPLICATION_STRING2(STR_SELECT_STORAGE_TITLE_ID,"Storage","String id for storage.");
	ADD_APPLICATION_STRING2(STR_DOWNLOAD_THEME_UNSUPPORTED,"Unsupported Content","String id for storage.");
	ADD_APPLICATION_STRING2(STR_LCD_SIZE_MISMATCH,"Screen Size Mismatch","String id for storage.");
	ADD_APPLICATION_STRING2(STR_ID_DOWNLOAD_THEME_FILE_NAME,"Name:","String id for theme file info.");
	ADD_APPLICATION_STRING2(STR_ID_DOWNLOAD_THEME_FILE_SIZE,"Size:","String id for theme file size info.");
	ADD_APPLICATION_STRING2(STR_ID_DOWNLOAD_THEME_URL,"URL:","String id for URL info.");
	ADD_APPLICATION_STRING2(STR_ID_THEME_STORAGE_PHONE,"Phone","String id for storage on Phone.");
	ADD_APPLICATION_STRING2(STR_ID_THEME_STORAGE_CARD,"Memory Card","String id for storage on card.");
	ADD_APPLICATION_STRING2(STR_ID_THEME_DOWNLOAD_COMPLETE,"Download completed. Do you want to apply?","String id for download complete.");
	ADD_APPLICATION_STRING2(STR_ID_DLT_DISK_FULL,"Memory Full","String id for Disk Full.");
	ADD_APPLICATION_STRING2(STR_ID_DLT_WRITE_PROTECTED,"Disk Write protected","String id for file write protected.");
	ADD_APPLICATION_STRING2(STR_ID_DLT_NO_MEMORY_CARD,"No Memory Card available","String id for No memory.");
	ADD_APPLICATION_STRING2(STR_ID_DLT_UNSUFFICIENT_MEMORY,"Unsufficient memory","String id for Unsufficient memory.");
	ADD_APPLICATION_STRING2(STR_ID_THEME_DOWNLOAD_ABORT,"Download Aborted","String id for Download abort.");
	ADD_APPLICATION_STRING2(STR_ID_USER_CANCEL,"Download Canceled","String id for Download use Cancel.");
	ADD_APPLICATION_STRING2(STR_ID_CONNECTION_BREAK,"Connection Failed","String id for Conection Break.");
	ADD_APPLICATION_STRING2(STR_ID_ERROR_DOWNLOAD,"Download Failed","String id for Error in download.");
	ADD_APPLICATION_STRING2(STR_ID_DLT_LCD_MISMATCH,"LCD Dimensions Mismatch. Do you want to continue","String id for LCD mismmatch query.");
	ADD_APPLICATION_STRING2(STR_ID_DLT_ERROR_CREATE_FILE,"Error in creating File","String id for error in creating file.");
	ADD_APPLICATION_STRING2(STR_ID_DLT_ERROR_IN_FILE,"Error in Downloaded File","String id for error in file.");
	ADD_APPLICATION_STRING2(STR_DOWNLOAD_ENTER_ADDRESS,"Input address","Enter Address ");
	ADD_APPLICATION_STRING2(STR_ID_DLT_THM_PROGRESS,"In Progress","progress string for theme activation");
	ADD_APPLICATION_STRING2(STR_DEFAULT_THEME_ACTIVATION,"Current Theme Not Found Activating Default Theme","string id for default theme");
	ADD_APPLICATION_STRING2(STR_THEME_INVALID_URL,"Invalid URL","invalid url string");

#endif
	ADD_APPLICATION_IMAGE2(IMG_MENU3201_UPDATE_PERIOD,CUST_IMG_BASE_PATH"\\\\NoImage.bmp","IMG_MENU3202_SET_ORDER");
#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__
	ADD_APPLICATION_IMAGE2(IMG_DOWNLOAD_TITLE_ID,CUST_IMG_BASE_PATH"\\\\NoImage.bmp","IMG_MENU3202_SET_ORDER");
	ADD_APPLICATION_IMAGE2(IMG_SELECT_STORAGE_TITLE_ID,CUST_IMG_BASE_PATH"\\\\NoImage.bmp","IMG_MENU3202_SET_ORDER");
#endif

	ADD_APPLICATION_IMAGE2(IMG_MENU3202_SET_ORDER,CUST_IMG_BASE_PATH"\\\\NoImage.bmp","IMG_MENU3202_SET_ORDER");
	ADD_APPLICATION_IMAGE2(IMG_SET_ORDER_MENU_CAPTION,CUST_IMG_BASE_PATH"\\\\NoImage.bmp","IMG_SET_ORDER_MENU_CAPTION");


	ADD_APPLICATION_STRING2(STR_MENU3301_UPDATE_OFF,"Off","STR_SCR3017_VIEW_PICTURE11");
	ADD_APPLICATION_STRING2(STR_MENU3302_UPDATE_HOURLY,"Hourly","STR_SCR3017_VIEW_PICTURE11");
	ADD_APPLICATION_STRING2(STR_MENU3303_UPDATE_DAILY,"Daily","STR_SCR3017_VIEW_PICTURE11");
	ADD_APPLICATION_STRING2(STR_MENU3304_UPDATE_WEEKLY,"Weekly","STR_SCR3017_VIEW_PICTURE11");

	ADD_APPLICATION_STRING2(STR_SCR3003_UPDATE_PERIOD_CAPTION,"Update Period","STR_SCR3017_VIEW_PICTURE11");
	
	ADD_APPLICATION_STRING2(STR_SCR3004_SET_ORDER_CAPTION,"Set Order","STR_SCR3017_VIEW_PICTURE11");

	ADD_APPLICATION_STRING2(STR_THEME_OFF_UPADTE_SUCCESS,"Done ","STR_SCR3017_VIEW_PICTURE11");

	ADD_APPLICATION_STRING2(STR_THEME_DEFAULT,"Default ","STR_THEME_DEFAULT");
	ADD_APPLICATION_STRING2(STR_THEME_THEME2,"Classic","STR_THEME_THEME2");
	ADD_APPLICATION_STRING2(STR_THEME_THEME3,"3D","STR_THEME_THEME3");
	ADD_APPLICATION_STRING2(STR_THEME_THEME4,"Theme4","STR_THEME_THEME4");
	ADD_APPLICATION_STRING2(STR_THEME_THEME5,"Theme5","STR_THEME_THEME5");
	ADD_APPLICATION_STRING2(STR_THEME_THEME6,"Theme6","STR_THEME_THEME6");
	ADD_APPLICATION_STRING2(STR_THEME_THEME7,"Theme7","STR_THEME_THEME7");
	ADD_APPLICATION_STRING2(STR_THEME_THEME8,"Theme8","STR_THEME_THEME8");
	ADD_APPLICATION_STRING2(STR_THEME_THEME9,"Theme9","STR_THEME_THEME9");
	ADD_APPLICATION_STRING2(STR_THEME_THEME10,"Theme10","STR_THEME_THEME10");
/* Added By Alok */
#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__
	ADD_APPLICATION_STRING2(STR_DOWNLOAD_ENTER_ADDRESS,"Input address","Input Address ");
#endif		
	ADD_APPLICATION_IMAGE2(IMAGE_THEME_SELECTED,CUST_IMG_BASE_PATH"\\\\EmptyImage.bmp","IMAGE_THEME_SELECTED");
	ADD_APPLICATION_IMAGE2(IMAGE_NOIMAGE_THEME,	CUST_IMG_BASE_PATH"\\\\NoImage.bmp","IMAGE_NOIMAGE_THEME");
#ifdef __MMI_THEMES_V2_SUPPORT__	
	ADD_APPLICATION_IMAGE2(IMAGE_PHONE_THEME,CUST_IMG_PATH"\\\\MainLCD\\\\Submenu\\\\Funandgame\\\\theme_p.pbm","IMAGE_PHONE_THEME");
	ADD_APPLICATION_IMAGE2(IMAGE_CARD_THEME,CUST_IMG_PATH"\\\\MainLCD\\\\Submenu\\\\Funandgame\\\\theme_c.pbm","IMAGE_CARD_THEME,");
	ADD_APPLICATION_IMAGE2(IMAGE_SYSTEM_THEME,CUST_IMG_PATH"\\\\MainLCD\\\\Submenu\\\\Funandgame\\\\theme_s.pbm","IMAGE_SYSTEM_THEME");
	ADD_APPLICATION_IMAGE2(IMAGE_ACTIVATED_THEME,CUST_IMG_PATH"\\\\MainLCD\\\\Submenu\\\\Funandgame\\\\theme_a.pbm","IMAGE_ACTIVATED_THEME");
#endif
	ADD_APPLICATION_IMAGE2(IMG_MENU_UPDATE_MONTHLY,	CUST_IMG_BASE_PATH"\\\\NoImage.bmp","IMAGE_NOIMAGE_THEME");
	ADD_APPLICATION_IMAGE2(IMG_MENU_UPDATE_SEASONALLY,	CUST_IMG_BASE_PATH"\\\\NoImage.bmp","IMAGE_NOIMAGE_THEME");

	ADD_APPLICATION_STRING2(STR_SCR3001_THEMES_CAPTION,"Themes","STR_SCR3001_THEMES_CAPTION");
#ifdef __MMI_THEMES_V2_SUPPORT__		
	ADD_APPLICATION_STRING2(STR_ID_DLT_THM_PROGRESS,"In Progress","progress string for theme activation");
	ADD_APPLICATION_STRING2(STR_DEFAULT_THEME_ACTIVATION,"Current Theme Not Found Activating Default Theme","STR_DEFAULT_THEME_ACTIVATION");
#endif
	ADD_APPLICATION_STRING2(STR_THEMES_ALARM_ACTIVATION,"Theme Updated","string id for theme activation during alarm");
	ADD_APPLICATION_IMAGE2(IMG_THEMES_CAPTION,	CUST_IMG_BASE_PATH"\\\\NoImage.bmp","IMAGE_NOIMAGE_THEME");

	ADD_APPLICATION_STRING2(STR_SCR3002_THEMES_OPTIONS_CAPTION,"Options","STR_SCR3002_THEMES_OPTIONS_CAPTION");

	ADD_APPLICATION_STRING2(STR_THEME_ACTIVATE_SUCCESS,"Activated","STR_THEME_ACTIVATE_SUCCESS");
#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__ //ritesh
	ADD_APPLICATION_STRING2(STR_THEME_NOT_AVAILABLE,"Theme Not Available","string id for theme not available");
#endif
//	ADD_APPLICATION_STRING2(STR_THEME_ALREADY_ACTIVATED,"Theme Already Active","STR_THEME_ALREADY_ACTIVATED");
#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__ //ritesh
	ADD_APPLICATION_STRING2(STR_THEME_DELETE_SUCCESS,"Deleted","string id for successful deletion of a theme ");
#endif
	
	ADD_APPLICATION_STRING2(STR_THEME_NONE,"None ","STR_THEME_NONE");
#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__	
	ADD_APPLICATION_STRING2(STR_THEME_FORMAT_NOT_SUPPORTED,"File Not Compatible","string id for format not supported for theme");
	ADD_APPLICATION_STRING2(STR_THEME_UNKNOWN_ERROR,"Unknown Error","STR_THEME_UNKNOWN_ERROR");
	ADD_APPLICATION_STRING2(STR_THEME_USB_MODE_DEFAULT_THEME,"USB Mode: Activating System Theme","STR_THEME_ERROR_USB_MODE");//Added by Shariq
	ADD_APPLICATION_STRING2(STR_THEME_ERROR_FILENAME_INCORRECT,"Incorrect Filename Type","string id for filename incorrect type like tilde, chinese etc");
    ADD_APPLICATION_STRING2(STR_THEME_ERROR_PHONE_MODEL_MISMATCH,"Incorrect Phone Model","string id for filename incorrect Phone Model");
    ADD_APPLICATION_STRING2(STR_THEME_ERROR_WAP_ALREADY_ACTIVE,"WAP Browser Alreay Active","WAP Browser App is already active");
    ADD_APPLICATION_STRING2(STR_THEME_FILE_DOWNLOADED,"Theme File","string id for theme file download");
#endif

	ADD_APPLICATION_IMAGE2(IMG_SET_THEME,CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\checkbox\\\\CK_V.bmp", "IMG_PROFILES_ACTIVATED");
#ifdef __MMI_THEMES_V2_SUPPORT__ //ritesh
	ADD_APPLICATION_IMAGE2(IMG_THEME_ACTIVATION	,CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\Progress\\\\PROGRESS"__MMI_RES_TYPE_POPUP_SCREEN__,"Processing Theme Activation icon");	
#endif

}
#endif


#endif


