#include "MMI_features.h" 
/*ShriKant*/
#ifdef __CERTMAN_SUPPORT__

//#include "StdC.h"
#include "CustomCfg.h"

#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif


#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"
#endif
#include "CertManMMIResDef.h"

void PopulateCertManRes(void)
{
	 /* resource ID check */
    if ((SCR_ID_CERTMAN_END > MMI_CERTMAN_BASE_MAX) ||
        (STR_CERTMAN_END > MMI_CERTMAN_BASE_MAX))
    {
        RESOURCE_ID_OUT_OF_RANGE_HANDLER();
    }
	ADD_APPLICATION_STRING2(STR_CERTMAN_INPUT_PASSWORD,"Input Password", "Input Password");
	ADD_APPLICATION_STRING2(STR_CERTMAN_PRIVATE_KEY," Private Key", "Private Key");
	ADD_APPLICATION_STRING2(STR_CERTMAN_PERSONAL_CERTIFICATE," Personal Certificate", "Personal Certificate");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERTIFICATE_INFO,"Certificate Info ", "Certificate Info ");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERTIFICATE_DISCARD,"Discard", "Discard");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERTIFICATE_DETAILS,"Certificate Details", "Certificate Details");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERTIFICATE_LABEL,"Label", "Certificate Label");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERTIFICATE_KEY_USAGE,"Key Usage", "Certificate Key Usage");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERTIFICATE_PRIVATE_KEY_PROTECTION,"Private Key Protection ", "Private Key Protection ");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERTIFICATE_PRIV_KEY_CONFIRMATION,"Confirmation ", "Confirmation method");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERTIFICATE_CONFIRM_PWD,"Confirm Password", "Confirm Password");
	ADD_APPLICATION_STRING2(STR_CERTMAN_FILE_CONTAINS,"FILE CONTAINS", "File Contains");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERT_TYPE,"Type", "Certificate Type");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERT_SERIAL_NO,"Serial No", "Certificate Serial Number");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERT_VERSION,"Version", "Certificate version");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERT_ISSUER,"Issuer", "Certificate Issued To");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERT_SUBJECT,"Subject", "Certificate Issued By");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERT_VALID_FROM,"Valid From", "Certificate Valid From");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERT_VALID_UPTO,"Valid To", "Certificate Valid To ");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERT_FINGER_PRINT,"Finger Print", "Finger Print");

	ADD_APPLICATION_STRING2(STR_CERTMAN_KP_ALL,"All", "All");
	ADD_APPLICATION_STRING2(STR_CERTMAN_KP_SERVER_AUTH ,"Server Authentication", "Server Authentication");
	ADD_APPLICATION_STRING2(STR_CERTMAN_KP_CLIENT_AUTH ,"Client Authentication", "Client Authentication");
	ADD_APPLICATION_STRING2(STR_CERTMAN_KP_CODE_SIGNING ,"Code Signing", "Code Signing");
	ADD_APPLICATION_STRING2(STR_CERTMAN_KP_EMAIL_PROTECTION ,"Email Protection", "Email Protection");
	ADD_APPLICATION_STRING2(STR_CERTMAN_KP_IPSEC_ENDSYSTEM,"Ip Security End System", "Ip Security End System");
	ADD_APPLICATION_STRING2(STR_CERTMAN_KP_IPSEC_TUNNEL,"Ip Security Tunnel", "Ip Security Tunnel");
	ADD_APPLICATION_STRING2(STR_CERTMAN_KP_IPSEC_USER ,"Ip Security User", "Ip Security User");
	ADD_APPLICATION_STRING2(STR_CERTMAN_KP_TIME_STAMPING ,"Time Stamping", "Time Stamping");
	ADD_APPLICATION_STRING2(STR_CERTMAN_KP_OCSP_SIGNING  ,"OCSP Signing", "OCSP Signing");


	ADD_APPLICATION_STRING2(STR_CERTMAN_MEMORY_FULL  ,"Memory Full","Memory Full");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_CONTEXT  ,"Invalid Context","Invalid Context");
	ADD_APPLICATION_STRING2(STR_CERTMAN_FILE_ERROR  ,"File Error","File Error");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_ENCODING  ,"Invalid Encoding","Invalid Encoding");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INCORRECT_PASSWORD  ,"Incorrect Password","Incorrect Password");
	ADD_APPLICATION_STRING2(STR_CERTMAN_NEED_PASSWORD  ,"Please Enter Password","Please Enter Password");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_JOB  ,"Invalid Job","Invalid Job");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_CERT_ID  ,"Invalid certificate","Invalid certificate");
	ADD_APPLICATION_STRING2(STR_CERTMAN_LABEL_EXISTS  ,"Label Exists","Label Exists");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_PASSWORD  ,"Invalid Password","Invalid Password");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_LABEL  ,"Invalid  Label","Invalid  Label");
	ADD_APPLICATION_STRING2(STR_CERTMAN_OUT_OF_RANGE  ,"Out of Range","Out of Range");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_CERT_GROUP  ,"Invalid Group","Invalid Group");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_KEY_PURPOSE  ,"Invalid Key Purpose","Invalid Key Purpose");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_DOMAIN  ,"Invalid Domain","Invalid Domain");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERTIFICATE_NOT_FOUND  ,"Certificate Not Found","Certificate Not Found");
	ADD_APPLICATION_STRING2(STR_CERTMAN_KEY_PURPOSE_DENIED  ,"Key purpose Denied","Key purpose Denied");
	ADD_APPLICATION_STRING2(STR_CERTMAN_KEY_NOT_FOUND  ,"Key Not Found","Key Not Found");
	ADD_APPLICATION_STRING2(STR_CERTMAN_ACCESS_DENIED  ,"Access Denied","Access Denied");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERT_EXISTS  ,"Certificate Already Exists","Certificate Already Exists");
	ADD_APPLICATION_STRING2(STR_CERTMAN_READ_ONLY  ,"Read Only Certificate","Read Only Certificate");
	ADD_APPLICATION_STRING2(STR_CERTMAN_NOT_SAVED  ,"Not Saved","Not Saved");
	ADD_APPLICATION_STRING2(STR_CERTMAN_DISCARDED  ,"Certificate Discarded","Certificate Discarded");
	ADD_APPLICATION_STRING2(STR_CERTMAN_MISMATCHED  ,"Password Mismatched","Password Mismatched");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERTTYPE_X509  ,"X.509","X.509 Certificate");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INSECURE_CERT  ,"Import Insecure Root Certificate","Import Insecure Root Certificate");
	ADD_APPLICATION_STRING2(STR_CERTMAN_EXPIRED_CERT  ,"Import Expired Certificate","Import Expired Certificate");
	ADD_APPLICATION_STRING2(STR_CERTMAN_MAX_LIMIT  ,"Max Limit Reached","Max limit Reached");

	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_DATA,"Invalid Data", "Invalid Data");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_INPUT,"Invalid input", "Invalid input");
	ADD_APPLICATION_STRING2(STR_CERTMAN_TOO_MANY_CERT,"Too Many certificates", "Too Many certificates");
	ADD_APPLICATION_STRING2(STR_CERTMAN_EXT_NOT_FOUND,"Extension Not Found", "Extension Not Found");
	ADD_APPLICATION_STRING2(STR_CERTMAN_SUBJECT_NOT_FOUND,"Subject Not Found", "Subject Not Found");
	ADD_APPLICATION_STRING2(STR_CERTMAN_ISSUER_NOT_FOUND,"Issuer not Found", "Issuer not Found");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CORRUPTED_DATA,"Corrupted data", "Corrupted data");
	
	ADD_APPLICATION_STRING2(STR_CERTMAN_CORRUPTED_FILE,"Corrupted File", "Corrupted File");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CONVERT_FAIL,"Convertion Fail", "Convertion Fail");





	ADD_APPLICATION_STRING2(STR_CERTMAN_CERTIFICATES,"Certificates","Certificates");
	ADD_APPLICATION_STRING2(STR_CERTMAN_AUTHORITY_CERT,"Authority Certificate","Authority Certificate");
	ADD_APPLICATION_STRING2(STR_CERTMAN_USER_CERT,"User Certificate","User Certificate");

	ADD_APPLICATION_STRING2(STR_CERTMAN_OPTION_KEY_USAGE,"Key Usage","Key Usage");
	ADD_APPLICATION_STRING2(STR_CERTMAN_CERTIFICATE_MANAGER,"Certificate Manager", "Certificate Manager");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_CERTIFICATE,"Invalid Certificate","Invalid Certificate");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_CERT_ERROR,"Invalid Certificate Error","Invalid Certificate Error");
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_CERT_CONTINUE,"Continue","Continue");

	
	ADD_APPLICATION_STRING2(STR_CERTMAN_INVALID_CERT_LABEL,"Invalid Certificate Label","Invalid Certificate Label");
	ADD_APPLICATION_STRING2(STR_CERTMAN_WARN_BCONST_NOT_CRITICAL,"Basic Constraints field is present, but marked as not critical","Critical");
	ADD_APPLICATION_STRING2(STR_CERTMAN_WARN_NO_TRUSTED_CERTS,"No trusted certificate","No trusted certificate");
	ADD_APPLICATION_STRING2(STR_CERTMAN_WARN_UNKNOWN_CRITICAL_EXT,"Unknown critical extension encountered","Unknown critical extension encountered");
	ADD_APPLICATION_STRING2(STR_CERTMAN_WARN_VALIDITY,"A certificate has expired, or has invalid validity date","A certificate has expired, or has invalid validity date");
	ADD_APPLICATION_STRING2(STR_CERTMAN_WARN_KEY_MISUSE,"One of the certificates in the chain is used not according to its key usage field","Cancel");
	ADD_APPLICATION_STRING2(STR_CERTMAN_WARN_INVALID_SIGNATURE," Certificate has Invalid signature","Cancel");
	ADD_APPLICATION_STRING2(STR_CERTMAN_WARN_CORRUPTED_CERT, "Corrupted certificate ","Corrupted");
	ADD_APPLICATION_STRING2(STR_CERTMAN_WARN_NO_CERT_HASH," SHA1 hash is not present for the certificate ","SHA1 hash is not present");
	ADD_APPLICATION_STRING2(STR_CERTMAN_WARN_URLS_DONT_MATCH,"Certificate hostname does not match with the url","Certificate hostname does not match");

	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_ALL_CERT,
									0,
									2,
									MENU_ID_CERTMAN_AUTHORITY_CERT,
									MENU_ID_CERTMAN_USER_CERT,
									SHOW, 	MOVEABLEWITHINPARENT, 	DISP_LIST,
									0, 	0));

	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_AUTHORITY_CERT,
									MENU_ID_CERTMAN_ALL_CERT,
									0,
									SHOW, 	MOVEABLEWITHINPARENT, 	DISP_LIST,
									STR_CERTMAN_AUTHORITY_CERT, 	0));

	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_USER_CERT,
									MENU_ID_CERTMAN_ALL_CERT,
										0,
										SHOW, 	MOVEABLEWITHINPARENT, 	DISP_LIST,
										STR_CERTMAN_USER_CERT, 	0));


	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_OPTIONS,
									0,
									3,
									MENU_ID_CERTMAN_OPTION_VIEW_CERTIFICATE,
									MENU_ID_CERTMAN_OPTION_DELETE_CERTIFICATE,
									MENU_ID_CERTMAN_OPTION_TRUST_SETTINGS_CERTIFICATE,
									SHOW, 	MOVEABLEWITHINPARENT, 	DISP_LIST,
									0, 	0));



	
	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_OPTION_VIEW_CERTIFICATE,
								   MENU_ID_CERTMAN_OPTIONS,
								   0, SHOW,
								   MOVEABLEWITHINPARENT,
								   DISP_LIST,
								   STR_CERTMAN_OPTION_VIEW,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_OPTION_DELETE_CERTIFICATE,
									MENU_ID_CERTMAN_OPTIONS,
									0,SHOW,
									MOVEABLEWITHINPARENT,
									DISP_LIST,
									STR_CERTMAN_OPTION_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_OPTION_TRUST_SETTINGS_CERTIFICATE,
								   MENU_ID_CERTMAN_OPTIONS,
								   0, SHOW,
								   MOVEABLEWITHINPARENT,
								   DISP_LIST, 
								   STR_CERTMAN_OPTION_KEY_USAGE,0));


	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_INVALID_OPTIONS1,
									0,
									3,
									MENU_ID_CERTMAN_INVALID_OPTION_INSTALL,
									MENU_ID_CERTMAN_INVALID_OPTION_CONTINUE,
									MENU_ID_CERTMAN_INVALID_OPTION_CANCEL,
									SHOW, 	MOVEABLEWITHINPARENT, 	DISP_LIST,
									0, 	0));
	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_INVALID_OPTION_INSTALL,
								   MENU_ID_CERTMAN_INVALID_OPTIONS1,
								   0, SHOW,
								   MOVEABLEWITHINPARENT,
								   DISP_LIST, 
								   STR_GLOBAL_INSTALL,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_INVALID_OPTION_CONTINUE,
								   MENU_ID_CERTMAN_INVALID_OPTIONS1,
								   0, SHOW,
								   MOVEABLEWITHINPARENT,
								   DISP_LIST, 
								   STR_CERTMAN_INVALID_CERT_CONTINUE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_INVALID_OPTION_CANCEL,
								   MENU_ID_CERTMAN_INVALID_OPTIONS1,
								   0, SHOW,
								   MOVEABLEWITHINPARENT,
								   DISP_LIST, 
								   STR_GLOBAL_CANCEL,0));


   ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_INVALID_OPTIONS2,
									0,
									2,
									MENU_ID_CERTMAN_INVALID_OPTION_CONTINUE,
									MENU_ID_CERTMAN_INVALID_OPTION_CANCEL,
									SHOW, 	MOVEABLEWITHINPARENT, 	DISP_LIST,
									0, 	0));
	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_INVALID_OPTION_CONTINUE,
								   MENU_ID_CERTMAN_INVALID_OPTIONS2,
								   0, SHOW,
								   MOVEABLEWITHINPARENT,
								   DISP_LIST, 
								   STR_CERTMAN_INVALID_CERT_CONTINUE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_CERTMAN_INVALID_OPTION_CANCEL,
								   MENU_ID_CERTMAN_INVALID_OPTIONS2,
								   0, SHOW,
								   MOVEABLEWITHINPARENT,
								   DISP_LIST, 
								   STR_GLOBAL_CANCEL,0));




	
}

#endif /*__CERTMAN_SUPPORT__*/
/*Shrikant*/
