/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *	Res_PoC.c
 *
 * Project:
 * --------
 *	MAUI
 *
 * Description:
 * ------------
 *	This file populates resource for PoC appliction.
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 * 				HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *============================================================================== 
 *******************************************************************************/

#ifndef _MMI_RES_POC_C
#define _MMI_RES_POC_C
#include "MMI_features.h"

#ifdef __MMI_POC__

#include "MMIDataType.h"
#include "CustomCfg.h"

#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif

#include "PocResDef.h"

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"


/**************************************************************

	FUNCTION NAME		: PoCResourceData

  	PURPOSE				: Register all the resources required by PoC application 

	INPUT PARAMETERS	: void

	OUTPUT PARAMETERS	: nil

	RETURNS				: void

	REMARKS				: nil

**************************************************************/
void PoCResourceData (void)
{
	// Images 
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\PoC\\\\SV_TYPE.PBM", "PoC Icon");
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_NOIMAGE, CUST_IMG_BASE_PATH"\\\\NoImage.bmp", "Blank Image for Inline Editor");
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_CONTACT_NAME, CUST_IMG_PATH"\\\\MainLCD\\\\PoC\\\\SV_NAME.PBM", "PoC Contact Name");
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_CONTACT_URI, CUST_IMG_PATH"\\\\MainLCD\\\\PoC\\\\SV_TYPE.PBM", "PoC Contact URI");	
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_CONTACT_ATTR, CUST_IMG_PATH"\\\\MainLCD\\\\PoC\\\\SV_SPEED.PBM", "PoC Contact URI");		
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_PROFILE_SELECTED,CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\checkbox\\\\CK_V.bmp", "PoC Selected Profile");

	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_DATE,CUST_IMG_PATH"\\\\MainLCD\\\\POC\\\\poc_date.pbm", "PoC Date");
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_TIME,CUST_IMG_PATH"\\\\MainLCD\\\\POC\\\\poc_time.pbm", "PoC Time");
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_MSG,CUST_IMG_PATH"\\\\MainLCD\\\\POC\\\\poc_msg.pbm", "PoC MSG");

//remember to update images
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_ONLINE, CUST_IMG_PATH"\\\\MainLCD\\\\POC\\\\poc_online.bmp", "Online image");
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_OFFLINE, CUST_IMG_PATH"\\\\MainLCD\\\\POC\\\\poc_offline.bmp", "Offline image");
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_BLOCK, CUST_IMG_PATH"\\\\MainLCD\\\\POC\\\\poc_block.bmp", "Offline image");	

	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_PROFILE_NAME, CUST_IMG_PATH"\\\\MainLCD\\\\PoC\\\\SV_ACCN.PBM", "PoC Profile Name");	
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_PROFILE_USER_NAME, CUST_IMG_PATH"\\\\MainLCD\\\\PoC\\\\SV_NAME.PBM", "PoC Profile User Name");	
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_PROFILE_URI, CUST_IMG_PATH"\\\\MainLCD\\\\PoC\\\\SV_TYPE.PBM", "PoC Profile URI");	
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_PROFILE_PASSWORD, CUST_IMG_PATH"\\\\MainLCD\\\\PoC\\\\SV_PASS.PBM", "PoC Profile Password");	
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_PROFILE_SERVER_ADDR, CUST_IMG_PATH"\\\\MainLCD\\\\PoC\\\\SV_SPEED.PBM", "PoC Profile address");	
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_PROFILE_SERVER_PORT, CUST_IMG_PATH"\\\\MainLCD\\\\PoC\\\\SV_DNS.PBM", "PoC Profile Port");	
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_PROFILE_XDM_ADDR, CUST_IMG_PATH"\\\\MainLCD\\\\PoC\\\\SV_SPEED.PBM", "PoC Profile address");	

	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_CM_INVITING, CUST_IMG_PATH"\\\\MainLCD\\\\POC\\\\Ca_poc_inviting.gif", "PoC ");	
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_CM_MO_RINGING, CUST_IMG_PATH"\\\\MainLCD\\\\POC\\\\Ca_poc_moring.gif", "PoC ");	
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_CM_MT_RINGING, CUST_IMG_PATH"\\\\MainLCD\\\\POC\\\\Ca_poc_mtring.gif", "PoC ");	
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_CM_CONNECTED_IDLE, CUST_IMG_PATH"\\\\MainLCD\\\\POC\\\\Ca_poc_connect.gif", "PoC ");	
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_CM_TALKING, CUST_IMG_PATH"\\\\MainLCD\\\\POC\\\\Cal_poc_talking.gif", "PoC ");	
	ADD_APPLICATION_IMAGE2 ( IMG_ID_POC_CM_LISTENING, CUST_IMG_PATH"\\\\MainLCD\\\\POC\\\\Ca_poc_listening.gif", "PoC ");	

	// Strings 
	ADD_APPLICATION_STRING2 ( STR_ID_POC_MAIN, "PoC", "PoC");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_STATUS, "PoC Status", "PoC Status");		
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CONTACTS, "Contacts", "PoC Contacts");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_TALK_GROUPS, "Talk Groups", "Talk Groups");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CALL_HISTORY, "Call History", "Call History");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_SETTINGS, "Settings", "Settings");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_SEND_ALERT, "Send Alert", "Send Alert");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ADHOC_TALK, "Adhoc Talk", "Adhoc Talk");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_REFRESH_STATUS, "Refresh Status", "Refresh Status");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ENTRY_SETTINGS, "Entry Settings", "Entry Settings");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_MODIFY, "Modify", "Modify");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_SESSION_ID, "Session ID", "Session ID");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_INFO, "Info", "Info");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ENTRY_INFO, "Entry Info", "Entry Info");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_NAME, "Name", "Name");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_URI, "URI", "URI");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ATTRIBUTES, "Attributes", "Attributes");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_DEFAULT_RULE, "Default Rule", "Default Rule");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_SET_ATTR, "Set Attr.", "Set Attr.");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ALLOW_INVITE, "Allow Invite", "Allow Invite");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ACCEPT, "Accept", "Accept");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_REJECT, "Reject", "Reject");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_POLITE_BLOCK, "Polite Block", "Polite Block");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_AUTO_ACCEPT, "Auto Accept", "Auto Accept");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ALLOW_SUBSCRIBE, "Allow Subscribe", "Allow Subscribe");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PROVIDE_PRES, "Provide Pres.", "Provide Pres.");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_SUBSCRIBE_PRES, "Subscribe Pres.", "Subscribe Pres.");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PRESENCE_ATTR, "Presence Attr.", "Presence Attr.");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PRESENCE_UPDATED, "Presence Updated.", "Presence Updated.");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_SUBSCRIBE, "Subscribe", "Subscribe");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_UNSUBSCRIBE, "Unsubscribe", "Unsubscribe");	

	ADD_APPLICATION_STRING2 ( STR_ID_POC_ACTIVITY, "Activity", "Activity");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_MOOD, "Mood", "Mood");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ALL, "All", "All");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ALERT_TEXT, "Alert Text", "Alert Text");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_SEND_FAKE, "Send Fake", "Send Fake");	

	ADD_APPLICATION_STRING2 ( STR_ID_POC_ADD_GROUP, "Add Group", "Add Group");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_DELETE_GROUP, "Delete Group", "Delete Group");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_GROUP_INFO, "Group Info", "Group Info");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CALL_OTHERS_GROUP, "Call Others Group", "Call Others Group");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ADD_FROM_CONTACTS, "Add From Contacts", "Add from Contacts");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CONF_STATE, "Conf. State", "Conf. State");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_INVITE_USER_DYNA, "Invite User Dyna.", "Invite User Dyna.");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_JOIN_HANDLING, "Join Handling", "Join Handling");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_INIT_CONFERENCE, "Init Conference", "Init Conference");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ANONYMITY, "Anonymity", "Anonymity");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_MAX_PARTICIPANTS, "Max Participants", "Max Participants");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_INVITE_MEMBER, "Invite Member", "Invite Member");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_MY_STATUS, "My Status", "My Status");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_NONE, "None", "None");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PRES_INFO, "Presence Info", "Presence Info");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_AWAY, "Away", "Away");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_APPOINTMENT, "Appointment", "Appointment");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_BUSY, "Busy", "Busy");
#if (0)
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
#endif
	ADD_APPLICATION_STRING2 ( STR_ID_POC_HAPPY, "Happy", "Happy");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_BORED, "Bored", "Bored");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_DEPRESSED, "Depressed", "Depressed");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ANSWER_MODE, "Answer Mode", "Answer Mode");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CALL_BARRING, "Call Barring", "Call Barring");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ALERT_BARRING, "Alert Barring", "Alert Barring");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_MAO, "Manual Answer Override", "Manual Answer Override");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PRIVACY, "Privacy", "Privacy");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_DISABLE, "Disable", "Disable");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ENABLE, "Enable", "Enable");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PRIVACY_ADDR, "Privacy Addr.", "Privacy Addr.");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_START_AT_BOOTUP, "Start at Boot Up", "PoC Start at Boot Up");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_USE_XDM, "Use XDM", "Use XDM");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_USE_PRES, "Use Presence", "Use Presence");		
#ifdef __MMI_POC_ADHOC_STR_INPUT__
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ADHOC_STR, "Adhoc String", "Adhoc String");	
#endif
	ADD_APPLICATION_STRING2 ( STR_ID_POC_POC_SETTINGS, "PoC Settings", "PoC Settings");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PROFILES, "Profiles", "Profiles");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PROFILE_1, "Profile 1", "PoC Profile 1");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PROFILE_2, "Profile 2", "PoC Profile 2");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PROFILE_3, "Profile 3", "PoC Profile 3");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PROFILE_NAME, "Profile Name", "PoC Profile Name");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PASSWORD, "Password", "Password");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_SERVER_ADDR, "Server Addr.", "Server Addr.");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_SERVER_PORT, "Server Port", "ServerPort");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_XDM_ADDR, "XDM Addr.", "XDM Addr.");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CONNECTION_SETTINGS, "Connection Settings", "Connection Settings");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_DATA_ACCOUNT, "Data Account", "Data Account");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_USE_PROXY, "Use Proxy", "Use Proxy");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PROXY_ADDR, "Proxy Addr.", "Proxy Addr.");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PROXY_PORT, "Proxy Port", "Proxy Port.");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PROXY_USERNAME, "Proxy Username", "Proxy Username");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_PROXY_PASSWORD, "Proxy Password", "Proxy Password");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_MESSAGE, "Message", "Message");

	ADD_APPLICATION_STRING2 ( STR_ID_POC_PROCESSING, "Processing", "PoC Processing Message");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_NULL_STR_ERR, "Invalid input", "PoC Invalid input.");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_AUTO_ANS, "Auto", "PoC auto answer");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_MANUAL_ANS, "Manual", "PoC manual answer");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_INVITING_SUCCESS, "Inviting Success", "Inviting Success");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_INVITING_FAIL, "Inviting Failed", "Inviting Failed");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_STATUS_MODE_MODIFIED, "Status Mode Modified", "Status Mode Modified");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_STATUS_MODE_NOT_MODIFIED, "Status Mode Not Modified", "Status Mode Not Modified");	

	ADD_APPLICATION_STRING2 ( STR_ID_POC_ALERT, "Alert", "Alert");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ALERT_FROM, "Alert from ", "Alert from ");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_REGISTERING, "Registering", "PoC Registering");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_DEREGISTERING, "Deregistering", "PoC Deregistering");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_REGISTERED, "Registered", "Registered");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_DEREGISTERED, "Deregistered", "Deregistered");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CM_INVITING, "Inviting ", "PoC Inviting");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CM_MO_RINGING, "Ringing ", "PoC MO Ringing");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CM_MT_RINGING, "Accept ", "PoC MT Accept");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CM_CONNECTED_IDLE, "Connected ", "PoC Connected");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CM_TALKING, "Talking to ", "PoC Talking to");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CM_LISTENING, "Listening from ", "PoC ");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_CM_ANONYMOUS, "Anonymous", "Anonymous");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_NOT_REGISTERED, "Not Registered", "PoC Not Registered");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_INVALID_SETTING, "Invalid Setting", "PoC Invalid Setting");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_INVALID_URI, "Invalid URI", "PoC Invalid URI");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_NOT_FOUND, "User Not Found", "PoC User Not Found");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_BUSY, "User Busy", "PoC User Busy");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_DEREGISTER_FIRST, "Turn Off PoC", "Turn Off PoC");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_TERMINATE_CALL_FIRST, "Hang Up First", "Hang Up First");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_FLOOR_LOST, "Floor Lost", "Floor Lost");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_XDM_ERROR, "XDM error", "XDM error");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_REG_PARTIAL_SUCCESS, "Partial Success", "Partial Success");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_MAXIMUM_REACHED, "Maximum Reached", "Maximum Reached");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_AUTH_FAIL, "Proxy Auth. Fail", "Proxy Auth. Fail");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_TURN_OFF_PRIVACY_MODE, "Turn Off Privacy Mode", "Turn Off Privacy Mode");		

	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_FS_ERROR, "File System Error", "File System Error");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_FLOOR_ALREADY_IN_USE, "Floor Already Used", "Floor Already Used");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_SERVER_INT_ERROR, "Server Error", "Server Error");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_ONLY_ONE_USER, "Only One User", "Only One User");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_FLOOR_RETRY_AFTER, "Retry Later", "Retry Later");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_LISTEN_ONLY, "Listen Only", "Listen Only");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_TALK_TOO_LONG, "Talk Too Long", "Talk Too Long");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_NO_FLOOR_PERMISSION, "No Permission", "No Permission");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_FLOOR_PREEMPTED, "Floor Preempted", "Floor Preempted");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_NO_RESOURCE, "No Resource", "No Resource");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_TIMEOUT_ERROR, "Time Out", "Time Out");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_RECV_SIP_BYE, "Peer Hangs Up", "Peer Hangs Up");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_TALK_ABORTED, "Peer Aborts", "Peer Aborts");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_TURN_ON_XDM, "Turn On XDM", "Turn On XDM");
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_AUTH_REQ, "Authentication Required", "Authentication Required");	
	ADD_APPLICATION_STRING2 ( STR_ID_POC_ERR_FORBIDDEN, "Forbidden", "Forbidden");		


 
	//Menus
	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_MAIN, MAIN_MENU_SERVICES_MENUID,
							3,
							MENU_ID_POC_STATUS,
							MENU_ID_POC_CALL_HISTORY,
							MENU_ID_POC_SETTINGS,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_MAIN, IMG_ID_POC_ICON));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_MAIN_REGOK, MAIN_MENU_SERVICES_MENUID,
							5,
							MENU_ID_POC_STATUS,
							MENU_ID_POC_CONTACT,
							MENU_ID_POC_TALK_GROUPS,
							MENU_ID_POC_CALL_HISTORY,
							MENU_ID_POC_SETTINGS,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_MAIN, IMG_ID_POC_ICON));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_STATUS, MENU_ID_POC_MAIN,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_STATUS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT, MENU_ID_POC_MAIN,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_CONTACTS, 0));


	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT, MENU_ID_POC_CONTACT,
							4,
							MENU_ID_POC_CONTACT_OPT_SETTINGS,
							MENU_ID_POC_CONTACT_OPT_SEND_ALERT,
							MENU_ID_POC_CONTACT_OPT_ADHOC_TALK,
							MENU_ID_POC_CONTACT_OPT_REFRESH_STATUS,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_OPTIONS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS, MENU_ID_POC_CONTACT_OPT,
							4,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_MODIFY,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ADD,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_DELETE,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_INFO,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_SETTINGS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_MODIFY, MENU_ID_POC_CONTACT_OPT_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_MODIFY, 0));


	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ADD, MENU_ID_POC_CONTACT_OPT_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_ADD, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_DELETE, MENU_ID_POC_CONTACT_OPT_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_DELETE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_INFO, MENU_ID_POC_CONTACT_OPT_SETTINGS,
							2,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_INFO_ACTIVITY,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_INFO_MOOD,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_PRES_INFO, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_INFO_ACTIVITY, MENU_ID_POC_CONTACT_OPT_SETTINGS_INFO,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ACTIVITY, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_INFO_MOOD, MENU_ID_POC_CONTACT_OPT_SETTINGS_INFO,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_MOOD, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES, 0,
							4,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_INVITE,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_SUBSCRIBE,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_PROVIDE_PRES,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_SUBSCRIBE_PRES,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ATTRIBUTES, NULL));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_INVITE, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES,
							3,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_INVITE_ACCEPT,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_INVITE_AUTO,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_INVITE_REJECT,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ALLOW_INVITE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_INVITE_ACCEPT, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_INVITE,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_MANUAL_ANS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_INVITE_AUTO, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_INVITE,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_AUTO_ACCEPT, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_INVITE_REJECT, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_INVITE,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_REJECT, 0));


	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_SUBSCRIBE, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES,
							3,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_SUBSCRIBE_ALLOW,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_SUBSCRIBE_BLOCK,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_SUBSCRIBE_POLITE_BLOCK,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ALLOW_SUBSCRIBE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_SUBSCRIBE_ALLOW, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_SUBSCRIBE,
							0,
 							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ACCEPT, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_SUBSCRIBE_BLOCK, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_SUBSCRIBE,
							0,
 							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_REJECT, 0));


	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_SUBSCRIBE_POLITE_BLOCK, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_ALLOW_SUBSCRIBE,
							0,
 							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_POLITE_BLOCK, 0));


	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_PROVIDE_PRES, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES,
							3,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_PROVIDE_PRES_ACTIVITY,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_PROVIDE_PRES_MOOD,
							MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_PROVIDE_PRES_ALL,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_PROVIDE_PRES, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_SUBSCRIBE_PRES, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_SUBSCRIBE_PRES, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_PROVIDE_PRES_ACTIVITY, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_PROVIDE_PRES,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ACTIVITY, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_PROVIDE_PRES_MOOD, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_PROVIDE_PRES,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_MOOD, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_PROVIDE_PRES_ALL, MENU_ID_POC_CONTACT_OPT_SETTINGS_ATTRIBUTES_PROVIDE_PRES,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ALL, 0));


	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_SEND_ALERT, MENU_ID_POC_CONTACT_OPT,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_SEND_ALERT, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_ADHOC_TALK, MENU_ID_POC_CONTACT_OPT,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ADHOC_TALK, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CONTACT_OPT_REFRESH_STATUS, MENU_ID_POC_CONTACT_OPT,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_REFRESH_STATUS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS, MENU_ID_POC_CONTACT,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_TALK_GROUPS, 0));


	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT, 0,
							5,
							MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS,
							MENU_ID_POC_TALK_GROUPS_OPT_ADD_GROUP,
							MENU_ID_POC_TALK_GROUPS_OPT_DELETE_GROUP,
							MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO,
							MENU_ID_POC_TALK_GROUPS_OPT_CALL_OTHERS_GROUP,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_OPTIONS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_EMPTY, 0,
							2,
							MENU_ID_POC_TALK_GROUPS_OPT_ADD_GROUP,
							MENU_ID_POC_TALK_GROUPS_OPT_CALL_OTHERS_GROUP,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_OPTIONS, 0));


	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS, MENU_ID_POC_TALK_GROUPS_OPT,
							4,
							MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ADD,
							MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ADD_FROM_CONTACT,
							MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_DELETE,
							MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_INFO,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ENTRY_SETTINGS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_NO_ENTRY, MENU_ID_POC_TALK_GROUPS_OPT,
							2,
							MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ADD,
							MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ADD_FROM_CONTACT,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ENTRY_SETTINGS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ADD, MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_ADD, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ADD_FROM_CONTACT, MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ADD_FROM_CONTACTS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_DELETE, MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_DELETE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_INFO, MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ENTRY_INFO, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES, 0,
							5,
							MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES_CONF_STATE,
							MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES_INVITE_USER_DYNA,
							MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES_JOIN_HANDLING,
							MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES_INIT_CONF,
							MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES_ANONYMITY,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ATTRIBUTES, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES_CONF_STATE, MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_CONF_STATE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES_INVITE_USER_DYNA, MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_INVITE_USER_DYNA, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES_JOIN_HANDLING, MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_JOIN_HANDLING, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES_INIT_CONF, MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_INIT_CONFERENCE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES_ANONYMITY, MENU_ID_POC_TALK_GROUPS_OPT_ENTRY_SETTINGS_ENTRY_ATTRIBUTES,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ANONYMITY, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_ADD_GROUP, MENU_ID_POC_TALK_GROUPS_OPT,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ADD_GROUP, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_DELETE_GROUP, MENU_ID_POC_TALK_GROUPS_OPT,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_DELETE_GROUP, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO, MENU_ID_POC_TALK_GROUPS_OPT,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_GROUP_INFO, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_CALL_OTHERS_GROUP, MENU_ID_POC_TALK_GROUPS_OPT,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_CALL_OTHERS_GROUP, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR, 0,
							5,
							MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR_CONF_STATE,
							MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR_INVITE_USER_DYNA,
							MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR_JOIN_HANDLING,
							MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR_INIT_CONF,
							MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR_ANONYMITY,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ATTRIBUTES, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR_CONF_STATE, MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_CONF_STATE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR_INVITE_USER_DYNA, MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_INVITE_USER_DYNA, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR_JOIN_HANDLING, MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_JOIN_HANDLING, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR_INIT_CONF, MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_INIT_CONFERENCE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR_ANONYMITY, MENU_ID_POC_TALK_GROUPS_OPT_GROUP_INFO_ATTR,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ANONYMITY, 0));



	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CALL_HISTORY, MENU_ID_POC_MAIN,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_CALL_HISTORY, 0));


#ifdef __MMI_POC_ETS_TESTCODE__
	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CALL_HISTORY_INFO_OPTION, 0,
							4,
							MENU_ID_POC_CALL_HISTORY_INFO_VIEW,
							MENU_ID_POC_CALL_HISTORY_INFO_OPTION_DELETE,
							MENU_ID_POC_CALL_HISTORY_INFO_OPTION_DELETE_ALL,
							MENU_ID_POC_CALL_HISTORY_INFO_OPTION_SEND_FAKE_SESSION,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_OPTIONS, 0));
#else
	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CALL_HISTORY_INFO_OPTION, 0,
							3,
							MENU_ID_POC_CALL_HISTORY_INFO_VIEW,
							MENU_ID_POC_CALL_HISTORY_INFO_OPTION_DELETE,
							MENU_ID_POC_CALL_HISTORY_INFO_OPTION_DELETE_ALL,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_OPTIONS, 0));
#endif
	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CALL_HISTORY_INFO_VIEW, MENU_ID_POC_CALL_HISTORY_INFO_OPTION,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_VIEW, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CALL_HISTORY_INFO_OPTION_DELETE, MENU_ID_POC_CALL_HISTORY_INFO_OPTION,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_DELETE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CALL_HISTORY_INFO_OPTION_DELETE_ALL, MENU_ID_POC_CALL_HISTORY_INFO_OPTION,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_DELETE_ALL, 0));

#ifdef __MMI_POC_ETS_TESTCODE__
	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CALL_HISTORY_INFO_OPTION_SEND_FAKE_SESSION, MENU_ID_POC_CALL_HISTORY_INFO_OPTION,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_SEND_FAKE, 0));
#endif

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS, MENU_ID_POC_MAIN,
							8,
							MENU_ID_POC_SETTINGS_MY_STATUS,
							MENU_ID_POC_SETTINGS_ANS_MODE,
							MENU_ID_POC_SETTINGS_CALL_BARRING,
							MENU_ID_POC_SETTINGS_ALERT_BARRING,
							MENU_ID_POC_SETTINGS_MAO,
							MENU_ID_POC_SETTINGS_PRIVACY,
							MENU_ID_POC_SETTINGS_START_AT_BOOTUP,
							MENU_ID_POC_SETTINGS_PROFILES,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_POC_SETTINGS, 0));

#ifdef __MMI_POC_ADHOC_STR_INPUT__
	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_NOREG, MENU_ID_POC_MAIN,
							5,
							MENU_ID_POC_SETTINGS_START_AT_BOOTUP,
							MENU_ID_POC_SETTINGS_USE_XDM,
							MENU_ID_POC_SETTINGS_USE_PRES,
							MENU_ID_POC_SETTINGS_ADHOC_STR,
							MENU_ID_POC_SETTINGS_PROFILES,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_POC_SETTINGS, 0));
#else
	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_NOREG, MENU_ID_POC_MAIN,
							4,
							MENU_ID_POC_SETTINGS_START_AT_BOOTUP,
							MENU_ID_POC_SETTINGS_USE_XDM,
							MENU_ID_POC_SETTINGS_USE_PRES,
							MENU_ID_POC_SETTINGS_PROFILES,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_POC_SETTINGS, 0));
#endif


	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_MY_STATUS, MENU_ID_POC_SETTINGS,
							2,
							MENU_ID_POC_SETTINGS_MY_STATUS_ACTIVITY,
							MENU_ID_POC_SETTINGS_MY_STATUS_MOOD,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_MY_STATUS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_MY_STATUS_ACTIVITY, MENU_ID_POC_SETTINGS_MY_STATUS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ACTIVITY, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_MY_STATUS_MOOD, MENU_ID_POC_SETTINGS_MY_STATUS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_MOOD, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_ANS_MODE, MENU_ID_POC_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ANSWER_MODE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_CALL_BARRING, MENU_ID_POC_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_CALL_BARRING, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_ALERT_BARRING, MENU_ID_POC_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ALERT_BARRING, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_MAO, MENU_ID_POC_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_MAO, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_PRIVACY, MENU_ID_POC_SETTINGS,
							2,
							MENU_ID_POC_SETTINGS_PRIVACY_DISABLE,
							MENU_ID_POC_SETTINGS_PRIVACY_ENABLE,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_PRIVACY, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_PRIVACY_DISABLE, MENU_ID_POC_SETTINGS_PRIVACY,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_DISABLE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_PRIVACY_ENABLE, MENU_ID_POC_SETTINGS_PRIVACY,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ENABLE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_START_AT_BOOTUP, MENU_ID_POC_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_START_AT_BOOTUP, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_USE_XDM, MENU_ID_POC_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_USE_XDM, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_USE_PRES, MENU_ID_POC_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_USE_PRES, 0));

#ifdef __MMI_POC_ADHOC_STR_INPUT__
	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_ADHOC_STR, MENU_ID_POC_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_ADHOC_STR, 0));
#endif

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_PROFILES, MENU_ID_POC_SETTINGS,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_PROFILES, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_PROFILES_OPTION, 0,
							2,
							MENU_ID_POC_SETTINGS_PROFILES_OPTION_ACTIVATE,
							MENU_ID_POC_SETTINGS_PROFILES_OPTION_EDIT,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_OPTIONS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_PROFILES_OPTION_ACTIVATE, MENU_ID_POC_SETTINGS_PROFILES_OPTION,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_ACTIVATE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_PROFILES_OPTION_EDIT, MENU_ID_POC_SETTINGS_PROFILES_OPTION,
							2,
							MENU_ID_POC_SETTINGS_PROFILES_OPTION_EDIT_POC,
							MENU_ID_POC_SETTINGS_PROFILES_OPTION_EDIT_CONN,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_GLOBAL_EDIT, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_PROFILES_OPTION_EDIT_POC, MENU_ID_POC_SETTINGS_PROFILES_OPTION_EDIT,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_POC_SETTINGS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_SETTINGS_PROFILES_OPTION_EDIT_CONN, MENU_ID_POC_SETTINGS_PROFILES_OPTION_EDIT,
							0,
							SHOW, NONMOVEABLE, DISP_LIST,
							STR_ID_POC_CONNECTION_SETTINGS, 0));


	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CM_OPTION_PRES_NOT_READY, 0,
								1,
								MENU_ID_POC_CM_ADD_USER,
//								MENU_ID_POC_CM_TALK_GROUP,
								SHOW, NONMOVEABLE, DISP_LIST,
								STR_GLOBAL_OPTIONS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CM_OPTION_PRES_SUBSCRIBE, 0,
								2,
								MENU_ID_POC_CM_ADD_USER,
								MENU_ID_POC_CM_SUBSCRIBE,
//								MENU_ID_POC_CM_TALK_GROUP,
								SHOW, NONMOVEABLE, DISP_LIST,
								STR_GLOBAL_OPTIONS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CM_OPTION_PRES_UNSUBSCRIBE, 0,
								2,
								MENU_ID_POC_CM_ADD_USER,
								MENU_ID_POC_CM_UNSUBSCRIBE,
//								MENU_ID_POC_CM_TALK_GROUP,
								SHOW, NONMOVEABLE, DISP_LIST,
								STR_GLOBAL_OPTIONS, 0));


	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CM_ADD_USER, MENU_ID_POC_CM_OPTION_PRES_NOT_READY,
								0,
								SHOW, NONMOVEABLE, DISP_LIST,
								STR_ID_POC_ADD_FROM_CONTACTS, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CM_SUBSCRIBE, MENU_ID_POC_CM_OPTION_PRES_SUBSCRIBE,
								0,
								SHOW, NONMOVEABLE, DISP_LIST,
								STR_ID_POC_SUBSCRIBE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CM_UNSUBSCRIBE, MENU_ID_POC_CM_OPTION_PRES_UNSUBSCRIBE,
								0,
								SHOW, NONMOVEABLE, DISP_LIST,
								STR_ID_POC_UNSUBSCRIBE, 0));

	ADD_APPLICATION_MENUITEM ((MENU_ID_POC_CM_TALK_GROUP, MENU_ID_POC_CM_OPTION_PRES_NOT_READY,
								0,
								SHOW, NONMOVEABLE, DISP_LIST,
								STR_ID_POC_TALK_GROUPS, 0));

}
#endif	//#ifdef DEVELOPER_BUILD_FIRST_PASS
#endif	//#ifdef __MMI_POC
#endif	//#ifndef __MMI_RES_POC_C
