/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/**
 *	Copyright Notice
 *	?2002 - 2003, Pixtel Communications, Inc., 1489 43rd Ave. W.,
 *	Vancouver, B.C. V6M 4K8 Canada. All Rights Reserved.
 *  (It is illegal to remove this copyright notice from this software or any
 *  portion of it)
 */

/**************************************************************

	FILENAME	: Res_.c

  	PURPOSE		: Populate Resource for 

	REMARKS		: nil

	AUTHOR		: Yogesh

	DATE		: August-11-2003

**************************************************************/
#include "MMI_features.h"

#include "MMIDataType.h"
#include "CustomCfg.h"
#include "CustResDef.h"
#include "GlobalMenuItems.h"
#include "CustDataRes.h"


#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif

#include "MMI_features.h"
#include "CalendarResDef.h"

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"
#include "ToDoListResDef.h"

void PopulateResourcesCal(void)
{
	ADD_APPLICATION_STRING2(CAL_STRING_LUNAR,"Lunar Calendar","Menu Item.");

	ADD_APPLICATION_STRING2(STR_CAL_CHINESE_NO1,"1","Chinese 1");	
	ADD_APPLICATION_STRING2(STR_CAL_CHINESE_NO2,"2","Chinese 2");	
	ADD_APPLICATION_STRING2(STR_CAL_CHINESE_NO3,"3","Chinese 3");		
	ADD_APPLICATION_STRING2(STR_CAL_CHINESE_NO4,"4","Chinese 4");	
	ADD_APPLICATION_STRING2(STR_CAL_CHINESE_NO5,"5","Chinese 5");		
	ADD_APPLICATION_STRING2(STR_CAL_CHINESE_NO6,"6","Chinese 6");	
	ADD_APPLICATION_STRING2(STR_CAL_CHINESE_NO7,"7","Chinese 7");	
	ADD_APPLICATION_STRING2(STR_CAL_CHINESE_NO8,"8","Chinese 8");		
	ADD_APPLICATION_STRING2(STR_CAL_CHINESE_NO9,"9","Chinese 9");	
	ADD_APPLICATION_STRING2(STR_CAL_CHINESE_NO10,"10","Chinese 10");		
	ADD_APPLICATION_STRING2(STR_CAL_CHINESE_NO20,"20","Chinese 20");
	ADD_APPLICATION_STRING2(STR_CAL_CHINESE_NO30,"30","Chinese 30");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM1,"SC","Slight Cold");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM2,"GC","Great Cold");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM3,"BS","Beginning Spring");		
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM4,"R","Raining");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM5,"WI","Waking of Insects");		
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM6,"SE","Spring Equinox");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM7,"PB","Pure Brightness");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM8,"GR","Grain Rain");		
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM9,"BS","Beginning Summer");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM10,"GF","Grain Full");		
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM11,"GE","Grain in Ear");
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM12,"SS","Summer Solstice");
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM13,"SH","Slight Heat");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM14,"GH","Great Heat");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM15,"BA","Begsinning Autumn");		
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM16,"LH","Limit of Heat");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM17,"WD","White Dew");		
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM18,"AE","Autumnal Equinox");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM19,"CD","Cold Dew");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM20,"FD","Frost's Descent");		
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM21,"BW","Beginning Winter");	
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM22,"SS","Slight Snow");		
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM23,"GS","Great Snow");
	ADD_APPLICATION_STRING2(STR_CAL_SOLARTERM24,"WS","Winter Solstice");
	ADD_APPLICATION_STRING2(STR_CAL_ANIMAL1,"M","Mouse");	
	ADD_APPLICATION_STRING2(STR_CAL_ANIMAL2,"C","Cattle");	
	ADD_APPLICATION_STRING2(STR_CAL_ANIMAL3,"T","Tiger");		
	ADD_APPLICATION_STRING2(STR_CAL_ANIMAL4,"R","Rabbit");	
	ADD_APPLICATION_STRING2(STR_CAL_ANIMAL5,"D","Dragon");		
	ADD_APPLICATION_STRING2(STR_CAL_ANIMAL6,"S","Snake");	
	ADD_APPLICATION_STRING2(STR_CAL_ANIMAL7,"H","Horse");	
	ADD_APPLICATION_STRING2(STR_CAL_ANIMAL8,"E","Sheep");		
	ADD_APPLICATION_STRING2(STR_CAL_ANIMAL9,"O","Monkey");	
	ADD_APPLICATION_STRING2(STR_CAL_ANIMAL10,"I","Chicken");		
	ADD_APPLICATION_STRING2(STR_CAL_ANIMAL11,"G","Dog");
	ADD_APPLICATION_STRING2(STR_CAL_ANIMAL12,"P","Pig");
	ADD_APPLICATION_STRING2(STR_CAL_KAN1,"J","Jia");	
	ADD_APPLICATION_STRING2(STR_CAL_KAN2,"Y","Yi");	
	ADD_APPLICATION_STRING2(STR_CAL_KAN3,"B","Bing");		
	ADD_APPLICATION_STRING2(STR_CAL_KAN4,"D","Ding");	
	ADD_APPLICATION_STRING2(STR_CAL_KAN5,"W","Wu");		
	ADD_APPLICATION_STRING2(STR_CAL_KAN6,"I","Ji");	
	ADD_APPLICATION_STRING2(STR_CAL_KAN7,"G","Geng");	
	ADD_APPLICATION_STRING2(STR_CAL_KAN8,"X","Xin");		
	ADD_APPLICATION_STRING2(STR_CAL_KAN9,"R","Ren");	
	ADD_APPLICATION_STRING2(STR_CAL_KAN10,"G","Gui");	
	ADD_APPLICATION_STRING2(STR_CAL_CHI1,"Z","Zi");	
	ADD_APPLICATION_STRING2(STR_CAL_CHI2,"C","Chou");	
	ADD_APPLICATION_STRING2(STR_CAL_CHI3,"Y","Yin");		
	ADD_APPLICATION_STRING2(STR_CAL_CHI4,"M","Mao");		
	ADD_APPLICATION_STRING2(STR_CAL_CHI5,"E","Chen");	
	ADD_APPLICATION_STRING2(STR_CAL_CHI6,"S","Si");	
	ADD_APPLICATION_STRING2(STR_CAL_CHI7,"W","Wu");		
	ADD_APPLICATION_STRING2(STR_CAL_CHI8,"I","Wei");	
	ADD_APPLICATION_STRING2(STR_CAL_CHI9,"N","Shen");	
	ADD_APPLICATION_STRING2(STR_CAL_CHI10,"O","You");	
	ADD_APPLICATION_STRING2(STR_CAL_CHI11,"X","Xu");	
	ADD_APPLICATION_STRING2(STR_CAL_CHI12,"H","Hai");	
	ADD_APPLICATION_STRING2(STR_CAL_DIRECTION1,"S","South");	
	ADD_APPLICATION_STRING2(STR_CAL_DIRECTION2,"E","East");	
	ADD_APPLICATION_STRING2(STR_CAL_DIRECTION3,"N","North");	
	ADD_APPLICATION_STRING2(STR_CAL_DIRECTION4,"W","West");	
	ADD_APPLICATION_STRING2(STR_CAL_UNFORTUNATE,"F","UNFORTUNATE");	
	ADD_APPLICATION_STRING2(STR_CAL_UNLUCKY,"L","UNLUCKY");	
	ADD_APPLICATION_STRING2(STR_CAL_YEAR,"Y","Chinese year");	
	ADD_APPLICATION_STRING2(STR_CAL_MONTH,"M","Chinese month");	
	ADD_APPLICATION_STRING2(STR_CAL_DAY,"D","Chinese day");		
	ADD_APPLICATION_STRING2(STR_CLNDR_JUMP_TO,"Jump To Date","Jump to menu item");	
	ADD_APPLICATION_STRING2(STR_CLNDR_DATE,"Date","Date caption");		
	ADD_APPLICATION_STRING2(STR_CLNDR_WRONG_DATE,"Date Error!","Date error message");			
#ifdef __MMI_CALENDAR_V2__
        ADD_APPLICATION_STRING2(STR_CLNDR_WEEK_SYMBOL,"W","Week Symbol");		

        ADD_APPLICATION_STRING2(STR_CLNDR_WEEK_SUNDAY,"S","Week Symbol");			
        ADD_APPLICATION_STRING2(STR_CLNDR_WEEK_MONDAY,"M","Week Symbol");
        ADD_APPLICATION_STRING2(STR_CLNDR_WEEK_TUESDAY,"T","Week Symbol");
        ADD_APPLICATION_STRING2(STR_CLNDR_WEEK_WEDNESDAY,"W","Week Symbol");
        ADD_APPLICATION_STRING2(STR_CLNDR_WEEK_THURSDAY,"T","Week Symbol");
        ADD_APPLICATION_STRING2(STR_CLNDR_WEEK_FRIDAY,"F","Week Symbol");
        ADD_APPLICATION_STRING2(STR_CLNDR_WEEK_SATURDAY,"S","Week Symbol");
        ADD_APPLICATION_STRING2(STR_CLNDR_OUT_OF_CALENDAR,"Valid date is 1970~2030","Out of Date");
        ADD_APPLICATION_STRING2(STR_CLNDR_WEEK_STRING,"Week","Week String");
      
#endif    
	
	ADD_APPLICATION_IMAGE2(IMG_CAL_ON,CUST_IMG_BASE_PATH"\\\\EmptyImage.bmp","Icon for On Button.");
	ADD_APPLICATION_IMAGE2(IMG_CAL_OFF,CUST_IMG_BASE_PATH"\\\\EmptyImage.bmp","Icon for Off Button.");

#ifdef __MMI_CALENDAR__
#ifdef __MMI_TODOLIST__
	ADD_APPLICATION_MENUITEM((MENU_GOTO_TASK_CAL,ORGANIZER_CALENDER_MENU,0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,
	CAL_STRING_VIEW,0));
#endif
#ifdef __MMI_CALENDAR_V2__
    
#ifdef __MMI_CLNDR_WEEKLY_VIEW_SUPPORT__
        ADD_APPLICATION_MENUITEM((MENU_ID_CLNDR_WEEKLY_VIEW,ORGANIZER_CALENDER_MONTHLY_OPTIONS_MENU,0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,
        STR_CLNDR_WEEKLY_VIEW,0));
        ADD_APPLICATION_MENUITEM((MENU_ID_CLNDR_MONTHLY_VIEW,ORGANIZER_CALENDER_WEEKLY_OPTIONS_MENU,0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,
        STR_CLNDR_MONTHLY_VIEW,0));
    
        ADD_APPLICATION_STRING2(STR_CLNDR_WEEKLY_VIEW,"Go To Weekly View","Go To Weekly View");     
        ADD_APPLICATION_STRING2(STR_CLNDR_MONTHLY_VIEW,"Go To Monthly View","Go To Monthly View");     
#endif
#ifdef __MMI_TODOLIST__    
        ADD_APPLICATION_MENUITEM((MENU_ID_CLNDR_ADD_TASK,ORGANIZER_CALENDER_MENU,0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,
            STR_CLNDR_ADD_TASK,0));
    
        ADD_APPLICATION_STRING2(STR_CLNDR_ADD_TASK,"Add Task","Jump to menu item"); 
#endif
        ADD_APPLICATION_IMAGE2 (IMG_CLNDR_TASK_CLOCK, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\icon\\\\time.pbm","calendar title left arrow");
#ifdef __MMI_TOUCH_SCREEN__
	ADD_APPLICATION_IMAGE2 (IMG_TOP_UP, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\Touch\\\\Th_top_up.bmp","calendar title left arrow");
	ADD_APPLICATION_IMAGE2 (IMG_TOP_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\Touch\\\\Th_top_down.bmp","calendar title left arrow down");
	ADD_APPLICATION_IMAGE2 (IMG_BOTTOM_UP, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\Touch\\\\Th_bottom_up.bmp","calendar title right arrow");
	ADD_APPLICATION_IMAGE2 (IMG_BOTTOM_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\Touch\\\\Th_bottom_down.bmp","calendar title right arrow down");
    
       ADD_APPLICATION_IMAGE2 (IMG_HOUR_PLUS_UP, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\Touch\\\\Th_Plus.bmp","calendar title left arrow");
	ADD_APPLICATION_IMAGE2 (IMG_HOUR_PLUS_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\Touch\\\\Th_Plus_down.bmp","calendar title left arrow down");
	ADD_APPLICATION_IMAGE2 (IMG_HOUR_SUBTRACT_UP, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\Touch\\\\Th_Subtract.bmp","calendar title right arrow");
	ADD_APPLICATION_IMAGE2 (IMG_HOUR_SUBTRACT_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\Touch\\\\Th_Subtract_down.bmp","calendar title right arrow down");
#endif /* __MMI_TOUCH_SCREEN__ */
#ifdef __MMI_CLNDR_ICON_SUPPORT__
	ADD_APPLICATION_IMAGE2 (IMG_CLNDR_ICON_CALL, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\icon\\\\call.pbm","calendar title left arrow");
	ADD_APPLICATION_IMAGE2 (IMG_CLNDR_ICON_ANNIVERSIRY, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\icon\\\\celebrate.pbm","calendar title left arrow");
	ADD_APPLICATION_IMAGE2 (IMG_CLNDR_ICON_COURSE, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\icon\\\\course.pbm","calendar title left arrow");
	ADD_APPLICATION_IMAGE2 (IMG_CLNDR_ICON_DATE, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\icon\\\\date.pbm","calendar title left arrow");
	ADD_APPLICATION_IMAGE2 (IMG_CLNDR_ICON_MEETING, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\icon\\\\meeting.pbm","calendar title left arrow");
	ADD_APPLICATION_IMAGE2 (IMG_CLNDR_ICON_REMINDER, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\icon\\\\reminder.pbm","calendar title left arrow");
    #endif
#ifdef __MMI_BIRTHDAY_REMINDER__
    ADD_APPLICATION_IMAGE2 (IMG_CLNDR_BIRTHDAY_REMINDER, CUST_IMG_PATH"\\\\MainLCD\\\\Calendar\\\\icon\\\\birthday.pbm","calendar title left arrow");
#endif   
#endif

	ADD_APPLICATION_MENUITEM((MENU_ID_CLNDR_JUMP_TO_DATE,ORGANIZER_CALENDER_MENU,0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,
	STR_CLNDR_JUMP_TO,0));

	ADD_APPLICATION_MENUITEM((MENU_CAL_TYPE,ORGANIZER_CALENDER_MENU,0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,
	CAL_STRING_LUNAR,0));
#endif

#ifdef __MMI_BPP_SUPPORT__
        ADD_APPLICATION_MENUITEM((MENU_ID_CLNDR_BPP_PRINT,ORGANIZER_CALENDER_MENU,0,SHOW,MOVEABLEWITHINPARENT,DISP_LIST,
	        STR_CLNDR_BPP_PRINT,0));
        ADD_APPLICATION_STRING2(STR_CLNDR_BPP_PRINT,"Print","BPP Print");     
        ADD_APPLICATION_STRING2(STR_CLNDR_BPP_PREVIEW,"Preview","BPP Preview");     
        
#endif /*__MMI_BPP_SUPPORT__*/

}

#endif


