/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

#include "MMI_features.h"   /* add if you use any compile options defined in MMI_features.h */

#if defined (__MMI_DOWNLOAD_AGENT__)
#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "CustDataProts.h"      /* for resource generator API */
#include "GlobalMenuItems.h"    /* for menu resource */


#include "DLAgentResDef.h"

//#include "ImageViewerResDefs.h"
//#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"

void PopulateDownloadAgentImgRes(void)
{
	ADD_APPLICATION_IMAGE2(IMG_ID_DA_DOWNLOAD_ICON,
		CUST_IMG_PATH"\\\\MainLCD\\\\DLAgent\\\\DL_AP.pbm", "download icon" );

	ADD_APPLICATION_IMAGE2(IMG_ID_DA_DOWNLOAD_PROGRESS_BANNER,
		CUST_IMG_PATH"\\\\MainLCD\\\\DLAgent\\\\DLT_loading", "download progress banner" );

	ADD_APPLICATION_IMAGE2(IMG_ID_DA_DOWNLOAD_STATE_COMPLETE,
		CUST_IMG_PATH"\\\\MainLCD\\\\DLAgent\\\\DL_Complete.pbm", "state icon complete" );
	ADD_APPLICATION_IMAGE2(IMG_ID_DA_DOWNLOAD_STATE_LOADING,
		CUST_IMG_PATH"\\\\MainLCD\\\\DLAgent\\\\DL_Loading.pbm", "state icon loading" );
	ADD_APPLICATION_IMAGE2(IMG_ID_DA_DOWNLOAD_STATE_PAUSE,
		CUST_IMG_PATH"\\\\MainLCD\\\\DLAgent\\\\DL_Pause.pbm", "state icon pause" );
}


void PopulateDownloadAgentStrRes(void)
{
    /* File Type */
	ADD_APPLICATION_STRING2(STR_DA_TEXT_FILE,           "Text file!",       "STR_DA_TEXT_FILE");
	ADD_APPLICATION_STRING2(STR_DA_IMAGE_FILE,          "Image file!",      "STR_DA_IMAGE_FILE");
	ADD_APPLICATION_STRING2(STR_DA_AUDIO_FILE,          "Audio file!",      "STR_DA_AUDIO_FILE");
	ADD_APPLICATION_STRING2(STR_DA_VIDEO_FILE,          "Video file!",      "STR_DA_VIDEO_FILE");
	ADD_APPLICATION_STRING2(STR_DA_APP_FILE,            "APP file!",        "STR_DA_APP_FILE");
	ADD_APPLICATION_STRING2(STR_DA_MSG_FILE,            "MSG file!",        "STR_DA_MSG_FILE");
	ADD_APPLICATION_STRING2(STR_DA_MULTI_FILE,          "MUITI file!",      "STR_DA_MULTI_FILE");
	ADD_APPLICATION_STRING2(STR_DA_UNKNOWN_FILE,        "Unknown file!",    "STR_DA_UNKNOWN_FILE");
	ADD_APPLICATION_STRING2(STR_DA_VCARD_FILE,          "Vcard file",       "STR_DA_VCARD_FILE");
	ADD_APPLICATION_STRING2(STR_DA_VCALENDAR_FILE,      "Vcalendar file",   "STR_DA_VCALENDAR_FILE");
	ADD_APPLICATION_STRING2(STR_DA_EBOOK_FILE,          "EBook file",       "STR_DA_EBook_FILE");

    /* General */
    ADD_APPLICATION_STRING2(STR_DA_EMPTY_USERNAME,      "Empty Username",   "STR_DA_EMPTY_USERNAME");
    
    ADD_APPLICATION_STRING2(STR_ID_DA_NEW_PUSH,         "File received", "STR_DA_NEW_PUSH");
    ADD_APPLICATION_STRING2(STR_ID_DA_REPLACE_FILE,     "File exists. Replace it?",     "STR_DA_REPLACE_FILE");
    ADD_APPLICATION_STRING2(STR_ID_DA_FILENAME_EDITOR,  "Edit Filename",                "STR_DA_FILENAME_EDITOR");
    ADD_APPLICATION_STRING2(STR_ID_DA_CALLBACK_NOW,     " saved. Use Now?",         "STR_DA_CALLBACK_NOW");

    /* Prompt */
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_SIZE,      "Size",             "size");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_TYPE,      "Type",             "type");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_NAME,      "Name",             "name");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_VENDOR,    "Vendor",           "vendor");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_DESC,      "Description",      "desc");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_INFOURL,   "InfoURL",          "infoURL");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_ESTIMATED, "Estimated Time",   "estimated time");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_UNKNOWN,   "Unknown",          "unknown");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_SEC,       "sec",              "sec");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_MIN,       "min",              "min");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_TIME_REMAIN, "Time remaining", "Time remaining");

    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_NOT_SUPPORT,       "We may not support this file. Still Download?\nThis file would be saved into ", "STR_ID_DA_PROMPT_NOT_SUPPORT");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_DL_COMPLETE,       "Download completed",    "STR_ID_DA_PROMPT_DL_COMPLETE");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_DL_COMPLETE_ASK,   " downloaded. Use now?", "STR_ID_DA_PROMPT_DL_COMPLETE_ASK");
#if 0
/* under construction !*/
#endif

    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_EXCEED_MAX_DL,     "Exceed Max Concurrent Download",  "STR_ID_DA_PROMPT_EXCEED_MAX_DL");
    ADD_APPLICATION_STRING2(STR_ID_DA_PROMPT_EXCEED_MAX_JOB,    "Exceed Max Download Task",  "STR_ID_DA_PROMPT_EXCEED_MAX_JOB");

    /* Error */
    ADD_APPLICATION_STRING2(STR_ID_DA_ERROR_FILE_MISMATCH,      "File is missing or modified. Download removed", "STR_ID_DA_ERROR_FILE_MISMATCH");
    ADD_APPLICATION_STRING2(STR_ID_DA_ERROR_TEMP_UNAVAILABLE,   "File is temporary unavailable", "STR_ID_DA_ERROR_TEMP_UNAVAILABLE");
    ADD_APPLICATION_STRING2(STR_ID_DA_ERROR_RESUME_FAIL,        "Fail to resume",              "STR_ID_DA_ERROR_RESUME_FAIL");
    ADD_APPLICATION_STRING2(STR_ID_DA_ERROR_CONNECT_CLOSED,     "Connection is closed",        "STR_ID_DA_ERROR_CONNECT_CLOSED");
    ADD_APPLICATION_STRING2(STR_ID_DA_ERROR_INSUFFICIENT_STORAGE,"Insufficient space",         "STR_ID_DA_ERROR_INSUFFICIENT_STORAGE");

    /* Job */
    ADD_APPLICATION_STRING2(STR_ID_DA_JOB_LIST,         "Download List",    "STR_ID_DA_JOB_LIST");
    ADD_APPLICATION_STRING2(STR_ID_DA_JOB_VIEW_DETAIL,  "View Detail",      "STR_ID_DA_JOB_VIEW_DETAIL");
    ADD_APPLICATION_STRING2(STR_ID_DA_JOB_CANCEL,       "Cancel",           "STR_ID_DA_JOB_CANCEL");
    ADD_APPLICATION_STRING2(STR_ID_DA_JOB_SUSPEND,      "Suspend",          "STR_ID_DA_JOB_SUSPEND");
    ADD_APPLICATION_STRING2(STR_ID_DA_JOB_RESUME,       "Resume",           "STR_ID_DA_JOB_RESUME");
    ADD_APPLICATION_STRING2(STR_ID_DA_JOB_UPDATE,       "Update",           "STR_ID_DA_JOB_UPDATE");
    ADD_APPLICATION_STRING2(STR_ID_DA_JOB_EXIST,        "Another download with same file exist!",
                                                                            "STR_ID_DA_JOB_EXIST");
    ADD_APPLICATION_STRING2(STR_ID_DA_JOB_USE,          "Use Now",          "STR_ID_DA_JOB_USE");
    ADD_APPLICATION_STRING2(STR_ID_DA_JOB_SAVE_AS,      "Move",             "STR_ID_DA_JOB_SAVE_AS");
    ADD_APPLICATION_STRING2(STR_ID_DA_JOB_REMOVE,       "Remove",           "STR_ID_DA_JOB_REMOVE");
    ADD_APPLICATION_STRING2(STR_ID_DA_JOB_REMOVE_ALL,   "Remove All Complete","STR_ID_DA_JOB_REMOVE_ALL");

    /* OMA */
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_USER_CANCELLED_MSG,       "User Cancelled",               "STR_DA_OMA_USER_CANCELLED_MSG");
#if defined (__MMI_OMA_DD_DOWNLOAD__)
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_INSUFFICIENT_MEM_MSG,     "Insufficient Memory",          "STR_DA_OMA_INSUFFICIENT_MEM_MSG");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_LOSS_OF_SERVICE_MSG,      "Download URL or Server Error", "STR_DA_OMA_LOSS_OF_SERVICE_MSG");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_ATTRIBUTE_MISMATCH_MSG,   "Attribute Mismatch",           "STR_DA_OMA_JAR_SIZE_MISMATCH_MSG");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_INVALID_DESCRIPTOR_MSG,   "Invalid descriptor",           "STR_DA_OMA_ATTRIBUTE_MISMATCH_MSG");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_INVALID_DDVSERSION_MSG,   "Invalid DDVersion",            "STR_DA_OMA_INVALID_DDVSERSION_MSG");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_DEVICE_ABORTED_MSG,       "Device Aborted",               "STR_DA_OMA_DEVICE_ABORTED_MSG");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_NON_ACCEPTABLE_CONTENT_MSG,"Non-Acceptable Content",      "STR_DA_OMA_NON_ACCEPTABLE_CONTENT_MSG");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_LOADER_ERROR_MSG,         "Download URL or Server Error", "STR_DA_OMA_LOADER_LOADER_ERROR_MSG");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_INSUFFICIENT_STORAGE_MSG, "More free space is needed for installation","STR_DA_OMA_INSUFFICIENT_STORAGE_MSG");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_AUTHORIZATION_FAILURE_MSG,"Does not have permission it requires","STR_DA_OMA_AUTHORIZATION_FAILURE_MSG");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_SEND_REPORT,              "Send Report",                  "STR_DA_OMA_SEND_REPORT");

    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_ERROR_SEND_REPORT_FAIL,   "Fail to send report",          "STR_ID_DA_OMA_ERROR_SEND_REPORT_FAIL");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_ERROR_SEND_REPORT_FAIL_AUTH,  "Fail to send report - authentication fail", "STR_ID_DA_OMA_ERROR_SEND_REPORT_FAIL_AUTH");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_ERROR_SEND_REPORT_CANCEL, "Sending report is canceled.",  "STR_ID_DA_OMA_ERROR_SEND_REPORT_CANCEL");
    ADD_APPLICATION_STRING2(STR_ID_DA_OMA_VIEW_DD,                  "View Descriptor",              "STR_DA_OMA_VIEW_DD");
#endif

    ADD_APPLICATION_STRING2(STR_ID_DA_LSK_DL,                       "DL",                           "STR_ID_DA_LSK_DL");

    ADD_APPLICATION_STRING2(STR_ID_DA_POPUP_SUSPENDED,              "Suspended",                    "STR_ID_DA_POPUP_SUSPENDED");
    ADD_APPLICATION_STRING2(STR_ID_DA_POPUP_CANCEL_ASK,             "Cancel?",                      "");
    ADD_APPLICATION_STRING2(STR_ID_DA_POPUP_SEND_ASK,               "Send?",                        "");


}


void PopulateDownloadAgentMenuItemRes(void)
{
/* Storage Filename editor option */
    /* level 1 */
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_OPTION,MENU_ID_DA,2,
		MENU_ID_DA_OPTION_SAVE,
		MENU_ID_DA_OPTION_INPUT_METHOD,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS,0));

    /* level 2 */
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_OPTION_SAVE,MENU_ID_DA_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_DONE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_OPTION_INPUT_METHOD,MENU_ID_DA_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_INPUT_METHOD,0));

#if defined (__MMI_OMA_DD_DOWNLOAD__)
    /* level 1 */
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_OMA_DL_OPTION, MENU_ID_DA, 2,
		MENU_ID_DA_OMA_DL_OPTION_DOWNLOAD_NOW,
		MENU_ID_DA_OMA_DL_OPTION_VIEW_DD,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS,0));
    
    /* level 2 */
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_OMA_DL_OPTION_DOWNLOAD_NOW,MENU_ID_DA_OMA_DL_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_DOWNLOAD,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_OMA_DL_OPTION_VIEW_DD,MENU_ID_DA_OMA_DL_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_OMA_VIEW_DD,0));
#endif

/* Job option 1 - for running job */
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION, MENU_ID_DA, 5,
		MENU_ID_DA_JOB_OPTION_VIEW_DETAIL,
		MENU_ID_DA_JOB_OPTION_CANCEL,
		MENU_ID_DA_JOB_OPTION_SUSPEND,
		MENU_ID_DA_JOB_OPTION_RESUME,
		MENU_ID_DA_JOB_OPTION_REMOVE_ALL,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION_VIEW_DETAIL, MENU_ID_DA_JOB_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_JOB_VIEW_DETAIL,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION_CANCEL, MENU_ID_DA_JOB_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_JOB_CANCEL,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION_SUSPEND, MENU_ID_DA_JOB_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_JOB_SUSPEND,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION_RESUME, MENU_ID_DA_JOB_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_JOB_RESUME,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION_REMOVE_ALL, MENU_ID_DA_JOB_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_JOB_REMOVE_ALL,0));
//#if defined (__MMI_OMA_DD_DOWNLOAD__)
//	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION_OMA_UPDATE, MENU_ID_DA_JOB_OPTION,0,
//		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_JOB_UPDATE,0));
//#endif

/* Job option 2 - for complete job */
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION2, MENU_ID_DA, 5,
		MENU_ID_DA_JOB_OPTION_VIEW_DETAIL,
		MENU_ID_DA_JOB_OPTION_USE_NOW,
		MENU_ID_DA_JOB_OPTION_SAVE_AS,
		MENU_ID_DA_JOB_OPTION_REMOVE,
		MENU_ID_DA_JOB_OPTION_REMOVE_ALL,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_OPTIONS,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION_VIEW_DETAIL, MENU_ID_DA_JOB_OPTION2,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_JOB_VIEW_DETAIL,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION_USE_NOW, MENU_ID_DA_JOB_OPTION2,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_JOB_USE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION_SAVE_AS, MENU_ID_DA_JOB_OPTION2,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_JOB_SAVE_AS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION_REMOVE, MENU_ID_DA_JOB_OPTION2,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_JOB_REMOVE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION_REMOVE_ALL, MENU_ID_DA_JOB_OPTION2,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_JOB_REMOVE_ALL,0));
//#if defined (__MMI_OMA_DD_DOWNLOAD__)
//	ADD_APPLICATION_MENUITEM((MENU_ID_DA_JOB_OPTION_OMA_UPDATE, MENU_ID_DA_JOB_OPTION,0,
//		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_DA_JOB_UPDATE,0));
//#endif

}


void PopulateDownloadAgentRes(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    
    /* resource ID check */
    if ((SCR_ID_DA_END > DL_AGENT_BASE_MAX) ||
        (STR_ID_DA_END > DL_AGENT_BASE_MAX) ||
        (IMG_ID_DA_END > DL_AGENT_BASE_MAX))
    {
        RESOURCE_ID_OUT_OF_RANGE_HANDLER();
    }
    
    PopulateDownloadAgentImgRes();
    PopulateDownloadAgentStrRes();
    PopulateDownloadAgentMenuItemRes();
}

#endif //__MMI_DOWNLOAD_AGENT__

//#endif //DEVELOPER_BUILD_FIRST_PASS
