/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/**
 *	Copyright Notice
 *	?2002 - 2003, Pixtel Communications, Inc., 1489 43rd Ave. W.,
 *	Vancouver, B.C. V6M 4K8 Canada. All Rights Reserved.
 *  (It is illegal to remove this copyright notice from this software or any
 *  portion of it)
 */

/**************************************************************

	FILENAME	: Res_PhoneBook.c

  	PURPOSE		: Populate Resource for

	REMARKS		: nil

	AUTHOR		: Yogesh

	DATE		: August-11-2003

**************************************************************/
#include "CustomCfg.h"

#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif
#include "MMI_features.h"
#include "PhoneBookResDef.h"

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"

#ifdef __MMI_DUAL_SIM_MASTER__
#include "MTPNP_AD_resdef.h"
#endif	/* __MMI_DUAL_SIM_MASTER__ */

typedef enum
{
	MMI_PHB_SETTING_BASE = 1, /* Memory Status and Fields */
#if defined(__MMI_VCARD__)
	MMI_PHB_SETTING_VCARD,
#if defined(__MMI_VCARD_V30__)
	MMI_PHB_SETTING_VCARD_VERSION,
#endif /* defined(__MMI_VCARD_V30__) */
#endif /* defined(__MMI_VCARD__) */
#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
	MMI_PHB_SETTING_SPEAK_NAME,
#endif
	MMI_PHB_SETTING_PREFER_STORAGE,
	MMI_PHB_SETTING_NO_SIM_ENUM_TOTAL = MMI_PHB_SETTING_PREFER_STORAGE,
#if defined(__MMI_PHB_NAME_LIST_FILTER__)
    MMI_PHB_SETTING_NAME_LIST_FILTER,
#endif
	MMI_PHB_SETTING_ENUM_TOTAL
}mmi_phb_setting_num_enum;

/**************************************************************

	FUNCTION NAME		: PopulatePbResData()

  	PURPOSE				: Populate phone book resource data

	INPUT PARAMETERS	: nil

	OUTPUT PARAMETERS	: nil

	RETURNS				: void

	REMARKS				: This function is developer specific call to automate default resource data population

**************************************************************/
void PopulatePbResData()
{
	/*Quick Seach*/
#if defined(__MMI_PHB_QUICK_SEARCH__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_QUICK_SEARCH,MAIN_MENU_PHONEBOOK_MENUID,0,
		SHOW, SHORTCUTABLE |MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_QUICK_SEARCH,IMG_ID_PHB_QUICK_SEARCH));

#if defined(__MMI_MULTITAP_FOR_STAR_AND_POUND__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_QUICK_SEARCH_OPTION,0,2,
		MENU_ID_PHB_QUICK_SEARCH_INPUT_METHOD,
		MENU_ID_PHB_QUICK_SEARCH_OP_OPTION,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_QUICK_SEARCH_INPUT_METHOD,MENU_ID_PHB_QUICK_SEARCH_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_INPUT_METHOD,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_QUICK_SEARCH_OP_OPTION,MENU_ID_PHB_QUICK_SEARCH_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_SCR_VIEW_OPTIONS_CAPTION,0));
		
    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_GENERIC_QUICK_SEARCH_OPTION,0,2,
		MENU_ID_PHB_GENERIC_QUICK_SEARCH_DONE,
		MENU_ID_PHB_GENERIC_QUICK_SEARCH_INPUT_METHOD,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_GENERIC_QUICK_SEARCH_DONE,MENU_ID_PHB_GENERIC_QUICK_SEARCH_OPTION,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DONE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_GENERIC_QUICK_SEARCH_INPUT_METHOD,MENU_ID_PHB_GENERIC_QUICK_SEARCH_OPTION,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_INPUT_METHOD,0));
#endif

#endif

	/*Search*/
	ADD_APPLICATION_MENUITEM((MITEM101_PBOOK_SEARCH_ENTRY,MAIN_MENU_PHONEBOOK_MENUID,0,
		SHOW, SHORTCUTABLE |MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM101,IMG_PHB_SEARCH_ENTRY));

	ADD_APPLICATION_MENUITEM((MITEM101_SEARCH_OPTIONS,0,2,
		MITEM1010_SEARCH,
		MITEM1011_INPUT_MEHTHOD,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));
	ADD_APPLICATION_MENUITEM((MITEM1010_SEARCH,MITEM101_SEARCH_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1010_SEARCH,IMG_MITEM1010_SEARCH));
	ADD_APPLICATION_MENUITEM((MITEM1011_INPUT_MEHTHOD,MITEM101_SEARCH_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_INPUT_METHOD,IMG_MITEM1011_INPUT_METHOD));

	/*Add New Entry*/
#ifdef __MMI_DUAL_SIM_MASTER__
	ADD_APPLICATION_MENUITEM((MITEM102_PBOOK_NEW_ENTRY, MAIN_MENU_PHONEBOOK_MENUID, 3,
		MITEM_ADD_ENTRY_TO_SIM,
		MENU_MTPNP_PB_ADD_SIM2,
		MITEM_ADD_ENTRY_TO_PHONE,
		SHOW, SHORTCUTABLE |MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM102,IMG_PHB_ADD_ENTRY));
#else /* __MMI_DUAL_SIM_MASTER__ */
	ADD_APPLICATION_MENUITEM((MITEM102_PBOOK_NEW_ENTRY,MAIN_MENU_PHONEBOOK_MENUID,2,
		MITEM_ADD_ENTRY_TO_SIM,
		MITEM_ADD_ENTRY_TO_PHONE,
		SHOW, SHORTCUTABLE |MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM102,IMG_PHB_ADD_ENTRY));
#endif /* __MMI_DUAL_SIM_MASTER__ */
	ADD_APPLICATION_MENUITEM((MITEM102_PBOOK_NEW_ENTRY_NO_SIM,MAIN_MENU_PHONEBOOK_NO_SIM_MENUID,1,
		MITEM_ADD_ENTRY_TO_PHONE,
		SHOW, SHORTCUTABLE |MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM102,IMG_PHB_ADD_ENTRY));

#ifdef __MMI_DUAL_SIM_MASTER__
	ADD_APPLICATION_MENUITEM((MITEM_ADD_ENTRY_TO_SIM,MITEM102_PBOOK_NEW_ENTRY,0,
		SHOW, NONMOVEABLE, DISP_LIST,STRING_MTPNP_SIM1PHB_ADD_NEW_ENTRY,IMG_ID_CARD1_PHB_STORAGE_SIM));
#else /* __MMI_DUAL_SIM_MASTER__ */
	ADD_APPLICATION_MENUITEM((MITEM_ADD_ENTRY_TO_SIM,MITEM102_PBOOK_NEW_ENTRY,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_STORAGE_LOCATION_SIM,IMG_STORAGE_SIM));
#endif	/* __MMI_DUAL_SIM_MASTER__ */
	ADD_APPLICATION_MENUITEM((MITEM_ADD_ENTRY_TO_PHONE,MITEM102_PBOOK_NEW_ENTRY,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_STORAGE_LOCATION_PHONE,IMG_STORAGE_HANDSET));

#if defined(__MMI_PHB_MULTI_OPERATION__)
    /* Multi Operation */
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MULTI_OP,MAIN_MENU_PHONEBOOK_MENUID,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MULTI_OP,IMG_PHB_MULTI_OP));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MULTI_OP,MAIN_MENU_PHONEBOOK_NO_SIM_MENUID,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MULTI_OP,IMG_PHB_MULTI_OP));

	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MULTI_OP_OPTION, 0, MMI_PHB_MULTI_OP_OPTION_ENUM_TOTAL,
		MENU_ID_PHB_MULTI_OP_SELECT_ALL,
		MENU_ID_PHB_MULTI_OP_UNSELECT_ALL,
		MENU_ID_PHB_MULTI_OP_SELECT_ALL_FROM_SIM,
		MENU_ID_PHB_MULTI_OP_UNSELECT_ALL_FROM_SIM,
		MENU_ID_PHB_MULTI_OP_SELECT_ALL_FROM_PHONE,
		MENU_ID_PHB_MULTI_OP_UNSELECT_ALL_FROM_PHONE,
		MENU_ID_PHB_MULTI_OP_COPY_SELECTED,
		MENU_ID_PHB_MULTI_OP_DELETE_SELECTED,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));

	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MULTI_OP_SELECT_ALL,MENU_ID_PHB_MULTI_OP_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MULTI_OP_SELECT_ALL,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MULTI_OP_UNSELECT_ALL,MENU_ID_PHB_MULTI_OP_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MULTI_OP_UNSELECT_ALL,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MULTI_OP_SELECT_ALL_FROM_SIM,MENU_ID_PHB_MULTI_OP_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MULTI_OP_SELECT_ALL_FROM_SIM,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MULTI_OP_UNSELECT_ALL_FROM_SIM,MENU_ID_PHB_MULTI_OP_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MULTI_OP_UNSELECT_ALL_FROM_SIM,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MULTI_OP_SELECT_ALL_FROM_PHONE,MENU_ID_PHB_MULTI_OP_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MULTI_OP_SELECT_ALL_FROM_PHONE,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MULTI_OP_UNSELECT_ALL_FROM_PHONE,MENU_ID_PHB_MULTI_OP_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MULTI_OP_UNSELECT_ALL_FROM_PHONE,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MULTI_OP_COPY_SELECTED,MENU_ID_PHB_MULTI_OP_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MULTI_OP_COPY_SELECTED,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_MULTI_OP_DELETE_SELECTED,MENU_ID_PHB_MULTI_OP_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_MULTI_OP_DELETE_SELECTED,IMG_ID_PHB_NO_IMAGE));

	//ADD_APPLICATION_STRING2(STR_COPY_ALL_ABORT, "Abort", "Copy All abort");
	ADD_APPLICATION_IMAGE2(IMG_COPY_ALL_ABORT, CUST_IMG_BASE_PATH"\\\\NoImage.bmp", "Copy all abort image");
	ADD_APPLICATION_STRING2(STR_COPY_ALL_ABORTING, "Aborting..", "Aborting Copy all");
	ADD_APPLICATION_IMAGE2(IMG_COPY_ALL_ABORTING,CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\Progress\\\\PROGRESS"__MMI_RES_TYPE_POPUP_SCREEN__,"Aborting Copy all image");

	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP, "Multi Operation", "Menu item string for Multi Operation");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_SELECT_ALL, "Select All", "Menu item string for Multi Operation Select All");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_UNSELECT_ALL, "Unselect All", "Menu item string for Multi Operation Unselect All");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_SELECT_ALL_FROM_SIM, "Select All From SIM", "Menu item string for Multi Opeation Select All From SIM");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_UNSELECT_ALL_FROM_SIM, "Unselect All From SIM", "Menu item string for Multi Operation Unselect All From SIM");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_SELECT_ALL_FROM_PHONE, "Select All From Phone", "Menu item string for Multi Operation Select All From Phone");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_UNSELECT_ALL_FROM_PHONE, "Unselect All From Phone", "Menu item string for Multi Operation Unselect All From Phone");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_COPY_SELECTED, "Copy selected", "Menu item string for Multi Operation Copy Selected");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_DELETE_SELECTED, "Delete Selected", "Menu item string for Multi Operation Delete Selected");			
    ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_COPY_SELECTED_ASK, "Copy selected?", "Menu item string for Multi Operation Copy Selected");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_DELETE_SELECTED_ASK, "Delete Selected?", "Menu item string for Multi Operation Delete Selected");			
    ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_PRESS_STAR, "Press Star to OnOff", "Menu item string for Multi Operation Press Star");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_PRESS_CENTER, "Press Center to OnOff", "Menu item string for Multi Operation Press Center");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_TOUCH_BOX, "Touch Box to OnOff", "Menu item string for Multi Operation Touch Box");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_PRESS_STAR_TOUCH_BOX, "Press Star or Touch Box to OnOff", "Menu item string for Multi Operation Press Star or Touch Box");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_PRESS_CENTER_TOUCH_BOX, "Press Center or Touch Box to OnOff", "Menu item string for Multi Operation Press Center or Touch Box");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MULTI_OP_DEST_FULL, "Destination Full", "Menu item string for Multi Operation Destination Full");
	ADD_APPLICATION_IMAGE2(IMG_PHB_MULTI_OP,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_MULTI_OPE.PBM","PHB Submenu image for multi operation");
#else /* defined(__MMI_PHB_MULTI_OPERATION__) */

	/* Delete All Phonebook Entry*/
#ifdef __MMI_DUAL_SIM_MASTER__
	ADD_APPLICATION_MENUITEM((MITEM103_PBOOK_DELETE_ALL,MAIN_MENU_PHONEBOOK_MENUID,4,
		MITEM_PBOOK_DELETE_ALL_SIM,
		MENU_MTPNP_PB_DELALL_SIM2,
		MITEM_PBOOK_DELETE_ALL_PHONE,
		MENU_ID_PHB_DELETE_ALL_ONE_BY_ONE,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DELETE,IMG_PHB_DELETE_ALL));
#else /* __MMI_DUAL_SIM_MASTER__ */
	ADD_APPLICATION_MENUITEM((MITEM103_PBOOK_DELETE_ALL,MAIN_MENU_PHONEBOOK_MENUID,3,
		MITEM_PBOOK_DELETE_ALL_SIM,
		MITEM_PBOOK_DELETE_ALL_PHONE,
		MENU_ID_PHB_DELETE_ALL_ONE_BY_ONE,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DELETE,IMG_PHB_DELETE_ALL));
#endif /* __MMI_DUAL_SIM_MASTER__ */

	ADD_APPLICATION_MENUITEM((MITEM103_PBOOK_DELETE_ALL_NO_SIM,MAIN_MENU_PHONEBOOK_NO_SIM_MENUID,2,
		MITEM_PBOOK_DELETE_ALL_PHONE,
		MENU_ID_PHB_DELETE_ALL_ONE_BY_ONE,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DELETE,IMG_PHB_DELETE_ALL));
#ifdef __MMI_DUAL_SIM_MASTER__
	ADD_APPLICATION_MENUITEM((MITEM_PBOOK_DELETE_ALL_SIM,MITEM103_PBOOK_DELETE_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STRING_MTPNP_SIM1PHB_DELETEALL,IMG_ID_CARD1_PHB_STORAGE_SIM));
#else /* __MMI_DUAL_SIM_MASTER__ */
	ADD_APPLICATION_MENUITEM((MITEM_PBOOK_DELETE_ALL_SIM,MITEM103_PBOOK_DELETE_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_DELETE_ALL_SIM,IMG_STORAGE_SIM));
#endif /*__MMI_DUAL_SIM_MASTER__*/
	ADD_APPLICATION_MENUITEM((MITEM_PBOOK_DELETE_ALL_PHONE,MITEM103_PBOOK_DELETE_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_DELETE_ALL_PHONE, IMG_STORAGE_HANDSET));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_DELETE_ALL_ONE_BY_ONE,MITEM103_PBOOK_DELETE_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_DELETE_ALL_ONE_BY_ONE,IMG_PHB_DELETE_ALL_ONE));
#endif /* defined(__MMI_PHB_MULTI_OPERATION__) */

	/* Phonebook Entry Option*/
	ADD_APPLICATION_MENUITEM((MITEM101_PBOOK_VIEW_OPTIONS,0, MMI_PHB_OPTION_ENUM_TOTAL,
#if defined(__MMI_PHB_DIAL_FROM_PHB__)
		MENU_ID_PHB_OPTION_DIAL,
#endif
#if defined(__MMI_PHB_IP_DIAL_FROM_PHB__)
#ifdef __MMI_DUAL_SIM_MASTER__
		MENU_MTPNP_PHB_OPTION_IP_DIAL_SIM1,
		MENU_MTPNP_PHB_OPTION_IP_DIAL_SIM2,
#else /* __MMI_DUAL_SIM_MASTER__ */
		MENU_ID_PHB_OPTION_IP_DIAL,
#endif /*__MMI_DUAL_SIM_MASTER__*/
#endif
#if defined(__MMI_PHB_SEND_SMS_FROM_PHB__)
		MENU_ID_PHB_OPTION_SEND_SMS,
#endif
#if defined(__MMI_PHB_SEND_MMS_FROM_PHB__)
		MENU_ID_PHB_OPTION_SEND_MMS,
#endif
		MITEM1010_PBOOK_VIEW,
		MITEM1011_PBOOK_EDIT,
#if defined(__MMI_PHB_INFO_FIELD__)
		MENU_ID_PHB_OPTION_EDIT_DETAIL,
#endif
#if defined(__MMI_PHB_IMPS_FIELD__) || defined(__MMI_PHB_POC_FIELD__) || defined(__MMI_VOIP__)
		MENU_ID_PHB_OPTION_EDIT_SERVICE_FIELD,
#endif
		MITEM1012_PBOOK_DELETE,
#if defined(__MMI_PHB_COMBINE_COPY_DUPLICATE__)
		MENU_ID_PHB_OPTION_COPY_DUPLICATE,
#else
		MITEM1013_PBOOK_COPY_ENTRY,
#endif
		MITEM1014_PBOOK_MOVE,
#if !defined(__MMI_PHB_COMBINE_COPY_DUPLICATE__)
		MITEM1015_PBOOK_DUPLICATE,
#endif
#if defined(__MMI_VCARD__)
		MENU_ID_PHB_VCARD_SEND_ENTRY,
#endif
#if defined(__MMI_VRSD_DIAL__)
		MENU_ID_VRSD_DIAL_PHB_OPTION,
#endif
#if defined(__MMI_BPP_SUPPORT__)
                MENU_ID_PHB_PRINT,
#endif
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));

	/* Phonebook Entry Option for No SIM inserted mode */
	ADD_APPLICATION_MENUITEM((MITEM101_PBOOK_VIEW_OPTIONS_NO_SIM,0, MMI_PHB_OPTION_NO_SIM_TOTAL,
		MITEM1010_PBOOK_VIEW,
		MITEM1011_PBOOK_EDIT,
#if defined(__MMI_PHB_INFO_FIELD__)
		MENU_ID_PHB_OPTION_EDIT_DETAIL,
#endif
#if defined(__MMI_PHB_IMPS_FIELD__) || defined(__MMI_PHB_POC_FIELD__) || defined(__MMI_VOIP__)
		MENU_ID_PHB_OPTION_EDIT_SERVICE_FIELD,
#endif
		MITEM1012_PBOOK_DELETE,
#if !defined(__MMI_PHB_COMBINE_COPY_DUPLICATE__)
		MITEM1015_PBOOK_DUPLICATE,
#endif
#if defined(__MMI_VCARD__)
		MENU_ID_PHB_VCARD_SEND_ENTRY,
#endif
#if defined(__MMI_BPP_SUPPORT__)
                MENU_ID_PHB_PRINT,
#endif
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));

	ADD_APPLICATION_MENUITEM((MITEM1010_PBOOK_VIEW,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM1010,IMG_MITEM1010));
	ADD_APPLICATION_MENUITEM((MITEM1011_PBOOK_EDIT,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_EDIT,IMG_MITEM1011));
#if defined(__MMI_PHB_INFO_FIELD__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_EDIT_DETAIL,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_EDIT_DETAIL,IMG_MITEM1011));
#endif
#if defined(__MMI_PHB_IMPS_FIELD__) || defined(__MMI_PHB_POC_FIELD__) || defined(__MMI_VOIP__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_EDIT_SERVICE_FIELD,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_EDIT_SERVICE_FIELD, IMG_MITEM1011));
#endif
	ADD_APPLICATION_MENUITEM((MITEM1012_PBOOK_DELETE,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DELETE,IMG_MITEM1012));
#ifdef __MMI_DUAL_SIM_MASTER__
	ADD_APPLICATION_MENUITEM((MITEM1013_PBOOK_COPY_ENTRY,MITEM101_PBOOK_VIEW_OPTIONS,6,
		MENU_MTPNP_PB_COPY_SIM1TOPHONE,
		MENU_MTPNP_PB_COPY_PHONETOSIM1,
		MENU_MTPNP_PB_COPY_SIM2TOSIM1,
		MENU_MTPNP_PB_COPY_SIM1TOSIM2,
		MENU_MTPNP_PB_COPY_SIM2TOPHONE,
		MENU_MTPNP_PB_COPY_PHONETOSIM2,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM1013,IMG_MITEM1013));

	ADD_APPLICATION_MENUITEM((MITEM1014_PBOOK_MOVE,MITEM101_PBOOK_VIEW_OPTIONS,6,
		MENU_MTPNP_PB_MOVE_SIM1TOPHONE,
		MENU_MTPNP_PB_MOVE_PHONETOSIM1,
		MENU_MTPNP_PB_MOVE_SIM2TOSIM1,
		MENU_MTPNP_PB_MOVE_SIM1TOSIM2,
		MENU_MTPNP_PB_MOVE_SIM2TOPHONE,
		MENU_MTPNP_PB_MOVE_PHONETOSIM2,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM1014,IMG_MITEM1014));
#else	/* __MMI_DUAL_SIM_MASTER__ */
	ADD_APPLICATION_MENUITEM((MITEM1013_PBOOK_COPY_ENTRY,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM1013,IMG_MITEM1013));
	ADD_APPLICATION_MENUITEM((MITEM1014_PBOOK_MOVE,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM1014,IMG_MITEM1014));
#endif	/* __MMI_DUAL_SIM_MASTER__ */
	ADD_APPLICATION_MENUITEM((MITEM1015_PBOOK_DUPLICATE,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM1015,IMG_MITEM1015));

	/*Dial from phonebook entry option menu.*/
#if defined(__MMI_PHB_DIAL_FROM_PHB__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_DIAL,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_DIAL,IMG_ID_PHB_NO_IMAGE));
#endif

	/*IP Dial from phonebook entry option menu.*/
#if defined(__MMI_PHB_IP_DIAL_FROM_PHB__)
#if defined(__MMI_DUAL_SIM_MASTER__)
	ADD_APPLICATION_MENUITEM((MENU_MTPNP_PHB_OPTION_IP_DIAL_SIM1,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STRING_MTPNP_PHB_OPTION_IP_DIAL_SIM1,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_MTPNP_PHB_OPTION_IP_DIAL_SIM2,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STRING_MTPNP_PHB_OPTION_IP_DIAL_SIM2,IMG_ID_PHB_NO_IMAGE));
#else /* __MMI_DUAL_SIM_MASTER__ */
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_IP_DIAL,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_OPTION_IP_DIAL,IMG_ID_PHB_NO_IMAGE));

	ADD_APPLICATION_STRING2(STR_ID_PHB_OPTION_IP_DIAL,	"IP Dial"	,"Menu item string for View options->IP Dial");
#endif /*__MMI_DUAL_SIM_MASTER__*/
#endif
	/*Send SMS from phonebook entry option menu.*/
#if defined(__MMI_PHB_SEND_SMS_FROM_PHB__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_SEND_SMS,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_OPTION_SEND_SMS,IMG_ID_PHB_NO_IMAGE));

	ADD_APPLICATION_STRING2(STR_ID_PHB_OPTION_SEND_SMS	,"Send SMS"	,"Menu item string for View options->Send SMS");
#endif
#if defined(__MMI_PHB_SEND_MMS_FROM_PHB__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_SEND_MMS, MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_OPTION_SEND_MMS,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_STRING2(STR_ID_PHB_OPTION_SEND_MMS	,"Send MMS"	,"Menu item string for Send Message of View options->Send MMS");
#endif

	/*Combine copy and duplicate into one option.*/
#if defined(__MMI_PHB_COMBINE_COPY_DUPLICATE__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_OPTION_COPY_DUPLICATE,MITEM101_PBOOK_VIEW_OPTIONS,2,
		MITEM1013_PBOOK_COPY_ENTRY,
		MITEM1015_PBOOK_DUPLICATE,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_OPTION_COPY_DUPLICATE,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MITEM1013_PBOOK_COPY_ENTRY,MENU_ID_PHB_OPTION_COPY_DUPLICATE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1013,IMG_MITEM1013));
	ADD_APPLICATION_MENUITEM((MITEM1015_PBOOK_DUPLICATE,MENU_ID_PHB_OPTION_COPY_DUPLICATE,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_MITEM1015,IMG_MITEM1015));

	ADD_APPLICATION_STRING2(STR_ID_PHB_OPTION_COPY_DUPLICATE,	"Copy"	,"Menu item string for View options->Copy Entry");
#endif

	/*vCard Menu*/
	/*vCard - SubMenu of PhoneBook Entry Options*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_SEND_ENTRY,MITEM101_PBOOK_VIEW_OPTIONS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_VCARD_SEND_ENTRY, IMG_ID_PHB_NO_IMAGE));

	/*vCard - SubMenu of PhoneBook Setting*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_MYCARD,MITEM110_PBOOK_SETTINGS,2,
		MENU_ID_PHB_VCARD_EDIT_MYCARD,
		MENU_ID_PHB_VCARD_SEND_MYCARD,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_VCARD, IMG_ID_PHB_NO_IMAGE));

	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_EDIT_MYCARD,MENU_ID_PHB_VCARD_MYCARD,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_VCARD_EDIT_MYCARD, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_SEND_MYCARD,MENU_ID_PHB_VCARD_MYCARD,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_VCARD_SEND_MYCARD,IMG_ID_PHB_NO_IMAGE));

#if defined(__MMI_BPP_SUPPORT__)
    /* BPP Print Menu - SubMenu of Phonebook Entry Options*/
        ADD_APPLICATION_MENUITEM((MENU_ID_PHB_PRINT,MITEM101_PBOOK_VIEW_OPTIONS,0,
                SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_PRINT, IMG_ID_PHB_NO_IMAGE));	
#endif /* defined(__MMI_BPP_SUPPORT__) */

#if defined(__MMI_FILE_MANAGER__) && !defined(__MMI_DISPLAY_CHAR_HIDE_MENU_FROM_FILE__)
	/*Associate Image - Option Menu For Associate Image Handling*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_IMAGE_OPTION,0,3,
		MENU_ID_PHB_IMAGE_OPTION_VIEW,
		MENU_ID_PHB_IMAGE_OPTION_SELECT,
		MENU_ID_PHB_IMAGE_OPTION_DELETE,
		SHOW, NONMOVEABLE, DISP_LIST,STR_SCR_VIEW_OPTIONS_CAPTION, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_IMAGE_OPTION_VIEW,MENU_ID_PHB_IMAGE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_VIEW_PICTURE_CAPTION, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_IMAGE_OPTION_SELECT,MENU_ID_PHB_IMAGE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_SELECT_FILE,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_IMAGE_OPTION_DELETE,MENU_ID_PHB_IMAGE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_DELETE_REF, IMG_ID_PHB_NO_IMAGE));

#if defined(__MMI_AVATAR__)	
    /* 3D Avatar Image - Option Menu for Associate Image Handling */
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_AVATAR_IMAGE_OPTION,0,3,
		MENU_ID_PHB_AVATAR_IMAGE_OPTION_VIEW,
		MENU_ID_PHB_AVATAR_IMAGE_OPTION_SELECT,
		MENU_ID_PHB_AVATAR_IMAGE_OPTION_DELETE,
		SHOW, NONMOVEABLE, DISP_LIST,STR_SCR_VIEW_OPTIONS_CAPTION, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_AVATAR_IMAGE_OPTION_VIEW,MENU_ID_PHB_AVATAR_IMAGE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_VIEW_PICTURE_CAPTION, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_AVATAR_IMAGE_OPTION_SELECT,MENU_ID_PHB_AVATAR_IMAGE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_AVATAR_SELECT_FILE,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_AVATAR_IMAGE_OPTION_DELETE,MENU_ID_PHB_AVATAR_IMAGE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_DELETE_REF, IMG_ID_PHB_NO_IMAGE));
#endif /* defined(__MMI_AVATAR__)	*/
	/*Save image to Phb from File Mgr*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_FMGR_SAVE_OPTION,0,3,
		MENU_ID_PHB_FMGR_SAVE_NEW,
		MENU_ID_PHB_FMGR_SAVE_LIST,
		MENU_ID_PHB_FMGR_SAVE_CALLGRP,
		SHOW, NONMOVEABLE, DISP_LIST,STR_SCR_VIEW_OPTIONS_CAPTION, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_FMGR_SAVE_NEW,MENU_ID_PHB_FMGR_SAVE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_TO_NEW_ENTRY, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_FMGR_SAVE_LIST,MENU_ID_PHB_FMGR_SAVE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_TO_SELECT_ENTRY,IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_FMGR_SAVE_CALLGRP,MENU_ID_PHB_FMGR_SAVE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_TO_CALLER_GROUP, IMG_ID_PHB_NO_IMAGE));

	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_IMAGE_SELECT_FILE	,"Select From File"	,"Select Image From File Manager");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_IMAGE_DELETE_REF	,"Delete Reference"	,"Delete image reference from File Manager");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_IMAGE_NO_SELECT	,"No Image Selected"	,"Pop up string for No Image Select when view image");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_TO_NEW_ENTRY	,"To New Entry"	,"Forward image to a new entry");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_TO_SELECT_ENTRY	,"To Selected Entry"	,"Forward image to a selected entry");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_TO_CALLER_GROUP	,"To Caller Group"	,"Forward image to caller group");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_IMAGE_NOT_SUPPORT	,"Format not support"	,"Error Message for file mgr");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_DISC_FULL,	"Free space is not enough for image."	,"Error Message for file mgre");
	ADD_APPLICATION_STRING2(STR_ID_PHB_FMGR_IMAGE_SELECTED	,"Select From File"	,"Selected Image From File Manager");
#endif	/* defined(__MMI_FILE_MANAGER__) && !defined(__MMI_DISPLAY_CHAR_HIDE_MENU_FROM_FILE__) */
#if defined(__MMI_AVATAR__)	
    ADD_APPLICATION_STRING2(STR_ID_PHB_AVATAR_SELECT_FILE	,"From 3D Avatar"	,"From 3D Avatar");
    ADD_APPLICATION_STRING2(STR_ID_PHB_AVATAR_SELECTED	,"3D Avatar Selected"	,"3D Avatar Selected");
    ADD_APPLICATION_STRING2(STR_ID_PHB_CANT_VIEW_AVATAR_IN_CALL	,"Cannot view avatar in call"	,"Cannot view avatar in call");
    ADD_APPLICATION_STRING2(STR_ID_PHB_AVATAR_NOT_EXISTED	,"Avatar not existed"	,"Avatar not existed");
#endif /* defined(__MMI_AVATAR__)	*/


	ADD_APPLICATION_STRING2(STR_SCR_PBOOK_CAPTION	,"Phone Book"	,"Title String for PhoneBook main screen");

	ADD_APPLICATION_STRING2(STR_MITEM101			,"Search Entry"	,"Menu item string for Search Entry");
	ADD_APPLICATION_STRING2(STR_MITEM102			,"Add New Entry","Menu item string for New Entry");
	//ADD_APPLICATION_STRING2(STR_MITEM103			,"Delete All"	,"Menu item string for Delete All entries");
	ADD_APPLICATION_STRING2(STR_MITEM1010			,"View"		,"Menu item string for View options->view");
	//ADD_APPLICATION_STRING2(STR_MITEM1011			,"Edit"		,"Menu item string for View options->Edit");
	//ADD_APPLICATION_STRING2(STR_MITEM1012			,"Delete"	,"Menu item string for View options->Delete");
	ADD_APPLICATION_STRING2(STR_MITEM1013			,"Copy"		,"Menu item string for View options->Copy Entry");
	ADD_APPLICATION_STRING2(STR_MITEM1014			,"Move"		,"Menu item string for View options->Move");
	ADD_APPLICATION_STRING2(STR_MITEM1015			,"Duplicate"	,"Menu item string for View options->Duplicate");
	ADD_APPLICATION_STRING2(STR_MITEM1010_SEARCH	,"Search", "Search options->search");
	//ADD_APPLICATION_STRING2(STR_MITEM1011_INPUT_METHOD,"Input Method","Search options->input method");

	ADD_APPLICATION_IMAGE2(IMG_MITEM1010,CUST_IMG_BASE_PATH"\\\\NoImage.bmp"	,"Menu item image for View options->View");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1011,CUST_IMG_BASE_PATH"\\\\NoImage.bmp"	,"Menu item image for View options->Edit");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1012,CUST_IMG_BASE_PATH"\\\\NoImage.bmp"	,"Menu item image for View options->Delete");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1013,CUST_IMG_BASE_PATH"\\\\NoImage.bmp"	,"Menu item image for View options->Copy Entry");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1014,CUST_IMG_BASE_PATH"\\\\NoImage.bmp"	,"Menu item image for View options->Move");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1015,CUST_IMG_BASE_PATH"\\\\NoImage.bmp"	,"Menu item image for View options->Duplicate");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1010_SEARCH	,CUST_IMG_BASE_PATH"\\\\NoImage.bmp", "Search options->search");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1011_INPUT_METHOD,CUST_IMG_BASE_PATH"\\\\NoImage.bmp","Search options->input method");
	ADD_APPLICATION_STRING2(STR_NO_ENTRIES_MESSAGE, "Phone Book Empty!", "No entries message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NAME_NUM_REQUIRE	,"Enter either name or number","Error message");
#if defined(__MMI_PHB_NAME_AND_NUM_REQUIRE__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_NAME_REQUIRE	,"Please enter name","Error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NUM_REQUIRE	,"Please enter number","Error message");
#endif
	ADD_APPLICATION_STRING2(STR_ID_PHB_NUM_INVALID	,"Invalid Number Format","Error message");
	ADD_APPLICATION_STRING2(STR_DELETE_QUERY_MSG			,"Delete"		,"Delete query message");
	ADD_APPLICATION_STRING2(STR_COPY_QUERY_MSG				,"Copy"		,"Copy query message");
	ADD_APPLICATION_STRING2(STR_MOVE_QUERY_MSG				,"Move"		,"Move query message");
	ADD_APPLICATION_STRING2(STR_DUPLICATE_QUERY_MSG			,"Duplicate"	,"Duplicate query message");
	ADD_APPLICATION_STRING2(STR_DELETEALL_QUERY_SIM_MSG		,"Delete SIM"	,"Delete All SIM message");
	ADD_APPLICATION_STRING2(STR_DELETEALL_QUERY_PHONE_MSG	,"Delete Phone","Delete All Phone message");
	//ADD_APPLICATION_STRING2(STR_SAVE_QUERY					,"Save"		,"Save entry query");
	ADD_APPLICATION_STRING2(STR_PBOOK_FULL_MSG	,"Phonebook Full!"	,"Phonebook full message");
	ADD_APPLICATION_STRING2(STR_SIM_FULL_MSG	,"SIM Storage Full!"	,"SIM full message");
	ADD_APPLICATION_STRING2(STR_PHONE_FULL_MSG	,"Phone Storage Full!"	,"Phone full message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NO_ENTRY_TO_SELECT	,"No Contact To Select!"	,"No entry can be selected message");
	ADD_APPLICATION_IMAGE2(IMG_COPIED, CUST_IMG_PATH"\\\\MainLCD\\\\Warningpage\\\\PopUpPage\\\\PP_COP"__MMI_RES_TYPE_POPUP_SCREEN__, "Copied image");
	ADD_APPLICATION_IMAGE2(IMG_ENTRY_MOVED_MSG			,CUST_IMG_PATH"\\\\MainLCD\\\\Warningpage\\\\PopUpPage\\\\PP_MOV"__MMI_RES_TYPE_POPUP_SCREEN__,"Entry Moved message icon");
	ADD_APPLICATION_IMAGE2(IMG_ENTRY_DUPLICATED_MSG		,CUST_IMG_PATH"\\\\MainLCD\\\\Warningpage\\\\PopUpPage\\\\PP_DUP"__MMI_RES_TYPE_POPUP_SCREEN__,"Entry Duplicated message icon");	
	ADD_APPLICATION_STRING2(STR_SCR_PBOOK_VIEW_CAPTION	,"Phone Book List"	,"Title string for entry list screen");
	ADD_APPLICATION_STRING2(STR_SCR_VIEW_OPTIONS_CAPTION	,"Contact Options"	,"Title string for view options screen");
	ADD_APPLICATION_STRING2(STR_SCR_INLINE_EDIT_CAPTION		,"Edit Contact"	,"Title string for Inline Edit screen");
	ADD_APPLICATION_STRING2(STR_SCR_ENTRY_VIEW_CAPTION,		"Phone Book View"	,"Title string for Entry View screen");
	ADD_APPLICATION_STRING2(STR_SCR_SEARCH_NAME_CAPTION	,"Name"			,"Title string for search name entry screen");
	ADD_APPLICATION_STRING2(STR_PROCESSING_PHONEBOOK	,"Processing Phone Book"	, "Processing Phonebook message");
	ADD_APPLICATION_IMAGE2(IMG_PROCESSING_PHONEBOOK	,CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\Progress\\\\PROGRESS"__MMI_RES_TYPE_POPUP_SCREEN__,"Processing Phonebook message icon");
	//ADD_APPLICATION_STRING2(STR_SCR_DELETE_ALL_MENU_CAPTION	,"Delete All", "Delete all menu caption string");
	ADD_APPLICATION_STRING2(STR_CHOOSE_STORAGE_CAPTION	,"Choose Storage"	,"Storage menu caption string");
	ADD_APPLICATION_STRING2(STR_STORAGE_LOCATION_SIM, "To SIM", "Storage location To SIM");
	ADD_APPLICATION_STRING2(STR_STORAGE_LOCATION_PHONE, "To Phone","Strorage location To Phone");
	ADD_APPLICATION_STRING2(STR_SCR_ADD_NEW_ENTRY_CAPTION, "New Contact", "New Entry screen caption");
	ADD_APPLICATION_STRING2(STR_ID_PHB_ADDED, "Added", "Added");
	ADD_APPLICATION_STRING2(STR_ID_PHB_ADD_QUERY, "Add?", "Add?");
	ADD_APPLICATION_STRING2(STR_EMERGENCY_NUMBER,"Emergency Number", "Emergency Number");
	ADD_APPLICATION_IMAGE2(IMG_SCR_PBOOK_CAPTION	,CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_PB.PNG","Title image for PhoneBook main screen");
	ADD_APPLICATION_IMAGE2(IMG_PHB_SEARCH_ENTRY,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_ENTRY.PBM","PHB Submenu image for Search Entry");
	ADD_APPLICATION_IMAGE2(IMG_PHB_ADD_ENTRY,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_ADD.PBM","PHB Submenu image for Add New Entry");
	ADD_APPLICATION_IMAGE2(IMG_PHB_DELETE_ALL,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_DELE.PBM","PHB Submenu image for Delete All");
	ADD_APPLICATION_IMAGE2(IMG_PHB_DELETE_ALL_ONE,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_DELEO.PBM","PHB Submenu image for Delete All");
	ADD_APPLICATION_IMAGE2(IMG_PHB_COPY_ALL,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_COPY.PBM","PHB Submenu image for Copy All");
	ADD_APPLICATION_IMAGE2(IMG_PHB_OWNER_NUMBER,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_OWNER.PBM","PHB Submenu image for Owner Number");
	//ADD_APPLICATION_IMAGE2(IMG_PHB_SDN,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_EDN.PBM","PHB Submenu image for SDN");
	//ADD_APPLICATION_IMAGE2(IMG_PHB_SOS_NUMBER,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_SOS.PBM","PHB Submenu image for SOS Number");
	ADD_APPLICATION_IMAGE2(IMG_PHB_SPEED_DIAL,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_SPEED.PBM","PHB Submenu image for Speed Dial");
	ADD_APPLICATION_IMAGE2(IMG_PHB_CALLER_GROUP,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_GROUP.PBM","PHB Submenu image for Caller Group");
	ADD_APPLICATION_IMAGE2(IMG_PHB_SETTINGS,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_SET.PBM","PHB Submenu image for Phonebook Settings");
	ADD_APPLICATION_IMAGE2(IMG_NAME			,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_Name.PBM"		,"name image");
	ADD_APPLICATION_IMAGE2(IMG_MOBILE_NUMBER,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_PHONE.PBM"	,"mobile number image");
	ADD_APPLICATION_IMAGE2(IMG_HOME_NUMBER	,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_HOME.PBM"	,"home number image");
	ADD_APPLICATION_IMAGE2(IMG_COMPANY_NAME	,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_CP.PBM"		,"company image");
	ADD_APPLICATION_IMAGE2(IMG_EMAIL_ADDRESS,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_Em.PBM"		,"email image");
	ADD_APPLICATION_IMAGE2(IMG_OFFICE_NUMBER,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_OFCNB.PBM"	,"office number image");
	ADD_APPLICATION_IMAGE2(IMG_FAX_NUMBER	,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_FAX.PBM"		,"fax number image");
	ADD_APPLICATION_IMAGE2(IMG_PICTURE		,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_PIC.PBM"		,"picture tag image");
	ADD_APPLICATION_IMAGE2(IMG_RING_TONE	,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_RING.PBM"	,"ring tone image");
	ADD_APPLICATION_IMAGE2(IMG_CALLER_GROUP	,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\Callergroup\\\\CG_GROUP.PBM","caller group image");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_CALLERGRP_MEMBER	,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\Callergroup\\\\CG_MEMBER.PBM","caller group image");
	ADD_APPLICATION_IMAGE2(IMG_STORAGE_SIM			,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_INSIM.PBM","SIM Card image");
	ADD_APPLICATION_IMAGE2(IMG_STORAGE_HANDSET		,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_INPH.PBM","Handset image");
#if defined(__MMI_PHB_BIRTHDAY_FIELD__)
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_BIRTHDAY,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_BDAY.PBM"		,"birthday image");
#endif
#if defined(__MMI_PHB_INFO_FIELD__)
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_TITLE,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_TITLE.PBM"		,"title image");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_URL,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_URL.PBM"		,"url image");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_ADDRESS,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_ADDR.PBM"		,"address image");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_NOTE,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_NOTE.PBM"		,"note image");
#endif

#if defined(__MMI_PHB_USIM_FIELD__)
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_ANR,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_ANR.PBM"		,"anr image");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_SNE,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_SNE.PBM"		,"sne image");
#endif

#ifdef __MMI_VOIP__
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_VOIP,CUST_IMG_PATH"\\\\MainLCD\\\\VOIP\\\\Call\\\\Phonebook\\\\PV_VoIP.PBM"		,"VoIP image");
#endif

	//ADD_APPLICATION_STRING2(STR_SCR_SEARCH_OPTIONS_CAPTION, "Option", "Title string for Search options screen");
	ADD_APPLICATION_STRING2(STR_NO_NUMBER_TO_DIAL,"No Number to Dial!","No Number to Dial");
	ADD_APPLICATION_STRING2(STR_CHOOSE_NUMBER_CAPTION,"Choose Number", "Choose Number Title");
	ADD_APPLICATION_STRING2(STR_COMPANY_CAPTION, "Company", "Company");
	ADD_APPLICATION_STRING2(STR_VIEW_PICTURE_CAPTION, "View Picture", "View Picture caption");
	//ADD_APPLICATION_STRING2(STR_PHB_OPTIONS, "Option", "Phonebook Options");

	ADD_APPLICATION_STRING2(STR_ID_PHB_NAME		,"Name"	, "Name String");
	ADD_APPLICATION_STRING2(STR_ID_PHB_MOBILE_NUMBER	,"Mobile Number"	, "Mobile Number String");
	//ADD_APPLICATION_STRING2(STR_ID_PHB_ADD, "Add", "General string for add a record");

	ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD						,"My vCard"			,"Menu item string for vCard");
	ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD_EDIT_MYCARD			,"Edit My Card"	,"Sub Menu item string for vCard -> Edit My Card");
	ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD_SEND_MYCARD			,"Send My Card"	,"Sub Menu item string for vCard -> Send My Card");
	ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD_SEND_ENTRY			,"Send This Entry"	,"Sub Menu item string for vCard -> Send This Card");

	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_NO_IMAGE,CUST_IMG_BASE_PATH"\\\\NoImage.bmp"	,"Common no image for submenu item.");
	ADD_APPLICATION_STRING2(STR_ID_PHB_AUDIO_ID_NOT_EXIST	,"Audio File Does Not Exist"	,"Audio File Does Not Exist");

#if defined(__MMI_BPP_SUPPORT__)
        ADD_APPLICATION_STRING2(STR_ID_PHB_PRINT	,"Print This Entry"	,"Sub Menu item string for BPP Print this entry");
#endif /* defined(__MMI_BPP_SUPPORT__) */

#if defined(__MMI_DOWNLOADABLE_THEMES_SUPPORT__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_THEME_TONE_NOT_FOUND	,"Theme Tone Not Found"	,"Theme Tone not found");
#endif	

#if defined(__MMI_PHB_QUICK_SEARCH__)		/*Quick Search*/
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_QUICK_SEARCH		,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_QSERH.PBM","Quick Search image");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_QUICK_SEARCH_FIND		,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_Search.pbm","Quick Search image");
	ADD_APPLICATION_STRING2(STR_ID_PHB_QUICK_SEARCH	,"Quick Search"	,"Quick Search string");
#endif

	ADD_APPLICATION_STRING2(STR_ID_PHB_OP_IMAGE_FAIL	,"Image"	,"Entry operation error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_OP_VIDEO_FAIL	,"Video"	,"Entry operation error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_ADD_FAIL			," Add Fail!"	,"Entry operation error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_EDIT_FAIL			," Edit Fail!"	,"Entry operation error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_DUPLICATE_FAIL			," Duplicate Fail!"	,"Entry operation error message");
	ADD_APPLICATION_STRING2(STR_ID_PHB_OP_COMMA		,", "	,"Entry operation error message");

#if defined(__MMI_PHB_CALLERGROUP_IN_SIM__) /* Associate caller group in SIM card entry*/
	ADD_APPLICATION_STRING2(STR_ID_PHB_REFRESH_SIM	,"SIM changed, Delete all caller group in SIM?"	,"SIM change prompt message.");
#endif
	/*For image list default icon*/
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_LIST_ICON1		,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_Default.jpg","Picture List Default Icon");

	PopulateAdvancedPbResData();
	PopulateInlineEditRes();
#if !defined(__MMI_PHB_MULTI_OPERATION__)
	PopulateCopyAllResData();
#endif /* defined(__MMI_PHB_MULTI_OPERATION__) */
	PopulateExtraNumberRes();
	PopulatePbookSettingsData();
	PopulatePhbExtraMainMenuRes();
}


void PopulateAdvancedPbResData(void)
{
	/*Caller Group*/
	ADD_APPLICATION_MENUITEM((MITEM109_PBOOK_CALLER_GROUPS, MAIN_MENU_PHONEBOOK_MENUID, 0,
		SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM109,IMG_PHB_CALLER_GROUP));

	/*Caller Group Member List*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLERGROUP_MEMBER_VIEW_OPTION,0,2,
		MENU_ID_PHB_CALLERGROUP_MEMBER_ADD_MEMBER,
		MENU_ID_PHB_CALLERGROUP_MEMBER_DELETE_MEMBER,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLERGROUP_MEMBER_ADD_MEMBER,MENU_ID_PHB_CALLERGROUP_MEMBER_VIEW_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_ADD,IMG_PHB_ADD_ENTRY));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLERGROUP_MEMBER_DELETE_MEMBER,MENU_ID_PHB_CALLERGROUP_MEMBER_VIEW_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_DELETE,IMG_MITEM1012));

	ADD_APPLICATION_IMAGE2(IMG_PHB_DEFAULT  ,CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Incoming\\\\CL_incom.gif", "Deafult picture of every entry");
	ADD_APPLICATION_IMAGE2(IMG_PHB_PICTURE1 ,CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Incoming\\\\CL_incom01.gif", "Picture 1");
	ADD_APPLICATION_IMAGE2(IMG_PHB_PICTURE2 ,CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Incoming\\\\CL_incom02.gif", "Picture 2");
	ADD_APPLICATION_IMAGE2(IMG_PHB_PICTURE3 ,CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Incoming\\\\CL_incom03.gif", "Picture 3");
	ADD_APPLICATION_IMAGE2(IMG_PHB_PICTURE4 ,CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Incoming\\\\CL_incom04.gif", "Picture 4");
	ADD_APPLICATION_IMAGE2(IMG_CG_NAME,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\CallerGroup\\\\CG_GROUP.PBM","Caller Grp name image");
	ADD_APPLICATION_IMAGE2(IMG_CG_ALERT_TYPE,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\CallerGroup\\\\CG_ALERT.PBM","Caller Grp alert type image");
	ADD_APPLICATION_IMAGE2(IMG_CG_RING_TONE,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\CallerGroup\\\\CG_RING.PBM","Caller Grp ring tone image");
	ADD_APPLICATION_IMAGE2(IMG_CG_PICTURE,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\CallerGroup\\\\CG_PIC.PBM","Caller Grp picture image");
	ADD_APPLICATION_IMAGE2(IMG_CG_INDICATOR_LITE,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\CallerGroup\\\\CG_PATT.PBM","Caller Grp indicator lite image");
	ADD_APPLICATION_STRING2(STR_MITEM109	,"Caller Group"	,"Menu item string for Caller Groups option");
	ADD_APPLICATION_STRING2(STR_SCR_CALLER_GROUP_CAPTION, "Caller Group", "Title string for Caller Groups screen");
	ADD_APPLICATION_STRING2(STR_SCR_CG_DETAILS_CAPTION, "Caller Group Details", "Title string for Caller Groups Details screen");
	ADD_APPLICATION_IMAGE2(IMG_CG_ALERT_TYPE,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\CallerGroup\\\\CG_ALERT.PBM","Caller Grp alert type image");
	ADD_APPLICATION_IMAGE2(IMG_CG_RING_TONE,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\CallerGroup\\\\CG_RING.PBM","Caller Grp ring tone image");
	ADD_APPLICATION_IMAGE2(IMG_CG_PICTURE,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\CallerGroup\\\\CG_PIC.PBM","Caller Grp picture image");
	ADD_APPLICATION_IMAGE2(IMG_CG_INDICATOR_LITE,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\CallerGroup\\\\CG_PATT.PBM","Caller Grp indicator lite image");
	//ADD_APPLICATION_STRING2(STR_NONE,					"None", "String None");
	ADD_APPLICATION_STRING2(STR_GRP_NAME_CAPTION, "Group Name", "Group Name Caption");
	ADD_APPLICATION_STRING2(STR_CG_RENAME_FAIL_MSG, "Cannot rename as other groups", "CG rename fail msg");
	ADD_APPLICATION_STRING2(STR_CALLER_GROUP_1, "Friends"	, "Caller Group 1");
	ADD_APPLICATION_STRING2(STR_CALLER_GROUP_2, "Family"	, "Caller Group 2");
	ADD_APPLICATION_STRING2(STR_CALLER_GROUP_3, "VIP"		, "Caller Group 3");
	ADD_APPLICATION_STRING2(STR_CALLER_GROUP_4, "Business"	, "Caller Group 4");
	ADD_APPLICATION_STRING2(STR_CALLER_GROUP_5, "Others"	, "Caller Group 5");
	ADD_APPLICATION_STRING2(STR_ID_PHB_CALLERGROUP_MEMBER_LIST, "Member List"	, "Caller Group Member List");
	ADD_APPLICATION_STRING2(STR_PICTURE_1, "Picture 1", "Picture Tag 1");
	ADD_APPLICATION_STRING2(STR_PICTURE_2, "Picture 2", "Picture Tag 2");
	ADD_APPLICATION_STRING2(STR_PICTURE_3, "Picture 3", "Picture Tag 3");
	ADD_APPLICATION_STRING2(STR_PICTURE_4, "Picture 4", "Picture Tag 4");
	ADD_APPLICATION_STRING2(STR_PHB_DUPLICATING,"Duplicating", "Duplicating");
	//ADD_APPLICATION_STRING2(STR_PHB_SAVING, "Saving", "Saving");
	ADD_APPLICATION_STRING2(STR_PHB_ERASING, "Erasing", "Erasing");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SORTING_EMAIL, "Sorting Email", "Processing String");
	ADD_APPLICATION_STRING2(STR_NUMBER_TOO_LONG, "Number Too Long! Maximum = 40", "Number Too Long!");
	ADD_APPLICATION_STRING2(STR_NOT_SAVED_NUMBER_TOO_LONG, "Not Saved, Number Too Long!", "Number Too Long!");
	ADD_APPLICATION_STRING2(STR_NOT_MOVED_NUMBER_TOO_LONG, "Not Moved, Number Too Long!", "Number Too Long!");
	ADD_APPLICATION_STRING2(STR_NOT_COPIED_NUMBER_TOO_LONG, "Not Copied, Number Too Long!", "Number Too Long!");
	ADD_APPLICATION_STRING2(STR_NOT_DUPLICATED_NUMBER_TOO_LONG, "Not Duplicated, Number Too Long!", "Number Too Long!");
	ADD_APPLICATION_STRING2(STR_COPIED_NAME_MODIFIED, "Copied, Name Modified!", "Copied, Name Modified!");
	ADD_APPLICATION_STRING2(STR_COPIED_TO_PHONE_DONE, "Copied To Phone!", "Copied To Phone!");
	ADD_APPLICATION_STRING2(STR_COPIED_TO_SIM_DONE, "Copied To SIM!", "Copied To SIM!");
	ADD_APPLICATION_STRING2(STR_MOVED_NAME_MODIFIED, "Moved, Name Modified!", "Moved, Name Modified!");
	ADD_APPLICATION_STRING2(STR_MOVED_TO_PHONE_DONE, "Moved To Phone!", "Moved To Phone!");
	ADD_APPLICATION_STRING2(STR_MOVED_TO_SIM_DONE, "Moved To SIM!", "Moved To SIM!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_COPIED, "Copied!", "Copied!");
	ADD_APPLICATION_STRING2(STR_ENTRY_COPIED, "Contact Copied!", "Entry Copied!");
	ADD_APPLICATION_STRING2(STR_ENTRIES_COPIED, "Contacts Copied!", "Entries Copied!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_ENTRY_DELETED, "Contact Deleted!", "Entry Deleted!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_ENTRIES_DELETED, "Contacts Deleted!", "Entries Deleted!");
}

#if !defined(__MMI_PHB_MULTI_OPERATION__)
void PopulateCopyAllResData(void)
{

	/*Copy All*/
#ifdef __MMI_DUAL_SIM_MASTER__
	ADD_APPLICATION_MENUITEM((MITEM104_PBOOK_COPY_ALL,MAIN_MENU_PHONEBOOK_MENUID,6,
		MITEM_PBOOK_COPY_ALL_SIM,
		MITEM_PBOOK_COPY_ALL_PHONE,
              MENU_MTPNP_PB_COPYALL_SIM2TOPHONE,	
              MENU_MTPNP_PB_COPYALL_PHONETOSIM2,
              MENU_MTPNP_PB_COPYALL_SIM1TOSIM2,		
              MENU_MTPNP_PB_COPYALL_SIM2TOSIM1,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM104,IMG_PHB_COPY_ALL));
#else/* __MMI_DUAL_SIM_MASTER__ */
	ADD_APPLICATION_MENUITEM((MITEM104_PBOOK_COPY_ALL,MAIN_MENU_PHONEBOOK_MENUID,2,
		MITEM_PBOOK_COPY_ALL_SIM,
		MITEM_PBOOK_COPY_ALL_PHONE,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM104,IMG_PHB_COPY_ALL));
#endif/* __MMI_DUAL_SIM_MASTER__ */

//huzhuhua 080722 begin
#ifdef __PHONEBOOK_INPUT__ 	
//huzhuhua 080724 begin 
    ADD_APPLICATION_MENUITEM((MENU_ID_PB_INPUT_OPTION, 0, 4,
                              MENU_ID_PB_INPUT_OPTION_INPUT,
                              MENU_ID_PB_INPUT_OPTION_RENAME,
                              MENU_ID_PB_INPUT_OPTION_DELETE,
                              MENU_ID_PB_INPUT_OPTION_DELETEALL,
                              SHOW, MOVEABLEWITHINPARENT | INSERTABLE, DISP_LIST,
                              MAIN_MENU_PHONEBOOK_TEXT,MAIN_MENU_PHONEBOOK_ICON));

    ADD_APPLICATION_MENUITEM((MENU_ID_PB_INPUT_OPTION_INPUT, MENU_ID_PB_INPUT_OPTION, 3,
                              MENU_ID_PB_INPUT_OPTION_INPUT_TOSIM1,
                              MENU_ID_PB_INPUT_OPTION_INPUT_TOSIM2,
                              MENU_ID_PB_INPUT_OPTION_INPUT_TOPHONE,
                              SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_PB_BACKUP_INPUT_OPTION_INPUT, IMG_GLOBAL_OPTIONS));
                              
    ADD_APPLICATION_MENUITEM((MENU_ID_PB_INPUT_OPTION_INPUT_TOSIM1, MENU_ID_PB_INPUT_OPTION_INPUT, 0,
                              SHOW, MOVEABLEACROSSPARENT, DISP_LIST, STR_PB_BACKUP_INPUT_SIM1, 0));

    ADD_APPLICATION_MENUITEM((MENU_ID_PB_INPUT_OPTION_INPUT_TOSIM2, MENU_ID_PB_INPUT_OPTION_INPUT, 0,
                              SHOW, MOVEABLEACROSSPARENT, DISP_LIST, STR_PB_BACKUP_INPUT_SIM2, 0));

    ADD_APPLICATION_MENUITEM((MENU_ID_PB_INPUT_OPTION_INPUT_TOPHONE, MENU_ID_PB_INPUT_OPTION_INPUT, 0,
                              SHOW, MOVEABLEACROSSPARENT, DISP_LIST, STR_PB_BACKUP_INPUT_PHONE, 0));                              
                              
    ADD_APPLICATION_MENUITEM((MENU_ID_PB_INPUT_OPTION_RENAME, MENU_ID_PB_INPUT_OPTION, 0,
                              SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_PB_BACKUP_INPUT_OPTION_RENAME, IMG_GLOBAL_OPTIONS));

    ADD_APPLICATION_MENUITEM((MENU_ID_PB_INPUT_OPTION_DELETE, MENU_ID_PB_INPUT_OPTION, 0,
                              SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_PB_BACKUP_INPUT_OPTION_DELETE, IMG_GLOBAL_OPTIONS));

     ADD_APPLICATION_MENUITEM((MENU_ID_PB_INPUT_OPTION_DELETEALL, MENU_ID_PB_INPUT_OPTION, 0,
                              SHOW, MOVEABLEWITHINPARENT, DISP_LIST, STR_PB_BACKUP_INPUT_OPTION_DELALL, IMG_GLOBAL_OPTIONS));

    ADD_APPLICATION_STRING2(STR_PB_BACKUP_INPUT_OPTION_INPUT ,"input"	 ,"Menu item string for Delete All->SIM");
    ADD_APPLICATION_STRING2(STR_PB_BACKUP_INPUT_OPTION_RENAME ,"rename"	 ,"Menu item string for Delete All->SIM");
    ADD_APPLICATION_STRING2(STR_PB_BACKUP_INPUT_OPTION_DELETE ,"delete"	 ,"Menu item string for Delete All->SIM");
    ADD_APPLICATION_STRING2(STR_PB_BACKUP_INPUT_OPTION_DELALL ,"delete all"	 ,"Menu item string for Delete All->SIM");
    ADD_APPLICATION_STRING2(STR_PB_BACKUP_INPUT_FIRST ,"main priority"	 ,"Menu item string for Delete All->SIM");
    ADD_APPLICATION_STRING2(STR_PB_BACKUP_INPUT_SECOND ,"second priority"	 ,"Menu item string for Delete All->SIM");    
    ADD_APPLICATION_STRING2(STR_PB_BACKUP_INPUT_SIM1 ,"To SIM1","Menu item string for Delete All->SIM");
    ADD_APPLICATION_STRING2(STR_PB_BACKUP_INPUT_SIM2 ,"To SIM2","Menu item string for Delete All->SIM");
    ADD_APPLICATION_STRING2(STR_PB_BACKUP_INPUT_PHONE ,"To phone","Menu item string for Delete All->SIM");   

    ADD_APPLICATION_STRING2(STR_PB_BACKUP_INPUT ,"Phonebook input"	 ,"Menu item string for Delete All->SIM");
//end
#endif

#ifdef __PHONEBOOK_OUTPUT_INPUT__
#ifdef __MMI_DUAL_SIM_MASTER__
	ADD_APPLICATION_MENUITEM((MITEM104_PBOOK_OUTPUT,MAIN_MENU_PHONEBOOK_MENUID,4,
    			MITEM_PBOOK_BACKUP_SIM1TOCARD,
    			MITEM_PBOOK_BACKUP_SIM2TOCARD,
    			MITEM_PBOOK_BACKUP_PHONETOCARD,
    			MITEM_PBOOK_BACKUP_ALLTOCARD,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_PB_BACKUP_OUTPUT,IMG_PHB_COPY_ALL));
#else
//#else 部分需要完善
	ADD_APPLICATION_MENUITEM((MITEM104_PBOOK_OUTPUT,MAIN_MENU_PHONEBOOK_MENUID,2,  
		MITEM_PBOOK_COPY_ALL_SIM,
		MITEM_PBOOK_COPY_ALL_PHONE,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_PB_BACKUP_OUTPUT,IMG_PHB_COPY_ALL));
#endif

    ADD_APPLICATION_MENUITEM((MITEM_PBOOK_BACKUP_SIM1TOCARD, MITEM104_PBOOK_OUTPUT, 0, SHOW, MOVEABLEWITHINPARENT,
                              DISP_LIST, STR_PB_BACKUP_OUTPUT_SIM1TOCARD, IMG_ID_PHB_NO_IMAGE));
    ADD_APPLICATION_MENUITEM((MITEM_PBOOK_BACKUP_SIM2TOCARD, MITEM104_PBOOK_OUTPUT, 0, SHOW, MOVEABLEWITHINPARENT,
                              DISP_LIST, STR_PB_BACKUP_OUTPUT_SIM2TOCARD, IMG_ID_PHB_NO_IMAGE));
    ADD_APPLICATION_MENUITEM((MITEM_PBOOK_BACKUP_PHONETOCARD, MITEM104_PBOOK_OUTPUT, 0, SHOW, MOVEABLEWITHINPARENT,
                              DISP_LIST, STR_PB_BACKUP_OUTPUT_PHONETOCARD, IMG_ID_PHB_NO_IMAGE));
    ADD_APPLICATION_MENUITEM((MITEM_PBOOK_BACKUP_ALLTOCARD, MITEM104_PBOOK_OUTPUT, 0, SHOW, MOVEABLEWITHINPARENT,
                              DISP_LIST, STR_PB_BACKUP_OUTPUT_ALLTOCARD, IMG_ID_PHB_NO_IMAGE));

	ADD_APPLICATION_STRING2(STR_PB_BACKUP_OUTPUT ,"Phonebook output"	 ,"Menu item string for Delete All->SIM");
	ADD_APPLICATION_STRING2(STR_PB_BACKUP_OUTPUT_SIM1TOCARD ,"From SIM1 to card"	 ,"Menu item string for Delete All->SIM");
	ADD_APPLICATION_STRING2(STR_PB_BACKUP_OUTPUT_SIM2TOCARD ,"From SIM2 to card"	 ,"Menu item string for Delete All->SIM");
	ADD_APPLICATION_STRING2(STR_PB_BACKUP_OUTPUT_PHONETOCARD ,"From Phone to card"	 ,"Menu item string for Delete All->SIM");
	ADD_APPLICATION_STRING2(STR_PB_BACKUP_OUTPUT_ALLTOCARD ,"Output all"	 ,"Menu item string for Delete All->SIM");
	ADD_APPLICATION_STRING2(STR_PB_IS_OUTPUT ,"Output?"	 ,"Menu item string for Delete All->SIM");
	ADD_APPLICATION_STRING2(STR_PB_OUTPUT_NAME ,"Output name:"	 ,"Menu item string for Delete All->SIM");
#endif
//end

#ifdef __MMI_DUAL_SIM_MASTER__
	ADD_APPLICATION_MENUITEM((MITEM_PBOOK_COPY_ALL_SIM,MITEM104_PBOOK_COPY_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STRING_MTPNP_PHB_COPYALL_SIM1TOPHONE,IMG_ID_MTPNP_PHB_COPYALL_FROM_SIM1TOPHONE));
	ADD_APPLICATION_MENUITEM((MITEM_PBOOK_COPY_ALL_PHONE,MITEM104_PBOOK_COPY_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STRING_MTPNP_PHB_COPYALL_PHONETOSIM1,IMG_ID_MTPNP_PHB_COPYALL_FROM_PHONETOSIM1));
#else /* __MMI_DUAL_SIM_MASTER__ */
	ADD_APPLICATION_MENUITEM((MITEM_PBOOK_COPY_ALL_SIM,MITEM104_PBOOK_COPY_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_COPY_ALL_SIM,IMG_STORAGE_SIM));
	ADD_APPLICATION_MENUITEM((MITEM_PBOOK_COPY_ALL_PHONE,MITEM104_PBOOK_COPY_ALL,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_COPY_ALL_PHONE,IMG_STORAGE_HANDSET));
#endif /* __MMI_DUAL_SIM_MASTER__ */

	ADD_APPLICATION_STRING2(STR_MITEM104 ,"Copy All"						,"Menu item string for Copy All");
	ADD_APPLICATION_STRING2(STR_COPY_ALL_SIM ,"From SIM"	 ,"Menu item string for Copy All->SIM");
	ADD_APPLICATION_STRING2(STR_COPY_ALL_PHONE ,"From Phone" ,"Menu item string for Copy All->Phone");
	ADD_APPLICATION_STRING2(STR_DELETE_ALL_SIM ,"From SIM"	 ,"Menu item string for Delete All->SIM");
	ADD_APPLICATION_STRING2(STR_DELETE_ALL_PHONE ,"From Phone" ,"Menu item string for Delete All->Phone");
	ADD_APPLICATION_STRING2(STR_COPY_ALL_SIM_QUERY ,"From SIM"	 ,"Menu item string for Copy All->SIM");
	ADD_APPLICATION_STRING2(STR_COPY_ALL_PHONE_QUERY ,"From Phone" ,"Menu item string for Copy All->Phone");
	ADD_APPLICATION_STRING2(STR_ID_PHB_DELETE_ALL_ONE_BY_ONE ,"One By One" ,"Menu item string for Delete All->Phone");
	ADD_APPLICATION_STRING2(STR_SCR_COPY_ALL_MENU_CAPTION, "Copy All", "Title string for Copy All menu screen");
	//ADD_APPLICATION_STRING2(STR_COPY_ALL_ABORT, "Abort", "Copy All abort");
	ADD_APPLICATION_IMAGE2(IMG_COPY_ALL_ABORT, CUST_IMG_BASE_PATH"\\\\NoImage.bmp", "Copy all abort image");
	ADD_APPLICATION_STRING2(STR_COPY_ALL_ABORTING, "Aborting..", "Aborting Copy all");
	ADD_APPLICATION_IMAGE2(IMG_COPY_ALL_ABORTING,CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\Progress\\\\PROGRESS"__MMI_RES_TYPE_POPUP_SCREEN__,"Aborting Copy all image");
}
#endif /* defined(__MMI_PHB_MULTI_OPERATION__) */

void PopulateExtraNumberRes(void)
{
	/* Populate Special Number Resource, including Owner Number, Service Dial Number, and SOS number */
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EXTRA_NUMBER,MAIN_MENU_PHONEBOOK_MENUID,
	#ifdef __MMI_DUAL_SIM_MASTER__
		6,
	#else /*__MMI_DUAL_SIM_MASTER__*/
		3,
	#endif /*__MMI_DUAL_SIM_MASTER__*/
		MITEM105_PBOOK_OWNER_NUMBER,
	#ifdef __MMI_DUAL_SIM_MASTER__
		MENU_MTPNP_CARD2_OWNER_NUMBER,
	#endif /*__MMI_DUAL_SIM_MASTER__*/
		MENU_PHONEBOOK_SERVICENUMBER,
	#ifdef __MMI_DUAL_SIM_MASTER__
		MENU_MTPNP_CARD2_SDL_NUMBER,
	#endif /*__MMI_DUAL_SIM_MASTER__*/       
		MITEM116_PBOOK_SOS_NUMBER,
	#ifdef __MMI_DUAL_SIM_MASTER__
		MENU_MTPNP_CARD2_SOS_NUMBER,
	#endif /*__MMI_DUAL_SIM_MASTER__*/		
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_EXTRA_NUMBER,IMG_PHB_OWNER_NUMBER));

	ADD_APPLICATION_STRING2(STR_ID_PHB_EXTRA_NUMBER ,"Special Number"	,"Menu item string for Special Number");

	/*Populate Owner Number Resource*/
	ADD_APPLICATION_MENUITEM((MITEM105_PBOOK_OWNER_NUMBER,MENU_ID_PHB_EXTRA_NUMBER,0,
		SHOW, SHORTCUTABLE|MOVEABLEWITHINPARENT, DISP_LIST,
	#ifdef __MMI_DUAL_SIM_MASTER__
		STRING_MTPNP_SIM1_OWNER_NUMBER,
	#else /* __MMI_DUAL_SIM_MASTER__ */
		STR_MITEM105,
	#endif /*__MMI_DUAL_SIM_MASTER__*/
		IMG_PHB_OWNER_NUMBER));

	ADD_APPLICATION_MENUITEM((MITEM105_OWNER_NUMBER_OPTIONS,0,2,
		MITEM1052_OWNER_NUMBER_EDIT,
		MITEM1051_OWNER_NUMBER_ERASE,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));
	ADD_APPLICATION_MENUITEM((MITEM1051_OWNER_NUMBER_ERASE,MITEM105_OWNER_NUMBER_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ERASE,IMG_MITEM1051));
	ADD_APPLICATION_MENUITEM((MITEM1052_OWNER_NUMBER_EDIT,MITEM105_OWNER_NUMBER_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_EDIT,IMG_MITEM1052));

	ADD_APPLICATION_STRING2(STR_MITEM105 ,"Owner Number"						,"Menu item string for Owner Number");
	//ADD_APPLICATION_STRING2(STR_MITEM1051 ,"Erase"						,"Menu item string for Owner Number Options->Erase");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1051 ,CUST_IMG_BASE_PATH"\\\\NoImage.bmp","Menu item image for Owner Number Options->Erase");
	//ADD_APPLICATION_STRING2(STR_MITEM1052 ,"Edit"						,"Menu item string for Owner Number Options->Edit");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1052 ,CUST_IMG_BASE_PATH"\\\\NoImage.bmp","Menu item image for Owner Number Options->Edit");
	//ADD_APPLICATION_STRING2(STR_SCR_OWNER_NUMBER_EDIT_CAPTION, "Edit", "Title screen for owner number edit screen");
	//ADD_APPLICATION_STRING2(STR_SCR_OWNER_NUMBERS_CAPTION ,"Owner Number"						,"Title string for Owner Numbers List screen");
	ADD_APPLICATION_STRING2(STR_NO_OWNER_NUMBER_MESSAGE, "Owner Number List Empty!", "No owner numbers message");
	//ADD_APPLICATION_STRING2(STR_SCR_OWNER_NUMBER_OPTIONS_CAPTION, "Owner Num. Option", "Title string for Owner Number Options screen");
	ADD_APPLICATION_STRING2(STR_OWNER_NAME_CAPTION, "Owner Name", "Owner Name caption");
	ADD_APPLICATION_STRING2(STR_ERASE, "Erase", "Owner number erase");
	ADD_APPLICATION_STRING2(STR_ERASE_QUERY, "Erase?", "Owner number erase query");
	ADD_APPLICATION_STRING2(STR_ID_PHB_ERASED, "Erased", "Owner number erased");

	/* Populate Service Dial Number Resource */
	ADD_APPLICATION_MENUITEM((MENU_PHONEBOOK_SERVICENUMBER, MENU_ID_PHB_EXTRA_NUMBER, 0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST, 
	#ifdef __MMI_DUAL_SIM_MASTER__		
		STRING_MTPNP_SIM1_SDL_NUMBER,
	#else /* __MMI_DUAL_SIM_MASTER__ */
		STR_SDL_MAIN_MENU,
	#endif /*__MMI_DUAL_SIM_MASTER__*/		
		IMG_PHB_SDN));

	ADD_APPLICATION_STRING2(STR_CALL_SDL_CAPTION	,"Service Dial Number"			,"SDL DIAL LIST CAPTION ");
	ADD_APPLICATION_STRING2(STR_SDL_MAIN_MENU		,"Service Dial Number"			,"SDL NO LIST CAPTION ");
	ADD_APPLICATION_STRING2(STR_SDL_NO_LIST_TEXT	,"Not Supported!"	,"SDL NO LIST TEXT ");
	//ADD_APPLICATION_STRING2(STR_SDL_CALL_LSK		,"Dial"							,"SDL VIEW OPTION CALL ");
	ADD_APPLICATION_IMAGE2(IMG_SDL_CALL_LSK			,CUST_IMG_BASE_PATH"\\\\NoImage.bmp", "SDL NO LIST SCREEN CAPTION ");

	/* Populate Emergency (SOS) Number Resource */
	ADD_APPLICATION_MENUITEM((MITEM116_PBOOK_SOS_NUMBER, MENU_ID_PHB_EXTRA_NUMBER, 0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,
	#ifdef __MMI_DUAL_SIM_MASTER__	
              STRING_MTPNP_SIM1_SOS_NUMBER,
	#else /* __MMI_DUAL_SIM_MASTER__ */
		STR_SOS_MENU_ITEM, 
	#endif /*__MMI_DUAL_SIM_MASTER__*/			
		IMG_PHB_SOS_NUMBER));

	ADD_APPLICATION_STRING2(STR_SOS_MENU_ITEM,"SOS Number","STR_SOS_MENU_ITEM");
	ADD_APPLICATION_STRING2(STR_DISPLAY_SOS_CAPTION,"SOS Number","STR_DISPLAY_SOS_CAPTION");
	//ADD_APPLICATION_STRING2(STR_SOS_OPTIONS_EDIT,"Edit","STR_SOS_OPTIONS_EDIT");
	//ADD_APPLICATION_STRING2(STR_SOS_ENTER_NUMBER, "Edit","STR_SOS_ENTER_NUMBER");
	//ADD_APPLICATION_STRING2(STR_CONFIRM_SOS_CALL_TEXT,"Dial","STR_CONFIRM_SOS_CALL_TEXT");
	//ADD_APPLICATION_STRING2(STR_NUMBER_EMPTY,"<Empty>","STR_SOSLIST_EMPTY");
	ADD_APPLICATION_STRING2(STR_SOSLIST_NVRAM,"in Phone","STR_SOSLIST_NVRAM");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SOSLIST_INSIM,"in SIM","STR_SOSLIST_INCARD");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SOSLIST_DIAL_QUERY,"call?","STR_ID_PHB_SOSLIST_DIAL_QUERY");
}

void PopulatePbookSettingsData(void)
{
	ADD_APPLICATION_MENUITEM((MITEM110_PBOOK_SETTINGS,MAIN_MENU_PHONEBOOK_MENUID, MMI_PHB_SETTING_ENUM_TOTAL,
		MITEM1101_PBOOK_MEMORY_STATUS,
		MITEM1102_PBOOK_STORAGE_LOCATION,
		MITEM1103_PBOOK_VIEW_FIELDS,
#if defined(__MMI_PHB_NAME_LIST_FILTER__)
        MENU_ID_PHB_NAME_LIST_FILTER,	
#endif
#if defined(__MMI_VCARD__)
		MENU_ID_PHB_VCARD_MYCARD,
#if defined(__MMI_VCARD_V30__)
		MENU_ID_PHB_VCARD_VERSION,
#endif /* defined(__MMI_VCARD_V30__) */
#endif
#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
		MENU_ID_PHB_SPEAK_NAME,
#endif
		SHOW, INSERTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM110,IMG_PHB_SETTINGS));

	ADD_APPLICATION_MENUITEM((MITEM110_PBOOK_SETTINGS_NO_SIM,MAIN_MENU_PHONEBOOK_NO_SIM_MENUID, MMI_PHB_SETTING_NO_SIM_ENUM_TOTAL,
		MITEM1101_PBOOK_MEMORY_STATUS,
		MITEM1103_PBOOK_VIEW_FIELDS,
#if defined(__MMI_VCARD__)
		MENU_ID_PHB_VCARD_MYCARD,
#if defined(__MMI_VCARD_V30__)
		MENU_ID_PHB_VCARD_VERSION,
#endif /* defined(__MMI_VCARD_V30__) */
#endif /* defined(__MMI_VCARD__) */
#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
		MENU_ID_PHB_SPEAK_NAME,
#endif
		SHOW, INSERTABLE|MOVEABLEWITHINPARENT, DISP_LIST,STR_MITEM110,IMG_PHB_SETTINGS));

	ADD_APPLICATION_MENUITEM((MITEM1101_PBOOK_MEMORY_STATUS, MITEM110_PBOOK_SETTINGS,0,
		SHOW, SHORTCUTABLE|MOVEABLEACROSSPARENT, DISP_LIST,STR_GLOBAL_MEMORY_STATUS,IMG_MITEM1101));
	
#ifdef __MMI_DUAL_SIM_MASTER__
	ADD_APPLICATION_MENUITEM((MITEM1102_PBOOK_STORAGE_LOCATION,MITEM110_PBOOK_SETTINGS, 3,
		MITEM_STORAGE_LOCATION_SIM,
		MENU_MTPNP_PB_PRE_STORAGE_SIM2,
		MITEM_STORAGE_LOCATION_PHONE,
		SHOW, SHORTCUTABLE|MOVEABLEACROSSPARENT, DISP_LIST,STR_GLOBAL_PREFERRED_STORAGE,IMG_MITEM1102));
#else /* __MMI_DUAL_SIM_MASTER__ */
	ADD_APPLICATION_MENUITEM((MITEM1102_PBOOK_STORAGE_LOCATION,MITEM110_PBOOK_SETTINGS, 2,
		MITEM_STORAGE_LOCATION_SIM,
		MITEM_STORAGE_LOCATION_PHONE,
		SHOW, SHORTCUTABLE|MOVEABLEACROSSPARENT, DISP_LIST,STR_GLOBAL_PREFERRED_STORAGE,IMG_MITEM1102));
#endif /* __MMI_DUAL_SIM_MASTER__ */

	ADD_APPLICATION_MENUITEM((MITEM1103_PBOOK_VIEW_FIELDS,MITEM110_PBOOK_SETTINGS,0,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_SETTING_VIEW_FIELDS,IMG_MITEM1103));

	ADD_APPLICATION_MENUITEM((MITEM_STORAGE_LOCATION_SIM,MITEM1102_PBOOK_STORAGE_LOCATION,0,
		SHOW, NONMOVEABLE, DISP_LIST,
        #ifdef __MMI_DUAL_SIM_MASTER__
		STRING_MTPNP_SIM1_MEMORY_STATUS,
        #else /* __MMI_DUAL_SIM_MASTER__ */
		STR_STORAGE_SIM,
        #endif /* __MMI_DUAL_SIM_MASTER__ */
		IMG_STORAGE_SIM));
	ADD_APPLICATION_MENUITEM((MITEM_STORAGE_LOCATION_PHONE,MITEM1102_PBOOK_STORAGE_LOCATION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_STORAGE_PHONE,IMG_STORAGE_HANDSET));

#if defined(__MMI_PHB_NAME_LIST_FILTER__)
#ifdef __MMI_DUAL_SIM_MASTER__
    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_NAME_LIST_FILTER,MITEM110_PBOOK_SETTINGS, 4,
        MENU_ID_PHB_NLF_SIM,
        MENU_MTPNP_PHB_NLF_SIM2,
        MENU_ID_PHB_NLF_PHONE,
        MENU_ID_PHB_NLF_BOTH,
        SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_NLF,IMG_ID_PHB_NLF));
#else /* __MMI_DUAL_SIM_MASTER__ */
    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_NAME_LIST_FILTER,MITEM110_PBOOK_SETTINGS, 3,
        MENU_ID_PHB_NLF_SIM,
        MENU_ID_PHB_NLF_PHONE,
        MENU_ID_PHB_NLF_BOTH,
        SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_NLF,IMG_ID_PHB_NLF));
#endif /* __MMI_DUAL_SIM_MASTER__ */
    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_NLF_SIM,MENU_ID_PHB_NAME_LIST_FILTER,0,
        SHOW, NONMOVEABLE, DISP_LIST,
    #ifdef __MMI_DUAL_SIM_MASTER__
        STRING_MTPNP_NLF_SIM1,
    #else /* __MMI_DUAL_SIM_MASTER__ */
        STR_ID_PHB_NLF_SIM,
    #endif /* __MMI_DUAL_SIM_MASTER__ */
        0));
    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_NLF_PHONE,MENU_ID_PHB_NAME_LIST_FILTER,0,
        SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_NLF_PHONE,0));
    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_NLF_BOTH,MENU_ID_PHB_NAME_LIST_FILTER,0,
        SHOW, NONMOVEABLE, DISP_LIST,
    #ifdef __MMI_DUAL_SIM_MASTER__
        STRING_MTPNP_NLF_ALL,
    #else
        STR_ID_PHB_NLF_BOTH,
    #endif
        0));
#endif /* defined(__MMI_PHB_NAME_LIST_FILTER__) */

#if defined(__MMI_VCARD__) && defined(__MMI_VCARD_V30__)		
    /* vCard Version 2.1 or 3.0 */
    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_VERSION,MITEM110_PBOOK_SETTINGS,2,
        MENU_ID_PHB_VCARD_VERSION_21,
        MENU_ID_PHB_VCARD_VERSION_30,
        SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_VCARD_VERSION, IMG_ID_PHB_NO_IMAGE));  

    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_VERSION_21,MENU_ID_PHB_VCARD_VERSION,0,
        SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_VCARD_VERSION_21,0));
    ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VCARD_VERSION_30,MENU_ID_PHB_VCARD_VERSION,0,
        SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_VCARD_VERSION_30,0));
#endif /* defined(__MMI_VCARD__)  && defined(__MMI_VCARD_V30__) */

#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SPEAK_NAME,MITEM110_PBOOK_SETTINGS,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_SPEAK_NAME,0));
#endif

	ADD_APPLICATION_STRING2(STR_MITEM110	,"Settings"	,"Menu item string for PhoneBook Setting option");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1101	,CUST_IMG_BASE_PATH"\\\\NoImage.bmp"		,"Menu item image for PhoneBook Settings->Memory status");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1102    ,CUST_IMG_BASE_PATH"\\\\NoImage.bmp"		,"Menu item image for PhoneBook Settings->Preferred storage");
	ADD_APPLICATION_IMAGE2(IMG_MITEM1103	,CUST_IMG_BASE_PATH"\\\\NoImage.bmp"		,"Menu item image for PhoneBook Settings->Phonebook fields");
	ADD_APPLICATION_STRING2(STR_SCR_PBSETTINGS_LIST_CAPTION	,"Settings"	,"Title string for Phonebook settings screen");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SETTING_VIEW_FIELDS	,"Fields"		,"Title string for View Fields screen");
	ADD_APPLICATION_STRING2(STR_STORAGE_SIM, "SIM", "Menu item string for Storage Location SIM");
	ADD_APPLICATION_STRING2(STR_STORAGE_PHONE, "Phone", "Menu item string for Storage Location Phone");
	ADD_APPLICATION_STRING2(STR_SCR_MEMORY_USAGE_CAPTION, "Memory Status", "Title string for Memory Status screen");
	ADD_APPLICATION_STRING2(STR_HOME_NUMBER			,"Home Number"		, "String for view field Home Number");
	ADD_APPLICATION_STRING2(STR_COMPNAY_NAME		,"Company Name"		, "String for view field Company Name");
	ADD_APPLICATION_STRING2(STR_EMAIL_ADRESS		,"Email Address"	, "String for view field Email Address");
	ADD_APPLICATION_STRING2(STR_OFFICE_NUMBER		,"Office Number"	, "String for view field Office Number");
	ADD_APPLICATION_STRING2(STR_FAX_NUMBER			,"Fax Number"		, "String for view field Fax Number");
	ADD_APPLICATION_STRING2(STR_ASSOCIATE_PICTURE	,"Associate Picture", "String for view field Associate Picture");
	ADD_APPLICATION_STRING2(STR_ASSOCIATE_SOUND		,"Associate Sound"	, "String for view field Associate Sound");
	ADD_APPLICATION_STRING2(STR_ASSOCIATE_ALERT     ,"Associate Alert"	, "String for view field Associate Alert");
	ADD_APPLICATION_STRING2(STR_ASSOCIATE_LED       ,"Associate LED"	, "String for view field Associate LED");
    ADD_APPLICATION_STRING2(STR_CALLER_GROUP		,"Caller Group"		, "String for view field Caller Group");
#if defined(__MMI_PHB_BIRTHDAY_FIELD__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_BIRTHDAY		,"Birthday"		, "String for view field birthday");
#endif

#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
	ADD_APPLICATION_STRING2(STR_ID_PHB_SPEAK_NAME		,"Human Voice Prompt"		, "Phonebook setting menu item");
#endif

	ADD_APPLICATION_STRING2(STR_MEMORY_STATUS_SIM, "SIM", "SIM on Memory status screen");
	ADD_APPLICATION_STRING2(STR_MEMORY_STATUS_PHONE, "Phone", "Phone on Memory status screen");

#if defined(__MMI_PHB_NAME_LIST_FILTER__)
    ADD_APPLICATION_STRING2(STR_ID_PHB_NLF ,"Name List Filter" ,"Menu item string for PhoneBook Setting->Name list filter");
    ADD_APPLICATION_IMAGE2(IMG_ID_PHB_NLF  ,CUST_IMG_BASE_PATH"\\\\NoImage.bmp"    ,"Menu item image for PhoneBook Settings->Name list filter");
    ADD_APPLICATION_STRING2(STR_ID_PHB_NLF_SIM ,"SIM Only" ,"Menu item string for List Filter SIM");
    ADD_APPLICATION_STRING2(STR_ID_PHB_NLF_PHONE   ,"Phone Only"   ,"Menu item string for List Filter Phone");	
    ADD_APPLICATION_STRING2(STR_ID_PHB_NLF_BOTH    ,"Both" ,"Menu item string for List Filter Both");	
#endif 	/* defined(__MMI_PHB_NAME_LIST_FILTER__) */

#if defined(__MMI_VCARD__) && defined(__MMI_VCARD_V30__)		
    /* vCard Version 2.1 or 3.0 */
    ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD_VERSION ,"Vcard Version" ,"Menu item string for vcard version");
    ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD_VERSION_21 ,"Vcard Version 2.1" ,"Menu item string for vcard verson 21");
    ADD_APPLICATION_STRING2(STR_ID_PHB_VCARD_VERSION_30 ,"Vcard Version 3.0"   ,"Menu item string for vcard version 30");	
#endif 	/* defined(__MMI_VCARD__) && defined(__MMI_VCARD_V30__) */

#if defined(__MMI_PHB_INFO_FIELD__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_EDIT_DETAIL		,"Edit Detail"		, "String for view option- edit detail");
	ADD_APPLICATION_STRING2(STR_ID_PHB_TITLE		,"Title"		, "String for view field title");
	ADD_APPLICATION_STRING2(STR_ID_PHB_URL  ,"Url"		, "String for view field url");
	ADD_APPLICATION_STRING2(STR_ID_PHB_ADDRESS		,"Postal Address"		, "String for view field postal address");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOTE		,"Note"		, "String for view field note");
	//ADD_APPLICATION_STRING2(STR_ID_PHB_MORE		,"More"		, "String for view extra field");
#endif

#if defined(__MMI_PHB_USIM_FIELD__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_ANR_1  , "Additional Number 1"		, "String for view field ANR 1");
	ADD_APPLICATION_STRING2(STR_ID_PHB_ANR_2  , "Additional Number 2"		, "String for view field ANR 2");
	ADD_APPLICATION_STRING2(STR_ID_PHB_ANR_3  , "Additional Number 3"		, "String for view field ANR 3");
	ADD_APPLICATION_STRING2(STR_ID_PHB_GAS_1, "SIM Group 1"	, "SIM Caller Group 1");
	ADD_APPLICATION_STRING2(STR_ID_PHB_GAS_2, "SIM Group 2"	, "SIM Caller Group 2");
	ADD_APPLICATION_STRING2(STR_ID_PHB_GAS_3, "SIM Group 3"	, "SIM Caller Group 3");
	ADD_APPLICATION_STRING2(STR_ID_PHB_GAS_4, "SIM Group 4"	, "SIM Caller Group 4");
	ADD_APPLICATION_STRING2(STR_ID_PHB_GAS_5, "SIM Group 5"	, "SIM Caller Group 5");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SNE  , "Nick Name"		, "String for view field Nick Name");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_SAVED_ANR_FULL  , "Not Saved, Additional Number Full!"		, "Additional Number Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_MOVED_ANR_FULL  , "Not Moved, Additional Number Full!"		, "Additional Number Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_COPIED_ANR_FULL  , "Not Copied, Additional Number Full!"		, "Additional Number Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_DUPLICATED_ANR_FULL  , "Not Duplicated, Additional Number Full!"		, "Additional Number Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_SAVED_EMAIL_FULL  , "Not Saved, Email Full!"		, "Email Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_MOVED_EMAIL_FULL  , "Not Moved, Email Full!"		, "Email Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_COPIED_EMAIL_FULL  , "Not Copied, Email Full!"		, "Email Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_DUPLICATED_EMAIL_FULL  , "Not Duplicated, Email Full!"		, "Email Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_SAVED_SNE_FULL  , "Not Saved, Nick Name Full!"		, "Nick Name Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_MOVED_SNE_FULL  , "Not Moved, Nick Name Full!"		, "Nick Name Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_COPIED_SNE_FULL  , "Not Copied, Nick Name Full!"		, "Nick Name Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_NOT_DUPLICATED_SNE_FULL  , "Not Duplicated, Nick Name Full!"	, "Nick Name Full!");
	ADD_APPLICATION_STRING2(STR_ID_PHB_PROCESSING_USIM  , "Processing SIM"	, "Processing SIM");
#endif

#if defined(__MMI_PHB_IMPS_FIELD__) || defined(__MMI_PHB_POC_FIELD__) || defined(__MMI_VOIP__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_EDIT_SERVICE_FIELD  , "Edit Service Field"		, "String for view field IMPS ID");
#endif
#if defined(__MMI_PHB_IMPS_FIELD__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_IMPS_ID  , "User ID"		, "String for view field IMPS ID");
#endif

#if defined(__MMI_VOIP__)
	ADD_APPLICATION_STRING2(STR_ID_PHB_VOIP_ID  , "VOIP URI"		, "String for view field IMPS ID");
#endif
}


void PopulateInlineEditRes(void)
{
	//ADD_APPLICATION_STRING2(STR_EDIT_LSK,"Edit","LSK label for Inline edit screen");
	//ADD_APPLICATION_STRING2(STR_DONE_RSK,"Done","RSK label for Inline edit screen");
	ADD_APPLICATION_STRING2(STR_VIEW_LSK,"View","LSK label for Inline edit screen");
	ADD_APPLICATION_IMAGE2(IMG_EDIT_LSK,CUST_IMG_BASE_PATH"\\\\NoImage.bmp","LSK image for Inline edit screen");
	ADD_APPLICATION_IMAGE2(IMG_DONE_RSK,CUST_IMG_BASE_PATH"\\\\NoImage.bmp","RSK image for Inline edit screen");
	ADD_APPLICATION_IMAGE2(IMG_VIEW_LSK,CUST_IMG_BASE_PATH"\\\\NoImage.bmp","LSK image for Inline edit screen");

	/*Associate Video Menu*/
#if defined(__MMI_INCOMING_CALL_VIDEO__)
	/*Option for video in file*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_OPTION,0,4,
		MENU_ID_PHB_VIDEO_FILE_VIEW,
		MENU_ID_PHB_VIDEO_FILE_SELECT,
		MENU_ID_PHB_VIDEO_FILE_DELETE,
		MENU_ID_PHB_VIDEO_FILE_SETTING,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_ASSOCIATE_VIDEO, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_VIEW,MENU_ID_PHB_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_WATCH_VIDEO, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_SELECT,MENU_ID_PHB_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_SELECT_FILE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_DELETE,MENU_ID_PHB_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_DELETE_REF, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_FILE_SETTING,MENU_ID_PHB_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_VIDEO_AUDIO_ONOFF, 0));

	/*Option for default video*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_DEFAULT_OPTION,0,2,
		MENU_ID_PHB_VIDEO_DEFAULT_VIEW,
		MENU_ID_PHB_VIDEO_DEFAULT_SETTING,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_ASSOCIATE_VIDEO, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_DEFAULT_VIEW,MENU_ID_PHB_VIDEO_DEFAULT_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_WATCH_VIDEO, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_VIDEO_DEFAULT_SETTING,MENU_ID_PHB_VIDEO_DEFAULT_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_VIDEO_AUDIO_ONOFF,0));


	ADD_APPLICATION_STRING2(STR_ID_PHB_ASSOCIATE_VIDEO		,"Associate Video"		, "String for view field Associate Video");
	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_AUDIO_ONOFF		,"Video Audio"		, "String for view field Video Audio");
	ADD_APPLICATION_STRING2(STR_ID_PHB_WATCH_VIDEO		,"Watch Video"		, "String for watch video");
	ADD_APPLICATION_STRING2(STR_ID_PHB_CANT_VIEW_VIDEO_IN_CALL		,"Can't  preview video during call"		, "String for watch video");
	ADD_APPLICATION_STRING2(STR_ID_PHB_CANT_SELECT_CALLER_VIDEO_IN_CALL		,"Can't select video during call"		, "String for watch video");

	ADD_APPLICATION_STRING2(STR_ID_PHB_VIDEO_1, "Video 1", "Video Tag 1");

	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_ASSOCIATE_VIDEO	,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\PBView\\\\PV_VIDEO.PBM","Assoicate Video Icon");

	/*Populate Default Video Resource*/
#if defined(MJPG_SUPPORT)
	ADD_APPLICATION_MEDIA(VDO_ID_PHB_MTCALL_1, CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Incoming\\\\video\\\\IC_V01.avi");
#elif defined(MP4_CODEC)
	ADD_APPLICATION_MEDIA(VDO_ID_PHB_MTCALL_1, CUST_IMG_PATH"\\\\MainLCD\\\\Call\\\\Incoming\\\\video\\\\IC_V01.mp4");
#endif

#ifdef __MMI_SWFLASH__
	/*Option for swflash in file*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_FILE_OPTION,0,4,
		MENU_ID_PHB_SWFLASH_FILE_VIEW,
		MENU_ID_PHB_SWFLASH_FILE_SELECT,
		MENU_ID_PHB_SWFLASH_FILE_DELETE,
		MENU_ID_PHB_SWFLASH_FILE_SETTING,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_ASSOCIATE_SWFLASH, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_FILE_VIEW,MENU_ID_PHB_SWFLASH_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_WATCH_SWFLASH, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_FILE_SELECT,MENU_ID_PHB_SWFLASH_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_SELECT_FILE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_FILE_DELETE,MENU_ID_PHB_SWFLASH_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_DELETE_REF, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_FILE_SETTING,MENU_ID_PHB_SWFLASH_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_SWFLASH_AUDIO_ONOFF, 0));

	/*Option for default video*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_DEFAULT_OPTION,0,2,
		MENU_ID_PHB_SWFLASH_DEFAULT_VIEW,
		MENU_ID_PHB_SWFLASH_DEFAULT_SETTING,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_ASSOCIATE_SWFLASH, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_DEFAULT_VIEW,MENU_ID_PHB_SWFLASH_DEFAULT_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_WATCH_SWFLASH, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_SWFLASH_DEFAULT_SETTING,MENU_ID_PHB_SWFLASH_DEFAULT_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_SWFLASH_AUDIO_ONOFF,0));

	ADD_APPLICATION_STRING2(STR_ID_PHB_ASSOCIATE_SWFLASH		,"Associate SWFlash"		, "String for view field Associate Video");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_AUDIO_ONOFF		,"SWFlash Audio"		, "String for view field Video Audio");
	ADD_APPLICATION_STRING2(STR_ID_PHB_WATCH_SWFLASH		,"Watch SWFlash"		, "String for watch video");
	ADD_APPLICATION_STRING2(STR_ID_PHB_CANT_VIEW_SWFLASH_IN_CALL		,"Can't  preview swflash during call"		, "String for watch video");

	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_1, "SWFlash 1", "SWFlash Tag 1");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_2, "SWFlash 2", "SWFlash Tag 2");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_3, "SWFlash 3", "SWFlash Tag 3");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_4, "SWFlash 4", "SWFlash Tag 4");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_5, "SWFlash 5", "SWFlash Tag 5");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_6, "SWFlash 6", "SWFlash Tag 6");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_7, "SWFlash 7", "SWFlash Tag 7");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_8, "SWFlash 8", "SWFlash Tag 8");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_9, "SWFlash 9", "SWFlash Tag 9");
	ADD_APPLICATION_STRING2(STR_ID_PHB_SWFLASH_10, "SWFlash 10", "SWFlash Tag 10");

	ADD_APPLICATION_MEDIA(MFH_ID_PHB_MTCALL_1, CUST_IMG_PATH"\\\\MainLCD\\\\SWFlash\\\\IC_M01.VIS");
#endif /* __MMI_SWFLASH__ */

#if defined(__MMI_AVATAR__)	
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_AVATAR_VIDEO_FILE_OPTION,0,3,
		MENU_ID_PHB_AVATAR_VIDEO_FILE_VIEW,
		MENU_ID_PHB_AVATAR_VIDEO_FILE_SELECT,
		MENU_ID_PHB_AVATAR_VIDEO_FILE_DELETE,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_ASSOCIATE_VIDEO, IMG_ID_PHB_NO_IMAGE));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_AVATAR_VIDEO_FILE_VIEW,MENU_ID_PHB_AVATAR_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_WATCH_VIDEO, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_AVATAR_VIDEO_FILE_SELECT,MENU_ID_PHB_AVATAR_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_AVATAR_SELECT_FILE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_AVATAR_VIDEO_FILE_DELETE,MENU_ID_PHB_AVATAR_VIDEO_FILE_OPTION,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_ID_PHB_FMGR_IMAGE_DELETE_REF, 0));
#endif /* defined(__MMI_AVATAR__)	*/

#endif /* __MMI_INCOMING_CALL_VIDEO__ */

#ifdef __MMI_VOIP__
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EDIT_VOIP_OPTIONS,0,2,
		MENU_ID_PHB_EDIT_VOIP_DONE,
		MENU_ID_PHB_EDIT_VOIP_INPUT_MEHTHOD,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_OPTIONS,IMG_GLOBAL_OPTIONS));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EDIT_VOIP_DONE,MENU_ID_PHB_EDIT_VOIP_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_GLOBAL_DONE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_EDIT_VOIP_INPUT_MEHTHOD,MENU_ID_PHB_EDIT_VOIP_OPTIONS,0,
		SHOW, NONMOVEABLE, DISP_LIST,STR_GLOBAL_INPUT_METHOD, 0));
#endif /* __MMI_VOIP__ */
}


void PopulatePhbExtraMainMenuRes(void)
{
#if defined(__MMI_PHB_CALLER_RES_SETTING__)
	/*Menu Resource*/
#if defined(__MMI_AVATAR__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_PIC,MAIN_MENU_PHONEBOOK_MENUID, 2,
		MENU_ID_PHB_CALLER_PIC_FILE,
		MENU_ID_PHB_CALLER_PIC_AVATAR,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_CALLER_PIC, IMG_ID_PHB_CALLER_PIC));
	
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_PIC_FILE, MENU_ID_PHB_CALLER_PIC,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_CALLER_VIDEO_FROM_FILE, IMG_MITEM1101));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_PIC_AVATAR, MENU_ID_PHB_CALLER_PIC,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_AVATAR_SELECT_FILE, IMG_MITEM1102));
#else
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_PIC,MAIN_MENU_PHONEBOOK_MENUID,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_CALLER_PIC, IMG_ID_PHB_CALLER_PIC));
#endif /* defined(__MMI_SWFLASH__) || defined(__MMI_AVATAR__) */


	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_RING,MAIN_MENU_PHONEBOOK_MENUID,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_CALLER_RING, IMG_ID_PHB_CALLER_RING));

	/*String Resource*/
	ADD_APPLICATION_STRING2(STR_ID_PHB_CALLER_PIC, "Caller Picture", "Personal Incoming Call Setting");
	ADD_APPLICATION_STRING2(STR_ID_PHB_CALLER_RING, "Caller Ring Tone", "Personal Incoming Call Setting");

	/*Image Resource*/
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_CALLER_PIC	,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_MTPIC.PBM","Personal Incoming Call Setting Icon");
	ADD_APPLICATION_IMAGE2(IMG_ID_PHB_CALLER_RING	,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_MTRING.PBM","Personal Incoming Call Setting Icon");

	/*For caller video*/
#if defined(__MMI_INCOMING_CALL_VIDEO__)
#if defined(__MMI_SWFLASH__) || defined(__MMI_AVATAR__)
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_VIDEO,MAIN_MENU_PHONEBOOK_MENUID, 3,
		MENU_ID_PHB_CALLER_VIDEO_FILE,
		MENU_ID_PHB_CALLER_VIDEO_AVATAR,
		MENU_ID_PHB_CALLER_VIDEO_SWFLASH,
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,STR_ID_PHB_CALLER_VIDEO, IMG_ID_PHB_CALLER_VIDEO));
	
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_VIDEO_FILE, MENU_ID_PHB_CALLER_VIDEO,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_CALLER_VIDEO_FROM_FILE, IMG_MITEM1101));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_VIDEO_AVATAR, MENU_ID_PHB_CALLER_VIDEO,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_AVATAR_SELECT_FILE, IMG_MITEM1102));
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_VIDEO_SWFLASH, MENU_ID_PHB_CALLER_VIDEO,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_CALLER_VIDEO_FROM_SWFLASH, IMG_MITEM1103));
	ADD_APPLICATION_STRING2(STR_ID_PHB_CALLER_VIDEO_FROM_FILE, "From File", "Select Caller Video From File");
	ADD_APPLICATION_STRING2(STR_ID_PHB_CALLER_VIDEO_FROM_SWFLASH, "From SWFlash", "Select Caller Video From SWFlash");
#else
	ADD_APPLICATION_MENUITEM((MENU_ID_PHB_CALLER_VIDEO,MAIN_MENU_PHONEBOOK_MENUID,0,
		SHOW, MOVEABLEACROSSPARENT, DISP_LIST,STR_ID_PHB_CALLER_VIDEO, IMG_ID_PHB_CALLER_VIDEO));
#endif /* defined(__MMI_SWFLASH__) || defined(__MMI_AVATAR__) */
		ADD_APPLICATION_STRING2(STR_ID_PHB_CALLER_VIDEO, "Caller Video", "Personal Incoming Call Setting");
			ADD_APPLICATION_IMAGE2(IMG_ID_PHB_CALLER_VIDEO	,CUST_IMG_PATH"\\\\MainLCD\\\\Phonebook\\\\SB_MTVDO.PBM","Personal Incoming Call Setting Icon");
#endif /* __MMI_INCOMING_CALL_VIDEO__ */

#endif	/* __MMI_PHB_CALLER_RES_SETTING__ */
}


#endif


