/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/**
 *	Copyright Notice
 *	?2002 - 2003, Pixtel Communications, Inc., 1489 43rd Ave. W.,
 *	Vancouver, B.C. V6M 4K8 Canada. All Rights Reserved.
 *  (It is illegal to remove this copyright notice from this software or any
 *  portion of it)
 */

/**************************************************************

	FILENAME	: Res_MtkApp.c

  	PURPOSE		: Populate Resource for MtkApp

	REMARKS		: nil

	AUTHOR		: Yogesh

	DATE		: August-15-2003

**************************************************************/

//MTK Add Robin 1001 for saperate MMI feature by project
#include "MMI_features.h" 
//MTK End

#include "MMIDataType.h"
#include "CustomCfg.h"


#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif

#include "FactoryModeResDef.h"

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"




/*********************************
 ** Factory Mode Functions
 **********************************/
 #ifdef __MMI_FACTORY_MODE__ //MTK Add Robin 1001 for saperate MMI feature by project
void populateFactoryModeMenu(void)
{
//Lisen 0720
       U16 FMRootItemCount; 

	ADD_APPLICATION_STRING2 ( STR_ID_FM_ROOT,			"Factory Mode",		"Factory Mode ");

	ADD_APPLICATION_STRING2 ( STR_ID_FM_VERSION,		"Version",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_RESOURCE_BIN,	"Resource BIN",		"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_RESOURCE_LANGPACK,	"LANGPACK",		"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_RESOURCE_CUSTPACK,	"CUSTPACK",		"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_LED,			"LED",				"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_LCD,			"LCD",				"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_LCD_CONTRAST, "LCD Contrast",		"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_KEYPAD,		"Keypad",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_LOUDSPK,		"Loud Spk",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_EACHLOOP,		"Echo Loop",		"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_VIBRATOR,		"Vibrator",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_ADC,			"ADC",				"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_RECEIVER,		"Receiver",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_HEADSET,		"Headset",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_CHARGER,		"Charger",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_RINGTONE,		"Ring Tone",		"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_RTC,			"RTC",				"Factory Mode menu item");
	
	//ADD_APPLICATION_STRING2 ( , "", "Factory Mode ");

	ADD_APPLICATION_STRING2 ( STR_ID_FM_LCD_CONTRAST_MAIN, "Main LCD", "Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_LCD_CONTRAST_SUB, "Sub LCD", "Factory Mode menu item ");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_LCD_AUTO,			"Auto Display",		"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_LCD_R,			"RED",				"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_LCD_G,			"GREEN",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_LCD_B,			"BLUE",				"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_LCD_W,			"WHITE",			"Factory Mode menu item");
//Lisen 05312005	
	ADD_APPLICATION_STRING2 ( STR_ID_FM_LCD_BLACK,			"BLACK",				"Factory Mode menu item");
	
	ADD_APPLICATION_STRING2 ( STR_ID_FM_BBCHIP_VER,	"BB Chip",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_DSPCODE_VER,	"DSP Code",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_DSPATCH_VER,	"DSP Patch",		"Factory Mode menu item");
       // Lisen 0921
	ADD_APPLICATION_STRING2 ( STR_ID_FM_SW_SUMMARY,		"Version Info Summary",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_SW_VER,		"MCU SW",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_HW_VER,		"MS Board",			"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_MELODY_VER,	"Melody",	  		"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_ISN,			"Serial No.",		"Factory Mode menu item");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_BUILD_TIME,			"Build No.",		"Factory Mode menu item");

	ADD_APPLICATION_STRING2 ( STR_ID_FM_RTC_NOTIFY , "RTC SET! Auto power-on later!", "Factory Mode Notification text ");

	ADD_APPLICATION_STRING2 ( STR_ID_FM_AUTO_TEST_ROOT,			"Auto Test",		"Factory Mode ");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_AUTO_TEST_REPORT,			"Report",		"Factory Mode ");
	//ADD_APPLICATION_STRING2 ( STR_ID_FM_AUTO_TEST_SUMMARY,		"Summary",		"Factory Mode ");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_AUTO_TEST_RESULT,			"Test Result",		"Factory Mode ");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_AUTO_TEST_START,			"Start",		"Factory Mode ");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_AUTO_TEST_PASS,			"Pass",		"Factory Mode ");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_AUTO_TEST_FAIL,			       "Fail",		"Factory Mode ");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_AUTO_TEST_RTC,			"RTC",		"Factory Mode ");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_AUTO_TEST_STOP,			"STOP",		"Factory Mode ");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_AUTO_TEST_RETEST, 			"ReTest",	"Factory Mode ");
	ADD_APPLICATION_STRING2 ( STR_ID_FM_AUTO_TEST_EXIT, 			"Exit",	"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTO_TEST_ALLPASSED,  			"All Passed!",	"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTO_TEST_ALLDONE,  			"All Tests Done!",	"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTO_TEST_FAILED,  			"Failed!",	"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTO_TEST_UNFINISHED,  			"Unfinished!",	"Factory Mode ");

	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_LED_R, 			"Red LED flashing",	"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_LED_G, 			"Green LED flashing",	"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_LED_B, 			"Blue LED flashing",	"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_CLAM, 				"Please open/close Clam",	"Factory Mode ");
	//ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_SUBLCM, 			"SubLCM Contrast",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_BACKLIGHT, 		"LCM/Keypad Backlight",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_RECEIVER, 			"Please test Receiver",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_MIC, 			       "Please test MIC",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_SPEAKER, 			"Please test Speaker",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_HEADSET, 			"Please test Headset",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_MELODY, 			"Melody Playing",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_VIB, 			       "Vibrating",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_NAND, 			       "Nand Testing",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_UART, 			       "UART Testing",		"Factory Mode ");

//Lisen 01262005
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_LEFT_SPEAKER, 			"Test left Speaker",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_AUTOTEST_RIGHT_SPEAKER, 			"Test right Speaker",		"Factory Mode ");

	ADD_APPLICATION_STRING2 (STR_ID_FM_MTBF, 			       "MTBF",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_MEMORY_CARD, 			       "Memory Card",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_UART, 			       "UART",		"Factory Mode ");

	ADD_APPLICATION_STRING2 (STR_ID_FM_NAND_FLASH, 			      "Nand Flash",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_CAMERA,						"Camera",				"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_CAMERA_SENSOR_SETTING,	"Sensor Setting",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_CAMERA_ISP_SETTING,		"ISP Setting",			"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_CAMERA_SAVE_TO_NVRAM,		"Save To NVRAM",		"Factory Mode ");
	ADD_APPLICATION_STRING2 (STR_ID_FM_CAMERA_RESTORE_DEFAULT,	"Restore Default",	"Factory Mode ");	

	ADD_APPLICATION_STRING2 (STR_ID_FM_CAMERA_SAVE_CONFRIM,		"Save?",		"Factory Mode ");	
	ADD_APPLICATION_STRING2 (STR_ID_FM_CAMERA_RESTORE_CONFIRM,	"Restore?",	"Factory Mode ");		

#ifdef __MMI_TOUCH_SCREEN__
	ADD_APPLICATION_STRING2 (STR_ID_FM_PARALLEL_TEST, 			       "Parallel Line Test",		"Factory Mode Pen Test");
	ADD_APPLICATION_STRING2 (STR_ID_FM_N_CROSS_M_TEST, 			    "N Cross M Point Test",	"Factory Mode Pen Test");
#endif /*__MMI_TOUCH_SCREEN__*/

#ifdef __MMI_FM_RADIO__
	ADD_APPLICATION_STRING2 (STR_ID_FM_FM_RADIO, 	    "FM Radio",	"Factory Mode Pen Test");
	ADD_APPLICATION_STRING2 (STR_ID_FM_FM_RADIO_CHANNEL_1,	    "Channel 1",	"Factory Mode Pen Test");
	ADD_APPLICATION_STRING2 (STR_ID_FM_FM_RADIO_CHANNEL_2,	    "Channel 2",	"Factory Mode Pen Test");
	ADD_APPLICATION_STRING2 (STR_ID_FM_FM_RADIO_CHANNEL_3,	    "Channel 3",	"Factory Mode Pen Test");	
#endif

    /* level Root */
       FMRootItemCount = 17;
    
#if (defined(__MSDC_MS__) || defined(__MSDC_SD_MMC__) || defined(__MSDC_MSPRO__))
       FMRootItemCount++;
#endif

#if (defined(NAND_SUPPORT))
       FMRootItemCount++;
#endif

#if (defined(__MMI_CAMERA__) && !defined(YUV_SENSOR_SUPPORT))
       FMRootItemCount++;
#endif
#if defined(__MMI_TOUCH_SCREEN__)
      FMRootItemCount+=2;
#endif /*__MMI_TOUCH_SCREEN__*/

#ifdef __MMI_FM_RADIO__
      FMRootItemCount++;   /* FM Radio */
#endif

	ADD_APPLICATION_MENUITEM((MENU_ID_FM_ROOT, IDLE_SCREEN_MENU_ID, FMRootItemCount, 
							   MENU_ID_FM_VERSION,
							   MENU_ID_FM_RESOURCE_BIN,
							   MENU_ID_FM_EACHLOOP,
							   MENU_ID_FM_KEYPAD,
							   MENU_ID_FM_VIBRATOR,
							   MENU_ID_FM_LOUDSPK,
							   MENU_ID_FM_RINGTONE,
							   MENU_ID_FM_LED,
							   MENU_ID_FM_LCD,
							   MENU_ID_FM_LCD_CONTRAST,
							   MENU_ID_FM_RECEIVER,
							   MENU_ID_FM_ADC,
							   MENU_ID_FM_CHARGER,
							   MENU_ID_FM_HEADSET,
							   MENU_ID_FM_RTC,
							   MENU_ID_FM_MTBF,
                                                           MENU_ID_FM_UART,							   
#if (defined(__MSDC_MS__) || defined(__MSDC_SD_MMC__) || defined(__MSDC_MSPRO__))							   
							   MENU_ID_FM_MEMORY_CARD,
#endif
#if (defined(NAND_SUPPORT))
							   MENU_ID_FM_NAND_FLASH,
#endif
#if (defined(__MMI_CAMERA__) && !defined(YUV_SENSOR_SUPPORT))
							   MENU_ID_FM_CAMERA,
#endif
#if defined(__MMI_TOUCH_SCREEN__)
							   MENU_ID_FM_PARALLEL_LINE,
							   MENU_ID_FM_N_CROSS_M,
#endif /*__MMI_TOUCH_SCREEN__*/
#ifdef __MMI_FM_RADIO__
                               MENU_ID_FM_FMRADIO,
#endif
							   SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_ROOT, IMG_ID_FM_ROOT ));

#if defined(__MMI_TOUCH_SCREEN__)
ADD_APPLICATION_MENUITEM((MENU_ID_FM_PARALLEL_LINE, MENU_ID_FM_ROOT, 0, 
							 		SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_FM_PARALLEL_TEST, 0));

ADD_APPLICATION_MENUITEM((MENU_ID_FM_N_CROSS_M, MENU_ID_FM_ROOT, 0, 
							 		SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_FM_N_CROSS_M_TEST, 0));
#endif /*__MMI_TOUCH_SCREEN__*/

#ifdef __MMI_FM_RADIO__
ADD_APPLICATION_MENUITEM((MENU_ID_FM_FMRADIO, MENU_ID_FM_ROOT, 0, 
							 		SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_FM_FM_RADIO, 0));
#endif

	ADD_APPLICATION_MENUITEM((MENU_ID_FM_AUTO_TEST_ROOT, IDLE_SCREEN_MENU_ID, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_AUTO_TEST_ROOT, IMG_ID_FM_AUTO_TEST_ROOT ));

	/* level 1 */
// Lisen 0921	
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_VERSION, MENU_ID_FM_ROOT, 9, 
                                                    MENU_ID_FM_SW_SUMMARY,
							   MENU_ID_FM_SW_VER,
							   MENU_ID_FM_MELODY_VER,
							   MENU_ID_FM_ISN,
						          MENU_ID_FM_BBCHIP_VER,
							   MENU_ID_FM_DSPCODE_VER,
							   MENU_ID_FM_DSPATCH_VER,
							   MENU_ID_FM_HW_VER,
							   MENU_ID_FM_BUILD_TIME,
  							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_VERSION, IMG_ID_FM_VERSION));


   ADD_APPLICATION_MENUITEM((MENU_ID_FM_RESOURCE_BIN , MENU_ID_FM_ROOT, 2, 
                                          	   MENU_ID_FM_RESOURCE_LANGPACK,
                                                    MENU_ID_FM_RESOURCE_CUSTPACK,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_RESOURCE_BIN, IMG_ID_FM_RESOURCE_BIN));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LED , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LED, IMG_ID_FM_LED));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LCD , MENU_ID_FM_ROOT, 6, 
							MENU_ID_FM_LCD_AUTO,
							MENU_ID_FM_LCD_R,
							MENU_ID_FM_LCD_G,
							MENU_ID_FM_LCD_B,
							MENU_ID_FM_LCD_W,
//Lisen 05312005	
							MENU_ID_FM_LCD_BLACK,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LCD, IMG_ID_FM_LCD));

#ifdef __MMI_SUBLCD__
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LCD_CONTRAST , MENU_ID_FM_ROOT, 2, 
							   MENU_ID_FM_LCD_CONTRAST_MAINLCD,
							   MENU_ID_FM_LCD_CONTRAST_SUBLCD,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LCD_CONTRAST, IMG_ID_FM_LCD_CONTRAST));
#else
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LCD_CONTRAST , MENU_ID_FM_ROOT, 1, 
							   MENU_ID_FM_LCD_CONTRAST_MAINLCD,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LCD_CONTRAST, IMG_ID_FM_LCD_CONTRAST));
#endif  /* __MMI_SUBLCD__ */


   ADD_APPLICATION_MENUITEM((MENU_ID_FM_KEYPAD , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_KEYPAD, IMG_ID_FM_KEYPAD));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LOUDSPK , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LOUDSPK, IMG_ID_FM_LOUDSPK));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_EACHLOOP , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_EACHLOOP, IMG_ID_FM_EACHLOOP));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_VIBRATOR , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_VIBRATOR, IMG_ID_FM_VIBRATOR));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_ADC , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_ADC, IMG_ID_FM_ADC));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_RECEIVER , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_RECEIVER, IMG_ID_FM_RECEIVER));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_RTC , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_RTC, IMG_ID_FM_RTC));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_MEMORY_CARD , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_MEMORY_CARD, IMG_ID_FM_MEMORY_CARD));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_UART , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_UART, IMG_ID_FM_UART));
	
  ADD_APPLICATION_MENUITEM((MENU_ID_FM_NAND_FLASH , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_NAND_FLASH, IMG_ID_FM_NAND_FLASH));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_HEADSET, MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_HEADSET, IMG_ID_FM_HEADSET));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_CHARGER , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_CHARGER, IMG_ID_FM_CHARGER));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_RINGTONE , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_RINGTONE, IMG_ID_FM_RINGTONE));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_MTBF , MENU_ID_FM_ROOT, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_MTBF, IMG_ID_FM_MTBF));

	/* FM Camera Tunning */
   ADD_APPLICATION_MENUITEM((	MENU_ID_FM_CAMERA, MENU_ID_FM_ROOT, 4, 
										MENU_ID_FM_CAMERA_SENSOR_SETTING,
										MENU_ID_FM_CAMERA_ISP_SETTING,
										MENU_ID_FM_CAMERA_SAVE_TO_NVRAM,
										MENU_ID_FM_CAMERA_RESTORE_DEFAULT,
									  	SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_CAMERA, 0));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_CAMERA_SENSOR_SETTING, MENU_ID_FM_CAMERA, 0, 
  							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_CAMERA_SENSOR_SETTING, 0));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_CAMERA_ISP_SETTING, MENU_ID_FM_CAMERA, 0, 
  							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_CAMERA_ISP_SETTING, 0));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_CAMERA_SAVE_TO_NVRAM, MENU_ID_FM_CAMERA, 0, 
  							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_CAMERA_SAVE_TO_NVRAM, 0));
   
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_CAMERA_RESTORE_DEFAULT, MENU_ID_FM_CAMERA, 0, 
  							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_CAMERA_RESTORE_DEFAULT, 0));

   /* level 2 */
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_BBCHIP_VER, MENU_ID_FM_VERSION, 0, 
  							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_BBCHIP_VER, IMG_ID_FM_BBCHIP_VER));
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_DSPCODE_VER, MENU_ID_FM_VERSION, 0, 
  							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_DSPCODE_VER, IMG_ID_FM_DSPCODE_VER));
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_DSPATCH_VER, MENU_ID_FM_VERSION, 0, 
  							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_DSPATCH_VER, IMG_ID_FM_DSPATCH_VER));
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_SW_VER, MENU_ID_FM_VERSION, 0, 
  							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_SW_VER, IMG_ID_FM_SW_VER));
// Lisen 0921	
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_SW_SUMMARY, MENU_ID_FM_VERSION, 0, 
  							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_SW_SUMMARY, IMG_ID_FM_SW_SUMMARY));
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_HW_VER, MENU_ID_FM_VERSION, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_HW_VER, IMG_ID_FM_HW_VER));
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_MELODY_VER , MENU_ID_FM_VERSION, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_MELODY_VER, IMG_ID_FM_MELODY_VER));
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_ISN, MENU_ID_FM_VERSION, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_ISN, IMG_ID_FM_ISN));
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_BUILD_TIME, MENU_ID_FM_VERSION, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_BUILD_TIME, IMG_ID_FM_BUILD_TIME));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_RESOURCE_LANGPACK, MENU_ID_FM_RESOURCE_BIN, 0, 
  							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_RESOURCE_LANGPACK, IMG_ID_FM_RESOURCE_LANGPACK));
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_RESOURCE_CUSTPACK, MENU_ID_FM_RESOURCE_BIN, 0, 
  							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_RESOURCE_CUSTPACK, IMG_ID_FM_RESOURCE_CUSTPACK));

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LCD_CONTRAST_MAINLCD , MENU_ID_FM_LCD_CONTRAST, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LCD_CONTRAST_MAIN, IMG_ID_FM_LCD_CONTRAST_MAIN));
#ifdef __MMI_SUBLCD__
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LCD_CONTRAST_SUBLCD , MENU_ID_FM_LCD_CONTRAST, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LCD_CONTRAST_SUB, IMG_ID_FM_LCD_CONTRAST_SUB));
#endif

   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LCD_AUTO , MENU_ID_FM_LCD, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LCD_AUTO, IMG_ID_FM_LCD_AUTO));
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LCD_R , MENU_ID_FM_LCD, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LCD_R, IMG_ID_FM_LCD_R));
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LCD_G , MENU_ID_FM_LCD, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LCD_G, IMG_ID_FM_LCD_G));
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LCD_B , MENU_ID_FM_LCD, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LCD_B, IMG_ID_FM_LCD_AUTO));
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LCD_W , MENU_ID_FM_LCD, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LCD_W, IMG_ID_FM_LCD_W));
   //Lisen 05312005	
   ADD_APPLICATION_MENUITEM((MENU_ID_FM_LCD_BLACK , MENU_ID_FM_LCD, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_FM_LCD_BLACK, IMG_ID_FM_LCD_BLACK));
   

   /* level 3 */

   /* level 4 */
   /*
   ADD_APPLICATION_MENUITEM((current_MENU_ID, parent_MENU_ID, 0, 
							SHOW, NONMOVEABLE, DISP_LIST, current_TEXT, current_ICON));

   */

   /* for contrast */
#ifdef __MMI_RES_TYPE_WALLPAPER__
    ADD_APPLICATION_IMAGE2(IMG_ID_FM_CONTRAST, CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\Wallpaper\\\\WALL01."__MMI_RES_TYPE_WALLPAPER__, "Image associated with wallpaper1.");
#else
   ADD_APPLICATION_IMAGE2(IMG_ID_FM_CONTRAST, CUST_IMG_PATH"\\\\MainLCD\\\\IdleScreen\\\\WallPaper\\\\wall01.gif","Image associated with wallpaper1.");
#endif /* __MMI_RES_TYPE_WALLPAPER__ */

}
#endif /* __MMI_FACTORY_MODE__ */

#endif


