/*******************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2002
*
*******************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 * MMSAppDefs.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file is intends for Defintion for MMS Applicaiton.
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/
#ifndef _MMS_APP_DEFS_H
#define _MMS_APP_DEFS_H
#ifdef __MMI_MMS_2__

typedef enum
{
    STR_ID_UMMS_PLEASE_WAIT = UMMS_MMS_BASE + 1,
    STR_ID_UMMS_DELETING_MMS,
    STR_ID_UMMS_MSGS,
    STR_ID_UMMS_OPTIONS_USE_DETAILS,
    STR_ID_UMMS_OPTIONS_PROPERTIES,
    STR_ID_UMMS_OPTIONS_MOVE_TO_ARCHIVE,
    STR_ID_UMMS_OPTIONS_MOVE_TO_DRAFTS,
    STR_ID_UMMS_NO_SUBJECT,
    /* STR_ID_UMMS_SUCESS_MMS_SENT, */
    STR_ID_UMMS_OPTIONS_USE_DETAILS_NUMBER,
    STR_ID_UMMS_OPTIONS_USE_DETAILS_EMAIL,
    STR_ID_UMMS_OPTIONS_USE_DETAILS_URL,
    STR_ID_UMMS_OPTIONS_USE_DETAILS_NUMBER_LIST,
    STR_ID_UMMS_OPTIONS_USE_DETAILS_EMAIL_LIST,
    STR_ID_UMMS_USE_DETAILS_ADDRESSES_SAVE_TO_PHONEBOOK,
    STR_ID_UMMS_USE_DETAILS_ADDRESSES_ADD_TO_CONTACT,
    STR_ID_UMMS_USE_DETAILS_ADDRESSES_CALL,
    STR_ID_UMMS_USE_DETAILS_NO_NUMBER,
    STR_ID_UMMS_USE_DETAILS_NO_EMAIL_ID,
	STR_ID_UMMS_MEMORY_FULL_CLEAN,
    STR_ID_UMMS_LOADING_MMS,
    STR_ID_UMMS_SAVING_MMS,
    STR_ID_UMMS_SAVE_SUCCESS,
    STR_ID_UMMS_OPTIONS_FORWARD,
    STR_ID_UMMS_OPTIONS_SAVE_OBJECTS,
    STR_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_TEXT_AS,
    STR_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_IMAGE_AS,
    STR_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_AUDIO_AS,
    STR_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_VIDEO_AS,
    STR_ID_UMMS_SAVE_OBJECT_OPTIONS_SAVE_ATTACHMENT_AS,
    STR_ID_UMMS_ERROR_GET_MSG_LIST,
    STR_ID_UMMS_ERROR_MMS_DELETE,
    STR_ID_UMMS_ERROR_MMS_MOVE,
    STR_ID_UMMS_DELETE_ALL_MMS_CONFIRM,
    STR_ID_UMMS_DELETE_ALL_UM_INBOX,
    STR_ID_UMMS_DELETE_ALL_UM_OUTBOX,
    STR_ID_UMMS_DELETE_ALL_UM_SENT,
    STR_ID_UMMS_DELETE_ALL_UM_DRAFTS,
    STR_ID_UMMS_FAILED_TO_DISPLAY_JSR_MMS,
    STR_ID_UMMS_EXPIRE_TIME,
    STR_ID_UMMS_HRS,
    STR_ID_UMMS_MINS,
    STR_ID_UMMS_DAYS,
    STR_ID_UMMS_SIZE,
    STR_ID_UMMS_KB,
    STR_ID_UMMS_GB,
    STR_ID_UMMS_BYTES,
    STR_ID_UMMS_WRITE_MMS_BYTES,
    STR_ID_UMMS_MSG_CLASS,
    STR_ID_UMMS_PERSONEL_MSG_CLASS,
    STR_ID_UMMS_INFORMATIONAL_MSG_CLASS,
    STR_ID_UMMS_AUTO_MSG_CLASS,
    STR_ID_UMMS_MESSAGE_ID,
    STR_ID_UMMS_ERROR_MMS_SENT,
	STR_ID_UMMS_ERROR_IN_SEND,
    STR_ID_UMMS_SUCCESS_MMS_SENT,
    STR_ID_UMMS_SUCCESS_MMS_SENT_ONLY,
    STR_ID_UMMS_BYTES_KB_RECIEVED,
    STR_ID_UMMS_COMM_ABORTED_AND_FAIL_STORE,
    STR_ID_UMMS_MEMORY_FULL,
    STR_ID_UMMS_FROM,
    STR_ID_UMMS_SUBJECT,
    STR_ID_UMMS_PLAY,
    STR_ID_UMMS_READ_NEW_MMS,
    STR_ID_UMMS_DOWNLOAD_NEW_MMS,
    STR_ID_UMMS_NEW_MMS,
    STR_ID_UMMS_CC,
    /* STR_ID_UMMS_DATE, */
    STR_ID_UMMS_TO,
    STR_ID_UMMS_STATUS,
    STR_ID_UMMS_BCC,
    /* STR_ID_UMMS_DELIVERY_STATUS_EXPIRED,
    STR_ID_UMMS_DELIVERY_STATUS_RETRIEVED,
    STR_ID_UMMS_DELIVERY_STATUS_REJECTED,
    STR_ID_UMMS_DELIVERY_STATUS_DEFFERED,
    STR_ID_UMMS_DELIVERY_STATUS_UNRECOGNISED,
    STR_ID_UMMS_DELIVERY_STATUS_INDETERMINATE,
    STR_ID_UMMS_DELIVERY_STATUS_FORWARDED,
       STR_ID_UMMS_DELIVERY_STATUS_UNREACHABLE, */
    STR_ID_UMMS_MMS_DOWNLOADING,
    STR_ID_UMMS_ERROR_MMS_DOWNLAOD,
    STR_ID_UMMS_MMS_DOWNLAOD_SUCCESS,
    STR_ID_UMMS_READ_REPORT_READ,
    STR_ID_UMMS_UNKNOWN,
    STR_ID_UMMS_READ_REPORT_DELETE_MSG,
    STR_ID_UMMS_READ_REPORT_MSG_ID,
    STR_ID_UMMS_ERROR_MMS_SAVING,
    STR_ID_UMMS_NEW_MMS_NOT_SAVED,
    STR_ID_UMMS_NEW_MMS_MEMORY_NOT_SAVED,
    STR_ID_UMMS_MMS_SENT_NOT_SAVE,
    STR_ID_UMMS_ERROR_MMS_SENT_AND_FAIL_STORE,
    STR_ID_UMMS_ERROR_MMS_SENT_AND_STORED,
    STR_ID_UMMS_SAVE_TO_DRAFTS,
    STR_ID_UMMS_APPLICATION_ID,
    STR_ID_UMMS_REPLY_TO_APPLICATION_ID,
    STR_ID_UMMS_NEW_JAVA_MMS,
    STR_ID_UMMS_ERROR_MMS_MEMORY_FULL,
    STR_ID_UMMS_ERROR_MMS_SENT_AND_FAIL_STORE_MEMORY,
    STR_ID_UMMS_ERROR_MMS_SENT_AND_FAIL_STORE_MEM_FULL,
    STR_ID_UMMS_MMS_SENT_NOT_SAVE_MEMORY,
    STR_ID_UMMS_MMS_SENT_NOT_SAVE_MEMORY_FULL,
    STR_ID_UMMS_MEMORY_LIMIT_REACH,
    STR_ID_UMMS_MEMORY_FULL_REACH,
    STR_ID_UMMS_ERROR_MMS_DOWNLAOD_STORE_FUL,
    STR_ID_UMMS_ERROR_MMS_SENT_STORE_FUL,
    STR_ID_UMMS_INBOX_OPTIONS_REPLY_ALL,
    STR_ID_UMMS_MB,
    STR_ID_UMMS_WRITE_MESSAGE,
    //STR_ID_MMS_OPTIONS_SAVE_OBJECTS,
    //STR_ID_MMS_OPTIONS_USE_DETAILS_NUMBER,
    STR_ID_UMMS_READ_REPORT_REQUEST,
    STR_ID_UMMS_READ_REPORT_DELETED,
    STR_ID_UMMS_READ_REPORT_MSG,
    STR_ID_UMMS_READ_REPORT_MSG_SUBJECT,
    STR_ID_UMMS_SUCCESS_READ_REPORT_SENT,
    STR_ID_UMMS_ERROR_READ_REPORT_SENT,
    STR_ID_UMMS_ERROR_DELIVERY_SAVING,
    STR_ID_UMMS_MEMORY_ERROR_DELIVERY_SAVING,
    STR_ID_UMMS_ERROR_NEW_MMS_NOTIF_SAVING,
    STR_ID_UMMS_MEMORY_ERROR_NEW_MMS_NOTIF_SAVING,
    STR_ID_UMMS_ERROR_READ_REPORT_SAVING,
    STR_ID_UMMS_MEMORY_ERROR_READ_REPORT_SAVING,
    STR_ID_UMMS_ERROR_ADDR_UNRESOLVED,
    STR_ID_UMMS_ERROR_NETWORK_PROBLEM,
    STR_ID_UMMS_ERROR_INVALID_MSG,
    STR_ID_UMMS_ERROR_REPLY_CHARGING,
    STR_ID_UMMS_ERROR_ADDR_HIDING,
    STR_ID_UMMS_ERROR_WRONG_CONTENT_TYPE,
    STR_ID_UMMS_ERROR_REDIRECTION,
    STR_ID_UMMS_ERROR_CLIENT,
    STR_ID_UMMS_ERROR_SERVER,
    STR_ID_UMMS_ERROR_SERVER_DENIED,
    STR_ID_UMMS_CONNECTING,
    STR_ID_UMMS_RETRY,
    STR_ID_UMMS_NOTF_IN_USE,
    STR_ID_UMMS_STORAGE_ERROR_READ_REPORT_SENT,
    STR_ID_UMMS_SETTINGS_VALIDITY_PERIOD,
    STR_ID_UMMS_SETTINGS_1_HR,
	STR_ID_UMMS_SETTINGS_6_HRS,
    STR_ID_UMMS_SETTINGS_12_HRS,
    STR_ID_UMMS_SETTINGS_1_DAY,
    STR_ID_UMMS_SETTINGS_1_WEEK,
    STR_ID_UMMS_SETTINGS_READ_REPORT,
    STR_ID_UMMS_SETTINGS_PRIORITY,
    STR_ID_UMMS_SETTINGS_LOW,
    /* STR_ID_SETTINGS_MEDIUM, */
    STR_ID_UMMS_SETTINGS_HIGH,
    STR_ID_UMMS_SETTINGS_DELIVERY_TIME,
    STR_ID_UMMS_SETTINGS_IMMEDIATE,
	STR_ID_UMMS_SETTINGS_DELV_1_HR,
	STR_ID_UMMS_SETTINGS_DELV_12_HRS,
    STR_ID_UMMS_SETTINGS_DELV_24_HRS,
    STR_ID_UMMS_SETTINGS_HIDE_SENDER,
	STR_ID_UMMS_SETTINGS_SEND_AND_SAVE,
    STR_ID_UMMS_SETTINGS_REPLY_CHARGING,
    STR_ID_UMMS_SETTINGS_REQUEST_TYPE,
    STR_ID_UMMS_SETTINGS_REQUEST_TYPE_FULL_MMS,
    STR_ID_UMMS_SETTINGS_REQUEST_TYPE_ONLY_TEXT,
    STR_ID_UMMS_SETTINGS_REPLY_DEADLINE,
    STR_ID_UMMS_SETTINGS_REPLY_CHARGE_SIZE,
	STR_ID_UMMS_SIGNATURE_SELECT_FILE,
	STR_ID_UMMS_SIGNATURE_DELETE_REF,
	STR_ID_UMMS_SIGNATURE_PATH_TOO_LONG,
	STR_ID_UMMS_AUDIO_VIDEO_NOT_ALLOWED,
	STR_ID_UMMS_VIDEO_IMAGE_NOT_ALLOWED,
	STR_ID_UMMS_REMOVE_AUDIO_IMAGE,
    STR_ID_UMMS_GLOBAL_MEDIUM,
    STR_ID_UMMS_FAILED,
    STR_ID_UMMS_DWNLOADING,
    STR_ID_UMMS_WAITING_DWNLOADING,
    STR_ID_UMMS_SENDING,
    STR_ID_UMMS_WAITING_SENDING,
    STR_ID_UMMS_NORMAL,
    STR_ID_UMMS_MESSAGE_STATUS,
    STR_ID_MMA_RESULT_FAIL,
    STR_ID_MMA_RESULT_FAIL_INCALL,
    STR_ID_MMA_RESULT_FAIL_NOT_READY,
    STR_ID_MMA_RESULT_FAIL_BUSY,
    STR_ID_MMA_RESULT_FAIL_INSUFFICIENT_MEMORY,
    STR_ID_MMA_RESULT_FAIL_INSUFFICIENT_STORAGE,
    STR_ID_MMA_RESULT_FAIL_MAX_MSG_NUM_REACHED,
    STR_ID_MMA_RESULT_FAIL_MAX_MSG_SIZE_REACHED,
    STR_ID_MMA_RESULT_FAIL_FILE_NOT_FOUND,
    STR_ID_MMA_RESULT_FAIL_FILE_CORRUPTED,
    STR_ID_MMA_RESULT_FAIL_FILE_IN_USE,
    STR_ID_MMA_RESULT_FAIL_FILE_IO,
    STR_ID_MMA_RESULT_FAIL_UNSUPPORT_CONTENT,
    STR_ID_MMA_RESULT_FAIL_CONNECT_ERROR,
    STR_ID_MMA_RESULT_FAIL_SERVER_TIMEOUT,
    STR_ID_MMA_RESULT_FAIL_USER_CANCEL,
    STR_ID_MMA_RESULT_FAIL_INVALID_PARAMETER,
    STR_ID_MMA_RESULT_FAIL_QUEUE_FULL,
    STR_ID_UMMS_CANCELLING_MMS,
    STR_ID_UMMS_COMM_ABORTED_FAILED,
	STR_ID_MMA_RESULT_DELAYED,
	STR_ID_MMA_RESULT_CONTINUE,
	STR_ID_MMA_RESULT_FAIL_MAX_SLIDE_NUM_REACHED,
	STR_ID_MMA_RESULT_FAIL_MAX_ATTACHMENT_NUM_REACHED,
	STR_ID_MMA_RESULT_FAIL_FOLDER_NOT_FOUND,
	STR_ID_MMA_RESULT_FAIL_COMM_UNSUPPORT_CONTENT,
	STR_ID_MMA_RESULT_FAIL_COMM_CONFIG_ERROR,
	STR_ID_MMA_RESULT_FAIL_COMM_SERVER_ERROR,
	STR_ID_MMA_RESULT_FAIL_COMM_SERVICE_DENIED,
	STR_ID_MMA_RESULT_FAIL_COMM_UNKNOWN_APN,
	STR_ID_MMA_RESULT_FAIL_COMM_UNAUTHORIZED,
	STR_ID_MMA_RESULT_FAIL_INVALID_MSGID,
	STR_ID_MMA_RESULT_FAIL_INVALID_FOLDER,
	STR_ID_MMA_RESULT_FAIL_PARSE,
	STR_ID_MMA_RESULT_FAIL_MSGID_IS_USING,
	STR_ID_MMA_RESULT_FAIL_CREATION_MODE_MAX_MSG_SIZE_REACHED,
	STR_ID_MMA_RESULT_FAIL_UPDATE_CHECKSUM_INVALID_PARAM,
    STR_ID_UMMS_SAVE_AS_TEMPLATE,
	STR_ID_UMMS_TEMPLATE_REMOVE_USB,
    STR_ID_UMMS_MAX_TEMPLATE_ALREADY_PRESENT,
	STR_ID_UMMS_OPTIONS_MSG_SIZE_EXCEED,
    STR_ID_UMMS_DR_STATUS_EXPIRED,
    STR_ID_UMMS_DR_STATUS_RETRIEVED,
    STR_ID_UMMS_DR_STATUS_REJECTED,
    STR_ID_UMMS_DR_STATUS_DEFERRED,
    STR_ID_UMMS_DR_STATUS_UNRECOGNISED,
    STR_ID_UMMS_DR_STATUS_INDETERMINATE,
    STR_ID_UMMS_DR_STATUS_FORWARDED,
    STR_ID_UMMS_DR_STATUS_UNREACHABLE,
    STR_ID_UMMS_DR_STATUS_READ,
    STR_ID_UMMS_DR_STATUS_NO_READ,
    /* Ashwani Starts */
    STR_ID_UMMS_USE_DETAILS_CURRENT_SLIDE,
    STR_ID_UMMS_USE_DETAILS_ALL_SLIDES,
    STR_ID_UMMS_OPTIONS_USE_DETAILS_OPTIONS,
    STR_ID_UMMS_OPTIONS_USE_DETAILS_URL_LIST,
    STR_ID_UMMS_USE_DETAILS_ADDRESSES_GO_TO,
    STR_ID_UMMS_USE_DETAILS_ADDRESSES_ADD_BOOKMARK,
    STR_ID_UMMS_USE_DETAILS_NO_URL,
    STR_ID_UMMS_OBJECTS_ATTACHMENT_LIST,
    STR_ID_UMMS_PHONE_MEMORY_FULL,
    STR_ID_UMMS_USE_DETAILS_MESSAGE_HEADER,
    STR_ID_UMMS_LOCK_MODE,
    STR_ID_UMMS_ON,
    STR_ID_UMMS_OFF,
    /* Ashwani Ends */
    STR_ID_UMMS_TEMPLATES_TITLE_01,
    STR_ID_UMMS_TEMPLATES_TITLE_02,
    STR_ID_UMMS_TEMPLATES_TITLE_03,
    STR_ID_UMMS_TEMPLATES_TITLE_04,
    STR_ID_UMMS_TEMPLATES_TITLE_05,
    STR_ID_UMMS_TEMPLATES_TITLE_06,
    STR_ID_UMMS_TEMPLATES_TITLE_07,
    STR_ID_UMMS_TEMPLATES_TITLE_08,
    STR_ID_UMMS_TEMPLATES_TITLE_09,
    STR_ID_UMMS_TEMPLATES_TITLE_10,
    STR_ID_UMMS_TEMPLATE_OPTIONS_DELETE,
    STR_ID_UMMS_TEMPLATE_OPTIONS_DELETE_ALL,
    STR_ID_UMMS_TEMPLATE_DEFAULT,
    STR_ID_UMMS_TEMPLATE_USER_DEFINED,
    STR_ID_UMMS_SETTINGS_MESSAGE_STATUS_TOTAL,
    STR_ID_UMMS_OUT_OF_MEMORY,
    STR_ID_UMMS_MMS_SETTINGS,
    STR_ID_UMMS_MAXIMUM,
    STR_ID_UMMS_SETTINGS_MESSAGE_STATUS_USAGE,
    STR_ID_UMMS_TEMPLATES,
    STR_ID_UMMS_MESSAGE_SETTINGS_COMPOSE,
    STR_ID_UMMS_MESSAGE_SETTINGS_SENDING,
    STR_ID_UMMS_MESSAGE_SETTINGS_RETRIEVAL,
    STR_ID_UMMS_MESSAGE_SETTINGS_EDIT_PROFILE,
    STR_ID_UMMS_MESSAGE_SETTINGS_MEMORY_STATUS,
    STR_ID_UMMS_SETTINGS_DEFAULT_SLIDE_TIMING,
    STR_ID_UMMS_SETTINGS_LAYOUT,
    STR_ID_UMMS_SETTINGS_POTRAIT,
    STR_ID_UMMS_SETTINGS_LANDSCAPE,
#ifdef __DRM_SUPPORT__
    STR_ID_UMMS_SETTINGS_ADD_DRM,
#endif 
    STR_ID_UMMS_SETTINGS_CREATION_MODES,
    STR_ID_UMMS_SETTINGS_RESTRICTED,
    STR_ID_UMMS_SETTINGS_WARNING,
    STR_ID_UMMS_SETTINGS_FREE,
    STR_ID_UMMS_SETTINGS_MAX_NUM_PAGES,
    STR_ID_UMMS_SETTINGS_BEST_PAGE_DURATION,
    STR_ID_UMMS_SETTINGS_AUTO_SIGNATURE,
    STR_ID_UMMS_AUTO_SIGNATURE_ERROR_TOO_MANY_SLIDES,
    STR_ID_UMMS_AUTO_SIGNATURE_ERROR_SIZE_TOO_LARGE,
	STR_ID_UMMS_SETTINGS_SIGNATURE,
	STR_ID_UMMS_SETTINGS_SIGNATURE_TEXT,
	STR_ID_UMMS_SETTINGS_SIGNATURE_IMAGE,
	STR_ID_UMMS_SETTINGS_SIGNATURE_VIDEO,
	STR_ID_UMMS_SETTINGS_SIGNATURE_AUDIO,
	STR_ID_UMMS_SETTINGS_SIGNATURE_NOT_ALLOWED,
	STR_ID_UMMS_SIGNATURE_SELECT_MEDIA,
STR_ID_UMMS_SIGNATURE_INVALID_SIZE,
STR_ID_UMMS_SIGNATURE_FILE_CORRUPTED,
    STR_ID_UMMS_SETTINGS_SAVING,
    STR_ID_UMMS_SETTINGS_SAVE,
    STR_ID_UMMS_SETTINGS_EDIT,
    STR_ID_UMMS_SETTINGS_EDIT_CONTENT,
    STR_ID_UMMS_SETTINGS_IMAGE_RESIZE,
    STR_ID_UMMS_SETTINGS_160_X_120,
    STR_ID_UMMS_SETTINGS_320_X_240,
    STR_ID_UMMS_SETTINGS_HOME_NETWORK,
    STR_ID_UMMS_SETTINGS_ROAMING,
    STR_ID_UMMS_SETTINGS_FILTERS,
    STR_ID_UMMS_SETTINGS_ON_REQUEST,
    STR_ID_UMMS_SETTINGS_SEND,
    STR_ID_UMMS_SETTINGS_NEVER_SEND,
    STR_ID_UMMS_SETTINGS_ANNONYMOUS,
    STR_ID_UMMS_SETTINGS_MAX_MSG_SIZE,
    STR_ID_UMMS_SETTINGS_ADVERTISMENT,
    STR_ID_UMMS_SETTINGS_ALLOW,
    STR_ID_UMMS_SETTINGS_REJECT,
    STR_ID_UMMS_DELIVERY_REPORT,
    STR_ID_UMMS_SETTINGS_DEFFERED,
    STR_ID_UMMS_SETTINGS_AS_HOME,
    STR_ID_UMMS_SETTINGS_ON,
    STR_ID_UMMS_SETTINGS_OFF,
    STR_ID_UMMS_MAX_PAGES_LIMIT,
    STR_ID_UMMS_SLIDE_TIME_ZERO_ERROR,
    STR_ID_UMMS_AUTO_SIGN_ERROR,
    STR_ID_UMMS_SETTINGS_REPLY_DEADLINE_ERROR,
    STR_ID_UMMS_SETTINGS_REPLY_CHARGE_SIZE_ERROR,
    STR_ID_UMMS_MAX_MSG_SIZE_LIMT,
    STR_ID_UMMS_SETTINGS_FREE_SPACE,
	STR_ID_UMMS_SETTINGS_640_X_480,
	STR_ID_UMMS_CREATION_DATE,
	STR_ID_UMMS_RECEIVE_DATE,
    STR_ID_UMMS_OPERATION_NOT_ALLOWED,
    STR_ID_UMMS_RESTRICTED_MODE,
    STR_ID_MMS_VIEWER_TEXT_STRIPPED,
    STR_ID_MMS_VIEWER_APP,
    STR_ID_MMS_VIEWER_SEND_RR_CONFIRM,
//MTI DRM2.0 START
    STR_ID_MMS_VIEWER_OUT_OF_MEMORY,
    STR_ID_MMS_VIEWER_ODF_MOVED_TO_ATTACHMENT,
    STR_ID_MMS_VIEWER_FILE_ERROR,
//MTI DRM2.0 END
	STR_ID_UMMS_CREATION_IN_PROCESS,
	STR_ID_UMMS_NOTIFICATION_EXPIRED,
    /* STR_ID_UMMS_MAX, */
	STR_ID_UMMS_SEND_EMAIL,
	STR_ID_UMMS_SEND_SMS,
	STR_ID_UMMS_SEND_MMS,
	STR_ID_UMMS_URL_TOO_LONG,
    STR_ID_UMMS_CORRUPT_AND_DELETE,
    STR_ID_UMMS_CANCEL_SEND,
    STR_ID_UMMS_CANCELLING_SEND,
    STR_ID_UMMS_CANCELLING_SEND_FAILURE,
    STR_ID_UMMS_CANCELLING_SEND_SUCESS,
	STR_ID_UMMS_TERMINATED,
	STR_ID_UMMS_INVALID_URL,
	STR_ID_UMMS_INVALID_TITLE,
	STR_ID_UMMS_FILE_SYSTEM_ERROR,
	STR_ID_UMMS_BOOK_MARK_FULL,
STR_ID_UMMS_USE_DETAILS_INVALID_NUMBER,
STR_ID_UMMS_USE_DETAILS_INVALID_EMAIL_ID,
STR_ID_UMMS_INBOX_OPTIONS_REPLY_SMS,
STR_ID_UMMS_OPTIONS_PROPERTIES_PRIORITY,
STR_ID_UMMS_FWD_OPTIONS,
STR_ID_UMMS_EDIT_CONFIRM,
STR_ID_UMMS_SEND_FAIL_RETRY,
STR_ID_UMMS_END
} STR_ID_UMMS_LIST;

typedef enum
{
    SCR_ID_UMMS_PROGRESS = UMMS_MMS_BASE + 1,
    SCR_ID_UMMS_NOTIFICATION,
    SCR_ID_UMMS_MMS,
    SCR_ID_UMMS_VIEWER,
    SCR_ID_UMMS_RETRIEVED_MMS_PROPERTIES,
    SCR_ID_UMMS_MESSAGE_STATUS,
    SCR_ID_UMMS_MMS_OPTIONS,
    SCR_ID_UMMS_DUMMY,
    SCR_ID_UMMS_JAVA_OPTIONS,
    SCR_ID_UMMS_READ_DELIVERY_REPORT_OPTIONS,
    SCR_ID_UMMS_MMS_OPTIONS_USE_DETAILS,
    SCR_ID_UMMS_MMS_OPTIONS_USE_DETAILS_OPTIONS,
    SCR_ID_UMMS_MMS_OPTIONS_USE_DETAILS_ADDRESS_LIST,
    SCR_ID_UMMS_OPTIONS_USE_DETAILS_ADDRESSES_OPTIONS,
    SCR_ID_UMMS_SAVE_OBJECT,
    SCR_ID_UMMS_SAVE_OBJECT_ATTACHMENT_LIST,
    SCR_ID_UMMS_TEMPLATES,
    SCR_ID_UMMS_TEMPLATES_OPTIONS,
    SCR_ID_UMMS_TEMPLATES_DEFAULT_USER_DEFINED,
    SCR_ID_UMMS_MESSAGE_SETTINGS,   /* mms settings */
    SCR_ID_UMMS_COMPOSE_SETTINGS,
    SCR_ID_UMMS_SENDING_SETTINGS,
    SCR_ID_UMMS_SENDING_REPLY_CHARGING_SETTINGS,
    SCR_ID_UMMS_RETRIEVAL_SETTINGS,
    SCR_ID_UMMS_RETRIEVAL_FILTERS_SETTINGS,
    SCR_ID_UMMS_MMS_MESSAGE_STATUS,
    SCR_ID_UMMS_OPTION_LOCK,
    SCR_ID_UMMS_MMS_OPTIONS_RESTRICTED,
    SCR_ID_UMMS_PROGRESS_USE_DETAILS,
    SCR_ID_UMMS_READ_REPORT,
    SCR_ID_UMMS_MMS_VIEWER,
    /* MAUI_00462177 */
    SCR_ID_UMMS_MMS_VIEWER_PROGRESS_SCREEN,
    /* MAUI_00462177 */    
    SCR_ID_UMMS_RR_CONFIRM_SCREEN,
    SCR_ID_UMMS_COMPOSE_SIGNATURE_SETTINGS,
    SCR_ID_UMMS_IMAGE_VIEW_IMAGE,
    SCR_ID_UMMS_COMPOSE_IMAGE_OPTION,
    SCR_ID_UMMS_FWD_EDIT_CLUBBED,
    SCR_ID_UMMS_RETRIEVED_MMS_VIEW_PROPERTIES,
    SCR_ID_UMMS_END
} SCR_ID_UMMS_LIST;

typedef enum
{
    IMG_ID_UMMS_TEMPLATES_01 = UMMS_MMS_BASE + 1,
    IMG_ID_UMMS_TEMPLATES_02,
    IMG_ID_UMMS_TEMPLATES_03,
    IMG_ID_UMMS_TEMPLATES_04,
    IMG_ID_UMMS_TEMPLATES_05,
    IMG_ID_UMMS_TEMPLATES_06,
    IMG_ID_UMMS_TEMPLATES_07,
    IMG_ID_UMMS_TEMPLATES_08,
    IMG_ID_UMMS_TEMPLATES_09,
    IMG_ID_UMMS_TEMPLATES_10,
    IMG_ID_UMMS_SETTINGS,
    IMG_ID_UMMS_WRITE_MESSAGE,
    IMG_ID_UMMS_TEMPLATE_MMS,
    IMG_ID_MMS_VIEWER_APP,
    IMG_ID_UMMS_USE_DETAILS_IMAGE_NUMBER,
    IMG_ID_UMMS_USE_DETAILS_IMAGE_EMAIL,
    IMG_ID_UMMS_USE_DETAILS_IMAGE_URL,
    IMG_ID_UMMS_ATTACHMENT_LIST,
    IMG_ID_UMMS_END
} IMG_UMMS_LIST;

#endif /* __MMI_MMS_2__ */ 

#endif /* _MMS_APP_DEFS_H */ /* __MMI_MMS_2__ */

