#ifdef L1_CATCHER

#include "TrcMod.h"

/****************/
/* Filter array */
/****************/
unsigned char L1Audio_Trace_Filter[5] = 
		{ 0x1, 0x3, 0x0, 0x0, 0x0 };
/***********************/
/* Set filter function */
/***********************/
void Set_L1Audio_Filter(unsigned char *setting)
{
	int i;

	for(i=0; i<5; i++)
		L1Audio_Trace_Filter[i] = setting[i];
}

/****************************************/
/* Function definition for each Message */
/****************************************/
/* L1Audio_Msg_AFE_Switch */
void L1TRC_Send_L1Audio_Msg_AFE_Switch(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xC0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AFE_TurnSpk */
void L1TRC_Send_L1Audio_Msg_AFE_TurnSpk(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xC1);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AFE_TurnMIC */
void L1TRC_Send_L1Audio_Msg_AFE_TurnMIC(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xC2);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AFE_TurnFIR */
void L1TRC_Send_L1Audio_Msg_AFE_TurnFIR(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xC3);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AFE_SetInput */
void L1TRC_Send_L1Audio_Msg_AFE_SetInput(char v1)
{
	TRC_START_FILL_TASK(4);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xC4);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_BYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AFE_MicVolume */
void L1TRC_Send_L1Audio_Msg_AFE_MicVolume(unsigned char v1)
{
	TRC_START_FILL_TASK(4);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xC5);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AFE_StVolume */
void L1TRC_Send_L1Audio_Msg_AFE_StVolume(unsigned char v1)
{
	TRC_START_FILL_TASK(4);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xC6);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AFE_EcParam */
void L1TRC_Send_L1Audio_Msg_AFE_EcParam(short v1, short v2)
{
	TRC_START_FILL_TASK(7);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xC7);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_SHORT(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AFE_SetDevice */
void L1TRC_Send_L1Audio_Msg_AFE_SetDevice(unsigned char v1, char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xC8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_BYTE(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AFE_SetVolume */
void L1TRC_Send_L1Audio_Msg_AFE_SetVolume(unsigned char v1, unsigned char v2, unsigned char v3)
{
	TRC_START_FILL_TASK(6);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xC9);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AFE_SpkSelect */
void L1TRC_Send_L1Audio_Msg_AFE_SpkSelect(short v1, short v2, short v3, short v4, short v5)
{
	TRC_START_FILL_TASK(13);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xCA);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_SHORT(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_SHORT(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_SHORT(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_MAKE_SHORT(TRC_TASK_BUFFER, TRC_LOCAL, v4);
	TRC_MAKE_SHORT(TRC_TASK_BUFFER, TRC_LOCAL, v5);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AFE_Gain */
void L1TRC_Send_L1Audio_Msg_AFE_Gain(unsigned short v1, unsigned short v2, short v3)
{
	TRC_START_FILL_TASK(9);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xCB);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_USHORT(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_USHORT(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_SHORT(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AM_Switch */
void L1TRC_Send_L1Audio_Msg_AM_Switch(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xCC);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AM_Handover */
void L1TRC_Send_L1Audio_Msg_AM_Handover(char v1)
{
	TRC_START_FILL_TASK(4);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xCD);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_BYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AM_IO_Switch */
void L1TRC_Send_L1Audio_Msg_AM_IO_Switch(unsigned char v1)
{
	TRC_START_FILL_TASK(4);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xCE);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AM_SetSpeech */
void L1TRC_Send_L1Audio_Msg_AM_SetSpeech(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xCF);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_Speech_State */
void L1TRC_Send_L1Audio_Msg_Speech_State(unsigned char v1)
{
	TRC_START_FILL_TASK(4);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xD0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_DSP_INT */
void L1TRC_Send_L1Audio_Msg_DSP_INT(unsigned short v1)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xD1);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_USHORT(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_AM_DELAY_TABLE */
void L1TRC_Send_L1Audio_Msg_AM_DELAY_TABLE(short v1)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xD2);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_SHORT(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_SPEECH_FRAME */
void L1TRC_Send_L1Audio_Msg_SPEECH_FRAME(unsigned char v1, unsigned char v2, unsigned char v3)
{
	TRC_START_FILL_TASK(6);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xD3);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_SPEECH_CODEC */
void L1TRC_Send_L1Audio_Msg_SPEECH_CODEC(unsigned char v1, unsigned char v2)
{
	TRC_START_FILL_TASK(5);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xD4);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_VM_DEBUG */
void L1TRC_Send_L1Audio_Msg_VM_DEBUG(unsigned short v1, unsigned short v2, unsigned short v3)
{
	TRC_START_FILL_TASK(9);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xD5);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_USHORT(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_USHORT(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_MAKE_USHORT(TRC_TASK_BUFFER, TRC_LOCAL, v3);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_VBI_RESET */
void L1TRC_Send_L1Audio_Msg_VBI_RESET(void)
{
	TRC_START_FILL_TASK(3);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xD6);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_END_FILL_TASK;
}

/* L1Audio_Msg_SPE_DEBUG */
void L1TRC_Send_L1Audio_Msg_SPE_DEBUG(unsigned short v1, unsigned short v2)
{
	TRC_START_FILL_TASK(7);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xF8);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0xD7);
	TRC_MAKE_UBYTE(TRC_TASK_BUFFER, TRC_LOCAL, 0x0);
	TRC_MAKE_USHORT(TRC_TASK_BUFFER, TRC_LOCAL, v1);
	TRC_MAKE_USHORT(TRC_TASK_BUFFER, TRC_LOCAL, v2);
	TRC_END_FILL_TASK;
}

#endif
