/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
* Filename:
* ---------
*  AudioPlayerResDef.h
*
* Project:
* --------
*   MAUI
*
* Description:
* ------------
*   Audio player Resource Definition
*
* Author:
* -------
*  Kinse Lin
*
*==============================================================================
*           HISTORY
* Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * $Log$
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 * removed!
 * removed!
 * 
 *
 *
 *------------------------------------------------------------------------------
* Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
*==============================================================================
*******************************************************************************/

#ifndef AUDIO_PLAYER_RES_DEF_H
#define AUDIO_PLAYER_RES_DEF_H

#ifdef __MMI_AUDIO_PLAYER__

typedef enum
{
    STR_ID_AUDPLY_BASE = AUDIO_PLAYER_BASE + 1,
    STR_ID_AUDPLY_TITLE,
    STR_ID_AUDPLY_LIST,
    STR_ID_AUDPLY_PLAYLIST,
    STR_ID_AUDPLY_LIST_FROM_PHONE,
    STR_ID_AUDPLY_LIST_FROM_CARD,
    STR_ID_AUDPLY_OPTION_PLAY,
    STR_ID_AUDPLY_OPTION_ADD,
    STR_ID_AUDPLY_OPTION_DETAIL,
    STR_ID_AUDPLY_OPTION_ADD_TO_RINGS,
    STR_ID_AUDPLY_OPTION_REMOVE,
    STR_ID_AUDPLY_OPTION_REMOVE_ALL,
    STR_ID_AUDPLY_OPTION_REMOVE_ASK,
    STR_ID_AUDPLY_OPTION_REMOVE_ALL_ASK,
    STR_ID_AUDPLY_OPTION_REGEN_LIST,
    STR_ID_AUDPLY_OPTION_SETTINGS,
    STR_ID_AUDPLY_PLAYER_SETTINGS,
    STR_ID_AUDPLY_DISPLAY_SETTINGS,
#if defined(__MMI_AUDIO_EQUALIZER__) || defined(__MMI_AUDIO_TIME_STRETCH__) || defined(__MMI_AUDIO_REVERB_EFFECT__) || defined(__MMI_AUDIO_SURROUND_EFFECT__)
    STR_ID_AUDPLY_SOUND_EFFECT_SETTINGS,
#endif
    STR_ID_AUDPLY_BLUETOOTH_SETTINGS,
#ifndef __MMI_SLIM_AUDIO_PLAYER__
    STR_ID_AUDPLY_SETTINGS_SKIN1,
    STR_ID_AUDPLY_SETTINGS_SKIN2,
    STR_ID_AUDPLY_SETTINGS_SKIN3,
#endif /* __MMI_SLIM_AUDIO_PLAYER__ */ 
    STR_ID_AUDPLY_SETTINGS_ON,
    STR_ID_AUDPLY_SETTINGS_OFF,
    STR_ID_AUDPLY_SETTINGS_ONE,
    STR_ID_AUDPLY_SETTINGS_ALL,
    STR_ID_AUDPLY_SETTINGS_LIST_AUTO_GEN,
    STR_ID_AUDPLY_SETTINGS_PREFER_LIST,
#ifndef __MMI_SLIM_AUDIO_PLAYER__      
    STR_ID_AUDPLY_SETTINGS_SKIN,
#endif    
    STR_ID_AUDPLY_SETTINGS_REPEAT,
    STR_ID_AUDPLY_SETTINGS_SHUFFLE,
#ifndef __MMI_AUDIO_PLAYER_ON_SUBLCD__    
    STR_ID_AUDPLY_SETTINGS_BACKGROUND_PLAY,
#endif
#ifdef __MMI_AUDIO_SPECTRUM_DISPLAY__
	STR_ID_AUDPLY_SETTINGS_SPECTRUM_DISPLAY_STYLE,
	STR_ID_AUDPLY_SETTINGS_SPECTRUM_DISPLAY_STYLE_1,
	STR_ID_AUDPLY_SETTINGS_SPECTRUM_DISPLAY_STYLE_2,
#endif /* __MMI_AUDIO_SPECTRUM_DISPLAY__ */
#ifdef __MMI_AUDIO_PLAYER_LYRIC_DISPLAY__
    STR_ID_AUDPLY_SETTINGS_LYRICS_DISPLAY,
#endif
#ifdef __MMI_AUDIO_PLAYER_A2DP_BLOCK_SPECTRUM__
    STR_ID_AUDPLY_A2DP_BLOCK_SPECTRUM,
#endif
    STR_ID_AUDPLY_SETTINGS_BT_A2DP_OUTPUT,
    STR_ID_AUDPLY_SETTINGS_BT_A2DP_HEADSET,
    STR_ID_AUDPLY_SETTINGS_ERR_MUST_SELECT_HEADSET,
    STR_ID_AUDPLY_SETTINGS_ERR_CANNOT_USE_BLUETOOTH_IN_FLIGHT_MODE,
    STR_ID_AUDPLY_DETAIL_SIZE,
    STR_ID_AUDPLY_DETAIL_TIME,
    STR_ID_AUDPLY_DETAIL_TITLE,
    STR_ID_AUDPLY_DETAIL_ARTIST,
    STR_ID_AUDPLY_DETAIL_ALBUM,
    STR_ID_AUDPLY_DETAIL_GENRE,
    STR_ID_AUDPLY_DETAIL_YEAR,
#ifdef __MMI_AUDIO_PLAYER_DETAIL_SHOW_MORE_INFO__
    STR_ID_AUDPLY_DETAIL_CHANNEL,
    STR_ID_AUDPLY_DETAIL_QUALITY,
    STR_ID_AUDPLY_DETAIL_MONO,
    STR_ID_AUDPLY_DETAIL_STEREO,
#endif /* __MMI_AUDIO_PLAYER_DETAIL_SHOW_MORE_INFO__ */ 
    STR_ID_AUDPLY_FILENAME_TOO_LONG,
    STR_ID_AUDPLY_RING_TONGS_FULL,
    STR_ID_AUDPLY_CANNOT_UPDATE_LIST_DISK_FULL,
    STR_ID_AUDPLY_CANNOT_UPDATE_LIST_FS_FAIL,
    STR_ID_AUDPLY_FILE_IN_DIFFERENT_STORAGE,
    STR_ID_AUDPLY_LIST_EMPTY,
    STR_ID_AUDPLY_LIST_FULL,
    STR_ID_AUDPLY_OPEN_FILE_ERROR,
    STR_ID_AUDPLY_NO_CARD,
    STR_ID_AUDPLY_COMMAND_ERROR,
    STR_ID_AUDPLY_DEVICE_BUSY,
    STR_ID_AUDPLY_BAD_FORMAT,
    STR_ID_AUDPLY_INVALID_FORMAT,
    STR_ID_AUDPLY_NO_SPACE,
    STR_ID_AUDPLY_ERROR,
    STR_ID_AUDPLY_UNSUPPORTED_CHANNEL,
    STR_ID_AUDPLY_UNSUPPORTED_FREQ,
    STR_ID_AUDPLY_UNSUPPORTED_TYPE,
    STR_ID_AUDPLY_CANNOT_PAUSE,
    STR_ID_AUDPLY_PROCESSING,
    STR_ID_AUDPLY_UNSUPPORTED_SPEED,
    STR_ID_AUDPLY_NO_AUDIO_TRACK,
    STR_ID_AUDPLY_DECODER_NOT_SUPPORT,
    STR_ID_AUDPLY_NOT_SUPPORT_A2DP,
    STR_ID_AUDPLY_SPEED,
    STR_ID_AUDPLY_SPEED_NORMAL,
    STR_ID_AUDPLY_SPEED_FAST1,
    STR_ID_AUDPLY_SPEED_FAST2,
    STR_ID_AUDPLY_SPEED_SLOW2,
    STR_ID_AUDPLY_SPEED_SLOW1,
#ifdef __MMI_AUDIO_PLAYER_ON_SUBLCD__
    STR_ID_AUDPLY_SUB_OPTION_PLAYLIST,
    STR_ID_AUDPLY_SUB_OPTION_REPEAT_SETTING,
    STR_ID_AUDPLY_SUB_OPTION_REPEAT_OFF,
    STR_ID_AUDPLY_SUB_OPTION_REPEAT_ONCE,
    STR_ID_AUDPLY_SUB_OPTION_REPEAT_ALL,
    STR_ID_AUDPLY_SUB_OPTION_SHUFFLE_SETTINGS,
    STR_ID_AUDPLY_SUB_OPTION_EXIT,
    STR_ID_AUDPLY_SETTINGS_SHUFFLE_ON,
    STR_ID_AUDPLY_SETTINGS_SHUFFLE_OFF,
    STR_ID_AUDPLY_SUB_ERROR,
#endif
#if defined(__MMI_A2DP_SUPPORT__) && defined(__MMI_AUDIO_EQUALIZER__)
    STR_ID_AUDPLY_A2DP_BLOCK_EQUALIZER,
#endif
#if defined(__MMI_A2DP_SUPPORT__) && defined(__MMI_AUDIO_EQUALIZER__) && defined(__MMI_AUDIO_PLAYER_A2DP_BLOCK_SPECTRUM__)
    STR_ID_AUDPLY_A2DP_BLOCK_EQUALIZER_SPCTRUM,
#endif
#if defined(__MMI_BT_MTK_SUPPORT__) && defined(__MMI_A2DP_SUPPORT__)
    STR_ID_AUDPLY_SAP_BLOCK_A2DP,
#endif
    STR_ID_AUDPLY_STOP_FMR,
    NO_OF_STR_ID_AUDPLY
} audply_str_id_enum;

typedef enum
{
    IMG_ID_AUDPLY_BASE = AUDIO_PLAYER_BASE + 1,
    IMG_ID_AUDPLY_ICON,
    IMG_ID_AUDPLY_SETTINGS_LIST_AUTO_GEN,
    IMG_ID_AUDPLY_SETTINGS_PREFER_LIST,
    IMG_ID_AUDPLY_SETTINGS_SKIN,
    IMG_ID_AUDPLY_SETTINGS_REPEAT,
    IMG_ID_AUDPLY_SETTINGS_SHUFFLE,
#ifndef __MMI_AUDIO_PLAYER_ON_SUBLCD__    
    IMG_ID_AUDPLY_SETTINGS_BACKGROUND_PLAY,
#endif
    IMG_ID_AUDPLY_SETTINGS_SPEED,
#ifdef __MMI_AUDIO_SPECTRUM_DISPLAY__  
    IMG_ID_AUDPLY_SETTINGS_SPECTRUM_DISPLAY_STYLE,
#endif 
#ifdef __MMI_AUDIO_PLAYER_LYRIC_DISPLAY__
    IMG_ID_AUDPLY_SETTINGS_LYRICS_DISPLAY_STYLE,
#endif
    /* play animation gif */
    IMG_ID_AUDPLY_PLAY_ANIMATION,
    IMG_ID_AUDPLY_STOP_ANIMATION,
    /* detail */
    IMG_ID_AUDPLY_DETAIL_FILE,
    IMG_ID_AUDPLY_DETAIL_TIME,
    IMG_ID_AUDPLY_DETAIL_TITLE,
    IMG_ID_AUDPLY_DETAIL_ARTIST,
    IMG_ID_AUDPLY_DETAIL_ALBUM,
    IMG_ID_AUDPLY_DETAIL_GENRE,
    IMG_ID_AUDPLY_DETAIL_YEAR,
#ifdef __MMI_AUDIO_PLAYER_DETAIL_SHOW_MORE_INFO__
    IMG_ID_AUDPLY_DETAIL_FILENAME,
    IMG_ID_AUDPLY_DETAIL_CHANNEL,
    IMG_ID_AUDPLY_DETAIL_QUALITY,
#endif /* __MMI_AUDIO_PLAYER_DETAIL_SHOW_MORE_INFO__ */ 
    /* audio file types */
    IMG_ID_AUDPLY_FILE_WAV_ICON,
    IMG_ID_AUDPLY_FILE_AMR_ICON,
    IMG_ID_AUDPLY_FILE_AUD_ICON,
    IMG_ID_AUDPLY_FILE_AAC_ICON,
    IMG_ID_AUDPLY_FILE_MID_ICON,
    IMG_ID_AUDPLY_FILE_IMY_ICON,
    IMG_ID_AUDPLY_FILE_AWB_ICON,
    IMG_ID_AUDPLY_FILE_AIF_ICON,
    IMG_ID_AUDPLY_FILE_AU_ICON,
    IMG_ID_AUDPLY_FILE_SND_ICON,
    IMG_ID_AUDPLY_FILE_M4A_ICON,
    IMG_ID_AUDPLY_FILE_MMF_ICON,
    IMG_ID_AUDPLY_FILE_WMA_ICON,
    IMG_ID_AUDPLY_FILE_3GP_ICON,
    IMG_ID_AUDPLY_FILE_MP4_ICON,
    IMG_ID_AUDPLY_FILE_UNKNOWN_ICON,
    /*IMG_ID_AUDPLY_FILE_ODF_ICON, replace with image id from file manager*/
    /* skin 1 */
    IMG_ID_AUDPLY_MAIN_SKIN1_BASE,
    IMG_ID_AUDPLY_MAIN_SKIN1_BG,
    IMG_ID_AUDPLY_MAIN_SKIN1_PLAYLIST_PHONE_ICON,
    IMG_ID_AUDPLY_MAIN_SKIN1_PLAYLIST_CARD_ICON,
    IMG_ID_AUDPLY_MAIN_SKIN1_VOLUME_INDICATOR,
    IMG_ID_AUDPLY_MAIN_SKIN1_PROGRESSBAR,
    IMG_ID_AUDPLY_MAIN_SKIN1_PROGRESSBAR_FAIL,
    IMG_ID_AUDPLY_MAIN_SKIN1_PREV_ON,
    IMG_ID_AUDPLY_MAIN_SKIN1_PREV_OFF,
    IMG_ID_AUDPLY_MAIN_SKIN1_PREV_DISABLED,
    IMG_ID_AUDPLY_MAIN_SKIN1_PREV_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN1_NEXT_ON,
    IMG_ID_AUDPLY_MAIN_SKIN1_NEXT_OFF,
    IMG_ID_AUDPLY_MAIN_SKIN1_NEXT_DISABLED,
    IMG_ID_AUDPLY_MAIN_SKIN1_NEXT_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN1_PLAY_ON,
    IMG_ID_AUDPLY_MAIN_SKIN1_PLAY_OFF,
    IMG_ID_AUDPLY_MAIN_SKIN1_PLAY_DISABLED,
    IMG_ID_AUDPLY_MAIN_SKIN1_PLAY_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN1_PAUSE_ON,
    IMG_ID_AUDPLY_MAIN_SKIN1_PAUSE_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN1_STOP_ON,
    IMG_ID_AUDPLY_MAIN_SKIN1_STOP_OFF,
    IMG_ID_AUDPLY_MAIN_SKIN1_STOP_DISABLED,
    IMG_ID_AUDPLY_MAIN_SKIN1_STOP_DOWN,
#ifdef __MMI_AUDIO_PLAYER_ANIMATION__
    IMG_ID_AUDPLY_MAIN_SKIN1_ANIMATION,
#endif 
#ifdef __MMI_AUDIO_PLAYER_SKIN_SHOW_REPEAT_SHUFFLE__
    IMG_ID_AUDPLY_MAIN_SKIN1_REPEAT_OFF_UP,
    IMG_ID_AUDPLY_MAIN_SKIN1_REPEAT_ALL_UP,
    IMG_ID_AUDPLY_MAIN_SKIN1_REPEAT_ONE_UP,
#ifdef __MMI_TOUCH_SCREEN__
    IMG_ID_AUDPLY_MAIN_SKIN1_REPEAT_OFF_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN1_REPEAT_ALL_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN1_REPEAT_ONE_DOWN,
#endif /*__MMI_TOUCH_SCREEN__*/
    IMG_ID_AUDPLY_MAIN_SKIN1_SHUFFLE_OFF_UP,
    IMG_ID_AUDPLY_MAIN_SKIN1_SHUFFLE_ON_UP,
#ifdef __MMI_TOUCH_SCREEN__
    IMG_ID_AUDPLY_MAIN_SKIN1_SHUFFLE_OFF_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN1_SHUFFLE_ON_DOWN,
#endif /*__MMI_TOUCH_SCREEN__*/
#endif /* __MMI_AUDIO_PLAYER_SKIN_SHOW_REPEAT_SHUFFLE__ */ 
    IMG_ID_AUDPLY_MAIN_SKIN1_VOLUME_INC_UP,
    IMG_ID_AUDPLY_MAIN_SKIN1_VOLUME_INC_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN1_VOLUME_DEC_UP,
    IMG_ID_AUDPLY_MAIN_SKIN1_VOLUME_DEC_DOWN,
#ifdef __MMI_TOUCH_SCREEN__
    IMG_ID_AUDPLY_MAIN_SKIN1_SETTING_UP,
    IMG_ID_AUDPLY_MAIN_SKIN1_SETTING_DOWN,
#endif /* __MMI_TOUCH_SCREEN__ */ 
#ifndef __MMI_SLIM_AUDIO_PLAYER__
    /* skin 2 */
    IMG_ID_AUDPLY_MAIN_SKIN2_BASE,
    IMG_ID_AUDPLY_MAIN_SKIN2_BG,
    IMG_ID_AUDPLY_MAIN_SKIN2_PLAYLIST_PHONE_ICON,
    IMG_ID_AUDPLY_MAIN_SKIN2_PLAYLIST_CARD_ICON,
    IMG_ID_AUDPLY_MAIN_SKIN2_VOLUME_INDICATOR,
    IMG_ID_AUDPLY_MAIN_SKIN2_PROGRESSBAR,
    IMG_ID_AUDPLY_MAIN_SKIN2_PROGRESSBAR_FAIL,
    IMG_ID_AUDPLY_MAIN_SKIN2_PREV_ON,
    IMG_ID_AUDPLY_MAIN_SKIN2_PREV_OFF,
    IMG_ID_AUDPLY_MAIN_SKIN2_PREV_DISABLED,
    IMG_ID_AUDPLY_MAIN_SKIN2_PREV_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN2_NEXT_ON,
    IMG_ID_AUDPLY_MAIN_SKIN2_NEXT_OFF,
    IMG_ID_AUDPLY_MAIN_SKIN2_NEXT_DISABLED,
    IMG_ID_AUDPLY_MAIN_SKIN2_NEXT_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN2_PLAY_ON,
    IMG_ID_AUDPLY_MAIN_SKIN2_PLAY_OFF,
    IMG_ID_AUDPLY_MAIN_SKIN2_PLAY_DISABLED,
    IMG_ID_AUDPLY_MAIN_SKIN2_PLAY_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN2_PAUSE_ON,
    IMG_ID_AUDPLY_MAIN_SKIN2_PAUSE_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN2_STOP_ON,
    IMG_ID_AUDPLY_MAIN_SKIN2_STOP_OFF,
    IMG_ID_AUDPLY_MAIN_SKIN2_STOP_DISABLED,
    IMG_ID_AUDPLY_MAIN_SKIN2_STOP_DOWN,
#ifdef __MMI_AUDIO_PLAYER_ANIMATION__
    IMG_ID_AUDPLY_MAIN_SKIN2_ANIMATION,
#endif 
#ifdef __MMI_AUDIO_PLAYER_SKIN_SHOW_REPEAT_SHUFFLE__
    IMG_ID_AUDPLY_MAIN_SKIN2_REPEAT_OFF_UP,
    IMG_ID_AUDPLY_MAIN_SKIN2_REPEAT_ALL_UP,
    IMG_ID_AUDPLY_MAIN_SKIN2_REPEAT_ONE_UP,
#ifdef __MMI_TOUCH_SCREEN__
    IMG_ID_AUDPLY_MAIN_SKIN2_REPEAT_OFF_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN2_REPEAT_ALL_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN2_REPEAT_ONE_DOWN,
#endif /*__MMI_TOUCH_SCREEN__*/
    IMG_ID_AUDPLY_MAIN_SKIN2_SHUFFLE_OFF_UP,
    IMG_ID_AUDPLY_MAIN_SKIN2_SHUFFLE_ON_UP,
#ifdef __MMI_TOUCH_SCREEN__
    IMG_ID_AUDPLY_MAIN_SKIN2_SHUFFLE_OFF_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN2_SHUFFLE_ON_DOWN,
#endif /*__MMI_TOUCH_SCREEN__*/
#endif /* __MMI_AUDIO_PLAYER_SKIN_SHOW_REPEAT_SHUFFLE__ */ 
    IMG_ID_AUDPLY_MAIN_SKIN2_VOLUME_INC_UP,
    IMG_ID_AUDPLY_MAIN_SKIN2_VOLUME_INC_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN2_VOLUME_DEC_UP,
    IMG_ID_AUDPLY_MAIN_SKIN2_VOLUME_DEC_DOWN,
#ifdef __MMI_TOUCH_SCREEN__
    IMG_ID_AUDPLY_MAIN_SKIN2_SETTING_UP,
    IMG_ID_AUDPLY_MAIN_SKIN2_SETTING_DOWN,
#endif /* __MMI_TOUCH_SCREEN__ */ 
    /* skin 3 */
    IMG_ID_AUDPLY_MAIN_SKIN3_BASE,
    IMG_ID_AUDPLY_MAIN_SKIN3_BG,
    IMG_ID_AUDPLY_MAIN_SKIN3_PLAYLIST_PHONE_ICON,
    IMG_ID_AUDPLY_MAIN_SKIN3_PLAYLIST_CARD_ICON,
    IMG_ID_AUDPLY_MAIN_SKIN3_VOLUME_INDICATOR,
    IMG_ID_AUDPLY_MAIN_SKIN3_PROGRESSBAR,
    IMG_ID_AUDPLY_MAIN_SKIN3_PROGRESSBAR_FAIL,
    IMG_ID_AUDPLY_MAIN_SKIN3_PREV_ON,
    IMG_ID_AUDPLY_MAIN_SKIN3_PREV_OFF,
    IMG_ID_AUDPLY_MAIN_SKIN3_PREV_DISABLED,
    IMG_ID_AUDPLY_MAIN_SKIN3_PREV_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN3_NEXT_ON,
    IMG_ID_AUDPLY_MAIN_SKIN3_NEXT_OFF,
    IMG_ID_AUDPLY_MAIN_SKIN3_NEXT_DISABLED,
    IMG_ID_AUDPLY_MAIN_SKIN3_NEXT_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN3_PLAY_ON,
    IMG_ID_AUDPLY_MAIN_SKIN3_PLAY_OFF,
    IMG_ID_AUDPLY_MAIN_SKIN3_PLAY_DISABLED,
    IMG_ID_AUDPLY_MAIN_SKIN3_PLAY_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN3_PAUSE_ON,
    IMG_ID_AUDPLY_MAIN_SKIN3_PAUSE_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN3_STOP_ON,
    IMG_ID_AUDPLY_MAIN_SKIN3_STOP_OFF,
    IMG_ID_AUDPLY_MAIN_SKIN3_STOP_DISABLED,
    IMG_ID_AUDPLY_MAIN_SKIN3_STOP_DOWN,
#ifdef __MMI_AUDIO_PLAYER_ANIMATION__
    IMG_ID_AUDPLY_MAIN_SKIN3_ANIMATION,
#endif 
#ifdef __MMI_AUDIO_PLAYER_SKIN_SHOW_REPEAT_SHUFFLE__
    IMG_ID_AUDPLY_MAIN_SKIN3_REPEAT_OFF_UP,
    IMG_ID_AUDPLY_MAIN_SKIN3_REPEAT_ALL_UP,
    IMG_ID_AUDPLY_MAIN_SKIN3_REPEAT_ONE_UP,
#ifdef __MMI_TOUCH_SCREEN__
    IMG_ID_AUDPLY_MAIN_SKIN3_REPEAT_OFF_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN3_REPEAT_ALL_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN3_REPEAT_ONE_DOWN,
#endif /*__MMI_TOUCH_SCREEN__*/
    IMG_ID_AUDPLY_MAIN_SKIN3_SHUFFLE_OFF_UP,
    IMG_ID_AUDPLY_MAIN_SKIN3_SHUFFLE_ON_UP,
#ifdef __MMI_TOUCH_SCREEN__
    IMG_ID_AUDPLY_MAIN_SKIN3_SHUFFLE_OFF_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN3_SHUFFLE_ON_DOWN,
#endif /*__MMI_TOUCH_SCREEN__*/
#endif /* __MMI_AUDIO_PLAYER_SKIN_SHOW_REPEAT_SHUFFLE__ */ 
    IMG_ID_AUDPLY_MAIN_SKIN3_VOLUME_INC_UP,
    IMG_ID_AUDPLY_MAIN_SKIN3_VOLUME_INC_DOWN,
    IMG_ID_AUDPLY_MAIN_SKIN3_VOLUME_DEC_UP,
    IMG_ID_AUDPLY_MAIN_SKIN3_VOLUME_DEC_DOWN,
#ifdef __MMI_TOUCH_SCREEN__
    IMG_ID_AUDPLY_MAIN_SKIN3_SETTING_UP,
    IMG_ID_AUDPLY_MAIN_SKIN3_SETTING_DOWN,
#endif /* __MMI_TOUCH_SCREEN__ */ 
#endif /* __MMI_SLIM_AUDIO_PLAYER__ */ 
    NO_OF_AUDIO_PLAYER_ICON
} audply_img_id_enum;

#ifdef __MMI_AUDIO_PLAYER_ON_SUBLCD__ 
typedef enum
{
    IMG_ID_AUDPLY_SUB_SKIN_BASE = NO_OF_AUDIO_PLAYER_ICON+1,
    IMG_ID_AUDPLY_SUB_SKIN_BG,
    IMG_ID_AUDPLY_SUB_SKIN_PLAYLIST_PHONE_ICON,
    IMG_ID_AUDPLY_SUB_SKIN_PLAYLIST_CARD_ICON,
    IMG_ID_AUDPLY_SUB_SKIN_VOLUME_INDICATOR,
    IMG_ID_AUDPLY_SUB_SKIN_PREV_ON,
    IMG_ID_AUDPLY_SUB_SKIN_PREV_OFF,
    IMG_ID_AUDPLY_SUB_SKIN_PREV_DISABLED,
    IMG_ID_AUDPLY_SUB_SKIN_PREV_DOWN,
    IMG_ID_AUDPLY_SUB_SKIN_NEXT_ON,
    IMG_ID_AUDPLY_SUB_SKIN_NEXT_OFF,
    IMG_ID_AUDPLY_SUB_SKIN_NEXT_DISABLED,
    IMG_ID_AUDPLY_SUB_SKIN_NEXT_DOWN,
    IMG_ID_AUDPLY_SUB_SKIN_PLAY_ON,
    IMG_ID_AUDPLY_SUB_SKIN_PLAY_OFF,
    IMG_ID_AUDPLY_SUB_SKIN_PLAY_DISABLED,
    IMG_ID_AUDPLY_SUB_SKIN_PLAY_DOWN,
    IMG_ID_AUDPLY_SUB_SKIN_PAUSE_ON,
    IMG_ID_AUDPLY_SUB_SKIN_PAUSE_DOWN,
    IMG_ID_AUDPLY_SUB_SKIN_ANIMATION,
    IMG_ID_AUDPLY_SUB_SKIN_REPEAT_OFF,
    IMG_ID_AUDPLY_SUB_SKIN_REPEAT_ALL,
    IMG_ID_AUDPLY_SUB_SKIN_REPEAT_ONE,
    IMG_ID_AUDPLY_SUB_SKIN_SHUFFLE_OFF,
    IMG_ID_AUDPLY_SUB_SKIN_SHUFFLE_ON,
    IMG_ID_AUDPLY_SUB_SKIN_REPEAT_SELECTED,
    IMG_ID_AUDPLY_SUB_SKIN_REPEAT_NOT_SELECTED,
    IMG_ID_AUDPLY_SUB_SKIN_REFRESH_LIST,
    IMG_ID_AUDPLY_SUB_SKIN_ERROR,
NO_OF_AUDIO_PLAYER_SUB_ICON
}audply_img_id_enum_sub;
#endif

typedef enum
{
    SCR_ID_AUDPLY_BASE = AUDIO_PLAYER_BASE + 1,
    SCR_ID_AUDPLY_MAIN,
    SCR_ID_AUDPLY_PLAYLIST,
    SCR_ID_AUDPLY_OPTION,
    SCR_ID_AUDPLY_SETTINGS,
    SCR_ID_AUDPLY_PLAYER_SETTINGS,
    SCR_ID_AUDPLY_DISPLAY_SETTINGS,
    SCR_ID_AUDPLY_SOUND_EFFECT_SETTINGS,
    SCR_ID_AUDPLY_BLUETOOTH_SETTINGS,
    SCR_ID_AUDPLY_BT_A2DP_HEADSET_LIST,
    SCR_ID_AUDPLY_DETAIL,
    SCR_ID_AUDPLY_REMOVE_CONFIRM,
    SCR_ID_AUDPLY_REMOVE_ALL_CONFIRM,
    SCR_ID_AUDPLY_PLAY_ANIMATION,
    SCR_ID_AUDPLY_ADD_FILES,
    SCR_ID_AUDPLY_REFRESH_LIST,
    SCR_ID_AUDPLY_MAIN_SUBLCD,
    SCR_ID_AUDPLY_OPTION_SUBLCD,
    SCR_ID_AUDPLY_PLAYLIST_SUBLCD,
    SCR_ID_AUDPLY_EQUALIZER_SETTING_SUBLCD,
    SCR_ID_AUDPLY_REPEAT_SETTING_SUBLCD,
    SCR_ID_AUDPLY_3D_EFFECT_SETTING_SUBLCD,
    NO_OF_SCR_AUDPLY
} audply_scr_id_enum;

#else /* __MMI_AUDIO_PLAYER__ */ 

typedef enum
{
    STR_ID_AUDPLY_BASE = AUDIO_PLAYER_BASE + 1,
    STR_ID_AUDPLY_TITLE,
    STR_ID_AUDPLY_LIST_FULL,
    STR_ID_AUDPLY_OPEN_FILE_ERROR,
    STR_ID_AUDPLY_NO_CARD,
    STR_ID_AUDPLY_COMMAND_ERROR,
    STR_ID_AUDPLY_DEVICE_BUSY,
    STR_ID_AUDPLY_BAD_FORMAT,
    STR_ID_AUDPLY_INVALID_FORMAT,
    STR_ID_AUDPLY_NO_SPACE,
    STR_ID_AUDPLY_ERROR,
    STR_ID_AUDPLY_UNSUPPORTED_CHANNEL,
    STR_ID_AUDPLY_UNSUPPORTED_FREQ,
    STR_ID_AUDPLY_UNSUPPORTED_TYPE,
    STR_ID_AUDPLY_UNSUPPORTED_SPEED,
    STR_ID_AUDPLY_NO_AUDIO_TRACK,
    STR_ID_AUDPLY_DECODER_NOT_SUPPORT,
    NO_OF_STR_ID_AUDPLY
} audply_str_id_enum;

typedef enum
{
    IMG_ID_AUDPLY_BASE = AUDIO_PLAYER_BASE + 1,
    /* play animation gif */
    IMG_ID_AUDPLY_PLAY_ANIMATION,
    IMG_ID_AUDPLY_STOP_ANIMATION,

    NO_OF_AUDIO_PLAYER_ICON
} audply_img_id_enum;

typedef enum
{
    SCR_ID_AUDPLY_BASE = AUDIO_PLAYER_BASE + 1,
    SCR_ID_AUDPLY_PLAY_ANIMATION,

    NO_OF_SCR_AUDPLY
} audply_scr_id_enum;

#endif /* __MMI_AUDIO_PLAYER__ */
#endif /* AUDIO_PLAYER_RES_DEF_H */ 

