/*
 * Generated by Drv CodeGen for MT6225. Copyright MediaTek Inc. (C) 2006.
 * Tue Aug 12 19:29:24 2008
 * Do Not Modify the File.
 */

#ifdef __CUST_NEW__
#include "kal_release.h"
#include "adc.h"


const unsigned char ADC_VBAT = 0;
const unsigned char ADC_VISENSE = 1;
const unsigned char ADC_VCHARGER = 3;
const unsigned char ADC_ACCESSORYID = 5;
const unsigned char ADC_CHR_USB = 6;
const unsigned char ADC_VBATTMP = ADC_ERR_CHANNEL_NO;
const unsigned char ADC_PCBTMP = ADC_ERR_CHANNEL_NO;
const unsigned char ADC_OTG_VBUS = ADC_ERR_CHANNEL_NO;
const unsigned char ADC_RFTMP = ADC_ERR_CHANNEL_NO;


#endif /* __CUST_NEW__ */


