/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   VdoEdtDefs.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Defined the Resource IDs.
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/
#ifndef _VDO_EDT_DEF_H_
#define _VDO_EDT_DEF_H_

#include "MMIDatatype.h"

/* screen */
typedef enum
{
    SCR_ID_VDOEDT_APP = VDOEDT_BASE + 1,
    SCR_ID_VDOEDT_MAIN,
    SCR_ID_VDOEDT_MEDIA_PREVIEW,
    SCR_ID_VDOEDT_PLAY_OPTION,
    SCR_ID_VDOEDT_FILENAME_EDITOR,
    SCR_ID_VDOEDT_FILENAME_EDITOR_OPTION,
    SCR_ID_VDOEDT_AUDIO_OPTION,
    SCR_ID_VDOEDT_AUDIO_SELECT,
    SCR_ID_VDOEDT_AUDIO_PLAY,
    SCR_ID_VDOEDT_VIDEO_OPTION,
    SCR_ID_VDOEDT_VIDEO_EDIT_EFFECT,
    SCR_ID_VDOEDT_VIDEO_CUT,
    SCR_ID_VDOEDT_IMAGE_INSERT_OPTION,
    SCR_ID_VDOEDT_IMAGE_DURATION,
    SCR_ID_VDOEDT_FRAME_EDIT,
    SCR_ID_VDOEDT_FRAME_EDIT_OPTION,
    SCR_ID_VDOEDT_FRAME_PREVIEW,
    SCR_ID_VDOEDT_FRAME_TEXT_EDITOR,
    SCR_ID_VDOEDT_FRAME_TEXT_EDITOR_OPTION,
    SCR_ID_VDOEDT_FRAME_TEXT_PROPERTY,
    SCR_ID_VDOEDT_IMAGE_COLOR_SEL,
    SCR_ID_VDOEDT_EMPTY_OPION,
    SCR_ID_VDOEDT_DEFAULT_AUDIO_SELECT,
    SCR_ID_VDOEDT_ENCODE,
    SCR_ID_VDOEDT_SAVE_OPTION,
    SCR_ID_VDOEDT_NULL_SCREEN,

    SCR_ID_VDOEDT_TOTAL
} SCR_ID_VDOEDT_ENUM;
/* string */
typedef enum
{
    STR_ID_VDOEDT_APP = VDOEDT_BASE + 1,      /* app name */
    STR_ID_VDOEDT_PREVIEW,
    STR_ID_VDOEDT_NEW_W7E,
    STR_ID_VDOEDT_AUDIO,
    STR_ID_VDOEDT_SEL_FROM_FILE,
    STR_ID_VDOEDT_AUD_DEFAULT,
    STR_ID_VDOEDT_PLAY,
    STR_ID_VDOEDT_CHANGE,
    STR_ID_VDOEDT_REMOVE,
    STR_ID_VDOEDT_REMOVE_CONFIRM,
    STR_ID_VDOEDT_REMOV_SHOT,
    STR_ID_VDOEDT_REMOV_FRMTXT,
    STR_ID_VDOEDT_REMOV_AUD,
    STR_ID_VDOEDT_AUD1,
    STR_ID_VDOEDT_AUD2,
    STR_ID_VDOEDT_AUD3,
    STR_ID_VDOEDT_AUD4,
    STR_ID_VDOEDT_AUD5,
    STR_ID_VDOEDT_INS_VDO,
    STR_ID_VDOEDT_INS_IMG,
    STR_ID_VDOEDT_CUT_VDO,
    STR_ID_VDOEDT_FRAME,
    STR_ID_VDOEDT_DUR,
    STR_ID_VDOEDT_IMG_DUR_1,
    STR_ID_VDOEDT_IMG_DUR_2,
    STR_ID_VDOEDT_IMG_DUR_3,
    STR_ID_VDOEDT_IMG_DUR_4,
    STR_ID_VDOEDT_IMG_DUR_5,
    STR_ID_VDOEDT_LAST_FRAME,
    STR_ID_VDOEDT_FIRST_FRAME,
    STR_ID_VDOEDT_COLOR,
    STR_ID_VDOEDT_EFFECT,
    STR_ID_VDOEDT_EFFECT_IN,
    STR_ID_VDOEDT_EFFECT_OUT,
    STR_ID_VDOEDT_EFFECT_PLAY,
    STR_ID_VDOEDT_EFFECT_NONE,
    STR_ID_VDOEDT_EFFECT_FROM_BLACK,
    STR_ID_VDOEDT_EFFECT_FROM_WHITE,
    STR_ID_VDOEDT_EFFECT_2_BLACK,
    STR_ID_VDOEDT_EFFECT_2_WHITE,
    STR_ID_VDOEDT_EFFECT_GRAYSCALE,
    STR_ID_VDOEDT_EFFECT_SEPIA,
    STR_ID_VDOEDT_EFFECT_SEPIAGREEN,
    STR_ID_VDOEDT_EFFECT_SEPIABLUE,
    STR_ID_VDOEDT_EFFECT_COLORINV,
    STR_ID_VDOEDT_EFFECT_GRAYINV,
    STR_ID_VDOEDT_TXT,
    STR_ID_VDOEDT_FRAME_TXT,
    STR_ID_VDOEDT_FRAME_EDT,
    STR_ID_VDOEDT_TXT_COLOR,
    STR_ID_VDOEDT_TXT_POSITION,
    STR_ID_VDOEDT_TXT_SIZE,
    STR_ID_VDOEDT_PLZ_INS_VDO,
    STR_ID_VDOEDT_TXT_L,
    STR_ID_VDOEDT_TXT_M,
    STR_ID_VDOEDT_TXT_S,
    STR_ID_VDOEDT_TXT_ALIGN_TOP,
    STR_ID_VDOEDT_TXT_ALIGN_CEN,
    STR_ID_VDOEDT_TXT_ALIGN_BTM,
    STR_ID_VDOEDT_TXT_CHOOSE_FRM,
    STR_ID_VDOEDT_CREATE_DIR_FAIL,
    STR_ID_VDOEDT_ENCODING,
    STR_ID_VDOEDT_2_PHONE,
    STR_ID_VDOEDT_2_CARD,
    STR_ID_VDOEDT_EXIT,
    STR_ID_VDOEDT_EXIT_CONFIRM_MSG,
    STR_ID_VDOEDT_OUTPUT_VDO,
    STR_ID_VDOEDT_O7E_CNF,
    STR_ID_VDOEDT_NO_SAVE_SPACE,
    STR_ID_VDOEDT_INVALID_VDO,
    STR_ID_VDOEDT_FILE_NOT_FOUND,
    STR_ID_VDOEDT_ENC_FAILED,
    STR_ID_VDOEDT_WHITE,
    STR_ID_VDOEDT_BLACK,
    STR_ID_VDOEDT_EMPTY_STRING,
    STR_ID_VDOEDT_BAD_VDO_REMOVE_NOTIFY,
    STR_ID_VDOEDT_VDO_IS_TOO_SHORT,
    STR_ID_VDOEDT_UNABLE_TO_OVERWRITE,
    STR_ID_VDOEDT_ERR_TOO_SHORT,
    STR_ID_VDOEDT_ERR_TOO_LONG,
    STR_ID_VDOEDT_ERR_RESOLUTION,
    STR_ID_VDOEDT_ERR_UNSUP_FORMAT,

    STR_ID_VDOEDT_TOTAL
}STR_ID_VDOEDT_ENUM;

/* image  */
typedef enum
{
    IMG_ID_VDOEDT_MAIN_ICON = VDOEDT_BASE+1,
    IMG_ID_VDOEDT_EDIT_BG,
    IMG_ID_VDOEDT_CUT_BG,
    IMG_ID_VDOEDT_PROGRESS_BAR,
    IMG_ID_VDOEDT_PROGRESS_BAR_BG,
    IMG_ID_VDOEDT_D0,
    IMG_ID_VDOEDT_D1,
    IMG_ID_VDOEDT_D2,
    IMG_ID_VDOEDT_D3,
    IMG_ID_VDOEDT_D4,
    IMG_ID_VDOEDT_D5,
    IMG_ID_VDOEDT_D6,
    IMG_ID_VDOEDT_D7,
    IMG_ID_VDOEDT_D8,
    IMG_ID_VDOEDT_D9,
    IMG_ID_VDOEDT_D_COL,
    IMG_ID_VDOEDT_PLAY,
    IMG_ID_VDOEDT_PLAY_DOWN,
    IMG_ID_VDOEDT_FF,               /* seek fast forward */
    IMG_ID_VDOEDT_FF_DOWN,
    IMG_ID_VDOEDT_RW,               /* rewind */
    IMG_ID_VDOEDT_RW_DOWN,    
    IMG_ID_VDOEDT_EDITBAR_BG,
    IMG_ID_VDOEDT_EDITBAR_HILIGHT,
    IMG_ID_VDOEDT_STAT_EMPTY,
    IMG_ID_VDOEDT_AUDIO,
    IMG_ID_VDOEDT_FRAME,    
    IMG_ID_VDOEDT_FADE_IN,
    IMG_ID_VDOEDT_FADE_OUT,
    IMG_ID_VDOEDT_WHITE_IN,
    IMG_ID_VDOEDT_WHITE_OUT,
    IMG_ID_VDOEDT_CUT_IN,
    IMG_ID_VDOEDT_CUT_IN_DOWN,
    IMG_ID_VDOEDT_CUT_OUT,
    IMG_ID_VDOEDT_CUT_OUT_DOWN,
    IMG_ID_VDOEDT_CUT_IN_ICON,
    IMG_ID_VDOEDT_CUT_OUT_ICON,
    IMG_ID_VDOEDT_ARROW_L,
    IMG_ID_VDOEDT_ARROW_L_DOWN,
    IMG_ID_VDOEDT_ARROW_L_DISABLE,
    IMG_ID_VDOEDT_ARROW_R,
    IMG_ID_VDOEDT_ARROW_R_DOWN,
    IMG_ID_VDOEDT_ARROW_R_DISABLE,
    IMG_ID_VDOEDT_CUT_BAR_BG,
    IMG_ID_VDOEDT_CUT_BAR,
    IMG_ID_VDOEDT_CUT_BAR_PROGRESS,
    IMG_ID_VDOEDT_FRAME1,
    IMG_ID_VDOEDT_FRAME2,
    IMG_ID_VDOEDT_FRAME3,
    IMG_ID_VDOEDT_FRAME4,
    IMG_ID_VDOEDT_FRAME5,
    IMG_ID_VDOEDT_VIEWER,
    IMG_ID_VDOEDT_FRM_BAR,
    IMG_ID_VDOEDT_FRM_BAR_H,
    IMG_ID_VDOEDT_CBAR_H,
    IMG_ID_VDOEDT_FRMSEL_LAK,
    IMG_ID_VDOEDT_FRMSEL_LAK_D,
    IMG_ID_VDOEDT_FRMSEL_RAK,
    IMG_ID_VDOEDT_FRMSEL_RAK_D,
    IMG_ID_VDOEDT_STOP,
    IMG_ID_VDOEDT_STOP_DOWN,

    IMG_ID_VDOEDT_TOTAL
}IMG_ID_VDOEDT_ENUM;

typedef enum
{
    AUD_ID_VDOEDT_BASE = VDOEDT_BASE + 1,
    AUD_ID_VDOEDT_AUD1,
    AUD_ID_VDOEDT_AUD2,
    AUD_ID_VDOEDT_AUD3,
    AUD_ID_VDOEDT_AUD4,
    AUD_ID_VDOEDT_AUD5,
    AUD_ID_VDOEDT_SILENT,

    AUD_ID_VDOEDT_TOTAL
}AUD_ID_VDOEDT_ENUM;
 

#endif  /* _VDO_EDT_DEF_H_ */

