/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * EngineerModeResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file is intends for engineer mode resource ids defination
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

/* Main menu string IDs */
typedef enum
{
    EM_SCR_BASE = ENGINEER_MODE_BASE,
    EM_MAIN_MENU_SCR,
    EM_NETWORK_SETTING_MENU_SCR,
    EM_NETWORK_INFO_MENU_SCR,
    EM_NETWORK_PREFER_RAT_MENU_SCR,
    EM_NETWORK_CELL_LOCK_MENU_SCR,
    EM_NETWORK_NETWORK_EVENT_MENU_SCR,
    EM_NETWORK_NETWORK_EVENT_FILTER_SCR, 
    EM_NETWORK_NETWORK_EVENT_FILTER_SETTING_SCR, 
    EM_NETWORK_NETWORK_EVENT_SETTING_SCR,
    EM_NETWORK_NETWORK_EVENT_GROUP_SCR,
    EM_NETWORK_NETWORK_EVENT_SELECT_RING_SCR,
    EM_NETWORK_NETWORK_EVENT_UPDATE_SCR,
    
    EM_AUDIO_MENU_SCR,
    EM_AUD_RING_TONE_MENU_SCR,
    EM_AUD_SET_MODE_MENU_SCR,
    EM_AUD_NORMAL_MODE_MENU_SCR,
    EM_AUD_LOUDSP_MODE_MENU_SCR,
    EM_AUD_HEADSET_MODE_MENU_SCR,
    EM_AUD_SET_VOLUME_MENU_SCR,
    EM_AUD_FIR_MENU_SCR,
    EM_AUD_SPEECH_MENU_SCR,
    EM_AUD_KEY_TONE_MENU_SCR,
    EM_AUD_MELODY_MENU_SCR,
    EM_AUD_SIDE_TONE_MENU_SCR,
    EM_AUD_CALL_TONE_MENU_SCR,
    EM_AUD_SOUND_MENU_SCR,
    EM_AUD_MICROPHONE_MENU_SCR,
    EM_AUD_SPH_ENH_MAIN_SCR,
    EM_AUD_SPH_ENH_PARA_LIST_SCR,
    EM_AUD_PARAM_EDITOR_SCR,
    EM_AUD_16_LEVEL_VOLUME_SCR,
    EM_AUD_TV_OUT_SCR,
    EM_AUD_AUTO_VM_SETTING_SCR,
    EM_DEVICE_MENU_SCR,
    EM_DEV_DEFAULT_USB_APP_MENU_SCR,
    EM_DEV_SET_UART_MENU_SCR,
    EM_DEV_INLINE_CONFIG_UART_MENU_SCR,
    EM_DEV_SLEEPMODE_MENU_SCR,

    EM_DEV_DCMMODE_MENU_SCR,

    EM_DEV_UART_POWER_ONOFF_MENU_SCR,

    EM_GPRS_ACT_MENU_SCR,
    EM_GPRS_1ST_PDP_MENU_SCR,
    EM_GPRS_2ND_PDP_MENU_SCR,
    EM_GPRS_ACTIVATE_2ND_PDP_MENU_SCR,
    EM_GPRS_ACTIVATE_PDP_MENU_SCR,
    EM_GPRS_SEND_DATA_MENU_SCR,
    EM_GPRS_SEND_DATA_EDITOR_SCR,
    EM_BAND_SEL_MENU_SCR,
    EM_MISC_MENU_SCR,
    EM_WAP_MENU_SCR,
    EM_WAP_USER_AGENT_MENU_SCR,
    EM_WAP_ACCEPT_HEADER_MENU_SCR,
    EM_WAP_ENABLE_DEBUG_MENU_SCR,
    EM_WAP_OFFLINE_PAGE_MENU_SCR,
    EM_WAP_MMS_VERSION_MENU_SCR,
    EM_POWER_ON_DURATION_MENU_SCR,
    EM_AUTO_TEST_REMOVE_MENU_SCR,
    EM_AUTO_TEST_ENTER_PRIORITY_MENU_SCR,
    EM_AUTO_TEST_CHANGE_PRIORITY_MENU_SCR,
    EM_AUTO_TEST_ADD_MENU_SCR,
    EM_AUTO_TEST_SETTING_MENU_SCR,
    EM_AUTO_TEST_OPTIONS_MENU_SCR,
    EM_PWR_DOWN_CONTROL_MENU_SCR,
    EM_SW_PATCH_MENU_SCR,
    EM_SERIAL_PORT_EN_MENU_SCR,
    EM_DEBUG_INFO_SCR,
    EM_LAST_EXCEPTION_SCR,
    EM_SYS_STATS_SCR,
    EM_WRITE_SYS_STATS_SCR,
    EM_SAVING_STAT_PWROFF_SCR,
    EM_SOCKET_MENU_SCR,
    EM_SOCKET_DNS_INPUT_SCR,
    EM_SOCKET_DNS_OPTION_SCR,
    EM_SOCKET_HTTP_INPUT_SCR,
    EM_SOCKET_HTTP_OPTION_SCR,
    EM_SOCKET_ECHO_INPUT_SCR,
    EM_SOCKET_DATE_INPUT_SCR,

    /* BEGIN OF IPERF */
    EM_SOCKET_IPERF_SETTING_SCR,
    EM_SOCKET_IPERF_PROT_SETTING_SCR,
    EM_SOCKET_IPERF_REPORT_SCR,
    EM_SOCKET_IPERF_PROGRESSING_SCR,
    /* END OF IPERF */

    EM_SOCKET_ECHO_STRING_INPUT_SCR,
    EM_SOCKET_TRACERT_PROCESS_SCR,
    EM_SOCKET_PROGRESS_SCR,
    EM_SOCKET_RESULT_SCR,
    EM_TOUCHSCREEN_TEST_SCR,
    EM_TOUCHSCREEN_TEST_OPTION_SCR,
    EM_TOUCHSCREEN_TEST_STATISTICS_SCR,
    EM_MMI_DEBUG_SCR,
    EM_MEMORY_DUMP_SCR,
    EM_FRM_PROFILING_SCR,

    /* UI Bench mark */
    EM_UI_BENCHMARK_PROCESSING_SCR,
    EM_UI_BENCHMARK_RESULT_SCR,

    /* Device */
    EM_DEV_LCD_EDITOR_SCR_ID,
    EM_DEV_GPIO_SCR_ID,
    EM_DEV_GPIO_LIST_SCR_ID,
    EM_DEV_GPIO_EDITOR_SCR_ID,
    EM_DEV_PWM_EDITOR_SCR_ID,
    EM_DEV_HW_LEVEL_EDITOR_SCR_ID,

    EM_DEV_EXT_CAMERA_SCR_ID,
    EM_DEV_EXT_CAMERA_WRITE_SCR_ID,
    EM_DEV_EXT_CAMERA_READ_SCR_ID,

    EM_DEV_GPIO_VIEWER_SCR_ID,
    EM_DEV_PWM_VIEWER_SCR_ID,

    /* Device USB */
    EM_DEV_USB_SCR_ID,

    /* GPRS ACT */
    EM_GPRS_PING_SCR_ID,

    /* DBG Trace */
    SCR_ID_EM_FS_TRACE,

    /* Bluetooth */
    EM_BT_SCR_ID,
    
    EM_BT_GENERNAL_TEST_SCR_ID,
    EM_BT_GET_CHIP_VERSION_SCR_ID,
    
    EM_BT_LOOKBACK_SCR_ID,
    EM_BT_PROGRESS_SCR,

    /* Cell Reselection */
    EM_MISC_CELL_RESELECTION_SCR_ID,

    /* MT6223 Debug Mode */
    EM_MISC_MT6223_DEBUG_MODE_SCR_ID,

    /* LSD Slower */
    EM_MISC_LSD_SLOWER_SCR_ID,
    
    EM_SET_SWDBG_SCR,

    EM_DEV_PMIC_6318_SCR,
    EM_DEV_PMIC_6318_REGISTER_EDITOR_SCR,
    EM_DEV_PMIC_6318_REGISTER_VIEWER_SCR,

    /* Charger Status */
    EM_DEV_PMIC_6318_CHARGER_STATUS_SCR,
    /* Set Charger */
    EM_DEV_PMIC_6318_SET_CHARGER_SCR,
    EM_DEV_PMIC_6318_SET_CHARGER_CURRENT_SCR,
    /* RGB LED */
    EM_DEV_PMIC_6318_RGB_LED_SCR,
    EM_DEV_PMIC_6318_RGB_CURRENT_SCR,
    /* KP LED */
    EM_DEV_PMIC_6318_KP_LED_SCR,
    EM_DEV_PMIC_6318_KP_DUTY_OPT_SCR,
    EM_DEV_PMIC_6318_KP_DIM_CLK_SCR,
    EM_DEV_PMIC_6318_KP_PUMP_CURRENT_SCR,
    /* BL LED */
    EM_DEV_PMIC_6318_BL_LED_SCR,
    EM_DEV_PMIC_6318_BL_DUTY_OPT_SCR,
    EM_DEV_PMIC_6318_BL_DIM_CLK_SCR,
    /* Audio */
    EM_DEV_PMIC_6318_AUDIO_SCR,
    EM_DEV_PMIC_6318_AUDIO_SPK_GAIN_SCR,
    /* Misc */
    EM_DEV_PMIC_6318_MISC_SCR,
    /* LCM BL Setting */
    EM_DEV_PMIC_6318_LCM_BL_SETTING_SCR,

    /* TVOut */
    SCR_ID_EM_TVOUT_SETTING,
    SCR_ID_EM_TVOUT_SETTING_TUNNING,

    /* profiling */
    SCR_ID_EM_PROFILING,
    SCR_ID_EM_PROFILING_MULTIMEDIA,
    SCR_ID_EM_PROFILING_AUTO_PLAY_FOLDER,
    SCR_ID_EM_PROFILING_AUTO_PLAY,
    SCR_ID_EM_PROFILING_VDOREC_PLAY,
    SCR_ID_EM_PROFILING_VDOPLY_PLAY,
    SCR_ID_EM_PROFILING_CAMERA_PLAY,
    SCR_ID_EM_PROFILING_VDOPLY_FILE_SEL,
    SCR_ID_EM_PROFILING_VDOREC_OPTION,
    SCR_ID_EM_PROFILING_VDOPLY_OPTION,
    SCR_ID_EM_PROFILING_CAMERA_OPTION,
    SCR_ID_EM_PROFILING_VDOREC_SETTING,
    SCR_ID_EM_PROFILING_VDOPLY_SETTING,
    SCR_ID_EM_PROFILING_CAMERA_SETTING,
    SCR_ID_EM_PROFILING_IMGDEC_OPTION,
    SCR_ID_EM_PROFILING_IMGDEC_GEN_DISP,
    SCR_ID_EM_PROFILING_IMGDEC_FULL_DISP,

    /* RF Test Tool */
    EM_RF_TEST_TOOL_SCR,
    /* GSM */
    EM_RF_TEST_GSM_SCR,
    /* GSM TX */
    EM_RF_TEST_GSM_TX_TEST_SCR,
    EM_RF_TEST_GSM_TX_TEST_DONE_SCR,
    /* GSM RX */
    EM_RF_TEST_GSM_RX_TEST_SCR,
    EM_RF_TEST_GSM_RX_TEST_DONE_SCR,
    /* GSM Power Scan */
    EM_RF_TEST_GSM_POWER_SCAN_SCR,
    EM_RF_TEST_GSM_POWER_SCAN_RESULT_SCR,
    /* WiFi */
    EM_RF_TEST_WIFI_SCR,
    /* WiFi TX */
    EM_RF_TEST_WIFI_TX_TEST_SCR,
    EM_RF_TEST_WIFI_TX_DAC_OFFSET_SCR,
    EM_RF_TEST_WIFI_TX_OUTPUT_POWER_SCR,
    EM_RF_TEST_WIFI_TX_OUTPUT_POWER_DONE_SCR,
    EM_RF_TEST_WIFI_TX_CARRIER_SUPP_SCR,
    EM_RF_TEST_WIFI_TX_CARRIER_SUPP_DONE_SCR,
    EM_RF_TEST_WIFI_TX_LOCAL_FREQ_SCR,
    EM_RF_TEST_WIFI_TX_LOCAL_FREQ_DONE_SCR,
    EM_RF_TEST_WIFI_TX_CONT_PKT_TX_SCR,
    EM_RF_TEST_WIFI_TX_CONT_PKT_TX_DONE_SCR,
    /* WiFi RX */
    EM_RF_TEST_WIFI_CONT_PKT_RX_SCR,
    EM_RF_TEST_WIFI_CONT_PKT_RX_DONE_SCR,
    /* WiFi Power Save */
    EM_RF_TEST_WIFI_POWER_SAVE_SCR,
    EM_RF_TEST_WIFI_POWER_SAVE_DONE_SCR,
    /* WiFi Register */
    EM_RF_TEST_WIFI_REGISTER_ACCESS_SCR,
    EM_RF_TEST_WIFI_REGISTER_MCR_SCR,
    EM_RF_TEST_WIFI_REGISTER_MCR_DONE_SCR,
    EM_RF_TEST_WIFI_REGISTER_BBCR_SCR,
    EM_RF_TEST_WIFI_REGISTER_BBCR_DONE_SCR,
    EM_RF_TEST_WIFI_REGISTER_EEPROM_SCR,
    EM_RF_TEST_WIFI_REGISTER_EEPROM_DONE_SCR,

    EM_DEV_FM_RADIO_SCR_ID,
    EM_DEV_FM_RADIO_MONO_SCR_ID,
    EM_DEV_FM_RADIO_STEREO_SCR_ID,
    EM_DEV_FM_RADIO_RSSI_SCR_ID,
    EM_DEV_FM_RADIO_IF_COUNT_DELTA_SCR_ID,
    EM_DEV_FM_RADIO_RSSI_INFO_SCR_ID,

    EM_DEV_RTC_XOSC_SCR_ID,

    /* VOIP */
    EM_VOIP_SCR_ID,
    EM_VOIP_SETTINGS_SCR_ID,
    EM_VOIP_SIP_SUPPORTED_SCR_ID,
    EM_VOIP_SIP_REQUIRE_SCR_ID,
    
    /* VOIP Log */
    EM_VOIP_LOG_SCR_ID,
    EM_VOIP_LOG_SETTINGS_SCR_ID,
    EM_VOIP_LOG_OPTION_SCR_ID,
    EM_VOIP_LOG_VIEW_SCR_ID,
    EM_VOIP_LOG_DELETE_ANIMATION_SCR_ID,

    /* BT RF Test */
    EM_DEV_BT_RF_TEST_SCR_ID,
    EM_DEV_BT_RF_TEST_TXRX_SCR_ID,
    
    EM_DEV_BT_RF_TEST_BD_ADDR_SCR_ID,
    EM_DEV_BT_RF_TEST_TESTING_SCR_ID,
    

    EM_SCR_END
} EM_SCR_IDS;

typedef enum
{
    ENGINEER_MODE_STR_BASE = ENGINEER_MODE_BASE,
    ENGINEER_MODE_TEXT,
    EM_SET_LSK_TEXT,
    //EM_TOGGLE_LSK_TEXT,

    EM_NOTICE_WARNING_TEXT,
    EM_NOTICE_SUCCESS_TEXT,

    /* Lisen 09062005 */
    EM_NOTICE_SUCCESS_REBOOT_TEXT,
    EM_UPDATE_TITLE_TEXT,
    EM_UPDATE_QUERY_TEXT,
    EM_UPDATE_ERROR_TEXT,
    EM_UPDATE_SUCCESS_TEXT,

    EM_STR_GPIO_EDITOR,
    EM_STR_GPO_EDITOR,
    EM_STR_GPIO_MODE,
    EM_STR_GPIO_DIRECTION,
    EM_STR_GPIO_LEVEL,

    EM_STR_EXT_CAMERA_TEXT,
    EM_STR_EXT_CAMERA_WRITE_TEXT,
    EM_STR_EXT_CAMERA_READ_TEXT,
    EM_STR_EXT_CAMERA_COMMAND_TEXT,
    EM_STR_EXT_CAMERA_PARA_TEXT,

    EM_STR_PWM_EDITOR,
    EM_STR_PWM_FREQUENCY,
    EM_STR_PWM_DUTY,
    EM_STR_PWM_LEVEL,
    EM_STR_PWNDOWN_CTRL_PDN_CON0,
    EM_STR_PWNDOWN_CTRL_PDN_CON1,
    EM_STR_PWNDOWN_CTRL_PDN_CON2,
    EM_STR_PWNDOWN_CTRL_PDN_CON3,
    EM_STR_SW_PATCH_DSP,

    /* Network */
    EM_NETWORK_SETTING_TEXT,
    EM_NETWORK_INFO_TEXT,
    EM_NETWORK_PREFER_RAT_TEXT,
    EM_NETWORK_PREFER_RAT_2G_TEXT,
    EM_NETWORK_PREFER_RAT_3G_TEXT,
    EM_NETWORK_CELL_LOCK_TEXT,
    EM_NETWORK_1900_BAND_TEXT,
    EM_NETWORK_ARFCN_TEXT,
    EM_NET_RR_CELL_SEL_TEXT,
    EM_NET_RR_CH_DSCR_TEXT,
    EM_NET_RR_CTRL_CH_TEXT,
    EM_NET_RR_RACH_CTRL_TEXT,
    EM_NET_RR_LAI_INFO_TEXT,
    EM_NET_RR_RADIO_LINK_TEXT,
    EM_NET_RR_MEAS_REP_TEXT,
    EM_NET_CC_CHAN_INFO_TEXT,
    EM_NET_CC_CALL_INFO_TEXT,
    EM_NET_CB_INFO_TEXT,
    EM_NET_PLMN_INFO_TEXT,
    EM_NET_GPRS_INFO_TEXT,
    EM_NET_Si2Q_MI_INFO_TEXT,
    EM_NET_TBF_STATUS_TEXT,
    EM_NET_BLK_INFO_TEXT,
    EM_NET_NETWORK_EVENT_TEXT,
    EM_NET_NETWORK_EVENT_START_TEXT,
    EM_NET_NETWORK_EVENT_FILTER_TEXT,
    EM_NET_NETWORK_EVENT_SETTING_TEXT,
    EM_NET_NETWORK_EVENT_GROUP_TEXT,    
    EM_NET_NETWORK_EVENT_SELECT_RING_TEXT,        

    /* Audio */
    EM_AUDIO_TEXT,
    EM_AUD_FIR_TEXT,
    EM_AUD_SET_VOLUME_TEXT,
    EM_AUD_SPEECH_TEXT,
    EM_AUD_SIDE_TONE_TEXT,
    EM_AUD_KEY_TONE_TEXT,
    //EM_AUD_CALL_TONE_TEXT,
    EM_AUD_MELODY_TEXT,
    EM_AUD_SOUND_TEXT,
    //EM_AUD_MEDIA_TEXT,
    EM_AUD_MICROPHONE_TEXT,
    EM_AUD_RING_TONE_TEXT,
    EM_AUD_MELODY_KEY_TEXT,
    EM_AUD_SET_MODE_TEXT,
    EM_AUD_NORMAL_MODE_TEXT,
    EM_AUD_LOUDSP_MODE_TEXT,
    EM_AUD_HEADSET_MODE_TEXT,
    EM_AUD_SET_MAX_SWING_TEXT,
    EM_AUD_VOLUME_0_TEXT,
    EM_AUD_VOLUME_1_TEXT,
    EM_AUD_VOLUME_2_TEXT,
    EM_AUD_VOLUME_3_TEXT,
    EM_AUD_VOLUME_4_TEXT,
    EM_AUD_VOLUME_5_TEXT,
    EM_AUD_VOLUME_6_TEXT,
    EM_AUD_FIR_0_TEXT,
    EM_AUD_FIR_1_TEXT,
    EM_AUD_FIR_2_TEXT,
    EM_AUD_FIR_3_TEXT,
    EM_AUD_FIR_4_TEXT,
    EM_AUD_FIR_5_TEXT,
    EM_AUD_DIRECT_APPLY_TEXT,
    EM_AUD_SET_SUCCESS_TEXT,
    EM_AUD_SET_ERROR_TEXT,
    EM_AUD_SPEECH_ENHANCEMENT_TEXT,
    EM_AUD_COMMON_PARAMETERS_TEXT,
    EM_AUD_BT_EARPHONE_MODE_TEXT,
    EM_AUD_BT_CORDLESS_MODE_TEXT,
    EM_AUD_AUX1_MODE_TEXT,
    EM_AUD_AUX2_MODE_TEXT,
    EM_AUD_AUX3_MODE_TEXT,
    EM_AUD_PARAMETER_0_TEXT,
    EM_AUD_PARAMETER_1_TEXT,
    EM_AUD_PARAMETER_2_TEXT,
    EM_AUD_PARAMETER_3_TEXT,
    EM_AUD_PARAMETER_4_TEXT,
    EM_AUD_PARAMETER_5_TEXT,
    EM_AUD_PARAMETER_6_TEXT,
    EM_AUD_PARAMETER_7_TEXT,
    EM_AUD_PARAMETER_8_TEXT,
    EM_AUD_PARAMETER_9_TEXT,
    EM_AUD_PARAMETER_10_TEXT,
    EM_AUD_PARAMETER_11_TEXT,

    EM_AUD_16_LELVEL_VOLUME_TEXT,
    EM_AUD_16_LELVEL_MAX_GAIN_TEXT,
    EM_AUD_16_LELVEL_STEP_TEXT,
    EM_AUD_TV_OUT_TEXT,
    EM_AUD_DEBUG_INFO_TEXT,
    EM_AUD_AUTO_VM_SETTING_TEXT,
    EM_AUD_VM_SUPPORT_TEXT,
    EM_AUD_AUTO_VM_TEXT,

    /* Device */
    EM_DEVICE_TEXT,
    EM_DEV_SET_UART_TEXT,
    EM_DEV_UART_SETTING_TEXT,
    EM_DEV_SET_UART_TST_PS_TEXT,
    EM_DEV_SET_UART_TST_L1_TEXT,
    EM_DEV_SET_UART_PS_TEXT,
    EM_DEV_SET_UART_CTI_ENABLE_TEXT,
    EM_DEV_SET_UART_ERROR_TEXT,
    EM_DEV_SET_UART_ERROR_PS_NOT_NULL_TEXT,
    
    EM_DEV_USB_PORT_TEXT,
    EM_DEV_DEFAULT_USB_DEBUG_TEXT,
    EM_DEV_UART_1_TEXT,
    EM_DEV_UART_2_TEXT,
    EM_DEV_UART_3_TEXT,
    //EM_DEV_UART_IRDA_TEXT,
    //EM_DEV_UART_USB_TEXT,
    EM_DEV_BAUD_AUTO_TEXT,
    EM_DEV_BAUD_75_TEXT,
    EM_DEV_BAUD_150_TEXT,
    EM_DEV_BAUD_300_TEXT,
    EM_DEV_BAUD_600_TEXT,
    EM_DEV_BAUD_1200_TEXT,
    EM_DEV_BAUD_2400_TEXT,
    EM_DEV_BAUD_4800_TEXT,
    EM_DEV_BAUD_7200_TEXT,
    EM_DEV_BAUD_9600_TEXT,
    EM_DEV_BAUD_14400_TEXT,
    EM_DEV_BAUD_19200_TEXT,
    EM_DEV_BAUD_28800_TEXT,
    EM_DEV_BAUD_33900_TEXT,
    EM_DEV_BAUD_38400_TEXT,
    EM_DEV_BAUD_57600_TEXT,
    EM_DEV_BAUD_115200_TEXT,
    EM_DEV_BAUD_230400_TEXT,
    EM_DEV_BAUD_460800_TEXT,
    EM_DEV_BAUD_921600_TEXT,
    EM_DEV_SLEEPMODE_TEXT,
    EM_DEV_SLEEPMODE_ON_TEXT,
    EM_DEV_SLEEPMODE_OFF_TEXT,

    EM_DEV_DCMMODE_TEXT,
    EM_DEV_DCMMODE_ON_TEXT,
    EM_DEV_DCMMODE_OFF_TEXT,

    EM_DEV_UART_POWER_ONOFF_TEXT,

    EM_DEV_LCD_TEXT,
    EM_DEV_LCD_MAIN_TEXT,
    EM_DEV_LCD_SUB_TEXT,
    EM_DEV_LCD_SET_CONSTRAST_TEXT,
    EM_DEV_LCD_SET_BIAS_TEXT,
    EM_DEV_LCD_SET_LINERATE_TEXT,
    EM_DEV_LCD_SET_TEMPERATURE_TEXT,
    EM_DEV_LCD_SET_PARAM_1_TEXT,
    EM_DEV_LCD_SET_PARAM_2_TEXT,
    EM_DEV_LCD_SET_PARAM_3_TEXT,
    EM_DEV_LCD_SET_PARAM_4_TEXT,
    EM_DEV_LCD_SET_PARAM_5_TEXT,

    EM_DEV_LCD_SET_COLOR_TEXT,
    EM_DEV_LCD_RGB_R_TEXT,
    EM_DEV_LCD_RGB_G_TEXT,
    EM_DEV_LCD_RGB_B_TEXT,
    EM_DEV_LCD_DISPLAY_DEMO_PIC_TEXT,

    EM_DEV_GPIO_TEXT,
    EM_DEV_GPIO_LIST_TEXT,
    //EM_DEV_GPIO_SET_TEXT,
    //EM_DEV_GPO_SET_TEXT,

    EM_DEV_PWM_TEXT,
    EM_DEV_PWM_START_TEXT,
    EM_DEV_PWM_STOP_TEXT,
    EM_DEV_PWM_SET_FREQ_TEXT,
    EM_DEV_PWM_SET_DUTY_TEXT,

    EM_DEV_EINT_TEXT,
    EM_DEV_ADC_TEXT,
    EM_DEV_NAND_FORMAT_TEXT,
    //EM_DEV_VDROP_TEXT,
    EM_DEV_CLAM_TEXT,
    EM_DEV_TVOUT_SETTING_TEXT,
    EM_DEV_TVOUT_SETTING_SWITCH_TEXT,
    EM_DEV_TVOUT_SETTING_TUNNING_TEXT,

    EM_DEV_HW_LEVEL_TEXT,
    EM_DEV_HW_LEVEL_MLCD_CON_TEXT,
    EM_DEV_HW_LEVEL_SLCD_CON_TEXT,
    EM_DEV_HW_LEVEL_BATTERY_TEXT,
    EM_DEV_HW_LEVEL_PWM1_TEXT,
    EM_DEV_HW_LEVEL_PWM2_TEXT,
    EM_DEV_HW_LEVEL_PWM3_TEXT,

    EM_DEV_USB_TEXT,
    EM_DEV_USB_OTG_SRP_TEXT,

    EM_DEV_RTC_XOSC_TEXT,

    /* GPRS Act */
    EM_GPRS_ACT_TEXT,
    EM_GPRS_AUTO_ATTACH_TEXT,
    EM_GPRS_1st_PDP_TEXT,
    EM_GPRS_2nd_PDP_TEXT,
    EM_GPRS_ACTIVATE_PDP_TEXT,
    EM_GPRS_DEACTIVATE_PDP_TEXT,
    EM_GPRS_SEND_DATA_TEXT,
    EM_GPRS_SEND_DATA_NORM_TEXT,
    EM_GPRS_SEND_DATA_HDR_TEXT,
    EM_GPRS_ACTIVATE_2ND_PDP_PRIMARY_TEXT,
    EM_GPRS_ACTIVATE_2ND_PDP_SECOND_TEXT,
    EM_GPRS_PING_TEXT,
    EM_GPRS_PINGIP_TEXT,
    EM_GPRS_PINGSIZE_TEXT,
    EM_GPRS_PINGCOUNT_TEXT,
    EM_GPRS_PINGTIMEOUT_TEXT,
    EM_GPRS_PDP_CONTEXT_1_TEXT,
    EM_GPRS_PDP_CONTEXT_2_TEXT,
    EM_GPRS_PDP_CONTEXT_3_TEXT,
    EM_GPRS_PDP_CONTEXT_4_TEXT,
    EM_GPRS_PDP_CONTEXT_5_TEXT,
    EM_GPRS_PDP_CONTEXT_6_TEXT,
    EM_GPRS_PDP_CONTEXT_7_TEXT,
    EM_GPRS_PDP_CONTEXT_8_TEXT,
    EM_GPRS_PDP_CONTEXT_9_TEXT,
    EM_GPRS_PDP_CONTEXT_10_TEXT,
    EM_GPRS_PDP_CONTEXT_11_TEXT,
    EM_GPRS_PDP_CONTEXT_12_TEXT,
    EM_GPRS_PDP_CONTEXT_13_TEXT,
    EM_GPRS_PDP_CONTEXT_14_TEXT,
    EM_GPRS_PDP_CONTEXT_15_TEXT,
    EM_GPRS_PDP_CONTEXT_30_TEXT,
    EM_GPRS_PDP_CONTEXT_31_TEXT,
    EM_GPRS_PDP_CONTEXT_GHIJK_INTERACTIVE_TEXT,
    EM_GPRS_PDP_CONTEXT_GHIJK_BACKGROUND_TEXT,   
    EM_GPRS_PDP_CONTEXT_ABCDEF_INTERACTIVE_TEXT,   
    EM_GPRS_PDP_CONTEXT_ABCDEF_BACKGROUND_TEXT,   

    /* Band Selection */
    EM_BAND_SEL_TEXT,
    EM_BAND_900_TEXT,
    EM_BAND_1800_TEXT,
    EM_BAND_DUAL_TEXT,
    EM_BAND_1900_TEXT,
    EM_BAND_850_TEXT,
    /* Lisen 05312005 */
    //EM_BAND_AUTO_TEXT,

    /* Misc. WAP */
    EM_MISC_TEXT,
    EM_AUTO_ANSWER_TEXT,
    EM_HIGHSPEED_SIM_MENUID_TEXT,
    EM_HIGHSPEED_SIM_MENUID_ICON,
    EM_BACKLIGHT_TEXT,
    EM_SERIAL_PORT_EN_TEXT,
    EM_WAP_TEXT,
    EM_WAP_ENABLE_DEBUG_TEXT,
    EM_WAP_OFFLINE_PAGE_TEXT,
    EM_WAP_USER_AGENT_TEXT,
    
    EM_WAP_USER_AGENT_MAUI_E800_TEXT,
    EM_WAP_USER_AGENT_NOKIA_N72_TEXT,
    EM_WAP_USER_AGENT_NOKIA_E70_TEXT,
    EM_WAP_USER_AGENT_NOKIA_N93_TEXT,
    EM_WAP_USER_AGENT_NOKIA_6680_TEXT,
    EM_WAP_USER_AGENT_NOKIA_6280_TEXT,
    EM_WAP_USER_AGENT_NOKIA_3230_TEXT,
    EM_WAP_USER_AGENT_NOKIA_6230_TEXT,
    EM_WAP_USER_AGENT_SE_W900I_TEXT,
    EM_WAP_USER_AGENT_SE_W800I_TEXT,
    EM_WAP_USER_AGENT_SE_K700i_TEXT,
    EM_WAP_USER_AGENT_SE_Z800_TEXT,
    EM_WAP_USER_AGENT_SAMSUNG_D608_TEXT,
    EM_WAP_USER_AGENT_MOTO_E1070_TEXT,
    
    EM_WAP_ACCEPT_HEADER_TEXT,
    EM_WAP_ACCEPT_HEADER_WAP121_TEXT,
    EM_WAP_ACCEPT_HEADER_WAP20_TEXT,
    EM_WAP_ACCEPT_HEADER_WML_TEXT,
    EM_WAP_ACCEPT_HEADER_XHTML_TEXT,
    EM_WAP_ACCEPT_HEADER_HTML_TEXT,
    EM_WAP_MMS_VERSION_TEXT,
    EM_WAP_MMS_VERSION_MMS_DEFAULT_TEXT,
    EM_WAP_MMS_VERSION_MMS10_TEXT,
    EM_WAP_MMS_VERSION_MMS11_TEXT,
    EM_WAP_MMS_VERSION_MMS12_TEXT,
    EM_POWER_ON_DURATION_TEXT,
    EM_J2ME_TCK_TEXT,
    EM_AUTO_RESET_TEXT,
    EM_PWR_DOWN_CONTROL_TEXT,
    EM_SW_PATCH_TEXT,
    EM_AMR_TEXT,
    EM_RAM_TEST_TEXT,
    EM_VIDEO_HI_BITRATE_TEXT,

    /* Cell Reselection */
    EM_MISC_CELL_RESELECT_TEXT,
    EM_MISC_CELL_RESELECT_SUSPEND_TEXT,
    EM_MISC_CELL_RESELECT_RESUME_IN_TRANSFER_TEXT,
    EM_MISC_CELL_RESELECT_RESUME_IN_ALL_TEXT,

    EM_MISC_FIXED_GAIN_FOR_HELIOS2_TEXT,    
    
    EM_MISC_MT6223_DEBUG_MODE_TEXT,
    EM_MISC_MT6223_DEBUG_NORMAL_MODE_TEXT,
    EM_MISC_MT6223_DEBUG_ICE_TASK_MODE_TEXT,
    EM_MISC_MT6223_DEBUG_SWDBG_MODE_TEXT,
    
    /* LSD slower */
    EM_MISC_LSD_SLOWER_TEXT,
    EM_MISC_LSD_SLOWER_TICKS_TEXT,
    
    /* Auto Test */
    EM_AUTO_TEST_SETTING_TEXT,
    EM_AUTO_TEST_OPTIONS_TEXT,
    EM_AUTO_TEST_ADD_TEXT,
    EM_AUTO_TEST_ENTER_PRIORITY_TEXT,
    EM_AUTO_TEST_CHANGE_PRIORITY_TEXT,
    EM_AUTO_TEST_REMOVE_TEXT,

    /* DBG Trace */
    STR_ID_EM_DEBUG_INFO,
    STR_ID_EM_FS_TRACE,
    STR_ID_EM_FS_TRACE_ALL_OFF,
    STR_ID_EM_FS_TRACE_ALL_ERROR,
    STR_ID_EM_FS_TRACE_ALL_API_ERROR,

    STR_ID_EM_LAST_EXCEPTION,

    STR_ID_EM_SYS_STATS,
    STR_ID_EM_WRITE_SYS_STATS,
    STR_ID_EM_SAVING_STAT_PWROFF,

    /* Bluetooth */
    EM_BT_STR_ID,
    EM_BT_GENERNAL_TEST_STR_ID,
    EM_BT_GET_CHIP_VERSION_STR_ID,
    EM_BT_ENTRY_TSMOD_STR_ID,
    EM_BT_ENTRY_FW_VERSION_STR_ID,
    EM_BT_ADD_SCO_LNK_STR_ID,
    EM_BT_RMV_SCO_LNK_STR_ID,
    EM_BT_ENTRY_TEST_STR_ID,
    EM_BT_DEBUG_TRACE_STR_ID,
    EM_BT_ADD_AUDIO_CONNECTION_STR_ID,
    EM_BT_REMOVE_AUDIO_CONNECTION_STR_ID,
    EM_BT_LOOKBACK_STR_ID,
    EM_BT_BD_ADDR_STR_ID,
    EM_BT_BD_PASSWORD_STR_ID,
    EM_BT_EXIT_TEST_MODE_STR_ID,
    EM_BT_AVRCP_CMD_LIST_STR_ID,

    /* Socket */
    EM_SOCKET_TEXT,
    EM_SOCKET_DNS_TEXT,
    EM_SOCKET_HTTP_TEXT,
    EM_SOCKET_ECHO_TEXT,
    EM_SOCKET_DATE_TEXT,
    EM_SOCKET_TRACERT_TEXT,
    EM_SOCKET_DNS_DOMAIN_NAME_TEXT,
    EM_SOCKET_HTTP_URL_TEXT,
    EM_SOCKET_ECHO_SERVER_IP_TEXT,
    EM_SOCKET_ECHO_STRING_TEXT,
    EM_SOCKET_TRACERT_REMOTE_IP_TEXT,
    EM_SOCKET_TRACERT_START_TEXT,
    EM_SOCKET_IN_PROGRESS_TEXT,
    EM_SOCKET_RESULT_TEXT,

    EM_SOCKET_ERROR_INVAL_PARA_TEXT,
    EM_SOCKET_ERROR_PEER_NOT_REACHABLE_TEXT,
    EM_SOCKET_ERROR_PEER_NO_RESPONSE_TEXT,
    EM_SOCKET_ERROR_CNT_RESET_BY_PEER_TEXT,
    EM_SOCKET_ERROR_BEARER_FAIL_TEXT,
    EM_SOCKET_ERROR_UNKNOWN_APP_TEXT,
    EM_SOCKET_ERROR_BUSY_TEXT,
    EM_SOCKET_ERROR_NO_MEMORY_TEXT,

    /* BEGIN OF IPERF */
    EM_SOCKET_IPERF_STR,
    EM_SOCKET_IPERF_IPERF_SETTING_STR,
    EM_SOCKET_IPERF_TCP_TESTING_STR,
    EM_SOCKET_IPERF_UDP_TESTING_STR,
    EM_SOCKET_IPERF_TCP_SETTING_STR,
    EM_SOCKET_IPERF_UDP_SETTING_STR,
    EM_SOCKET_IPERF_DATA_ACCOUNT_STR,
    EM_SOCKET_IPERF_CLIENT_SERVER_STR,
    EM_SOCKET_IPERF_RW_FILE_STR,
    EM_SOCKET_IPERF_CLIENT_STR,
    EM_SOCKET_IPERF_SERVER_STR,
    EM_SOCKET_IPERF_FADDR_STR,
    EM_SOCKET_IPERF_LEN_STR,
    EM_SOCKET_IPERF_PORT_STR,
    EM_SOCKET_IPERF_WINDOW_STR,
    EM_SOCKET_IPERF_BUFFER_STR,
    EM_SOCKET_IPERF_MSS_STR,
    EM_SOCKET_IPERF_BANDWIDTH_STR,
    EM_SOCKET_IPERF_NUM_BYTES_STR,
    EM_SOCKET_IPERF_DUAL_STR,
    EM_SOCKET_IPERF_TIME_SECS_STR,
    EM_SOCKET_IPERF_TOS_STR,
    EM_SOCKET_IPERF_BEST_EFFORT_STR,
    EM_SOCKET_IPERF_BACK_GROUND_STR,
    EM_SOCKET_IPERF_VIDEO_STR,
    EM_SOCKET_IPERF_VOICE_STR,
    EM_SOCKET_IPERF_WRONG_SETTING_STR,
    EM_SOCKET_IPERF_PROGRESSING_STR,
    EM_SOCKET_IPERF_TEST_FAILED_STR,
    EM_SOCKET_IPERF_REPORT_STR,
    EM_SOCKET_IPERF_RUN_STR,
    EM_SOCKET_IPERF_LEN_ERR_STR,
    EM_SOCKET_IPERF_PORT_ERR_STR,
    EM_SOCKET_IPERF_WINDOW_ERR_STR,
    EM_SOCKET_IPERF_BUFFER_ERR_STR,
    EM_SOCKET_IPERF_MSS_ERR_STR,
    EM_SOCKET_IPERF_BANDWIDTH_ERR_STR,
    EM_SOCKET_IPERF_NUM_BYTES_ERR_STR,
    EM_SOCKET_IPERF_FADDR_ERR_STR,
    EM_SOCKET_IPERF_SERVER_DUAL_ERR_STR,
    EM_SOCKET_IPERF_TIME_SECS_ERR_STR,
    EM_SOCKET_IPERF_CNF_FAILED_ERR_STR,
    EM_SOCKET_IPERF_TEST_FAILED_ERR_STR,
    /* END OF IPERF */

    /* Touch Screen */
    EM_TOUCHSCREEN_TEXT,
    EM_TOUCHSCREEN_TEST_STATISTICS_TEXT,
    EM_TOUCHSCREEN_TEST_EXIT_TEXT,
    EM_TOUCHSCREEN_TEST_TEXT,
    EM_MMI_DEBUG_TEXT,
    EM_MEMORY_DUMP_TEXT,
    EM_FRM_PROFILING_TEXT,
    EM_UI_BENCHMARK_TEXT,
    EM_GLOBAL_PROCESSING_TEXT,
    EM_SWDBG_TEXT,
    EM_SWDBG_OFF_TEXT,
    EM_SWDBG_DSP_L1_TEXT,
    EM_SWDBG_DSP_PS_TEXT,
    EM_SWDBG_L1_PS_TEXT,
    EM_SWDBG_MCU_TEXT,
    EM_SWDBG_DSP_L1_PS_TEXT,
    EM_SWDBG_MCU_DSP_TEXT,

    EM_SWDBG_MCU_DSP_IRDBG_TEXT,
    EM_SWDBG_RESET_TEXT,
    EM_DEV_PMIC_6318_TEXT,
    EM_DEV_PMIC_6318_REGISTER_EDITOR_TEXT,

    /* Charger Status */
    EM_DEV_PMIC_6318_CHARGER_STATUS_TEXT,
    EM_DEV_PMIC_CHARGER_OVSPI_TEXT,
    EM_DEV_PMIC_CHARGER_CHRDET_TEXT,
    EM_DEV_PMIC_CHARGER_AC_DET_TEXT,
    EM_DEV_PMIC_CHARGER_USB_DET_TEXT,
    EM_DEV_PMIC_CHARGER_BAT_ON_TEXT,
    EM_DEV_PMIC_CHARGER_CV_TEXT,
    EM_DEV_PMIC_CHARGER_CHRG_DIS_TEXT,
    /* Set Charger */
    EM_DEV_PMIC_6318_SET_CHARGER_TEXT,
    EM_DEV_PMIC_6318_SET_CHARGER_CHREN_TEXT,
    EM_DEV_PMIC_6318_SET_CHARGER_AC_CURRENT_TEXT,
    EM_DEV_PMIC_6318_SET_CHARGER_USB_CHREN_TEXT,
    EM_DEV_PMIC_6318_SET_CHARGER_USB_CURRENT_TEXT,
    EM_DEV_PMIC_6318_SET_CHARGER_CURRENT_50_TEXT,
    EM_DEV_PMIC_6318_SET_CHARGER_CURRENT_90_TEXT,
    EM_DEV_PMIC_6318_SET_CHARGER_CURRENT_150_TEXT,
    EM_DEV_PMIC_6318_SET_CHARGER_CURRENT_225_TEXT,
    EM_DEV_PMIC_6318_SET_CHARGER_CURRENT_300_TEXT,
    EM_DEV_PMIC_6318_SET_CHARGER_CURRENT_450_TEXT,
    EM_DEV_PMIC_6318_SET_CHARGER_CURRENT_650_TEXT,
    EM_DEV_PMIC_6318_SET_CHARGER_CURRENT_800_TEXT,
    EM_DEV_PMIC_6318_CHARGER_CURRENT_TEXT,
    /* RGB LED */
    EM_DEV_PMIC_6318_RGB_TEXT,
    EM_DEV_PMIC_R_LED_TEXT,
    EM_DEV_PMIC_R_LED_CURRENT_TEXT,
    EM_DEV_PMIC_G_LED_TEXT,
    EM_DEV_PMIC_G_LED_CURRENT_TEXT,
    EM_DEV_PMIC_B_LED_TEXT,
    EM_DEV_PMIC_B_LED_CURRENT_TEXT,
    EM_DEV_PMIC_RGB_LED_CURRENT_12_TEXT,
    EM_DEV_PMIC_RGB_LED_CURRENT_16_TEXT,
    EM_DEV_PMIC_RGB_LED_CURRENT_20_TEXT,
    EM_DEV_PMIC_RGB_LED_CURRENT_24_TEXT,
    EM_DEV_PMIC_RGB_LED_CURRENT_TEXT,
    /* KP LED */
    EM_DEV_PMIC_6318_KP_LED_TEXT,
    EM_DEV_PMIC_6318_KP_ENABLE_TEXT,
    EM_DEV_PMIC_6318_KP_DUTY_OPTION_TEXT,
    EM_DEV_PMIC_6318_KP_DIM_CLOCK_TEXT,
    EM_DEV_PMIC_6318_KP_CHR_PUMP_EN_TEXT,
    EM_DEV_PMIC_6318_KP_CHR_PUMP_CURRENT_TEXT,
    EM_DEV_PMIC_6318_KP_CHR_PUMP_CURRENT_LEVEL1_TEXT,
    EM_DEV_PMIC_6318_KP_CHR_PUMP_CURRENT_LEVEL2_TEXT,
    EM_DEV_PMIC_6318_KP_CHR_PUMP_CURRENT_LEVEL3_TEXT,
    EM_DEV_PMIC_6318_KP_CHR_PUMP_CURRENT_LEVEL4_TEXT,
    /* BL LED */
    EM_DEV_PMIC_6318_BL_LED_TEXT,
    EM_DEV_PMIC_6318_BL_ENABLE_TEXT,
    EM_DEV_PMIC_6318_BL_DUTY_OPTION_TEXT,
    EM_DEV_PMIC_6318_BL_DIM_CLOCK_TEXT,
    EM_DEV_PMIC_6318_BL_DIM_BYPASS_TEXT,
    /* Audio */
    EM_DEV_PMIC_6318_AUDIO_TEXT,
    EM_DEV_PMIC_6318_AUDIO_SPEAKER_TEXT,
    EM_DEV_PMIC_6318_AUDIO_AMPGAIN_TEXT,
    EM_DEV_PMIC_6318_AUDIO_AMPGAIN0_TEXT,
    EM_DEV_PMIC_6318_AUDIO_AMPGAIN1_TEXT,
    EM_DEV_PMIC_6318_AUDIO_AMPGAIN2_TEXT,
    EM_DEV_PMIC_6318_AUDIO_AMPGAIN3_TEXT,
    EM_DEV_PMIC_6318_AUDIO_AMPGAIN4_TEXT,
    EM_DEV_PMIC_6318_AUDIO_AMPGAIN5_TEXT,
    EM_DEV_PMIC_6318_AUDIO_AMPGAIN6_TEXT,
    EM_DEV_PMIC_6318_AUDIO_AMPGAIN7_TEXT,
    /* Misc */
    EM_DEV_PMIC_6318_MISC_TEXT,
    EM_DEV_PMIC_6318_MISC_VIBRATOR_ENABLE_TEXT,
    EM_DEV_PMIC_6318_MISC_VIBRATOR_OUT_TEXT,
    EM_DEV_PMIC_6318_MISC_VMC_ENABLE_TEXT,
    EM_DEV_PMIC_6318_MISC_VMC_SEL_TEXT,
    EM_DEV_PMIC_6318_MISC_VA_SW_ENABLE_TEXT,
    EM_DEV_PMIC_6318_MISC_VA_SW_SEL_TEXT,
    EM_DEV_PMIC_6318_MISC_USB_PWR_ENABLE_TEXT,
    EM_DEV_PMIC_6318_MISC_VBAT_OUT_ENABLE_TEXT,
    EM_DEV_PMIC_6318_MISC_ISENSE_OUT_ENABLE_TEXT,
    /* LCM BL Setting */
    EM_DEV_PMIC_6318_MISC_LCM_BL_SETTING_TEXT,

    /* Profiling */
    STR_ID_EM_PROFILING,
    EM_PROFILING_DISPLAY_TIME_TEXT,
    EM_PROFILING_GDI_PROFILE_TEXT,
    EM_PROFILING_SCREEN_DELAY_TEXT,
    EM_PROFILING_MATRIX_DELAY_TEXT,
    EM_PROFILING_LIST_DELAY_TEXT,
    EM_PROFILING_DELAY_OFFSET_TEXT,
    STR_ID_EM_PROFILING_MULTIMEDIA,
    STR_ID_EM_PROFILING_AUTO_PLAY,
    STR_ID_EM_PROFILING_VDOREC,
    STR_ID_EM_PROFILING_VDOPLY,
    STR_ID_EM_PROFILING_CAMERA,
    STR_ID_EM_PROFILING_START,
    STR_ID_EM_PROFILING_SETTING,
    STR_ID_EM_PROFILING_EXTRA_LAYER,
    STR_ID_EM_PROFILING_ROTATE,
    STR_ID_EM_PROFILING_TV_OUT_MODE,
    STR_ID_EM_PROFILING_RECORD_SIZE,
    STR_ID_EM_PROFILING_PREVIEW_SIZE,
    STR_ID_EM_PROFILING_PLAY_SIZE,
    STR_ID_EM_PROFILING_ROTATE_0,
    STR_ID_EM_PROFILING_ROTATE_90,
    STR_ID_EM_PROFILING_ROTATE_180,
    STR_ID_EM_PROFILING_ROTATE_270,
    STR_ID_EM_PROFILING_TV_LCD_SCREEN,
    STR_ID_EM_PROFILING_TV_FULL_SCREEN,
    STR_ID_EM_PROFILING_SIZE_SQCIF, /* 128x96 */
    STR_ID_EM_PROFILING_SIZE_QCIF,  /* 176x144 */
    STR_ID_EM_PROFILING_SIZE_CIF,   /* 352x288 */
    STR_ID_EM_PROFILING_SIZE_QQVGA, /* 160x120 */
    STR_ID_EM_PROFILING_SIZE_QVGA,  /* 320x240 */
    STR_ID_EM_PROFILING_SIZE_VGA,   /* 640x480 */
    STR_ID_EM_PROFILING_SIZE_LCD,
    STR_ID_EM_PROFILING_IMAGE_DECODE, /*Cathy Add EM IMAGE DECODE*/
    STR_ID_EM_PROFILING_SINGLE_FOLDER, /*Cathy Add EM IMAGE DECODE*/
    STR_ID_EM_PROFILING_SINGLE_FOLDER_ROTATE, /*Cathy Add EM IMAGE DECODE*/   

    /* RF Tool */
    EM_RF_TEST_TOOL_TEXT,
    /* GSM */
    EM_RF_TEST_GSM_CONFIRM_NOTIFY_TEST,
    EM_RF_TEST_GSM_TEST,
    /* GSM -- TX */
    EM_RF_GSM_TX_TEST_TEXT,
    EM_RF_GSM_TX_BAND_TEXT,
    EM_RF_GSM_TX_BAND_GSM850_TEXT,
    EM_RF_GSM_TX_BAND_GSM900_TEXT,
    EM_RF_GSM_TX_BAND_DCS1800_TEXT,
    EM_RF_GSM_TX_BAND_PCS1900_TEXT,
    EM_RF_GSM_TX_ARFCN_TEXT,
    EM_RF_GSM_TX_TSC_TEXT,
    EM_RF_GSM_TX_PCL_TEXT,
    EM_RF_GSM_TX_AFC_TEXT,
    EM_RF_GSM_TX_BURST_TYPE_TEXT,
    EM_RF_GSM_TX_BURST_NB_TEXT,
    EM_RF_GSM_TX_BURST_NBALL_TEXT,
    EM_RF_GSM_TX_BURST_AB_TEXT,
    EM_RF_GSM_TX_BURST_CONTTX00_TEXT,
    EM_RF_GSM_TX_BURST_CONTTX11_TEXT,
    EM_RF_GSM_TX_BURST_CONTTX01_TEXT,
    EM_RF_GSM_TX_BURST_CONTTX_RANDOM_TEXT,
    EM_RF_GSM_TX_GAIN_TEXT,
    /* GSM -- RX */
    EM_RF_GSM_RX_TEST_TEXT,
    EM_RF_GSM_RX_BURST_CONT_RX_TEXT,
    EM_RF_GSM_RX_BURST_BURST_RX_TEXT,
    /* GSM -- Power Scan */
    EM_RF_GSM_POWER_SCAN_TEXT,

    /* WiFi */
    EM_RF_TEST_WIFI_TEST,
    /* WiFi -- TX */
    EM_RF_WIFI_TX_TESTS_TEXT,
    EM_RF_WIFI_TX_DAC_OFFSET_TEXT,
    EM_RF_WIFI_TX_OUTPUT_POWER_TEXT,
    EM_RF_WIFI_TX_CARRIER_SUPP_TEXT,
    EM_RF_WIFI_TX_LOCAL_FREQUENCY_TEXT,
    EM_RF_WIFI_TX_CONT_PKT_TX_TEXT,
    /* WiFi -- TX -- Domain */
    EM_RF_WIFI_TX_DOMAIN_TEXT,
    EM_RF_WIFI_TX_DOMAIN_US_TEXT,
    EM_RF_WIFI_TX_DOMAIN_JP_TEXT,
    /* WiFi -- TX -- Channel Freq. */
    EM_RF_WIFI_TX_CH_FREQ_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_1_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_2_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_3_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_4_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_5_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_6_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_7_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_8_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_9_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_10_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_11_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_12_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_13_TEXT,
    EM_RF_WIFI_TX_CH_FREQ_14_TEXT,
    /* WiFi -- TX -- TX Rate */
    EM_RF_WIFI_TX_RATE_TEXT,
    EM_RF_WIFI_TX_RATE_1_TEXT,
    EM_RF_WIFI_TX_RATE_2_TEXT,
    EM_RF_WIFI_TX_RATE_3_TEXT,
    EM_RF_WIFI_TX_RATE_4_TEXT,
    EM_RF_WIFI_TX_RATE_5_TEXT,
    EM_RF_WIFI_TX_RATE_6_TEXT,
    EM_RF_WIFI_TX_RATE_7_TEXT,
    EM_RF_WIFI_TX_RATE_8_TEXT,
    EM_RF_WIFI_TX_RATE_9_TEXT,
    EM_RF_WIFI_TX_RATE_10_TEXT,
    EM_RF_WIFI_TX_RATE_11_TEXT,
    EM_RF_WIFI_TX_RATE_12_TEXT,
    /* WiFi -- TX -- Ant, gain, pkt */
    EM_RF_WIFI_TX_ANT_TEXT,
    EM_RF_WIFI_TX_GAIN_TEXT,
    EM_RF_WIFI_TX_PKT_COUNT_TEXT,
    EM_RF_WIFI_TX_PKT_INTERVAL_TEXT,
    EM_RF_WIFI_TX_PKT_LENGTH_TEXT,
    /* WiFi -- TX -- TX Pattern */
    EM_RF_WIFI_TX_PATTERN_TEXT,
    EM_RF_WIFI_TX_PATTERN_ALL_0_TEXT,
    EM_RF_WIFI_TX_PATTERN_ALL_1_TEXT,
    EM_RF_WIFI_TX_PATTERN_ALTER_BITS_TEXT,
    EM_RF_WIFI_TX_PATTERN_RANDOM_TEXT,
    /* WiFi -- TX -- short preamble */
    EM_RF_WIFI_TX_SHORT_PERAMBLE_TEXT,
    EM_RF_WIFI_TX_SHORT_PERAMBLE_TRUE_TEXT,
    EM_RF_WIFI_TX_SHORT_PERAMBLE_FALSE_TEXT,
    /* WiFi -- TX -- mac Header */
    EM_RF_WIFI_TX_MAC_HEADER_TEXT,
    /* WiFi -- RX */
    EM_RF_WIFI_CONT_PKT_RX_TEXT,
    /* WiFi -- Power Save */
    EM_RF_WIFI_POWER_SAVE_TEXT,
    EM_RF_WIFI_POWER_SAVE_MODE_TEXT,
    EM_RF_WIFI_POWER_SAVE_NORMAL_TEXT,
    EM_RF_WIFI_POWER_SAVE_IDLE_TEXT,
    EM_RF_WIFI_POWER_SAVE_SLEEP_TEXT,
    /* WiFi -- Register */
    EM_RF_WIFI_REGISTER_TEXT,
    EM_RF_WIFI_REGISTER_MCR_TEXT,
    EM_RF_WIFI_REGISTER_BBCR_TEXT,
    EM_RF_WIFI_REGISTER_EEPROM_TEXT,
    EM_RF_WIFI_REGISTER_TYPE_TEXT,
    EM_RF_WIFI_REGISTER_ACCESS_TEXT,
    EM_RF_WIFI_REGISTER_ADDRESS_TEXT,
    EM_RF_WIFI_REGISTER_INDEX_TEXT,
    EM_RF_WIFI_REGISTER_DATA_TEXT,
    EM_RF_WIFI_REGISTER_16_TEXT,
    EM_RF_WIFI_REGISTER_32_TEXT,
    EM_RF_WIFI_REGISTER_READ_TEXT,
    EM_RF_WIFI_REGISTER_WRITE_TEXT,

    EM_DEV_FM_RADIO_TEXT,
    EM_DEV_FM_RADIO_MONO_TEXT,
    EM_DEV_FM_RADIO_STEREO_TEXT,
    EM_DEV_FM_RADIO_STEREO_ENABLE_SBLEND_ON_TEXT,
    EM_DEV_FM_RADIO_STEREO_ENABLE_SBLEND_OFF_TEXT,
    EM_DEV_FM_RADIO_RSSI_TEXT,
    EM_DEV_FM_RADIO_RSSI_LEVEL1_TEXT,
    EM_DEV_FM_RADIO_RSSI_LEVEL2_TEXT,
    EM_DEV_FM_RADIO_RSSI_LEVEL3_TEXT,
    EM_DEV_FM_RADIO_RSSI_LEVEL4_TEXT,
    EM_DEV_FM_RADIO_RSSI_LEVEL5_TEXT,
    EM_DEV_FM_RADIO_RSSI_LEVEL6_TEXT,
    EM_DEV_FM_RADIO_IF_COUNT_DELTA_TEXT,
    EM_DEV_FM_RADIO_IF_COUNT_DELTA_10_TEXT,
    EM_DEV_FM_RADIO_IF_COUNT_DELTA_15_TEXT,
    EM_DEV_FM_RADIO_IF_COUNT_DELTA_20_TEXT,
    EM_DEV_FM_RADIO_IF_COUNT_DELTA_25_TEXT,
    EM_DEV_FM_RADIO_IF_COUNT_DELTA_30_TEXT,
    EM_DEV_FM_RADIO_RSSI_INFO_TEXT,

    /* VOIP */
    EM_VOIP_TEXT,
    EM_VOIP_SETTINGS_TEXT,
    EM_VOIP_SIP_SUPPORTED_TEXT,
    EM_VOIP_SIP_REQUIRE_TEXT,

    EM_VOIP_P2P_CALL_TEXT,
    EM_VOIP_REREGISTER_TIMER_TEXT,
    EM_VOIP_CALL_REFRESH_TIMER_TEXT,
    EM_VOIP_REFER_SUB_TIMER_TEXT,
    EM_VOIP_MWI_SUB_TIMER_TEXT,
    EM_VOIP_MWI_RETRY_TIME_TEXT,

    EM_VOIP_UAS_Refresher_TEXT,
    EM_VOIP_UAC_Refresher_TEXT,
    EM_VOIP_UAS_TEXT,
    EM_VOIP_UAC_TEXT,
    EM_VOIP_RPORT_SUPPORT_TEXT,
    EM_VOIP_LOCAL_ADDR_TEXT,
    
    /* VOIP Log */
    EM_VOIP_LOG_TEXT,
    EM_VOIP_LOG_CONTENT_TEXT,
    EM_VOIP_LOG_SETTINGS_TEXT,
    EM_VOIP_LOG_AUTO_DELETE_TEXT,
    EM_VOIP_LOG_DELETE_ALL_TEXT,
    EM_VOIP_LOG_DELETE_ONE_DAY_TEXT,
    EM_VOIP_LOG_DELETE_HALF_MONTH_TEXT,
    EM_VOIP_LOG_DELETE_ONE_MONTH_TEXT,


    /* BT RF Test */
    EM_DEV_BT_RF_TEST_TEXT,
    EM_DEV_BT_RF_TEST_TX_TEXT,
    EM_DEV_BT_RF_TEST_RX_TEXT,
    EM_DEV_BT_RF_TEST_BD_ADDR_TEXT,
    EM_DEV_BT_RF_TEST_MODE_TEXT,

    EM_DEV_BT_RF_TEST_NO_HOPING_TEXT,
    EM_DEV_BT_RF_TEST_HOPING_TEXT,
    EM_DEV_BT_RF_TEST_CHANNEL_TEXT,
    EM_DEV_BT_RF_TEST_CTRL_PWR_LEVEL_TEXT,

    EM_DEV_BT_RF_TEST_PACKET_TYPE_TEXT,
    EM_DEV_BT_RF_TEST_PACKET_TYPE_DH1_TEXT,
    EM_DEV_BT_RF_TEST_PACKET_TYPE_DH3_TEXT,
    EM_DEV_BT_RF_TEST_PACKET_TYPE_DH5_TEXT,
    
    EM_DEV_BT_RF_TEST_DATA_LEN_TEXT,
    EM_DEV_BT_RF_TEST_POLL_PERIOD_TEXT,
    EM_DEV_BT_RF_TEST_TURN_OFF_BT_TEXT,
    
    /* Cascading Menu */
    STR_ID_EM_MISC_CASCADE_MENU,

   ENGINEER_MODE_STR_END
} EM_STR_IDS;

typedef enum
{
    ENGINEER_MODE_ICON_BASE = ENGINEER_MODE_BASE,

    /* Common */
    ENGINEER_MODE_ICON,
    ENGINEER_MODE_LSK_ICON,
    ENGINEER_MODE_RSK_ICON,

    /* Network */
    EM_NETWORK_ICON,
    EM_NET_RR_CELL_SEL_ICON,
    EM_NET_RR_CH_DSCR_ICON,
    EM_NET_RR_CTRL_CH_ICON,
    EM_NET_RR_RACH_CTRL_ICON,
    EM_NET_RR_LAI_INFO_ICON,
    EM_NET_RR_RADIO_LINK_ICON,
    EM_NET_RR_MEAS_REP_ICON,
    EM_NET_RR_CTRL_MSG_ICON,
    EM_NET_CC_CHAN_INFO_ICON,
    EM_NET_CC_CALL_INFO_ICON,
    EM_NET_CB_INFO_ICON,
    EM_NET_SS_INFO_ICON,
    EM_NET_MM_INFO_ICON,
    EM_NET_UEM_INFO_ICON,

    /* Audio */
    EM_AUDIO_ICON,
    EM_AUD_SET_VOLUME_ICON,
    EM_AUD_FIR_ICON,
    EM_AUD_SPEECH_ICON,
    EM_AUD_SIDE_TONE_ICON,
    EM_AUD_KEY_TONE_ICON,
    EM_AUD_CALL_TONE_ICON,
    EM_AUD_MELODY_ICON,
    EM_AUD_SOUND_ICON,
    EM_AUD_MEDIA_ICON,
    EM_AUD_MICROPHONE_ICON,
    EM_AUD_RING_TONE_ICON,
    EM_AUD_SET_MODE_ICON,
    EM_AUD_NORMAL_MODE_ICON,
    EM_AUD_LOUDSP_MODE_ICON,
    EM_AUD_HEADSET_MODE_ICON,
    EM_AUD_SPEECH_ENHANCEMENT_ICON,
    EM_AUD_COMMON_PARAMETERS_ICON,
    EM_AUD_BT_EARPHONE_MODE_ICON,
    EM_AUD_BT_CORDLESS_MODE_ICON,
    EM_AUD_AUX1_MODE_ICON,
    EM_AUD_AUX2_MODE_ICON,
    EM_AUD_AUX3_MODE_ICON,
    EM_AUD_SET_MAX_SWING_ICON,
    EM_AUD_VOLUME_0_ICON,
    EM_AUD_VOLUME_1_ICON,
    EM_AUD_VOLUME_2_ICON,
    EM_AUD_VOLUME_3_ICON,
    EM_AUD_VOLUME_4_ICON,
    EM_AUD_VOLUME_5_ICON,
    EM_AUD_VOLUME_6_ICON,
    EM_AUD_DIRECT_APPLY_ICON,

    /* Device */
    EM_DEVICE_ICON,
    EM_DEV_SET_UART_ICON,
    EM_DEV_SET_UART_PORT_ICON,
    EM_DEV_SET_UART_BUAD_ICON,
    EM_DEV_DEFAULT_USB_APP_ICON,
    EM_DEV_DEFAULT_USB_DATA_ICON,
    EM_DEV_DEFAULT_USB_DEBUG_ICON,
    EM_DEV_UART_1_ICON,
    EM_DEV_UART_2_ICON,
    EM_DEV_UART_3_ICON,
    EM_DEV_BAUD_115200_ICON,
    EM_DEV_BAUD_230400_ICON,
    EM_DEV_BAUD_460800_ICON,
    EM_DEV_BAUD_921600_ICON,
    EM_DEV_SLEEPMODE_ICON,
    EM_DEV_SLEEPMODE_ON_ICON,
    EM_DEV_SLEEPMODE_OFF_ICON,

    EM_DEV_LCD_ICON,
    EM_DEV_LCD_MAIN_ICON,
    EM_DEV_LCD_SUB_ICON,
    EM_DEV_LCD_SET_CONSTRAST_ICON,
    EM_DEV_LCD_SET_BIAS_ICON,
    EM_DEV_LCD_SET_LINERATE_ICON,
    EM_DEV_LCD_SET_TEMPERATURE_ICON,
    EM_DEV_LCD_SET_PARAM_1_ICON,
    EM_DEV_LCD_SET_PARAM_2_ICON,
    EM_DEV_LCD_SET_PARAM_3_ICON,
    EM_DEV_LCD_SET_PARAM_4_ICON,
    EM_DEV_LCD_SET_PARAM_5_ICON,
    EM_DEV_GPIO_ICON,
    EM_DEV_GPIO_LIST_ICON,
    EM_DEV_GPIO_SET_ICON,
    EM_DEV_GPO_SET_ICON,

    EM_DEV_EXT_CAMERA_ICON,
    EM_DEV_EXT_CAMERA_WRITE_ICON,
    EM_DEV_EXT_CAMERA_READ_ICON,

    EM_DEV_PWM_ICON,
    EM_DEV_PWM_START_ICON,
    EM_DEV_PWM_STOP_ICON,
    EM_DEV_PWM_SET_FREQ_ICON,
    EM_DEV_PWM_SET_DUTY_ICON,

    EM_DEV_EINT_ICON,
    EM_DEV_ADC_ICON,
    EM_DEV_NAND_FORMAT_ICON,
    EM_DEV_VDROP_ICON,
    EM_DEV_CLAM_ICON,

    EM_DEV_HW_LEVEL_ICON,
    EM_DEV_HW_LEVEL_MLCD_CON_ICON,
    EM_DEV_HW_LEVEL_SLCD_CON_ICON,
    EM_DEV_HW_LEVEL_BATTERY_ICON,
    EM_DEV_HW_LEVEL_PWM1_ICON,
    EM_DEV_HW_LEVEL_PWM2_ICON,
    EM_DEV_HW_LEVEL_PWM3_ICON,

    /* GPRS */
    EM_GPRS_ACT_ICON,
    EM_GPRS_AUTO_ATTACH_ICON,
    EM_GPRS_ACTIVATE_PDP_ICON,
    EM_GPRS_DEACTIVATE_PDP_ICON,
    EM_GPRS_SEND_DATA_ICON,
    EM_GPRS_SEND_DATA_NORM_ICON,
    EM_GPRS_SEND_DATA_HDR_ICON,
    EM_GPRS_PING_ICON,
    EM_GPRS_PINGIP_ICON,
    EM_GPRS_PINGSIZE_ICON,
    EM_GPRS_PINGCOUNT_ICON,
    EM_GPRS_PINGTIMEOUT_ICON,
    EM_GPRS_PDP_CONTEXT_1_ICON,
    EM_GPRS_PDP_CONTEXT_2_ICON,
    EM_GPRS_PDP_CONTEXT_3_ICON,
    EM_GPRS_PDP_CONTEXT_4_ICON,
    EM_GPRS_PDP_CONTEXT_5_ICON,
    EM_GPRS_PDP_CONTEXT_6_ICON,
    EM_GPRS_PDP_CONTEXT_7_ICON,
    EM_GPRS_PDP_CONTEXT_8_ICON,
    EM_GPRS_PDP_CONTEXT_9_ICON,
    EM_GPRS_PDP_CONTEXT_10_ICON,
    EM_GPRS_PDP_CONTEXT_11_ICON,
    EM_GPRS_PDP_CONTEXT_12_ICON,
    EM_GPRS_PDP_CONTEXT_13_ICON,
    EM_GPRS_PDP_CONTEXT_14_ICON,
    EM_GPRS_PDP_CONTEXT_15_ICON,

    /* Band Selection */
    EM_BAND_SEL_ICON,
    EM_BAND_900_ICON,
    EM_BAND_1800_ICON,
    EM_BAND_DUAL_ICON,
    EM_BAND_1900_ICON,
    EM_BAND_850_ICON,
    /* Lisen 05312005 */
    EM_BAND_AUTO_ICON,

    /* MISC. WAP */
    EM_MISC_ICON,
    EM_AUTO_ANSWER_ICON,
    EM_BACKLIGHT_ICON,
    EM_SERIAL_PORT_EN_ICON,
    EM_WAP_ICON,
    EM_WAP_ENABLE_DEBUG_ICON,
    EM_WAP_OFFLINE_PAGE_ICON,
    EM_WAP_USER_AGENT_ICON,
    EM_WAP_USER_AGENT_MAUI_E800_ICON,
    EM_WAP_USER_AGENT_SONY_P800_ICON,
    EM_WAP_USER_AGENT_NOKIA_7250i_ICON,
    EM_WAP_USER_AGENT_SHARP_GX21_ICON,
    EM_WAP_USER_AGENT_SONY_T610_ICON,
    EM_WAP_USER_AGENT_SAMSUNG_ICON,
    EM_WAP_USER_AGENT_NOKIA_6230_ICON,
    EM_WAP_USER_AGENT_MOTO_V303_ICON,
    EM_WAP_USER_AGENT_SE_W800i_ICON,
    EM_WAP_USER_AGENT_SE_Z800_ICON,
    EM_WAP_ACCEPT_HEADER_ICON,
    EM_WAP_ACCEPT_HEADER_WAP121_ICON,
    EM_WAP_ACCEPT_HEADER_WAP20_ICON,
    EM_WAP_ACCEPT_HEADER_WML_ICON,
    EM_WAP_ACCEPT_HEADER_XHTML_ICON,
    EM_WAP_ACCEPT_HEADER_HTML_ICON,
    EM_WAP_MMS_VERSION_ICON,
    EM_WAP_MMS_VERSION_MMS_DEFAULT_ICON,
    EM_WAP_MMS_VERSION_MMS10_ICON,
    EM_WAP_MMS_VERSION_MMS11_ICON,
    EM_WAP_MMS_VERSION_MMS12_ICON,
    EM_POWER_ON_DURATION_ICON,
    EM_J2ME_TCK_ICON,
    EM_AUTO_RESET_ICON,
    EM_PWR_DOWN_CONTROL_ICON,
    EM_SW_PATCH_ICON,
    EM_AMR_ICON,
    EM_MMI_DEBUG_ICON,
    EM_MEMORY_DUMP_ICON,
    EM_FRM_PROFILING_ICON,
    EM_RAM_TEST_ICON,
    EM_SWDBG_ICON,
    EM_SWDBG_OFF_ICON,
    EM_SWDBG_DSP_L1_ICON,
    EM_SWDBG_DSP_PS_ICON,
    EM_SWDBG_L1_PS_ICON,
    EM_SWDBG_MCU_ICON,
    EM_SWDBG_DSP_L1_PS_ICON,
    EM_SWDBG_MCU_DSP_ICON,
    EM_SWDBG_MCU_DSP_IRDBG_ICON,
    EM_SWDBG_RESET_ICON,
    EM_AUTO_TEST_SETTING_ICON,
    EM_AUTO_TEST_OPTIONS_ICON,
    EM_AUTO_TEST_ADD_ICON,
    EM_AUTO_TEST_ENTER_PRIORITY_ICON,
    EM_AUTO_TEST_CHANGE_PRIORITY_ICON,
    EM_AUTO_TEST_REMOVE_ICON,

    /* DBG Info */
    IMG_ID_EM_DEBUG_INFO,
    IMG_ID_EM_FS_TRACE,
    IMG_ID_EM_LAST_EXCEPTION,

    IMG_ID_EM_SYS_STATS,
    IMG_ID_EM_WRITE_SYS_STATS,
    IMG_ID_EM_SAVING_STAT_PWROFF,

    /* Bluetooth */
    EM_BT_IMG_ID,
    EM_BT_ENTRY_TSMOD_IMG_ID,
    EM_BT_ENTRY_FW_VERSION_IMG_ID,
    EM_BT_ADD_SCO_LNK_IMG_ID,
    EM_BT_RMV_SCO_LNK_IMG_ID,
    EM_BT_ENTRY_TEST_IMG_ID,
    EM_BT_DEBUG_TRACE_IMG_ID,
    EM_BT_ADD_AUDIO_CONNECTION_IMG_ID,
    EM_BT_REMOVE_AUDIO_CONNECTION_IMG_ID,

    /* Socket */
    EM_SOCKET_ICON,
    EM_SOCKET_DNS_ICON,
    EM_SOCKET_HTTP_ICON,
    EM_SOCKET_ECHO_ICON,
    EM_SOCKET_DATE_ICON,

    /* BEGIN OF IPERF */
    EM_SOCKET_IPERF_ICON,
   	EM_SOCKET_IPERF_TCP_ICON,
   	EM_SOCKET_IPERF_UDP_ICON,
    /* END OF IPERF */

    EM_SOCKET_DNS_OPTION_ICON,
    EM_SOCKET_DNS_DONE_ICON,
    EM_SOCKET_DNS_INPUT_METHOD_ICON,
    EM_SOCKET_HTTP_OPTION_ICON,
    EM_SOCKET_HTTP_DONE_ICON,
    EM_SOCKET_HTTP_INPUT_METHOD_ICON,
    EM_DEV_PMIC_6318_ICON,
    EM_DEV_PMIC_6318_REGISTER_EDITOR_ICON,

    ENGINEER_MODE_ICON_END
} EM_ICON_IDS;


