/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *  BarcodeReaderResDefs.h
 *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  QR Code Reader Applications v0.1
 *
 * Author:
 * -------
 * -------
 *                      
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

/****************************************************************************
* Include Files                                                                
*****************************************************************************/
#ifndef MMI_BARCODEREADER_RES_DEF_H
#define MMI_BARCODEREADER_RES_DEF_H

#ifndef MMI_BARCODEREADER_FEATURES_H
#error "Include MMI_features_barcodereader.h before BarcodeReaderResDefs.h"
#endif 

#define MMI_BARCODEREADER_EV_BASE                   (BARCODEREADER_BASE+110)        /* reserve 20 for this */
#define MMI_BARCODEREADER_FLASH_BASE                (BARCODEREADER_BASE+130)
#define MMI_BARCODEREADER_STORAGE_BASE              (BARCODEREADER_BASE+150)
#define MMI_BARCODEREADER_FOCUS_MODE_BASE           (BARCODEREADER_BASE+170)
#define MMI_BARCODEREADER_BANDING_BASE              (BARCODEREADER_BASE+190)

#define MMI_BARCODEREADER_FLASH_ITEM_COUNT             (STR_ID_BARCODEREADER_FLASH_END-STR_ID_BARCODEREADER_FLASH_START-1)
#define MMI_BARCODEREADER_EV_ITEM_COUNT                (STR_ID_BARCODEREADER_EV_END-STR_ID_BARCODEREADER_EV_START-1)
#define MMI_BARCODEREADER_FOCUS_MODE_ITEM_COUNT        (STR_ID_BARCODEREADER_FOCUS_MODE_END-STR_ID_BARCODEREADER_FOCUS_MODE_START-1)
#define MMI_BARCODEREADER_STORAGE_ITEM_COUNT           (STR_ID_BARCODEREADER_STORAGE_END-STR_ID_BARCODEREADER_STORAGE_START-1)
#define MMI_BARCODEREADER_BANDING_ITEM_COUNT           (STR_ID_BARCODEREADER_BANDING_END-STR_ID_BARCODEREADER_BANDING_START-1)
/***************************************************************************** 
* Typedef ENUM
*****************************************************************************/
typedef enum
{
    SCR_ID_BARCODEREADER_MAIN = BARCODEREADER_BASE + 1,
    SCR_ID_BARCODEREADER_PREVIEW,
    SCR_ID_BARCODEREADER_FILELIST_STORAGE_SELECT,
    SCR_ID_BARCODEREADER_FILELIST,
    SCR_ID_BARCODEREADER_FILELIST_OPTION,
    SCR_ID_BARCODEREADER_SERVICE_SUMMARY,
    SCR_ID_BARCODEREADER_HELP,
    SCR_ID_BARCODEREADER_SETTING,
    SCR_ID_BARCODEREADER_APP_PREVIEW,
    SCR_ID_BARCODEREADER_APP_PREVIEW_OPTION,
    SCR_ID_BARCODEREADER_TIP,
    SCR_ID_BARCODEREADER_EDITOR,
    SCR_ID_BARCODEREADER_ORDER_CONFIRM,
    SCR_ID_BARCODEREADER_URL,
    SCR_ID_BARCODEREADER_PHONEBOOK_MULTI_CONTENT_SEL,
    SCR_ID_BARCODEREADER_OPTION_STORAGE,
    SCR_ID_BARCODEREADER_OPTION,
    SCR_ID_BARCODEREADER_SAVE,
    SCR_ID_BARCODEREADER_ALL
} barcodereader_scr_id_enum;

/***************************************************************************** 
* Typedef IMAGE ID 
*****************************************************************************/
typedef enum
{
    /* QR code reader app */
    STR_ID_BARCODEREADER_APP_NAME = BARCODEREADER_BASE + 1,
    STR_ID_BARCODEREADER_PREVIEW,
    STR_ID_BARCODEREADER_RECOGNIZE,
    STR_ID_BARCODEREADER_SETTING,
    
    /*encoding error*/
    STR_ID_BARCODEREADER_ENCODING_ERROR,
    STR_ID_BARCODEREADER_DECODE_FAILED,
    STR_ID_BARCODEREADER_ERROR_DECODE_TIMEOUT,
       
#ifdef __MMI_BARCODEREADER_OPERATOR1__
    /* main screen*/
    STR_ID_BARCODEREADER_FILELIST,
    STR_ID_BARCODEREADER_SERVICE_SUMMARY,
    STR_ID_BARCODEREADER_SERVICE_SUMMARY_CONTENT,
    STR_ID_BARCODEREADER_HELP,

    STR_ID_BARCODEREADER_HELP_START,
    STR_ID_BARCODEREADER_HELP_CONTENT1,
    STR_ID_BARCODEREADER_HELP_CONTENT2,
    STR_ID_BARCODEREADER_HELP_CONTENT3,
    STR_ID_BARCODEREADER_HELP_CONTENT4,
    STR_ID_BARCODEREADER_HELP_CONTENT5,
    STR_ID_BARCODEREADER_HELP_CONTENT6,
    STR_ID_BARCODEREADER_HELP_END,

    /*attribute string*/
    STR_ID_BARCODEREADER_ATTR_N,
    STR_ID_BARCODEREADER_ATTR_TIL,
    STR_ID_BARCODEREADER_ATTR_DIV,
    STR_ID_BARCODEREADER_ATTR_COR,
    STR_ID_BARCODEREADER_ATTR_ADR,
    STR_ID_BARCODEREADER_ATTR_ZIP,
    STR_ID_BARCODEREADER_ATTR_TEL,
    STR_ID_BARCODEREADER_ATTR_M,
    STR_ID_BARCODEREADER_ATTR_FAX,
    STR_ID_BARCODEREADER_ATTR_EM,
    STR_ID_BARCODEREADER_ATTR_URL,
    STR_ID_BARCODEREADER_ATTR_SM,
    STR_ID_BARCODEREADER_ATTR_TO,
    STR_ID_BARCODEREADER_ATTR_CT,
    STR_ID_BARCODEREADER_ATTR_TXT,
    STR_ID_BARCODEREADER_ATTR_INTR,
    STR_ID_BARCODEREADER_ATTR_TYPE,
    STR_ID_BARCODEREADER_ATTR_LEN,
    STR_ID_BARCODEREADER_ATTR_FILE,
    STR_ID_BARCODEREADER_ATTR_CR,
    STR_ID_BARCODEREADER_ATTR_SUB,
    STR_ID_BARCODEREADER_ATTR_DG,
    STR_ID_BARCODEREADER_ATTR_SID,

    STR_ID_BARCODEREADER_CALL,
    STR_ID_BARCODEREADER_MAIL,
    STR_ID_BARCODEREADER_ACCESS,
    STR_ID_BARCODEREADER_ADD_BM,

    STR_ID_BARCODEREADER_FILE_OPEN,
    STR_ID_BARCODEREADER_FILE_DELETE,
    STR_ID_BARCODEREADER_FILE_DELETE_ALL,
    STR_ID_BARCODEREADER_OPTION,

    /*fro smssell, wapsell, ivrsell*/
    STR_ID_BARCODEREADER_TO_ACCESSS,
    STR_ID_BARCODEREADER_SAVE_BOOKMARK,
    STR_ID_BARCODEREADER_TO_COMMEND,
    STR_ID_BARCODEREADER_TO_ORDER,
    STR_ID_BARCODEREADER_SERVICE_TEL,
    STR_ID_BARCODEREADER_TO_LISTEN,

    STR_ID_BARCODEREADER_RECOGNIZE_ERROR,
#endif

    /* option */
    STR_ID_BARCODEREADER_RESTORE_DEFAULT,
    STR_ID_BARCODEREADER_FOCUS_MODE,
    STR_ID_BARCODEREADER_FLASH,
    STR_ID_BARCODEREADER_EV,
    STR_ID_BARCODEREADER_STORAGE,
    STR_ID_BARCODEREADER_BANDING,

    /* Notify */
    STR_ID_BARCODEREADER_NOTIFY_DISK_FULL,
    STR_ID_BARCODEREADER_NOTIFY_NO_MEMORY_CARD,
    STR_ID_BARCODEREADER_NOTIFY_WRITE_PROTECTION,
    STR_ID_BARCODEREADER_NOTIFY_HW_NOT_READY,
    STR_ID_BARCODEREADER_NOTIFY_ERROR,
    STR_ID_BARCODEREADER_NOTIFY_RESTORE_DEFAULT_CONFIRM,
    STR_ID_BARCODEREADER_NOTIFY_CAPTURE_AND_DECODE,
    STR_ID_BARCODEREADER_NOTIFY_SEND_TO,
    STR_ID_BARCODEREADER_NOTIFY_CONTENT,

    /* Error String */
    STR_ID_BARCODEREADER_ERROR_OVER_VERSION,
    STR_ID_BARCODEREADER_ERROR_MEMORY_NOT_ENOUGH,
    STR_ID_BARCODEREADER_ERROR_BROKEN_IMAGE,

    /* 23key rsk string "capture" */
    STR_ID_BARCODEREADER_RSK_CAPTURE,

    /* Applications */
#ifndef __MMI_BARCODEREADER_OPERATOR1__
    STR_ID_BARCODEREADER_TO_CARD,
    STR_ID_BARCODEREADER_TO_CONTENT,
    STR_ID_BARCODEREADER_TO_BUSINESS,
    STR_ID_BARCODEREADER_TO_EMAIL,
    STR_ID_BARCODEREADER_TO_SMS,
    STR_ID_BARCODEREADER_TO_GENERAL,
#else
    STR_ID_BARCODEREADER_SMS,
    STR_ID_BARCODEREADER_DTXT,
    STR_ID_BARCODEREADER_EMAIL,
    STR_ID_BARCODEREADER_VCARD,
    STR_ID_BARCODEREADER_SMSSELL,
    STR_ID_BARCODEREADER_WAPSELL,
    STR_ID_BARCODEREADER_IVRSELL,
#endif
    /* Functions */
    STR_ID_BARCODEREADER_FUNC_SAVE_TO_FOLDER,
    STR_ID_BARCODEREADER_FUNC_SEND_BY_SMS,
    STR_ID_BARCODEREADER_FUNC_SAVE_SMS,
    STR_ID_BARCODEREADER_FUNC_SAVE_TO_PHONEBOOK,
    STR_ID_BARCODEREADER_FUNC_SEND_BY_EMAIL,
    STR_ID_BARCODEREADER_FUNC_OPEN_URL,
    STR_ID_BARCODEREADER_FUNC_SAVE_URL,
    STR_ID_BARCODEREADER_FUNC_ORDER,
    STR_ID_BARCODEREADER_FUNC_MAKE_CALL,
    STR_ID_BARCODEREADER_FUNC_SAVE_EMAIL,
    STR_ID_BARCODEREADER_FUNC_EDIT_BY_EMAIL,  

#ifndef __MMI_BARCODEREADER_OPERATOR1__
    STR_ID_BARCODEREADER_FUNC_EXIT,
    STR_ID_BARCODEREADER_FUNC_EDIT_BY_MMS,
    STR_ID_BARCODEREADER_FUNC_EDIT_BY_SMS,
     
#else
    STR_ID_BARCODEREADER_FUNC_PREVIEW,
    STR_ID_BARCODEREADER_FUNC_BACK_TO_MAIN,
    STR_ID_BARCODEREADER_FUNC_SEND_BY_MMS,
    STR_ID_BARCODEREADER_FUNC_COMMEND,
#endif
    
    /* misc */
    STR_ID_BARCODEREADER_ORDER_CONFIRM,
    STR_ID_BARCODEREADER_ORDER_ATTENTION,

    /* append barcode */
    STR_ID_BARCODEREADER_RSK_CONTINUE,
    STR_ID_BARCODEREADER_LSK_RESET,
    STR_ID_BARCODEREADER_HELP_WRONG_SERIES,
    STR_ID_BARCODEREADER_HELP_DUPLICATED_CODE,
    STR_ID_BARCODEREADER_HELP_APPEND_BARCODE,
    STR_ID_BARCODEREADER_HELP_DECODE_NEXT,
    
    /* Total string count */
    STR_ID_BARCODEREADER_TOTAL_COUNT
} barcodereader_str_id_enum;

/***************** ev *******************/
typedef enum
{
    STR_ID_BARCODEREADER_EV_START = MMI_BARCODEREADER_EV_BASE,

#ifdef __MMI_BARCODEREADER_EV_4__
    STR_ID_BARCODEREADER_EV_N4,
#endif 

#ifdef __MMI_BARCODEREADER_EV_3__
    STR_ID_BARCODEREADER_EV_N3,
#endif 

#ifdef __MMI_BARCODEREADER_EV_2__
    STR_ID_BARCODEREADER_EV_N2,
#endif 

    STR_ID_BARCODEREADER_EV_N1,
    STR_ID_BARCODEREADER_EV_0,
    STR_ID_BARCODEREADER_EV_P1,

#ifdef __MMI_BARCODEREADER_EV_2__
    STR_ID_BARCODEREADER_EV_P2,
#endif 

#ifdef __MMI_BARCODEREADER_EV_3__
    STR_ID_BARCODEREADER_EV_P3,
#endif 

#ifdef __MMI_BARCODEREADER_EV_4__
    STR_ID_BARCODEREADER_EV_P4,
#endif 

    STR_ID_BARCODEREADER_EV_END
} barcodereader_ev_str_id_enum;

/***************** flash *******************/
typedef enum
{
    STR_ID_BARCODEREADER_FLASH_START = MMI_BARCODEREADER_FLASH_BASE,

    STR_ID_BARCODEREADER_FLASH_OFF,
    STR_ID_BARCODEREADER_FLASH_ON,

    STR_ID_BARCODEREADER_FLASH_END
} barcodereader_flash_str_id_enum;

/***************** storage *******************/
typedef enum
{
    STR_ID_BARCODEREADER_STORAGE_START = MMI_BARCODEREADER_STORAGE_BASE,

    STR_ID_BARCODEREADER_STORAGE_PHONE,
    STR_ID_BARCODEREADER_STORAGE_MEMORY_CARD,

    STR_ID_BARCODEREADER_STORAGE_END
} barcodereader_storage_str_id_enum;

/***************** focus mode *******************/
typedef enum
{
    STR_ID_BARCODEREADER_FOCUS_MODE_START = MMI_BARCODEREADER_FOCUS_MODE_BASE,
    STR_ID_BARCODEREADER_FOCUS_MODE_AUTO,
#ifdef __MMI_BARCODEREADER_FOCUS_MODE_MACRO__
    STR_ID_BARCODEREADER_FOCUS_MODE_MACRO,
#endif 
#ifdef __MMI_BARCODEREADER_FOCUS_MODE_INFINITE__
    STR_ID_BARCODEREADER_FOCUS_MODE_INFINITE,
#endif 
#ifdef __MMI_BARCODEREADER_FOCUS_MODE_MANUAL__
    STR_ID_BARCODEREADER_FOCUS_MODE_MANUAL,
#endif 

    STR_ID_BARCODEREADER_FOCUS_MODE_END
} barcodereader_af_mode_str_id_enum;

/***************** banding *******************/

typedef enum
{
    STR_ID_BARCODEREADER_BANDING_START = MMI_BARCODEREADER_BANDING_BASE,

    STR_ID_BARCODEREADER_BANDING_50HZ,
    STR_ID_BARCODEREADER_BANDING_60HZ,

    STR_ID_BARCODEREADER_BANDING_END
} banding_banding_str_id_enum;

typedef enum
{
    IMG_ID_BARCODEREADER_APP_ICON = BARCODEREADER_BASE + 1,

    /******************************************
    * Menu Icon 
    *******************************************/
    IMG_ID_BARCODEREADER_PREVIEW_ICON,
#ifdef __MMI_BARCODEREADER_OPERATOR1__
    IMG_ID_BARCODEREADER_FILELIST_ICON,
    IMG_ID_BARCODEREADER_SERVICE_SUMMARY_ICON,
    IMG_ID_BARCODEREADER_HELP_ICON,
    IMG_ID_BARCODEREADER_SETTING_ICON,
#endif
    /******************************************
    * Menu Icon 
    *******************************************/
    IMG_ID_BARCODEREADER_MENUICON_FLASH,
    IMG_ID_BARCODEREADER_MENUICON_STORAGE,
    IMG_ID_BARCODEREADER_MENUICON_EV,
    IMG_ID_BARCODEREADER_MENUICON_FOCUS_MODE,
    IMG_ID_BARCODEREADER_MENUICON_BANDING,
    
    /******************************************
    * OSD Icon 
    *******************************************/
    IMG_ID_BARCODEREADER_OSD_EV_INC,
    IMG_ID_BARCODEREADER_OSD_EV_INC_SEL,
    IMG_ID_BARCODEREADER_OSD_EV_DEC,
    IMG_ID_BARCODEREADER_OSD_EV_DEC_SEL,
    IMG_ID_BARCODEREADER_OSD_MF_INC,
    IMG_ID_BARCODEREADER_OSD_MF_INC_SEL,
    IMG_ID_BARCODEREADER_OSD_MF_DEC,
    IMG_ID_BARCODEREADER_OSD_MF_DEC_SEL,
    IMG_ID_BARCODEREADER_OSD_MF_BAR,
    IMG_ID_BARCODEREADER_OSD_MF_SLIDER,
    IMG_ID_BARCODEREADER_OSD_CAPTURE,
    IMG_ID_BARCODEREADER_OSD_CAPTURE_SEL,

   /******************************************
   * MISC
   *******************************************/
    IMG_ID_BARCODEREADER_PREVIEW_SUBLCD_ICON,
    IMG_ID_BARCODEREADER_PREVIEW_BACKGROUND,

    /******************************************
    * FUNCS
    *******************************************/
    /* Applications */
    IMG_ID_BARCODEREADER_TO_CARD,
    IMG_ID_BARCODEREADER_TO_CONTENT,
    IMG_ID_BARCODEREADER_TO_BUSINESS,
    IMG_ID_BARCODEREADER_TO_EMAIL,
    IMG_ID_BARCODEREADER_TO_SMS,
    IMG_ID_BARCODEREADER_TO_GENERAL,

    /* Functions */
    IMG_ID_BARCODEREADER_FUNC_SAVE,
    IMG_ID_BARCODEREADER_FUNC_EXIT,
    IMG_ID_BARCODEREADER_FUNC_SAVE_TO_PHONEBOOK,
    IMG_ID_BARCODEREADER_FUNC_EDIT_BY_MMS,
    IMG_ID_BARCODEREADER_FUNC_EDIT_BY_SMS,
    IMG_ID_BARCODEREADER_FUNC_EDIT_BY_EMAIL,
    IMG_ID_BARCODEREADER_FUNC_ORDER,
    IMG_ID_BARCODEREADER_FUNC_SAVE_URL,
    IMG_ID_BARCODEREADER_FUNC_OPEN_URL,
    IMG_ID_BARCODEREADER_FUNC_SEND_BY_EMAIL,
    IMG_ID_BARCODEREADER_FUNC_SEND_BY_SMS,
    IMG_ID_BARCODEREADER_FUNC_MAKE_CALL,
    IMG_ID_BARCODEREADER_FUNC_SAVE_SMS,
    IMG_ID_BARCODEREADER_FUNC_SAVE_EMAIL,

    IMG_ID_BARCODEREADER_TOTAL_COUNT
} IMG_BARCODEREADER_ID;

/***************** flash *******************/
typedef enum
{
    IMG_ID_BARCODEREADER_OSD_FLASH_START = MMI_BARCODEREADER_FLASH_BASE,

    IMG_ID_BARCODEREADER_OSD_FLASH_OFF,
    IMG_ID_BARCODEREADER_OSD_FLASH_ON,
    IMG_ID_BARCODEREADER_OSD_FLASH_OFF_SEL,
    IMG_ID_BARCODEREADER_OSD_FLASH_ON_SEL,
    IMG_ID_BARCODEREADER_OSD_FLASH_END
} barcodereader_flash_img_id_enum;

/***************** ev *******************/
typedef enum
{
    IMG_ID_BARCODEREADER_OSD_EV_START = MMI_BARCODEREADER_EV_BASE,

#ifdef __MMI_BARCODEREADER_EV_4__
    IMG_ID_BARCODEREADER_OSD_EV_N4,
#endif 

#ifdef __MMI_BARCODEREADER_EV_3__
    IMG_ID_BARCODEREADER_OSD_EV_N3,
#endif 

#ifdef __MMI_BARCODEREADER_EV_2__
    IMG_ID_BARCODEREADER_OSD_EV_N2,
#endif 

    IMG_ID_BARCODEREADER_OSD_EV_N1,
    IMG_ID_BARCODEREADER_OSD_EV_0,
    IMG_ID_BARCODEREADER_OSD_EV_P1,

#ifdef __MMI_BARCODEREADER_EV_2__
    IMG_ID_BARCODEREADER_OSD_EV_P2,
#endif 

#ifdef __MMI_BARCODEREADER_EV_3__
    IMG_ID_BARCODEREADER_OSD_EV_P3,
#endif 

#ifdef __MMI_BARCODEREADER_EV_4__
    IMG_ID_BARCODEREADER_OSD_EV_P4,
#endif 

    IMG_ID_BARCODEREADER_OSD_EV_END
} barcodereader_ev_img_id_enum;

typedef enum
{
    IMG_ID_BARCODEREADER_OSD_FOCUS_MODE_START = MMI_BARCODEREADER_FOCUS_MODE_BASE,

    IMG_ID_BARCODEREADER_OSD_FOCUS_MODE_AUTO,

#ifdef __MMI_BARCODEREADER_FOCUS_MODE_MACRO__
    IMG_ID_BARCODEREADER_OSD_FOCUS_MODE_MACRO,
#endif 

#ifdef __MMI_BARCODEREADER_FOCUS_MODE_MANUAL__
    IMG_ID_BARCODEREADER_OSD_FOCUS_MODE_MANUAL,
#endif 

    IMG_ID_BARCODEREADER_OSD_FOCUS_MODE_AUTO_SEL,

#ifdef __MMI_BARCODEREADER_FOCUS_MODE_MACRO__
    IMG_ID_BARCODEREADER_OSD_FOCUS_MODE_MACRO_SEL,
#endif 

#ifdef __MMI_BARCODEREADER_FOCUS_MODE_MANUAL__
    IMG_ID_BARCODEREADER_OSD_FOCUS_MODE_MANUAL_SEL,
#endif 

    IMG_ID_BARCODEREADER_OSD_FOCUS_MODE_END
} barcodereader_focus_mode_img_id_enum;

/***************** storage *******************/
typedef enum
{
    IMG_ID_BARCODEREADER_OSD_STORAGE_START = MMI_BARCODEREADER_STORAGE_BASE,

    IMG_ID_BARCODEREADER_OSD_STORAGE_PHONE,
    IMG_ID_BARCODEREADER_OSD_STORAGE_MEMORY_CARD,

    IMG_ID_BARCODEREADER_OSD_STORAGE_PHONE_SEL,
    IMG_ID_BARCODEREADER_OSD_STORAGE_MEMORY_CARD_SEL,

    IMG_ID_BARCODEREADER_OSD_STORAGE_END
} barcodereader_storage_img_id_enum;

/***************** banding *******************/

typedef enum
{
    IMG_ID_BARCODEREADER_BANDING_START = MMI_BARCODEREADER_BANDING_BASE,

    IMG_ID_BARCODEREADER_BANDING_50HZ,
    IMG_ID_BARCODEREADER_BANDING_60HZ,

    IMG_ID_BARCODEREADER_BANDING_END
} banding_banding_img_id_enum;


/******* [Barcode Reader Option Menu Settings] ********/
typedef enum
{

#ifdef __MMI_BARCODEREADER_FLASH__
    MMI_BARCODEREADER_SETTING_FLASH,
#endif 

    MMI_BARCODEREADER_SETTING_EV,

#ifdef __MMI_BARCODEREADER_STORAGE__
    MMI_BARCODEREADER_SETTING_STORAGE,
#endif 

#ifdef __MMI_BARCODEREADER_FOCUS_MODE__
    MMI_BARCODEREADER_SETTING_FOCUS_MODE,
#endif 

#ifdef __MMI_BARCODEREADER_BANDING__
    MMI_BARCODEREADER_SETTING_BANDING,
#endif

    MMI_BARCODEREADER_SETTING_ITEM_COUNT
} barcodereader_setting_count_enum;

#endif /* _MMI_BARCODEREADER_RES_DEF_H_ */ /* _CAMERA_RES_DEF_H_ */

