/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 * BrowserResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   This file is contains enums for screen, image and strings.
 *
 * Author:
 * -------
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/

#ifndef BROWSERRESDEF_H
#define BROWSERRESDEF_H

#include "MMI_features.h"

#ifdef __MMI_BROWSER_2__
#include "MMIDataType.h"

#define BROWSER_BASE				JATAAYU_BROWSER_BASE
#define BROWSER_PROVISIONING_BASE	BROWSER_BASE + 500
#define BROWSER_PUSH_BASE			BROWSER_PROVISIONING_BASE+100

/* Image ID's */
typedef enum
{
    IMG_ID_BRW_WAP = BROWSER_BASE + 1,
    IMG_ID_BRW_HOMEPAGE,
    IMG_ID_BRW_BOOKMARKS,
	IMG_ID_BRW_BOOKMARKS_FOLDER_ICON,
	IMG_ID_BRW_BOOKMARKS_DEFAULT_FILE,
	IMG_ID_BRW_BOOKMARKS_USER_FILE,
    IMG_ID_BRW_RECENT_PAGES,
    IMG_ID_BRW_ENTER_ADDRESS,
	IMG_ID_BRW_OPEN_FILE,
	IMG_ID_BRW_LAST_WEB_ADDR,
	IMG_ID_BRW_STORED_PAGES,
    IMG_ID_BRW_PUSH_INBOX,
    IMG_ID_BRW_SETTINGS,
    IMG_ID_BRW_CONNECTION_STATUS_CSD,
    IMG_ID_BRW_CONNECTION_STATUS_GPRS,
    IMG_ID_BRW_CONNECTION_STATUS_WIFI,
    IMG_ID_BRW_CONNECTION_STATUS_CSD_STATIC,
    IMG_ID_BRW_CONNECTION_STATUS_GPRS_STATIC,
    IMG_ID_BRW_CONNECTION_STATUS_WIFI_STATIC,
	IMG_ID_BRW_ACTIVE_HMPAGE_SETTINGS,
	IMG_ID_BRW_SPLASH_SCREEN,
	IMG_ID_BRW_PAGE_OBJECTS,
	IMG_ID_BRW_TRUSTED_CERTS,
	IMG_ID_BRW_DO_ELEMENTS,

	/*Added by Ritesh for push module*//*START*/
    IMG_ID_BRW_PUSH_READ,
    IMG_ID_BRW_PUSH_UNREAD,
    IMG_ID_BRW_PUSH_EXPIRED_READ,
	IMG_ID_BRW_PUSH_EXPIRED_UNREAD
	/*Added by Ritesh for push module*//*END*/

} IMG_ID_BRW_ENUM;

/* String ID's */
typedef enum
{
    STR_ID_BRW_INTERNET_SERVICES = BROWSER_BASE + 1,
    STR_ID_BRW_HOMEPAGE,
    STR_ID_BRW_BOOKMARKS,
    STR_ID_BRW_ENTER_ADDRESS,
	STR_ID_BRW_OPEN_FILE,
	STR_ID_BRW_LAST_WEB_ADDR,
    STR_ID_BRW_RECENT_PAGES,
	STR_ID_BRW_RECENT_HOSTS,
	STR_ID_BRW_STORED_PAGES,
    //STR_ID_BRW_PUSH_INBOX,
    STR_ID_BRW_SETTINGS,
    STR_ID_BRW_EDIT_PROFILE,
    STR_ID_BRW_BROWSER_OPTIONS,
	STR_ID_BRW_PREFERENCES,
	STR_ID_BRW_SECURITY_SETTINGS,
	//STR_ID_BRW_PUSH_SETTINGS,
	STR_ID_BRW_RESTORE_BROWSER_SETTINGS,
    STR_ID_BRW_GOTO,
    STR_ID_BRW_EDIT,
    STR_ID_BRW_SET_AS_HOMEPAGE,
	STR_ID_BRW_ADD_TO_BOOKMARK,
	STR_ID_BRW_SEND_ADDRESS,
	STR_ID_BRW_SEND_BOOKMARK,
    STR_ID_BRW_DELETE,
    STR_ID_BRW_DELETE_ALL,
	STR_ID_BRW_SORT,
	STR_ID_BRW_SORT_BY_DATE,
	STR_ID_BRW_SORT_BY_SITE,
	STR_ID_BRW_SORT_BY_LAST_VISITED,
	STR_ID_BRW_SORT_BY_MOST_VISITED,
	STR_ID_BRW_THIS_LINK,
	STR_ID_BRW_NAVIGATE,
	STR_ID_BRW_THIS_PAGE,
	STR_ID_BRW_SELECT_MODE,
	STR_ID_BRW_PROPERTIES,
	STR_ID_BRW_RENAME,
	STR_ID_BRW_MEMORY_STATUS,
	STR_ID_BRW_TITLE,
    STR_ID_BRW_ADDRESS,
	STR_ID_BRW_PAGE_SIZE,
	STR_ID_BRW_DATE,
	STR_ID_BRW_USER_DEFINED,
	STR_ID_BRW_ACTIVE_PROFILE,
	STR_ID_BRW_USE_CURRENT_PAGE,
	STR_ID_BRW_USE_BLANK,
    STR_ID_BRW_VIEW,
	STR_ID_BRW_ACTIVATE,
	STR_ID_BRW_RENDERING_MODES,
	STR_ID_BRW_STANDARD,
	STR_ID_BRW_TEXT_WRAP,
	STR_ID_BRW_SCREEN_OPTIMIZED,
	STR_ID_BRW_TEXT_ONLY,
	STR_ID_BRW_NAVIGATION_MODES,
	STR_ID_BRW_FOUR_WAY,
	STR_ID_BRW_TWO_WAY,
	STR_ID_BRW_SCROLLING,
	STR_ID_BRW_SCREEN_SIZE,
	STR_ID_BRW_SMALL,
	STR_ID_BRW_MEDIUM,
	STR_ID_BRW_FULL,
	STR_ID_BRW_LARGE,
	STR_ID_BRW_ENCODING,
    STR_ID_BRW_TRUSTED_CERTIFICATES,
	STR_ID_BRW_SAVE_AS,
	STR_ID_BRW_STORE_OFFLINE,
	STR_ID_BRW_PAGE_OBJECTS,
	STR_ID_BRW_PAGE_PROPERTIES,
	STR_ID_BRW_HOMEPAGE_SETTINGS,
    STR_ID_BRW_VIA_INFRARED,
	STR_ID_BRW_VIA_BLUETOOTH,
	STR_ID_BRW_VIA_EMAIL,
	STR_ID_BRW_THUMBNAIL,
	STR_ID_BRW_SESSION_INFO,
	STR_ID_BRW_CURRENT_CERTIFICATE,
    STR_ID_BRW_TIMEOUT,
    STR_ID_BRW_SHOW_IMAGES,
	STR_ID_BRW_SHOW_VIDEOS,
	STR_ID_BRW_PLAY_SOUNDS,
	STR_ID_BRW_LOAD_UNKNOWN_MEDIA,
	STR_ID_BRW_CSS,
	STR_ID_BRW_SCRIPT,
	STR_ID_BRW_CACHE,
	STR_ID_BRW_COOKIE,
	STR_ID_BRW_SHORTCUTS,
	STR_ID_BRW_SECURITY_WARNINGS,
	STR_ID_BRW_SEND_DEVICE_ID,
	STR_ID_BRW_ENABLE,
	STR_ID_BRW_DISABLE,
	STR_ID_BRW_ALWAYS,
	STR_ID_BRW_NEVER,
    STR_ID_BRW_INVAL_TIMEOUT,
	STR_ID_BRW_NAME,
    STR_ID_BRW_CONTENT_SIZE,
	STR_ID_BRW_RESTORE_BROWSER_SETTINGS_CONFIRM,
    STR_ID_BRW_REFRESH,
	STR_ID_BRW_FORWARD,
	STR_ID_BRW_BACKWARD,
	STR_ID_BRW_PAGE_ACTIONS,
	STR_ID_BRW_ENTER_NAME,
	STR_ID_BRW_OPEN,
	STR_ID_BRW_CLEAR_AUTH_INFO,
	STR_ID_BRW_CREATE_FOLDER,
	STR_ID_BRW_COPY_TO,
	STR_ID_BRW_MOVE_TO,
	STR_ID_BRW_NORMAL,
	STR_ID_BRW_IMAGES,
	STR_ID_BRW_BG_IMAGES,
	STR_ID_BRW_SOUNDS,
	STR_ID_BRW_OTHERS,
    STR_ID_BRW_MAKE_CALL,
    STR_ID_BRW_ADD_ENTRY,
	STR_ID_BRW_READ_ONLY_PROFILE,
    STR_ID_BRW_INVALID_URL,
    STR_ID_BRW_NO_HISTORY,
    STR_ID_BRW_EXIT,
	STR_ID_BRW_MODIFY,
	STR_ID_BRW_INVALID_PARAM,
	STR_ID_BRW_ERROR_COMMUNICATION,
	STR_ID_BRW_HOST_NOT_FOUND,
	STR_ID_BRW_REQUEST_TIMEOUT,
	STR_ID_BRW_CONNECTION_FAILED,
	STR_ID_BRW_SECURE_CONNECTION_FAILED,
	STR_ID_BRW_ERROR_AUTHENTICATION,
	STR_ID_BRW_SECURE_CONNECTION_CANCELLED,
	STR_ID_BRW_PAGE_NOT_FOUND,
	STR_ID_BRW_PAGE_ALREADY_EXISTS,
	STR_ID_BRW_REQUEST_FAILED,
	STR_ID_BRW_PAGE_SAVED_PARTIALLY,
	STR_ID_BRW_PAGE_LIMIT_EXCEEDED,
	STR_ID_BRW_UNSUPPORTED_SCHEME,
	STR_ID_BRW_UNSUPPORTED_ENCODING,
	STR_ID_BRW_SYNTAX_ERROR,
	STR_ID_BRW_UNKNOWN_DOC_TYPE,
	STR_ID_BRW_UNSUPPORTED_WBXML,
	STR_ID_BRW_DOC_VALIDATION_ERROR,
	STR_ID_BRW_PARSER_NOT_INITIALIZED,
	STR_ID_BRW_INTERNAL_ERROR,
	STR_ID_BRW_RESEND_POST_WARNING,
	STR_ID_BRW_OUT_OF_MEMORY,
	STR_ID_BRW_CONTENT_TOO_LARGE,
	STR_ID_BRW_RESET,
	STR_ID_BRW_INVAL_CHANNEL_ID,
	STR_ID_BRW_INVAL_REQUEST_ID,
	STR_ID_BRW_INVAL_SEQUENCE_NUM,
	STR_ID_BRW_SAVE,
	STR_ID_BRW_SAVE_BOTH,
	STR_ID_BRW_SAVE_ONLY_USERNAME,
	STR_ID_BRW_DELETE_ALL_FILES,
	STR_ID_BRW_SAVE_TO_BOOKMARK,
	STR_ID_BRW_INVALID_TITLE,
    STR_ID_BRW_FILE_ALREADY_EXISTS,
	STR_ID_BRW_FOLDER_ALREADY_EXISTS,
	STR_ID_BRW_FILE_CREATION_ERROR,
    STR_ID_BRW_FILENAME_EMPTY,
    STR_ID_BRW_FILE_SYSTEM_ERROR,
	STR_ID_BRW_INVALID_BOOKMARK_FILE,
	STR_ID_BRW_SAVE_NONE,
	STR_ID_BRW_FONT_SIZE,
	STR_ID_BRW_UNSUPPORTED_ACTION,
    STR_ID_BRW_ACTIVATE_PROFILE,
	STR_ID_BRW_ERR_WML_ACCESS_VIOLATION,
	STR_ID_BRW_ERR_WML_SCRIPT_ACCESS_VIOLATION,
	STR_ID_BRW_ERROR_LOW_MEMORY,
	STR_ID_BRW_FILE_ALREADY_EXISTS_REPLACE,
	STR_ID_BRW_CHARSET_AUTO_SELECT,
	STR_ID_BRW_ACCESS_DENIED,
	STR_ID_BRW_NOT_FOUND,
	STR_ID_BRW_REQUEST_ABORTED,
	STR_ID_BRW_NOT_ENOUGH_MEM,
	STR_ID_BRW_INPUT_METHOD,
    STR_ID_BRW_DOWNLOADS,
    STR_ID_BRW_WAP_NOT_READY,
	STR_ID_BRW_BKGRD_DOWNLOAD_SUSPEND,
	STR_ID_BRW_EMPTY_TRUSTED_CERT_LIST,
    STR_ID_BRW_OPTION,
    STR_ID_BRW_EDIT_BOOKMARK,
    STR_ID_BRW_ADD_BOOKMARK,
	STR_ID_BRW_ENCODING_METHODS,
	STR_ID_BRW_OPTIONS,
	STR_ID_BRW_SELECT,
	STR_ID_BRW_SAVE_BOOKMARK,
	STR_ID_BRW_DELETE_BOOKMARK,
	STR_ID_BRW_DELETE_ALL_BOOKMARK,
    STR_ID_BRW_EMPTY,
    STR_ID_BRW_PLEASE_WAIT,
	STR_ID_BRW_AUTHENTICATION,
    STR_ID_BRW_USER_NAME,
    STR_ID_BRW_PASSWORD,
	STR_ID_BRW_CLEAR_CACHE,
	STR_ID_BRW_CLEAR_COOKIE,
	STR_ID_BRW_TEXT_MESSAGE,
	STR_ID_BRW_MULTIMEDIA_MESSAGE,
	STR_ID_BRW_DONE,
	STR_ID_BRW_CANCEL,
	STR_ID_BRW_BYTES,
	STR_ID_BRW_UNKNOWN,
	STR_ID_BRW_FILE_PATH_LEN_EXCEEDED,
	STR_ID_BRW_AVAILABLE,
	STR_ID_BRW_ALLOCATED,
	STR_ID_BRW_TOTAL,
	STR_ID_BRW_KBYTES,
	STR_ID_BRW_DIR_PATH_TOO_DEEP,
	STR_ID_BRW_ACTIVATE_JAVA,
	STR_ID_BRW_SEND_SMS_TO,
	STR_ID_BRW_SEND_MMS_TO,
	STR_ID_BRW_NOT_SUPPORTED

} STR_ID_BRW_ENUM;

/* Screen ID's */
typedef enum
{
	SCR_ID_BRW_FIRST_SCREEN_ID = BROWSER_BASE,
	/*please add all screen IDs below this line*/

    SCR_ID_BRW_INTERNET_SERVICES,
    SCR_ID_BRW_BOOKMARKS,
    SCR_ID_BRW_BOOKMARK_OPTIONS,
    SCR_ID_BRW_EDIT_BOOKMARK,
    SCR_ID_BRW_ADD_BOOKMARK,
    SCR_ID_BRW_RECENT_PAGES,
    SCR_ID_BRW_RECENT_PAGE_OPTIONS,
    SCR_ID_BRW_ENTER_ADDRESS,
    SCR_ID_BRW_ENTER_URL,
    SCR_ID_BRW_SETTINGS,
    SCR_ID_BRW_BROWSER_OPTIONS,
    SCR_ID_BRW_RENDERED_PAGE_OPTIONS,
	SCR_ID_BRW_ENTER_ADDRESS_OPTIONS,
	SCR_ID_BRW_SEND_ADDRESS_OPTIONS,
	SCR_ID_BRW_SORT_RECENT_PAGES,
	SCR_ID_BRW_STORED_PAGES,
	SCR_ID_BRW_STORED_PAGE_OPTIONS,
	SCR_ID_BRW_REN_PAGE_SETTINGS,
	SCR_ID_BRW_HOMEPAGE_SETTINGS,
	SCR_ID_BRW_USER_DEFINED_HOMEPAGE,
	SCR_ID_BRW_ACTIVE_PROFILE_HOMEPAGE,
	SCR_ID_BRW_SECURITY_SETTINGS,
	SCR_ID_BRW_USER_DEFINED_HOMEPAGE_MODIFY,
	SCR_ID_BRW_RENDERING_MODES,
	SCR_ID_BRW_NAVIGATION_MODES,
	SCR_ID_BRW_BROWSER_PREFERENCES,
	SCR_ID_BRW_ENCODING_METHODS,
	SCR_ID_BRW_BROWSER_MAIN,
	SCR_ID_BRW_REN_PAGE_THIS_LINK,
	SCR_ID_BRW_REN_PAGE_THIS_PAGE,
	SCR_ID_BRW_FONT_SIZE,
	SCR_ID_BRW_MEMORY_STATUS,
	SCR_ID_BRW_STORED_PAGE_PROPERTIES,
	SCR_ID_BRW_STORED_PAGE_RENAME,
	SCR_ID_BRW_USER_DEFINED_HMPAGE_EDIT,
	SCR_ID_BRW_USER_DEFINED_HMPAGE_VIEW,
	SCR_ID_BRW_ACTIVE_PROFILE_HMPAGE_VIEW,
	SCR_ID_BRW_VIEW_URL,
	SCR_ID_BRW_TRUSTED_CERTIFICATES,
	SCR_ID_BRW_TRUSTED_CERTIFICATES_OPTIONS,
	SCR_ID_BRW_SESSION_INFO,
	SCR_ID_BRW_TRUSTED_CERTIFICATES_VIEW,
	SCR_ID_BRW_NAVIGATE,
	SCR_ID_BRW_PAGE_ACTIONS,
	SCR_ID_BRW_EDIT_STORE_OFFLINE,
	SCR_ID_BRW_THIS_PAGE_PROPERTIES,
	SCR_ID_BRW_OBJECT_PROPERTIES,
	SCR_ID_BRW_BKM_CREATE_FOLDER,
	SCR_ID_BRW_PAGE_OBJECT_TYPES,
	SCR_ID_BRW_PAGE_OBJECTS,
	SCR_ID_BRW_PAGE_OBJECTS_OPTIONS,
	SCR_ID_BRW_SHOW_AUTH_DIALOG,
	SCR_ID_BRW_CURRENT_CERT,
	SCR_ID_BRW_RECENT_PAGES_HOST,
	SCR_ID_BRW_RECENT_PAGE_HOST_OPTIONS,
	SCR_ID_BRW_ACTIVE_PROFILE_HMPAGE_EDIT,
	SCR_ID_BRW_BUSY_SCREEN,
	SCR_ID_BRW_SHOW_AUTH_DLG_OPTIONS,
	SCR_ID_BRW_VIEW_BOOKMARK,
	SCR_ID_BRW_BOOKMARK_BROWSE_PATH,
	SCR_ID_BRW_BOOKMARK_BROWSE_PATH_OPTIONS,
	SCR_ID_BRW_BOOKMARK_SEND_BOOKMARK_OPTIONS,
	SCR_ID_BRW_SAVE_TO_BOOKMARK,
	SCR_ID_BRW_BOOKMARK_OPEN_FROM_FMGR,
	SCR_ID_BRW_IRDA_FORWARD_PROCESSING,
	SCR_ID_BRW_SELECT_BOOKMARK,
	SCR_ID_BRW_EDITOR_OPTION,
	SCR_ID_BRW_DUMMY,
	SCR_ID_BRW_TEMP_BUSY_SCREEN,
	SCR_ID_BRW_EDIT_BOOKMARK_FROM_FMGR,

	/*please add all screen IDs above this line*/
	SCR_ID_BRW_LAST_SCREEN_ID
} SCR_ID_BRW_ENUM;

#endif /* __MMI_BROWSER_2__ */ 
#endif /* BROWSERRESDEF_H */ 

