/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *  CameraResDefs.h
 *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  Define Camera related resource IDs
 *
 * Author:
 * -------
 * -------
 *                      
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#ifndef _CAMERA_RES_DEF_H_
#define _CAMERA_RES_DEF_H_

#ifndef _CAMERA_FEATURES_H_
#error "Include MMI_features_camera.h before CameraResDefs.h"
#endif 

/***************************************************************************** 
* Define
*****************************************************************************/
/* camera setting */

#define CAMERA_WB_BASE              (CAMERA_BASE+110)   /* reserve 20 for this */
#define CAMERA_FLASH_BASE           (CAMERA_BASE+130)
#define CAMERA_LED_HIGHLIGHT        (CAMERA_BASE+140)
#define CAMERA_SHUTTER_SOUND_BASE   (CAMERA_BASE+150)
#define CAMERA_EV_BASE              (CAMERA_BASE+160)
#define CAMERA_NIGHT_BASE           (CAMERA_BASE+170)
#define CAMERA_CLOSEUP_BASE         (CAMERA_BASE+180)
#define CAMERA_BANDING_BASE         (CAMERA_BASE+190)
#define CAMERA_IMAGE_SIZE_BASE      (CAMERA_BASE+200)
#define CAMERA_IMAGE_QTY_BASE       (CAMERA_BASE+210)
#define CAMERA_EFFECT_BASE          (CAMERA_BASE+220)   /* reserve 30 for this */
#define CAMERA_ADD_FRAME_BASE       (CAMERA_BASE+250)   /* reserve 60 for this */
#define CAMERA_CONT_SHOT_BASE       (CAMERA_BASE+310)
#define CAMERA_DELAY_TIMER_BASE     (CAMERA_BASE+330)
#define CAMERA_STORAGE_BASE         (CAMERA_BASE+340)
#define CAMERA_AE_METER_BASE        (CAMERA_BASE+350)
#define CAMERA_ISO_BASE             (CAMERA_BASE+360)
#define CAMERA_ZOOM_BASE            (CAMERA_BASE+370)   /* reserve 40 for this */
#define CAMERA_ICONLIST_BASE        (CAMERA_BASE+410)   /* reserve 30 for this */
#define CAMERA_ICONLIST_SEL_BASE    (CAMERA_BASE+440)   /* reserve 30 for this */
#define CAMERA_DSC_MODE_BASE        (CAMERA_BASE+470)   /* reserve 20 for this */
#define CAMERA_AUTOFOCUS_BASE       (CAMERA_BASE+490)   /* reserve 20 for this */
#define CAMERA_AUTOFOCUS_MODE_BASE  (CAMERA_BASE+510)
#if defined(DOUBLE_CAMERA_SUPPORT)
//Huyanwei Add It 
#define CAMERA_DOUBLE_SWITCH_BASE  (CAMERA_BASE+550)
#endif

#define CAMERA_DSC_MODE_ITEM_COUNT              (STR_ID_CAMERA_DSC_MODE_END-STR_ID_CAMERA_DSC_MODE_START-1)
#define CAMERA_AUTOFOCUS_ITEM_COUNT             (STR_ID_CAMERA_AUTOFOCUS_END-STR_ID_CAMERA_AUTOFOCUS_START-1)
#define CAMERA_AUTOFOCUS_MODE_ITEM_COUNT        (STR_ID_CAMERA_AUTOFOCUS_MODE_END-STR_ID_CAMERA_AUTOFOCUS_MODE_START-1)

#define CAMERA_WB_ITEM_COUNT                    (STR_ID_CAMERA_WB_END-STR_ID_CAMERA_WB_START-1)
#define CAMERA_FLASH_ITEM_COUNT                 (STR_ID_CAMERA_FLASH_END-STR_ID_CAMERA_FLASH_START-1)
#define CAMERA_LCD_HIGHLIGHT_ITEM_COUNT         (STR_ID_CAMERA_LED_HIGHLIGHT_END-STR_ID_CAMERA_LED_HIGHLIGHT_START-1)
#define CAMERA_SHUTTER_SOUND_ITEM_COUNT         (STR_ID_CAMERA_SHUTTER_SOUND_END-STR_ID_CAMERA_SHUTTER_SOUND_START-1)
#define CAMERA_EV_ITEM_COUNT                    (STR_ID_CAMERA_EV_END-STR_ID_CAMERA_EV_START-1)
#define CAMERA_NIGHT_ITEM_COUNT                 (STR_ID_CAMERA_NIGHT_END-STR_ID_CAMERA_NIGHT_START-1)
#define CAMERA_CLOSEUP_ITEM_COUNT               (STR_ID_CAMERA_CLOSEUP_END-STR_ID_CAMERA_CLOSEUP_START-1)
#define CAMERA_BANDING_ITEM_COUNT               (STR_ID_CAMERA_BANDING_END-STR_ID_CAMERA_BANDING_START-1)
#define CAMERA_AE_METER_ITEM_COUNT              (STR_ID_CAMERA_AE_METER_END-STR_ID_CAMERA_AE_METER_START-1)
#define CAMERA_ISO_ITEM_COUNT                   (STR_ID_CAMERA_ISO_END-STR_ID_CAMERA_ISO_START-1)

#define CAMERA_IMAGE_SIZE_ITEM_COUNT            (STR_ID_CAMERA_IMAGE_SIZE_END-STR_ID_CAMERA_IMAGE_SIZE_START-1)
#define CAMERA_IMAGE_QTY_ITEM_COUNT             (STR_ID_CAMERA_IMAGE_QTY_END-STR_ID_CAMERA_IMAGE_QTY_START-1)

#define CAMERA_EFFECT_SETTING_ITEM_COUNT        (STR_ID_CAMERA_EFFECT_END-STR_ID_CAMERA_EFFECT_START-1)
#define CAMERA_ADD_FRAME_ITEM_COUNT             (IMG_ID_CAMERA_ADD_FRAME_END-IMG_ID_CAMERA_ADD_FRAME_START)
#define CAMERA_CONT_SHOT_ITEM_COUNT             (STR_ID_CAMERA_CONT_SHOT_END-STR_ID_CAMERA_CONT_SHOT_START-1)
#define CAMERA_DELAY_TIMER_ITEM_COUNT           (STR_ID_CAMERA_DELAY_TIMER_END-STR_ID_CAMERA_DELAY_TIMER_START-1)
#define CAMERA_STORAGE_ITEM_COUNT               (STR_ID_CAMERA_STORAGE_END-STR_ID_CAMERA_STORAGE_START-1)

#define CAMERA_ICONLIST_ITEM_COUNT              (IMG_ID_CAMERA_ICONLIST_END-IMG_ID_CAMERA_ICONLIST_START-1)

#define CAMERA_ADD_FRAME_TYPE_COUNT             (STR_ID_CAMERA_ADD_FRAME_TYPE_END-STR_ID_CAMERA_ADD_FRAME_TYPE_START-1)
#define CAMERA_ADD_FRAME_COLOR_IDX_ITEM_COUNT   (IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_END-IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_START)

/***************************************************************************** 
* Typedef 
*****************************************************************************/
typedef enum
{
    SCR_ID_CAMERA_APP = CAMERA_BASE + 1,
    SCR_ID_CAMERA_OPTION,
    SCR_ID_CAMERA_CAMERA_SETTING,
    SCR_ID_CAMERA_IMAGE_SETTING,
    SCR_ID_CAMERA_EFFECT_SETTING,
    SCR_ID_CAMERA_ADD_FRAME,
    SCR_ID_CAMERA_ADD_FRAME_OPTION,
    SCR_ID_CAMERA_ADD_FRAME_VIEW,
    SCR_ID_CAMERA_CONT_SHOT,
    SCR_ID_CAMERA_DELAY_TIMER,
    SCR_ID_CAMERA_STORAGE,
    SCR_ID_CAMERA_EFFECT_SET_OPTION,
    SCR_ID_CAMERA_EFFECT_EDIT,
    SCR_ID_CAMERA_EFFECT_SAVE_OPTION,
    SCR_ID_CAMERA_ADD_FRAME_SET_OPTION,
    SCR_ID_CAMERA_RESTORE_DEFAULT,
    SCR_ID_CAMERA_DSC_MODE,
    SCR_ID_CAMERA_DSC_MODE_SETTING,
    SCR_ID_CAMERA_AUTOFOCUS_METERING,
    SCR_ID_CAMERA_AUTOFOCUS_MODE,
    SCR_ID_CAMERA_ISO,
    SCR_ID_CAMERA_WB,
    SCR_ID_CAMERA_WB_MANUAL,
    SCR_ID_CAMERA_WB_MANUAL_HELP,
    SCR_ID_CAMERA_SUBLCD_APP,
    SCR_ID_CAMERA_SUBLCD_OPTION,
    SCR_ID_CAMERA_SUBLCD_OPTION_FLASH,

    SCR_ID_CAMERA_EXTERNAL_REQUESET_SCREEN,
    /* screen snapshot */
    SCR_ID_CAMERA_SCREEN_SNAPSHOT
} camera_scr_id_enum;

typedef enum
{
    /* camera app */
    STR_ID_CAMERA_APP_NAME = CAMERA_BASE + 1,

    /* option */
    STR_ID_CAMERA_TO_IMGVIEW,
    STR_ID_CAMERA_CAMERA_SETTING,
    STR_ID_CAMERA_IMAGE_SETTING,
    STR_ID_CAMERA_EFFECT_SETTING,
    STR_ID_CAMERA_ADD_FRAME,
    STR_ID_CAMERA_CONT_SHOT,
    STR_ID_CAMERA_SELF_CAPTURE,
    STR_ID_CAMERA_RESTORE_DEFAULT,
    STR_ID_CAMERA_AUTOFOCUS_METERING,
    STR_ID_CAMERA_AUTOFOCUS_MODE,
    STR_ID_CAMERA_DSC_MODE,
    STR_ID_CAMERA_WB,
    STR_ID_CAMERA_WB_HELP,
    STR_ID_CAMERA_EXIT,

    /* camera setting */
    STR_ID_CAMERA_FLASH,
    STR_ID_CAMERA_LED_HIGHLIGHT,
    STR_ID_CAMERA_SHUTTER_SOUND,
    STR_ID_CAMERA_EV,
    STR_ID_CAMERA_NIGHT,
    STR_ID_CAMERA_CLOSEUP,
    STR_ID_CAMERA_BANDING,
    STR_ID_CAMERA_AE_METER,
    STR_ID_CAMERA_ISO,
    STR_ID_CAMERA_DELAY_TIMER,
    STR_ID_CAMERA_STORAGE,

    /* image setting */
    STR_ID_CAMERA_IMAGE_SIZE,
    STR_ID_CAMERA_IMAGE_QTY,

    /* effect setting menu */
    STR_ID_CAMERA_EFFECT_CUSTOM_FX_SET,
    STR_ID_CAMERA_EFFECT_CUSTOM_FX_EDIT_EFFECT,
    STR_ID_CAMERA_EFFECT_CUSTOM_FX_EDIT_SAVE,
    STR_ID_CAMERA_EFFECT_CUSTOM_FX_EDIT_RESTORE_DEFAULT,

    STR_ID_CAMERA_EFFECT_CUSTOM_FX_BRIGHTNESS,
    STR_ID_CAMERA_EFFECT_CUSTOM_FX_SATURATION,
    STR_ID_CAMERA_EFFECT_CUSTOM_FX_CONTRAST,
    STR_ID_CAMERA_EFFECT_CUSTOM_FX_HUE,

    /* add frame menu */
    STR_ID_CAMERA_ADD_FRAME_SET,
    STR_ID_CAMERA_ADD_FRAME_DE_ASSOCIATE,
    STR_ID_CAMERA_ADD_FRAME_REPLACE,

    /* Notify */
    STR_ID_CAMERA_NOTIFY_DISK_FULL,
    STR_ID_CAMERA_NOTIFY_NO_MEMORY_CARD,
    STR_ID_CAMERA_NOTIFY_WRITE_PROTECTION,
    STR_ID_CAMERA_NOTIFY_HW_NOT_READY,
    STR_ID_CAMERA_NOTIFY_ERROR,
    STR_ID_CAMERA_NOTIFY_NO_CARD_SWITCH_DEFAULT,
    STR_ID_CAMERA_NOTIFY_SELF_CAPTURE_ON,
    STR_ID_CAMERA_NOTIFY_SELF_CAPTURE_OFF,
    STR_ID_CAMERA_NOFITY_SELF_CAPTURE_SUBLCD_PREVIEW,
    STR_ID_CAMERA_NOFIFY_CAPTURING,
    STR_ID_CAMERA_NOFIFY_BURST_CAPTURING,
    STR_ID_CAMERA_NOTIFY_SAVING,
    STR_ID_CAMERA_NOTIFY_SAVING_FAIL,
    STR_ID_CAMERA_NOTIFY_RESTORE_DEFAULT_CONFIRM,
    STR_ID_CAMERA_NOTIFY_SAVE_CONFIRM,
    STR_ID_CAMERA_NOTIFY_CHANGE_SIZE_FOR_ADD_FRAME,
    STR_ID_CAMERA_NOTIFY_CAPTURE_FAILED,
    STR_ID_CAMERA_NOTIFY_SCREEN_CAPTURED,
    STR_ID_CAMERA_NOTIFY_BT_IS_WORKING,
    STR_ID_CAMERA_NOTIFY_XENON_TIMEOUT,
    STR_ID_CAMERA_NOTIFY_XENON_LOW_BATTERY,

    /* 23key rsk string "capture" */
    STR_ID_CAMERA_RSK_CAPTURE,

    /* Image Size Strings */
    STR_ID_CAMERA_IMAGE_SIZE_2048x1536,
    STR_ID_CAMERA_IMAGE_SIZE_1600x1200,
    STR_ID_CAMERA_IMAGE_SIZE_1280x1024,
    STR_ID_CAMERA_IMAGE_SIZE_1280x960,
    STR_ID_CAMERA_IMAGE_SIZE_800x600,
    STR_ID_CAMERA_IMAGE_SIZE_640x480,
    STR_ID_CAMERA_IMAGE_SIZE_320x240,
    STR_ID_CAMERA_IMAGE_SIZE_160x120,
    STR_ID_CAMERA_IMAGE_SIZE_80x60,
    STR_ID_CAMERA_IMAGE_SIZE_80x56,
    STR_ID_CAMERA_IMAGE_SIZE_240x320,
    STR_ID_CAMERA_IMAGE_SIZE_176x220,
    STR_ID_CAMERA_IMAGE_SIZE_128x160,
    STR_ID_CAMERA_IMAGE_SIZE_128x128,
    STR_ID_CAMERA_IMAGE_SIZE_96x64,
    STR_ID_CAMERA_IMAGE_SIZE_128x85,    /* 96x64 scale to 128 width */
    STR_ID_CAMERA_IMAGE_SIZE_UNDEFINE,

	#if defined(DOUBLE_CAMERA_SUPPORT)
	//Huyanwei Add It 
	STR_ID_CAMERA_IMAGE_DOUBLE_MODE,
	STR_ID_CAMERA_IMAGE_DOUBLE_MODE_MASTER,
	STR_ID_CAMERA_IMAGE_DOUBLE_MODE_SILVER,	
	#endif

    /* Total string count */
    STR_ID_CAMERA_TOTAL_COUNT
} camera_str_id_enum;

/* use compile options to wrap following setting, for customization inline selection */

/***************** wb *******************/
typedef enum
{
    STR_ID_CAMERA_WB_START = CAMERA_WB_BASE,

#ifdef __CAMERA_FEATURE_WB_AUTO__
    STR_ID_CAMERA_WB_AUTO,
#endif 

#ifdef __CAMERA_FEATURE_WB_DAYLIGHT__
    STR_ID_CAMERA_WB_DAYLIGHT,
#endif 

#ifdef __CAMERA_FEATURE_WB_TUNGSTEN__
    STR_ID_CAMERA_WB_TUNGSTEN,
#endif 

#ifdef __CAMERA_FEATURE_WB_FLUORESCENT__
    STR_ID_CAMERA_WB_FLUORESCENT,
#endif 

#ifdef __CAMERA_FEATURE_WB_CLOUD__
    STR_ID_CAMERA_WB_CLOUD,
#endif 

#ifdef __CAMERA_FEATURE_WB_INCANDESCENCE__
    STR_ID_CAMERA_WB_INCANDESCENCE,
#endif 

#ifdef __CAMERA_FEATURE_WB_MANUAL__
    STR_ID_CAMERA_WB_MANUAL,
#endif 
    STR_ID_CAMERA_WB_END
} camera_wb_str_id_enum;

/***************** auto focus  *******************/
typedef enum
{
    STR_ID_CAMERA_AUTOFOCUS_START = CAMERA_AUTOFOCUS_BASE,
#ifdef __CAMERA_AUTOFOCUS_1_ZONE__
    STR_ID_CAMERA_AUTOFOCUS_1_ZONE,
#endif 
#ifdef __CAMERA_AUTOFOCUS_3_ZONE__
    STR_ID_CAMERA_AUTOFOCUS_3_ZONE,
#endif 
#ifdef __CAMERA_AUTOFOCUS_5_ZONE__
    STR_ID_CAMERA_AUTOFOCUS_5_ZONE,
#endif 
    STR_ID_CAMERA_AUTOFOCUS_END
} camera_af_str_id_enum;

typedef enum
{
    STR_ID_CAMERA_AUTOFOCUS_MODE_START = CAMERA_AUTOFOCUS_MODE_BASE,
#ifdef __CAMERA_AUTOFOCUS_MODE_AUTO__
    STR_ID_CAMERA_AUTOFOCUS_MODE_AUTO,
#endif 
#ifdef __CAMERA_AUTOFOCUS_MODE_MACRO__
    STR_ID_CAMERA_AUTOFOCUS_MODE_MACRO,
#endif 
#ifdef __CAMERA_AUTOFOCUS_MODE_INFINITE__
    STR_ID_CAMERA_AUTOFOCUS_MODE_INFINITE,
#endif 
#ifdef __CAMERA_AUTOFOCUS_MODE_MANUAL__
    STR_ID_CAMERA_AUTOFOCUS_MODE_MANUAL,
#endif 

    STR_ID_CAMERA_AUTOFOCUS_MODE_END
} camera_af_mode_str_id_enum;

/***************** DSC mode  *******************/
typedef enum
{
    STR_ID_CAMERA_DSC_MODE_START = CAMERA_DSC_MODE_BASE,
#ifdef __CAMERA_DSC_MODE_AUTO__
    STR_ID_CAMERA_DSC_MODE_AUTO,
#endif 
#ifdef __CAMERA_DSC_MODE_PORTRAIT__
    STR_ID_CAMERA_DSC_MODE_PORTRAIT,
#endif 
#ifdef __CAMERA_DSC_MODE_LANDSCAPE__
    STR_ID_CAMERA_DSC_MODE_LANDSCAPE,
#endif 
#ifdef __CAMERA_DSC_MODE_SPORT__
    STR_ID_CAMERA_DSC_MODE_SPORT,
#endif 
#ifdef __CAMERA_DSC_MODE_FLOWER__
    STR_ID_CAMERA_DSC_MODE_FLOWER,
#endif 
#ifdef __CAMERA_DSC_MODE_NIGHT__
    STR_ID_CAMERA_DSC_MODE_NIGHT,
#endif 
#ifdef __CAMERA_DSC_MODE_SHUTTER_PRI__
    STR_ID_CAMERA_DSC_MODE_SHUTTER_PRI,
#endif 
#ifdef __CAMERA_DSC_MODE_APERTURE_PRI__
    STR_ID_CAMERA_DSC_MODE_APERTURE_PRI,
#endif 

    STR_ID_CAMERA_DSC_MODE_END
} camera_dsc_mode_str_id_enum;

/***************** flash *******************/

typedef enum
{
    STR_ID_CAMERA_FLASH_START = CAMERA_FLASH_BASE,
#if defined(__CAMERA_FEATURE_FLASH__) || defined(__CAMERA_FEATURE_LED_HIGHLIGHT__)
    STR_ID_CAMERA_FLASH_OFF,
    STR_ID_CAMERA_FLASH_ON,
#endif

#ifdef __CAMERA_FEATURE_FLASH_AUTO__
    STR_ID_CAMERA_FLASH_AUTO,
#endif 

#ifdef __CAMERA_FEATURE_FLASH_REDEYE__
    STR_ID_CAMERA_FLASH_REDEYE,
#endif 

    STR_ID_CAMERA_FLASH_END
} camera_flash_str_id_enum;

/***************** led highlight *******************/
/* led highlight */
typedef enum
{
    STR_ID_CAMERA_LED_HIGHLIGHT_START = CAMERA_LED_HIGHLIGHT,
    STR_ID_CAMERA_LED_HIGHLIGHT_OFF,

#ifdef __CAMERA_FEATURE_LED_HIGHLIGHT_ON_OFF__
    STR_ID_CAMERA_LED_HIGHLIGHT_ON,
#endif /* __CAMERA_FEATURE_LED_HIGHLIGHT__ */

#ifdef __CAMERA_FEATURE_LED_HIGHLIGHT_7_COLOR__
    STR_ID_CAMERA_LED_HIGHLIGHT_WHITE,
    STR_ID_CAMERA_LED_HIGHLIGHT_RED,
    STR_ID_CAMERA_LED_HIGHLIGHT_GREEN,
    STR_ID_CAMERA_LED_HIGHLIGHT_BLUE,
    STR_ID_CAMERA_LED_HIGHLIGHT_YELLOW,
    STR_ID_CAMERA_LED_HIGHLIGHT_PURPLE,
    STR_ID_CAMERA_LED_HIGHLIGHT_CYAN,
#endif /* __CAMERA_FEATURE_LED_HIGHLIGHT_7_COLOR__ */ 

    STR_ID_CAMERA_LED_HIGHLIGHT_END
} camera_led_highlight_str_id_enum;

/***************** shutter sound *******************/

typedef enum
{
    STR_ID_CAMERA_SHUTTER_SOUND_START = CAMERA_SHUTTER_SOUND_BASE,

#ifdef __CAMERA_FEATURE_SHUTTER_SOUND_OFF__
    STR_ID_CAMERA_SHUTTER_SOUND_OFF,
#endif 

#ifdef __CAMERA_FEATURE_SHUTTER_SOUND_1__
    STR_ID_CAMERA_SHUTTER_SOUND_1,
#endif 

#ifdef __CAMERA_FEATURE_SHUTTER_SOUND_2__
    STR_ID_CAMERA_SHUTTER_SOUND_2,
#endif 

#ifdef __CAMERA_FEATURE_SHUTTER_SOUND_3__
    STR_ID_CAMERA_SHUTTER_SOUND_3,
#endif 

    STR_ID_CAMERA_SHUTTER_SOUND_END
} camera_shutter_sound_str_id_enum;

/***************** ev *******************/

typedef enum
{
    STR_ID_CAMERA_EV_START = CAMERA_EV_BASE,

#ifdef __CAMERA_FEATURE_EV_4__
    STR_ID_CAMERA_EV_N4,
#endif 

#ifdef __CAMERA_FEATURE_EV_3__
    STR_ID_CAMERA_EV_N3,
#endif 

#ifdef __CAMERA_FEATURE_EV_2__
    STR_ID_CAMERA_EV_N2,
#endif 
#ifdef __CAMERA_FEATURE_EV__
    STR_ID_CAMERA_EV_N1,
    STR_ID_CAMERA_EV_0,
    STR_ID_CAMERA_EV_P1,
#endif
#ifdef __CAMERA_FEATURE_EV_2__
    STR_ID_CAMERA_EV_P2,
#endif 

#ifdef __CAMERA_FEATURE_EV_3__
    STR_ID_CAMERA_EV_P3,
#endif 

#ifdef __CAMERA_FEATURE_EV_4__
    STR_ID_CAMERA_EV_P4,
#endif 

    STR_ID_CAMERA_EV_END
} camera_ev_str_id_enum;

/***************** night *******************/

typedef enum
{
    STR_ID_CAMERA_NIGHT_START = CAMERA_NIGHT_BASE,

    STR_ID_CAMERA_NIGHT_OFF,
    STR_ID_CAMERA_NIGHT_ON,

    STR_ID_CAMERA_NIGHT_END
} camera_night_str_id_enum;

/***************** closeup *******************/

typedef enum
{
    STR_ID_CAMERA_CLOSEUP_START = CAMERA_CLOSEUP_BASE,

    STR_ID_CAMERA_CLOSEUP_OFF,
    STR_ID_CAMERA_CLOSEUP_ON,

    STR_ID_CAMERA_CLOSEUP_END
} camera_closeup_str_id_enum;

/***************** banding *******************/

typedef enum
{
    STR_ID_CAMERA_BANDING_START = CAMERA_BANDING_BASE,
#ifdef __CAMERA_FEATURE_BANDING__
    STR_ID_CAMERA_BANDING_50HZ,
    STR_ID_CAMERA_BANDING_60HZ,
#endif
    STR_ID_CAMERA_BANDING_END
} camera_banding_str_id_enum;

/***************** image size *******************/
/* 
 * NOTICE, STR_ID_CAMERA_IMAGE_SIZE_XX is not used as string id, 
 * it is used to calucute CAMERA_IMAGE_SIZE_ITEM_COUNT
 * 
 * actual image size string is STR_ID_CAMERA_IMAGE_SIZE_128x128, etc.
 */
typedef enum
{
    STR_ID_CAMERA_IMAGE_SIZE_START = CAMERA_IMAGE_SIZE_BASE,

#ifdef __CAMERA_FEATURE_IMAGE_SIZE_SS__
    STR_ID_CAMERA_IMAGE_SIZE_SS,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_SIZE_S__
    STR_ID_CAMERA_IMAGE_SIZE_S,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_SIZE_M__
    STR_ID_CAMERA_IMAGE_SIZE_M,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_SIZE_L__
    STR_ID_CAMERA_IMAGE_SIZE_L,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_SIZE_LL__
    STR_ID_CAMERA_IMAGE_SIZE_LL,
#endif 

#if defined(__CAMERA_130W_CHEAT__) 
//Huyanwei Add It
    STR_ID_CAMERA_IMAGE_SIZE_LLL,
#endif

    STR_ID_CAMERA_IMAGE_SIZE_END
} camera_image_size_str_id_enum;

/***************** image qty *******************/
typedef enum
{
    STR_ID_CAMERA_IMAGE_QTY_START = CAMERA_IMAGE_QTY_BASE,

#ifdef __CAMERA_FEATURE_IMAGE_QTY_LOW__
    STR_ID_CAMERA_IMAGE_QTY_LOW,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_QTY_NORMAL__
    STR_ID_CAMERA_IMAGE_QTY_NORMAL,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_QTY_HIGH__
    STR_ID_CAMERA_IMAGE_QTY_HIGH,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_QTY_FINE__
    STR_ID_CAMERA_IMAGE_QTY_FINE,
#endif 

    STR_ID_CAMERA_IMAGE_QTY_END
} camera_image_qty_str_id_enum;

/***************** ae meter  *******************/
typedef enum
{
    STR_ID_CAMERA_AE_METER_START = CAMERA_AE_METER_BASE,

#ifdef __CAMERA_FEATURE_AE_METER_AUTO__
    STR_ID_CAMERA_AE_METER_AUTO,
#endif 

#ifdef __CAMERA_FEATURE_AE_METER_SPOT__
    STR_ID_CAMERA_AE_METER_SPOT,
#endif 

#ifdef __CAMERA_FEATURE_AE_METER_CENTER__
    STR_ID_CAMERA_AE_METER_CENTER,
#endif 

#ifdef __CAMERA_FEATURE_AE_METER_AVERAGE__
    STR_ID_CAMERA_AE_METER_AVERAGE,
#endif 

    STR_ID_CAMERA_AE_METER_END
} camera_ae_meter_str_id_enum;

/***************** iso  *******************/
typedef enum
{
    STR_ID_CAMERA_ISO_START = CAMERA_ISO_BASE,

#ifdef __CAEMRA_FEATURE_ISO_AUTO__
    STR_ID_CAMERA_ISO_AUTO,
#endif 

#ifdef __CAEMRA_FEATURE_ISO_100__
    STR_ID_CAMERA_ISO_100,
#endif 

#ifdef __CAEMRA_FEATURE_ISO_200__
    STR_ID_CAMERA_ISO_200,
#endif 

#ifdef __CAEMRA_FEATURE_ISO_400__
    STR_ID_CAMERA_ISO_400,
#endif 

    STR_ID_CAMERA_ISO_END
} camera_iso_str_id_enum;

/***************** effect setting  *******************/
typedef enum
{
    STR_ID_CAMERA_EFFECT_START = CAMERA_EFFECT_BASE,

#ifdef __CAMERA_FEATURE_EFFECT_NORMAL__
    STR_ID_CAMERA_EFFECT_NORMAL,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_GRAYSCALE__
    STR_ID_CAMERA_EFFECT_GRAYSCALE,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_SEPIA__
    STR_ID_CAMERA_EFFECT_SEPIA,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_SEPIA_GREEN__
    STR_ID_CAMERA_EFFECT_SEPIA_GREEN,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_SEPIA_BLUE__
    STR_ID_CAMERA_EFFECT_SEPIA_BLUE,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_COLOR_INVERT__
    STR_ID_CAMERA_EFFECT_COLOR_INVERT,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_GRAY_INVERT__
    STR_ID_CAMERA_EFFECT_GRAY_INVERT,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_BLACKBOARD__
    STR_ID_CAMERA_EFFECT_BLACKBOARD,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_WHITEBOARD__
    STR_ID_CAMERA_EFFECT_WHITEBOARD,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_COPPER_CARVING__
    STR_ID_CAMERA_EFFECT_COPPER_CARVING,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_BLUE_CARVING__
    STR_ID_CAMERA_EFFECT_BLUE_CARVING,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_EMBOSSMENT__
    STR_ID_CAMERA_EFFECT_EMBOSSMENT,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_CONTRAST__
    STR_ID_CAMERA_EFFECT_CONTRAST,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_JEAN__
    STR_ID_CAMERA_EFFECT_JEAN,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_SKETCH__
    STR_ID_CAMERA_EFFECT_SKETCH,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_OIL__
    STR_ID_CAMERA_EFFECT_OIL,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_CUSTOM_FX_1__
    STR_ID_CAMERA_EFFECT_CUSTOM_FX_1,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_CUSTOM_FX_2__
    STR_ID_CAMERA_EFFECT_CUSTOM_FX_2,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_CUSTOM_FX_3__
    STR_ID_CAMERA_EFFECT_CUSTOM_FX_3,
#endif 
    STR_ID_CAMERA_EFFECT_END
} camera_effect_str_id_enum;

/***************** add frame  *******************/
typedef enum
{
    STR_ID_CAMERA_ADD_FRAME_TYPE_START = CAMERA_ADD_FRAME_BASE,

#ifdef __CAMERA_FEATURE_ADD_FRAME_NORMAL__
    STR_ID_CAMERA_ADD_FRAME_NORMAL,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_TILESHOT__
    STR_ID_CAMERA_ADD_FRAME_TILESHOT,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX__
    STR_ID_CAMERA_ADD_FRAME_COLOR_IDX,
#endif 

    STR_ID_CAMERA_ADD_FRAME_TYPE_END
} camera_add_frame_type_enum;

typedef enum
{
    STR_ID_CAMERA_ADD_FRAME_START = STR_ID_CAMERA_ADD_FRAME_TYPE_END,
    STR_ID_CAMERA_ADD_FRAME_OFF,

#if defined(__CAMERA_FEATURE_ADD_FRAME_1__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_1__)
    STR_ID_CAMERA_ADD_FRAME_1,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_2__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_2__)
    STR_ID_CAMERA_ADD_FRAME_2,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_3__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_3__)
    STR_ID_CAMERA_ADD_FRAME_3,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_4__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_4__)
    STR_ID_CAMERA_ADD_FRAME_4,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_5__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_5__)
    STR_ID_CAMERA_ADD_FRAME_5,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_6__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_6__)
    STR_ID_CAMERA_ADD_FRAME_6,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_7__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_7__)
    STR_ID_CAMERA_ADD_FRAME_7,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_8__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_8__)
    STR_ID_CAMERA_ADD_FRAME_8,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_9__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_9__)
    STR_ID_CAMERA_ADD_FRAME_9,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_10__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_10__)
    STR_ID_CAMERA_ADD_FRAME_10,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_CUSTOM_1__
    STR_ID_CAMERA_ADD_FRAME_CUSTOM_1,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_CUSTOM_2__
    STR_ID_CAMERA_ADD_FRAME_CUSTOM_2,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_CUSTOM_3__
    STR_ID_CAMERA_ADD_FRAME_CUSTOM_3,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_CUSTOM_4__
    STR_ID_CAMERA_ADD_FRAME_CUSTOM_4,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_CUSTOM_5__
    STR_ID_CAMERA_ADD_FRAME_CUSTOM_5,
#endif 

    STR_ID_CAMERA_ADD_FRAME_END
} camera_add_frame_str_id_enum;

/***************** cont shot *******************/
typedef enum
{
    STR_ID_CAMERA_CONT_SHOT_START = CAMERA_CONT_SHOT_BASE,
#ifdef __CAMERA_FEATURE_CONT_SHOT__
    STR_ID_CAMERA_CONT_SHOT_OFF,
    STR_ID_CAMERA_CONT_SHOT_1,
#endif

#ifdef __CAMERA_FEATURE_CONT_SHOT_2__
    STR_ID_CAMERA_CONT_SHOT_2,
#endif 

#ifdef __CAMERA_FEATURE_CONT_SHOT_3__
    STR_ID_CAMERA_CONT_SHOT_3,
#endif 

#ifdef __CAMERA_FEATURE_CONT_SHOT_TILE__
    STR_ID_CAMERA_CONT_SHOT_TILE,
#endif 

#ifdef __CAMERA_FEATURE_CONT_SHOT_BURST__
    STR_ID_CAMERA_CONT_SHOT_BURST,
#endif 

    STR_ID_CAMERA_CONT_SHOT_END
} camera_cont_shot_str_id_enum;

/***************** delay timer *******************/
typedef enum
{
    STR_ID_CAMERA_DELAY_TIMER_START = CAMERA_DELAY_TIMER_BASE,
#ifdef __CAMERA_FEATURE_DELAY_TIMER__
    STR_ID_CAMERA_DELAY_TIMER_OFF,
    STR_ID_CAMERA_DELAY_TIMER_1,
#endif
#ifdef __CAMERA_FEATURE_DELAY_TIMER_2__
    STR_ID_CAMERA_DELAY_TIMER_2,
#endif 

#ifdef __CAMERA_FEATURE_DELAY_TIMER_3__
    STR_ID_CAMERA_DELAY_TIMER_3,
#endif 

    STR_ID_CAMERA_DELAY_TIMER_END
} camera_delay_timer_str_id_enum;

/***************** storage *******************/
typedef enum
{
    STR_ID_CAMERA_STORAGE_START = CAMERA_STORAGE_BASE,

    STR_ID_CAMERA_STORAGE_PHONE,
    STR_ID_CAMERA_STORAGE_MEMORY_CARD,

    STR_ID_CAMERA_STORAGE_END
} camera_storage_str_id_enum;

typedef enum
{
    IMG_ID_CAMERA_APP_ICON = CAMERA_BASE + 1,

   /******** menu ********/
    /* option menu */
    IMG_ID_CAMERA_TO_IMGVIEW,
    IMG_ID_CAMERA_CAMERA_SETTING,
    IMG_ID_CAMERA_IMAGE_SETTING,
    IMG_ID_CAMERA_EFFECT_SETTING,
    IMG_ID_CAMERA_ADD_FRAME,
    IMG_ID_CAMERA_CONT_SHOT,
    IMG_ID_CAMERA_SELF_CAPTURE,
    IMG_ID_CAMERA_RESTORE_DEFAULT,

    IMG_ID_CAMERA_ADD_FRAME_NORMAL,
    IMG_ID_CAMERA_ADD_FRAME_TILESHOT,
    IMG_ID_CAMERA_ADD_FRAME_COLOR_IDX,
    IMG_ID_CAMERA_AUTOFOCUS_METERING,
    IMG_ID_CAMERA_AUTOFOCUS_MODE,
    IMG_ID_CAMERA_DSC_MODE,
    IMG_ID_CAMERA_WB,

    /* dsc_mode x2 */
    IMG_ID_CAMERA_DSC_MODE_SHUTTER_PRI,
    IMG_ID_CAMERA_DSC_MODE_APERTURE_PRI,

    /* camera setting */
    IMG_ID_CAMERA_FLASH,
    IMG_ID_CAMERA_LED_HIGHLIGHT,
    IMG_ID_CAMERA_SHUTTER_SOUND,
    IMG_ID_CAMERA_EV,
    IMG_ID_CAMERA_NIGHT,
    IMG_ID_CAMERA_AE_METER,
    IMG_ID_CAMERA_CLOSEUP,
    IMG_ID_CAMERA_BANDING,
    IMG_ID_CAMERA_ISO,
    IMG_ID_CAMERA_EFFECT,
    IMG_ID_CAMERA_DELAY_TIMER,
    IMG_ID_CAMERA_STORAGE,

    /* image setting */
    IMG_ID_CAMERA_IMAGE_SIZE,
    IMG_ID_CAMERA_IMAGE_QTY,

    /* custom fx */
    IMG_ID_CAMERA_CUSTOM_FX_BIRIGHTNESS,
    IMG_ID_CAMERA_CUSTOM_FX_SATURATION,
    IMG_ID_CAMERA_CUSTOM_FX_CONTRAST,
    IMG_ID_CAMERA_CUSTOM_FX_HUE,

    /* osd */
    /* touch screen control for ev */
    IMG_ID_CAMERA_OSD_EV_INC,
    IMG_ID_CAMERA_OSD_EV_INC_SEL,
    IMG_ID_CAMERA_OSD_EV_DEC,
    IMG_ID_CAMERA_OSD_EV_DEC_SEL,

    /* touch screen control for zoom */
    IMG_ID_CAMERA_OSD_ZOOM_BAR,
    IMG_ID_CAMERA_OSD_ZOOM_SLIDER,
    IMG_ID_CAMERA_OSD_ZOOM_INC,
    IMG_ID_CAMERA_OSD_ZOOM_INC_SEL,
    IMG_ID_CAMERA_OSD_ZOOM_DEC,
    IMG_ID_CAMERA_OSD_ZOOM_DEC_SEL,

    /* capture button */
    IMG_ID_CAMERA_OSD_CAPTURE,
    IMG_ID_CAMERA_OSD_CAPTURE_SEL,

    /* zoom and mf toggle */
    IMG_ID_CAMERA_OSD_ZOOM_MF_TOGGLE,
    IMG_ID_CAMERA_OSD_ZOOM_MF_TOGGLE_MF,
    IMG_ID_CAMERA_OSD_ZOOM_MF_TOGGLE_ZOOM,
    IMG_ID_CAMERA_OSD_MF_BAR,
    IMG_ID_CAMERA_OSD_MF_SLIDER,
    IMG_ID_CAMERA_OSD_MF_INC,
    IMG_ID_CAMERA_OSD_MF_INC_SEL,
    IMG_ID_CAMERA_OSD_MF_DEC,
    IMG_ID_CAMERA_OSD_MF_DEC_SEL,

   /******** preview sublcd ********/
    IMG_ID_CAMERA_PREVIEW_SUBLCD_ICON,

   /******** preview mainlcd ********/
    IMG_ID_CAMERA_PREVIEW_BACKGROUND,

   /******** poplist ********/
    IMG_ID_CAMERA_POPLIST_TITLE_LEFT,
    IMG_ID_CAMERA_POPLIST_TITLE_RIGHT,
    IMG_ID_CAMERA_POPLIST_TITLE_CENTER,
    IMG_ID_CAMERA_POPLIST_BODY_LEFT,
    IMG_ID_CAMERA_POPLIST_BODY_RIGHT,
    IMG_ID_CAMERA_POPLIST_BODY_CENTER,
    IMG_ID_CAMERA_POPLIST_BOTTOM_LEFT,
    IMG_ID_CAMERA_POPLIST_BOTTOM_RIGHT,
    IMG_ID_CAMERA_POPLIST_BOTTOM_CENTER,
    IMG_ID_CAMERA_POPLIST_BOTTOM_CHAT_MARK,
    IMG_ID_CAMERA_POPLIST_BOTTOM_U_ARROW,
    IMG_ID_CAMERA_POPLIST_BOTTOM_U_ARROW_SEL,
    IMG_ID_CAMERA_POPLIST_BOTTOM_U_ARROW_DIS,
    IMG_ID_CAMERA_POPLIST_BOTTOM_D_ARROW,
    IMG_ID_CAMERA_POPLIST_BOTTOM_D_ARROW_SEL,
    IMG_ID_CAMERA_POPLIST_BOTTOM_D_ARROW_DIS,

   /******** iconlist ********/
    IMG_ID_CAMERA_ICONLIST_LEFT_ARROW,
    IMG_ID_CAMERA_ICONLIST_LEFT_ARROW_SEL,
    IMG_ID_CAMERA_ICONLIST_LEFT_ARROW_DIS,
    IMG_ID_CAMERA_ICONLIST_RIGHT_ARROW,
    IMG_ID_CAMERA_ICONLIST_RIGHT_ARROW_SEL,
    IMG_ID_CAMERA_ICONLIST_RIGHT_ARROW_DIS,
    IMG_ID_CAMERA_ICONLIST_HIDE,

   /******** iconbar ********/
    IMG_ID_CAMERA_ICONBAR_LEFT_ARROW,
    IMG_ID_CAMERA_ICONBAR_LEFT_ARROW_SEL,
    IMG_ID_CAMERA_ICONBAR_RIGHT_ARROW,
    IMG_ID_CAMERA_ICONBAR_RIGHT_ARROW_SEL,
    IMG_ID_CAMERA_ICONBAR_ITEM,
    IMG_ID_CAMERA_ICONBAR_ITEM_SEL,
    IMG_ID_CAMERA_ICONBAR_ITEM_DIS,

   /******** image size ********/
    IMG_ID_CAMERA_IMAGE_SIZE_2048x1536,
    IMG_ID_CAMERA_IMAGE_SIZE_1600x1200,
    IMG_ID_CAMERA_IMAGE_SIZE_1280x1024,
    IMG_ID_CAMERA_IMAGE_SIZE_1280x960,
    IMG_ID_CAMERA_IMAGE_SIZE_800x600,
    IMG_ID_CAMERA_IMAGE_SIZE_640x480,
    IMG_ID_CAMERA_IMAGE_SIZE_320x240,
    IMG_ID_CAMERA_IMAGE_SIZE_160x120,
    IMG_ID_CAMERA_IMAGE_SIZE_80x60,
    IMG_ID_CAMERA_IMAGE_SIZE_80x56,
    IMG_ID_CAMERA_IMAGE_SIZE_240x320,
    IMG_ID_CAMERA_IMAGE_SIZE_176x220,
    IMG_ID_CAMERA_IMAGE_SIZE_128x160,
    IMG_ID_CAMERA_IMAGE_SIZE_128x128,
    IMG_ID_CAMERA_IMAGE_SIZE_96x64,
    IMG_ID_CAMERA_IMAGE_SIZE_128x85,    /* 96x64 scale to 128 width */
    IMG_ID_CAMERA_IMAGE_SIZE_UNDEFINE,

    IMG_ID_CAMERA_FORWARD_TO_MMS,
    IMG_ID_CAMERA_FLASH_CHARGING,
    IMG_ID_CAMERA_FLASH_FULL,

    IMG_ID_CAMERA_TOTAL_COUNT
} IMG_CAMERA_ID;

/***************** wb *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_WB_START = CAMERA_WB_BASE,

#ifdef __CAMERA_FEATURE_WB_AUTO__
    IMG_ID_CAMERA_OSD_WB_AUTO,
#endif 

#ifdef __CAMERA_FEATURE_WB_DAYLIGHT__
    IMG_ID_CAMERA_OSD_WB_DAYLIGHT,
#endif 

#ifdef __CAMERA_FEATURE_WB_TUNGSTEN__
    IMG_ID_CAMERA_OSD_WB_TUNGSTEN,
#endif 

#ifdef __CAMERA_FEATURE_WB_FLUORESCENT__
    IMG_ID_CAMERA_OSD_WB_FLUORESCENT,
#endif 

#ifdef __CAMERA_FEATURE_WB_CLOUD__
    IMG_ID_CAMERA_OSD_WB_CLOUD,
#endif 

#ifdef __CAMERA_FEATURE_WB_INCANDESCENCE__
    IMG_ID_CAMERA_OSD_WB_INCANDESCENCE,
#endif 

#ifdef __CAMERA_FEATURE_WB_MANUAL__
    IMG_ID_CAMERA_OSD_WB_MANUAL,
#endif 
    IMG_ID_CAMERA_OSD_WB_LEFT_ARROW_UP,
    IMG_ID_CAMERA_OSD_WB_LEFT_ARROW_DOWN,
    IMG_ID_CAMERA_OSD_WB_RIGHT_ARROW_UP,
    IMG_ID_CAMERA_OSD_WB_RIGHT_ARROW_DOWN,

    IMG_ID_CAMERA_OSD_WB_END
} camera_wb_img_id_enum;

/***************** flash *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_FLASH_START = CAMERA_FLASH_BASE,

    IMG_ID_CAMERA_OSD_FLASH_OFF,
    IMG_ID_CAMERA_OSD_FLASH_ON,

#ifdef __CAMERA_FEATURE_FLASH_AUTO__
    IMG_ID_CAMERA_OSD_FLASH_AUTO,
#endif 

#ifdef __CAMERA_FEATURE_FLASH_REDEYE__
    IMG_ID_CAMERA_OSD_FLASH_REDEYE,
#endif 

    IMG_ID_CAMERA_OSD_FLASH_END
} camera_flash_img_id_enum;

/***************** led highlight *******************/
/* led highlight */
typedef enum
{
    IMG_ID_CAMERA_OSD_LED_HIGHLIGHT_START = CAMERA_LED_HIGHLIGHT,
    IMG_ID_CAMERA_OSD_LED_HIGHLIGHT_OFF,

#ifdef __CAMERA_FEATURE_LED_HIGHLIGHT_ON_OFF__
    /* on/off */
    IMG_ID_CAMERA_OSD_LED_HIGHLIGHT_ON,
#endif /* __CAMERA_FEATURE_LED_HIGHLIGHT_ON_OFF__ */ /* __CAMERA_FEATURE_LED_HIGHLIGHT__ */

#ifdef __CAMERA_FEATURE_LED_HIGHLIGHT_7_COLOR__
    /* 7 color */
    IMG_ID_CAMERA_OSD_LED_HIGHLIGHT_WHITE,
    IMG_ID_CAMERA_OSD_LED_HIGHLIGHT_RED,
    IMG_ID_CAMERA_OSD_LED_HIGHLIGHT_GREEN,
    IMG_ID_CAMERA_OSD_LED_HIGHLIGHT_BLUE,
    IMG_ID_CAMERA_OSD_LED_HIGHLIGHT_YELLOW,
    IMG_ID_CAMERA_OSD_LED_HIGHLIGHT_PURPLE,
    IMG_ID_CAMERA_OSD_LED_HIGHLIGHT_CYAN,
#endif /* __CAMERA_FEATURE_LED_HIGHLIGHT_7_COLOR__ */ 

    IMG_ID_CAMERA_OSD_LED_HIGHLIGHT_END
} camera_led_highlight_img_id_enum;

/***************** shutter sound *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_SHUTTER_SOUND_START = CAMERA_SHUTTER_SOUND_BASE,

#ifdef __CAMERA_FEATURE_SHUTTER_SOUND_OFF__
    IMG_ID_CAMERA_OSD_SHUTTER_SOUND_OFF,
#endif 

#ifdef __CAMERA_FEATURE_SHUTTER_SOUND_1__
    IMG_ID_CAMERA_OSD_SHUTTER_SOUND_1,
#endif 

#ifdef __CAMERA_FEATURE_SHUTTER_SOUND_2__
    IMG_ID_CAMERA_OSD_SHUTTER_SOUND_2,
#endif 

#ifdef __CAMERA_FEATURE_SHUTTER_SOUND_3__
    IMG_ID_CAMERA_OSD_SHUTTER_SOUND_3,
#endif 

    IMG_ID_CAMERA_OSD_SHUTTER_SOUND_END
} camera_shutter_sound_img_id_enum;

/***************** ev *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_EV_START = CAMERA_EV_BASE,

#ifdef __CAMERA_FEATURE_EV_4__
    IMG_ID_CAMERA_OSD_EV_N4,
#endif 

#ifdef __CAMERA_FEATURE_EV_3__
    IMG_ID_CAMERA_OSD_EV_N3,
#endif 

#ifdef __CAMERA_FEATURE_EV_2__
    IMG_ID_CAMERA_OSD_EV_N2,
#endif 

    IMG_ID_CAMERA_OSD_EV_N1,
    IMG_ID_CAMERA_OSD_EV_0,
    IMG_ID_CAMERA_OSD_EV_P1,

#ifdef __CAMERA_FEATURE_EV_2__
    IMG_ID_CAMERA_OSD_EV_P2,
#endif 

#ifdef __CAMERA_FEATURE_EV_3__
    IMG_ID_CAMERA_OSD_EV_P3,
#endif 

#ifdef __CAMERA_FEATURE_EV_4__
    IMG_ID_CAMERA_OSD_EV_P4,
#endif 

    IMG_ID_CAMERA_OSD_EV_END
} camera_ev_img_id_enum;

/***************** night *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_NIGHT_START = CAMERA_NIGHT_BASE,

    IMG_ID_CAMERA_OSD_NIGHT_OFF,
    IMG_ID_CAMERA_OSD_NIGHT_ON,

    IMG_ID_CAMERA_OSD_NIGHT_END
} camera_night_img_id_enum;

/***************** closeup *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_CLOSEUP_START = CAMERA_CLOSEUP_BASE,

    IMG_ID_CAMERA_OSD_CLOSEUP_OFF,
    IMG_ID_CAMERA_OSD_CLOSEUP_ON,

    IMG_ID_CAMERA_OSD_CLOSEUP_END
} camera_closeup_img_id_enum;

/***************** banding *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_BANDING_START = CAMERA_BANDING_BASE,

    IMG_ID_CAMERA_OSD_BANDING_50HZ,
    IMG_ID_CAMERA_OSD_BANDING_60HZ,

    IMG_ID_CAMERA_OSD_BANDING_END
} camera_banding_img_id_enum;

/***************** image size *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_IMAGE_SIZE_START = CAMERA_IMAGE_SIZE_BASE,

#ifdef __CAMERA_FEATURE_IMAGE_SIZE_SS__
    IMG_ID_CAMERA_OSD_IMAGE_SIZE_SS,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_SIZE_S__
    IMG_ID_CAMERA_OSD_IMAGE_SIZE_S,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_SIZE_M__
    IMG_ID_CAMERA_OSD_IMAGE_SIZE_M,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_SIZE_L__
    IMG_ID_CAMERA_OSD_IMAGE_SIZE_L,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_SIZE_LL__
    IMG_ID_CAMERA_OSD_IMAGE_SIZE_LL,
#endif 

#if defined(__CAMERA_130W_CHEAT__) 
    //Huyanwei Add it
    IMG_ID_CAMERA_OSD_IMAGE_SIZE_LLL,
   #endif

    IMG_ID_CAMERA_OSD_IMAGE_SIZE_END
} camera_image_size_img_id_enum;

/***************** image qty *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_IMAGE_QTY_START = CAMERA_IMAGE_QTY_BASE,

#ifdef __CAMERA_FEATURE_IMAGE_QTY_LOW__
    IMG_ID_CAMERA_OSD_IMAGE_QTY_LOW,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_QTY_NORMAL__
    IMG_ID_CAMERA_OSD_IMAGE_QTY_NORMAL,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_QTY_HIGH__
    IMG_ID_CAMERA_OSD_IMAGE_QTY_HIGH,
#endif 

#ifdef __CAMERA_FEATURE_IMAGE_QTY_FINE__
    IMG_ID_CAMERA_OSD_IMAGE_QTY_FINE,
#endif 

    IMG_ID_CAMERA_OSD_IMAGE_QTY_END
} camera_image_qty_img_id_enum;

/***************** effect  *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_EFFECT_START = CAMERA_EFFECT_BASE,

#ifdef __CAMERA_FEATURE_EFFECT_NORMAL__
    IMG_ID_CAMERA_OSD_EFFECT_NORMAL,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_GRAYSCALE__
    IMG_ID_CAMERA_OSD_EFFECT_GRAYSCALE,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_SEPIA__
    IMG_ID_CAMERA_OSD_EFFECT_SEPIA,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_SEPIA_GREEN__
    IMG_ID_CAMERA_OSD_EFFECT_SEPIA_GREEN,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_SEPIA_BLUE__
    IMG_ID_CAMERA_OSD_EFFECT_SEPIA_BLUE,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_COLOR_INVERT__
    IMG_ID_CAMERA_OSD_EFFECT_COLOR_INVERT,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_GRAY_INVERT__
    IMG_ID_CAMERA_OSD_EFFECT_GRAY_INVERT,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_BLACKBOARD__
    IMG_ID_CAMERA_OSD_EFFECT_BLACKBOARD,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_WHITEBOARD__
    IMG_ID_CAMERA_OSD_EFFECT_WHITEBOARD,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_COPPER_CARVING__
    IMG_ID_CAMERA_OSD_EFFECT_COPPER_CARVING,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_BLUE_CARVING__
    IMG_ID_CAMERA_OSD_EFFECT_BLUE_CARVING,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_EMBOSSMENT__
    IMG_ID_CAMERA_OSD_EFFECT_EMBOSSMENT,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_CONTRAST__
    IMG_ID_CAMERA_OSD_EFFECT_CONTRAST,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_JEAN__
    IMG_ID_CAMERA_OSD_EFFECT_JEAN,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_SKETCH__
    IMG_ID_CAMERA_OSD_EFFECT_SKETCH,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_OIL__
    IMG_ID_CAMERA_OSD_EFFECT_OIL,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_CUSTOM_FX_1__
    IMG_ID_CAMERA_OSD_EFFECT_CUSTOM_FX_1,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_CUSTOM_FX_2__
    IMG_ID_CAMERA_OSD_EFFECT_CUSTOM_FX_2,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT_CUSTOM_FX_3__
    IMG_ID_CAMERA_OSD_EFFECT_CUSTOM_FX_3,
#endif 
    IMG_ID_CAMERA_OSD_EFFECT_END
} camera_effect_img_id_enum;

/***************** ae meter  *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_AE_METER_START = CAMERA_AE_METER_BASE,

#ifdef __CAMERA_FEATURE_AE_METER_AUTO__
    IMG_ID_CAMERA_OSD_AE_METER_AUTO,
#endif 

#ifdef __CAMERA_FEATURE_AE_METER_SPOT__
    IMG_ID_CAMERA_OSD_AE_METER_SPOT,
#endif 

#ifdef __CAMERA_FEATURE_AE_METER_CENTER__
    IMG_ID_CAMERA_OSD_AE_METER_CENTER,
#endif 

#ifdef __CAMERA_FEATURE_AE_METER_AVERAGE__
    IMG_ID_CAMERA_OSD_AE_METER_AVERAGE,
#endif 

    IMG_ID_CAMERA_OSD_AE_METER_END
} camera_ae_meter_img_id_enum;

/***************** auto focus *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_FOCUS_METER_START = CAMERA_AUTOFOCUS_BASE,
#ifdef __CAMERA_AUTOFOCUS_1_ZONE__
    IMG_ID_CAMERA_OSD_AUTOFOCUS_1_ZONE,
#endif 
#ifdef __CAMERA_AUTOFOCUS_3_ZONE__
    IMG_ID_CAMERA_OSD_AUTOFOCUS_3_ZONE,
#endif 
#ifdef __CAMERA_AUTOFOCUS_5_ZONE__
    IMG_ID_CAMERA_OSD_AUTOFOCUS_5_ZONE,
#endif 

    IMG_ID_CAMERA_AUTOFOCUS_NORMAL_WHITE,
    IMG_ID_CAMERA_AUTOFOCUS_NORMAL_RED,
    IMG_ID_CAMERA_AUTOFOCUS_NORMAL_GREEN,
    IMG_ID_CAMERA_AUTOFOCUS_SMALL_WHITE,
    IMG_ID_CAMERA_AUTOFOCUS_SMALL_RED,
    IMG_ID_CAMERA_AUTOFOCUS_SMALL_GREEN,
    IMG_ID_CAMERA_AUTOFOCUS_SMALL_GRAY,
    IMG_ID_CAMERA_AUTOFOCUS_LARGE_WHITE,
    IMG_ID_CAMERA_AUTOFOCUS_LARGE_RED,
    IMG_ID_CAMERA_AUTOFOCUS_LARGE_GREEN,

    IMG_ID_CAMERA_OSD_AUTOFOCUS_END
} camera_autofocus_osd_id_enum;

typedef enum
{
    IMG_ID_CAMERA_OSD_FOCUS_MODE_START = CAMERA_AUTOFOCUS_MODE_BASE,
#ifdef __CAMERA_AUTOFOCUS_MODE_AUTO__
    IMG_ID_CAMERA_OSD_AUTOFOCUS_MODE_AUTO,
#endif 
#ifdef __CAMERA_AUTOFOCUS_MODE_MACRO__
    IMG_ID_CAMERA_OSD_AUTOFOCUS_MODE_MACRO,
#endif 
#ifdef __CAMERA_AUTOFOCUS_MODE_INFINITE__
    IMG_ID_CAMERA_OSD_AUTOFOCUS_MODE_INFINITE,
#endif 
#ifdef __CAMERA_AUTOFOCUS_MODE_MANUAL__
    IMG_ID_CAMERA_OSD_AUTOFOCUS_MODE_MANUAL,
#endif 

    IMG_ID_CAMERA_OSD_AUTOFOCUS_MODE_END
} camera_autofocus_mode_osd_id_enum;

#if defined(DOUBLE_CAMERA_SUPPORT)
//Huyanwei Add It 
typedef enum __CAMERA_SWITCH_IMAGE_ID
{
    IMG_ID_CAMERA_DOUBLE_START= CAMERA_DOUBLE_SWITCH_BASE ,
    IMG_ID_CAMERA_DOUBLE_0,
    IMG_ID_CAMERA_DOUBLE_1,
    IMG_ID_CAMERA_DOUBLE_END
}CAMERA_SWITCH_IMAGE_ID;
#endif


/***************** dsc mode  *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_DSC_MODE_START = CAMERA_DSC_MODE_BASE,
#ifdef __CAMERA_DSC_MODE_AUTO__
    IMG_ID_CAMERA_OSD_DSC_MODE_AUTO,
#endif 
#ifdef __CAMERA_DSC_MODE_SHUTTER_PRI__
    IMG_ID_CAMERA_OSD_DSC_MODE_SHUTTER_PRI,
#endif 
#ifdef __CAMERA_DSC_MODE_APERTURE_PRI__
    IMG_ID_CAMERA_OSD_DSC_MODE_APERTURE_PRI,
#endif 
#ifdef __CAMERA_DSC_MODE_PORTRAIT__
    IMG_ID_CAMERA_OSD_DSC_MODE_PORTRAIT,
#endif 
#ifdef __CAMERA_DSC_MODE_LANDSCAPE__
    IMG_ID_CAMERA_OSD_DSC_MODE_LANDSCAPE,
#endif 
#ifdef __CAMERA_DSC_MODE_SPORT__
    IMG_ID_CAMERA_OSD_DSC_MODE_SPORT,
#endif 
#ifdef __CAMERA_DSC_MODE_FLOWER__
    IMG_ID_CAMERA_OSD_DSC_MODE_FLOWER,
#endif 
#ifdef __CAMERA_DSC_MODE_NIGHT__
    IMG_ID_CAMERA_OSD_DSC_MODE_NIGHT,
#endif 

    IMG_ID_CAMERA_OSD_DSC_MODE_END
} camera_dsc_mode_img_id_enum;

/***************** iso  *******************/

typedef enum
{
    IMG_ID_CAMERA_OSD_ISO_START = CAMERA_ISO_BASE,

#ifdef __CAEMRA_FEATURE_ISO_AUTO__
    IMG_ID_CAMERA_OSD_ISO_AUTO,
#endif 

#ifdef __CAEMRA_FEATURE_ISO_100__
    IMG_ID_CAMERA_OSD_ISO_100,
#endif 

#ifdef __CAEMRA_FEATURE_ISO_200__
    IMG_ID_CAMERA_OSD_ISO_200,
#endif 

#ifdef __CAEMRA_FEATURE_ISO_400__
    IMG_ID_CAMERA_OSD_ISO_400,
#endif 

    IMG_ID_CAMERA_OSD_ISO_END
} camera_iso_img_id_enum;

/***************** add frame osd icon  *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_ADD_FRAME_START = CAMERA_ADD_FRAME_BASE,

#if defined(__CAMERA_FEATURE_ADD_FRAME_1__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_1__)
    IMG_ID_CAMERA_OSD_ADD_FRAME_1,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_2__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_2__)
    IMG_ID_CAMERA_OSD_ADD_FRAME_2,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_3__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_3__)
    IMG_ID_CAMERA_OSD_ADD_FRAME_3,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_4__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_4__)
    IMG_ID_CAMERA_OSD_ADD_FRAME_4,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_5__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_5__)
    IMG_ID_CAMERA_OSD_ADD_FRAME_5,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_6__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_6__)
    IMG_ID_CAMERA_OSD_ADD_FRAME_6,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_7__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_7__)
    IMG_ID_CAMERA_OSD_ADD_FRAME_7,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_8__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_8__)
    IMG_ID_CAMERA_OSD_ADD_FRAME_8,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_9__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_9__)
    IMG_ID_CAMERA_OSD_ADD_FRAME_9,
#endif 

#if defined(__CAMERA_FEATURE_ADD_FRAME_10__) || defined(__CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_10__)
    IMG_ID_CAMERA_OSD_ADD_FRAME_10,
#endif 

    IMG_ID_CAMERA_OSD_ADD_FRAME_END
} camera_osd_add_frame_img_id_enum;

/***************** add frame  *******************/
typedef enum
{
    IMG_ID_CAMERA_ADD_FRAME_START = IMG_ID_CAMERA_OSD_ADD_FRAME_END + 1,

#ifdef __CAMERA_FEATURE_ADD_FRAME_1__
    IMG_ID_CAMERA_ADD_FRAME_1,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_2__
    IMG_ID_CAMERA_ADD_FRAME_2,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_3__
    IMG_ID_CAMERA_ADD_FRAME_3,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_4__
    IMG_ID_CAMERA_ADD_FRAME_4,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_5__
    IMG_ID_CAMERA_ADD_FRAME_5,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_6__
    IMG_ID_CAMERA_ADD_FRAME_6,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_7__
    IMG_ID_CAMERA_ADD_FRAME_7,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_8__
    IMG_ID_CAMERA_ADD_FRAME_8,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_9__
    IMG_ID_CAMERA_ADD_FRAME_9,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_10__
    IMG_ID_CAMERA_ADD_FRAME_10,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_CUSTOM_1__
    IMG_ID_CAMERA_ADD_FRAME_CUSTOM_1,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_CUSTOM_2__
    IMG_ID_CAMERA_ADD_FRAME_CUSTOM_2,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_CUSTOM_3__
    IMG_ID_CAMERA_ADD_FRAME_CUSTOM_3,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_CUSTOM_4__
    IMG_ID_CAMERA_ADD_FRAME_CUSTOM_4,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_CUSTOM_5__
    IMG_ID_CAMERA_ADD_FRAME_CUSTOM_5,
#endif 

    IMG_ID_CAMERA_ADD_FRAME_END
} camera_add_frame_img_id_enum;

typedef enum
{
    IMG_ID_CAMERA_TILE_ADD_FRAME_START = IMG_ID_CAMERA_ADD_FRAME_END + 1,

#ifdef __CAMERA_FEATURE_ADD_FRAME_1__
    IMG_ID_CAMERA_TILE_ADD_FRAME_1,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_2__
    IMG_ID_CAMERA_TILE_ADD_FRAME_2,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_3__
    IMG_ID_CAMERA_TILE_ADD_FRAME_3,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_4__
    IMG_ID_CAMERA_TILE_ADD_FRAME_4,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_5__
    IMG_ID_CAMERA_TILE_ADD_FRAME_5,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_6__
    IMG_ID_CAMERA_TILE_ADD_FRAME_6,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_7__
    IMG_ID_CAMERA_TILE_ADD_FRAME_7,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_8__
    IMG_ID_CAMERA_TILE_ADD_FRAME_8,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_9__
    IMG_ID_CAMERA_TILE_ADD_FRAME_9,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_10__
    IMG_ID_CAMERA_TILE_ADD_FRAME_10,
#endif 

    IMG_ID_CAMERA_TILE_ADD_FRAME_END
} camera_tileshot_add_frame_img_id_enum;

typedef enum
{
    IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_START = IMG_ID_CAMERA_TILE_ADD_FRAME_END + 1,

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_1__
    IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_1,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_2__
    IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_2,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_3__
    IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_3,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_4__
    IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_4,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_5__
    IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_5,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_6__
    IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_6,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_7__
    IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_7,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_8__
    IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_8,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_9__
    IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_9,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_10__
    IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_10,
#endif 

    IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_END
} camera_coloridx_add_frame_img_id_enum;

typedef enum
{
    IMG_ID_CAMERA_COLOR_IDX2_ADD_FRAME_START = IMG_ID_CAMERA_COLOR_IDX_ADD_FRAME_END + 1,

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_1__
    IMG_ID_CAMERA_COLOR_IDX2_ADD_FRAME_1,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_2__
    IMG_ID_CAMERA_COLOR_IDX2_ADD_FRAME_2,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_3__
    IMG_ID_CAMERA_COLOR_IDX2_ADD_FRAME_3,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_4__
    IMG_ID_CAMERA_COLOR_IDX2_ADD_FRAME_4,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_5__
    IMG_ID_CAMERA_COLOR_IDX2_ADD_FRAME_5,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_6__
    IMG_ID_CAMERA_COLOR_IDX2_ADD_FRAME_6,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_7__
    IMG_ID_CAMERA_COLOR_IDX2_ADD_FRAME_7,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_8__
    IMG_ID_CAMERA_COLOR_IDX2_ADD_FRAME_8,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_9__
    IMG_ID_CAMERA_COLOR_IDX2_ADD_FRAME_9,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME_COLOR_IDX_10__
    IMG_ID_CAMERA_COLOR_IDX2_ADD_FRAME_10,
#endif 

    IMG_ID_CAMERA_COLOR_IDX2_ADD_FRAME_END
} camera_coloridx2_add_frame_img_id_enum;

/***************** cont shot *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_CONT_SHOT_START = CAMERA_CONT_SHOT_BASE,

    IMG_ID_CAMERA_OSD_CONT_SHOT_OFF,
    IMG_ID_CAMERA_OSD_CONT_SHOT_1,

#ifdef __CAMERA_FEATURE_CONT_SHOT_2__
    IMG_ID_CAMERA_OSD_CONT_SHOT_2,
#endif 

#ifdef __CAMERA_FEATURE_CONT_SHOT_3__
    IMG_ID_CAMERA_OSD_CONT_SHOT_3,
#endif 

#ifdef __CAMERA_FEATURE_CONT_SHOT_TILE__
    IMG_ID_CAMERA_OSD_CONT_SHOT_TILE,
#endif 

#ifdef __CAMERA_FEATURE_CONT_SHOT_BURST__
    IMG_ID_CAMERA_OSD_CONT_SHOT_BURST,
#endif 

    IMG_ID_CAMERA_OSD_CONT_SHOT_END
} camera_cont_shot_img_id_enum;

/***************** cont shot count bar *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_CONT_SHOT_BAR_START = IMG_ID_CAMERA_OSD_CONT_SHOT_END + 1,
    IMG_ID_CAMERA_OSD_CONT_SHOT_BAR_1,

#ifdef __CAMERA_FEATURE_CONT_SHOT_2__
    IMG_ID_CAMERA_OSD_CONT_SHOT_BAR_2,
#endif 

#ifdef __CAMERA_FEATURE_CONT_SHOT_3__
    IMG_ID_CAMERA_OSD_CONT_SHOT_BAR_3,
#endif 

    IMG_ID_CAMERA_OSD_CONT_SHOT_BAR_END
} camera_cont_shot_bar_img_id_enum;

/***************** delay timer *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_DELAY_TIMER_START = CAMERA_DELAY_TIMER_BASE,
    IMG_ID_CAMERA_OSD_DELAY_TIMER_OFF,
    IMG_ID_CAMERA_OSD_DELAY_TIMER_1,

#ifdef __CAMERA_FEATURE_DELAY_TIMER_2__
    IMG_ID_CAMERA_OSD_DELAY_TIMER_2,
#endif 

#ifdef __CAMERA_FEATURE_DELAY_TIMER_3__
    IMG_ID_CAMERA_OSD_DELAY_TIMER_3,
#endif 

    IMG_ID_CAMERA_OSD_DELAY_TIMER_END
} camera_delay_timer_img_id_enum;

/***************** storage *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_STORAGE_START = CAMERA_STORAGE_BASE,

    IMG_ID_CAMERA_OSD_STORAGE_PHONE,
    IMG_ID_CAMERA_OSD_STORAGE_MEMORY_CARD,

    IMG_ID_CAMERA_OSD_STORAGE_END
} camera_storage_img_id_enum;

/***************** zoom *******************/
typedef enum
{
    IMG_ID_CAMERA_OSD_ZOOM_START = CAMERA_ZOOM_BASE,

    IMG_ID_CAMERA_OSD_ZOOM_1,
    IMG_ID_CAMERA_OSD_ZOOM_2,
    IMG_ID_CAMERA_OSD_ZOOM_3,
    IMG_ID_CAMERA_OSD_ZOOM_4,
    IMG_ID_CAMERA_OSD_ZOOM_5,
    IMG_ID_CAMERA_OSD_ZOOM_6,
    IMG_ID_CAMERA_OSD_ZOOM_7,
    IMG_ID_CAMERA_OSD_ZOOM_8,
    IMG_ID_CAMERA_OSD_ZOOM_9,
    IMG_ID_CAMERA_OSD_ZOOM_10,
    IMG_ID_CAMERA_OSD_ZOOM_11,
    IMG_ID_CAMERA_OSD_ZOOM_12,
    IMG_ID_CAMERA_OSD_ZOOM_13,
    IMG_ID_CAMERA_OSD_ZOOM_14,
    IMG_ID_CAMERA_OSD_ZOOM_15,
    IMG_ID_CAMERA_OSD_ZOOM_16,
    IMG_ID_CAMERA_OSD_ZOOM_17,
    IMG_ID_CAMERA_OSD_ZOOM_18,
    IMG_ID_CAMERA_OSD_ZOOM_19,
    IMG_ID_CAMERA_OSD_ZOOM_20,
    IMG_ID_CAMERA_OSD_ZOOM_21,
    IMG_ID_CAMERA_OSD_ZOOM_22,
    IMG_ID_CAMERA_OSD_ZOOM_23,
    IMG_ID_CAMERA_OSD_ZOOM_24,
    IMG_ID_CAMERA_OSD_ZOOM_25,
    IMG_ID_CAMERA_OSD_ZOOM_26,
    IMG_ID_CAMERA_OSD_ZOOM_27,
    IMG_ID_CAMERA_OSD_ZOOM_28,
    IMG_ID_CAMERA_OSD_ZOOM_29,
    IMG_ID_CAMERA_OSD_ZOOM_30,

    IMG_ID_CAMERA_OSD_ZOOM_END
} camera_zoom_img_id_enum;

/***************** osd menu *******************/
typedef enum
{
    IMG_ID_CAMERA_ICONLIST_START = CAMERA_ICONLIST_BASE,

    IMG_ID_CAMERA_ICONLIST_IMAGE_SIZE,
    IMG_ID_CAMERA_ICONLIST_IMAGE_QTY,

#ifdef __CAMERA_FEATURE_WB__
    IMG_ID_CAMERA_ICONLIST_WB,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT__
    IMG_ID_CAMERA_ICONLIST_EFFECT,
#endif 

#ifdef __CAMERA_FEATURE_NIGHT__
    IMG_ID_CAMERA_ICONLIST_NIGHT,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME__
    IMG_ID_CAMERA_ICONLIST_ADD_FRAME,
#endif 

#ifdef __CAMERA_FEATURE_CONT_SHOT__
    IMG_ID_CAMERA_ICONLIST_CONT_SHOT,
#endif 

#ifdef __CAMERA_FEATURE_DELAY_TIMER__
    IMG_ID_CAMERA_ICONLIST_DELAY_TIMER,
#endif 

#ifdef __CAMERA_FEATURE_LED_HIGHLIGHT__
    IMG_ID_CAMERA_ICONLIST_LED_HIGHLIGHT,
#endif 

#ifdef __CAMERA_FEATURE_SHUTTER_SOUND__
    IMG_ID_CAMERA_ICONLIST_SHUTTER_SOUND,
#endif 

#ifdef __CAMERA_FEATURE_BANDING__
    IMG_ID_CAMERA_ICONLIST_BANDING,
#endif 

#ifdef __CAMERA_FEATURE_SELF_CAPTURE__
    IMG_ID_CAMERA_ICONLIST_SELF_CAPTURE,
#endif 

#ifdef __CAMERA_FEATURE_STORAGE__
    IMG_ID_CAMERA_ICONLIST_STORAGE,
#endif 

    IMG_ID_CAMERA_ICONLIST_END
} camera_iconlist_img_id_enum;


typedef enum
{
    IMG_ID_CAMERA_ICONLIST_SEL_START = CAMERA_ICONLIST_SEL_BASE,

    IMG_ID_CAMERA_ICONLIST_IMAGE_SIZE_SEL,
    IMG_ID_CAMERA_ICONLIST_IMAGE_QTY_SEL,

#ifdef __CAMERA_FEATURE_WB__
    IMG_ID_CAMERA_ICONLIST_WB_SEL,
#endif 

#ifdef __CAMERA_FEATURE_EFFECT__
    IMG_ID_CAMERA_ICONLIST_EFFECT_SEL,
#endif 

#ifdef __CAMERA_FEATURE_NIGHT__
    IMG_ID_CAMERA_ICONLIST_NIGHT_SEL,
#endif 

#ifdef __CAMERA_FEATURE_ADD_FRAME__
    IMG_ID_CAMERA_ICONLIST_ADD_FRAME_SEL,
#endif 

#ifdef __CAMERA_FEATURE_CONT_SHOT__
    IMG_ID_CAMERA_ICONLIST_CONT_SHOT_SEL,
#endif 

#ifdef __CAMERA_FEATURE_DELAY_TIMER__
    IMG_ID_CAMERA_ICONLIST_DELAY_TIMER_SEL,
#endif 

#ifdef __CAMERA_FEATURE_LED_HIGHLIGHT__
    IMG_ID_CAMERA_ICONLIST_LED_HIGHLIGHT_SEL,
#endif 

#ifdef __CAMERA_FEATURE_SHUTTER_SOUND__
    IMG_ID_CAMERA_ICONLIST_SHUTTER_SOUND_SEL,
#endif 

#ifdef __CAMERA_FEATURE_BANDING__
    IMG_ID_CAMERA_ICONLIST_BANDING_SEL,
#endif 

#ifdef __CAMERA_FEATURE_SELF_CAPTURE__
    IMG_ID_CAMERA_ICONLIST_SELF_CAPTURE_SEL,
#endif 

#ifdef __CAMERA_FEATURE_STORAGE__
    IMG_ID_CAMERA_ICONLIST_STORAGE_SEL,
#endif 

    IMG_ID_CAMERA_ICONLIST_SEL_END
} camera_iconlist_sel_img_id_enum;

/******* [Option Menu] ********/
typedef enum
{
    CAMERA_OPTION_TO_IMGVIEW,
    CAMERA_OPTION_CAMERA_SETTING,
    CAMERA_OPTION_IMAGE_SETTING,

#ifdef __CAMERA_FEATURE_EFFECT__
    CAMERA_OPTION_EFFECT_SETTING,
#endif 

#ifdef __CAMERA_FEATURE_WB__
    CAMERA_OPTION_WB,
#endif 

#ifdef __CAMERA_AUTOFOCUS_MODE__
    CAMERA_OPTION_FOCUS_MODE,
#endif 

#ifdef __CAMERA_AUTOFOCUS_METERING__
    CAMERA_OPTION_AUTOFOCUS,
#endif 

#ifdef __CAMERA_DSC_MODE__
    CAMERA_OPTION_DSC_MODE,
#endif 

#ifdef __CAMERA_FEATURE_ISO_SUPPORT__ 
	CAMERA_OPTION_ISO,
#endif

#ifdef __CAMERA_FEATURE_ADD_FRAME__
    CAMERA_OPTION_ADD_FRAME,
#endif 

#ifdef __CAMERA_FEATURE_SELF_CAPTURE__
    CAMERA_OPTION_SELF_CAPTURE,
#endif 

#ifdef __CAMERA_FEATURE_STORAGE__
    CAMERA_OPTION_STORAGE,
#endif 

    CAMERA_OPTION_RESTORE_DEFAULT,
    CAMERA_OPTION_ITEM_COUNT
} camera_option_count_enum;

/******* [Camera Setting Menu] ********/
typedef enum
{

#ifdef __CAMERA_FEATURE_FLASH__
    CAMERA_CAMERA_SETTING_FLASH,
#endif 

#ifdef __CAMERA_FEATURE_LED_HIGHLIGHT__
    CAMERA_CAMERA_SETTING_LED_HIGHLIGHT,
#endif 

#ifdef __CAMERA_FEATURE_SHUTTER_SOUND__
    CAMERA_CAMERA_SETTING_SHUTTER_SOUND,
#endif 

#ifdef __CAMERA_FEATURE_EV__
    CAMERA_CAMERA_SETTING_EV,
#endif 

#ifdef __CAMERA_FEATURE_NIGHT__
    CAMERA_CAMERA_SETTING_NIGHT,
#endif 

#ifdef __CAMERA_FEATURE_CLOSEUP__
    CAMERA_CAMERA_SETTING_CLOSEUP,
#endif 

#ifdef __CAMERA_FEATURE_BANDING__
    CAMERA_CAMERA_SETTING_BANDING,
#endif 

#ifdef __CAMERA_FEATURE_AE_METER__
    CAMERA_CAMERA_SETTING_AE_METER,
#endif 

#ifdef __CAMERA_FEATURE_DELAY_TIMER__
    CAMERA_CAMERA_SETTING_DELAY_TIMER,
#endif 

#ifdef __CAMERA_FEATURE_CONT_SHOT__
    CAMERA_CAMERA_SETTING_CONT_SHOT,
#endif 

    CAMERA_CAMERA_SETTING_ITEM_COUNT
} camera_camera_setting_count_enum;

/******* [Image Setting Menu] ********/
typedef enum
{
    CAMERA_IMAGE_SETTING_IMAGE_SIZE,
    CAMERA_IMAGE_SETTING_IMAGE_QTY,
    CAMERA_IMAGE_SETTING_ITEM_COUNT
} camera_image_setting_count_enum;

#ifdef __MMI_SUBLCD_CAMERA__
typedef enum
{
    CAMERA_SUBLCD_OPTION_PREVIEW,
#if defined(__CAMERA_FEATURE_FLASH__) || defined(__CAMERA_FEATURE_LED_HIGHLIGHT__)
    CAMERA_SUBLCD_OPTOIN_FLASH,
#endif
    CAMERA_SUBLCD_OPTION_EXIT,
    CAMERA_SUBLCD_OPTION_COUNT
}camera_sublcd_option_enum;
#endif

#endif /* _CAMERA_RES_DEF_H_ */ 

