/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*******************************************************************************
 * Filename:
 * ---------
 *   VdoRecResDef.h
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Video Recorder Resource Define
 *
 * Author:
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/
#ifndef VDO_REC_RES_DEF_H
#define VDO_REC_RES_DEF_H


/***************************************************************************** 
 * Image
 *****************************************************************************/
#define VDOREC_IMG_EV_BASE                (VDOREC_BASE+200)
#define VDOREC_IMG_ZOOM_BASE              (VDOREC_BASE+220)     /* reserve 50 for this */
#define VDOREC_IMG_NIGHT_BASE             (VDOREC_BASE+270)
#define VDOREC_IMG_LED_HIGHLIGHT_BASE     (VDOREC_BASE+280)
#define VDOREC_IMG_RECORD_AUD_BASE        (VDOREC_BASE+290)
#define VDOREC_IMG_SIZE_LIMIT_BASE        (VDOREC_BASE+300)
#define VDOREC_IMG_TIME_LIMIT_BASE        (VDOREC_BASE+310)
#define VDOREC_IMG_COLOR_IDX_BASE         (VDOREC_BASE+320)     /* reserve 30 for this */

typedef enum
{
    IMG_ID_VDOREC_APP_ICON = VDOREC_BASE + 1,
    IMG_ID_VDOREC_SUBLCD_ICON,

    /****** menu *******/
    IMG_ID_VDOREC_TO_VDOPLY,
    IMG_ID_VDOREC_CAMCODER_SETTING,
    IMG_ID_VDOREC_VIDEO_SETTING,
    IMG_ID_VDOREC_COLOR_IDX_FRAME,
    IMG_ID_VDOREC_EFFECT_SETTING,
    IMG_ID_VDOREC_SELF_RECORD,
    IMG_ID_VDOREC_STORAGE,
    IMG_ID_VDOREC_RESTORE_DEFAULT,

    /* camecoder setting */
    IMG_ID_VDOREC_WB,
    IMG_ID_VDOREC_LED_HIGHLIGHT,
    IMG_ID_VDOREC_EV,
    IMG_ID_VDOREC_NIGHT,
    IMG_ID_VDOREC_BANDING,

    /* video setting */
    IMG_ID_VDOREC_VIDEO_SIZE,
    IMG_ID_VDOREC_VIDEO_QTY,
    IMG_ID_VDOREC_SIZE_LIMIT,
    IMG_ID_VDOREC_TIME_LIMIT,
    IMG_ID_VDOREC_RECORD_AUD,
    IMG_ID_VDOREC_VIDEO_FORMAT,

   /********** OSD **********/
    IMG_ID_VDOREC_OSD_BG,
    IMG_ID_VDOREC_OSD_BUTTOM_BAR_BG,

    /* timer */
    IMG_ID_VDOREC_OSD_TIMER_0,
    IMG_ID_VDOREC_OSD_TIMER_1,
    IMG_ID_VDOREC_OSD_TIMER_2,
    IMG_ID_VDOREC_OSD_TIMER_3,
    IMG_ID_VDOREC_OSD_TIMER_4,
    IMG_ID_VDOREC_OSD_TIMER_5,
    IMG_ID_VDOREC_OSD_TIMER_6,
    IMG_ID_VDOREC_OSD_TIMER_7,
    IMG_ID_VDOREC_OSD_TIMER_8,
    IMG_ID_VDOREC_OSD_TIMER_9,
    IMG_ID_VDOREC_OSD_TIMER_COL,
    IMG_ID_VDOREC_OSD_TIMER_BG,

    /* state */
    IMG_ID_VDOREC_OSD_STATE_REC,
    IMG_ID_VDOREC_OSD_STATE_PAUSE,
    IMG_ID_VDOREC_OSD_STATE_STOP,

    /********** Touch Screen OSD **********/
    IMG_ID_VDOREC_TOUCH_OSD_EV_INC,
    IMG_ID_VDOREC_TOUCH_OSD_EV_INC_SEL,
    IMG_ID_VDOREC_TOUCH_OSD_EV_INC_DIS,
    IMG_ID_VDOREC_TOUCH_OSD_EV_DEC,
    IMG_ID_VDOREC_TOUCH_OSD_EV_DEC_SEL,
    IMG_ID_VDOREC_TOUCH_OSD_EV_DEC_DIS,
    IMG_ID_VDOREC_TOUCH_OSD_ZOOM_INC,
    IMG_ID_VDOREC_TOUCH_OSD_ZOOM_INC_SEL,
    IMG_ID_VDOREC_TOUCH_OSD_ZOOM_INC_DIS,
    IMG_ID_VDOREC_TOUCH_OSD_ZOOM_DEC,
    IMG_ID_VDOREC_TOUCH_OSD_ZOOM_DEC_SEL,
    IMG_ID_VDOREC_TOUCH_OSD_ZOOM_DEC_DIS,
    IMG_ID_VDOREC_TOUCH_OSD_REC,
    IMG_ID_VDOREC_TOUCH_OSD_REC_SEL,
    IMG_ID_VDOREC_TOUCH_OSD_PAUSE,
    IMG_ID_VDOREC_TOUCH_OSD_PAUSE_SEL,
    IMG_ID_VDOREC_TOUCH_OSD_STOP,
    IMG_ID_VDOREC_TOUCH_OSD_STOP_SEL,

    /* softkey image */
    IMG_ID_VDOREC_LSK_OPTION,
    IMG_ID_VDOREC_LSK_OPTION_SEL,
    IMG_ID_VDOREC_CK_RECORD,
    IMG_ID_VDOREC_CK_RECORD_SEL,
    IMG_ID_VDOREC_CK_PAUSE,
    IMG_ID_VDOREC_CK_PAUSE_SEL,
    IMG_ID_VDOREC_CK_RESUME,
    IMG_ID_VDOREC_CK_RESUME_SEL,
    IMG_ID_VDOREC_RSK_BACK,
    IMG_ID_VDOREC_RSK_BACK_SEL,
    IMG_ID_VDOREC_RSK_STOP,
    IMG_ID_VDOREC_RSK_STOP_SEL,

    IMG_ID_VDOREC_FORWARD_TO_MMS,

/* hongzhe.liu add start */
#if defined(ANALOG_TV_SUPPORT)
	IMG_ID_ANALOG_APP_ICON,

	/********** OSD **********/
	IMG_ID_ANALOG_OSD_BG,
	IMG_ID_ANALOG_OSD_BUTTOM_BAR_BG,

	/* volumn */
	IMG_ID_ANALOG_OSD_VOLUME_START,
	IMG_ID_ANALOG_OSD_VOLUME_1,
	IMG_ID_ANALOG_OSD_VOLUME_2,
	IMG_ID_ANALOG_OSD_VOLUME_3,
	IMG_ID_ANALOG_OSD_VOLUME_4,
	IMG_ID_ANALOG_OSD_VOLUME_5,
	IMG_ID_ANALOG_OSD_VOLUME_6,	
	IMG_ID_ANALOG_OSD_VOLUME_7,		
	IMG_ID_ANALOG_OSD_VOLUME_MUTE,

	/* progress */
	IMG_ID_ANALOG_OSD_PROGRESS_FILL,
	IMG_ID_ANALOG_OSD_PROGRESS_EMPTY,	
	
	/********** Fullscreen OSD **********/
	IMG_ID_ANALOG_FULLSCR_OSD_BG,
	/* volumn */
	IMG_ID_ANALOG_FULLSCR_OSD_VOLUME_START,
	IMG_ID_ANALOG_FULLSCR_OSD_VOLUME_1,
	IMG_ID_ANALOG_FULLSCR_OSD_VOLUME_2,
	IMG_ID_ANALOG_FULLSCR_OSD_VOLUME_3,
	IMG_ID_ANALOG_FULLSCR_OSD_VOLUME_4,
	IMG_ID_ANALOG_FULLSCR_OSD_VOLUME_5,
	IMG_ID_ANALOG_FULLSCR_OSD_VOLUME_6,	
	IMG_ID_ANALOG_FULLSCR_OSD_VOLUME_7,		
	IMG_ID_ANALOG_FULLSCR_OSD_VOLUME_MUTE,


	/* progress */
	IMG_ID_ANALOG_FULLSCR_OSD_PROGRESS_FILL,
	IMG_ID_ANALOG_FULLSCR_OSD_PROGRESS_EMPTY,	

	/********** Touch Screen OSD **********/
	IMG_ID_ANALOG_TOUCH_OSD_CHANNEL_INC,
	IMG_ID_ANALOG_TOUCH_OSD_CHANNEL_INC_SEL,
	IMG_ID_ANALOG_TOUCH_OSD_CHANNEL_INC_DIS,	
	IMG_ID_ANALOG_TOUCH_OSD_CHANNEL_DEC,
	IMG_ID_ANALOG_TOUCH_OSD_CHANNEL_DEC_SEL,	
	IMG_ID_ANALOG_TOUCH_OSD_CHANNEL_DEC_DIS,		
	IMG_ID_ANALOG_TOUCH_OSD_VOLUME_INC,
	IMG_ID_ANALOG_TOUCH_OSD_VOLUME_INC_SEL,
	IMG_ID_ANALOG_TOUCH_OSD_VOLUME_INC_DIS,	
	IMG_ID_ANALOG_TOUCH_OSD_VOLUME_DEC,
	IMG_ID_ANALOG_TOUCH_OSD_VOLUME_DEC_SEL,
	IMG_ID_ANALOG_TOUCH_OSD_VOLUME_DEC_DIS,
	IMG_ID_ANALOG_TOUCH_OSD_FULLSCREEN,
	IMG_ID_ANALOG_TOUCH_OSD_FULLSCREEN_SEL,		

	IMG_ID_ANALOG_TOUCH_FULL_OSD_CHANNEL_INC,
	IMG_ID_ANALOG_TOUCH_FULL_OSD_CHANNEL_INC_SEL,
	IMG_ID_ANALOG_TOUCH_FULL_OSD_CHANNEL_INC_DIS,	
	IMG_ID_ANALOG_TOUCH_FULL_OSD_CHANNEL_DEC,
	IMG_ID_ANALOG_TOUCH_FULL_OSD_CHANNEL_DEC_SEL,	
	IMG_ID_ANALOG_TOUCH_FULL_OSD_CHANNEL_DEC_DIS,		
	IMG_ID_ANALOG_TOUCH_FULL_OSD_VOLUME_INC,
	IMG_ID_ANALOG_TOUCH_FULL_OSD_VOLUME_INC_SEL,
	IMG_ID_ANALOG_TOUCH_FULL_OSD_VOLUME_INC_DIS,	
	IMG_ID_ANALOG_TOUCH_FULL_OSD_VOLUME_DEC,
	IMG_ID_ANALOG_TOUCH_FULL_OSD_VOLUME_DEC_SEL,
	IMG_ID_ANALOG_TOUCH_FULL_OSD_VOLUME_DEC_DIS,
	IMG_ID_TV_SIGNAL, //bw added
	IMG_ID_TV_MAINMENU,//zrb_bw
	IMG_ID_TV_LOGO,//__MMI_ANALOT_TV_LOGO__UNI@bw_20070413  添加电视logo
	#if defined(TV_RECORD_SUPPORT)
	//Huyanwei Add It 
	IMG_ID_ANALOG_TOUCH_OSD_RECORD,
	#endif
#endif
/* hongzhe.liu add end */



    IMG_ID_VDOREC_TOTAL_COUNT
} vdorec_img_id_enum;


/***************** EV *******************/
typedef enum
{
    IMG_ID_VDOREC_OSD_EV_START = VDOREC_IMG_EV_BASE,

#ifdef __VDOREC_FEATURE_EV_4__
    IMG_ID_VDOREC_OSD_EV_N4,
#endif 

#ifdef __VDOREC_FEATURE_EV_3__
    IMG_ID_VDOREC_OSD_EV_N3,
#endif 

#ifdef __VDOREC_FEATURE_EV_2__
    IMG_ID_VDOREC_OSD_EV_N2,
#endif 

    IMG_ID_VDOREC_OSD_EV_N1,
    IMG_ID_VDOREC_OSD_EV_0,
    IMG_ID_VDOREC_OSD_EV_P1,

#ifdef __VDOREC_FEATURE_EV_2__
    IMG_ID_VDOREC_OSD_EV_P2,
#endif 

#ifdef __VDOREC_FEATURE_EV_3__
    IMG_ID_VDOREC_OSD_EV_P3,
#endif 

#ifdef __VDOREC_FEATURE_EV_4__
    IMG_ID_VDOREC_OSD_EV_P4,
#endif 

    IMG_ID_VDOREC_OSD_EV_END
} vdorec_ev_img_id_enum;

/*************** COLOR IDX OVERLAY FRAME *************/
typedef enum
{
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_START = VDOREC_IMG_COLOR_IDX_BASE + 1,

#ifdef __VDOREC_COLOR_IDX_FRAME_1__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_1,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_2__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_2,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_3__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_3,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_4__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_4,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_5__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_5,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_6__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_6,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_7__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_7,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_8__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_8,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_9__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_9,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_10__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_10,
#endif 

    IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_END
} vdorec_frame_qcif_img_id_enum;

typedef enum
{
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QVGA_START = IMG_ID_VDOREC_COLOR_IDX_FRAME_QCIF_END + 1,

#ifdef __VDOREC_COLOR_IDX_FRAME_1__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QVGA_1,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_2__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QVGA_2,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_3__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QVGA_3,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_4__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QVGA_4,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_5__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QVGA_5,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_6__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QVGA_6,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_7__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QVGA_7,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_8__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QVGA_8,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_9__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QVGA_9,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_10__
    IMG_ID_VDOREC_COLOR_IDX_FRAME_QVGA_10,
#endif 

    IMG_ID_VDOREC_COLOR_IDX_FRAME_QVGA_END
} camera_frame_qvga_img_id_enum;

/***************** zoom *******************/
typedef enum
{

    IMG_ID_VDOREC_OSD_ZOOM_START = VDOREC_IMG_ZOOM_BASE,

    IMG_ID_VDOREC_OSD_ZOOM_10,
    IMG_ID_VDOREC_OSD_ZOOM_12,
    IMG_ID_VDOREC_OSD_ZOOM_14,
    IMG_ID_VDOREC_OSD_ZOOM_16,
    IMG_ID_VDOREC_OSD_ZOOM_18,
    IMG_ID_VDOREC_OSD_ZOOM_20,
    IMG_ID_VDOREC_OSD_ZOOM_22,
    IMG_ID_VDOREC_OSD_ZOOM_24,
    IMG_ID_VDOREC_OSD_ZOOM_26,
    IMG_ID_VDOREC_OSD_ZOOM_28,
    IMG_ID_VDOREC_OSD_ZOOM_30,
    IMG_ID_VDOREC_OSD_ZOOM_32,
    IMG_ID_VDOREC_OSD_ZOOM_34,
    IMG_ID_VDOREC_OSD_ZOOM_36,
    IMG_ID_VDOREC_OSD_ZOOM_38,
    IMG_ID_VDOREC_OSD_ZOOM_40,
    IMG_ID_VDOREC_OSD_ZOOM_42,
    IMG_ID_VDOREC_OSD_ZOOM_44,
    IMG_ID_VDOREC_OSD_ZOOM_46,
    IMG_ID_VDOREC_OSD_ZOOM_48,
    IMG_ID_VDOREC_OSD_ZOOM_50,
    IMG_ID_VDOREC_OSD_ZOOM_52,
    IMG_ID_VDOREC_OSD_ZOOM_54,
    IMG_ID_VDOREC_OSD_ZOOM_56,
    IMG_ID_VDOREC_OSD_ZOOM_58,
    IMG_ID_VDOREC_OSD_ZOOM_60,
    IMG_ID_VDOREC_OSD_ZOOM_62,
    IMG_ID_VDOREC_OSD_ZOOM_64,
    IMG_ID_VDOREC_OSD_ZOOM_66,
    IMG_ID_VDOREC_OSD_ZOOM_68,
    IMG_ID_VDOREC_OSD_ZOOM_70,
    IMG_ID_VDOREC_OSD_ZOOM_72,
    IMG_ID_VDOREC_OSD_ZOOM_74,
    IMG_ID_VDOREC_OSD_ZOOM_76,
    IMG_ID_VDOREC_OSD_ZOOM_78,
    IMG_ID_VDOREC_OSD_ZOOM_80,
    
    IMG_ID_VDOREC_OSD_ZOOM_END
} vdorec_zoom_img_id_enum;

/***************** night *******************/
typedef enum
{

    IMG_ID_VDOREC_OSD_NIGHT_START = VDOREC_IMG_NIGHT_BASE,

    IMG_ID_VDOREC_OSD_NIGHT_OFF,
    IMG_ID_VDOREC_OSD_NIGHT_ON,

    IMG_ID_VDOREC_OSD_NIGHT_END
} vdorec_night_img_id_enum;

/***************** led highlight *******************/

/* led highlight */
typedef enum
{
    IMG_ID_VDOREC_OSD_LED_HIGHLIGHT_START = VDOREC_IMG_LED_HIGHLIGHT_BASE,
    IMG_ID_VDOREC_OSD_LED_HIGHLIGHT_OFF,

#ifdef __VDOREC_FEATURE_LED_HIGHLIGHT_ON_OFF__
    /* on/off */
    IMG_ID_VDOREC_OSD_LED_HIGHLIGHT_ON,
#endif /* __VDOREC_FEATURE_LED_HIGHLIGHT_ON_OFF__ */ /* __VDOREC_FEATURE_LED_HIGHLIGHT__ */

#ifdef __VDOREC_FEATURE_LED_HIGHLIGHT_7_COLOR__
    /* 7 color */
    IMG_ID_VDOREC_OSD_LED_HIGHLIGHT_WHITE,
    IMG_ID_VDOREC_OSD_LED_HIGHLIGHT_RED,
    IMG_ID_VDOREC_OSD_LED_HIGHLIGHT_GREEN,
    IMG_ID_VDOREC_OSD_LED_HIGHLIGHT_BLUE,
    IMG_ID_VDOREC_OSD_LED_HIGHLIGHT_YELLOW,
    IMG_ID_VDOREC_OSD_LED_HIGHLIGHT_PURPLE,
    IMG_ID_VDOREC_OSD_LED_HIGHLIGHT_CYAN,
#endif /* __VDOREC_FEATURE_LED_HIGHLIGHT_7_COLOR__ */ 

    IMG_ID_VDOREC_OSD_LED_HIGHLIGHT_END
} vdorec_led_highlight_img_id_enum;

/***************** record aud *******************/
typedef enum
{

    IMG_ID_VDOREC_OSD_RECORD_AUD_START = VDOREC_IMG_RECORD_AUD_BASE,

    IMG_ID_VDOREC_OSD_RECORD_AUD_OFF,
    IMG_ID_VDOREC_OSD_RECORD_AUD_ON,

    IMG_ID_VDOREC_OSD_RECORD_AUD_END
} vdorec_record_aud_img_id_enum;

/***************** size limit *******************/
typedef enum
{

    IMG_ID_VDOREC_OSD_SIZE_LIMIT_START = VDOREC_IMG_SIZE_LIMIT_BASE,

    IMG_ID_VDOREC_OSD_SIZE_LIMIT_OFF,
    IMG_ID_VDOREC_OSD_SIZE_LIMIT_1,
    IMG_ID_VDOREC_OSD_SIZE_LIMIT_2,
    IMG_ID_VDOREC_OSD_SIZE_LIMIT_3,

    IMG_ID_VDOREC_OSD_SIZE_LIMIT_END
} vdorec_size_limit_img_id_enum;

/***************** time limit *******************/
typedef enum
{

    IMG_ID_VDOREC_OSD_TIME_LIMIT_START = VDOREC_IMG_TIME_LIMIT_BASE,

    IMG_ID_VDOREC_OSD_TIME_LIMIT_OFF,
    IMG_ID_VDOREC_OSD_TIME_LIMIT_1,
    IMG_ID_VDOREC_OSD_TIME_LIMIT_2,
    IMG_ID_VDOREC_OSD_TIME_LIMIT_3,

    IMG_ID_VDOREC_OSD_TIME_LIMIT_END
} vdorec_time_limit_img_id_enum;


/***************************************************************************** 
 * String
 *****************************************************************************/
/* camera setting */
#define VDOREC_WB_BASE              (VDOREC_BASE+110)
#define VDOREC_LED_HIGHLIGHT_BASE   (VDOREC_BASE+120)
#define VDOREC_EV_BASE              (VDOREC_BASE+130)
#define VDOREC_NIGHT_BASE           (VDOREC_BASE+140)
#define VDOREC_BANDING_BASE         (VDOREC_BASE+150)

#define VDOREC_VIDEO_SIZE_BASE      (VDOREC_BASE+160)
#define VDOREC_VIDEO_QTY_BASE       (VDOREC_BASE+170)
#define VDOREC_SIZE_LIMIT_BASE      (VDOREC_BASE+180)
#define VDOREC_TIME_LIMIT_BASE      (VDOREC_BASE+190)
#define VDOREC_RECORD_AUD_BASE      (VDOREC_BASE+200)
#define VDOREC_VIDEO_FORMAT_BASE    (VDOREC_BASE+210)
#define VDOREC_EFFECT_BASE          (VDOREC_BASE+220)   /* reserve 30 for this */
#define VDOREC_COLOR_IDX_FRAME_BASE (VDOREC_BASE+250)   /* reserve 30 for this */

#define VDOREC_WB_ITEM_COUNT              (STR_ID_VDOREC_WB_END-STR_ID_VDOREC_WB_START-1)
#define VDOREC_LED_HIGHLIGHT_ITEM_COUNT   (STR_ID_VDOREC_LED_HIGHLIGHT_END-STR_ID_VDOREC_LED_HIGHLIGHT_START-1)
#define VDOREC_EV_ITEM_COUNT              (STR_ID_VDOREC_EV_END-STR_ID_VDOREC_EV_START-1)
#define VDOREC_NIGHT_ITEM_COUNT           (STR_ID_VDOREC_NIGHT_END-STR_ID_VDOREC_NIGHT_START-1)
#define VDOREC_BANDING_ITEM_COUNT         (STR_ID_VDOREC_BANDING_END-STR_ID_VDOREC_BANDING_START-1)

#define VDOREC_VIDEO_SIZE_ITEM_COUNT      (STR_ID_VDOREC_VIDEO_SIZE_END-STR_ID_VDOREC_VIDEO_SIZE_START-1)
#define VDOREC_VIDEO_QTY_ITEM_COUNT       (STR_ID_VDOREC_VIDEO_QTY_END-STR_ID_VDOREC_VIDEO_QTY_START-1)
#define VDOREC_SIZE_LIMIT_ITEM_COUNT      (STR_ID_VDOREC_SIZE_LIMIT_END-STR_ID_VDOREC_SIZE_LIMIT_START-1)
#define VDOREC_TIME_LIMIT_ITEM_COUNT      (STR_ID_VDOREC_TIME_LIMIT_END-STR_ID_VDOREC_TIME_LIMIT_START-1)
#define VDOREC_RECORD_AUD_ITEM_COUNT      (STR_ID_VDOREC_RECORD_AUD_END-STR_ID_VDOREC_RECORD_AUD_START-1)
#define VDOREC_VIDEO_FORMAT_ITEM_COUNT    (STR_ID_VDOREC_VIDEO_FORMAT_END-STR_ID_VDOREC_VIDEO_FORMAT_START-1)
#define VDOREC_EFFECT_ITEM_COUNT          (STR_ID_VDOREC_EFFECT_END-STR_ID_VDOREC_EFFECT_START-1)
#define VDOREC_COLOR_IDX_FRAME_ITEM_COUNT (STR_ID_VDOREC_COLOR_IDX_FRAME_END-STR_ID_VDOREC_COLOR_IDX_FRAME_START-1)

/******* [Option Menu] ********/
typedef enum
{

#ifdef __VDOREC_FEATURE_MERGE_MENU__
    VDOREC_OPTION_CAMCODER_SETTING,
#else /* __VDOREC_FEATURE_MERGE_MENU__ */ 
    VDOREC_OPTION_CAMCODER_SETTING,
    VDOREC_OPTION_VIDEO_SETTING,
#endif /* __VDOREC_FEATURE_MERGE_MENU__ */ 

#ifdef __VDOREC_FEATURE_EFFECT__
    VDOREC_OPTION_EFFECT_SETTING,
#endif 

#ifdef __VDOREC_FEATURE_SELF_RECORD__
    VDOREC_OPTION_SELF_RECORD,
#endif 

#ifdef __VDOREC_FEATURE_STORAGE__
    VDOREC_OPTION_STORAGE,
#endif 

    VDOREC_OPTION_RESTORE_DEFAULT,

    VDOREC_OPTION_ITEM_COUNT
} vdorec_option_count_enum;

/******* [CamCoder Setting] ********/
typedef enum
{

#if defined(DOUBLE_CAMERA_SUPPORT)
    // Huyanwei Add It For Video Recode Switch Camera
    VDOREC_CAMCODER_SETTING_CAM,
#endif

#ifdef __VDOREC_FEATURE_WB__
    VDOREC_CAMCODER_SETTING_WB,
#endif 

#if defined(__VDOREC_FEATURE_LED_HIGHLIGHT_ON_OFF__) || defined(__VDOREC_FEATURE_LED_HIGHLIGHT_7_COLOR__)
    VDOREC_CAMCODER_SETTING_LED_HIGHLIGHT,
#endif 

#ifdef __VDOREC_FEATURE_EV__
    VDOREC_CAMCODER_SETTING_EV,
#endif 

#ifdef __VDOREC_FEATURE_NIGHT__
    VDOREC_CAMCODER_SETTING_NIGHT,
#endif 

#ifdef __VDOREC_FEATURE_BANDING__
    VDOREC_CAMCODER_SETTING_BANDING,
#endif 

#ifdef __VDOREC_FEATURE_MERGE_MENU__
    /* merge "Video Setting" items into "CamCoder Setting" */
#ifdef __VDOREC_FEATURE_VIDEO_QTY__
    VDOREC_VIDEO_SETTING_VIDEO_QTY,
#endif 

#ifdef __VDOREC_FEATURE_SIZE_LIMIT__
    VDOREC_VIDEO_SETTING_SIZE_LIMIT,
#endif 

#ifdef __VDOREC_FEATURE_TIME_LIMIT__
    VDOREC_VIDEO_SETTING_TIMER_LIMIT,
#endif 

#ifdef __VDOREC_FEATURE_RECORD_AUD__
    VDOREC_VIDEO_SETTING_RECORD_AUD,
#endif 

#ifdef __VDOREC_FEATURE_VIDEO_FORMAT__
    VDOREC_VIDEO_SETTING_VIDEO_FORMAT,
#endif 
#endif /* __VDOREC_FEATURE_MERGE_MENU__ */ 

    VDOREC_CAMCODER_SETTING_ITEM_COUNT
} vdorec_camcoder_setting_count_enum;

/******* [Video Setting] ********/
#ifndef __VDOREC_FEATURE_MERGE_MENU__

typedef enum
{

#ifdef __VDOREC_FEATURE_VIDEO_SIZE__
    VDOREC_VIDEO_SETTING_VIDEO_SIZE,
#endif 

#ifdef __VDOREC_FEATURE_VIDEO_QTY__
    VDOREC_VIDEO_SETTING_VIDEO_QTY,
#endif 

#ifdef __VDOREC_FEATURE_SIZE_LIMIT__
    VDOREC_VIDEO_SETTING_SIZE_LIMIT,
#endif 

#ifdef __VDOREC_FEATURE_TIME_LIMIT__
    VDOREC_VIDEO_SETTING_TIMER_LIMIT,
#endif 

#ifdef __VDOREC_FEATURE_RECORD_AUD__
    VDOREC_VIDEO_SETTING_RECORD_AUD,
#endif 

#ifdef __VDOREC_FEATURE_VIDEO_FORMAT__
    VDOREC_VIDEO_SETTING_VIDEO_FORMAT,
#endif 

    VDOREC_VIDEO_SETTING_ITEM_COUNT
} vdorec_video_setting_count_enum;

#endif /* __VDOREC_FEATURE_MERGE_MENU__ */ 


typedef enum
{
    /* app */
    STR_ID_VDOREC_APP_NAME = VDOREC_BASE + 1,
    STR_ID_VDOREC_STOP,

    /* option menu */
    STR_ID_VDOREC_TO_VDOPLY,
    STR_ID_VDOREC_CAMCODER_SETTING,
    STR_ID_VDOREC_VIDEO_SETTING,
    STR_ID_VDOREC_EFFECT_SETTING,
    STR_ID_VDOREC_COLOR_IDX_FRAME,
    STR_ID_VDOREC_SELF_RECORD,
    STR_ID_VDOREC_STORAGE,
    STR_ID_VDOREC_RESTORE_DEFAULT,

    /* color idx frame */
    STR_ID_VDOREC_COLOR_IDX_FRAME_SET,
    STR_ID_VDOREC_COLOR_IDX_FRAME_DE_ASSOCIATE,
    STR_ID_VDOREC_COLOR_IDX_FRAME_REPLACE,

    /* camecoder setting */
    STR_ID_VDOREC_WB,
    STR_ID_VDOREC_LED_HIGHLIGHT,
    STR_ID_VDOREC_EV,
    STR_ID_VDOREC_NIGHT,
    STR_ID_VDOREC_BANDING,

    /* video setting */
    STR_ID_VDOREC_VIDEO_SIZE,
    STR_ID_VDOREC_VIDEO_QTY,
    STR_ID_VDOREC_SIZE_LIMIT,
    STR_ID_VDOREC_TIME_LIMIT,
    STR_ID_VDOREC_RECORD_AUD,
    STR_ID_VDOREC_VIDEO_FORMAT,

    /* storage */
    STR_ID_VDOREC_STORAGE_PHONE,
    STR_ID_VDOREC_STORAGE_MEMORY_CARD,

    /* Notify */
    STR_ID_VDOREC_NOTIFY_STORAGE_NOT_READY,
    /* hongzhe.liu add start */
    STR_ID_VDOREC_NOTIFY_NO_MEMORY_CARD,
    /* hongzhe.liu add end */
    STR_ID_VDOREC_NOTIFY_WRITE_PROTECTION,
    STR_ID_VDOREC_NOTIFY_ERROR,
    STR_ID_VDOREC_NOTIFY_SAVING,
    STR_ID_VDOREC_NOTIFY_HW_NOT_READY,
    STR_ID_VDOREC_NOTIFY_RESTORE_DEFAULT_CONFIRM,
    STR_ID_VDOREC_NOTIFY_SAVE_CONFIRM,
    STR_ID_VDOREC_NOTIFY_SAVE_FILE_ERROR,
    STR_ID_VDOREC_NOTIFY_REACH_TIME_LIMIT,
    STR_ID_VDOREC_NOTIFY_REACH_SIZE_LIMIT,
    STR_ID_VDOREC_NOTIFY_STORAGE_TOO_SLOW,
    STR_ID_VDOREC_NOTIFY_SYSTEM_TOO_BUSY,

    /* 23KEY */
    STR_ID_VDOREC_RSK_RECORD,


/* hongzhe.liu add start */
#if defined(ANALOG_TV_SUPPORT)
    STR_ID_TV_IN,
    STR_ID_TV_IN_SOURCE_FORMAT,
    STR_ID_TV_IN_SOURCE_FORMAT_NTSC,
    STR_ID_TV_IN_SOURCE_FORMAT_PAL,
    STR_ID_VDOREC_NOTIFY_CABLE_NOT_READY,
    STR_ID_ANALOG_TV,
    STR_ID_TLG_TV_SELECT_AREA,
    STR_ID_TLG_TV_CHANNEL_LIST,
    STR_ID_TLG_TV_AUTO_SEARCH,
    STR_ID_TLG_TV_SELECT_MODE, 
    //area start
    STR_ID_TLG_TV_CHINA,
    STR_ID_TLG_TV_SHENZHEN,    
    STR_ID_TLG_TV_EUROPE,
    STR_ID_TLG_TV_TURKEY,
    STR_ID_TLG_TV_UAE,
    STR_ID_TLG_TV_AFGHANISTAN,
    STR_ID_TLG_TV_SINGAPORE,
    STR_ID_TLG_TV_THAILAND,
    STR_ID_TLG_TV_CAMBODIA,
    STR_ID_TLG_TV_INDONESIA,
    STR_ID_TLG_TV_MALAYSIA,
    STR_ID_TLG_TV_MYANMAR,
    STR_ID_TLG_TV_LAOS,
    STR_ID_TLG_TV_SPAIN,
    STR_ID_TLG_TV_PORTUGAL,
    STR_ID_TLG_TV_INDIA,
    STR_ID_TLG_TV_PAKISTAN,    
    STR_ID_TLG_TV_VIETNAM,    
    STR_ID_TLG_TV_ARGENTINA,    
    STR_ID_TLG_TV_HONGKONG,
    STR_ID_TLG_TV_ENGLAND,
    STR_ID_TLG_TV_SOUTH_AFRICA,    
    STR_ID_TLG_TV_AMERICA,
    STR_ID_TLG_TV_CANADA,
    STR_ID_TLG_TV_KOREA,
    STR_ID_TLG_TV_TAIWAN,
    STR_ID_TLG_TV_MEXICO,
    STR_ID_TLG_TV_CHILE,
    STR_ID_TLG_TV_VENEZUELA,
    STR_ID_TLG_TV_PHILIPPINES,
    STR_ID_TLG_TV_BRAZIL,
    STR_ID_TLG_TV_JAPAN,
    //area end
    STR_ID_TV_NOTIFY_INITIALIZED_FAIL,
    STR_ID_TLG_TV_ANALOGTV,
    STR_ID_TLG_TV_CATV,
    STR_ID_TLG_TV_CATV_WARNING,
    STR_ID_SIGNAL_QUALITY_HINT,
    #if defined(TV_RECORD_SUPPORT)
    //Huyanwei Add It 
    STR_ID_ANALOG_TV_RECORD,
    #endif
#endif
/* hongzhe.liu add end */

    STR_ID_VDOREC_TOTAL_COUNT
} vdorec_str_id_enum;

/* color idx overlay frame */
typedef enum
{
    STR_ID_VDOREC_COLOR_IDX_FRAME_START = VDOREC_COLOR_IDX_FRAME_BASE,
    STR_ID_VDOREC_COLOR_IDX_FRAME_OFF,

#ifdef __VDOREC_COLOR_IDX_FRAME_1__
    STR_ID_VDOREC_COLOR_IDX_FRAME_1,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_2__
    STR_ID_VDOREC_COLOR_IDX_FRAME_2,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_3__
    STR_ID_VDOREC_COLOR_IDX_FRAME_3,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_4__
    STR_ID_VDOREC_COLOR_IDX_FRAME_4,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_5__
    STR_ID_VDOREC_COLOR_IDX_FRAME_5,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_6__
    STR_ID_VDOREC_COLOR_IDX_FRAME_6,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_7__
    STR_ID_VDOREC_COLOR_IDX_FRAME_7,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_8__
    STR_ID_VDOREC_COLOR_IDX_FRAME_8,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_9__
    STR_ID_VDOREC_COLOR_IDX_FRAME_9,
#endif 

#ifdef __VDOREC_COLOR_IDX_FRAME_10__
    STR_ID_VDOREC_COLOR_IDX_FRAME_10,
#endif 

    STR_ID_VDOREC_COLOR_IDX_FRAME_END
} vdorec_color_idx_frame_str_id_enum;

/***************** WB *******************/
typedef enum
{
    STR_ID_VDOREC_WB_START = VDOREC_WB_BASE,

#ifdef __VDOREC_FEATURE_WB_AUTO__
    STR_ID_VDOREC_WB_AUTO,
#endif 

#ifdef __VDOREC_FEATURE_WB_DAYLIGHT__
    STR_ID_VDOREC_WB_DAYLIGHT,
#endif 

#ifdef __VDOREC_FEATURE_WB_TUNGSTEN__
    STR_ID_VDOREC_WB_TUNGSTEN,
#endif 

#ifdef __VDOREC_FEATURE_WB_FLUORESCENT__
    STR_ID_VDOREC_WB_FLUORESCENT,
#endif 

#ifdef __VDOREC_FEATURE_WB_CLOUD__
    STR_ID_VDOREC_WB_CLOUD,
#endif 

#ifdef __VDOREC_FEATURE_WB_INCANDESCENCE__
    STR_ID_VDOREC_WB_INCANDESCENCE,
#endif 

    STR_ID_VDOREC_WB_END
} vdorec_wb_str_id_enum;

/***************** LED Highlight *******************/

typedef enum
{
    STR_ID_VDOREC_LED_HIGHLIGHT_START = VDOREC_LED_HIGHLIGHT_BASE,
    STR_ID_VDOREC_LED_HIGHLIGHT_OFF,

#ifdef __VDOREC_FEATURE_LED_HIGHLIGHT_ON_OFF__

    STR_ID_VDOREC_LED_HIGHLIGHT_ON,

#endif /* __VDOREC_FEATURE_LED_HIGHLIGHT_ON_OFF__ */ 

#ifdef __VDOREC_FEATURE_LED_HIGHLIGHT_7_COLOR__

    STR_ID_VDOREC_LED_HIGHLIGHT_WHITE,
    STR_ID_VDOREC_LED_HIGHLIGHT_RED,
    STR_ID_VDOREC_LED_HIGHLIGHT_GREEN,
    STR_ID_VDOREC_LED_HIGHLIGHT_BLUE,
    STR_ID_VDOREC_LED_HIGHLIGHT_YELLOW,
    STR_ID_VDOREC_LED_HIGHLIGHT_PURPLE,
    STR_ID_VDOREC_LED_HIGHLIGHT_CYAN,

#endif /* __VDOREC_FEATURE_LED_HIGHLIGHT_7_COLOR__ */ 

    STR_ID_VDOREC_LED_HIGHLIGHT_END
} vdorec_led_highlight_str_id_enum;

/***************** EV *******************/
typedef enum
{
    STR_ID_VDOREC_EV_START = VDOREC_EV_BASE,

#ifdef __VDOREC_FEATURE_EV_4__
    STR_ID_VDOREC_EV_N4,
#endif 

#ifdef __VDOREC_FEATURE_EV_3__
    STR_ID_VDOREC_EV_N3,
#endif 

#ifdef __VDOREC_FEATURE_EV_2__
    STR_ID_VDOREC_EV_N2,
#endif 

    STR_ID_VDOREC_EV_N1,
    STR_ID_VDOREC_EV_0,
    STR_ID_VDOREC_EV_P1,

#ifdef __VDOREC_FEATURE_EV_2__
    STR_ID_VDOREC_EV_P2,
#endif 

#ifdef __VDOREC_FEATURE_EV_3__
    STR_ID_VDOREC_EV_P3,
#endif 

#ifdef __VDOREC_FEATURE_EV_4__
    STR_ID_VDOREC_EV_P4,
#endif 

    STR_ID_VDOREC_EV_END
} vdorec_ev_str_id_enum;

/***************** Night *******************/
typedef enum
{

    STR_ID_VDOREC_NIGHT_START = VDOREC_NIGHT_BASE,

    STR_ID_VDOREC_NIGHT_OFF,
    STR_ID_VDOREC_NIGHT_ON,

    STR_ID_VDOREC_NIGHT_END
} vdorec_night_str_id_enum;

/***************** Banding *******************/
typedef enum
{
    STR_ID_VDOREC_BANDING_START = VDOREC_BANDING_BASE,

    STR_ID_VDOREC_BANDING_50HZ,
    STR_ID_VDOREC_BANDING_60HZ,

    STR_ID_VDOREC_BANDING_END
} vdorec_banding_str_id_enum;

/***************** Video size *******************/
typedef enum
{
    STR_ID_VDOREC_VIDEO_SIZE_START = VDOREC_VIDEO_SIZE_BASE,

#ifdef __VDOREC_FEATURE_VIDEO_SIZE_SQCIF__
    STR_ID_VDOREC_VIDEO_SIZE_SQCIF,
#endif 

#ifdef __VDOREC_FEATURE_VIDEO_SIZE_QQVGA__
    STR_ID_VDOREC_VIDEO_SIZE_QQVGA,
#endif 

#ifdef __VDOREC_FEATURE_VIDEO_SIZE_QCIF__
    STR_ID_VDOREC_VIDEO_SIZE_QCIF,
#endif 

#ifdef __VDOREC_FEATURE_VIDEO_SIZE_CIF__
    STR_ID_VDOREC_VIDEO_SIZE_CIF,
#endif 

    STR_ID_VDOREC_VIDEO_SIZE_END
} vdorec_video_size_str_id_enum;

/***************** Video Qty *******************/
typedef enum
{
    STR_ID_VDOREC_VIDEO_QTY_START = VDOREC_VIDEO_QTY_BASE,

#ifdef __VDOREC_FEATURE_VIDEO_QTY_FINE__
    STR_ID_VDOREC_VIDEO_QTY_FINE,
#endif 

#ifdef __VDOREC_FEATURE_VIDEO_QTY_HIGH__
    STR_ID_VDOREC_VIDEO_QTY_HIGH,
#endif 

#ifdef __VDOREC_FEATURE_VIDEO_QTY_NORMAL__
    STR_ID_VDOREC_VIDEO_QTY_NORMAL,
#endif 

#ifdef __VDOREC_FEATURE_VIDEO_QTY_LOW__
    STR_ID_VDOREC_VIDEO_QTY_LOW,
#endif 

    STR_ID_VDOREC_VIDEO_QTY_END
} vdorec_video_qty_str_id_enum;

/***************** Size Limit *******************/
typedef enum
{
    STR_ID_VDOREC_SIZE_LIMIT_START = VDOREC_SIZE_LIMIT_BASE,

    STR_ID_VDOREC_SIZE_LIMIT_NO_LIMIT,
    STR_ID_VDOREC_SIZE_LIMIT_1,
    STR_ID_VDOREC_SIZE_LIMIT_2,
    STR_ID_VDOREC_SIZE_LIMIT_3,

    STR_ID_VDOREC_SIZE_LIMIT_END
} vdorec_size_limit_str_id_enum;

/***************** Time Limit *******************/
typedef enum
{
    STR_ID_VDOREC_TIME_LIMIT_START = VDOREC_TIME_LIMIT_BASE,

    STR_ID_VDOREC_TIME_LIMIT_NO_LIMIT,
    STR_ID_VDOREC_TIME_LIMIT_1,
    STR_ID_VDOREC_TIME_LIMIT_2,
    STR_ID_VDOREC_TIME_LIMIT_3,

    STR_ID_VDOREC_TIME_LIMIT_END
} vdorec_time_limit_str_id_enum;

/***************** Record Aud *******************/
typedef enum
{
    STR_ID_VDOREC_RECORD_AUD_START = VDOREC_RECORD_AUD_BASE,
    STR_ID_VDOREC_RECORD_AUD_OFF,
    STR_ID_VDOREC_RECORD_AUD_ON,

    STR_ID_VDOREC_RECORD_AUD_END
} vdorec_record_aud_str_id_enum;

/***************** Video Format *******************/
typedef enum
{
    STR_ID_VDOREC_VIDEO_FORMAT_START = VDOREC_VIDEO_FORMAT_BASE,
    STR_ID_VDOREC_VIDEO_FORMAT_3GP,
    STR_ID_VDOREC_VIDEO_FORMAT_MP4,

    STR_ID_VDOREC_VIDEO_FORMAT_END
} vdorec_video_format_str_id_enum;

/***************** Effect *******************/
typedef enum
{
    STR_ID_VDOREC_EFFECT_START = VDOREC_EFFECT_BASE,

#ifdef __VDOREC_FEATURE_EFFECT_NORMAL__
    STR_ID_VDOREC_EFFECT_NORMAL,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_GRAYSCALE__
    STR_ID_VDOREC_EFFECT_GRAYSCALE,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_SEPIA__
    STR_ID_VDOREC_EFFECT_SEPIA,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_SEPIA_GREEN__
    STR_ID_VDOREC_EFFECT_SEPIA_GREEN,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_SEPIA_BLUE__
    STR_ID_VDOREC_EFFECT_SEPIA_BLUE,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_COLOR_INVERT__
    STR_ID_VDOREC_EFFECT_COLOR_INVERT,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_GRAY_INVERT__
    STR_ID_VDOREC_EFFECT_GRAY_INVERT,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_BLACKBOARD__
    STR_ID_VDOREC_EFFECT_BLACKBOARD,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_WHITEBOARD__
    STR_ID_VDOREC_EFFECT_WHITEBOARD,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_COPPER_CARVING__
    STR_ID_VDOREC_EFFECT_COPPER_CARVING,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_BLUE_CARVING__
    STR_ID_VDOREC_EFFECT_BLUE_CARVING,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_EMBOSSMENT__
    STR_ID_VDOREC_EFFECT_EMBOSSMENT,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_CONTRAST__
    STR_ID_VDOREC_EFFECT_CONTRAST,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_JEAN__
    STR_ID_VDOREC_EFFECT_JEAN,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_SKETCH__
    STR_ID_VDOREC_EFFECT_SKETCH,
#endif 

#ifdef __VDOREC_FEATURE_EFFECT_OIL__
    STR_ID_VDOREC_EFFECT_OIL,
#endif 

    STR_ID_VDOREC_EFFECT_END
} vdorec_effect_str_id_enum;



/***************************************************************************** 
 * Screen
 *****************************************************************************/
typedef enum
{
    SCR_ID_VDOREC_APP = VDOREC_BASE + 1,
    SCR_ID_VDOREC_OPTION,
    SCR_ID_VDOREC_CAMCODER_SETTING,
    SCR_ID_VDOREC_VIDEO_SETTING,
    SCR_ID_VDOREC_EFFECT_SETTING,
    SCR_ID_VDOREC_STORAGE,
    SCR_ID_VDOREC_RESTORE_DEFAULT,
    SCR_ID_VDOREC_SAVING,
    SCR_ID_VDOREC_SAVE_CONFIRM,
    SCR_ID_VDOREC_COLOR_IDX_FRAME,
    SCR_ID_VDOREC_COLOR_IDX_FRAME_OPTION,
    SCR_ID_VDOREC_COLOR_IDX_FRAME_VIEW
   /* hongzhe.liu add start */ 
       #if defined(ANALOG_TV_SUPPORT)  
       ,SCR_ID_TV_IN_APP,
        SCR_ID_TV_IN_OPTION,
        SCR_ID_TV_IN_SAVING,
        SCR_ID_TV_IN_SAVE_CONFIRM,
        SCR_ID_TV_IN_SOURCE_FORMAT,
        SCR_ID_TV_IN_STORAGE,
        SCR_ID_TV_IN_REC_SETTING,
        SCR_ID_TLG_TV_OPTION,
        SCR_ID_TLG_TV_CHANNEL_LIST,
        SCR_ID_TLG_TV_SEARCHING,
        SCR_ID_TLG_TV_SELECT_AREA,
        SCR_ID_TLG_TV_SELECT_MODE,   //P_6226_M14_bw_Z0053 tv添加有线电视的选择菜单
        SCR_ID_TLG_TV_CHANNEL_EDIT,
        SCR_ID_TLG_TV_CHANNEL_NAME_EDIT,
        SCR_ID_TLG_TV_SAVE_CHANNEL_CONFIRM,
        SCR_ID_TLG_TV_CLEAR_CHANNEL_CONFIRM,
        SCR_ID_TLG_TV_CHANNEL_NAME_EDIT_OPTION,
        SCR_ID_TLG_TV_CHANNEL_OPTION
        //end
      #endif
   /* hongzhe.liu add end */
} vdorec_scr_id_enum;

#endif /* VDO_REC_RES_DEF_H */ 


