/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*******************************************************************************
 *
 * Filename:
 * ---------
 * CatScreenBrowserResDef.h
 *
 * Description:
 * ------------
 *    
 * (definition of data types)
 *
 * Author:
 *  Zhao Nan
 * -------
 * -------
 *
 *==============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *==============================================================================
 *******************************************************************************/

#ifndef _CSB_BROWSER_RES_DEF_H
#define _CSB_BROWSER_RES_DEF_H
#include "MMI_features.h"

#ifdef __MMI_CSB_BROWSER__

typedef enum
{
    STR_ID_CSB = CSB_BASE + 1,
    STR_ID_CSB_TEXT,
    STR_ID_CSB_VIEW_TEXT,
    STR_ID_CSB_SEARCH_TEXT,
    STR_ID_CSB_TESTTOOL_TEXT,
    STR_ID_CSB_START_VIEW_TEXT,
    STR_ID_CSB_START_VIEW_X_TEXT,
    STR_ID_CSB_VIEW_OPTIONS_TEXT,
    STR_ID_CSB_SEARCH_CONTROL_TEXT,
    STR_ID_CSB_SEARCH_APP_TEXT,
    STR_ID_CSB_SEARCH_SCREENID_TEXT,
    STR_ID_CSB_OPTIONS_VIEW_MODE_TEXT,
    STR_ID_CSB_OPTIONS_MODE_SETTINGS_TEXT,
    STR_ID_CSB_VIEW_MODE_AUTO_TEXT,
    STR_ID_CSB_VIEW_MODE_MANUAL_TEXT,
    STR_ID_CSB_AUTO_MODE_TIME_TEXT,
    STR_ID_CSB_MANUAL_MODE_TEXT,
    STR_ID_CSB_MANUAL_MODE_INTERACTIVE_TEXT,
    STR_ID_CSB_MANUAL_MODE_NONINTERACTIVE_TEXT,
    STR_ID_CSB_RUN_TESTTOOL_TEXT,
    STR_ID_CSB_SET_LOCATION_TEXT,
    STR_ID_CSB_TESTTOOL_PASS,
    STR_ID_CSB_TESTTOOL_FAIL,
    STR_ID_CSB_JPEG_FAIL_TEXT,
    STR_ID_CSB_MEMORY_FAIL_TEXT,
    STR_ID_CSB_NO_MEMORY_CARD,
    STR_ID_CSB_VIEW_IMAGES,
    STR_ID_CSB_CALL_SCR_TEXT,
    STR_ID_CSB_COLOR_PICKER_TEXT,
    STR_ID_CSB_EDITOR_TEXT,
    STR_ID_CSB_EDITOR_LIST_MENU_TEXT,
    STR_ID_CSB_EDITOR_POPUP_TEXT,
    STR_ID_CSB_IDLE_TEXT,
    STR_ID_CSB_IMAGE_VIEWER_TEXT,
    STR_ID_CSB_LIST_MENU_TEXT,
    STR_ID_CSB_MATRIX_MENU_TEXT,
    STR_ID_CSB_POPUP_TEXT,
    STR_ID_CSB_PROGRESS_BAR_TEXT,
    STR_ID_CSB_SLIDER_TEXT,
    STR_ID_CSB_RADIO_BUTTON_TEXT,
    STR_ID_CSB_CHECK_BOX_TEXT,
    STR_ID_CSB_SUB_LCD_TEXT,
    STR_ID_CSB_PANEL_TEXT,//052907 CSB
    STR_ID_CSB_CALLS_TEXT,
    STR_ID_CSB_ENGG_MODE_TEXT,
    STR_ID_CSB_EXTRA_TEXT,
    STR_ID_CSB_FUN_AND_GAMES_TEXT,
    STR_ID_CSB_FILE_MANAGER_TEXT,
    STR_ID_CSB_MESSAGES_TEXT,
    STR_ID_CSB_MISC_TEXT,
    STR_ID_CSB_MULTIMEDIA_TEXT,
    STR_ID_CSB_ORGANIZER_TEXT,
    STR_ID_CSB_PHONEBOOK_TEXT,
    STR_ID_CSB_PROFILE_TEXT,
    STR_ID_CSB_SERVICES_TEXT,
    STR_ID_CSB_SHORTCUT_TEXT,
    STR_ID_CSB_SETTINGS_TEXT,
    STR_ID_CSB_WAP_TEXT,
    STR_ID_CSB_UNUSED_TEXT,
    STR_ID_CSB_HID_TEXT,//052907 CSB
    STR_ID_CSB_DUMMY_TEXT,
    STR_ID_CSB_LSK_TEXT,
    STR_ID_CSB_RSK_TEXT,
    STR_ID_CSB_SCR_NOT_EXIST_TEXT,
    STR_ID_CSB_NO_SCR_FOUND_TEXT,
    STR_ID_CSB_SHOW_CATEGORY_TEXT,
    STR_ID_CSB_SCREEN_TEXT,
    STR_ID_CSB_FILE_PATH_TOO_LONG,
    STR_ID_CSB_MENUITEM1_TEXT,
    STR_ID_CSB_MENUITEM2_TEXT,
    STR_ID_CSB_MENUITEM3_TEXT,
    STR_ID_CSB_MENUITEM4_TEXT,
    STR_ID_CSB_MENUITEM5_TEXT,
    STR_ID_CSB_MENUITEM6_TEXT,
    STR_ID_CSB_MENUITEM7_TEXT,
    /* zhaonan modified */  
    STR_ID_CSB_DUMMY_TEXT_BUF,
    STR_ID_CSB_CATEGORY_TEXT_BUF,
	STR_ID_CSB_LSK_TEXT_BUF,
	STR_ID_CSB_RSK_TEXT_BUF,    
	STR_ID_CSB_MENUITEM1_TEXT_BUF,
	STR_ID_CSB_MENUITEM2_TEXT_BUF,
	STR_ID_CSB_MENUITEM3_TEXT_BUF,
	STR_ID_CSB_MENUITEM4_TEXT_BUF,
	STR_ID_CSB_MENUITEM5_TEXT_BUF,
	STR_ID_CSB_MENUITEM6_TEXT_BUF,
	STR_ID_CSB_MENUITEM7_TEXT_BUF,
	/* zhaonan modified */   
    STR_ID_CSB_CATEGORY_TEXT,
    STR_ID_CSB_PROCESSING_TEXT,
    STR_ID_CSB_SET_TEXT,
    STR_ID_CSB_TOTAL
} csb_str_id_enum;

/* 052907 CSB Start */
typedef enum
{
    IMG_ID_CSB = CSB_BASE + 1,
    IMG_ID_CSB_HID_IMG_BG,
    IMG_ID_CSB_DESKTOP_IMG_01_DISALBE,
    IMG_ID_CSB_DESKTOP_IMG_01_OFF,
    IMG_ID_CSB_DESKTOP_IMG_01_ON,
    IMG_ID_CSB_DESKTOP_IMG_01_DOWN,
    IMG_ID_CSB_DESKTOP_IMG_02_DISALBE,
    IMG_ID_CSB_DESKTOP_IMG_02_OFF,
    IMG_ID_CSB_DESKTOP_IMG_02_ON,
    IMG_ID_CSB_DESKTOP_IMG_02_DOWN,
    IMG_ID_CSB_DESKTOP_IMG_03_DISALBE,
    IMG_ID_CSB_DESKTOP_IMG_03_OFF,
    IMG_ID_CSB_DESKTOP_IMG_03_ON,
    IMG_ID_CSB_DESKTOP_IMG_03_DOWN,
    IMG_ID_CSB_DESKTOP_IMG_04_DISALBE,
    IMG_ID_CSB_DESKTOP_IMG_04_OFF,
    IMG_ID_CSB_DESKTOP_IMG_04_ON,
    IMG_ID_CSB_DESKTOP_IMG_04_DOWN,
    IMG_ID_CSB_DESKTOP_IMG_05_DISALBE,
    IMG_ID_CSB_DESKTOP_IMG_05_OFF,
    IMG_ID_CSB_DESKTOP_IMG_05_ON,
    IMG_ID_CSB_DESKTOP_IMG_05_DOWN,
    IMG_ID_CSB_DESKTOP_IMG_06_DISALBE,
    IMG_ID_CSB_DESKTOP_IMG_06_OFF,
    IMG_ID_CSB_DESKTOP_IMG_06_ON,
    IMG_ID_CSB_DESKTOP_IMG_06_DOWN,
    IMG_ID_CSB_DESKTOP_IMG_07_DISALBE,
    IMG_ID_CSB_DESKTOP_IMG_07_OFF,
    IMG_ID_CSB_DESKTOP_IMG_07_ON,
    IMG_ID_CSB_DESKTOP_IMG_07_DOWN,
    IMG_ID_CSB_DESKTOP_IMG_08_DISALBE,
    IMG_ID_CSB_DESKTOP_IMG_08_OFF,
    IMG_ID_CSB_DESKTOP_IMG_08_ON,
    IMG_ID_CSB_DESKTOP_IMG_08_DOWN,
    IMG_ID_CSB_DESKTOP_IMG_09_DISALBE,
    IMG_ID_CSB_DESKTOP_IMG_09_OFF,
    IMG_ID_CSB_DESKTOP_IMG_09_ON,
    IMG_ID_CSB_DESKTOP_IMG_09_DOWN,
    IMG_ID_CSB_DESKTOP_IMG_10_DISALBE,
    IMG_ID_CSB_DESKTOP_IMG_10_OFF,
    IMG_ID_CSB_DESKTOP_IMG_10_ON,
    IMG_ID_CSB_DESKTOP_IMG_10_DOWN,
    IMG_ID_CSB_DESKTOP_IMG_11_DISALBE,
    IMG_ID_CSB_DESKTOP_IMG_11_OFF,
    IMG_ID_CSB_DESKTOP_IMG_11_ON,
    IMG_ID_CSB_DESKTOP_IMG_11_DOWN,
    IMG_ID_CSB_DESKTOP_IMG_12_DISALBE,
    IMG_ID_CSB_DESKTOP_IMG_12_OFF,
    IMG_ID_CSB_DESKTOP_IMG_12_ON,
    IMG_ID_CSB_DESKTOP_IMG_12_DOWN,

    IMG_ID_CSB_MOUSE_IMG_UP_DISALBE,
    IMG_ID_CSB_MOUSE_IMG_UP_OFF,
    IMG_ID_CSB_MOUSE_IMG_UP_ON,
    IMG_ID_CSB_MOUSE_IMG_UP_DOWN,
    IMG_ID_CSB_MOUSE_IMG_DOWN_DISALBE,
    IMG_ID_CSB_MOUSE_IMG_DOWN_OFF,
    IMG_ID_CSB_MOUSE_IMG_DOWN_ON,
    IMG_ID_CSB_MOUSE_IMG_DOWN_DOWN,
    IMG_ID_CSB_MOUSE_IMG_LEFT_DISALBE,
    IMG_ID_CSB_MOUSE_IMG_LEFT_OFF,
    IMG_ID_CSB_MOUSE_IMG_LEFT_ON,
    IMG_ID_CSB_MOUSE_IMG_LEFT_DOWN,
    IMG_ID_CSB_MOUSE_IMG_RIGHT_DISALBE,
    IMG_ID_CSB_MOUSE_IMG_RIGHT_OFF,
    IMG_ID_CSB_MOUSE_IMG_RIGHT_ON,
    IMG_ID_CSB_MOUSE_IMG_RIGHT_DOWN,
    IMG_ID_CSB_MOUSE_IMG_COMMON,
    
    IMG_ID_CSB_TOTAL
} csb_img_id_enum;
/* 052907 CSB End */


typedef enum
{
    SCR_ID_CS_BROWSER_BASE = CSB_BASE + 1,
    SCR_ID_CSB,
    SCR_ID_CSB_VIEW_SCR_ID,
    SCR_ID_CSB_START_VIEW_SCR_ID,
    SCR_ID_CSB_START_VIEW_X_SCR_ID,
    SCR_ID_CSB_VIEW_OPTIONS_SCR_ID,
    SCR_ID_CSB_OPTIONS_VIEW_MODE_SCR_ID,
    SCR_ID_CSB_OPTIONS_MODE_SETTINGS_SCR_ID,
    SCR_ID_CSB_OPTIONS_AUTO_MODE_TIME_SCR_ID,
    SCR_ID_CSB_OPTIONS_MANUAL_MODE_SCR_ID,
    SCR_ID_CSB_SEARCH_SCR_ID,
    SCR_ID_CSB_SEARCH_BY_CONT_SCR_ID,
    SCR_ID_CSB_SEARCH_BY_APP_SCR_ID,
    SCR_ID_CSB_SEARCH_BY_SCRID_SCR_ID,
    SCR_ID_CSB_SEARCH_LIST_SCR_ID,
    SCR_ID_CSB_TESTTOOL_SCR_ID,
    SCR_ID_CSB_DUMMY_SCR_ID,
    SCR_ID_CSB_PROCESSING_SCR_ID,
    SCR_ID_CSB_SHOW_CURR_SCR_ID,
    SCR_ID_CSB_MEM_ERROR_SCR_ID,
    SCR_ID_CS_TOTAL
} csb_scr_id_enum;

/* Enum for UI Controls */
typedef enum
{
    CSB_CONT_CALL_SCR = 0,
    CSB_CONT_COLOR_PICKER_SCR,
    CSB_CONT_EDITOR_SCR,
    CSB_CONT_IDLE_SCR,
    CSB_CONT_IMAGE_VIEWER_SCR,
    CSB_CONT_LIST_MENU_SCR,
    CSB_CONT_MATRIX_MENU_SCR,
    CSB_CONT_POPUP_SCR,
    CSB_CONT_PROGRESS_BAR_SCR,
    CSB_CONT_SLIDER_SCR,
    CSB_CONT_RADIO_BUTTON_SCR,
    CSB_CONT_CHECK_BOX_SCR,
    CSB_CONT_SUB_LCD,
    CSB_CONT_PANEL,//052907 CSB
    CSB_TOTAL_CONTROLS
} csb_control_enum;

/* Enum for Applications */
typedef enum
{
    CSB_APP_CALLS = 0,
    CSB_APP_EDITOR,
    CSB_APP_ENGG_MODE,
    CSB_APP_EXTRA,
    CSB_APP_FUN_AND_GAMES,
    CSB_APP_FILE_MANAGER,
    CSB_APP_MESSAGES,
    CSB_APP_MISC,
    CSB_APP_MULTIMEDIA,
    CSB_APP_ORGANIZER,
    CSB_APP_PHONEBOOK,
    CSB_APP_PROFILE,
    CSB_APP_SERVICES,
    CSB_APP_SHORTCUT,
    CSB_APP_SETTINGS,
    CSB_APP_WAP,
    CSB_APP_HID,//052907 CSB
    CSB_TOTAL_APP
} csb_app_enum;
#endif /* __MMI_CSB_BROWSER__ */ 

#endif /* _CSB_BROWSER_RES_DEF_H */ 

