/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
*
 * Filename:
 * ---------
 * GameStairDefs.h
  *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  Game id define Stair.
 *
 * Author:
 * -------
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#ifndef _MMI_GX_STAIR_DEFS_H
#define _MMI_GX_STAIR_DEFS_H

/***************************************************************************** 
* Typedef 
*****************************************************************************/
/* String ID */
typedef enum
{
#if defined(__MMI_GAME_STAIR_128x160__) || defined(__MMI_GAME_STAIR_128x128__) || defined(__MMI_GAME_STAIR_176x220__)
    STR_ID_GX_STAIR_GAME_NAME = GAME_STAIR_BASE + 1,
    STR_ID_GX_STAIR_HELP_DESCRIPTION,
#elif defined(__MMI_GAME_CHICKEN_128x128__) || defined(__MMI_GAME_CHICKEN_128x160__)
    STR_ID_GX_STAIR_GAME_NAME_CHICKEN = GAME_STAIR_BASE + 1,
    STR_ID_GX_STAIR_HELP_DESCRIPTION_CHICKEN,
#elif defined(__MMI_GAME_ROBOT_176x220__) || defined(__MMI_GAME_ROBOT_128x160__)
    STR_ID_GX_STAIR_GAME_NAME_ROBOT = GAME_STAIR_BASE + 1,
    STR_ID_GX_STAIR_HELP_DESCRIPTION_ROBOT,
#endif 
    STR_ID_GX_STAIR_LEVEL_EASY,
    STR_ID_GX_STAIR_LEVEL_NORMAL,
    STR_ID_GX_STAIR_LEVEL_HARD,

    STR_ID_GX_STAIR_COUNT
} gx_stair_str_id_enum;

/* Image ID */
typedef enum
{
    IMG_ID_GX_STAIR_GAME_ICON = GAME_STAIR_BASE + 1,
    IMG_ID_GX_STAIR_BOX,
    IMG_ID_GX_STAIR_FLOAT_STAIR_1,
    IMG_ID_GX_STAIR_FLOAT_STAIR_2,
    IMG_ID_GX_STAIR_ROLE,
    IMG_ID_GX_STAIR_ROLE_DYING,
    IMG_ID_GX_STAIR_ROLE_FALLING_0,
    IMG_ID_GX_STAIR_ROLE_FALLING_1,
    IMG_ID_GX_STAIR_ROLE_LEFT_0,
    IMG_ID_GX_STAIR_ROLE_LEFT_1,
    IMG_ID_GX_STAIR_ROLE_RIGHT_0,
    IMG_ID_GX_STAIR_ROLE_RIGHT_1,
    IMG_ID_GX_STAIR_SCORE,
    IMG_ID_GX_STAIR_STAIR,
    IMG_ID_GX_STAIR_THORN,
    IMG_ID_GX_STAIR_THORN_STAIR,
    IMG_ID_GX_STAIR_TITLE,
    IMG_ID_GX_STAIR_WALL,
#if defined(__MMI_GAME_STAIR_128x160__) || defined(__MMI_GAME_STAIR_176x220__) || defined(__MMI_GAME_CHICKEN_128x160__) || defined(__MMI_GAME_ROBOT_176x220__) || defined(__MMI_GAME_ROBOT_128x160__)
    IMG_ID_GX_STAIR_ENERGY_BAR,
#elif defined(__MMI_GAME_STAIR_128x128__) || defined(__MMI_GAME_CHICKEN_128x128__)
    IMG_ID_GX_STAIR_ENERGY_BAR_HORIZONTAL,
#endif 

    IMG_ID_GX_STAIR_ROLE_FLYING_0,
    IMG_ID_GX_STAIR_ROLE_FLYING_1,
    IMG_ID_GX_STAIR_NUMBER_0,
    IMG_ID_GX_STAIR_NUMBER_1,
    IMG_ID_GX_STAIR_NUMBER_2,
    IMG_ID_GX_STAIR_NUMBER_3,
    IMG_ID_GX_STAIR_NUMBER_4,
    IMG_ID_GX_STAIR_NUMBER_5,
    IMG_ID_GX_STAIR_NUMBER_6,
    IMG_ID_GX_STAIR_NUMBER_7,
    IMG_ID_GX_STAIR_NUMBER_8,
    IMG_ID_GX_STAIR_NUMBER_9,
    IMG_ID_GX_STAIR_GRADESMAP,
    IMG_ID_GX_STAIR_GOPIC,
    IMG_ID_GX_STAIR_BACKGROUND,

#ifndef __MMI_GAME_MULTI_LANGUAGE_SUPPORT__
    IMG_ID_GX_STAIR_GOTEXT,
    IMG_ID_GX_STAIR_FLYING_MARK,	
#else
    IMG_ID_GX_STAIR_GOTEXT_LANGUAGE0,
    IMG_ID_GX_STAIR_FLYING_MARK_LANGUAGE0,
    IMG_ID_GX_STAIR_GOTEXT_LANGUAGE1,
    IMG_ID_GX_STAIR_FLYING_MARK_LANGUAGE1,
    IMG_ID_GX_STAIR_GOTEXT_LANGUAGE2,
    IMG_ID_GX_STAIR_FLYING_MARK_LANGUAGE2,
    IMG_ID_GX_STAIR_GOTEXT_LANGUAGE3,
    IMG_ID_GX_STAIR_FLYING_MARK_LANGUAGE3,
    IMG_ID_GX_STAIR_GOTEXT_LANGUAGE4,
    IMG_ID_GX_STAIR_FLYING_MARK_LANGUAGE4,
    IMG_ID_GX_STAIR_GOTEXT_LANGUAGE5,
    IMG_ID_GX_STAIR_FLYING_MARK_LANGUAGE5,
    IMG_ID_GX_STAIR_GOTEXT_LANGUAGE6,
    IMG_ID_GX_STAIR_FLYING_MARK_LANGUAGE6,
    IMG_ID_GX_STAIR_GOTEXT_LANGUAGE7,
    IMG_ID_GX_STAIR_FLYING_MARK_LANGUAGE7,
    IMG_ID_GX_STAIR_GOTEXT_LANGUAGE8,
    IMG_ID_GX_STAIR_FLYING_MARK_LANGUAGE8,
    IMG_ID_GX_STAIR_GOTEXT_LANGUAGE9,
    IMG_ID_GX_STAIR_FLYING_MARK_LANGUAGE9,
#endif

    IMG_ID_GX_STAIR_COUNT
} gx_stair_img_id_neum;


#endif /* _MMI_GX_STAIR_DEFS_H */ 

