/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 * PoCResDef.h
 *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  This file defines poc prototypes for other modules
 *
 * Author:
 * -------
 * -------
 *
==============================================================
 *              HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *------------------------------------------------------------------------------
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!! 
 *=============================================================
 *******************************************************************************/
#ifndef _MMI_POC_RES_DEF_H
#define _MMI_POC_RES_DEF_H

/*---------------------------------------------------------------------------*/
/* Definition */
/*---------------------------------------------------------------------------*/
#define POC_STRING_BASE                     (POC_BASE + 1)
#define POC_IMAGE_BASE                          (POC_BASE + 1)
#define POC_SCREEN_BASE                     (POC_BASE + 1)

/*---------------------------------------------------------------------------*/
/* Enum */
/*---------------------------------------------------------------------------*/
/* Screen ID */
typedef enum
{
    SCR_ID_POC_MAIN = POC_SCREEN_BASE,
    SCR_ID_POC_CONTACT,
    SCR_ID_POC_CONTACT_OPT,
    SCR_ID_POC_CONTACT_ENTRY_SETTINGS,
    SCR_ID_POC_CONTACT_ENTRY_MODIFY,
    SCR_ID_POC_CONTACT_ENTRY_ADD,
    SCR_ID_POC_CONTACT_ENTRY_INFO,
    SCR_ID_POC_CONTACT_ENTRY_ATTR,
    SCR_ID_POC_CONTACT_ENTRY_ALLOW_INVITE,
    SCR_ID_POC_CONTACT_ENTRY_ALLOW_SUBSCRIBE,
    SCR_ID_POC_CONTACT_ENTRY_PRES_ATTR,
    SCR_ID_POC_CONTACT_ALERT,
    SCR_ID_POC_CONTACT_ADHOC_TALK,
    SCR_ID_POC_TALK_GROUP,
    SCR_ID_POC_TALK_GROUP_ENTRY,
    SCR_ID_POC_TALK_GROUP_OPT,
    SCR_ID_POC_TALK_GROUP_OPT_EMPTY,
    SCR_ID_POC_TALK_GROUP_ENTRY_SETTINGS,
    SCR_ID_POC_TALK_GROUP_ENTRY_INFO,
    SCR_ID_POC_TALK_GROUP_ENTRY_ATTR,
    SCR_ID_POC_TALK_GROUP_ENTRY_ADD,
    SCR_ID_POC_TALK_GROUP_ENTRY_FROM_CONTACT,
    SCR_ID_POC_TALK_GROUP_ADD,
    SCR_ID_POC_TALK_GROUP_ADD_GROUP_SELECT_ENTRY,
    SCR_ID_POC_TALK_GROUP_INFO,
    SCR_ID_POC_TALK_GROUP_INFO_ATTR,
    SCR_ID_POC_TALK_GROUP_CALL_OTHERS_GROUP,
    SCR_ID_POC_HISTORY,
    SCR_ID_POC_HISTORY_INFO,
    SCR_ID_POC_HISTORY_OPT,
    SCR_ID_POC_SETTING,
    SCR_ID_POC_SETTING_MYSTATUS,
    SCR_ID_POC_SETTING_MYSTATUS_ACTIVITY,
    SCR_ID_POC_SETTING_MYSTATUS_MOOD,
    SCR_ID_POC_SETTING_PRIVACY,
    SCR_ID_POC_SETTING_PRIVACY_ADDR,
    SCR_ID_POC_SETTING_ADHOC_STR,
    SCR_ID_POC_SETTING_PROF,
    SCR_ID_POC_SETTING_PROF_OPT,
    SCR_ID_POC_SETTING_PROF_OPT_EDIT,
    SCR_ID_POC_SETTING_PROF_OPT_EDIT_POC,
    SCR_ID_POC_SETTING_PROF_OPT_EDIT_CONN,
    SCR_ID_POC_GENERAL_PROGRESSING,
    SCR_ID_POC_CM,
    SCR_ID_POC_REG,
    SCR_ID_POC_TALK_OPTION,
    SCR_ID_POC_TALK_OPTION_ADD_USER,
    SCR_ID_POC_INCOMING_ALERT,

    /* add new items before this line */
    SCR_ID_POC_TOTAL
} POC_SCREEN_ENUM;

/* String ID */
typedef enum
{
    STR_ID_POC_MAIN = POC_STRING_BASE,
    STR_ID_POC_STATUS,
    STR_ID_POC_CONTACTS,
    STR_ID_POC_TALK_GROUPS,
    STR_ID_POC_CALL_HISTORY,
    STR_ID_POC_SETTINGS,
    STR_ID_POC_SEND_ALERT,
    STR_ID_POC_ADHOC_TALK,
    STR_ID_POC_REFRESH_STATUS,
    STR_ID_POC_ENTRY_SETTINGS,
    STR_ID_POC_MODIFY,
    STR_ID_POC_SESSION_ID,
    STR_ID_POC_INFO,
    STR_ID_POC_ENTRY_INFO,
    STR_ID_POC_NAME,
    STR_ID_POC_URI,
    STR_ID_POC_ATTRIBUTES,
    STR_ID_POC_DEFAULT_RULE,
    STR_ID_POC_SET_ATTR,
    STR_ID_POC_ALLOW_INVITE,
    STR_ID_POC_ACCEPT,
    STR_ID_POC_REJECT,
    STR_ID_POC_POLITE_BLOCK,
    STR_ID_POC_AUTO_ACCEPT,
    STR_ID_POC_ALLOW_SUBSCRIBE,
    STR_ID_POC_PROVIDE_PRES,
    STR_ID_POC_SUBSCRIBE_PRES,
    STR_ID_POC_PRESENCE_ATTR,
    STR_ID_POC_PRESENCE_UPDATED,
    STR_ID_POC_SUBSCRIBE,
    STR_ID_POC_UNSUBSCRIBE,
    STR_ID_POC_ACTIVITY,
    STR_ID_POC_MOOD,
    STR_ID_POC_ALL,
    STR_ID_POC_ALERT_TEXT,
    STR_ID_POC_SEND_FAKE,
    STR_ID_POC_ADD_GROUP,
    STR_ID_POC_DELETE_GROUP,
    STR_ID_POC_GROUP_INFO,
    STR_ID_POC_CALL_OTHERS_GROUP,
    STR_ID_POC_ADD_FROM_CONTACTS,
    STR_ID_POC_CONF_STATE,
    STR_ID_POC_INVITE_USER_DYNA,
    STR_ID_POC_JOIN_HANDLING,
    STR_ID_POC_INIT_CONFERENCE,
    STR_ID_POC_ANONYMITY,
    STR_ID_POC_MAX_PARTICIPANTS,
    STR_ID_POC_INVITE_MEMBER,
    STR_ID_POC_MY_STATUS,
    STR_ID_POC_NONE,
    STR_ID_POC_PRES_INFO,
    STR_ID_POC_AWAY,
    STR_ID_POC_APPOINTMENT,
    STR_ID_POC_BUSY,
#if (0)
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
#endif /* (0) */ 
    STR_ID_POC_HAPPY,
    STR_ID_POC_BORED,
    STR_ID_POC_DEPRESSED,
    STR_ID_POC_ANSWER_MODE,
    STR_ID_POC_CALL_BARRING,
    STR_ID_POC_ALERT_BARRING,
    STR_ID_POC_MAO,
    STR_ID_POC_PRIVACY,
    STR_ID_POC_DISABLE,
    STR_ID_POC_ENABLE,
    STR_ID_POC_PRIVACY_ADDR,
    STR_ID_POC_START_AT_BOOTUP,
    STR_ID_POC_USE_XDM,
    STR_ID_POC_USE_PRES,
    STR_ID_POC_POC_SETTINGS,
    STR_ID_POC_PROFILES,
    STR_ID_POC_PROFILE_1,
    STR_ID_POC_PROFILE_2,
    STR_ID_POC_PROFILE_3,
    STR_ID_POC_PROFILE_NAME,
    STR_ID_POC_PASSWORD,
    STR_ID_POC_SERVER_ADDR,
    STR_ID_POC_SERVER_PORT,
    STR_ID_POC_XDM_ADDR,
    STR_ID_POC_CONNECTION_SETTINGS,
    STR_ID_POC_DATA_ACCOUNT,
    STR_ID_POC_USE_PROXY,
    STR_ID_POC_PROXY_ADDR,
    STR_ID_POC_PROXY_PORT,
    STR_ID_POC_PROXY_USERNAME,
    STR_ID_POC_PROXY_PASSWORD,
    STR_ID_POC_MESSAGE,
    STR_ID_POC_PROCESSING,
    STR_ID_POC_NULL_STR_ERR,
    STR_ID_POC_AUTO_ANS,
    STR_ID_POC_MANUAL_ANS,
    STR_ID_POC_INVITING_SUCCESS,
    STR_ID_POC_INVITING_FAIL,
    STR_ID_POC_STATUS_MODE_MODIFIED,
    STR_ID_POC_STATUS_MODE_NOT_MODIFIED,
    STR_ID_POC_ADHOC_STR,

    STR_ID_POC_ALERT,
    STR_ID_POC_ALERT_FROM,
    STR_ID_POC_REGISTERING,
    STR_ID_POC_DEREGISTERING,
    STR_ID_POC_REGISTERED,
    STR_ID_POC_DEREGISTERED,
    STR_ID_POC_CM_INVITING,
    STR_ID_POC_CM_MO_RINGING,
    STR_ID_POC_CM_MT_RINGING,
    STR_ID_POC_CM_CONNECTED_IDLE,
    STR_ID_POC_CM_TALKING,
    STR_ID_POC_CM_LISTENING,
    STR_ID_POC_CM_ANONYMOUS,
    STR_ID_POC_ERR_NOT_REGISTERED,
    STR_ID_POC_ERR_INVALID_SETTING,
    STR_ID_POC_ERR_INVALID_URI,
    STR_ID_POC_ERR_NOT_FOUND,
    STR_ID_POC_ERR_BUSY,
    STR_ID_POC_ERR_DEREGISTER_FIRST,
    STR_ID_POC_ERR_TERMINATE_CALL_FIRST,
    STR_ID_POC_ERR_FLOOR_LOST,
    STR_ID_POC_ERR_REG_PARTIAL_SUCCESS,
    STR_ID_POC_ERR_XDM_ERROR,
    STR_ID_POC_ERR_MAXIMUM_REACHED,
    STR_ID_POC_ERR_AUTH_FAIL,
    STR_ID_POC_ERR_TURN_OFF_PRIVACY_MODE,
    /* new error requests */
    STR_ID_POC_ERR_FS_ERROR,
    STR_ID_POC_ERR_FLOOR_ALREADY_IN_USE,
    STR_ID_POC_ERR_SERVER_INT_ERROR,
    STR_ID_POC_ERR_ONLY_ONE_USER,
    STR_ID_POC_ERR_FLOOR_RETRY_AFTER,
    STR_ID_POC_ERR_LISTEN_ONLY,
    STR_ID_POC_ERR_TALK_TOO_LONG,
    STR_ID_POC_ERR_NO_FLOOR_PERMISSION,
    STR_ID_POC_ERR_FLOOR_PREEMPTED,
    STR_ID_POC_ERR_NO_RESOURCE,
    STR_ID_POC_ERR_TIMEOUT_ERROR,
    STR_ID_POC_ERR_RECV_SIP_BYE,
    STR_ID_POC_ERR_TALK_ABORTED,
    STR_ID_POC_ERR_TURN_ON_XDM,
    STR_ID_POC_ERR_AUTH_REQ,
    STR_ID_POC_ERR_FORBIDDEN,

    /* add new items before this line */
    STR_ID_POC_DEFINES_MAX
} POC_STRING_ENUM;

/* Image ID */
typedef enum
{
    IMG_ID_POC_ICON = POC_IMAGE_BASE,
    IMG_ID_POC_NOIMAGE,
    IMG_ID_POC_CONTACT_NAME,
    IMG_ID_POC_CONTACT_URI,
    IMG_ID_POC_CONTACT_ATTR,

    IMG_ID_POC_PROFILE_SELECTED,
    IMG_ID_POC_DATE,
    IMG_ID_POC_TIME,
    IMG_ID_POC_MSG,

    IMG_ID_POC_ONLINE,
    IMG_ID_POC_OFFLINE,
    IMG_ID_POC_BLOCK,

    IMG_ID_POC_PROFILE_NAME,
    IMG_ID_POC_PROFILE_USER_NAME,
    IMG_ID_POC_PROFILE_URI,
    IMG_ID_POC_PROFILE_PASSWORD,
    IMG_ID_POC_PROFILE_SERVER_ADDR,
    IMG_ID_POC_PROFILE_SERVER_PORT,
    IMG_ID_POC_PROFILE_XDM_ADDR,

    IMG_ID_POC_CM_INVITING,
    IMG_ID_POC_CM_MO_RINGING,
    IMG_ID_POC_CM_MT_RINGING,
    IMG_ID_POC_CM_CONNECTED_IDLE,
    IMG_ID_POC_CM_TALKING,
    IMG_ID_POC_CM_LISTENING,

    /* add new items before this line */
    IMG_ID_POC_DEFINES_MAX
} POC_IMAGE_ENUM;

/* enum */

#endif /* _MMI_POC_RES_DEF_H */ 

