#ifdef __MMI_DUAL_SIM_MASTER__
/* MTK head files*/
#include "MMI_features.h"
#include "wgui_status_icons.h"
#include "SimDetectionDef.h"
#include "SimDetectionGprot.h"
#include "gui_data_types.h"
#include "GSM7BitDefaultAlphabet.h"
#include "wgui_categories_idlescreen.h"
#include "wgui_categories_popup.h"
#include "wgui_categories_inputs.h"
#include "StatusIconRes.h"
#include "GlobalDefs.h"
#include "SettingProfile.h"
#include "SettingDefs.h"
#include "IdleAppDef.h"
#include "HistoryGprot.h"
#include "CommonScreens.h"
#include "EventsGprot.h"
#include "GlobalConstants.h"
#include "SimDetectionGprot.h"
#include "EventsGprot.h"
#include "wgui_categories_inputsenum.h"
#include "MainMenuDef.h"
/* MTK head files*/

#ifdef __MMI_UCM__
#include "UCMResDef.h"
#endif /* __MMI_UCM__ */

#include "CallHistoryEnum.h"
#include "CallSetUpEnum.h"
#include "ChatAppResDef.h"
#include "MessagesResourceData.h"
#include "NetworkSetupGProt.h"
#include "PhoneBookDef.h"
#include "ServiceDefs.h"
#include "vObjectsResDef.h"
#if defined(__MMI_EMAIL__)
#include "EmailAppResDef.h"
#endif
#include "FileManagerDef.h"

#if defined(__SYNCML_SUPPORT__)
#include "SyncMLResDef.h"
#endif

#if defined(__MMI_IMPS__)
#include "IMPSResDef.h"
#endif

#include "MTPNP_AD_resdef.h"
#include "MTPNP_PFAL_menuitem.h"

const ST_MTPNP_AD_MENU MasterMenuId[] = {
    /* sms */
    {MENU_MTPNP_MSGBOX_OPT_MASTER_FORWARD, STRING_MTPNP_MASTER_MSGBOX_FORWARD, STRING_MTPNP_MASTER_MSGBOX_FORWARD},
    {EMS_ED_OPT_DONE, STR_GLOBAL_DONE, STRING_MTPNP_SMS_MASTER_DONE},
    {SMS_OUTBOX_OPT_SEND_MENUID, STR_GLOBAL_SEND, STR_GLOBAL_SEND},
    {MESSAGES_MENU_MSG_SETTINGS_MENUID, STRING_MTPNP_SIM1_MESSAGESETUP_MENUENTRY,
     STRING_MTPNP_SIM1_MESSAGESETUP_MENUENTRY},
    {MESSAGES_MENU_VMAIL_MENUID, STRING_MTPNP_SIM1_VMAIL_MENUENTRY, STRING_MTPNP_SIM1_VMAIL_MENUENTRY},
    {MESSAGES_MENU_CB_MENUID, STRING_MTPNP_SIM1_CB_MENUENTRY, STRING_MTPNP_SIM1_CB_MENUENTRY},
    {SMS_OUTBOX_OPT_SEND_MENUID, STR_GLOBAL_SEND, STRING_MTPNP_OUTBOX_MASTER_SEND_SMS},    
    {MENU_MTPNP_SMS_SELECT_SIM1_OPTION, STRING_MTPNP_OUTBOX_MASTER_SEND_SMS, STRING_MTPNP_OUTBOX_MASTER_SEND_SMS},
    {MENU_MTPNP_SMS_SELECT_SAVE_SIM1_OPTION, STRING_MTPNP_SAVE_SMS_TO_SIM1, STRING_MTPNP_SAVE_SMS_TO_SIM1},

#if defined(__MMI_EMAIL__)
    {MENU_ID_EMAIL_MAIN, STR_EMAIL_MAIN_ID, STR_EMAIL_MAIN_ID},
#endif

#if defined(__MMI_IMPS__)
    {MENU_ID_IMPS_MAIN, STR_ID_IMPS, STR_ID_IMPS},
#endif

#if defined(__SYNCML_SUPPORT__)
    {MENU_ID_SYNCML_MAIN, STR_ID_SYNC_MENU, STR_ID_SYNC_MENU},
#endif

    /* security */
//    {MENU9101_SECURITY, STR_MENU9101_SECURITY, STRING_MTPNP_CARD1_SECURITY_SETTING},
//    {MENU9169_SIM_LOCK, STR_MENU9169_SIM_LOCK, STR_MENU9169_SIM_LOCK},
//    {MENU9167_FIXED_DIAL, STR_MENU9167_FIXED_DIAL, STR_MENU9167_FIXED_DIAL},
//    {MENU9168_BARRED_DAIL, STR_MENU9168_BARRED_DAIL, STR_MENU9168_BARRED_DAIL},
//    {MENU9174_CP_PIN1, STR_MENU9174_CP_PIN1, STR_MENU9174_CP_PIN1},
//    {MENU9175_CP_PIN2, STR_MENU9175_CP_PIN2, STR_MENU9175_CP_PIN2},

    /* call */
    {MENU_ID_UCM_CALL_SETTING_SIM1, STRING_MTPNP_CARD1_CALL_SETTING, STRING_MTPNP_CARD1_CALL_SETTING},
    {MENU_CALLER_ID, STR_MENU_CALLER_ID, STR_MENU_CALLER_ID},
    {MENU8237_SCR8093_MNGCALL_MENU_WAIT, STR_SCR8094_MNGCALL_CALWAIT_MENU_CAPTION,
     STR_SCR8094_MNGCALL_CALWAIT_MENU_CAPTION},
    {MENU8237_SCR8093_MNGCALL_MENU_FWD, STR_MENU8238_MNGCALL_CALLFWD_CAPTION, STR_MENU8238_MNGCALL_CALLFWD_CAPTION},
    {MENU8237_SCR8093_MNGCALL_MENU_BARRING, STR_MENU_CALL_BARRING, STR_MENU_CALL_BARRING},
    {MENU_LINE_SWCH, STR_LINE_SWITCH, STR_LINE_SWITCH},

    /* call history */
    {MAIN_MENU_CALL_HISTORY, MAIN_MENU_CALL_HISTORY_TEXT, STRING_MTPNP_CARD1_CALL_HISTORY},
    {MENU8113_CALLHISTORY_RESETCALL, STR_MENU8113_CALLHISTORY_RESETCALL, STR_MENU8113_CALLHISTORY_RESETCALL},
    {MENU_CALL_HISTORY_CALLCOST, STR_MENU_CALL_COST_MAIN, STR_MENU_CALL_COST_MAIN},
    {MENU_CALL_HISTORY_SMSCOUNTER, STR_SMS_CAPTION, STR_SMS_CAPTION},
    {MENU_CALL_HISTORY_GPRSCOUNTER, STR_GPRS_CAPTION, STR_GPRS_CAPTION},
    {MENU_CALL_TIME_SETUP, STR_MENU_CALL_TIME_SETUP, STR_MENU_CALL_TIME_SETUP},
    {MENU_MISSED_CALLS, STR_MENU_MISSED_CALLS, STR_MENU_MISSED_CALLS},
    {MENU_DIALED_CALLS, STR_MENU_DIALED_CALLS, STR_MENU_DIALED_CALLS},
    {RECEIVED_CALL_MENU_CALL, STRING_MTPNP_SIM1DIAL, STRING_MTPNP_SIM1DIAL},
    {MISSED_CALL_MENU_CALL, STRING_MTPNP_SIM1DIAL, STRING_MTPNP_SIM1DIAL},
    {DIALED_CALL_MENU_CALL, STRING_MTPNP_SIM1DIAL, STRING_MTPNP_SIM1DIAL},
    {MENU_MTPNP_RECEIVED_CALL_MENU_CALL, STRING_MTPNP_SIM1DIAL, STRING_MTPNP_SIM1DIAL},
    {MENU_MTPNP_MISSED_CALL_MENU_CALL, STRING_MTPNP_SIM1DIAL, STRING_MTPNP_SIM1DIAL},
    {MENU_MTPNP_DIALED_CALL_MENU_CALL, STRING_MTPNP_SIM1DIAL, STRING_MTPNP_SIM1DIAL},
    {MENU_ALL_CALLS, STR_GLOBAL_DELETE_ALL, STR_GLOBAL_DELETE_ALL},
    {MENU_RECEIVED_CALLS, STR_MENU_RECEIVED_CALLS, STR_MENU_RECEIVED_CALLS},

//    {MENU_SETTING_SPEED_DIAL, STR_MENU_SETTING_SPEED_DIAL, STR_MENU_SETTING_SPEED_DIAL},
    {MENU_IP_NUM_ACTIVATE, STR_GLOBAL_ACTIVATE, STR_GLOBAL_ACTIVATE},

    /* network */
    {MENU9185_NETWORK_SETUP, STR_ID_NETSET_MITEM9185, STR_ID_NETSET_MITEM9185},
#ifdef __MANUAL_MODE_NW_SEL__
    {MENU9186_SELECTION_MODE, STR_ID_NETSET_SELECTION_SELECT_NETWORK, STR_ID_NETSET_SELECTION_SELECT_NETWORK},
#else
    {MENU9186_SELECTION_MODE, STR_ID_NETSET_MITEM9186_MANUAL, STR_ID_NETSET_MITEM9186_MANUAL},
#endif
    {MENU9187_PREFERRED_NETWORKS, STR_ID_NETSET_MITEM9187, STR_ID_NETSET_MITEM9187},
#ifdef __MMI_GPRS_FEATURES__
    {MENU9189_GPRS_CONNECTION_MODE, STR_ID_NETSET_MITEM9189, STR_ID_NETSET_MITEM9189},
#endif
#ifdef __IP_NUMBER__
    {SLAVE_MENU_CALL_INCOMING_OPT_CARD1_IP_DIALBACK, SLAVE_STR_CALL_INCOMING_OPT_CARD1_IP_DIALBACK,
     SLAVE_STR_CALL_INCOMING_OPT_CARD1_IP_DIALBACK},
#endif
#if defined(__MMI_PHB_IP_DIAL_FROM_PHB__)       /* IP Dial from phonebook entry option menu. */
    {MENU_MTPNP_PHB_OPTION_IP_DIAL_SIM1, STRING_MTPNP_PHB_OPTION_IP_DIAL_SIM1, STRING_MTPNP_PHB_OPTION_IP_DIAL_SIM1},
#endif

    /* CHAT message */
#ifdef __MMI_MESSAGES_CHAT__
    {MENU_MTPNP_CHARSTART_MASTER_NEW, STRING_MTPNP_CHOOSE_MASTER_CHAT, STRING_MTPNP_CHOOSE_MASTER_CHAT},
#endif  /* __MMI_MESSAGES_CHAT__ */
    /* CHAT message */

    {SLAVE_MENU_CALL_INCOMING_OPT_CARD1_DIALBACK, SLAVE_STR_CALL_INCOMING_OPT_CARD1_DIALBACK,
     SLAVE_STR_CALL_INCOMING_OPT_CARD1_DIALBACK},
    /* other */
    {MENU_VCLNDR_SEND_BY_SMS, STR_ID_VOBJ_FORWARD_TO_SMS, STRING_MTPNP_VOBJ_FORWARD_TO_CARD1_SMS}

};

const ST_MTPNP_AD_MENU SlaveMenuId[] = {
    /* sms */
    {MENU_MTPNP_EMS_ED_OPT_DONE, STR_GLOBAL_DONE, STRING_MTPNP_SMS_SLAVE_DONE},
    {MENU_MTPNP_MSGBOX_OPT_SLAVE_FORWARD, STRING_MTPNP_SLAVE_MSGBOX_FORWARD, STRING_MTPNP_SLAVE_MSGBOX_FORWARD},
    {MENU_MTPNP_SMS_SELECT_SIM2_OPTION, STRING_MTPNP_OUTBOX_SLAVE_SEND_SMS, STRING_MTPNP_OUTBOX_SLAVE_SEND_SMS},
    {MENU_MTPNP_OUTBOX_OPT_SEND_SMS, STRING_MTPNP_OUTBOX_SLAVE_SEND_SMS, STRING_MTPNP_OUTBOX_SLAVE_SEND_SMS},
    {MENU_MTPNP_SMS_SELECT_SAVE_SIM2_OPTION, STRING_MTPNP_SAVE_SMS_TO_SIM2, STRING_MTPNP_SAVE_SMS_TO_SIM2},

    /* phone setting */
    {MENU_MTPNP_PHONE_SETTING, STRING_MTPNP_PHONE_SETTING, STRING_MTPNP_PHONE_SETTING},

    /* call setting */
    {MENU_MTPNP_CALL_SETTING, STRING_MTPNP_CALL_SETTING, STRING_MTPNP_CALL_SETTING},

    /* call history */
    {MENU_MTPNP_CALL_HISTORY, STRING_MTPNP_CALL_HISTORY, STRING_MTPNP_CALL_HISTORY},
    {MENU_MTPNP_SIM1_RECEIVED_NUM_CALL, STRING_MTPNP_SIM2DIAL, STRING_MTPNP_SIM2DIAL},
    {MENU_MTPNP_SIM1_MISSED_NUM_CALL, STRING_MTPNP_SIM2DIAL, STRING_MTPNP_SIM2DIAL},
    {MENU_MTPNP_SIM1_DIALED_NUM_CALL, STRING_MTPNP_SIM2DIAL, STRING_MTPNP_SIM2DIAL},

    /* security setting */
//    {MENU_MTPNP_SECURITY_SETTING, STRING_MTPNP_SECURITY_SETTING, STRING_MTPNP_SECURITY_SETTING},

    /* network setup */
    {MENU_MTPNP_NETWORK_SETUP, STRING_MTPNP_NETWORK_SETUP, STRING_MTPNP_NETWORK_SETUP},

    /* message setting */
    {MENU_MTPNP_MSG_SETTINGS_MENUID, STRING_MTPNP_MESSAGESETUP_MENUENTRY, STRING_MTPNP_MESSAGESETUP_MENUENTRY},

    /* broadcast message */
    {MENU_MTPNP_CB_MESSAGES, STRING_MTPNP_CB_MENUENTRY, STRING_MTPNP_CB_MENUENTRY},

    /* voice mail server */
    {MENU_MTPNP_VMAIL, STRING_MTPNP_VMAIL_MENUENTRY, STRING_MTPNP_VMAIL_MENUENTRY},

    /* vcard */
#ifdef __IP_NUMBER__
    {SLAVE_MENU_CALL_INCOMING_OPT_CARD2_IP_DIALBACK, SLAVE_STR_CALL_INCOMING_OPT_CARD2_IP_DIALBACK,
     SLAVE_STR_CALL_INCOMING_OPT_CARD2_IP_DIALBACK},
#endif
#if defined(__MMI_PHB_IP_DIAL_FROM_PHB__)       /* IP Dial from phonebook entry option menu. */
    {MENU_MTPNP_PHB_OPTION_IP_DIAL_SIM2, STRING_MTPNP_PHB_OPTION_IP_DIAL_SIM2, STRING_MTPNP_PHB_OPTION_IP_DIAL_SIM2},
#endif

    /* CHAT message */
#ifdef __MMI_MESSAGES_CHAT__
    {MENU_MTPNP_CHARSTART_SLAVE_NEW, STRING_MTPNP_CHOOSE_SLAVE_CHAT, STRING_MTPNP_CHOOSE_SLAVE_CHAT},
#endif  /* __MMI_MESSAGES_CHAT__ */
    /* CHAT message */

    {SLAVE_MENU_CALL_INCOMING_OPT_CARD2_DIALBACK, SLAVE_STR_CALL_INCOMING_OPT_CARD2_DIALBACK,
     SLAVE_STR_CALL_INCOMING_OPT_CARD2_DIALBACK}
};

const ST_MTPNP_AD_MENU MasterPhbMenuId[] = {
    /* extra phonebook */
//    {MITEM105_PBOOK_OWNER_NUMBER, STRING_MTPNP_SIM1_OWNER_NUMBER, STRING_MTPNP_SIM1_OWNER_NUMBER},
//    {MENU_PHONEBOOK_SERVICENUMBER, STR_SDL_MAIN_MENU, STR_SDL_MAIN_MENU},
//    {MITEM116_PBOOK_SOS_NUMBER, STR_SOS_MENU_ITEM, STR_SOS_MENU_ITEM},
    {MENU_SETTING_SHOW_OWN_NUMBER, STR_OWN_NO, STR_OWN_NO},
    /* phonebook */
//    {MITEM_ADD_ENTRY_TO_SIM, STRING_MTPNP_SIM1PHB_ADD_NEW_ENTRY, STRING_MTPNP_SIM1PHB_ADD_NEW_ENTRY},
//    {MITEM_PBOOK_DELETE_ALL_SIM, STRING_MTPNP_SIM1PHB_DELETEALL, STRING_MTPNP_SIM1PHB_DELETEALL},


//    {MENU_ID_PHB_NLF_SIM, STR_ID_PHB_NLF_SIM, STR_ID_PHB_NLF_SIM},
//    {MITEM_STORAGE_LOCATION_SIM, STR_STORAGE_SIM, STR_STORAGE_SIM},
//    {MENU_FMGR_FWD_PHB, STR_FMGR_PHB, STR_FMGR_PHB}
};

const ST_MTPNP_AD_MENU SlavePhbMenuId[] = {
    /* extra phonebook */
//    {MENU_MTPNP_CARD2_OWNER_NUMBER, STRING_MTPNP_OWNER_NUMBER, STRING_MTPNP_OWNER_NUMBER},
//    {MENU_MTPNP_CARD2_SDL_NUMBER, STRING_MTPNP_SDL_NUMBER, STRING_MTPNP_SDL_NUMBER},
//    {MENU_MTPNP_CARD2_SOS_NUMBER, STRING_MTPNP_SOS_NUMBER, STRING_MTPNP_SOS_NUMBER},
    
    {MENU_MTPNP_CARD2_PHBEXTRA, STRING_MTPNP_SHOW_OWNER_NUMBER, STRING_MTPNP_SHOW_OWNER_NUMBER},
    {MENU_MTPNP_SHOW_CARD2_OWNER_NUMBER, STRING_MTPNP_SHOW_OWNER_NUMBER, STRING_MTPNP_SHOW_OWNER_NUMBER},

    /* phonebook */
//    {MENU_MTPNP_PB_ADD_SIM2, STRING_MTPNP_SIM2PHB_ADD_NEW_ENTRY, STRING_MTPNP_SIM2PHB_ADD_NEW_ENTRY},
//    {MENU_MTPNP_PB_DELALL_SIM2, STRING_MTPNP_SIM2PHB_DELETEALL, STRING_MTPNP_SIM2PHB_DELETEALL},


//    {MENU_MTPNP_PB_PRE_STORAGE_SIM2, STRING_MTPNP_SIM2PHB_PRESTORAGE, STRING_MTPNP_SIM2PHB_PRESTORAGE},
//    {MENU_MTPNP_PHB_NLF_SIM2, STRING_MTPNP_SIM2PHB_NLF_SIM2, STRING_MTPNP_SIM2PHB_NLF_SIM2}
};

const ST_MTPNP_AD_MENU IPDialMenuId[] = {
    {MENU_MTPNP_PHB_OPTION_IP_DIAL_SIM1, STRING_MTPNP_PHB_OPTION_IP_DIAL_SIM1, STRING_MTPNP_PHB_OPTION_IP_DIAL_SIM1},
    {MENU_MTPNP_PHB_OPTION_IP_DIAL_SIM2, STRING_MTPNP_PHB_OPTION_IP_DIAL_SIM2, STRING_MTPNP_PHB_OPTION_IP_DIAL_SIM2},
    {MENU_ID_PHB_OPTION_IP_DIAL, STR_ID_PHB_OPTION_IP_DIAL, STR_ID_PHB_OPTION_IP_DIAL}

};
#endif /* __MMI_DUAL_SIM_MASTER__ */
