/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/**
 *	Copyright Notice
 *	?2002 - 2003, Pixtel Communications, Inc., 1489 43rd Ave. W.,
 *	Vancouver, B.C. V6M 4K8 Canada. All Rights Reserved.
 *  (It is illegal to remove this copyright notice from this software or any
 *  portion of it)
 */

/**************************************************************

	FILENAME	: Res_.c

  	PURPOSE		: Populate Resource for 

	REMARKS		: nil

	AUTHOR		: Yogesh

	DATE		: August-11-2003

**************************************************************/
#include "CustomCfg.h"


#include "MMI_features.h" //ritesh
#include "GlobalMenuItems.h"
#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"

#include "ProfilesDefs.h"
#include "UserProfilesResDef.h"

/**************************************************************

	FUNCTION NAME		: PopulateprofileMenu(void)

  	PURPOSE				: Populate Menu for Profile

	INPUT PARAMETERS	: nil

	OUTPUT PARAMETERS	: nil

	RETURNS				: void

	REMARKS				: 

**************************************************************/
void PopulateprofileMenu(void)
{
	/*Menu Items*/
		ADD_APPLICATION_MENUITEM((MAIN_MENU_PROFILES_MENUID,
#ifdef __MMI_BI_DEGREE_MAIN_MENU_STYLE__
		MAIN_MENU_SYSTEM_MENU_ID,
#else
#ifdef __MMI_OP01_MENU_9MATRIX__
/* under construction !*/
#else
		IDLE_SCREEN_MENU_ID,
#endif
#endif
#ifdef __MMI_BT_PROFILE__
		6,
#else
		5,
#endif
		MAIN_MENU_PROFILES_GENERAL,
		MAIN_MENU_PROFILES_MEETING,
		MAIN_MENU_PROFILES_OUTDOOR,
		MAIN_MENU_PROFILES_INDOOR,
		MAIN_MENU_PROFILES_HEADSET,
#ifdef __MMI_BT_PROFILE__
		MAIN_MENU_PROFILES_BT,
#endif
		0,MOVEABLEACROSSPARENT | SHORTCUTABLE,1,MAIN_MENU_PROFILES_TEXT
		,MAIN_MENU_PROFILES_ICON));
	

	ADD_APPLICATION_MENUITEM((MAIN_MENU_PROFILES_GENERAL,MAIN_MENU_PROFILES_MENUID,0,SHOW,MOVEABLEWITHINPARENT,1,
		STR_PROFILES_GENERAL,IMG_PROFILES_GENERAL));

	ADD_APPLICATION_MENUITEM((MAIN_MENU_PROFILES_MEETING,MAIN_MENU_PROFILES_MENUID,0,SHOW,MOVEABLEWITHINPARENT,1,
		STR_PROFILES_MEETING,IMG_PROFILES_MEETING));

	ADD_APPLICATION_MENUITEM((MAIN_MENU_PROFILES_OUTDOOR,MAIN_MENU_PROFILES_MENUID,0,SHOW,MOVEABLEWITHINPARENT,1,
		STR_PROFILES_OUTDOOR,IMG_PROFILES_OUTDOOR));

	ADD_APPLICATION_MENUITEM((MAIN_MENU_PROFILES_INDOOR,MAIN_MENU_PROFILES_MENUID,0,SHOW,MOVEABLEWITHINPARENT,1,
		STR_PROFILES_INDOOR,IMG_PROFILES_INDOOR));

	ADD_APPLICATION_MENUITEM((MAIN_MENU_PROFILES_HEADSET,MAIN_MENU_PROFILES_MENUID,0,SHOW,MOVEABLEWITHINPARENT,1,
		STR_PROFILES_HEADSET,IMG_PROFILES_HEADSET));
#ifdef __MMI_BT_PROFILE__
	ADD_APPLICATION_MENUITEM((MAIN_MENU_PROFILES_BT,MAIN_MENU_PROFILES_MENUID,0,SHOW,MOVEABLEWITHINPARENT,1,
		STR_PROFILES_BT,IMG_PROFILES_BT));
#endif
/* Robin 0909 */
/* Shrink active/customize menu items */
#ifndef __MMI_PROF_MENU_ACTIVE_SHRINK__
//MTK Leo end
	ADD_APPLICATION_MENUITEM((MENU_PROFILES_OPTIONS,0,2,
		MENU_PROFILES_ACTIVATE,
		MENU_PROFILES_CUSTOMIZE,
		SHOW,NONMOVEABLE, DISP_LIST,STR_PROFILE_OPTION_CAPTION,0));

	ADD_APPLICATION_MENUITEM((MENU_PROFILES_OPTIONS_CUSTOMIZE,0,1,
		MENU_PROFILES_CUSTOMIZE,
		SHOW,NONMOVEABLE, DISP_LIST,STR_PROFILE_OPTION_CAPTION,0));
	
#endif /* __MMI_PROF_MENU_ACTIVE_SHRINK__ */ 

	ADD_APPLICATION_MENUITEM((MENU_PROFILES_ACTIVATE,MENU_PROFILES_OPTIONS,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_PROFILES_OPTION_ACTIVATE,0));


typedef enum {
#ifdef __MMI_PROF_MENU_ACTIVE_SHRINK__
    PROF_ITEM_ACTIVATE,
#endif    
	PROF_ITEM_TONE_SETUP,
	PROF_ITEM_VOLUME_LEVEL,
	PROF_ITEM_MT_CALL_ALERT_TYPE,

#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
	PROF_ITEM_INTELLIGENT_CALL_ALERT,
#endif

	PROF_ITEM_RING_TYPE,

#ifdef __MMI_CONNECT_NOTICE__
	PROF_ITEM_CONNECT_NOTICE,
#endif

	PROF_ITEM_EXTRA_TONE,
	PROF_ITEM_ANSEWRING_MODE,

#if !defined(HARDWARE_LED_NOT_SUPPORT)
	PROF_ITEM_LIGHT,
#endif
	PROF_ITEM_MAX_NUM
 } PROFILE_ITEM_ENUM;

#define PROF_ITEM_MAX_NUM_CHINESE PROF_ITEM_MAX_NUM

/* Customize Menu Tree*/
/* Normal Profile menu style, Engilish mode */
	ADD_APPLICATION_MENUITEM((MENU_PROFILES_CUSTOMIZE, 0,PROF_ITEM_MAX_NUM,
#ifdef __MMI_PROF_MENU_ACTIVE_SHRINK__
		MENU_PROFILES_ACTIVATE,
#endif
		MENU_TONE_SETUP,
		MENU_VOLUME_LEVEL,
		MENU_MT_CALL_ALERT_TYPE,
#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
		MENU_INTELLIGENT_CALL_ALERT,
#endif
		MENU_RING_TYPE,

#ifdef __MMI_CONNECT_NOTICE__
		MENU_CONNECT_NOTICE,
#endif
		MENU_EXTRA_TONE,
		MENU_ANSEWRING_MODE,

#if !defined(HARDWARE_LED_NOT_SUPPORT)
		MENU_LIGHT_STATUS,
#endif

		SHOW,NONMOVEABLE, DISP_LIST,STR_PROFILES_OPTION_CUSTOMIZE,0));

/* Normal Profile menu style, Chinese mode */
	ADD_APPLICATION_MENUITEM((MENU_PROFILES_CUSTOMIZE_CHINESE, 0,PROF_ITEM_MAX_NUM_CHINESE,
#ifdef __MMI_PROF_MENU_ACTIVE_SHRINK__
		MENU_PROFILES_ACTIVATE,
#endif
		MENU_TONE_SETUP,
		MENU_VOLUME_LEVEL,
		MENU_MT_CALL_ALERT_TYPE,
#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
		MENU_INTELLIGENT_CALL_ALERT,
#endif
		MENU_RING_TYPE,

#ifdef __MMI_CONNECT_NOTICE__
		MENU_CONNECT_NOTICE,
#endif
		MENU_EXTRA_TONE,
		MENU_ANSEWRING_MODE,

#if !defined(HARDWARE_LED_NOT_SUPPORT)
		MENU_LIGHT_STATUS,
#endif
		SHOW,NONMOVEABLE, DISP_LIST,STR_PROFILES_OPTION_CUSTOMIZE,0));


#ifdef __MMI_PROF_MENU_ACTIVE_SHRINK__

/* Normal Profile menu style, english mode */
	ADD_APPLICATION_MENUITEM((MENU_PROFILES_CUSTOMIZE_DEVICE,0,PROF_ITEM_MAX_NUM,
		MENU_TONE_SETUP,
		MENU_VOLUME_LEVEL,
		MENU_MT_CALL_ALERT_TYPE,
#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
		MENU_INTELLIGENT_CALL_ALERT,
#endif
		MENU_RING_TYPE,

#ifdef __MMI_CONNECT_NOTICE__
		MENU_CONNECT_NOTICE,
#endif
		MENU_EXTRA_TONE,
		MENU_ANSEWRING_MODE,

#if !defined(HARDWARE_LED_NOT_SUPPORT)
		MENU_LIGHT_STATUS,
#endif

		SHOW,NONMOVEABLE, DISP_LIST,STR_PROFILES_OPTION_CUSTOMIZE,0));

/* Shrink Profile menu style, chinese menu (No font size selection) */
	ADD_APPLICATION_MENUITEM((MENU_PROFILES_CUSTOMIZE_CHINESE_DEVICE,0,PROF_ITEM_MAX_NUM_CHINESE,
		MENU_TONE_SETUP,
		MENU_VOLUME_LEVEL,
		MENU_MT_CALL_ALERT_TYPE,
#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
		MENU_INTELLIGENT_CALL_ALERT,
#endif
		MENU_RING_TYPE,

#ifdef __MMI_CONNECT_NOTICE__
		MENU_CONNECT_NOTICE,
#endif
		MENU_EXTRA_TONE,
		MENU_ANSEWRING_MODE,

#if !defined(HARDWARE_LED_NOT_SUPPORT)
		MENU_LIGHT_STATUS,
 #endif
		SHOW,NONMOVEABLE, DISP_LIST,STR_PROFILES_OPTION_CUSTOMIZE,0));

#endif  /* __MMI_PROF_MENU_ACTIVE_SHRINK__ */
/* Customize Menu Tree*/

/* Tone Setup Menu Tree*/
	ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP,MENU_PROFILES_CUSTOMIZE,
#ifdef __MMI_CLAMSHELL__
        2+
#endif
#ifndef __MMI_ALM_CUSTOMIZE_TONE__
	1+
#endif
#ifdef __MMI_VIDEO_CALL_TONE__
        1+
#endif
#ifdef __MMI_DUAL_PROFILE_SUPPORT__
        2+
#endif
        5,
        MENU_TONE_SETUP_RING_TONE,
#ifdef __MMI_DUAL_PROFILE_SUPPORT__
        MENU_TONE_SETUP_CARD2_RING_TONE,
#endif
#ifdef __MMI_VIDEO_CALL_TONE__
        MENU_TONE_SETUP_VIDEO_CALL_RING_TONE,
#endif		
#ifndef __MMI_ALM_CUSTOMIZE_TONE__
        MENU_TONE_SETUP_ALARM_TONE,
#endif
        MENU_TONE_SETUP_POWERON_TONE,
        MENU_TONE_SETUP_POWEROFF_TONE,
#ifdef __MMI_CLAMSHELL__		
        MENU_TONE_SETUP_COVEROPEN_TONE,
        MENU_TONE_SETUP_COVERCLOSE_TONE,
#endif		
        MENU_TONE_SETUP_MESSAGE_TONE,
#ifdef __MMI_DUAL_PROFILE_SUPPORT__
        MENU_TONE_SETUP_CARD2_MESSAGE_TONE,
#endif
        MENU_TONE_SETUP_KEYPAD_TONE,
        SHOW,MOVEABLEWITHINPARENT | SHORTCUTABLE, DISP_LIST,STR_TONE_SETUP,0));


    ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP_RING_TONE,MENU_TONE_SETUP,0,
        SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_TONE_SETUP_RING_TONE_DEF,0));

#ifdef __MMI_DUAL_PROFILE_SUPPORT__
    ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP_CARD2_RING_TONE,MENU_TONE_SETUP,0,
        SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_TONE_SETUP_SIM2_RING_TONE_DEF,0));
#endif

#ifdef __MMI_VIDEO_CALL_TONE__
	ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP_VIDEO_CALL_RING_TONE,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_TONE_SETUP_VIDEO_RING_TONE,0));
#endif
    
#ifndef __MMI_ALM_CUSTOMIZE_TONE__
	ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP_ALARM_TONE,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_TONE_SETUP_ALARM_TONE,0));
#endif

	ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP_POWERON_TONE,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_TONE_SETUP_POWERON_TONE,0));

	ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP_POWEROFF_TONE,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_TONE_SETUP_POWEROFF_TONE,0));

#ifdef __MMI_CLAMSHELL__
	ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP_COVEROPEN_TONE,MENU_TONE_SETUP,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_TONE_SETUP_COVEROPEN_TONE,0));

	ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP_COVERCLOSE_TONE,MENU_TONE_SETUP,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_TONE_SETUP_COVERCLOSE_TONE,0));
#endif


    ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP_MESSAGE_TONE,MENU_TONE_SETUP,0,
        SHOW,NONMOVEABLE, DISP_LIST,STR_TONE_SETUP_MESSAGE_TONE_DEF,0));

#ifdef __MMI_DUAL_PROFILE_SUPPORT__
    ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP_CARD2_MESSAGE_TONE,MENU_TONE_SETUP,0,
        SHOW,NONMOVEABLE, DISP_LIST,STR_TONE_SETUP_SIM2_MESSAGE_TONE,0));
#endif

/* KeyPad Tone Menu Tree*/
	ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP_KEYPAD_TONE,MENU_TONE_SETUP,
#if defined( __MMI_CUST_KEYPAD_TONE__ )
		1+
#endif
#if defined( __MMI_HUMAN_VOICE_KEYPAD_TONE__ )
		1+
#endif
		3,
		MENU_KEYPAD_TONE_SILENT,
		MENU_KEYPAD_TONE_CLICK,
		MENU_KEYPAD_TONE_TONE,
#if defined( __MMI_CUST_KEYPAD_TONE__ )
		MENU_KEYPAD_TONE_CUST_1,
//		MENU_KEYPAD_TONE_CUST_2,
//		MENU_KEYPAD_TONE_CUST_3,
//		MENU_KEYPAD_TONE_CUST_4,
//		MENU_KEYPAD_TONE_CUST_5,
//		MENU_KEYPAD_TONE_CUST_6,
#endif

#if defined( __MMI_HUMAN_VOICE_KEYPAD_TONE__ )
		MENU_KEYPAD_TONE_HUMAN_VOICE_1,
//		MENU_KEYPAD_TONE_HUMAN_VOICE_2,
//		MENU_KEYPAD_TONE_HUMAN_VOICE_3,
//		MENU_KEYPAD_TONE_HUMAN_VOICE_4,
//		MENU_KEYPAD_TONE_HUMAN_VOICE_5,
//		MENU_KEYPAD_TONE_HUMAN_VOICE_6,
#endif
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_TONE_SETUP_KEYPAD_TONE,0));

	ADD_APPLICATION_MENUITEM((	MENU_KEYPAD_TONE_SILENT,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_SILENT,0));

	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_CLICK,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_CLICK,0));

	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_TONE,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_TONE,0));

#if defined( __MMI_CUST_KEYPAD_TONE__ )
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_CUST_1,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_CUST_1,0));
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_CUST_2,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_CUST_2,0));
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_CUST_3,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_CUST_3,0));
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_CUST_4,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_CUST_4,0));
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_CUST_5,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_CUST_5,0));
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_CUST_6,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_CUST_6,0));
#endif

#if defined( __MMI_HUMAN_VOICE_KEYPAD_TONE__ )
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_HUMAN_VOICE_1,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_HUMAN_VOICE_1,0));
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_HUMAN_VOICE_2,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_HUMAN_VOICE_2,0));
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_HUMAN_VOICE_3,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_HUMAN_VOICE_3,0));
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_HUMAN_VOICE_4,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_HUMAN_VOICE_4,0));
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_HUMAN_VOICE_5,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_HUMAN_VOICE_5,0));
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_TONE_HUMAN_VOICE_6,MENU_TONE_SETUP,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_TONE_HUMAN_VOICE_6,0));
#endif
/* KeyPad Tone Menu Tree*/
/* Tone Setup Menu Tree*/

/* Volume Level Menu Tree*/
	ADD_APPLICATION_MENUITEM((MENU_VOLUME_LEVEL,MENU_PROFILES_CUSTOMIZE,2,
		MENU_RING_VOLUME_LEVEL,
		MENU_KEYPAD_VOLUME_LEVEL,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_VOLUME_LEVEL,0));

	ADD_APPLICATION_MENUITEM((MENU_RING_VOLUME_LEVEL,MENU_VOLUME_LEVEL,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_RING_VOLUME_LEVEL,0));
	
	ADD_APPLICATION_MENUITEM((MENU_KEYPAD_VOLUME_LEVEL,MENU_VOLUME_LEVEL,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_KEYPAD_VOLUME_LEVEL,0));
/* Volume Level Menu Tree end*/

/* Alert Type Menu Tree*/	
	ADD_APPLICATION_MENUITEM((MENU_MT_CALL_ALERT_TYPE,MENU_PROFILES_CUSTOMIZE,
#if !defined(HARDWARE_LED_NOT_SUPPORT)
		5,
#else
        #ifndef __VIBRATOR_TONE_SUPPORT__  //su-2008/12/04
		4,
	#else
		3,
	#endif
#endif
		MENU_RING,
		MENU_VIBRATION_ONLY,
#ifndef __VIBRATOR_TONE_SUPPORT__
		MENU_VIBRATION_AND_RING,
#endif
		MENU_VIBRATION_THEN_RING,
#if !defined(HARDWARE_LED_NOT_SUPPORT)
		MENU_SILENT,
#endif
		SHOW,MOVEABLEWITHINPARENT,DISP_LIST,STR_MT_CALL_ALERT_TYPE,0));	

#if !defined(HARDWARE_LED_NOT_SUPPORT)
        ADD_APPLICATION_MENUITEM((MENU_SILENT,MENU_MT_CALL_ALERT_TYPE,0,
                SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_SILENT,0));
#endif

        ADD_APPLICATION_MENUITEM((MENU_VIBRATION_ONLY,MENU_MT_CALL_ALERT_TYPE,0,
                SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_VIBRATION_ONLY,0));

        ADD_APPLICATION_MENUITEM((MENU_VIBRATION_AND_RING,MENU_MT_CALL_ALERT_TYPE,0,
                SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_VIBRATION_AND_RING,0));

        ADD_APPLICATION_MENUITEM((MENU_VIBRATION_THEN_RING,MENU_MT_CALL_ALERT_TYPE,0,
                SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_VIBRATION_THEN_RING,0));

        ADD_APPLICATION_MENUITEM((MENU_RING,MENU_MT_CALL_ALERT_TYPE,0,
                SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_RING,0));
/* Alert Type Menu Tree*/


/* Intelligent Call Alert Menu Tree*/
#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
	ADD_APPLICATION_MENUITEM((MENU_INTELLIGENT_CALL_ALERT,MENU_PROFILES_CUSTOMIZE,2,
		MENU_INTELLIGENT_CALL_ALERT_OFF,
		MENU_INTELLIGENT_CALL_ALERT_ON,
		SHOW,MOVEABLEWITHINPARENT | SHORTCUTABLE,DISP_LIST,STR_PROFILES_INTELLIGENT_CALL_ALERT,0));	
	ADD_APPLICATION_MENUITEM((MENU_INTELLIGENT_CALL_ALERT_ON,MENU_INTELLIGENT_CALL_ALERT,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_ON,0));
	ADD_APPLICATION_MENUITEM((MENU_INTELLIGENT_CALL_ALERT_OFF,MENU_INTELLIGENT_CALL_ALERT,0,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_GLOBAL_OFF,0));
#endif
/* Intelligent Call Alert Menu Tree*/

/* Ring Type Menu Tree*/
	ADD_APPLICATION_MENUITEM((MENU_RING_TYPE,MENU_PROFILES_CUSTOMIZE,3,
		MENU_RING_TYPE_SINGLE,
		MENU_RING_TYPE_REPEAT,
		MENU_RING_TYPE_ASCENDING,
		SHOW,MOVEABLEWITHINPARENT | SHORTCUTABLE, DISP_LIST,STR_RING_TYPE,0));

        ADD_APPLICATION_MENUITEM((MENU_RING_TYPE_SINGLE,MENU_RING_TYPE,0,
                SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_RING_TYPE_SINGLE,0));

        ADD_APPLICATION_MENUITEM((MENU_RING_TYPE_REPEAT,MENU_RING_TYPE,0,
                SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_RING_TYPE_REPEAT,0));

        ADD_APPLICATION_MENUITEM((MENU_RING_TYPE_ASCENDING,MENU_RING_TYPE,0,
                SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_RING_TYPE_ASCENDNG,0));
/* Ring Type Menu Tree*/

/* Connect Notice Menu Tree*/
#ifdef __MMI_CONNECT_NOTICE__
	ADD_APPLICATION_MENUITEM((MENU_CONNECT_NOTICE,MENU_PROFILES_CUSTOMIZE,4,
		MENU_NOTICE_NONE,
		MENU_NOTICE_TONE_ONLY,
		MENU_NOTICE_VIB_ONLY,
		MENU_NOTICE_TONE_AND_VIB,
		SHOW,SHORTCUTABLE,DISP_LIST,STR_CONNECT_NOTICE,0));	
	ADD_APPLICATION_MENUITEM((MENU_NOTICE_NONE ,MENU_CONNECT_NOTICE,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_NOTICE_NONE,0));
	ADD_APPLICATION_MENUITEM((MENU_NOTICE_TONE_ONLY ,MENU_CONNECT_NOTICE,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_NOTICE_TONE_ONLY,0));
	ADD_APPLICATION_MENUITEM((MENU_NOTICE_VIB_ONLY ,MENU_CONNECT_NOTICE,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_NOTICE_VIB_ONLY,0));
	ADD_APPLICATION_MENUITEM((MENU_NOTICE_TONE_AND_VIB ,MENU_CONNECT_NOTICE,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_NOTICE_TONE_AND_VIB,0));

#endif
/* Connect Notice Menu Tree*/

/* Extra Tone Menu Tree*/
#ifdef __MMI_CONNECT_NOTICE__
	ADD_APPLICATION_MENUITEM((MENU_EXTRA_TONE,MENU_PROFILES_CUSTOMIZE,3,
		MENU_TONE_SETUP_WARNING_TONE,
		MENU_EXTRA_TONE_ERROR,
		MENU_EXTRA_TONE_CAMPON,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_EXTRA_TONE,0));
#else
	ADD_APPLICATION_MENUITEM((MENU_EXTRA_TONE,MENU_PROFILES_CUSTOMIZE,4,
		MENU_TONE_SETUP_WARNING_TONE,
		MENU_EXTRA_TONE_ERROR,
		MENU_EXTRA_TONE_CAMPON,
		MENU_EXTRA_TONE_CONNECT,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_EXTRA_TONE,0));
#endif

	ADD_APPLICATION_MENUITEM((MENU_TONE_SETUP_WARNING_TONE,MENU_EXTRA_TONE,0,
				SHOW,NONMOVEABLE, DISP_LIST,STR_TONE_SETUP_WARNING_TONE,0));

	ADD_APPLICATION_MENUITEM((MENU_EXTRA_TONE_ERROR,MENU_EXTRA_TONE,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_EXTRA_TONE_ERROR,0));

	ADD_APPLICATION_MENUITEM((MENU_EXTRA_TONE_CONNECT,MENU_EXTRA_TONE,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_EXTRA_TONE_CONNECT,0));

	ADD_APPLICATION_MENUITEM((MENU_EXTRA_TONE_CAMPON,MENU_EXTRA_TONE,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_EXTRA_TONE_CAMPON,0));
/* Extra Tone Menu Tree*/

/* Answering Mode Menu Tree*/
#ifdef __MMI_CLAMSHELL__
	ADD_APPLICATION_MENUITEM((MENU_ANSEWRING_MODE,MENU_PROFILES_CUSTOMIZE,2,
		MENU_NORMAL_ANSEWRING_MODE,
		MENU_ANYKEY_ANSEWRING_MODE,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_ANSEWRING_MODE,0));

	ADD_APPLICATION_MENUITEM((MENU_ANSEWRING_MODE_HEADSET,MENU_PROFILES_CUSTOMIZE,3,
		MENU_NORMAL_ANSEWRING_MODE,
		MENU_ANYKEY_ANSEWRING_MODE,
		MENU_AUTO_ANSEWRING_MODE,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_ANSEWRING_MODE,0));

#else
	ADD_APPLICATION_MENUITEM((MENU_ANSEWRING_MODE,MENU_PROFILES_CUSTOMIZE,1,
		MENU_ANYKEY_ANSEWRING_MODE,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_ANSEWRING_MODE,0));

	ADD_APPLICATION_MENUITEM((MENU_ANSEWRING_MODE_HEADSET,MENU_PROFILES_CUSTOMIZE,2,
		MENU_ANYKEY_ANSEWRING_MODE,
		MENU_AUTO_ANSEWRING_MODE,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_ANSEWRING_MODE,0));
#endif

	ADD_APPLICATION_MENUITEM((MENU_NORMAL_ANSEWRING_MODE,MENU_ANSEWRING_MODE,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_NORMAL_ANSEWRING_MODE,0));
	ADD_APPLICATION_MENUITEM((MENU_ANYKEY_ANSEWRING_MODE,MENU_ANSEWRING_MODE,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_ANYKEY_ANSEWRING_MODE,0));
	ADD_APPLICATION_MENUITEM((MENU_AUTO_ANSEWRING_MODE,MENU_ANSEWRING_MODE,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_AUTO_ANSEWRING_MODE,0));
/* Answering Mode Menu Tree*/

/* Light Status Menu Tree*/
#if !defined(HARDWARE_LED_NOT_SUPPORT)
	ADD_APPLICATION_MENUITEM((MENU_LIGHT_STATUS,MENU_PROFILES_CUSTOMIZE,7,
		MENU_LIGHT_STATUS_NONE,
		MENU_LIGHT_STATUS_COLOR1,
		MENU_LIGHT_STATUS_COLOR2,
		MENU_LIGHT_STATUS_COLOR3,
		MENU_LIGHT_STATUS_COLOR4,
		MENU_LIGHT_STATUS_COLOR5,
		MENU_LIGHT_STATUS_COLOR6,
		SHOW,MOVEABLEWITHINPARENT, DISP_LIST,STR_LIGHT_STATUS,0));

	ADD_APPLICATION_MENUITEM((MENU_LIGHT_STATUS_NONE,MENU_LIGHT_STATUS,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_LIGHT_STATUS_NONE,0));
	
	ADD_APPLICATION_MENUITEM((MENU_LIGHT_STATUS_COLOR1,MENU_LIGHT_STATUS,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_LIGHT_STATUS_COLOR1,0));

	ADD_APPLICATION_MENUITEM((MENU_LIGHT_STATUS_COLOR2,MENU_LIGHT_STATUS,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_LIGHT_STATUS_COLOR2,0));

	ADD_APPLICATION_MENUITEM((MENU_LIGHT_STATUS_COLOR3,MENU_LIGHT_STATUS,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_LIGHT_STATUS_COLOR3,0));

	ADD_APPLICATION_MENUITEM((MENU_LIGHT_STATUS_COLOR4,MENU_LIGHT_STATUS,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_LIGHT_STATUS_COLOR4,0));

	ADD_APPLICATION_MENUITEM((MENU_LIGHT_STATUS_COLOR5,MENU_LIGHT_STATUS,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_LIGHT_STATUS_COLOR5,0));

	ADD_APPLICATION_MENUITEM((MENU_LIGHT_STATUS_COLOR6,MENU_LIGHT_STATUS,0,
		SHOW,NONMOVEABLE, DISP_LIST,STR_LIGHT_STATUS_COLOR6,0));
#endif /* HARDWARE_LED_NOT_SUPPORT */
/* Light Status Menu Tree*/

    /*String Items*/
    ADD_APPLICATION_STRING2(STR_PROFILES_SAVE_ASK,"Save?","String to ask user save or not.");

	ADD_APPLICATION_STRING2(STR_DEFAULT_VOLUME_CAPTION,"Volume","String Associated with Default Volume Screen.");

	ADD_APPLICATION_STRING2(STR_KEY_TONE_VOLUME_CAPTION,"KeyTone Volume","String Associated with KeyTone Volume Screen.");
	ADD_APPLICATION_STRING2(STR_PROFILES_CANNOT_CHANGE_SILENT_MODE_SETTING,"Can't Change Silent Mode Setting","Can't Change Silent Mode Setting");	
	
	ADD_APPLICATION_STRING2(STR_NO_COLOR_MESSAGE,"No Color is selected","No Color is selected");
	ADD_APPLICATION_STRING2(STR_COLOR1_MESSAGE,"Color1 is selected","Color1 is selected");
	ADD_APPLICATION_STRING2(STR_COLOR2_MESSAGE,"Color2 is selected","Color2 is selected");
	ADD_APPLICATION_STRING2(STR_COLOR3_MESSAGE,"Color3 is selected","Color3 is selected");
	ADD_APPLICATION_STRING2(STR_COLOR3_MESSAGE,"Color4 is selected","Color4 is selected");
	ADD_APPLICATION_STRING2(STR_COLOR3_MESSAGE,"Color5 is selected","Color5 is selected");
	ADD_APPLICATION_STRING2(STR_COLOR3_MESSAGE,"Color6 is selected","Color6 is selected");
	
		
	ADD_APPLICATION_STRING2(STR_SILENT,"Light Only","Silent");	
	
	
	ADD_APPLICATION_STRING2(STR_EXTRA_TONE_CONNECT,"Connect","Connect");	

	ADD_APPLICATION_STRING2(STR_EXTRA_TONE_CAMPON,"Camp on","Camp on - Option ");	
	
	
	ADD_APPLICATION_STRING2(STR_EXTRA_TONE_CAPTION,"Extra Tone","Extra Tone screen caption");	

	ADD_APPLICATION_STRING2(STR_EXTRA_TONE_ERROR,"Error","Error");	
		
	ADD_APPLICATION_STRING2(STR_PROFILES_OPTION_ACTIVATE,"Activate","Activate - Option");	
	ADD_APPLICATION_STRING2(STR_PROFILES_OPTION_CUSTOMIZE,"Customize","Customize - Option");	
	ADD_APPLICATION_STRING2(STR_PROFILE_OPTION_CAPTION,"Profile Options","Profile Options screen caption");	

	/*In case of togling silent profile Begin*/
	ADD_APPLICATION_STRING2(STR_GENERAL_RESTORED_MESSAGE,"General Activated","Profile changed to General");	
	ADD_APPLICATION_STRING2(STR_MEETING_RESTORED_MESSAGE,"Meeting Activated" ,"Profile changed to Meeting");	
	ADD_APPLICATION_STRING2(STR_OUTDOOR_RESTORED_MESSAGE,"Outdoor Activated" ,"Profile changed to Outdoor");	
	ADD_APPLICATION_STRING2(STR_INDOOR_RESTORED_MESSAGE,"Indoor Activated" ,"Profile changed to Indoor");	

	ADD_APPLICATION_STRING2(STR_SILENT_ACTIVATE_MESSAGE,"Silent Activated","Profile changed to Silent");
	/*In case of togling silent profile End*/
	
#ifdef __MMI_CONNECT_NOTICE__
	ADD_APPLICATION_STRING2(STR_CONNECT_NOTICE,"Connect Notice" ,"Connect Notice");	
	ADD_APPLICATION_STRING2(STR_NOTICE_NONE,"None" ,"Connect Notice -- None ");	
	ADD_APPLICATION_STRING2(STR_NOTICE_TONE_ONLY,"Tone Only" ,"Connect Notice -- Tone Only");	
	ADD_APPLICATION_STRING2(STR_NOTICE_VIB_ONLY,"Vib. Only" ,"Connect Notice -- Vib Only ");	
	ADD_APPLICATION_STRING2(STR_NOTICE_TONE_AND_VIB,"Tone & Vib." ,"Connect Notice -- Tone & Vib");	
#endif
	
	ADD_APPLICATION_STRING2(STR_GENERAL_ACTIVATE_MESSAGE,"Activated","Profile Activated");	

	ADD_APPLICATION_STRING2(STR_PROFILE_CUSTOMIZE_CAPTION,"Customize" ,"Customize Screen Caption");	

	ADD_APPLICATION_STRING2(STR_VOLUME_LEVEL,"Volume","Volume Option");	
	
	ADD_APPLICATION_STRING2(STR_COMMON_VOLUME_LEVEL_RING_CAPTION,"Ring Tone","Ring Tone Volume Level screen Caption");	

	ADD_APPLICATION_STRING2(STR_COMMON_VOLUME_LEVEL_KEY_CAPTION,"Key Tone","Key Tone Volume Level screen Caption");	
	
	ADD_APPLICATION_STRING2(STR_MT_CALL_ALERT_TYPE,"Alert Type" ,"Alert Type - option");	
	ADD_APPLICATION_STRING2(STR_RING_TYPE,"Ring Type" ,"Ring Type - Option");	

	ADD_APPLICATION_STRING2(STR_RING_TYPE_CAPTION,"Ring Type" ,"Ring Type screen caption");	
	ADD_APPLICATION_STRING2(STR_RING_TYPE_SINGLE,"Single","Ring Type Single - option");	
	ADD_APPLICATION_STRING2(STR_RING_TYPE_REPEAT,"Repeat","Ring Type Repeat - option");	
	ADD_APPLICATION_STRING2(STR_RING_TYPE_ASCENDNG,"Ascending","Ring Type Ascending - option");	

	ADD_APPLICATION_STRING2(STR_VOLUME_LEVEL_CAPTION,"Volume","Volume Screen Caption");	
	ADD_APPLICATION_STRING2(STR_RING_VOLUME_LEVEL,"Ring Tone","Ring Tone - option");	
	ADD_APPLICATION_STRING2(STR_KEYPAD_VOLUME_LEVEL,"Key Tone","Key Tone - option");	

	ADD_APPLICATION_STRING2(STR_TONE_SETUP,"Tone Setup" ,"Tone Setup-option");	
	
	ADD_APPLICATION_STRING2(STR_ANSEWRING_MODE,"Answer Mode" ,"Answering Mode-option");	
	ADD_APPLICATION_STRING2(STR_FONT_SIZE,"Font Size" ,"Font Size-option");	
	ADD_APPLICATION_STRING2(STR_EXTRA_TONE,"Extra Tone" ,"Extra Tone-option");	

	ADD_APPLICATION_STRING2(STR_VIBRATION_ONLY,"Vibration Only" ,"'Vibration Only' option");	
	ADD_APPLICATION_STRING2(STR_VIBRATION_AND_RING,"Vibra and Ring" ,"'Vibration & Ring' option");	
	ADD_APPLICATION_STRING2(STR_VIBRATION_THEN_RING,"Vibra Then Ring" ,"'Vibration Then Ring' option");	
	ADD_APPLICATION_STRING2(STR_RING,"Ring" ,"'Ring' option");	

	ADD_APPLICATION_STRING2(STR_PROFILE_CAPTION,"User Profiles" ,"User Profiles Screen caption");	
	ADD_APPLICATION_STRING2(STR_CALL_ALERT_CAPTION,"Alert Type" ,"Alert Type screen caption");	

	ADD_APPLICATION_STRING2(STR_ANSEWRING_MODE_CAPTION,"Answer Mode" ,"Answering Mode screen Caption");	
	
#ifdef __MMI_CLAMSHELL__
	ADD_APPLICATION_STRING2(STR_NORMAL_ANSEWRING_MODE,"Cover Answer" ,"Cover Answer - option");	
#endif

	ADD_APPLICATION_STRING2(STR_ANYKEY_ANSEWRING_MODE,"Any Key" ,"Any Key - option");	
	ADD_APPLICATION_STRING2(STR_AUTO_ANSEWRING_MODE,"Auto" ,"Auto - option");	

#if !defined(HARDWARE_LED_NOT_SUPPORT)
	ADD_APPLICATION_STRING2(STR_LIGHT_STATUS,"Status LED" ,"Status LED - option");	
	ADD_APPLICATION_STRING2(STR_LIGHT_STATUS_NONE,"None" ,"None");	
	ADD_APPLICATION_STRING2(STR_LIGHT_STATUS_CAPTION,"Status LED " ,"Status LED Pattern Caption String");
	ADD_APPLICATION_STRING2(STR_LIGHT_STATUS_COLOR1,"Color pattern 1" ,"Color pattern 1");
	ADD_APPLICATION_STRING2(STR_LIGHT_STATUS_COLOR2,"Color pattern 2" ,"Color pattern 2");	
	ADD_APPLICATION_STRING2(STR_LIGHT_STATUS_COLOR3,"Color pattern 3" ,"Color pattern 3");
	ADD_APPLICATION_STRING2(STR_LIGHT_STATUS_COLOR4,"Color pattern 4" ,"Color pattern 4");
	ADD_APPLICATION_STRING2(STR_LIGHT_STATUS_COLOR5,"Color pattern 5" ,"Color pattern 5");
	ADD_APPLICATION_STRING2(STR_LIGHT_STATUS_COLOR6,"Color pattern 6" ,"Color pattern 6");
#endif

#ifndef __MMI_ALM_CUSTOMIZE_TONE__
	ADD_APPLICATION_STRING2(STR_TONE_SETUP_ALARM_TONE,"Alarm" ,"Alarm Tone");	
#endif
	ADD_APPLICATION_STRING2(STR_ALARM_TONE_CAPTION,"Alarm" ,"Alarm Tone - option");	
	
#ifdef __MMI_VIDEO_CALL_TONE__
#ifdef __MMI_DUAL_PROFILE_SUPPORT__
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_SIM1_VOICE_RING_TONE,"SIM1 Voice Call" ,"Voice Incoming Call - option");
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_SIM2_VOICE_RING_TONE,"SIM2 Voice Call" ,"Voice Incoming Call - option");
#else
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_VOICE_RING_TONE,"Voice Call" ,"Voice Incoming Call - option");
#endif
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_VIDEO_RING_TONE,"Video Call" ,"Video Incoming Call - option");

#else
#ifdef __MMI_DUAL_PROFILE_SUPPORT__
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_SIM1_RING_TONE,"SIM1 Incoming Call" ,"Video Incoming Call - option");
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_SIM2_RING_TONE,"SIM2 Incoming Call" ,"Voice Incoming Call - option");
#else
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_RING_TONE,"Incoming Call" ,"Incoming Call - option");
#endif

#endif

    ADD_APPLICATION_STRING2(STR_TONE_FILE_NOT_EXIST,"<File Not Exist>" ,"Profile tone File not exist");	
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_RING_TONE_EXT_SET,"Select" ,"Set external melody - option");
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_VDIEO_RING_TONE_EXT_SET,"Set As Video Call Tone" ,"Set external melody - option");
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_RING_TONE_PHB_EXT_SET,"Forward to phonebook" ,"Set external melody - option");	
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_RING_TONE_EXT_DEL,"Delete" ,"Del external melody - option");	
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_RING_TONE_EXT_ADD,"Add" ,"Add external melody - option");
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_ALARM_TONE_EXT_SET,"Select" ,"Set external melody - option");	
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_ALARM_TONE_EXT_DEL,"Delete" ,"Del external melody - option");	
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_ALARM_TONE_EXT_ADD,"Add" ,"Add external melody - option");

    ADD_APPLICATION_STRING2(STR_TONE_SETUP_POWERON_TONE,"Power On" ,"Power On Tone - option");
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_POWEROFF_TONE,"Power Off" ,"PowerOff Tone - option");	

#ifdef __MMI_CLAMSHELL__
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_COVEROPEN_TONE,"Cover Open" ,"CoverOpen Tone - option");
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_COVERCLOSE_TONE,"Cover Close" ,"CoverClose Tone - option");	
#endif

#ifdef __MMI_DUAL_PROFILE_SUPPORT__
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_SIM1_MESSAGE_TONE,"SIM1 Message Tone" ,"Message Tone - option");
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_SIM2_MESSAGE_TONE,"SIM2 Message Tone" ,"Message Tone - option");
#else
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_MESSAGE_TONE,"Message Tone" ,"Message Tone - option");
#endif

    ADD_APPLICATION_STRING2(STR_TONE_SETUP_KEYPAD_TONE,"Keypad Tone" ,"Keypad Tone - option");	
    ADD_APPLICATION_STRING2(STR_TONE_SETUP_WARNING_TONE,"Warning","Warning Tone");

#ifdef __MMI_VIDEO_CALL_TONE__

#ifdef __MMI_DUAL_PROFILE_SUPPORT__
    ADD_APPLICATION_STRING2(STR_PROFILES_SIM1_VOICE_RING_TONE_SETUP_CAPTION,"SIM1 Voice Call","Voice Incoming Call Tone screen caption");
    ADD_APPLICATION_STRING2(STR_PROFILES_SIM2_VOICE_RING_TONE_SETUP_CAPTION,"SIM2 Voice Call","Voice Incoming Call Tone screen caption");
#else
    ADD_APPLICATION_STRING2(STR_PROFILES_VOICE_RING_TONE_SETUP_CAPTION,"Voice Call","Voice Incoming Call Tone screen caption");
#endif
    ADD_APPLICATION_STRING2(STR_PROFILES_VIDEO_RING_TONE_SETUP_CAPTION,"Video Call","Video Incoming Call Tone screen caption");
#else

#ifdef __MMI_DUAL_PROFILE_SUPPORT__
    ADD_APPLICATION_STRING2(STR_PROFILES_SIM1_RING_TONE_SETUP_CAPTION,"SIM1 Incoming Call","Voice Incoming Call Tone screen caption");
    ADD_APPLICATION_STRING2(STR_PROFILES_SIM2_RING_TONE_SETUP_CAPTION,"SIM2 Incoming Call","Voice Incoming Call Tone screen caption");
#else
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_TONE_SETUP_CAPTION,"Incoming Call","Incoming Call Tone screen caption");   
#endif

#endif

    ADD_APPLICATION_STRING2(STR_PROFILES_TONE_SETUP_CAPTION,"Tone Setup","Tone Setup screen caption");

#ifdef __MMI_PROFILE_EXTMELODY_SUPPORT__    
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_TONE_SETUP_DRV_PHONE,"From Phone","Tone Setup screen caption");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_TONE_SETUP_DRV_CARD,"From Card","Tone Setup screen caption");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_TONE_SETUP_LISTFULL,"List Full","Tone Setup screen caption");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_TONE_SETUP_DUPLICATED,"Duplicated","Tone Setup screen caption");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_TONE_SETUP_NAMETOOLONG,"File path/name too long","Tone Setup screen string");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_TONE_SETUP_FILETOOLARGE,"File too large","Tone Setup screen string");
#endif


#ifdef __MMI_CLAMSHELL__
    ADD_APPLICATION_STRING2(STR_COVEROPEN_TONE_CAPTION,"Cover Open","Cover Open screen caption");
    ADD_APPLICATION_STRING2(STR_COVERCLOSE_TONE_CAPTION,"Cover Close","Cover Close screen caption");
#endif

#ifdef __MMI_DUAL_PROFILE_SUPPORT__
    ADD_APPLICATION_STRING2(STR_SIM1_MESSAGE_TONE_CAPTION,"SIM1 Message Tone","Message tone  screen caption");
    ADD_APPLICATION_STRING2(STR_SIM2_MESSAGE_TONE_CAPTION,"SIM2 Message Tone","Message tone  screen caption");
#else
    ADD_APPLICATION_STRING2(STR_MESSAGE_TONE_CAPTION,"Message Tone","Message tone  screen caption");
#endif

    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_SILENT,"Silent","Silent - option for keypad");
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_CLICK,"Click","Click - option for keypad");
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_TONE,"Tone","Tone - option for keypad");

#if defined( __MMI_HUMAN_VOICE_KEYPAD_TONE__ )
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_HUMAN_VOICE_1,"Human Voice Tone 1","Tone - option for keypad");
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_HUMAN_VOICE_2,"Human Voice Tone 2","Tone - option for keypad");
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_HUMAN_VOICE_3,"Human Voice Tone 3","Tone - option for keypad");
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_HUMAN_VOICE_4,"Human Voice Tone 4","Tone - option for keypad");
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_HUMAN_VOICE_5,"Human Voice Tone 5","Tone - option for keypad");
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_HUMAN_VOICE_6,"Human Voice Tone 6","Tone - option for keypad");
#endif

#if defined( __MMI_CUST_KEYPAD_TONE__ )
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_CUST_1,"Custom Tone 1","Tone - option for keypad");
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_CUST_2,"Custom Tone 2","Tone - option for keypad");
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_CUST_3,"Custom Tone 3","Tone - option for keypad");
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_CUST_4,"Custom Tone 4","Tone - option for keypad");
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_CUST_5,"Custom Tone 5","Tone - option for keypad");
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_CUST_6,"Custom Tone 6","Tone - option for keypad");
#endif

#if defined( __MMI_INTELLIGENT_CALL_ALERT__ )
    ADD_APPLICATION_STRING2(STR_PROFILES_INTELLIGENT_CALL_ALERT,"Intelligent Call Alert","Intelligent Call Alert");
#endif
	
    ADD_APPLICATION_STRING2(STR_KEYPAD_TONE_CAPTION,"Keypad Tone","Keypad screen caption");
    ADD_APPLICATION_STRING2(STR_POWERON_TONE_SETUP_CAPTION,"Power On","Power On screen caption");
    ADD_APPLICATION_STRING2(STR_POWEROFF_TONE_SETUP_CAPTION,"Power Off","Power Off screen caption");	
    ADD_APPLICATION_STRING2(STR_PROFILES_GENERAL,"General","General - Option");
    ADD_APPLICATION_STRING2(STR_PROFILES_MEETING,"Meeting","Meeting - Option");
    ADD_APPLICATION_STRING2(STR_PROFILES_OUTDOOR,"Outdoor","Outdoor - Option");
    ADD_APPLICATION_STRING2(STR_PROFILES_INDOOR,"Indoor","Indoor - Option");
    ADD_APPLICATION_STRING2(STR_PROFILES_HEADSET,"Headset","Headset - Option");
#ifdef __MMI_BT_PROFILE__
    ADD_APPLICATION_STRING2(STR_PROFILES_BT,"Bluetooth","Bluetooth - Option");
#endif
    ADD_APPLICATION_STRING2(STR_PROFILES_RING,"Ring","Ring string");

    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI,"MIDI ","Midi string");

    ADD_APPLICATION_STRING2(STR_PROFILES_SILENT,"Silent","Silent String");
    ADD_APPLICATION_STRING2(STR_PROFILES_TONE,"Tone","Tone String");
    	
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_1,"Ring 1","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_2,"Ring 2","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_3,"Ring 3","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_4,"Ring 4","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_5,"Ring 5","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_6,"Ring 6","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_7,"Ring 7","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_8,"Ring 8","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_9,"Ring 9","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_RING_10,"Ring 10","Ring string");

    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_1,"MIDI 1","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_2,"MIDI 2","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_3,"MIDI 3","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_4,"MIDI 4","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_5,"MIDI 5","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_6,"MIDI 6","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_7,"MIDI 7","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_8,"MIDI 8","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_9,"MIDI 9","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_10,"MIDI 10","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_11,"MIDI 11","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_12,"MIDI 12","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_13,"MIDI 13","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_14,"MIDI 14","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_15,"MIDI 15","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_16,"MIDI 16","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_17,"MIDI 17","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_18,"MIDI 18","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_19,"MIDI 19","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_20,"MIDI 20","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_21,"MIDI 21","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_22,"MIDI 22","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_23,"MIDI 23","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_24,"MIDI 24","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_25,"MIDI 25","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_26,"MIDI 26","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_27,"MIDI 27","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_28,"MIDI 28","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_29,"MIDI 29","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_30,"MIDI 30","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_31,"MIDI 31","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_32,"MIDI 32","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_33,"MIDI 33","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_34,"MIDI 34","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_35,"MIDI 35","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_36,"MIDI 36","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_37,"MIDI 37","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_38,"MIDI 38","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_39,"MIDI 39","Ring string");
    ADD_APPLICATION_STRING2(STR_PROFILES_MIDI_40,"MIDI 40","Ring string");
#ifdef __MMI_DOWNLOADABLE_THEMES_SUPPORT__	
    ADD_APPLICATION_STRING2(STR_PROFILES_CURR_THEME,"Theme tone","current downloaded theme ring tone string");
#endif
    ADD_APPLICATION_IMAGE2(IMG_PROFILES_GENERAL,CUST_IMG_PATH"\\\\MainLCD\\\\SubMenu\\\\Profile\\\\SB_POG.PBM","Image Associated with General Profiles");
    ADD_APPLICATION_IMAGE2(IMG_PROFILES_MEETING,CUST_IMG_PATH"\\\\MainLCD\\\\SubMenu\\\\Profile\\\\SB_PMEET.PBM","Image Associated with Meeting Profiles");
    ADD_APPLICATION_IMAGE2(IMG_PROFILES_OUTDOOR,CUST_IMG_PATH"\\\\MainLCD\\\\SubMenu\\\\Profile\\\\SB_POUT.PBM","Image Associated with OutDoor Profiles");
    ADD_APPLICATION_IMAGE2(IMG_PROFILES_INDOOR,CUST_IMG_PATH"\\\\MainLCD\\\\SubMenu\\\\Profile\\\\SB_PIN.PBM","Image Associated with InDoor Profiles");
    ADD_APPLICATION_IMAGE2(IMG_PROFILES_HEADSET,CUST_IMG_PATH"\\\\MainLCD\\\\SubMenu\\\\Profile\\\\SB_HDSET.PBM","Image Associated with InDoor Profiles");
#ifdef __MMI_BT_PROFILE__
    ADD_APPLICATION_IMAGE2(IMG_PROFILES_BT,CUST_IMG_PATH"\\\\MainLCD\\\\SubMenu\\\\Profile\\\\SB_BT.PBM","Image Associated with InDoor Profiles");
#endif
    ADD_APPLICATION_IMAGE2(IMG_PROFILES_TITLEE,CUST_IMG_PATH"\\\\MainLCD\\\\TitleBar\\\\TB_PR.PBM","Image Associated with Title of Profiles");
    ADD_APPLICATION_IMAGE2(IMG_PROFILES_NO_IMAGE,CUST_IMG_BASE_PATH"\\\\NoImage.bmp", "IMG_PROFILES_NO_IMAGE");
    ADD_APPLICATION_IMAGE2(IMG_PROFILES_ACTIVATED,CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\checkbox\\\\CK_V.BMP", "IMG_PROFILES_ACTIVATED");
}

#endif


