#include "MMI_features.h" 

#ifdef __MMI_CSB_BROWSER__

#include "CustomCfg.h"

#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif


#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"
#include "CatScreenBrowserResDef.h"


void populateCSBrowserMenu(void)
{
	/* CS Main Menu */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_TEXT, "Category Screen Browser", "Category Screen Browser Caption String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_VIEW_TEXT, "View", "Category Screen Browser View");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SEARCH_TEXT, "Search", "Category Screen Browser Search");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_TESTTOOL_TEXT, "TestTool", "Category Screen Browser TestTool");

	/* View Main Menu */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_START_VIEW_TEXT, "Start View", "Category Screen Browser Start View");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_START_VIEW_X_TEXT, "Start View X", "Category Screen Browser Start View X");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_VIEW_OPTIONS_TEXT, "Options", "Category Screen Browser Start View Options");

	/* Search Main Menu */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SEARCH_CONTROL_TEXT, "By Control", "Category Screen Browser Search by Control");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SEARCH_APP_TEXT, "By Application", "Category Screen Browser Search by App");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SEARCH_SCREENID_TEXT, "By Screen ID", "Category Screen Browser Search by Screen ID");

	/* Option Menu */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_OPTIONS_VIEW_MODE_TEXT, "View Mode", "View Mode String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_OPTIONS_MODE_SETTINGS_TEXT, "Mode Settings", "Mode Settings String");

	/* View Mode Menu */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_VIEW_MODE_AUTO_TEXT, "Auto", "Auto View Mode String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_VIEW_MODE_MANUAL_TEXT, "Manual", "Manual View Mode String");
	
	/* Mode Setting Menu */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_AUTO_MODE_TIME_TEXT, "Auto Mode Time", "Auto Mode Time String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MANUAL_MODE_TEXT, "Manual Mode", "Manual Mode String");

	/* Manual Mode Menu */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MANUAL_MODE_INTERACTIVE_TEXT, "Interactive", "Interactive String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MANUAL_MODE_NONINTERACTIVE_TEXT, "Non-Interactive", "Non Interactive String");

	/* Test Tool */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_RUN_TESTTOOL_TEXT, "Run Test Tool", "Run test tool String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SET_LOCATION_TEXT, "Set Location", "Set Location String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_VIEW_IMAGES, "View Images", "View Images String");


	/* Strings for Control Names */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_CALL_SCR_TEXT, "Call Screen", "Call Screen String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_COLOR_PICKER_TEXT, "Color Picker Screen", "Color Picker Screen String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_EDITOR_TEXT, "Editor", "Editor String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_EDITOR_LIST_MENU_TEXT, "Editor List Menu", "Editor List menu String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_EDITOR_POPUP_TEXT, "Editor Popup", "Editor Pop-up String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_IDLE_TEXT, "Idle Screen", "Idle Screen String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_IMAGE_VIEWER_TEXT, "Image Viewer", "Image Viewer String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_LIST_MENU_TEXT, "List Menu", "List Menu String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MATRIX_MENU_TEXT, "Matrix Menu", "Matrix Menu String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_POPUP_TEXT, "Pop-Up", "Pop-Up String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_PROGRESS_BAR_TEXT, "Progress Bar", "Progress Bar String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SLIDER_TEXT, "Slider Screen", "Slider Screen String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_RADIO_BUTTON_TEXT, "Radio Button", "Radio Button String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_CHECK_BOX_TEXT, "Check Box", "Check Box String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SUB_LCD_TEXT, "Sub LCD", "Sub LCD String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_PANEL_TEXT, "Panel", "Panel String");//052907 CSB

	/* String for Appplication names */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_CALLS_TEXT,		"Calls", "Calls String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_EDITOR_TEXT,	"Editor", "Call Screen String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_ENGG_MODE_TEXT,	"Engineering Mode","Engineering Mode String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_EXTRA_TEXT,		"Extra","Extra String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_FUN_AND_GAMES_TEXT,"Fun and Games","Fun and Games String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_FILE_MANAGER_TEXT,"File Manager","File Manager String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MESSAGES_TEXT,"Messages","Messages String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MISC_TEXT,"Misc","Misc String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MULTIMEDIA_TEXT,"Multimedia","Multimedia String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_ORGANIZER_TEXT,"Organizer","Organizer String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_PHONEBOOK_TEXT,"Phonebook","Phonebook String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_PROFILE_TEXT,"Profile","Profile String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SERVICES_TEXT,"Services","Services String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SHORTCUT_TEXT,"Shortcut","Shortcut String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SETTINGS_TEXT,"Settings","Settings String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_WAP_TEXT,"Wap","WAP String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_UNUSED_TEXT,"Unused","Unused String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_HID_TEXT,"HID","HID String");//052907 CSB

	/* Error String */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SCR_NOT_EXIST_TEXT,"Screen does not exist!","Error String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_TESTTOOL_PASS,"TestTool executed successfully!","Error String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_TESTTOOL_FAIL,"TestTool execution error!","Error String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_FILE_PATH_TOO_LONG,"File path too long!","Error String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_NO_SCR_FOUND_TEXT,"No Screen Found!","Error String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_JPEG_FAIL_TEXT,"JPEG Encoder Error!","Error String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MEMORY_FAIL_TEXT,"Memory Not Available!","Error String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_NO_MEMORY_CARD,"Memory Card Not Found!","Error String");

	/* Misc */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SET_TEXT,"Set","Set Folder String");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SHOW_CATEGORY_TEXT,"ShowCategory","category prefix");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_SCREEN_TEXT,"screen","category suffix");

	/* Dummy Strings */
	ADD_APPLICATION_STRING2 (STR_ID_CSB_PROCESSING_TEXT, "Processing", "Common String for Processing Screen");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_CATEGORY_TEXT, "Category", "Common String for Category Screens");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_DUMMY_TEXT, "Dummy", "Dummy String for Category Screens");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_LSK_TEXT, "LSK", "LSK for dummy Category Screens");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_RSK_TEXT, "RSK", "RSK for dummy Category Screens");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MENUITEM1_TEXT, "MenuItem1", "Dummy Menuitem String for Category Screens");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MENUITEM2_TEXT, "MenuItem2", "Dummy Menuitem String for Category Screens");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MENUITEM3_TEXT, "MenuItem3", "Dummy Menuitem String for Category Screens");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MENUITEM4_TEXT, "MenuItem4", "Dummy Menuitem String for Category Screens");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MENUITEM5_TEXT, "MenuItem5", "Dummy Menuitem String for Category Screens");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MENUITEM6_TEXT, "MenuItem6", "Dummy Menuitem String for Category Screens");
	ADD_APPLICATION_STRING2 (STR_ID_CSB_MENUITEM7_TEXT, "MenuItem7", "Dummy Menuitem String for Category Screens");

#if 0 /* remove for code size */
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
/* under construction !*/
#endif /* remove for code size */

	/* CSB Main Menu*/
	ADD_APPLICATION_MENUITEM((CSB_MENUID, ENGINEER_MODE_MENUID, 3,
                            CSB_VIEW_MENUID,
                            CSB_SEARCH_MENUID,
                            CSB_TESTOOL_MENUID,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_TEXT, 0));

	/* View Main Menu */
	ADD_APPLICATION_MENUITEM((CSB_VIEW_MENUID, CSB_MENUID, 3,
							CSB_START_VIEW_MENUID,
                            CSB_START_VIEW_X_MENUID,
                            CSB_VIEW_OPTIONS_MENUID,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_VIEW_TEXT, 0));
	/* Search Main Menu */
    ADD_APPLICATION_MENUITEM((CSB_SEARCH_MENUID, CSB_MENUID, 3,
							CSB_SEARCH_CONTROL_MENUID,
							CSB_SEARCH_APP_MENUID,
							CSB_SEARCH_SCREENID_MENUID,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_SEARCH_TEXT, 0));
	/* Test Tool Main Menu */
    ADD_APPLICATION_MENUITEM((CSB_TESTOOL_MENUID, CSB_MENUID, 3,
							CSB_TESTOOL_RUN_MENUID,
							CSB_TESTOOL_SET_LOC_MENUID,
							CSB_TESTOOL_VIEW_IMAGES_MENUID,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_TESTTOOL_TEXT, 0));


	/* View Menu */
	ADD_APPLICATION_MENUITEM((CSB_START_VIEW_MENUID, CSB_VIEW_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_START_VIEW_TEXT, 0));

    ADD_APPLICATION_MENUITEM((CSB_START_VIEW_X_MENUID, CSB_VIEW_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_START_VIEW_X_TEXT, 0));

    ADD_APPLICATION_MENUITEM((CSB_VIEW_OPTIONS_MENUID, CSB_VIEW_MENUID, 2,
							CSB_VIEW_OPTIONS_VIEW_MODE_MENUID,
							CSB_VIEW_OPTIONS_MODE_SETTINGS_MENUID,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_VIEW_OPTIONS_TEXT, 0));

	/* View Options Menu */
	ADD_APPLICATION_MENUITEM((CSB_VIEW_OPTIONS_VIEW_MODE_MENUID, CSB_VIEW_OPTIONS_MENUID, 2,
							CSB_OPTIONS_VIEW_MODE_MANUAL_MENUID,
							CSB_OPTIONS_VIEW_MODE_AUTO_MENUID,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_OPTIONS_VIEW_MODE_TEXT, 0));

	/* View Options View Mode */
	ADD_APPLICATION_MENUITEM((CSB_OPTIONS_VIEW_MODE_MANUAL_MENUID, CSB_VIEW_OPTIONS_VIEW_MODE_MENUID,0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_VIEW_MODE_MANUAL_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_OPTIONS_VIEW_MODE_AUTO_MENUID, CSB_VIEW_OPTIONS_VIEW_MODE_MENUID,0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_VIEW_MODE_AUTO_TEXT, 0));


	/* View Options Mode Settings */
	ADD_APPLICATION_MENUITEM((CSB_VIEW_OPTIONS_MODE_SETTINGS_MENUID, CSB_VIEW_OPTIONS_MENUID, 2,
							CSB_OPTIONS_SETTING_AUTO_MODE_TIME_MENUID,
							CSB_OPTIONS_SETTING_MANUAL_MODE_MENUID,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_OPTIONS_MODE_SETTINGS_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_OPTIONS_SETTING_MANUAL_MODE_MENUID, CSB_VIEW_OPTIONS_MODE_SETTINGS_MENUID, 2,
							CSB_SETTING_MANUAL_MODE_INTERACTIVE_MENUID,
							CSB_SETTING_MANUAL_MODE_NONINTERACTIVE_MENUID,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_MANUAL_MODE_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_OPTIONS_SETTING_AUTO_MODE_TIME_MENUID, CSB_VIEW_OPTIONS_MODE_SETTINGS_MENUID,0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_AUTO_MODE_TIME_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_SETTING_MANUAL_MODE_INTERACTIVE_MENUID, CSB_OPTIONS_SETTING_MANUAL_MODE_MENUID,0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_MANUAL_MODE_INTERACTIVE_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_SETTING_MANUAL_MODE_NONINTERACTIVE_MENUID, CSB_OPTIONS_SETTING_MANUAL_MODE_MENUID,0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_MANUAL_MODE_NONINTERACTIVE_TEXT, 0));


	/* Search By Control Menu */
	ADD_APPLICATION_MENUITEM((CSB_SEARCH_CONTROL_MENUID, CSB_SEARCH_MENUID, CSB_TOTAL_CONTROLS,
							CSB_CONTROL_CALL_MENUID,
							CSB_CONTROL_COLOR_PKR_MENUID,
							CSB_CONTROL_EDITOR_MENUID,
							CSB_CONTROL_IDLE_SCREEN_MENUID,
							CSB_CONTROL_IMAGE_VWR_MENUID,
							CSB_CONTROL_LIST_MENUID,
							CSB_CONTROL_MATRIX_MENUID,
							CSB_CONTROL_POPUP_MENUID,
							CSB_CONTROL_PROGRESS_MENUID,
							CSB_CONTROL_SLIDER_MENUID,
							CSB_CONTROL_RADIO_BUTTON_MENUID,
							CSB_CONTROL_CHECK_BOX_MENUID,
							CSB_CONTROL_SUBLCD_MENUID,
							CSB_CONTROL_PANEL_MENUID,//052907 CSB
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_SEARCH_CONTROL_TEXT, 0));

	/* Search by Application menu */
    ADD_APPLICATION_MENUITEM((CSB_SEARCH_APP_MENUID, CSB_SEARCH_MENUID, CSB_TOTAL_APP,
							CSB_APP_CALLS_MENUID,
							CSB_APP_EDITOR_MENUID,
							CSB_APP_ENGG_MODE_MENUID,
							CSB_APP_EXTRA_MENUID,
							CSB_APP_FUN_AND_GAMES_MENUID,
							CSB_APP_FILE_MANAGER_MENUID,
							CSB_APP_MESSAGES_MENUID,
							CSB_APP_MISC_MENUID,
							CSB_APP_MULTIMEDIA_MENUID,
							CSB_APP_ORGANIZER_MENUID,
							CSB_APP_PHONEBOOK_MENUID,
							CSB_APP_PROFILE_MENUID,
							CSB_APP_SERVICES_MENUID,
							CSB_APP_SHORTCUT_MENUID,
							CSB_APP_SETTINGS_MENUID,
							CSB_APP_WAP_MENUID,
							CSB_APP_HID_MENUID,//052907 CSB
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_SEARCH_APP_TEXT, 0));
	/* Search by Screen ID */
    ADD_APPLICATION_MENUITEM((CSB_SEARCH_SCREENID_MENUID, CSB_SEARCH_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_SEARCH_SCREENID_TEXT, 0));


	/* Control Sub Menus */
	ADD_APPLICATION_MENUITEM((CSB_CONTROL_CALL_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_CALL_SCR_TEXT, 0));
	
	ADD_APPLICATION_MENUITEM((CSB_CONTROL_COLOR_PKR_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_COLOR_PICKER_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_EDITOR_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_EDITOR_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_EDITOR_LIST_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_EDITOR_LIST_MENU_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_EDITOR_POPUP_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_EDITOR_POPUP_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_IDLE_SCREEN_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_IDLE_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_IMAGE_VWR_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_IMAGE_VIEWER_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_LIST_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_LIST_MENU_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_MATRIX_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_MATRIX_MENU_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_POPUP_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_POPUP_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_PROGRESS_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_PROGRESS_BAR_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_SLIDER_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_SLIDER_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_RADIO_BUTTON_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_RADIO_BUTTON_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_CHECK_BOX_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_CHECK_BOX_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_SUBLCD_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_SUB_LCD_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_CONTROL_PANEL_MENUID, CSB_SEARCH_CONTROL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_PANEL_TEXT, 0));//052907 CSB


	/* Application Sub Menus */
	ADD_APPLICATION_MENUITEM((CSB_APP_CALLS_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_CALLS_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_EDITOR_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_EDITOR_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_ENGG_MODE_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_ENGG_MODE_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_EXTRA_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_EXTRA_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_FUN_AND_GAMES_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_FUN_AND_GAMES_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_FILE_MANAGER_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_FILE_MANAGER_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_MESSAGES_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_MESSAGES_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_MISC_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_MISC_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_MULTIMEDIA_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_MULTIMEDIA_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_ORGANIZER_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_ORGANIZER_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_PHONEBOOK_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_PHONEBOOK_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_PROFILE_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_PROFILE_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_SERVICES_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_SERVICES_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_SHORTCUT_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_SHORTCUT_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_SETTINGS_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_SETTINGS_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_WAP_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_WAP_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_UNUSED_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_UNUSED_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_APP_HID_MENUID, CSB_SEARCH_APP_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_HID_TEXT, 0));//052907 CSB


	/* Test Tool menuitems */
	ADD_APPLICATION_MENUITEM((CSB_TESTOOL_RUN_MENUID, CSB_TESTOOL_MENUID, 0,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_RUN_TESTTOOL_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_TESTOOL_SET_LOC_MENUID, CSB_TESTOOL_MENUID, 0,
						SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_SET_LOCATION_TEXT, 0));

	ADD_APPLICATION_MENUITEM((CSB_TESTOOL_VIEW_IMAGES_MENUID, CSB_TESTOOL_MENUID, 0,
						SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_VIEW_IMAGES, 0));

	/* Dummy Menuitem */
	ADD_APPLICATION_MENUITEM((CSB_DUMMY_PARENT_MENUID, 0, 7,
                            CSB_DUMMY_CHILD1_MENUID,
                            CSB_DUMMY_CHILD2_MENUID,
                            CSB_DUMMY_CHILD3_MENUID,
							CSB_DUMMY_CHILD4_MENUID,
							CSB_DUMMY_CHILD5_MENUID,
							CSB_DUMMY_CHILD6_MENUID,
							CSB_DUMMY_CHILD7_MENUID,
							SHOW, NONMOVEABLE, DISP_LIST, STR_ID_CSB_CATEGORY_TEXT, 0));

}

#endif
#endif /* __MMI_CSB_BROWSER__ */


