/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

#include "MMI_features.h" 
#ifdef __MMI_SOUND_RECORDER__

#include "MMIDataType.h"    /* for resource base */

#include "CustResDef.h"         /* for image/audio path */
#include "CustDataProts.h"      /* for resource generator API */
#include "GlobalMenuItems.h"    /* for menu resource */
#include "GlobalDefs.h"             /* for global string */
#include "SoundRecorderResDef.h"
#include "FunAndGamesResDef.h"

void populateSoundRecorderMenu(void)
{
#ifdef __MMI_SOUND_RECORDER_STYLE_X__
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_MAIN,"Voice Recorder", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_NEW_RECORD,"New Record", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_LIST,"List", "Sound Recorder String");
#else
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_MAIN,"Sound Recorder", "Sound Recorder String");
#endif
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_OPTION,"Option", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_RECORD,"Record", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_PLAY,"Play", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_APPEND,"Append", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_RENAME,"Rename", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_DELETE,"Delete", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_DELETE_ALL,"Delete All Files", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_SMS_RECORD_TIMEOUT,"Exceed Application Limit", "Sound Recorder String");
#ifdef __MMI_MEMORY_CARD_SUPPORT__
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_DELETE_ALL_PHONE,"Phone", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_DELETE_ALL_CARD,"Card", "Sound Recorder String");
#endif
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_SETTINGS,"Settings", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_RENAME_OPTION,"Option", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_OPTION_SAVE,"Save", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_OPTION_INPUT_METHOD,"Input Method", "Sound Recorder String");
#ifdef __MMI_MEMORY_CARD_SUPPORT__
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_SETTINGS_STORAGE,"Pref. Storage", "Sound Recorder String");
//	ADD_APPLICATION_STRING2(STR_ID_SNDREC_SETTINGS_PHONE,"Phone", "Sound Recorder String");
//	ADD_APPLICATION_STRING2(STR_ID_SNDREC_SETTINGS_CARD,"Card", "Sound Recorder String");
#endif
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_SETTINGS_FORMAT,"File Format", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_SETTINGS_AMR,"AMR", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_SETTINGS_WAV,"WAV", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_SETTINGS_AMRWB,"AWB", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_SETTINGS_VM,"VM", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_PAUSE,"Pause", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_RESUME,"Cont.", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_STOP,"Stop", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_QUERY_ABORT, "Abort", "Voice Memo String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_OPEN_FILE_ERROR,"Can't Open", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_NO_CARD,"Drive Not Found", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_COMMAND_ERROR,"Command Error", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_DEVICE_BUSY,"Device Busy", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_ERROR, "Audio Content Error!!", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_AVAILABLE, "Available", "Sound Recorder String");
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_BAD_FORMAT, "Bad Format", "Sound Recorder String" );
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_INVALID_FORMAT, "Invalid Format", "Sound Recorder String" );
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_WRITE_PROTECTION_ERROR, "Write Protection!!", "Sound Recorder String" );

	ADD_APPLICATION_STRING2(STR_ID_SNDREC_AUTO_RECORD_ON, "Auto Record is Recording", "Sound Recorder String" );
    ADD_APPLICATION_STRING2(STR_ID_SNDREC_SETTING_QUALITY, "Audio Quality", "Sound Recorder String" );
    ADD_APPLICATION_STRING2(STR_ID_SNDREC_QUALITY_HIGH, "High", "Sound Recorder String" );
    ADD_APPLICATION_STRING2(STR_ID_SNDREC_QUALITY_LOW, "Low", "Sound Recorder String" );
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_UNSUPPORTED_FREQ, "Unsupported frequency", "Sound Recorder String" );
	ADD_APPLICATION_STRING2(STR_ID_SNDREC_SAVE_AUDIO, "Save Audio?", "Sound Recorder String" );
/* level 1 */
#ifdef __MMI_SOUND_RECORDER_STYLE_X__
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_MAIN, MAIN_MENU_MULTIMEDIA_MENUID, 2,
		MENU_ID_SNDREC_NEW_RECORD,
		MENU_ID_SNDREC_LIST,
		SHOW, MOVEABLEACROSSPARENT | SHORTCUTABLE, DISP_LIST,STR_ID_SNDREC_MAIN,IMG_ID_SNDREC_MAIN));
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_NEW_RECORD, MENU_ID_SNDREC_MAIN, 0, 
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_NEW_RECORD, IMG_ID_SNDREC_NEW_RECORD));
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_LIST, MENU_ID_SNDREC_MAIN, 0, 
		SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_LIST, IMG_ID_SNDREC_LIST));
#else
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_MAIN, MAIN_MENU_MULTIMEDIA_MENUID, 0,
		SHOW, MOVEABLEACROSSPARENT | SHORTCUTABLE, DISP_LIST,STR_ID_SNDREC_MAIN,IMG_ID_SNDREC_MAIN));
#endif

/* level 2 */
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_OPTION, 0,  
#ifdef __MMI_SOUND_RECORDER_STYLE_X__
                     7,
#else
                     8,
                     MENU_ID_SNDREC_RECORD,
#endif
                     MENU_ID_SNDREC_PLAY,
                     MENU_ID_SNDREC_APPEND,
                     MENU_ID_SNDREC_RENAME,
                     MENU_ID_SNDREC_DELETE,
                     MENU_ID_SNDREC_DELETE_ALL,
                     MENU_ID_SNDREC_SETTINGS,
                     MENU_FMGR_GEN_OPTION_FORWARD,
							SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));

	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_OPTION_1, 0,
#ifdef __MMI_SOUND_RECORDER_STYLE_X__
                     1,
#else
                     2,
                     MENU_ID_SNDREC_RECORD,
#endif
                     MENU_ID_SNDREC_SETTINGS,
							SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));

	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_OPTION_2, 0,
#ifdef __MMI_SOUND_RECORDER_STYLE_X__
                     6,
#else
                     7,
                     MENU_ID_SNDREC_RECORD,
#endif
                     MENU_ID_SNDREC_PLAY,
                     MENU_ID_SNDREC_RENAME,
                     MENU_ID_SNDREC_DELETE,
                     MENU_ID_SNDREC_DELETE_ALL,
                     MENU_ID_SNDREC_SETTINGS,
                     MENU_FMGR_GEN_OPTION_FORWARD,
							SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));

       ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_OPTION_3, 0,
#ifdef __MMI_SOUND_RECORDER_STYLE_X__
                     6,
#else
                     7,
                     MENU_ID_SNDREC_RECORD,
#endif
                     MENU_ID_SNDREC_PLAY,
                     MENU_ID_SNDREC_APPEND,
                     MENU_ID_SNDREC_RENAME,
                     MENU_ID_SNDREC_DELETE,
                     MENU_ID_SNDREC_DELETE_ALL,
                     MENU_FMGR_GEN_OPTION_FORWARD,
							SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));

	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_OPTION_4, 0, 1,
#ifdef __MMI_SOUND_RECORDER_STYLE_X__
                     MENU_ID_SNDREC_NEW_RECORD,
#else
                     MENU_ID_SNDREC_RECORD,
#endif
							SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));

	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_OPTION_5, 0,
#ifdef __MMI_SOUND_RECORDER_STYLE_X__
                     5,
#else
                     6,
                     MENU_ID_SNDREC_RECORD,
#endif
                     MENU_ID_SNDREC_PLAY,
                     MENU_ID_SNDREC_RENAME,
                     MENU_ID_SNDREC_DELETE,
                     MENU_ID_SNDREC_DELETE_ALL,
                     MENU_FMGR_GEN_OPTION_FORWARD,
							SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));

	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_OPTION_6, 0,  
#ifdef __MMI_SOUND_RECORDER_STYLE_X__
		6,
#else
		7,
		MENU_ID_SNDREC_RECORD,
#endif
        MENU_ID_SNDREC_PLAY,
        MENU_ID_SNDREC_APPEND,
        MENU_ID_SNDREC_RENAME,
        MENU_ID_SNDREC_DELETE,
        MENU_ID_SNDREC_DELETE_ALL,
        MENU_ID_SNDREC_SETTINGS,
		SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));

	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_OPTION_7, 0,
#ifdef __MMI_SOUND_RECORDER_STYLE_X__
        5,
#else
        6,
        MENU_ID_SNDREC_RECORD,
#endif
        MENU_ID_SNDREC_PLAY,
        MENU_ID_SNDREC_RENAME,
        MENU_ID_SNDREC_DELETE,
        MENU_ID_SNDREC_DELETE_ALL,
        MENU_ID_SNDREC_SETTINGS,
		SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));

	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_OPTION_8, 0,
#ifdef __MMI_SOUND_RECORDER_STYLE_X__
        5,
#else
        6,
        MENU_ID_SNDREC_RECORD,
#endif
        MENU_ID_SNDREC_PLAY,
        MENU_ID_SNDREC_APPEND,
        MENU_ID_SNDREC_RENAME,
        MENU_ID_SNDREC_DELETE,
        MENU_ID_SNDREC_DELETE_ALL,
		SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));

	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_OPTION_9, 0,
#ifdef __MMI_SOUND_RECORDER_STYLE_X__
        4,
#else
        5,
        MENU_ID_SNDREC_RECORD,
#endif
        MENU_ID_SNDREC_PLAY,
        MENU_ID_SNDREC_RENAME,
        MENU_ID_SNDREC_DELETE,
        MENU_ID_SNDREC_DELETE_ALL,
		SHOW, NONMOVEABLE, DISP_LIST,	STR_ID_SNDREC_OPTION, IMG_ID_SNDREC_OPTION));

/* level 3 */
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_RECORD, MENU_ID_SNDREC_OPTION, 0, 
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_RECORD, IMG_ID_SNDREC_RECORD));
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_PLAY, MENU_ID_SNDREC_OPTION, 0, 
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_PLAY, IMG_ID_SNDREC_PLAY));
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_APPEND, MENU_ID_SNDREC_OPTION, 0, 
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_APPEND, IMG_ID_SNDREC_APPEND));
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_RENAME, MENU_ID_SNDREC_OPTION, 0, 
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_RENAME, IMG_ID_SNDREC_RENAME));
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_DELETE, MENU_ID_SNDREC_OPTION, 0, 
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_DELETE, IMG_ID_SNDREC_DELETE));
#ifdef __MMI_MEMORY_CARD_SUPPORT__
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_DELETE_ALL, MENU_ID_SNDREC_OPTION, 2, 
                     MENU_ID_SNDREC_DELETE_ALL_PHONE,
                     MENU_ID_SNDREC_DELETE_ALL_CARD,
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_DELETE_ALL, IMG_ID_SNDREC_DELETE_ALL));
#else
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_DELETE_ALL, MENU_ID_SNDREC_OPTION, 0, 
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_DELETE_ALL, IMG_ID_SNDREC_DELETE_ALL));

#endif
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_SETTINGS, MENU_ID_SNDREC_OPTION, 0, 
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_SETTINGS, IMG_ID_SNDREC_SETTINGS));

/* level 4 */
#ifdef __MMI_MEMORY_CARD_SUPPORT__
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_DELETE_ALL_PHONE, MENU_ID_SNDREC_DELETE_ALL, 0, 
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_DELETE_ALL_PHONE, IMG_ID_SNDREC_DELETE_ALL_PHONE));
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_DELETE_ALL_CARD, MENU_ID_SNDREC_DELETE_ALL, 0, 
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,	STR_ID_SNDREC_DELETE_ALL_CARD, IMG_ID_SNDREC_DELETE_ALL_CARD));
#endif
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_RENAME_OPTION,	0, 	2,  
							MENU_ID_SNDREC_OPTION_SAVE,
							MENU_ID_SNDREC_OPTION_INPUT_METHOD,
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,
							STR_ID_SNDREC_RENAME_OPTION, IMG_ID_SNDREC_RENAME_OPTION));
	ADD_APPLICATION_MENUITEM(  (MENU_ID_SNDREC_OPTION_SAVE,	MENU_ID_SNDREC_RENAME_OPTION, 0, 
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,
							STR_ID_SNDREC_OPTION_SAVE, IMG_ID_SNDREC_OPTION_SAVE));
	ADD_APPLICATION_MENUITEM( (MENU_ID_SNDREC_OPTION_INPUT_METHOD,	MENU_ID_SNDREC_RENAME_OPTION, 0, 
							SHOW, MOVEABLEWITHINPARENT, DISP_LIST,
							STR_ID_SNDREC_OPTION_INPUT_METHOD, IMG_ID_SNDREC_OPTION_INPUT_METHOD));
	ADD_APPLICATION_IMAGE2(IMG_ID_SNDREC_MAIN,CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SB_SR.PBM"	,"Sound Recorder icon");	
	//ADD_APPLICATION_IMAGE2(IMG_ID_SNDREC_SETTINGS_PHONE,CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SRSetting\\\\SR_PHONE.PBM","Sound Recorder Playing");
	//ADD_APPLICATION_IMAGE2(IMG_ID_SNDREC_SETTINGS_CARD,CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SRSetting\\\\SR_CARD.PBM","Sound Recorder Play Pause");
	ADD_APPLICATION_IMAGE2(IMG_ID_SNDREC_SETTINGS_STORAGE,CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SRSetting\\\\SR_STORAGE.PBM","Sound Recorder Play Pause");
	ADD_APPLICATION_IMAGE2(IMG_ID_SNDREC_SETTINGS_FORMAT,CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SRSetting\\\\SR_FORMAT.PBM","Sound Recorder Play Pause");
        ADD_APPLICATION_IMAGE2(IMG_ID_SNDREC_SETTINGS_QUALITY,CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SRSetting\\\\SR_SoundQuality.pbm","Sound Recorder Play Pause");
#ifdef __MMI_SLIM_PROGRESS_ANIMATION__
	ADD_APPLICATION_IMAGE2( IMG_ID_SNDREC_RECORDING, CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\Progress\\\\PROGRESS"__MMI_RES_TYPE_POPUP_SCREEN__, "shared progress image" );
#else
	ADD_APPLICATION_IMAGE2(IMG_ID_SNDREC_RECORDING,CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SR_RECORD.GIF","Sound Recorder Recording");
#endif
	ADD_APPLICATION_IMAGE2(IMG_ID_SNDREC_RECORDING_PAUSED,CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SR_RECORD_P.GIF","Sound Recorder Record Pause");

#ifdef __MMI_SLIM_PROGRESS_ANIMATION__
	ADD_APPLICATION_IMAGE2( IMG_ID_SNDREC_PLAYING, CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\Progress\\\\PROGRESS"__MMI_RES_TYPE_POPUP_SCREEN__, "shared progress image" );
#else
	ADD_APPLICATION_IMAGE2(IMG_ID_SNDREC_PLAYING,CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SR_PLAY.GIF","Sound Recorder Playing");
#endif
	ADD_APPLICATION_IMAGE2(IMG_ID_SNDREC_PLAYING_PAUSED,CUST_IMG_PATH"\\\\MainLCD\\\\SoundRecorder\\\\SR_PLAY_P.GIF","Sound Recorder Play Pause");
}
#endif /* __MMI_SOUND_RECORDER__ */



