/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/*****************************************************************************
 *
 * Filename:
 * ---------
 *  Res_MobileTVPlayer.c
 *
 * Project:
 * --------
 *  MAUI
 *
 * Description:
 * ------------
 *  Mobile TV Player Applications v0.1
 *
 * Author:
 * -------
 * -------
 *                      
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

/****************************************************************************
* Include Files                                                                
*****************************************************************************/
#include "CustomCfg.h"

#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif 

#include "MMI_features.h"
#include "MMIDataType.h"
#if defined(__MMI_MOBILE_TV_PLAYER__)

#include "lcd_sw_inc.h"
#include "MobileTVPlayerResDef.h"       /* include this for mobile tv player related resource IDs */
#include "mmi_features_mtv_player.h"


#include "PopulateRes.h"
#include "CustResDef.h"

#if defined(__MMI_MTV_A2DP_SUPPORT__)
#include "AudioPlayerResDef.h"
#endif

/***************************************************************************** 
* Typedef 
*****************************************************************************/


/*****************************************************************************
 * FUNCTION
 *  PopulateMobileTVPlayerStrRes
 * DESCRIPTION
 *  Generate Mobile TV Player application string resources
 * PARAMETERS
 *  void
 * RETURNS
 *  void
 *****************************************************************************/
void PopulateMobileTVPlayerStrRes(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_APP_NAME, "Mobile TV", "[Mobile TV App Name]");

	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_CHANNEL_LIST, "Channel List", "[Mobile TV App Name]");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_SETTING, "Settings", "[Mobile TV App Name]");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_STORAGE, "Storage", "[Mobile TV App Name]");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_BAND, "Band", "[Mobile TV App Name]");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_PLAY, "Play", "[Mobile TV App Name]");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_UPDATE_LIST, "Update List", "[Mobile TV App Name]");
       

	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_SETTING_BRIGHTNESS,"Brightness","STR_ID_MOBILE_TV_SETTING_BRIGHTNESS");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_SETTING_CONTRAST,"Contrast","STR_ID_MOBILE_TV_SETTING_CONTRAST");

	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_SETTING_PLAY_SPEED,	"Play Speed", "STR_ID_MOBILE_TV_PLAYER_SETTING_PLAY_SPEED");
	ADD_APPLICATION_STRING2(STR_ID_MTV_PLAYER_PLAY_SPEED_10X,	"1x",		"STR_ID_MTV_PLAYER_PLAY_SPEED_10X");
	ADD_APPLICATION_STRING2(STR_ID_MTV_PLAYER_PLAY_SPEED_20X,	"2x",		"STR_ID_MTV_PLAYER_PLAY_SPEED_20X");
	ADD_APPLICATION_STRING2(STR_ID_MTV_PLAYER_PLAY_SPEED_5X,	"0.5x",		"STR_ID_MTV_PLAYER_PLAY_SPEED_5X");


	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_ADJUST_N5,	"-5",		"STR_ID_MOBILE_TV_ADJUST_N5");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_ADJUST_N4,	"-4",		"STR_ID_MOBILE_TV_ADJUST_N4");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_ADJUST_N3,	"-3",		"STR_ID_MOBILE_TV_ADJUST_N3");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_ADJUST_N2,	"-2",		"STR_ID_MOBILE_TV_ADJUST_N2");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_ADJUST_N1,	"-1",		"STR_ID_MOBILE_TV_ADJUST_N1");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_ADJUST_0,	"0",		"STR_ID_MOBILE_TV_ADJUST_0");		
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_ADJUST_P1,	"+1",		"STR_ID_MOBILE_TV_ADJUST_P1");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_ADJUST_P2,	"+2",		"STR_ID_MOBILE_TV_ADJUST_P2");		
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_ADJUST_P3,	"+3", 	    "STR_ID_MOBILE_TV_ADJUST_P3");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_ADJUST_P4,	"+4",		"STR_ID_MOBILE_TV_ADJUST_P4");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_ADJUST_P5,	"+5",		"STR_ID_MOBILE_TV_ADJUST_P5");

	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_SAVE_UNSAVED_RECORDING,  "Save unsaved recoding?", "STR_ID_MOBILE_TV_PLAYER_SAVE_UNSAVED_RECORDING");   
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_DISCARDING,  "Discarding...", "STR_ID_MOBILE_TV_PLAYER_DISCARDING");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_NOTIFY_SAVING,  "Auto Saving...", "STR_ID_MOBILE_TV_PLAYER_DISCARDING");
  	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_NOTIFY_SAVE_FILE_ERROR, "Save file failed", "STR_ID_MOBILE_TV_PLAYER_NOTIFY_SAVE_FILE_ERROR");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_NOTIFY_NO_CHANNELS_SCANNED,"No Channel Available!","[Notify-No Channel Available]");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_NOTIFY_STORAGE_NOT_READY,"Storage not ready","[Notify-Storage not ready]");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_NOTIFY_WRITE_PROTECTION,"Memory card is locked.\nCan't write in.","[Notify-Write Protection]");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_NOTIFY_HW_NOT_READY,"HW not ready.","[Notify-HW Not Ready]");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_NOTIFY_ERROR, "Error!!","[Notify- Error]");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_NOTIFY_RECORDER_ERROR, "Recorder Error!!","[Notify- Error]");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_NOTIFY_INITIALIZING, "Init...","[Notify-Init]");

	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_NOTIFY_INITIALIZING_ERROR, "Init Error!!","[Notify- Error]");

	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_BAND_TAIWAN, "Taiwan", "Taiwan");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_BAND_CHINA, "China", "China");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_BAND_JAPAN, "Japan", "Japan");
	ADD_APPLICATION_STRING2(STR_ID_MOBILE_TV_PLAYER_BAND_KOREA, "Korea", "Korea");

}


/*****************************************************************************
 * FUNCTION
 *  PopulateMobileTVPlayerImgRes
 * DESCRIPTION
 *  Generate Mobile TV Player image resource
 * PARAMETERS
 *  void
 * RETURNS
 *  void
 *****************************************************************************/
void PopulateMobileTVPlayerImgRes(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    #define MOBILETVPLAYER_ROOT_PATH CUST_IMG_PATH"\\\\MainLCD\\\\MobileTVPlayer\\\\"
    #define MOBILETVPLAYER_OSD_PATH MOBILETVPLAYER_ROOT_PATH"\\\\OSD\\\\"
    #define MOBILETVPLAYER_OSD_PATH_FULLSCREEN MOBILETVPLAYER_ROOT_PATH"\\\\FULLSCREEN\\\\"
    /******************************************
    * App
    *******************************************/
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MOBILE_TV_PLAYER_APP_ICON,
        MOBILETVPLAYER_ROOT_PATH"MOBILE_TV_PLAYER.pbm",
        "IMG_ID_MOBILE_TV_PLAYER_APP_ICON");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MOBILE_TV_LOADING,
        MOBILETVPLAYER_ROOT_PATH"MTV_LOADING.GIF",
        "IMG_ID_MOBILE_TV_PLAYER_BG");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MOBILE_TV_PLAYER_BG,
        MOBILETVPLAYER_OSD_PATH"MTV_BG.GIF",
        "IMG_ID_MOBILE_TV_PLAYER_BG");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_CHANNEL_NEXT_UP,
        MOBILETVPLAYER_OSD_PATH"MTV_CHANNEL_NEXT_UP.PBM",
        "IMG_ID_MTV_PLAYER_CHANNEL_NEXT_UP");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_CHANNEL_NEXT_DOWN,
        MOBILETVPLAYER_OSD_PATH"MTV_CHANNEL_NEXT_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_CHANNEL_NEXT_DOWN");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_CHANNEL_PREV_UP,
        MOBILETVPLAYER_OSD_PATH"MTV_CHANNEL_PREV_UP.PBM",
        "IMG_ID_MTV_PLAYER_CHANNEL_PREV_UP");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_CHANNEL_PREV_DOWN,
        MOBILETVPLAYER_OSD_PATH"MTV_CHANNEL_PREV_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_CHANNEL_PREV_DOWN");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_FULLSCREEN_UP,
        MOBILETVPLAYER_OSD_PATH"MTV_FULLSCREEN_UP.PBM",
        "IMG_ID_MTV_PLAYER_FULLSCREEN_UP");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_FULLSCREEN_DOWN,
        MOBILETVPLAYER_OSD_PATH"MTV_FULLSCREEN_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_FULLSCREEN_DOWN");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_INTERACTION_UP,
        MOBILETVPLAYER_OSD_PATH"MTV_INTERACTION_UP.PBM",
        "IMG_ID_MTV_PLAYER_INTERACTION_UP");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_INTERACTION_DOWN,
        MOBILETVPLAYER_OSD_PATH"MTV_INTERACTION_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_INTERACTION_DOWN");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PAUSE_UP,
        MOBILETVPLAYER_OSD_PATH"MTV_PAUSE_UP.PBM",
        "IMG_ID_MTV_PLAYER_PAUSE_UP");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PAUSE_DOWN,
        MOBILETVPLAYER_OSD_PATH"MTV_PAUSE_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_PAUSE_DOWN");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PLAY_UP,
        MOBILETVPLAYER_OSD_PATH"MTV_PLAY_UP.PBM",
        "IMG_ID_MTV_PLAYER_PLAY_UP");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PLAY_DOWN,
        MOBILETVPLAYER_OSD_PATH"MTV_PLAY_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_PLAY_DOWN");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_STOP_UP,
        MOBILETVPLAYER_OSD_PATH"MTV_STOP_UP.PBM",
        "IMG_ID_MTV_PLAYER_STOP_UP");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_STOP_DOWN,
        MOBILETVPLAYER_OSD_PATH"MTV_STOP_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_STOP_DOWN");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_FORWARD_UP,
        MOBILETVPLAYER_OSD_PATH"MTV_FORWARD_UP.PBM",
        "IMG_ID_MTV_PLAYER_FORWARD_UP");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_FORWARD_DOWN,
        MOBILETVPLAYER_OSD_PATH"MTV_FORWARD_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_FORWARD_DOWN");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_REWIND_UP,
        MOBILETVPLAYER_OSD_PATH"MTV_REWIND_UP.PBM",
        "IMG_ID_MTV_PLAYER_REWIND_UP");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_REWIND_DOWN,
        MOBILETVPLAYER_OSD_PATH"MTV_REWIND_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_REWIND_DOWN");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_RECORD_UP,
        MOBILETVPLAYER_OSD_PATH"MTV_RECORD_UP.PBM",
        "IMG_ID_MTV_PLAYER_RECORD_UP");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_RECORD_DOWN,
        MOBILETVPLAYER_OSD_PATH"MTV_RECORD_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_RECORD_DOWN");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_INC_UP,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_INC_UP.PBM",
        "IMG_ID_MTV_PLAYER_VOL_INC_UP");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_INC_DOWN,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_INC_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_VOL_INC_DOWN");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_DEC_UP,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_DEC_UP.PBM",
        "IMG_ID_MTV_PLAYER_VOL_DEC_UP");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_DEC_DOWN,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_DEC_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_VOL_DEC_DOWN");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PROGRESS_IND,
        MOBILETVPLAYER_OSD_PATH"MTV_PROGRESS_IND.PBM",
        "IMG_ID_MTV_PROGRESS_IND");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PROGRESS_FILL,
        MOBILETVPLAYER_OSD_PATH"MTV_PROGRESS_FILL.PBM",
        "IMG_ID_MTV_PROGRESS_FILL");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PROGRESS_BAR,
        MOBILETVPLAYER_OSD_PATH"MTV_PROGRESS_BAR.PBM",
        "IMG_ID_MTV_PROGRESS_BAR");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_NUM_0,
        MOBILETVPLAYER_OSD_PATH"MTV_NUM_0.PBM",
        "IMG_ID_MTV_PLAYER_NUM_0");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_NUM_1,
        MOBILETVPLAYER_OSD_PATH"MTV_NUM_1.PBM",
        "IMG_ID_MTV_PLAYER_NUM_1");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_NUM_2,
        MOBILETVPLAYER_OSD_PATH"MTV_NUM_2.PBM",
        "IMG_ID_MTV_PLAYER_NUM_2");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_NUM_3,
        MOBILETVPLAYER_OSD_PATH"MTV_NUM_3.PBM",
        "IMG_ID_MTV_PLAYER_NUM_3");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_NUM_4,
        MOBILETVPLAYER_OSD_PATH"MTV_NUM_4.PBM",
        "IMG_ID_MTV_PLAYER_NUM_4");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_NUM_5,
        MOBILETVPLAYER_OSD_PATH"MTV_NUM_5.PBM",
        "IMG_ID_MTV_PLAYER_NUM_5");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_NUM_6,
        MOBILETVPLAYER_OSD_PATH"MTV_NUM_6.PBM",
        "IMG_ID_MTV_PLAYER_NUM_6");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_NUM_7,
        MOBILETVPLAYER_OSD_PATH"MTV_NUM_7.PBM",
        "IMG_ID_MTV_PLAYER_NUM_7");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_NUM_8,
        MOBILETVPLAYER_OSD_PATH"MTV_NUM_8.PBM",
        "IMG_ID_MTV_PLAYER_NUM_8");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_NUM_9,
        MOBILETVPLAYER_OSD_PATH"MTV_NUM_9.PBM",
        "IMG_ID_MTV_PLAYER_NUM_9");

    /******************************************
    * Play Speed
    *******************************************/
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PLAY_SPEED_5X,
        MOBILETVPLAYER_OSD_PATH"MTV_SPEED_05X.PBM",
        "IMG_ID_MTV_PLAYER_PLAY_SPEED_5X");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PLAY_SPEED_10X,
        MOBILETVPLAYER_OSD_PATH"MTV_SPEED_10X.PBM",
        "IMG_ID_MTV_PLAYER_PLAY_SPEED_10X");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PLAY_SPEED_20X,
        MOBILETVPLAYER_OSD_PATH"MTV_SPEED_20X.PBM",
        "IMG_ID_MTV_PLAYER_PLAY_SPEED_20X");

    /******************************************
    * Signal level
    *******************************************/
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_1,
        MOBILETVPLAYER_OSD_PATH"MTV_SIGNAL_1.PBM",
        "IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_1");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_2,
        MOBILETVPLAYER_OSD_PATH"MTV_SIGNAL_2.PBM",
        "IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_2");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_3,
        MOBILETVPLAYER_OSD_PATH"MTV_SIGNAL_3.PBM",
        "IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_3");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_4,
        MOBILETVPLAYER_OSD_PATH"MTV_SIGNAL_4.PBM",
        "IMG_ID_MTV_PLAYER_SIGNAL_LEVEL_4");


    /******************************************
    * Volume
    *******************************************/
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_MUTE,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_MUTE.PBM",
        "IMG_ID_MTV_PLAYER_VOL_MUTE");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_1,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_1.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_1");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_2,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_2.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_2");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_3,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_3.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_3");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_4,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_4.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_4");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_5,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_5.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_5");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_6,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_6.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_6");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_7,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_7.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_7");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_8,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_8.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_8");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_9,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_9.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_9");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_10,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_10.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_10");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_11,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_11.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_11");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_12,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_12.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_12");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_13,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_13.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_13");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_14,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_14.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_14");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_15,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_15.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_15");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_LEVEL_16,
        MOBILETVPLAYER_OSD_PATH"MTV_VOL_16.PBM",
        "IMG_ID_MTV_PLAYER_VOL_LEVEL_16");


    /************* Full Screen icon ************/

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MOBILE_TV_PLAYER_BG_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_BG.GIF",
        "IMG_ID_MOBILE_TV_PLAYER_BG_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_CHANNEL_NEXT_UP_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_CHANNEL_NEXT_UP.PBM",
        "IMG_ID_MTV_PLAYER_CHANNEL_NEXT_UP_H");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_CHANNEL_NEXT_DOWN_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_CHANNEL_NEXT_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_CHANNEL_NEXT_DOWN_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_CHANNEL_PREV_UP_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_CHANNEL_PREV_UP.PBM",
        "IMG_ID_MTV_PLAYER_CHANNEL_PREV_UP_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_CHANNEL_PREV_DOWN_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_CHANNEL_PREV_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_CHANNEL_PREV_DOWN_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_FULLSCREEN_UP_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_FULLSCREEN_UP.PBM",
        "IMG_ID_MTV_PLAYER_FULLSCREEN_UP_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_FULLSCREEN_DOWN_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_FULLSCREEN_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_FULLSCREEN_DOWN_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_INTERACTION_UP_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_INTERACTION_UP.PBM",
        "IMG_ID_MTV_PLAYER_INTERACTION_UP_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_INTERACTION_DOWN_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_INTERACTION_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_INTERACTION_DOWN_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PAUSE_UP_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_PAUSE_UP.PBM",
        "IMG_ID_MTV_PLAYER_PAUSE_UP_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PAUSE_DOWN_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_PAUSE_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_PAUSE_DOWN_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PLAY_UP_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_PLAY_UP.PBM",
        "IMG_ID_MTV_PLAYER_PLAY_UP_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PLAY_DOWN_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_PLAY_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_PLAY_DOWN_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_STOP_UP_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_STOP_UP.PBM",
        "IMG_ID_MTV_PLAYER_STOP_UP_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_STOP_DOWN_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_STOP_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_STOP_DOWN_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_FORWARD_UP_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_FORWARD_UP.PBM",
        "IMG_ID_MTV_PLAYER_FORWARD_UP_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_FORWARD_DOWN_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_FORWARD_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_FORWARD_DOWN_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_REWIND_UP_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_REWIND_UP.PBM",
        "IMG_ID_MTV_PLAYER_REWIND_UP_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_REWIND_DOWN_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_REWIND_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_REWIND_DOWN_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_RECORD_UP_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_RECORD_UP.PBM",
        "IMG_ID_MTV_PLAYER_RECORD_UP_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_RECORD_DOWN_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_RECORD_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_RECORD_DOWN_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_INC_UP_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_INC_UP.PBM",
        "IMG_ID_MTV_PLAYER_VOL_INC_UP_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_INC_DOWN_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_INC_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_VOL_INC_DOWN_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_DEC_UP_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_DEC_UP.PBM",
        "IMG_ID_MTV_PLAYER_VOL_DEC_UP_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_DEC_DOWN_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_DEC_DOWN.PBM",
        "IMG_ID_MTV_PLAYER_VOL_DEC_DOWN_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PROGRESS_IND_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_PROGRESS_IND.PBM",
        "IMG_ID_MTV_PROGRESS_IND_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PROGRESS_FILL_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_PROGRESS_FILL.PBM",
        "IMG_ID_MTV_PROGRESS_FILL_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PROGRESS_BAR_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_PROGRESS_BAR.PBM",
        "IMG_ID_MTV_PROGRESS_BAR_H");

    /******************************************
    * Play Speed
    *******************************************/
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PLAY_SPEED_5X_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_SPEED_05X.PBM",
        "IMG_ID_MTV_PLAYER_PLAY_SPEED_5X_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PLAY_SPEED_10X_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_SPEED_10X.PBM",
        "IMG_ID_MTV_PLAYER_PLAY_SPEED_10X_H");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_PLAY_SPEED_20X_H,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_SPEED_20X.PBM",
        "IMG_ID_MTV_PLAYER_PLAY_SPEED_20X_H");

    /******************************************
    * Volume
    *******************************************/
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_MUTE,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_MUTE.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_MUTE");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_1,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_1.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_1");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_2,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_2.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_2");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_3,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_3.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_3");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_4,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_4.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_4");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_5,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_5.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_5");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_6,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_6.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_6");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_7,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_7.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_7");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_8,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_8.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_8");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_9,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_9.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_9");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_10,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_10.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_10");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_11,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_11.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_11");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_12,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_12.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_12");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_13,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_13.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_13");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_14,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_14.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_14");
    
    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_15,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_15.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_15");

    ADD_APPLICATION_IMAGE2(
        IMG_ID_MTV_PLAYER_VOL_H_LEVEL_16,
        MOBILETVPLAYER_OSD_PATH_FULLSCREEN"MTV_FULL_VOL_16.PBM",
        "IMG_ID_MTV_PLAYER_VOL_H_LEVEL_16");

}


/*****************************************************************************
 * FUNCTION
 *  PopulateMobileTVPlayerMenuRes
 * DESCRIPTION
 *  Generate Mobile TV Player menu resources
 * PARAMETERS
 *  void
 * RETURNS
 *  void
 *****************************************************************************/
void PopulateMobileTVPlayerMenuRes(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/

    ADD_APPLICATION_MENUITEM((MENU_ID_MOBILE_TV_PLAYER_APP, MAIN_MENU_MULTIMEDIA_MENUID, 0,
                              SHOW, MOVEABLEACROSSPARENT | SHORTCUTABLE, 1, STR_ID_MOBILE_TV_PLAYER_APP_NAME,
                              IMG_ID_MOBILE_TV_PLAYER_APP_ICON));

    /*********** Option Menu *************/
    ADD_APPLICATION_MENUITEM((MENU_ID_MOBILE_TV_PLAYER_OPTION,
                              0,
                              4
                        #if defined(__MMI_MTV_A2DP_SUPPORT__)
                              +1
                        #endif
                              ,                             
                              MENU_ID_MOBILE_TV_PLAYER_OPTION_CHANNEL_LIST,
                              MENU_ID_MOBILE_TV_PLAYER_OPTION_BAND,
                              MENU_ID_MOBILE_TV_PLAYER_OPTION_SETTING,
                        #if defined(__MMI_MTV_A2DP_SUPPORT__)
                              MENU_ID_MOBILE_TV_PLAYER_BLUETOOTH_SETTING,
                        #endif
                              MENU_ID_MOBILE_TV_PLAYER_OPTION_STORAGE,
                              0, 
                              0, 
                              1,
                              STR_GLOBAL_OPTIONS,
                              0));

    ADD_APPLICATION_MENUITEM((MENU_ID_MOBILE_TV_PLAYER_OPTION_CHANNEL_LIST, MENU_ID_MOBILE_TV_PLAYER_OPTION,0,
                            SHOW,NONMOVEABLE,1,STR_ID_MOBILE_TV_PLAYER_CHANNEL_LIST,0));
    ADD_APPLICATION_MENUITEM((MENU_ID_MOBILE_TV_PLAYER_OPTION_SETTING, MENU_ID_MOBILE_TV_PLAYER_OPTION,0,
                            SHOW,NONMOVEABLE,1,STR_ID_MOBILE_TV_PLAYER_SETTING,0));
    ADD_APPLICATION_MENUITEM((MENU_ID_MOBILE_TV_PLAYER_OPTION_STORAGE, MENU_ID_MOBILE_TV_PLAYER_OPTION,0,
                            SHOW,NONMOVEABLE,1,STR_ID_MOBILE_TV_PLAYER_STORAGE,0));
    ADD_APPLICATION_MENUITEM((MENU_ID_MOBILE_TV_PLAYER_OPTION_BAND, MENU_ID_MOBILE_TV_PLAYER_OPTION,0,
                            SHOW,NONMOVEABLE,1,STR_ID_MOBILE_TV_PLAYER_BAND,0));
    #if defined(__MMI_MTV_A2DP_SUPPORT__)
    ADD_APPLICATION_MENUITEM((MENU_ID_MOBILE_TV_PLAYER_BLUETOOTH_SETTING, MENU_ID_MOBILE_TV_PLAYER_OPTION,0,
                            SHOW,NONMOVEABLE,1,STR_ID_AUDPLY_BLUETOOTH_SETTINGS,0));
    #endif


    /*********** Option Menu for Channel List **************/
	ADD_APPLICATION_MENUITEM((MENU_ID_MOBILE_TV_PLAYER_CL_OPTION,
                              0,
                              2,
                              MENU_ID_MOBILE_TV_PLAYER_CL_OPTION_PLAY,
                              MENU_ID_MOBILE_TV_PLAYER_CL_OPTION_UPDATE,
                              0, 
                              0, 
                              1,
                              STR_GLOBAL_OPTIONS,
                              0));

    ADD_APPLICATION_MENUITEM((MENU_ID_MOBILE_TV_PLAYER_CL_OPTION_PLAY, MENU_ID_MOBILE_TV_PLAYER_CL_OPTION,0,
                            SHOW,NONMOVEABLE,1,STR_ID_MOBILE_TV_PLAYER_PLAY,0));
    ADD_APPLICATION_MENUITEM((MENU_ID_MOBILE_TV_PLAYER_CL_OPTION_UPDATE, MENU_ID_MOBILE_TV_PLAYER_CL_OPTION,0,
                            SHOW,NONMOVEABLE,1,STR_ID_MOBILE_TV_PLAYER_UPDATE_LIST,0));

}


/*****************************************************************************
 * FUNCTION
 *  PopulateMobileTVPlayerRes
 * DESCRIPTION
 *  Generate Mobile TV Player related resources
 * PARAMETERS
 *  void
 * RETURNS
 *  void
 *****************************************************************************/
void PopulateMobileTVPlayerRes(void)
{
    /*----------------------------------------------------------------*/
    /* Local Variables                                                */
    /*----------------------------------------------------------------*/

    /*----------------------------------------------------------------*/
    /* Code Body                                                      */
    /*----------------------------------------------------------------*/
    PopulateMobileTVPlayerStrRes();
    PopulateMobileTVPlayerImgRes();
    PopulateMobileTVPlayerMenuRes();
}
#endif /* defined(__MMI_MOBILE_TV_PLAYER__) */ 

