/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
/**
 *	Copyright Notice
 *	?2002 - 2003, Pixtel Communications, Inc., 1489 43rd Ave. W.,
 *	Vancouver, B.C. V6M 4K8 Canada. All Rights Reserved.
 *  (It is illegal to remove this copyright notice from this software or any
 *  portion of it)
 */
/*****************************************************************************
 *
 * Filename:
 * ---------
 * Res_Browser.c
 *
 * Project:
 * --------
 *   MAUI
 *
 * Description:
 * ------------
 *   Populate Resource for Generic Browser.
 *
 * Author:
 * -------
 * -------
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 * removed!
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *
 * removed!
 * removed!
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/
#include "MMI_features.h"
#include "CustomCfg.h"

#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"

#ifdef __MMI_BROWSER_2__

#include "BrowserResDef.h"
#include "ProfileHandlerResDef.h"
#include "PushInboxResDef.h"
#include "DLAgentResDef.h"


void PopulateBrowserRes(void)
{
/*Internet Services Menu*//*START*/
    ADD_APPLICATION_MENUITEM((MENU_ID_BRW_HOMEPAGE,SERVICES_WAP_MENU_ID,0,SHOW,NONMOVEABLE,DISP_LIST,
		STR_ID_BRW_HOMEPAGE,IMG_ID_BRW_HOMEPAGE));
#ifdef __MMI_VBOOKMARK__
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BOOKMARKS,SERVICES_WAP_MENU_ID,0,SHOW,NONMOVEABLE,DISP_LIST,
		STR_ID_BRW_BOOKMARKS,IMG_ID_BRW_BOOKMARKS));
#endif /*__MMI_VBOOKMARK__*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ENTER_ADDRESS,SERVICES_WAP_MENU_ID,0,SHOW,NONMOVEABLE,DISP_LIST,
		STR_ID_BRW_ENTER_ADDRESS,IMG_ID_BRW_ENTER_ADDRESS));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_OPEN_FILE,SERVICES_WAP_MENU_ID,0,SHOW,NONMOVEABLE,DISP_LIST,
		STR_ID_BRW_OPEN_FILE,IMG_ID_BRW_OPEN_FILE));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_LAST_WEB_ADDR,SERVICES_WAP_MENU_ID,0,SHOW,NONMOVEABLE,DISP_LIST,
		STR_ID_BRW_LAST_WEB_ADDR,IMG_ID_BRW_LAST_WEB_ADDR));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGES,SERVICES_WAP_MENU_ID,0,SHOW,NONMOVEABLE,DISP_LIST,
		STR_ID_BRW_RECENT_PAGES,IMG_ID_BRW_RECENT_PAGES));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_STORED_PAGES,SERVICES_WAP_MENU_ID,0,SHOW,NONMOVEABLE,DISP_LIST,
		STR_ID_BRW_STORED_PAGES,IMG_ID_BRW_STORED_PAGES));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_PUSH_INBOX,SERVICES_WAP_MENU_ID,0,SHOW,NONMOVEABLE,DISP_LIST,
		STR_ID_PUSH_INBOX,IMG_ID_BRW_PUSH_INBOX));
	ADD_APPLICATION_MENUITEM2((MENU_ID_BRW_SETTINGS, SERVICES_WAP_MENU_ID,
			MENU_ID_BRW_EDIT_PROFILE,
			MENU_ID_BRW_HOMEPAGE_SETTINGS,
			MENU_ID_BRW_BROWSER_OPTIONS,
			MENU_ID_BRW_PREFERENCES,
#if defined (WAP_SEC_SUPPORT)
			MENU_ID_BRW_SECURITY_SETTINGS,
#endif
			MENU_ID_BRW_PUSH_SETTINGS,
			MENU_ID_BRW_RESTORE_BROWSER_SETTINGS,
			MENU_ITEM_END,
				SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_SETTINGS, IMG_ID_BRW_SETTINGS));
/*Internet Services Menu*//*END*/


/* Bookmark Menu Start */
#ifdef __MMI_VBOOKMARK__
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_OPTIONS_FOR_FOLDER, 0, 5,
		MENU_ID_BRW_BKM_OPEN_FOLDER,
		MENU_ID_BRW_BKM_DELETE_FOLDER,
		MENU_ID_BRW_BKM_ADD_BOOKMARK,
		MENU_ID_BRW_BKM_CREATE_FOLDER,
		MENU_ID_BRW_BKM_MEMORY_STATUS,
			SHOW,NONMOVEABLE,DISP_LIST,0,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_OPTIONS_FOR_EMPTY_FOLDER, 0, 3,
		MENU_ID_BRW_BKM_ADD_BOOKMARK,
		MENU_ID_BRW_BKM_CREATE_FOLDER,
		MENU_ID_BRW_BKM_MEMORY_STATUS,
			SHOW,NONMOVEABLE,DISP_LIST,0,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_OPTIONS_FOR_DEFAULT_FILE, 0, 6,
		MENU_ID_BRW_BKM_GOTO,
		MENU_ID_BRW_BKM_VIEW,
		MENU_ID_BRW_BKM_ADD_BOOKMARK,
		MENU_ID_BRW_BKM_SET_AS_HOMEPAGE,
		MENU_ID_BRW_BKM_CREATE_FOLDER,
		MENU_ID_BRW_BKM_MEMORY_STATUS,
			SHOW,NONMOVEABLE,DISP_LIST,0,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_OPTIONS_FOR_USER_FILE, 0, 12,
		MENU_ID_BRW_BKM_GOTO,
		MENU_ID_BRW_BKM_VIEW,
		MENU_ID_BRW_BKM_EDIT,
		MENU_ID_BRW_BKM_DELETE,
		MENU_ID_BRW_BKM_DELETE_ALL_USER_FILES,
		MENU_ID_BRW_BKM_ADD_BOOKMARK,
		MENU_ID_BRW_BKM_SET_AS_HOMEPAGE,
		MENU_ID_BRW_BKM_SEND_BOOKMARK,
		MENU_ID_BRW_BKM_CREATE_FOLDER,
		MENU_ID_BRW_BKM_COPY_TO,
		MENU_ID_BRW_BKM_MOVE_TO,
		MENU_ID_BRW_BKM_MEMORY_STATUS,
			SHOW,NONMOVEABLE,DISP_LIST,0,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_OPTIONS_OPEN_FROM_FMGR, 0, 5,
		MENU_ID_BRW_BKM_GOTO_FROM_FMGR,
		MENU_ID_BRW_BKM_VIEW,
		MENU_ID_BRW_BKM_EDIT_FROM_FMGR,
		MENU_ID_BRW_BKM_SET_AS_HOMEPAGE,
		MENU_ID_BRW_BKM_SAVE_TO_BOOKMARK_FROM_FMGR,
			SHOW,NONMOVEABLE,DISP_LIST,0,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_BROWSE_PATH_OPTIONS, 0, 3,
		MENU_ID_BRW_BKM_BROWSE_PATH_OPTIONS_SELECT,
		MENU_ID_BRW_BKM_BROWSE_PATH_OPTIONS_OPEN_FOLDER,
		MENU_ID_BRW_BKM_BROWSE_PATH_OPTIONS_CREATE_FOLDER,
			SHOW,NONMOVEABLE,DISP_LIST,0,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_OPEN_FOLDER, MENU_ID_BRW_BKM_OPTIONS, 0, SHOW, NONMOVEABLE,DISP_LIST,STR_ID_BRW_OPEN,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_DELETE_FOLDER, MENU_ID_BRW_BKM_OPTIONS, 0, SHOW, NONMOVEABLE,DISP_LIST,STR_ID_BRW_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_GOTO, MENU_ID_BRW_BKM_OPTIONS, 0, SHOW, NONMOVEABLE,DISP_LIST,STR_ID_BRW_GOTO,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_VIEW, MENU_ID_BRW_BKM_OPTIONS, 0, SHOW, NONMOVEABLE,DISP_LIST,STR_ID_BRW_VIEW,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_EDIT, MENU_ID_BRW_BKM_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_EDIT,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_DELETE,MENU_ID_BRW_BKM_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_DELETE_ALL_USER_FILES,MENU_ID_BRW_BKM_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_DELETE_ALL_FILES,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_ADD_BOOKMARK,MENU_ID_BRW_BKM_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_ADD_BOOKMARK,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_SET_AS_HOMEPAGE,MENU_ID_BRW_BKM_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_SET_AS_HOMEPAGE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_SEND_BOOKMARK,MENU_ID_BRW_BKM_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_SEND_BOOKMARK,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_CREATE_FOLDER,MENU_ID_BRW_BKM_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_CREATE_FOLDER,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_COPY_TO,MENU_ID_BRW_BKM_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_COPY_TO,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_MOVE_TO,MENU_ID_BRW_BKM_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_MOVE_TO,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_MEMORY_STATUS,MENU_ID_BRW_BKM_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_MEMORY_STATUS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_BROWSE_PATH_OPTIONS_SELECT,MENU_ID_BRW_BKM_BROWSE_PATH_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_SELECT,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_BROWSE_PATH_OPTIONS_OPEN_FOLDER,MENU_ID_BRW_BKM_BROWSE_PATH_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_OPEN,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_BROWSE_PATH_OPTIONS_CREATE_FOLDER,MENU_ID_BRW_BKM_BROWSE_PATH_OPTIONS, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_CREATE_FOLDER,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_GOTO_FROM_FMGR, MENU_ID_BRW_BKM_OPTIONS_OPEN_FROM_FMGR, 0, SHOW, NONMOVEABLE,DISP_LIST,STR_ID_BRW_GOTO,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_EDIT_FROM_FMGR, MENU_ID_BRW_BKM_OPTIONS_OPEN_FROM_FMGR, 0, SHOW, NONMOVEABLE,DISP_LIST,STR_ID_BRW_EDIT,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_SAVE_TO_BOOKMARK_FROM_FMGR,MENU_ID_BRW_BKM_OPTIONS_OPEN_FROM_FMGR, 0, SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_SAVE_TO_BOOKMARK,0));

	/* Send Bookmark Options Start */
	ADD_APPLICATION_MENUITEM2((MENU_ID_BRW_BKM_SEND_BOOKMARK_OPTIONS, 0,
#if !defined(__MMI_MESSAGES_NO_SEND_BY_SMS_OPTION__)
		MENU_ID_BRW_BKM_SEND_BOOKMARK_AS_SMS,
#endif
#if defined(__MMI_MMS__)
		MENU_ID_BRW_BKM_SEND_BOOKMARK_AS_MMS,
#endif
#if  defined(__MMI_IRDA_SUPPORT__)
		MENU_ID_BRW_BKM_SEND_BOOKMARK_VIA_INFRARED,
#endif
#ifdef __MMI_OPP_SUPPORT__
		MENU_ID_BRW_BKM_SEND_BOOKMARK_VIA_BLUETOOTH,
#endif
#if  defined(__MMI_EMAIL__)
		MENU_ID_BRW_BKM_SEND_BOOKMARK_VIA_EMAIL,
#endif
		MENU_ITEM_END,
			SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_SEND_BOOKMARK,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_SEND_BOOKMARK_AS_SMS,MENU_ID_BRW_BKM_SEND_BOOKMARK_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_TEXT_MESSAGE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_SEND_BOOKMARK_AS_MMS,MENU_ID_BRW_BKM_SEND_BOOKMARK_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_MULTIMEDIA_MESSAGE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_SEND_BOOKMARK_VIA_INFRARED,MENU_ID_BRW_BKM_SEND_BOOKMARK_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_VIA_INFRARED,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_SEND_BOOKMARK_VIA_BLUETOOTH,MENU_ID_BRW_BKM_SEND_BOOKMARK_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_VIA_BLUETOOTH,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BKM_SEND_BOOKMARK_VIA_EMAIL,MENU_ID_BRW_BKM_SEND_BOOKMARK_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_VIA_EMAIL,0));
	/* Send Bookmark Options End */
#endif /*__MMI_VBOOKMARK__*/
/* Bookmark Menu End */

/*Enter Address Options Menu*//*START*/
	ADD_APPLICATION_MENUITEM2((MENU_ID_BRW_ENTER_ADR_OPTIONS, 0,
		MENU_ID_BRW_ENTER_ADR_GOTO,
		MENU_ID_BRW_ENTER_ADR_EDIT,
		MENU_ID_BRW_ENTER_ADR_SET_AS_HOMEPAGE,
#ifdef __MMI_VBOOKMARK__
		MENU_ID_BRW_ENTER_ADR_ADD_TO_BOOKMARK,
#endif /*__MMI_VBOOKMARK__*/
		MENU_ID_BRW_ENTER_ADR_SEND_ADDRESS,
		MENU_ID_BRW_ENTER_ADR_DELETE,
		MENU_ID_BRW_ENTER_ADR_DELETE_ALL,
		MENU_ITEM_END,
			SHOW,NONMOVEABLE,DISP_LIST,0,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ENTER_ADR_GOTO,MENU_ID_BRW_ENTER_ADR_OPTIONS,0,SHOW,NONMOVEABLE,DISP_LIST,
		STR_ID_BRW_GOTO,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ENTER_ADR_EDIT,MENU_ID_BRW_ENTER_ADR_OPTIONS,0,SHOW,NONMOVEABLE,DISP_LIST,
		STR_ID_BRW_EDIT,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ENTER_ADR_SET_AS_HOMEPAGE,MENU_ID_BRW_ENTER_ADR_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SET_AS_HOMEPAGE,0));
#ifdef __MMI_VBOOKMARK__
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ENTER_ADR_ADD_TO_BOOKMARK,MENU_ID_BRW_ENTER_ADR_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_ADD_TO_BOOKMARK,0));
#endif /*__MMI_VBOOKMARK__*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ENTER_ADR_SEND_ADDRESS, MENU_ID_BRW_ENTER_ADR_OPTIONS, 0, SHOW, NONMOVEABLE,
		DISP_LIST, STR_ID_BRW_SEND_ADDRESS, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ENTER_ADR_DELETE,MENU_ID_BRW_ENTER_ADR_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ENTER_ADR_DELETE_ALL,MENU_ID_BRW_ENTER_ADR_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_DELETE_ALL,0));
/*Enter Address Options Menu*//*END*/


/*Send Address Options Menu*//*START*/
	ADD_APPLICATION_MENUITEM2((MENU_ID_BRW_SEND_ADDRESS_OPTIONS, 0,
#if !defined(__MMI_MESSAGES_NO_SEND_BY_SMS_OPTION__)
		MENU_ID_BRW_SEND_ADDRESS_AS_SMS,
#endif
#if defined(__MMI_MMS__)
		MENU_ID_BRW_SEND_ADDRESS_AS_MMS,
#endif
#if  defined(__MMI_IRDA_SUPPORT__)	&&  defined(__MMI_VBOOKMARK__)
		MENU_ID_BRW_SEND_ADDRESS_VIA_INFRARED,
#endif
#if  defined(__MMI_OPP_SUPPORT__)	&&  defined(__MMI_VBOOKMARK__)
		MENU_ID_BRW_SEND_ADDRESS_VIA_BLUETOOTH,
#endif
#if  defined(__MMI_EMAIL__)
		MENU_ID_BRW_SEND_ADDRESS_VIA_EMAIL,
#endif
		MENU_ITEM_END,
			SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_SEND_ADDRESS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SEND_ADDRESS_AS_SMS,MENU_ID_BRW_SEND_ADDRESS_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_TEXT_MESSAGE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SEND_ADDRESS_AS_MMS,MENU_ID_BRW_SEND_ADDRESS_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_MULTIMEDIA_MESSAGE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SEND_ADDRESS_VIA_INFRARED,MENU_ID_BRW_SEND_ADDRESS_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_VIA_INFRARED,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SEND_ADDRESS_VIA_BLUETOOTH,MENU_ID_BRW_SEND_ADDRESS_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_VIA_BLUETOOTH,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SEND_ADDRESS_VIA_EMAIL,MENU_ID_BRW_SEND_ADDRESS_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_VIA_EMAIL,0));
/*Send Address Options Menu*//*END*/


/* Recent Pages Options Menu*//*Start*/
	/* Recent Pages Options Menu - for sorted by last visited or most visited*//*Start*/
	ADD_APPLICATION_MENUITEM2((MENU_ID_BRW_RECENT_PAGE_OPTIONS,0,
		MENU_ID_BRW_RECENT_PAGE_GOTO,
		MENU_ID_BRW_RECENT_PAGE_SORT,
		MENU_ID_BRW_RECENT_PAGE_DELETE,
		MENU_ID_BRW_RECENT_PAGE_DELETE_ALL,
		MENU_ID_BRW_RECENT_PAGE_SET_AS_HOMEPAGE,
#ifdef __MMI_VBOOKMARK__
		MENU_ID_BRW_RECENT_PAGE_ADD_TO_BOOKMARK,
#endif /*__MMI_VBOOKMARK__*/
		MENU_ID_BRW_RECENT_PAGE_SEND_ADDRESS,
		MENU_ITEM_END,
			SHOW,NONMOVEABLE,DISP_LIST,0,0));
	/* Recent Pages Options Menu - for sorted by last visited or most visited*//*End*/

	/* Recent Pages Options Menu - for sorted by site*//*Start*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_OPTIONS_1,0,4,
		MENU_ID_BRW_RECENT_PAGE_OPEN_HOST,
		MENU_ID_BRW_RECENT_PAGE_SORT_HOST,
		MENU_ID_BRW_RECENT_PAGE_DELETE_HOST,
		MENU_ID_BRW_RECENT_PAGE_DELETE_ALL_HOST,
		SHOW,NONMOVEABLE,DISP_LIST,0,0));
	/* Recent Pages Options Menu - for sorted by site*//*End*/

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_GOTO,MENU_ID_BRW_RECENT_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_GOTO,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_SORT,MENU_ID_BRW_RECENT_PAGE_OPTIONS,3,
		MENU_ID_BRW_RECENT_PAGE_SORT_BY_LAST_VISITED,
		MENU_ID_BRW_RECENT_PAGE_SORT_BY_MOST_VISITED,
		MENU_ID_BRW_RECENT_PAGE_SORT_BY_SITE,
			SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_SORT,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_DELETE,MENU_ID_BRW_RECENT_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_DELETE_ALL,MENU_ID_BRW_RECENT_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_DELETE_ALL,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_SET_AS_HOMEPAGE,MENU_ID_BRW_RECENT_PAGE_OPTIONS,0,SHOW,
		NONMOVEABLE,DISP_LIST,STR_ID_BRW_SET_AS_HOMEPAGE,0));
#ifdef __MMI_VBOOKMARK__
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_ADD_TO_BOOKMARK,MENU_ID_BRW_RECENT_PAGE_OPTIONS,0,SHOW,
		NONMOVEABLE,DISP_LIST,STR_ID_BRW_ADD_TO_BOOKMARK,0));
#endif /*__MMI_VBOOKMARK__*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_SEND_ADDRESS,MENU_ID_BRW_RECENT_PAGE_OPTIONS,0,SHOW,
		NONMOVEABLE,DISP_LIST,STR_ID_BRW_SEND_ADDRESS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_OPEN_HOST,MENU_ID_BRW_RECENT_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_OPEN,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_SORT_HOST,MENU_ID_BRW_RECENT_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SORT,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_DELETE_HOST,MENU_ID_BRW_RECENT_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_DELETE_ALL_HOST,MENU_ID_BRW_RECENT_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_DELETE_ALL,0));

/*Sort Recent Pages Menu*//*Start*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_SORT_BY_LAST_VISITED,MENU_ID_BRW_RECENT_PAGE_SORT,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SORT_BY_LAST_VISITED,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_SORT_BY_MOST_VISITED,MENU_ID_BRW_RECENT_PAGE_SORT,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SORT_BY_MOST_VISITED,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_SORT_BY_SITE,MENU_ID_BRW_RECENT_PAGE_SORT,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SORT_BY_SITE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RECENT_PAGE_SORT_BY_DATE,MENU_ID_BRW_RECENT_PAGE_SORT,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SORT_BY_DATE,0));
/*Sort Recent Pages Menu*//*END*/
/* Recent Pages Options Menu*//*End*/


/*Stored Pages Options Menu*//*Start*/
	ADD_APPLICATION_MENUITEM2((MENU_ID_BRW_STORED_PAGE_OPTIONS,0,
		MENU_ID_BRW_STORED_PAGE_OPEN,
		MENU_ID_BRW_STORED_PAGE_PROPERTIES,
		MENU_ID_BRW_STORED_PAGE_RENAME,
		MENU_ID_BRW_STORED_PAGE_DELETE,
		MENU_ID_BRW_STORED_PAGE_DELETE_ALL,
		MENU_ID_BRW_STORED_PAGE_SET_AS_HOMEPAGE,
#ifdef __MMI_VBOOKMARK__
		MENU_ID_BRW_STORED_PAGE_ADD_TO_BOOKMARK,
#endif /*__MMI_VBOOKMARK__*/
		MENU_ID_BRW_STORED_PAGE_SEND_ADDRESS,
		MENU_ID_BRW_STORED_PAGE_MEMORY_STATUS,
		MENU_ITEM_END,
			SHOW,NONMOVEABLE,DISP_LIST,0,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_STORED_PAGE_OPEN,MENU_ID_BRW_STORED_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_OPEN,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_STORED_PAGE_PROPERTIES,MENU_ID_BRW_STORED_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_PROPERTIES,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_STORED_PAGE_RENAME,MENU_ID_BRW_STORED_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_RENAME,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_STORED_PAGE_DELETE,MENU_ID_BRW_STORED_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_STORED_PAGE_DELETE_ALL,MENU_ID_BRW_STORED_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_DELETE_ALL,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_STORED_PAGE_SET_AS_HOMEPAGE,MENU_ID_BRW_STORED_PAGE_OPTIONS,0,SHOW,
		NONMOVEABLE,DISP_LIST,STR_ID_BRW_SET_AS_HOMEPAGE,0));
#ifdef __MMI_VBOOKMARK__
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_STORED_PAGE_ADD_TO_BOOKMARK,MENU_ID_BRW_STORED_PAGE_OPTIONS,0,SHOW,
		NONMOVEABLE,DISP_LIST,STR_ID_BRW_ADD_TO_BOOKMARK,0));
#endif /*__MMI_VBOOKMARK__*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_STORED_PAGE_SEND_ADDRESS,MENU_ID_BRW_STORED_PAGE_OPTIONS,0,SHOW,
		NONMOVEABLE,DISP_LIST,STR_ID_BRW_SEND_ADDRESS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_STORED_PAGE_MEMORY_STATUS,MENU_ID_BRW_STORED_PAGE_OPTIONS,0,SHOW,
		NONMOVEABLE,DISP_LIST,STR_ID_BRW_MEMORY_STATUS,0));
/*Stored Pages Options Menu*//*End*/


/*Browser Settings Menu*//*START*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_EDIT_PROFILE, MENU_ID_BRW_SETTINGS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_EDIT_PROFILE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_HOMEPAGE_SETTINGS, MENU_ID_BRW_SETTINGS, 2,
		MENU_ID_BRW_USER_DEFINED_HOMEPAGE,
		MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_HOMEPAGE_SETTINGS, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BROWSER_OPTIONS, MENU_ID_BRW_SETTINGS, 9,
		MENU_ID_BRW_BROWSER_OPTIONS_RENDERING_MODES,
		MENU_ID_BRW_BROWSER_OPTIONS_NAVIGATION_MODES,
		MENU_ID_BRW_BROWSER_OPTIONS_FONT_SIZE,
		MENU_ID_BRW_BROWSER_OPTIONS_THUMBNAIL,
		MENU_ID_BRW_BROWSER_OPTIONS_SCREEN_SIZE,
		MENU_ID_BRW_BROWSER_OPTIONS_ENCODING,
		MENU_ID_BRW_BROWSER_OPTIONS_CLEAR_CACHE,
		MENU_ID_BRW_BROWSER_OPTIONS_CLEAR_COOKIE,
		MENU_ID_BRW_BROWSER_OPTIONS_CLEAR_AUTH_INFO,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_BROWSER_OPTIONS, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_PREFERENCES, MENU_ID_BRW_SETTINGS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_PREFERENCES, 0));
#if defined (WAP_SEC_SUPPORT)
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SECURITY_SETTINGS, MENU_ID_BRW_SETTINGS, 3,
		MENU_ID_BRW_SECURITY_SETTINGS_SESSION_INFO,
		MENU_ID_BRW_SECURITY_SETTINGS_CURRENT_CERTIFICATE,
		MENU_ID_BRW_SECURITY_SETTINGS_TRUSTED_CERTIFICATES,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_SECURITY_SETTINGS, 0));
#endif
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_PUSH_SETTINGS, MENU_ID_BRW_SETTINGS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PUSH_INBOX_SETTING, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RESTORE_BROWSER_SETTINGS, MENU_ID_BRW_SETTINGS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_RESTORE_BROWSER_SETTINGS, 0));
/*Browser Settings Menu*//*END*/


/*Home Page Settings*//*START*/
	/*User Defined Home Page Settings*//*START*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_USER_DEFINED_HOMEPAGE, MENU_ID_BRW_HOMEPAGE_SETTINGS, 3,
		MENU_ID_BRW_USER_DEFINED_HOMEPAGE_ACTIVATE,
		MENU_ID_BRW_USER_DEFINED_HOMEPAGE_MODIFY,
		MENU_ID_BRW_USER_DEFINED_HOMEPAGE_VIEW,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_USER_DEFINED, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_USER_DEFINED_HOMEPAGE_ACTIVATE, MENU_ID_BRW_USER_DEFINED_HOMEPAGE, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_ACTIVATE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_USER_DEFINED_HOMEPAGE_MODIFY, MENU_ID_BRW_USER_DEFINED_HOMEPAGE, 3,
			MENU_ID_BRW_USE_CURRENT_PAGE,
			MENU_ID_BRW_USE_BLANK,
			MENU_ID_BRW_USER_DEFINED_HOMEPAGE_EDIT,
				SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_MODIFY, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_USER_DEFINED_HOMEPAGE_MODIFY_1, MENU_ID_BRW_USER_DEFINED_HOMEPAGE, 2,
			MENU_ID_BRW_USE_BLANK,
			MENU_ID_BRW_USER_DEFINED_HOMEPAGE_EDIT,
				SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_MODIFY, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_USER_DEFINED_HOMEPAGE_VIEW, MENU_ID_BRW_USER_DEFINED_HOMEPAGE_EDIT, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_VIEW, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_USE_CURRENT_PAGE, MENU_ID_BRW_USER_DEFINED_HOMEPAGE_MODIFY, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_USE_CURRENT_PAGE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_USE_BLANK, MENU_ID_BRW_USER_DEFINED_HOMEPAGE_MODIFY, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_USE_BLANK, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_USER_DEFINED_HOMEPAGE_EDIT, MENU_ID_BRW_USER_DEFINED_HOMEPAGE_MODIFY, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_EDIT, 0));
	/*User Defined Home Page Settings*//*END*/

	/*Active Profile Home Page Settings*//*START*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE, MENU_ID_BRW_HOMEPAGE_SETTINGS, 2,
		MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE_ACTIVATE,
		MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE_VIEW,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_ACTIVE_PROFILE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE_EDITABLE, MENU_ID_BRW_HOMEPAGE_SETTINGS, 3,
		MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE_ACTIVATE,
		MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE_EDIT,
		MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE_VIEW,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_ACTIVE_PROFILE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE_ACTIVATE, MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_ACTIVATE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE_EDIT, MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_EDIT, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE_VIEW, MENU_ID_BRW_ACTIVE_PROFILE_HOMEPAGE, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_VIEW, 0));
	/*Active Profile Home Page Settings*//*END*/
/*Home Page Settings*//*END*/


/*Browsing Options*//*START*/
	/*Rendering Modes*//*START*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BROWSER_OPTIONS_RENDERING_MODES, MENU_ID_BRW_BROWSER_OPTIONS, 4,
		MENU_ID_BRW_RENDERING_MODES_STANDARD,
		MENU_ID_BRW_RENDERING_MODES_TEXT_WRAP,
		MENU_ID_BRW_RENDERING_MODES_SCREEN_OPTIMIZED,
		MENU_ID_BRW_RENDERING_MODES_TEXT_ONLY,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_RENDERING_MODES, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RENDERING_MODES_STANDARD, MENU_ID_BRW_BROWSER_OPTIONS_RENDERING_MODES, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_STANDARD, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RENDERING_MODES_TEXT_WRAP, MENU_ID_BRW_BROWSER_OPTIONS_RENDERING_MODES, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_TEXT_WRAP, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RENDERING_MODES_SCREEN_OPTIMIZED, MENU_ID_BRW_BROWSER_OPTIONS_RENDERING_MODES, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_SCREEN_OPTIMIZED, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_RENDERING_MODES_TEXT_ONLY, MENU_ID_BRW_BROWSER_OPTIONS_RENDERING_MODES, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_TEXT_ONLY, 0));
	/*Rendering Modes*//*END*/

	/*Navigation Modes*//*START*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BROWSER_OPTIONS_NAVIGATION_MODES, MENU_ID_BRW_BROWSER_OPTIONS, 3,
		MENU_ID_BRW_NAVIGATION_MODES_FOUR_WAY,
		MENU_ID_BRW_NAVIGATION_MODES_TWO_WAY,
		MENU_ID_BRW_NAVIGATION_MODES_SCROLLING,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_NAVIGATION_MODES, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_NAVIGATION_MODES_FOUR_WAY, MENU_ID_BRW_BROWSER_OPTIONS_NAVIGATION_MODES, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_FOUR_WAY, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_NAVIGATION_MODES_TWO_WAY, MENU_ID_BRW_BROWSER_OPTIONS_NAVIGATION_MODES, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_TWO_WAY, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_NAVIGATION_MODES_SCROLLING, MENU_ID_BRW_BROWSER_OPTIONS_NAVIGATION_MODES, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_SCROLLING, 0));
	/*Navigation Modes*//*END*/

	/*Font Sizes*//*START*/
	ADD_APPLICATION_MENUITEM2((MENU_ID_BRW_BROWSER_OPTIONS_FONT_SIZE, MENU_ID_BRW_BROWSER_OPTIONS,
		MENU_ID_BRW_BROWSER_OPTIONS_FONT_SIZE_SMALL,
		MENU_ID_BRW_BROWSER_OPTIONS_FONT_SIZE_MEDIUM,
		MENU_ID_BRW_BROWSER_OPTIONS_FONT_SIZE_LARGE,
		MENU_ITEM_END,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_FONT_SIZE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BROWSER_OPTIONS_FONT_SIZE_SMALL, MENU_ID_BRW_BROWSER_OPTIONS_FONT_SIZE, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_SMALL, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BROWSER_OPTIONS_FONT_SIZE_MEDIUM, MENU_ID_BRW_BROWSER_OPTIONS_FONT_SIZE, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_MEDIUM, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BROWSER_OPTIONS_FONT_SIZE_LARGE, MENU_ID_BRW_BROWSER_OPTIONS_FONT_SIZE, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_LARGE, 0));
	/*Font Sizes*//*END*/

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BROWSER_OPTIONS_THUMBNAIL, MENU_ID_BRW_BROWSER_OPTIONS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_THUMBNAIL, 0));

	/*Screen Size Options*//*START*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BROWSER_OPTIONS_SCREEN_SIZE, MENU_ID_BRW_BROWSER_OPTIONS, 2,
		MENU_ID_BRW_SCREEN_SIZE_FULL,
		MENU_ID_BRW_SCREEN_SIZE_SMALL,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_SCREEN_SIZE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SCREEN_SIZE_FULL, MENU_ID_BRW_BROWSER_OPTIONS_SCREEN_SIZE, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_FULL, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SCREEN_SIZE_SMALL, MENU_ID_BRW_BROWSER_OPTIONS_SCREEN_SIZE, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_SMALL, 0));
	/*Screen Size Options*//*END*/

	/*Encoding Methods Menu*//*START*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BROWSER_OPTIONS_ENCODING, MENU_ID_BRW_BROWSER_OPTIONS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_ENCODING, 0));
	/*Encoding Methods Menu*//*END*/

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BROWSER_OPTIONS_CLEAR_CACHE, MENU_ID_BRW_BROWSER_OPTIONS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_CLEAR_CACHE, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BROWSER_OPTIONS_CLEAR_COOKIE, MENU_ID_BRW_BROWSER_OPTIONS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_CLEAR_COOKIE, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_BROWSER_OPTIONS_CLEAR_AUTH_INFO, MENU_ID_BRW_BROWSER_OPTIONS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_CLEAR_AUTH_INFO, 0));

/*Browsing Options*//*END*/


/*Security Settings*//*START*/
#if defined (WAP_SEC_SUPPORT)
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SECURITY_SETTINGS_SESSION_INFO, MENU_ID_BRW_SECURITY_SETTINGS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_SESSION_INFO, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SECURITY_SETTINGS_CURRENT_CERTIFICATE, MENU_ID_BRW_SECURITY_SETTINGS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_CURRENT_CERTIFICATE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SECURITY_SETTINGS_TRUSTED_CERTIFICATES, MENU_ID_BRW_SECURITY_SETTINGS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_TRUSTED_CERTIFICATES, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_TRUSTED_CERTIFICATES_OPTIONS, 0, 2,
			MENU_ID_BRW_TRUSTED_CERTIFICATES_OPTIONS_VIEW,
			MENU_ID_BRW_TRUSTED_CERTIFICATES_OPTIONS_DELETE,
				SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_OPTIONS, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_TRUSTED_CERTIFICATES_OPTIONS_VIEW, MENU_ID_BRW_TRUSTED_CERTIFICATES_OPTIONS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_VIEW, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_TRUSTED_CERTIFICATES_OPTIONS_DELETE, MENU_ID_BRW_TRUSTED_CERTIFICATES_OPTIONS, 0,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_DELETE, 0));
#endif
/*Security Settings*//*END*/

/* Rendered Page Options*//*START*/
	ADD_APPLICATION_MENUITEM2(( MENU_ID_BRW_RENDERED_PAGE_OPTIONS, 0,
        MENU_ID_BRW_REN_PAGE_THIS_LINK,
        MENU_ID_BRW_REN_PAGE_EDIT,
        MENU_ID_BRW_REN_PAGE_RESET,
		MENU_ID_BRW_REN_PAGE_DOWNLOADS,
        MENU_ID_BRW_ENTER_ADDRESS,
		MENU_ID_BRW_HOMEPAGE,
#ifdef __MMI_VBOOKMARK__
        MENU_ID_BRW_BOOKMARKS,
#endif /*__MMI_VBOOKMARK__*/
		MENU_ID_BRW_OPEN_FILE,
		MENU_ID_BRW_RECENT_PAGES,
		MENU_ID_BRW_STORED_PAGES,
		MENU_ID_BRW_REN_PAGE_NAVIGATE,
		MENU_ID_BRW_REN_PAGE_THIS_PAGE,
		MENU_ID_BRW_REN_PAGE_SELECT_MODE,
        MENU_ID_BRW_PUSH_INBOX,
        MENU_ID_BRW_REN_PAGE_SETTINGS,
		MENU_ID_BRW_REN_PAGE_EXIT,
		MENU_ITEM_END,
			SHOW,NONMOVEABLE,DISP_LIST,0,0));

	ADD_APPLICATION_MENUITEM2((MENU_ID_BRW_REN_PAGE_THIS_LINK,MENU_ID_BRW_RENDERED_PAGE_OPTIONS,
		MENU_ID_BRW_THIS_LINK_GOTO,
		MENU_ID_BRW_THIS_LINK_SET_AS_HOMEPAGE,
#ifdef __MMI_VBOOKMARK__
		MENU_ID_BRW_THIS_LINK_ADD_TO_BOOKMARK,
#endif /*__MMI_VBOOKMARK__*/
		MENU_ID_BRW_THIS_LINK_SEND_ADDRESS,
		MENU_ITEM_END,
			SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_THIS_LINK,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_EDIT,MENU_ID_BRW_RENDERED_PAGE_OPTIONS,0,
			SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_EDIT,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_RESET,MENU_ID_BRW_RENDERED_PAGE_OPTIONS,0,
			SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_RESET,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_DOWNLOADS,MENU_ID_BRW_RENDERED_PAGE_OPTIONS,0,
			SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_DOWNLOADS,IMG_ID_DA_DOWNLOAD_ICON));	

	ADD_APPLICATION_MENUITEM2((MENU_ID_BRW_REN_PAGE_THIS_PAGE,MENU_ID_BRW_RENDERED_PAGE_OPTIONS,
		MENU_ID_BRW_REN_PAGE_SET_AS_HOMEPAGE,
#ifdef __MMI_VBOOKMARK__
		MENU_ID_BRW_REN_PAGE_ADD_TO_BOOKMARK,
#endif /*__MMI_VBOOKMARK__*/
		MENU_ID_BRW_REN_PAGE_SEND_ADDRESS,
		MENU_ID_BRW_REN_PAGE_STORE_OFFLINE,
		MENU_ID_BRW_REN_PAGE_PAGE_OBJECTS,
		MENU_ID_BRW_REN_PAGE_PROPERTIES,
		MENU_ITEM_END,
			SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_THIS_PAGE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_SELECT_MODE,MENU_ID_BRW_RENDERED_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SELECT_MODE,0));
	ADD_APPLICATION_MENUITEM2((MENU_ID_BRW_REN_PAGE_SETTINGS, MENU_ID_BRW_RENDERED_PAGE_OPTIONS,
			MENU_ID_BRW_HOMEPAGE_SETTINGS,
			MENU_ID_BRW_BROWSER_OPTIONS,
			MENU_ID_BRW_PREFERENCES,
#if defined (WAP_SEC_SUPPORT)
			MENU_ID_BRW_SECURITY_SETTINGS,
#endif
			MENU_ID_BRW_PUSH_SETTINGS,
			MENU_ID_BRW_RESTORE_BROWSER_SETTINGS,
			MENU_ITEM_END,
				SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_SETTINGS, IMG_ID_BRW_SETTINGS));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_EXIT,MENU_ID_BRW_RENDERED_PAGE_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_EXIT,0));
/* Rendered Page Options*//*END*/

/*This Link Options*//*START*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_THIS_LINK_GOTO, MENU_ID_BRW_REN_PAGE_THIS_LINK, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_GOTO,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_THIS_LINK_SET_AS_HOMEPAGE, MENU_ID_BRW_REN_PAGE_THIS_LINK, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SET_AS_HOMEPAGE,0));
#ifdef __MMI_VBOOKMARK__
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_THIS_LINK_ADD_TO_BOOKMARK, MENU_ID_BRW_REN_PAGE_THIS_LINK, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_ADD_TO_BOOKMARK,0));
#endif /*__MMI_VBOOKMARK__*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_THIS_LINK_SEND_ADDRESS, MENU_ID_BRW_REN_PAGE_THIS_LINK, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SEND_ADDRESS,0));
/*This Link Options*//*END*/


/*This Page Options*//*START*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_SET_AS_HOMEPAGE, MENU_ID_BRW_REN_PAGE_THIS_PAGE, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SET_AS_HOMEPAGE,0));
#ifdef __MMI_VBOOKMARK__
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_ADD_TO_BOOKMARK, MENU_ID_BRW_REN_PAGE_THIS_PAGE, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_ADD_TO_BOOKMARK,0));
#endif /*__MMI_VBOOKMARK__*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_SEND_ADDRESS, MENU_ID_BRW_REN_PAGE_THIS_PAGE, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SEND_ADDRESS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_STORE_OFFLINE, MENU_ID_BRW_REN_PAGE_THIS_PAGE, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_STORE_OFFLINE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_PAGE_OBJECTS, MENU_ID_BRW_REN_PAGE_THIS_PAGE, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_PAGE_OBJECTS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_PROPERTIES, MENU_ID_BRW_REN_PAGE_THIS_PAGE, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_PAGE_PROPERTIES,0));
/*This Page Options*//*END*/

/*Page Objects Options*//*START*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_PAGE_OBJECTS_OPTIONS, 0, 2,
		MENU_ID_BRW_PAGE_OBJECTS_SAVE_AS,
		MENU_ID_BRW_PAGE_OBJECTS_PROPERTIES,
			SHOW, NONMOVEABLE,DISP_LIST,STR_ID_BRW_PAGE_OBJECTS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_PAGE_OBJECTS_SAVE_AS, MENU_ID_BRW_PAGE_OBJECTS_OPTIONS, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SAVE_AS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_PAGE_OBJECTS_PROPERTIES, MENU_ID_BRW_PAGE_OBJECTS_OPTIONS, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_PROPERTIES,0));
/*Page Objects Options*//*END*/

/*Select Mode*//*START*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SELECT_MODE_OPTIONS, 0, 3,
		MENU_ID_BRW_SELECT_MODE_SAVE_AS,
		MENU_ID_BRW_SELECT_MODE_PROPERTIES,
		MENU_ID_BRW_SELECT_MODE_EXIT,
			SHOW, NONMOVEABLE,DISP_LIST,STR_ID_BRW_OPTIONS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SELECT_MODE_SAVE_AS, MENU_ID_BRW_SELECT_MODE_OPTIONS, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SAVE_AS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SELECT_MODE_PROPERTIES, MENU_ID_BRW_SELECT_MODE_OPTIONS, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_PROPERTIES,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_SELECT_MODE_EXIT, MENU_ID_BRW_SELECT_MODE_OPTIONS, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_EXIT,0));
/*Select Mode*//*END*/

/*Navigate*//*START*/
	ADD_APPLICATION_MENUITEM2((MENU_ID_BRW_REN_PAGE_NAVIGATE, MENU_ID_BRW_RENDERED_PAGE_OPTIONS,
		MENU_ID_BRW_REN_PAGE_NAVIGATE_REFRESH,
		MENU_ID_BRW_REN_PAGE_NAVIGATE_FORWARD,
		MENU_ID_BRW_REN_PAGE_NAVIGATE_BACKWARD,
		MENU_ID_BRW_REN_PAGE_NAVIGATE_PAGE_ACTIONS,
		MENU_ITEM_END,
			SHOW, NONMOVEABLE,DISP_LIST,STR_ID_BRW_NAVIGATE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_NAVIGATE_REFRESH, MENU_ID_BRW_REN_PAGE_NAVIGATE, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_REFRESH,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_NAVIGATE_FORWARD, MENU_ID_BRW_REN_PAGE_NAVIGATE, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_FORWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_NAVIGATE_BACKWARD, MENU_ID_BRW_REN_PAGE_NAVIGATE, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_BACKWARD,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_REN_PAGE_NAVIGATE_PAGE_ACTIONS, MENU_ID_BRW_REN_PAGE_NAVIGATE, 0, SHOW, NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_PAGE_ACTIONS,0));
/*Navigate*//*END*/

/*Authentication Dialog Options Menu*//*START*/
/*	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_AUTH_DIALOG_OPTIONS,0,3,
		MENU_ID_BRW_AUTH_DIALOG_DONE,
		MENU_ID_BRW_AUTH_DIALOG_SAVE_BOTH,
		MENU_ID_BRW_AUTH_DIALOG_SAVE_ONLY_USERNAME,
			SHOW,NONMOVEABLE,DISP_LIST,STR_ID_BRW_OPTIONS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_AUTH_DIALOG_DONE,MENU_ID_BRW_AUTH_DIALOG_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_DONE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_AUTH_DIALOG_SAVE_BOTH,MENU_ID_BRW_AUTH_DIALOG_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SAVE_BOTH,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_AUTH_DIALOG_SAVE_ONLY_USERNAME,MENU_ID_BRW_AUTH_DIALOG_OPTIONS,0,SHOW,NONMOVEABLE,
		DISP_LIST,STR_ID_BRW_SAVE_ONLY_USERNAME,0));
*/
/*Authentication Dialog Options Menu*//*END*/

/*Full Screen Editor Options Menu*//*START*/
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_EDITOR_OPTION,0,3,
		MENU_ID_BRW_EDITOR_OPTION_DONE,
		MENU_ID_BRW_EDITOR_OPTION_CANCEL,
		MENU_ID_BRW_EDITOR_OPTION_INPUT_METHOD,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_OPTION, IMG_GLOBAL_OPTIONS));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_EDITOR_OPTION_DONE, MENU_ID_BRW_EDITOR_OPTION, 0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_DONE, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_EDITOR_OPTION_CANCEL, MENU_ID_BRW_EDITOR_OPTION, 0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_CANCEL, 0));
	ADD_APPLICATION_MENUITEM((MENU_ID_BRW_EDITOR_OPTION_INPUT_METHOD, MENU_ID_BRW_EDITOR_OPTION, 0,
		SHOW, NONMOVEABLE, DISP_LIST, STR_ID_BRW_INPUT_METHOD, 0));
/*Full Screen Editor Options Menu*//*END*/

/* Image ID's Start */
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_HOMEPAGE,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_HOME.pbm","wap menu icon homepage");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_BOOKMARKS,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_BOMK.pbm","wap menu icon bookmark");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_BOOKMARKS_FOLDER_ICON,CUST_IMG_PATH"\\\\MainLCD\\\\FileManager\\\\FM_LIFOLDER.gif","wap menu icon bookmark folder icon");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_BOOKMARKS_DEFAULT_FILE,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\Bookmark\\\\BM_PDefine.pbm","wap menu icon bookmark default file");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_BOOKMARKS_USER_FILE,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\Bookmark\\\\BM_USER.pbm","wap menu icon bookmark user created file");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_ENTER_ADDRESS,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_ETAD.pbm","wap menu icon enter address");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_OPEN_FILE,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_BStorage.pbm","wap menu icon open file");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_LAST_WEB_ADDR,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_BLast.pbm","wap menu icon last web address");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_RECENT_PAGES,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_RTPAGE.pbm","wap menu icon recent pages");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_STORED_PAGES,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_OFLN.pbm","wap menu icon stored pages");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_PUSH_INBOX,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_INBOX.pbm","wap push inbox icon");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_SETTINGS,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_SET.pbm","wap menu icon settings");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_CONNECTION_STATUS_CSD,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\CSD.gif","wap animation CSD");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_CONNECTION_STATUS_GPRS,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\GPRS.gif","wap animation GPRS");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_CONNECTION_STATUS_WIFI,CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\Titlebar\\\\TB_busy.gif","wap animation WIFI");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_CONNECTION_STATUS_CSD_STATIC,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\CSD_C.pbm","wap non animation CSD");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_CONNECTION_STATUS_GPRS_STATIC,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\GPRS_C.pbm","wap non animation GPRS");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_CONNECTION_STATUS_WIFI_STATIC,CUST_IMG_PATH"\\\\MainLCD\\\\WLAN\\\\Titlebar\\\\TB_disconnect.gif","wap non animation WIFI");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_ACTIVE_HMPAGE_SETTINGS,CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\checkbox\\\\CK_V.bmp", "Img Activated Homepage Settings");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_SPLASH_SCREEN,CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\Progress\\\\BroswerLoading.gif", "browser splash screen image");
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_PAGE_OBJECTS,CUST_IMG_PATH"\\\\MainLCD\\\\FileManager\\\\FM_SIWEB.PBM", "browser page objects image");/*using temp image of htm file, it should be changed later*/
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_TRUSTED_CERTS,CUST_IMG_PATH"\\\\MainLCD\\\\FileManager\\\\FM_SIWEB.PBM", "browser trusted certificate image");/*using temp image of htm file, it should be changed later*/
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_DO_ELEMENTS,CUST_IMG_PATH"\\\\MainLCD\\\\FileManager\\\\FM_SIWEB.PBM", "browser do element image");/*using temp image of htm file, it should be changed later*/

	/*Added by Ritesh for push module*//*START*/
	ADD_APPLICATION_IMAGE2(IMG_ID_BRW_PUSH_READ,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_READ.pbm","wap push read message icon");
    ADD_APPLICATION_IMAGE2(IMG_ID_BRW_PUSH_UNREAD,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_UNREAD.pbm","wap push unread message icon");
    ADD_APPLICATION_IMAGE2(IMG_ID_BRW_PUSH_EXPIRED_READ,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_EREAD.pbm","wap push expired read message icon");
    ADD_APPLICATION_IMAGE2(IMG_ID_BRW_PUSH_EXPIRED_UNREAD,CUST_IMG_PATH"\\\\MainLCD\\\\WAP\\\\SW_EUNREAD.pbm","wap push expired unread message icon");
	/*Added by Ritesh for push module*//*END*/
/* Image ID's End */

/* String ID's Start */
	ADD_APPLICATION_STRING2(STR_ID_BRW_INTERNET_SERVICES,"Internet Services","Internet Services screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_HOMEPAGE,"Homepage","Homepage menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_BOOKMARKS,"Bookmarks","Bookmarks title/menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ENTER_ADDRESS,"Enter Address","Enter address Screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_OPEN_FILE,"Open File","Enter address Screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_LAST_WEB_ADDR,"Last Web Address","Enter address Screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_RECENT_PAGES,"Recent Pages","Recent pages screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_RECENT_HOSTS,"Recent Hosts","Recent pages screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_STORED_PAGES,"Stored Pages","Recent pages screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SETTINGS,"Settings","Settings screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_EDIT_PROFILE,"Edit Profile","Edit profile screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_BROWSER_OPTIONS,"Browser Options","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PREFERENCES,"Preferences","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SECURITY_SETTINGS,"Security Settings","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_RESTORE_BROWSER_SETTINGS,"Restore Browser Settings","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_GOTO,"Goto","Goto URL");
	ADD_APPLICATION_STRING2(STR_ID_BRW_EDIT,"Edit","Edit screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SET_AS_HOMEPAGE,"Set As Homepage","Set As Homepage");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ADD_TO_BOOKMARK,"Add To Bookmark","Add To Bookmark");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SEND_ADDRESS,"Send Address","Send Address");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SEND_BOOKMARK,"Send Bookmark","Send Bookmark");
	ADD_APPLICATION_STRING2(STR_ID_BRW_DELETE,"Delete","Delete menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_DELETE_ALL,"Delete All","Delete All menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SORT,"Sort","Sort");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SORT_BY_DATE,"By Date","Delete All menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SORT_BY_SITE,"By Site","Delete All menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SORT_BY_LAST_VISITED,"By Last Visited","Delete All menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SORT_BY_MOST_VISITED,"By Most Visited","Delete All menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_THIS_LINK,"This Link","Delete All menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_NAVIGATE,"Navigate","Delete All menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_THIS_PAGE,"This Page","Delete All menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SELECT_MODE,"Select Mode","Delete All menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PROPERTIES,"Properties","Recent pages screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_RENAME,"Rename","Rename Profile menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_MEMORY_STATUS,"Memory Status","Rename Profile menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_TITLE,"Title","Title menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ADDRESS,"Address","Address menu");

	ADD_APPLICATION_STRING2(STR_ID_BRW_PAGE_SIZE,"Page Size","Delete All menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_DATE,"Date","Recent pages screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_USER_DEFINED,"User Defined","Rename Profile menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ACTIVE_PROFILE,"Active Profile","Rename Profile menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_USE_CURRENT_PAGE,"Use Current Page","Title menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_USE_BLANK,"Use Blank","Address menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_VIEW,"View","View");

	ADD_APPLICATION_STRING2(STR_ID_BRW_ACTIVATE,"Activate","Delete All menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_RENDERING_MODES,"Rendering Modes","Recent pages screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_STANDARD,"Standard","Rename Profile menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_TEXT_WRAP,"Text Wrap","Rename Profile menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SCREEN_OPTIMIZED,"Screen Optimized","Title menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_TEXT_ONLY,"Text Only","Address menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_NAVIGATION_MODES,"Navigation Modes","Exit");

	ADD_APPLICATION_STRING2(STR_ID_BRW_FOUR_WAY,"Four Way","Delete All menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_TWO_WAY,"Two Way","Recent pages screen title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SCROLLING,"Scrolling","Rename Profile menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SCREEN_SIZE,"Screen Size","Rename Profile menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SMALL,"Small","Small");
	ADD_APPLICATION_STRING2(STR_ID_BRW_MEDIUM,"Medium","Medium");
	ADD_APPLICATION_STRING2(STR_ID_BRW_FULL,"Full","Title menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_LARGE,"Large","Large");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ENCODING,"Encoding","Exit");
	ADD_APPLICATION_STRING2(STR_ID_BRW_TRUSTED_CERTIFICATES,"Trusted Certificates","Address menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SAVE_AS,"Save As","Save As");
	ADD_APPLICATION_STRING2(STR_ID_BRW_STORE_OFFLINE,"Store Offline","Save As");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PAGE_OBJECTS,"Page Objects","Save As");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PAGE_PROPERTIES,"Page Properties","Save As");
	ADD_APPLICATION_STRING2(STR_ID_BRW_HOMEPAGE_SETTINGS,"Homepage Settings","Save As");
	ADD_APPLICATION_STRING2(STR_ID_BRW_VIA_INFRARED,"Via Infrared","Send Via Infrared");
	ADD_APPLICATION_STRING2(STR_ID_BRW_VIA_BLUETOOTH,"Via Bluetooth","Send Via Bluetooth");
	ADD_APPLICATION_STRING2(STR_ID_BRW_VIA_EMAIL,"Via Email","Send Via Email");
	ADD_APPLICATION_STRING2(STR_ID_BRW_THUMBNAIL,"Thumbnail","Save As");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SESSION_INFO, "Session Info", "Navigation History Will Be Deleted.\nContinue");
	ADD_APPLICATION_STRING2(STR_ID_BRW_CURRENT_CERTIFICATE, "Current Certificate", "Navigation History Will Be Deleted.\nContinue");
	ADD_APPLICATION_STRING2(STR_ID_BRW_TIMEOUT,"Timeout","Timeout menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SHOW_IMAGES,"Show Images","Show Images menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SHOW_VIDEOS,"Show Videos","Show Images menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PLAY_SOUNDS,"Play Sounds","Timeout menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_LOAD_UNKNOWN_MEDIA,"Load Misc Media","Load Unknown Media");
	ADD_APPLICATION_STRING2(STR_ID_BRW_CSS,"CSS","Show Images menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SCRIPT,"Script","Timeout menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_CACHE,"Cache","Show Images menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_COOKIE,"Cookies	","Show Images menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SHORTCUTS,"Shortcuts","Timeout menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SECURITY_WARNINGS,"Security Warnings","Show Images menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SEND_DEVICE_ID,"Send Device ID","Show Images menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ENABLE,"Enable","Show Images menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_DISABLE,"Disable","Show Images menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ALWAYS,"Always","Show Images menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_NEVER,"Never","Show Images menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_INVAL_TIMEOUT, "Invalid Timeout (15-300)", "Invalid Timeout (15-300)");
	ADD_APPLICATION_STRING2(STR_ID_BRW_NAME,"Name","Show Images menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_CONTENT_SIZE, "Size", "Content Size");
	ADD_APPLICATION_STRING2(STR_ID_BRW_RESTORE_BROWSER_SETTINGS_CONFIRM,"Restore Browser Settings to Default","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_REFRESH,"Refresh","Refresh menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_FORWARD,"Forward","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_BACKWARD,"Backward","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PAGE_ACTIONS,"Page Actions","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ENTER_NAME,"Enter Name","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_OPEN,"Open","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_CLEAR_AUTH_INFO,"Clear Authentication Info","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_CREATE_FOLDER,"Create Folder","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_COPY_TO,"Copy To","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_MOVE_TO,"Move To","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_NORMAL,"Normal","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_IMAGES,"Images","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_BG_IMAGES,"Background Images","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SOUNDS,"Sounds","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_OTHERS,"Others","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_MAKE_CALL, "Call", "TAPI Makecall string");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ADD_ENTRY, "Add To Phonebook", "TAPI Add to phonebook string");
	ADD_APPLICATION_STRING2(STR_ID_BRW_READ_ONLY_PROFILE, "Profile is read only!", "TAPI Add to phonebook string");
	ADD_APPLICATION_STRING2(STR_ID_BRW_INVALID_URL,"Invalid URL","Invalid URL");
	ADD_APPLICATION_STRING2(STR_ID_BRW_NO_HISTORY,"No History Available","History empty");
	ADD_APPLICATION_STRING2(STR_ID_BRW_EXIT,"Exit","Exit");
	ADD_APPLICATION_STRING2(STR_ID_BRW_MODIFY,"Modify","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_INVALID_PARAM,"Invalid Input Parameter","Browser options menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ERROR_COMMUNICATION,"Communication Error","Communication Error");
	ADD_APPLICATION_STRING2(STR_ID_BRW_HOST_NOT_FOUND,"Host Not Found","Host Not Found");
	ADD_APPLICATION_STRING2(STR_ID_BRW_REQUEST_TIMEOUT,"Request Timeout","Request Timeout");
	ADD_APPLICATION_STRING2(STR_ID_BRW_CONNECTION_FAILED,"Connection Failed","Connection Failed");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SECURE_CONNECTION_FAILED,"Secure Connection Failed","Secure Connection Failed");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ERROR_AUTHENTICATION,"Authentication Error","Authentication Error");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SECURE_CONNECTION_CANCELLED,"Secure Connection Cancelled","Secure Connection Cancelled");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PAGE_NOT_FOUND,"Page Not Found","Page Not Found");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PAGE_ALREADY_EXISTS,"Page Already Exists","Saved Page Exists");
	ADD_APPLICATION_STRING2(STR_ID_BRW_REQUEST_FAILED,"Request Failed","Request Failed");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PAGE_SAVED_PARTIALLY,"Page Saved Partially","Page Saved Partially");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PAGE_LIMIT_EXCEEDED,"Page Limit Exceeded","Page Limit Exceeded");
	ADD_APPLICATION_STRING2(STR_ID_BRW_UNSUPPORTED_SCHEME,"Unsupported Scheme","Unsupported Scheme");
	ADD_APPLICATION_STRING2(STR_ID_BRW_UNSUPPORTED_ENCODING,"Unsupported Encoding","Unsupported Encoding");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SYNTAX_ERROR,"Syntax Error","Syntax Error");
	ADD_APPLICATION_STRING2(STR_ID_BRW_UNKNOWN_DOC_TYPE,"Unknown Document Type","Unknown Document Type");
	ADD_APPLICATION_STRING2(STR_ID_BRW_UNSUPPORTED_WBXML,"Unsupported WBXML","Unsupported WBXML");
	ADD_APPLICATION_STRING2(STR_ID_BRW_DOC_VALIDATION_ERROR,"Document Validation Error","Document Validation Error");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PARSER_NOT_INITIALIZED,"Parser Not Initialized","Parser Not Initialized");
	ADD_APPLICATION_STRING2(STR_ID_BRW_INTERNAL_ERROR,"Browser Internal Error","Browser Internal Error");
	ADD_APPLICATION_STRING2(STR_ID_BRW_RESEND_POST_WARNING,"Resend Post Warning","Resend Post Warning");
	ADD_APPLICATION_STRING2(STR_ID_BRW_OUT_OF_MEMORY,"Out Of Memory","Out Of Memory");
	ADD_APPLICATION_STRING2(STR_ID_BRW_CONTENT_TOO_LARGE,"Content Too Large","Content Too Large");
	ADD_APPLICATION_STRING2(STR_ID_BRW_RESET,"Reset","Reset");
	ADD_APPLICATION_STRING2(STR_ID_BRW_INVAL_CHANNEL_ID,"Invalid Channel ID","Reset");
	ADD_APPLICATION_STRING2(STR_ID_BRW_INVAL_REQUEST_ID,"Invalid Request ID","Reset");
	ADD_APPLICATION_STRING2(STR_ID_BRW_INVAL_SEQUENCE_NUM,"Invalid Sequence Number","Reset");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SAVE,"Save","Reset");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SAVE_BOTH,"Save Both","Save Both");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SAVE_ONLY_USERNAME,"Save Only Username","Save Only Username");
	ADD_APPLICATION_STRING2(STR_ID_BRW_DELETE_ALL_FILES,"Delete All Files","Delete All Files");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SAVE_TO_BOOKMARK,"Save To Bookmark","Save To Bookmark");
	ADD_APPLICATION_STRING2(STR_ID_BRW_INVALID_TITLE,"Invalid Title","Empty Title");
	ADD_APPLICATION_STRING2(STR_ID_BRW_FILE_ALREADY_EXISTS,"File Already Exists","File Already Exists");
	ADD_APPLICATION_STRING2(STR_ID_BRW_FOLDER_ALREADY_EXISTS,"Folder Already Exists","Folder Already Exists");
	ADD_APPLICATION_STRING2(STR_ID_BRW_FILE_CREATION_ERROR,"File Creation Error","File Creation Error");
	ADD_APPLICATION_STRING2(STR_ID_BRW_FILENAME_EMPTY,"Empty Filename!","Empty_Filename");	
	ADD_APPLICATION_STRING2(STR_ID_BRW_FILE_SYSTEM_ERROR, "File System Error", "File System Error");
	ADD_APPLICATION_STRING2(STR_ID_BRW_INVALID_BOOKMARK_FILE, "Invalid Bookmark File", "Invalid Bookmark File");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SAVE_NONE, "Save None", "Save None");
	ADD_APPLICATION_STRING2(STR_ID_BRW_FONT_SIZE, "Font Size", "Font Size");
	ADD_APPLICATION_STRING2(STR_ID_BRW_UNSUPPORTED_ACTION,"Unsupported Action","Unsupported Action");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ACTIVATE_PROFILE,"Activate Profile","Activate profile menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ERR_WML_ACCESS_VIOLATION, "WML Access Violation", "WML Access Violation");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ERR_WML_SCRIPT_ACCESS_VIOLATION,"WML Script Access Violation","WML Script Access Violation");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ERROR_LOW_MEMORY,"Large page. Content incompletely shown.","Large page. Content incompletely shown.");
	ADD_APPLICATION_STRING2(STR_ID_BRW_FILE_ALREADY_EXISTS_REPLACE,"File Already Exists.\nReplace?","File Already Exists Replace");
	ADD_APPLICATION_STRING2(STR_ID_BRW_CHARSET_AUTO_SELECT,"Auto-select","Auto Select Charset");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ACCESS_DENIED,"Access Denied","Access Denied");
	ADD_APPLICATION_STRING2(STR_ID_BRW_NOT_FOUND,"Not Found","Not Found");
	ADD_APPLICATION_STRING2(STR_ID_BRW_REQUEST_ABORTED,"Request Aborted","Request Aborted");
	ADD_APPLICATION_STRING2(STR_ID_BRW_NOT_ENOUGH_MEM,"Not Enough Memory","Not Enough Memory");
	ADD_APPLICATION_STRING2(STR_ID_BRW_INPUT_METHOD,"Input Method","Input Method");
	ADD_APPLICATION_STRING2(STR_ID_BRW_DOWNLOADS, "Download List", "Download List");
	ADD_APPLICATION_STRING2(STR_ID_BRW_WAP_NOT_READY, "Wap Not Ready", "Wap Not Ready");
	ADD_APPLICATION_STRING2(STR_ID_BRW_BKGRD_DOWNLOAD_SUSPEND, "Still downloading. Suspend?", "Still downloading. Suspend?");
	ADD_APPLICATION_STRING2(STR_ID_BRW_EMPTY_TRUSTED_CERT_LIST,"No Certificate Found","Save As");

	ADD_APPLICATION_STRING2(STR_ID_BRW_OPTION,"Option","Option screen title ");
	ADD_APPLICATION_STRING2(STR_ID_BRW_EDIT_BOOKMARK,"Edit Bookmark","Edit bookmark screen title ");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ADD_BOOKMARK,"Add Bookmark","Add bookmarks screen title ");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ENCODING_METHODS,"Encoding Methods","Save As");
	ADD_APPLICATION_STRING2(STR_ID_BRW_OPTIONS,"Options","Save As");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SELECT,"Select","Save As");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SAVE_BOOKMARK,"Save Bookmark","Save Bookmark");
	ADD_APPLICATION_STRING2(STR_ID_BRW_DELETE_BOOKMARK,"Delete Bookmark","Delete Bookmark");
	ADD_APPLICATION_STRING2(STR_ID_BRW_DELETE_ALL_BOOKMARK,"Delete All Bookmarks","Delete All Bookmarks");
	ADD_APPLICATION_STRING2(STR_ID_BRW_EMPTY,"Empty","Empty message");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PLEASE_WAIT,"Please Wait!","Please Wait");
	ADD_APPLICATION_STRING2(STR_ID_BRW_AUTHENTICATION,"Authentication","Authentication");
	ADD_APPLICATION_STRING2(STR_ID_BRW_USER_NAME,"User Name","User name menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PASSWORD,"Password","Password menu");
	ADD_APPLICATION_STRING2(STR_ID_BRW_CLEAR_CACHE, "Clear Cache", "Clear Cache");
	ADD_APPLICATION_STRING2(STR_ID_BRW_CLEAR_COOKIE, "Clear Cookies", "Clear Cookies");
	ADD_APPLICATION_STRING2(STR_ID_BRW_TEXT_MESSAGE,"Via Text Message","Send Via Text Message");
	ADD_APPLICATION_STRING2(STR_ID_BRW_MULTIMEDIA_MESSAGE,"Via Multimedia Message","Send Via Multimedia Message");
	ADD_APPLICATION_STRING2(STR_ID_BRW_DONE,"Done","Done");
	ADD_APPLICATION_STRING2(STR_ID_BRW_CANCEL,"Cancel","Cancel");
	ADD_APPLICATION_STRING2(STR_ID_BRW_BYTES,"Bytes","Bytes");
	ADD_APPLICATION_STRING2(STR_ID_BRW_UNKNOWN,"Unknown","Unknown");
	ADD_APPLICATION_STRING2(STR_ID_BRW_FILE_PATH_LEN_EXCEEDED,"Path Length Exceeded","File Path Length Exceeded");
	ADD_APPLICATION_STRING2(STR_ID_BRW_AVAILABLE,"Available","Available");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ALLOCATED,"Allocated","Allocated");
	ADD_APPLICATION_STRING2(STR_ID_BRW_TOTAL,"Total","Total");
	ADD_APPLICATION_STRING2(STR_ID_BRW_KBYTES,"KB","Kilo Bytes");
	ADD_APPLICATION_STRING2(STR_ID_BRW_DIR_PATH_TOO_DEEP,"Path Too Deep","Directory Path Too Deep");
	ADD_APPLICATION_STRING2(STR_ID_BRW_ACTIVATE_JAVA,"Activate JAVA And Terminate Browser?","Activate JAVA And Terminate Browser");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SEND_SMS_TO,"Send SMS To","Send SMS To");
	ADD_APPLICATION_STRING2(STR_ID_BRW_SEND_MMS_TO,"Send MMS To","Send MMS To");
	ADD_APPLICATION_STRING2(STR_ID_BRW_NOT_SUPPORTED,"Not Supported","Not Supported");
/* String ID's End */

/*Added by Ritesh*//*start*/
	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_DATA_ACCOUNT, 0, 2,
			MENU_ID_PROF_DATA_ACCOUNT_PRIMARY,
			MENU_ID_PROF_DATA_ACCOUNT_SECONDARY,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PROF_HDLR_DATA_ACCOUNT, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_DATA_ACCOUNT_PRIMARY, 0, 3,
			MENU_ID_PROF_DATA_ACCOUNT_GSM,
			MENU_ID_PROF_DATA_ACCOUNT_GPRS,
			MENU_ID_PROF_DATA_ACCOUNT_WIFI,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PROF_HDLR_DATA_ACCOUNT_PRIMARY, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_DATA_ACCOUNT_SECONDARY, 0, 4,
			MENU_ID_PROF_DATA_ACCOUNT_GSM,
			MENU_ID_PROF_DATA_ACCOUNT_GPRS,
			MENU_ID_PROF_DATA_ACCOUNT_WIFI,
			MENU_ID_PROF_DATA_ACCOUNT_NONE,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PROF_HDLR_DATA_ACCOUNT_SECONDARY, 0));


	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_CONNECTION_TYPE, 0, 2,
			MENU_ID_PROF_CONN_TYPE_CONNECTION,
			MENU_ID_PROF_CONN_TYPE_HTTP,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PROF_HDLR_CONN_TYPE, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_DATA_ACCOUNT_GSM,MENU_ID_PROF_DATA_ACCOUNT_PRIMARY,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_DATA_ACCOUNT_BEARER_GSM,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_DATA_ACCOUNT_GPRS,MENU_ID_PROF_DATA_ACCOUNT_PRIMARY,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_DATA_ACCOUNT_BEARER_GPRS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_DATA_ACCOUNT_WIFI,MENU_ID_PROF_DATA_ACCOUNT_PRIMARY,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_DATA_ACCOUNT_BEARER_WIFI,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_DATA_ACCOUNT_NONE,MENU_ID_PROF_DATA_ACCOUNT_SECONDARY,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_DATA_ACCOUNT_BEARER_NONE,0));


	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_CONN_TYPE_CONNECTION,MENU_ID_PROF_CONNECTION_TYPE,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_CONN_TYPE_WAP,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_CONN_TYPE_HTTP,MENU_ID_PROF_CONNECTION_TYPE,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_CONN_TYPE_HTTP,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_SELECT_PROFILE, 0, 3,
			MENU_ID_PROF_SELECT_PROFILE_ACTIVATE,
			MENU_ID_PROF_SELECT_PROFILE_EDIT,
			MENU_ID_PROF_SELECT_PROFILE_DELETE,
			SHOW, NONMOVEABLE, DISP_LIST, 0, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_SELECT_PROFILE_ACTIVATE,MENU_ID_PROF_SELECT_PROFILE,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_ACTIVATE_PROFILE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_SELECT_PROFILE_EDIT,MENU_ID_PROF_SELECT_PROFILE,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_EDIT_PROFILE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_SELECT_PROFILE_DELETE,MENU_ID_PROF_SELECT_PROFILE,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_DELETE_PROFILE,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_SELECT_DEFAULT_PROFILE, 0, 2,
			MENU_ID_PROF_SELECT_PROFILE_ACTIVATE,
			MENU_ID_PROF_SELECT_PROFILE_VIEW_ONLY,
			SHOW, NONMOVEABLE, DISP_LIST, 0, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PROF_SELECT_PROFILE_VIEW_ONLY,MENU_ID_PROF_SELECT_DEFAULT_PROFILE,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PROF_HDLR_VIEW_PROFILE,0));


	ADD_APPLICATION_IMAGE2(IMG_ID_PROF_HDLR_SET_ACTIVATED_PROFILE,CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\checkbox\\\\CK_V.bmp", "Img Activated profile ");

	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_SELECT_PROF_CAPTION ,"Select Profile","Select Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_ACTIVATE_PROFILE ,"Activate Profile","Activate Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_EDIT_PROFILE ,"Edit Profile","Edit Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_VIEW_PROFILE ,"View Profile","View Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_DELETE_PROFILE ,"Delete Profile","Delete Profile");

	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_RENAME_PROFILE ,"Rename Profile","Rename Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_HOMEPAGE ,"Homepage","Homepage");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_MMSC_URL ,"MMSC Url","MMSC Url");

	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_DATA_ACCOUNT ,"Data Account","Data Account");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_CONN_TYPE ,"Connection Type","Connection Type");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_USER_NAME ,"User Name","User Name");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_PASSWORD ,"Password","Password");

	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_DATA_ACCOUNT_PRIMARY ,"Primary","Primary");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_DATA_ACCOUNT_SECONDARY ,"Secondary","Secondary");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_DATA_ACCOUNT_BEARER_GSM ,"GSM","GSM");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_DATA_ACCOUNT_BEARER_GPRS ,"GPRS","GPRS");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_DATA_ACCOUNT_BEARER_WIFI ,"Wireless LAN","Wireless LAN");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_DATA_ACCOUNT_BEARER_NONE ,"NONE","NONE");

	//ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_SAVED ,"Saved","Saved");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_CONN_TYPE_WAP ,"WAP","WAP");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_CONN_TYPE_HTTP ,"HTTP","HTTP");
	//ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_CONN_TYPE_WIFI ,"WIFI","WIFI");


	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_IP_ADDRESS ,"IP Address","IP Address");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_PROXY_ADDRESS ,"Proxy Address","Proxy Address");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_SECURITY ,"Security","Security");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_PORT ,"Proxy Port","Proxy Port");

	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_OFF ,"Off","Off");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_ON ,"On","On");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_PROFILE ,"Profile","Profile");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_INVALID_INPUT ,"Invalid Input","Invalid Input");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_INVALID_IP ,"Invalid IP Address","Invalid IP Address");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_DATA_ACCOUNT_ERROR ,"Invalid Setting","Invalid Setting");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_INVALID_URL_ERROR ,"Invalid Url","Invalid Url");
	ADD_APPLICATION_STRING2(STR_ID_PROV_HDLR_PERMISSION_DENIED ,"Permission Denied","Permission Denied");

/******** PUSH MODULE MENU ITEM AND STRING EDITION ***********/

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_INBOX,0,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SETTING, 0, 4,
			MENU_ID_PUSH_ENABLE,
			MENU_ID_PUSH_TRUST_SETTING,
			MENU_ID_PUSH_SL_SETTING,
			MENU_ID_PUSH_TRUST_LIST,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PUSH_INBOX_SETTING, 0));


	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_LIST,MENU_ID_PUSH_SETTING,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_TRUSTED_LIST,0));


	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_ENABLE, 0, 2,
			MENU_ID_PUSH_ENABLE_ON,
			MENU_ID_PUSH_ENABLE_OFF,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PUSH_INBOX_ENABLE_PUSH, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_ENABLE_ON,MENU_ID_PUSH_ENABLE,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_ENABLE_ON,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_ENABLE_OFF,MENU_ID_PUSH_ENABLE,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_ENABLE_OFF,0));


	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_SETTING, 0, 2,
			MENU_ID_PUSH_TRUST_SETTING_DISABLE,
			MENU_ID_PUSH_TRUST_SETTING_ALWAYS,
		/*	MENU_ID_PUSH_TRUST_SETTING_ALWAYS_ASK,*/
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PUSH_INBOX_TRUST_SETTING, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_SETTING_DISABLE,MENU_ID_PUSH_TRUST_SETTING,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_TRUST_LIST_DISABLE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_SETTING_ALWAYS,MENU_ID_PUSH_TRUST_SETTING,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_TRUST_LIST_ALWAYS,0));
	//ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_SETTING_ALWAYS_ASK,MENU_ID_PUSH_TRUST_SETTING,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_TRUST_LIST_ALWAYS_ASK,0));


	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SL_SETTING, 0, 3,
			MENU_ID_PUSH_SL_SETTING_NEVER,
			MENU_ID_PUSH_SL_SETTING_CONFIRM,
			MENU_ID_PUSH_SL_SETTING_WITHOUT_CONFIRM,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PUSH_INBOX_SL_SETTING, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SL_SETTING_NEVER,MENU_ID_PUSH_SL_SETTING,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SL_SETTING_NEVER,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SL_SETTING_CONFIRM,MENU_ID_PUSH_SL_SETTING,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SL_SETTING_CONFIRM,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SL_SETTING_WITHOUT_CONFIRM,MENU_ID_PUSH_SL_SETTING,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SL_SETTING_WITHOUT_CONFIRM,0));


	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_ADD_NEW, 0, 3,
			MENU_ID_PUSH_TRUST_LIST_PHONE_NO,
			MENU_ID_PUSH_TRUST_LIST_IP_ADDRESS,
			MENU_ID_PUSH_TRUST_LIST_DOMAIN_NAME,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PUSH_INBOX_ADD_NEW, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_LIST_PHONE_NO,MENU_ID_PUSH_TRUST_ADD_NEW,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_TRUST_LIST_PHONE_NUMBER,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_LIST_IP_ADDRESS,MENU_ID_PUSH_TRUST_ADD_NEW,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_TRUST_LIST_IP_ADDRESS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_LIST_DOMAIN_NAME,MENU_ID_PUSH_TRUST_ADD_NEW,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_TRUST_LIST_DOMAIN_NAME,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_SELECT_ADDR, 0, 3,
			MENU_ID_PUSH_TRUST_LIST_MODIFY,
			MENU_ID_PUSH_TRUST_LIST_DELETE,
			MENU_ID_PUSH_TRUST_LIST_DELETE_ALL,
			SHOW, NONMOVEABLE, DISP_LIST, 0, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_LIST_MODIFY,MENU_ID_PUSH_TRUST_SELECT_ADDR,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_TRUST_LIST_MODIFY,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_LIST_DELETE,MENU_ID_PUSH_TRUST_SELECT_ADDR,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_TRUST_LIST_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_TRUST_LIST_DELETE_ALL,MENU_ID_PUSH_TRUST_SELECT_ADDR,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_TRUST_LIST_DELETE_ALL,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_INBOX_OPTION, 0, 3,
			MENU_ID_PUSH_SERVICE_MSG_READ,
			MENU_ID_PUSH_UM_COMPILE_OPTION_MSG_DELETE,
			MENU_ID_PUSH_SERVICE_MSG_DELETE_ALL,
			SHOW, NONMOVEABLE, DISP_LIST, 0, 0));


	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_READ,MENU_ID_PUSH_INBOX_OPTION,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_READ,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_UM_COMPILE_OPTION_MSG_DELETE,MENU_ID_PUSH_INBOX_OPTION,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_DELETE_ALL,MENU_ID_PUSH_INBOX_OPTION,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE_ALL,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_MESSAGE_OPTION_1, 0,
#ifdef __MMI_VBOOKMARK__
			6,
#else
			5,
#endif
			MENU_ID_PUSH_SERVICE_MSG_GOTO,
			MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST,
			MENU_ID_PUSH_SERVICE_MSG_ADD_HOMEPAGE,
#ifdef __MMI_VBOOKMARK__
			MENU_ID_PUSH_SERVICE_MSG_ADD_BOOKMARK,
#endif
			MENU_ID_PUSH_SERVICE_MSG_SEND_BY,
			MENU_ID_PUSH_SERVICE_MSG_DELETE,
			SHOW, NONMOVEABLE, DISP_LIST, 0, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_DELETE,MENU_ID_PUSH_MESSAGE_OPTION_1,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_GOTO,MENU_ID_PUSH_MESSAGE_OPTION_1,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_GOTO,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST,MENU_ID_PUSH_MESSAGE_OPTION_1,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_TO_TRUST_LIST,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_HOMEPAGE,MENU_ID_PUSH_MESSAGE_OPTION_1,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_HOMEPAGE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_BOOKMARK,MENU_ID_PUSH_MESSAGE_OPTION_1,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_BOOKMARK,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_SEND_BY, 0, 3,
			MENU_ID_PUSH_SERVICE_MSG_SEND_BY_EMAIL,
			MENU_ID_PUSH_SERVICE_MSG_SEND_BY_SMS,
			MENU_ID_PUSH_SERVICE_MSG_SEND_BY_MMS,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY, 0));

		ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_MESSAGE_OPTION_ISINCALL_1, 0, 
#ifdef __MMI_VBOOKMARK__
			5,
#else
			4,
#endif
			MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST,
			MENU_ID_PUSH_SERVICE_MSG_ADD_HOMEPAGE,
#ifdef __MMI_VBOOKMARK__
			MENU_ID_PUSH_SERVICE_MSG_ADD_BOOKMARK,
#endif
			MENU_ID_PUSH_SERVICE_MSG_SEND_BY,
			MENU_ID_PUSH_SERVICE_MSG_DELETE,
			SHOW, NONMOVEABLE, DISP_LIST, 0, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_DELETE,MENU_ID_PUSH_MESSAGE_OPTION_ISINCALL_1,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST,MENU_ID_PUSH_MESSAGE_OPTION_ISINCALL_1,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_TO_TRUST_LIST,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_HOMEPAGE,MENU_ID_PUSH_MESSAGE_OPTION_ISINCALL_1,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_HOMEPAGE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_BOOKMARK,MENU_ID_PUSH_MESSAGE_OPTION_ISINCALL_1,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_BOOKMARK,0));


	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_MESSAGE_OPTION_2, 0,
#ifdef __MMI_VBOOKMARK__
			7,
#else
			6,
#endif
			MENU_ID_PUSH_SERVICE_MSG_GOTO,
			MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST,
			MENU_ID_PUSH_SERVICE_MSG_ADD_HOMEPAGE,
#ifdef __MMI_VBOOKMARK__
			MENU_ID_PUSH_SERVICE_MSG_ADD_BOOKMARK,
#endif
			MENU_ID_PUSH_SERVICE_MSG_SEND_BY,
			MENU_ID_PUSH_SERVICE_MSG_DELETE,
			MENU_ID_PUSH_SERVICE_MSG_DELETE_ALL,
			SHOW, NONMOVEABLE, DISP_LIST, 0, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_DELETE,MENU_ID_PUSH_MESSAGE_OPTION_2,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_GOTO,MENU_ID_PUSH_MESSAGE_OPTION_2,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_GOTO,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST,MENU_ID_PUSH_MESSAGE_OPTION_2,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_TO_TRUST_LIST,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_HOMEPAGE,MENU_ID_PUSH_MESSAGE_OPTION_2,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_HOMEPAGE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_BOOKMARK,MENU_ID_PUSH_MESSAGE_OPTION_2,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_BOOKMARK,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_DELETE_ALL,MENU_ID_PUSH_MESSAGE_OPTION_2,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE_ALL,0));

ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_MESSAGE_OPTION_ISINCALL_2, 0, 
#ifdef __MMI_VBOOKMARK__
			6,
#else
			5,
#endif
			MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST,
			MENU_ID_PUSH_SERVICE_MSG_ADD_HOMEPAGE,
#ifdef __MMI_VBOOKMARK__
			MENU_ID_PUSH_SERVICE_MSG_ADD_BOOKMARK,
#endif
			MENU_ID_PUSH_SERVICE_MSG_SEND_BY,
			MENU_ID_PUSH_SERVICE_MSG_DELETE,
			MENU_ID_PUSH_SERVICE_MSG_DELETE_ALL,
			SHOW, NONMOVEABLE, DISP_LIST, 0, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_DELETE,MENU_ID_PUSH_MESSAGE_OPTION_ISINCALL_2,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST,MENU_ID_PUSH_MESSAGE_OPTION_ISINCALL_2,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_TO_TRUST_LIST,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_HOMEPAGE,MENU_ID_PUSH_MESSAGE_OPTION_ISINCALL_2,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_HOMEPAGE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_BOOKMARK,MENU_ID_PUSH_MESSAGE_OPTION_ISINCALL_2,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_BOOKMARK,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_DELETE_ALL,MENU_ID_PUSH_MESSAGE_OPTION_ISINCALL_2,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE_ALL,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_MESSAGE_OPTION_3, 0, 3,
			MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST,
			MENU_ID_PUSH_SERVICE_MSG_SEND_BY,
			MENU_ID_PUSH_SERVICE_MSG_DELETE,
			SHOW, NONMOVEABLE, DISP_LIST, 0, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST,MENU_ID_PUSH_MESSAGE_OPTION_3,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_TO_TRUST_LIST,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_DELETE,MENU_ID_PUSH_MESSAGE_OPTION_3,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE,0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_MESSAGE_OPTION_4, 0, 4,
			MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST,
			MENU_ID_PUSH_SERVICE_MSG_SEND_BY,
			MENU_ID_PUSH_SERVICE_MSG_DELETE,
			MENU_ID_PUSH_SERVICE_MSG_DELETE_ALL,
			SHOW, NONMOVEABLE, DISP_LIST, 0, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_ADD_TO_TRUST_LIST,MENU_ID_PUSH_MESSAGE_OPTION_4,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_ADD_TO_TRUST_LIST,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_DELETE,MENU_ID_PUSH_MESSAGE_OPTION_4,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_DELETE_ALL,MENU_ID_PUSH_MESSAGE_OPTION_4,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE_ALL,0));


	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_SEND_BY, 0, 3,
			MENU_ID_PUSH_SERVICE_MSG_SEND_BY_EMAIL,
			MENU_ID_PUSH_SERVICE_MSG_SEND_BY_SMS,
			MENU_ID_PUSH_SERVICE_MSG_SEND_BY_MMS,
			SHOW, NONMOVEABLE, DISP_LIST, STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY, 0));

	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_SEND_BY_EMAIL,MENU_ID_PUSH_SERVICE_MSG_SEND_BY,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY_EMAIL,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_SEND_BY_SMS,MENU_ID_PUSH_SERVICE_MSG_SEND_BY,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY_SMS,0));
	ADD_APPLICATION_MENUITEM((MENU_ID_PUSH_SERVICE_MSG_SEND_BY_MMS,MENU_ID_PUSH_SERVICE_MSG_SEND_BY,0,SHOW,NONMOVEABLE,DISP_LIST,STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY_MMS,0));

	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX,"Service Inbox","Service Inbox");

	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SETTING ,"Service Message Setting","Service Message Setting");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_ENABLE_PUSH ,"Enable Push","Enable Push");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SL_SETTING ,"SL Setting","SL Setting");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_TRUST_SETTING ,"Trust Setting","Trust Setting");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_TRUSTED_LIST ,"Trust List","trust List");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_ENABLE_ON ,"On","On");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_ENABLE_OFF ,"Off","Off");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_ADD_NEW ,"Add New","Add New");



    ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_TRUST_LIST_DISABLE,"Disable","Disable");
    ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_TRUST_LIST_ALWAYS,"Always","Always Ask");
    ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_TRUST_LIST_ALWAYS_ASK,"Always Ask","Always Ask");

	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_TRUST_LIST_MODIFY,"Modify","modify");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_TRUST_LIST_DELETE,"Delete","Delete");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_TRUST_LIST_DELETE_ALL,"Delete All","Delete All");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_TRUST_LIST_PHONE_NUMBER,"SC Address","SC Address");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_TRUST_LIST_IP_ADDRESS,"IP Address","IP Address");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_TRUST_LIST_DOMAIN_NAME,"Domain Name","Domain Name");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SL_SETTING,"SL Setting","SL Setting");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SL_SETTING_NEVER,"Never","Never");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SL_SETTING_CONFIRM,"Confirm","Confirm");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SL_SETTING_WITHOUT_CONFIRM,"Without Confirm","Without Confirm");
    ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SERVICE_MESSAGE_READ,"Read","Read");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE,"Delete","Delete");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SERVICE_MESSAGE_DELETE_ALL,"Delete All","Delete All");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SERVICE_MESSAGE_GOTO,"GoTo","GoTo");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_ADD_TO_TRUST_LIST,"Add To Trust List","Add To Trust List");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_ADD_HOMEPAGE,"Add Homepage","Add Homepage");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_ADD_BOOKMARK,"Add Bookmark","Add Bookmark");
	//ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SERVICE_MESSAGE_INFO,"Info","Info");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY,"Send By","Send By");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY_EMAIL,"Email","Email");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY_SMS,"SMS","SMS");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_SERVICE_MESSAGE_SEND_BY_MMS,"MMS","MMS");

	ADD_APPLICATION_STRING2(STR_ID_PUSH_SERVICE_MESSAGE_RCVD,"New Service Message","New Service Message");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PUSH_CREATED_TIME,"Created Time","Created Time");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PUSH_EXPIRY_TIME,"Expiry Time","Expiry Time");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PUSH_PRIORITY,"Priority","Priority");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PUSH_PRIORITY_LOW,"Low","Low");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PUSH_PRIORITY_MEDIUM,"Medium","Medium");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PUSH_PRIORITY_HIGH,"High","High");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_MSG_NOT_AVAILABLE,"Message Not Available","Message Not Available");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_VALIDATION_FAIL_NEW_MSG,"Invalid Message","Invalid Message");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_MESSAGE,"Message","Message");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_URL,"Url","Url");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_TRUST_LIST_FULL,"Trust List Full","Trust List Full");
	ADD_APPLICATION_STRING2(STR_ID_BRW_NEW_PUSH_MESSAGE,"New Service Message","New Service Message");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_MODIFIED,"Inbox Modified","Inbox Modified");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_SETTING_INVALID_ENTRY,"Invalid Entry","Invalid Entry");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_EMPTY,"Empty","Empty");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_MSG_LOADING,"Loading","Loading");

	ADD_APPLICATION_STRING2(STR_ID_BRW_PUSH_VALIDATION_ADDR,"Validation Address","Validation Address:");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PUSH_SENDER_ADDR,"Sender Address","Sender Address:");
	ADD_APPLICATION_STRING2(STR_ID_BRW_PUSH_MESSAGE_EXPIRED,"Message Expired","Message Expired");
	ADD_APPLICATION_STRING2(STR_ID_PROF_HDLR_ADD_NEW,"Add New","Add New");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_STORAGE_FULL,"Push Storage Full","Push Storage Full");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INVALID_SIM,"Invalid SIM","Invalid SIM");
//	ADD_APPLICATION_STRING2(STR_ID_PUSH_USB_PLUGGED_IN,"USB MODE","USB MODE");
	ADD_APPLICATION_STRING2(STR_ID_BRW_NEW_MESSAGE,"New Message","New Message");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_INBOX_TRUST_LIST_ADD_NEW, "Add New", "Add New");
	ADD_APPLICATION_STRING2(STR_ID_PUSH_SAME_ITEM_EXIST, "Same item exist", "Same item exist");

/*Added by Ritesh*//*End*/
}
#endif /* __MMI_BROWSER_2__ */

#endif /* DEVELOPER_BUILD_FIRST_PASS */

