/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2005
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/
#include "MMI_features.h" 

#include "CustomCfg.h"


#ifdef FIRST_PASS
#include "BuildCfg.h"
#endif

#include "FunAndGamesResDef.h"

#ifdef DEVELOPER_BUILD_FIRST_PASS
#include "PopulateRes.h"

#ifdef __MMI_BI_DEGREE_MAIN_MENU_STYLE__
#include "MainMenuDef.h"
#endif
#include "AudioPlayerResDef.h"
void populateAudioPlayerMenu(void)
{
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_TITLE, "Audio Player", "Audio Player String" );

	// error message strings
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_LIST_FULL, "List Full", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_OPEN_FILE_ERROR, "Can't Open", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_NO_CARD, "No Card", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_COMMAND_ERROR, "Failed To Play", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DEVICE_BUSY, "Device Busy", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_BAD_FORMAT, "Bad Format", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_INVALID_FORMAT, "Invalid Format", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_NO_SPACE, "Exceed File Limit", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_ERROR, "Audio Content Error", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_UNSUPPORTED_CHANNEL, "Unsupported Channel", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_UNSUPPORTED_FREQ, "Unsupported Frequency", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_UNSUPPORTED_TYPE, "Unsupported Type", "Audio Player String" );
  	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_NO_AUDIO_TRACK, "No Audio Track", "Audio Player String" );
  	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DECODER_NOT_SUPPORT, "Audio Content Not Support", "Audio Player String" );

	/* play animation gif */
#ifdef __MMI_SLIM_PROGRESS_ANIMATION__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_PLAY_ANIMATION, CUST_IMG_PATH"\\\\MainLCD\\\\UIElement\\\\Progress\\\\PROGRESS.gif", "shared progress image" );
#else
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_PLAY_ANIMATION, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\PLAY\\\\AP_PLAY_ANIMATION.gif", "audio player image" );
#endif
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_STOP_ANIMATION, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\PLAY\\\\AP_STOP_ANIMATION.gif", "audio player image" );
	
#ifdef __MMI_AUDIO_PLAYER__
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_LIST, "List", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_PLAYLIST, "Play List", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_LIST_FROM_PHONE, "From Phone", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_LIST_FROM_CARD, "From Card", "Audio Player String" );

#if defined(MT6223) || defined(MT6223P)
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_NOT_SUPPORT_A2DP, "File Type Not Support A2DP", "Audio Player String" );
#endif    
	// options
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_OPTION_PLAY, "Play", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_OPTION_ADD, "Add", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_OPTION_DETAIL, "Detail", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_OPTION_ADD_TO_RINGS, "Add To Rings", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_OPTION_REMOVE, "Remove", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_OPTION_REMOVE_ALL, "Remove All", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_OPTION_REMOVE_ASK, "Remove?", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_OPTION_REMOVE_ALL_ASK, "Remove All?", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_OPTION_REGEN_LIST, "Refresh List", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_OPTION_SETTINGS, "Settings", "Audio Player String" );
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_PLAYER_SETTINGS, "Player Settings", "Audio Player String" );
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DISPLAY_SETTINGS, "Display Settings", "Audio Player String" );
#if defined(__MMI_AUDIO_EQUALIZER__) || defined(__MMI_AUDIO_TIME_STRETCH__) || defined(__MMI_AUDIO_REVERB_EFFECT__) || defined(__MMI_AUDIO_SURROUND_EFFECT__)
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SOUND_EFFECT_SETTINGS, "Sound Effects", "Audio Player String" );
#endif
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_BLUETOOTH_SETTINGS, "Bluetooth Settings", "Audio Player String" );
#ifndef __MMI_SLIM_AUDIO_PLAYER__
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_SKIN1, "Skin1", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_SKIN2, "Skin2", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_SKIN3, "Skin3", "Audio Player String" );
#endif
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_ON, "On", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_OFF, "Off", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_ONE, "One", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_ALL, "All", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_LIST_AUTO_GEN, "List Auto Gen", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_PREFER_LIST, "Pre. Play List", "Audio Player String" );
#ifndef __MMI_SLIM_AUDIO_PLAYER__
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_SKIN, "Skin", "Audio Player String" );
#endif
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_REPEAT, "Repeat", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_SHUFFLE, "Shuffle", "Audio Player String" );
#ifndef __MMI_AUDIO_PLAYER_ON_SUBLCD__
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_BACKGROUND_PLAY, "Background Play", "Audio Player String" );
#endif
#ifdef __MMI_AUDIO_SPECTRUM_DISPLAY__
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_SPECTRUM_DISPLAY_STYLE, "Spectrum Display", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_SPECTRUM_DISPLAY_STYLE_1, "Style 1", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_SPECTRUM_DISPLAY_STYLE_2, "Style 2", "Audio Player String" );
#endif // __MMI_AUDIO_SPECTRUM_DISPLAY__
#ifdef __MMI_AUDIO_PLAYER_LYRIC_DISPLAY__
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_LYRICS_DISPLAY, "Lyrics Display", "Audio Player String" );
#endif
#ifdef __MMI_AUDIO_PLAYER_A2DP_BLOCK_SPECTRUM__
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_A2DP_BLOCK_SPECTRUM, "Spectrum is Blocked", "Audio Player String" );
#endif
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_BT_A2DP_OUTPUT, "BT Stereo Output", "Audio Player String" );
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_BT_A2DP_HEADSET, "BT Stereo Headset", "Audio Player String" );
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_ERR_MUST_SELECT_HEADSET, "Must Select a Headset", "Audio Player String" );
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_ERR_CANNOT_USE_BLUETOOTH_IN_FLIGHT_MODE, "Can't Use Bluetooth in Flight Mode", "Audio Player String" );

	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DETAIL_TIME, "Time", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DETAIL_SIZE, "Size", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DETAIL_TITLE, "Title", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DETAIL_ARTIST, "Artist", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DETAIL_ALBUM, "Album", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DETAIL_GENRE, "Genre", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DETAIL_YEAR, "Year", "Audio Player String" );
#ifdef __MMI_AUDIO_PLAYER_DETAIL_SHOW_MORE_INFO__
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DETAIL_CHANNEL, "Channel", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DETAIL_QUALITY, "Quality", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DETAIL_MONO, "Mono", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_DETAIL_STEREO, "Stereo", "Audio Player String" );
#endif
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_FILENAME_TOO_LONG, "Filename Too Long", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_RING_TONGS_FULL, "Ring Slots Full", "Audio Player String" );
	
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_CANNOT_UPDATE_LIST_DISK_FULL, "Can't Update List: Disk Full", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_CANNOT_UPDATE_LIST_FS_FAIL, "Can't Update List: Access File Fail", "Audio Player String" );
    
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_LIST_EMPTY, "<Empty>", "Audio Player String" );
	
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_PROCESSING, "Processing", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_FILE_IN_DIFFERENT_STORAGE, "File in Different Storage", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_CANNOT_PAUSE, "Can't Pause", "Audio Player String" );
#if defined(__MMI_A2DP_SUPPORT__) && defined(__MMI_AUDIO_EQUALIZER__)
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_A2DP_BLOCK_EQUALIZER, "Equalizer is Blocked", "Audio Player String" );
#endif
#if defined(__MMI_A2DP_SUPPORT__) && defined(__MMI_AUDIO_EQUALIZER__) && defined(__MMI_AUDIO_PLAYER_A2DP_BLOCK_SPECTRUM__)
        ADD_APPLICATION_STRING2( STR_ID_AUDPLY_A2DP_BLOCK_EQUALIZER_SPCTRUM, "Equalizer and Spectrum are Blocked", "Audio Player String" );
#endif
#if defined(__MMI_BT_MTK_SUPPORT__) && defined(__MMI_A2DP_SUPPORT__)
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SAP_BLOCK_A2DP, "SIM Access Profile Turned on", "Audio Player String" );
#endif
    ADD_APPLICATION_STRING2( STR_ID_AUDPLY_STOP_FMR, "Turn off FM Radio?", "Audio Player String" );

/* level 1 */
#ifdef __MMI_BI_DEGREE_MAIN_MENU_STYLE__
	ADD_APPLICATION_MENUITEM((AUDIO_PLAYER_MAIN_MENUID, MAIN_MENU_AVZONE_MENU_ID, 0,
		SHOW, NONMOVEABLE | SHORTCUTABLE, 0, MAIN_MENU_AUDPLY_TEXT, MAIN_MENU_AUDPLY_ICON));

	ADD_APPLICATION_MENUITEM((MAIN_MENU_OPTION_AUDIO_PLAYER_APP, MAIN_MENU_OPTION_AVZONE_MENUID, 0,
		SHOW, MOVEABLEACROSSPARENT | SHORTCUTABLE, 0, STR_ID_AUDPLY_TITLE, IMG_ID_AUDPLY_ICON ));

#else
	ADD_APPLICATION_MENUITEM((AUDIO_PLAYER_MAIN_MENUID, MAIN_MENU_MULTIMEDIA_MENUID, 0,
		SHOW, MOVEABLEACROSSPARENT | SHORTCUTABLE, 0, STR_ID_AUDPLY_TITLE, IMG_ID_AUDPLY_ICON ));
#endif		
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SB_AudioPlayer.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SETTINGS_LIST_AUTO_GEN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_AUTO_GEN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SETTINGS_PREFER_LIST, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_PREFER_LIST.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SETTINGS_SKIN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_SKIN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SETTINGS_REPEAT, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_REPEAT.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SETTINGS_SHUFFLE, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_SHUFFLE.pbm", "audio player image" );
#ifndef __MMI_AUDIO_PLAYER_ON_SUBLCD__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SETTINGS_BACKGROUND_PLAY, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_BGPlay.pbm", "audio player image" );
#endif
#ifdef __MMI_AUDIO_SPECTRUM_DISPLAY__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SETTINGS_SPECTRUM_DISPLAY_STYLE, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_SPECTRUM.pbm", "audio player image" );
#endif // __MMI_AUDIO_SPECTRUM_DISPLAY__
#ifdef __MMI_AUDIO_PLAYER_LYRIC_DISPLAY__
    ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SETTINGS_LYRICS_DISPLAY_STYLE, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_WORDS.pbm", "audio player image" );
#endif // __MMI_AUDIO_PLAYER_LYRIC_DISPLAY__
	/* detail */
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_DETAIL_FILE, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_SIZE.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_DETAIL_TIME, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_TIME.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_DETAIL_TITLE, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_TITLE.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_DETAIL_ARTIST, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_ALBUM.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_DETAIL_ALBUM, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_ARTIST.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_DETAIL_GENRE, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_GENRE.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_DETAIL_YEAR, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_YEAR.pbm", "audio player image" );
#ifdef __MMI_AUDIO_PLAYER_DETAIL_SHOW_MORE_INFO__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_DETAIL_FILENAME, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILENAME.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_DETAIL_CHANNEL, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_CHANNEL.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_DETAIL_QUALITY, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_QUALITY.pbm", "audio player image" );
#endif	
	/* audio file types */
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_WAV_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_WAV.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_AMR_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_AMR.pbm", "audio player image" );
#ifdef AAC_DECODE
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_AAC_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_AAC.pbm", "audio player image" );
#endif
#ifdef DAF_DECODE
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_AUD_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_AUD.pbm", "audio player image" );
#endif
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_MID_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_MID.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_IMY_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_IMY.pbm", "audio player image" );
#ifdef AMRWB_DECODE
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_AWB_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_AWB.pbm", "audio player image" );
#endif
#ifdef AIFF_DECODE
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_AIF_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_AIF.pbm", "audio player image" );
#endif
#ifdef AU_DECODE
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_AU_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_AU.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_SND_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_SND.pbm", "audio player image" );
#endif
#ifdef AAC_DECODE
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_M4A_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_M4A.pbm", "audio player image" );
#endif
#ifdef YAMAHA_MA3
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_MMF_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_MMF.pbm", "audio player image" );
#endif
#ifdef WMA_DECODE
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_WMA_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_WMA.pbm", "audio player image" );
#endif

#if defined(__MMI_PURE_AUDIO__)
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_3GP_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_3GP.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_MP4_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_FILE_MP4.pbm", "audio player image" );   
#endif

    ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_FILE_UNKNOWN_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_unknown.pbm", "audio player image" );

#ifdef __MMI_RESOURCE_ENFB_SUPPORT__
    SetENFBAssociatedID();
#endif
	/* skin 1 */
/*#ifdef __MMI_MAINLCD_320X240__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_BG, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN.jpg", "audio player image" );
#else*/
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_BG, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN.gif", "audio player image" );
/*#endif*/
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PLAYLIST_PHONE_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PLAYLIST_PHONE.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PLAYLIST_CARD_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PLAYLIST_CARD.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_VOLUME_INDICATOR, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_VOLUME_IND.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PROGRESSBAR, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PROGRESS_FILL.pbm", "audio player image" );    
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PROGRESSBAR_FAIL, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PROGRESS_FAIL.pbm", "audio player image" );        
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PREV_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PREV_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PREV_OFF, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PREV_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PREV_DISABLED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PREV_DISABLED.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PREV_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PREV_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_NEXT_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_NEXT_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_NEXT_OFF, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_NEXT_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_NEXT_DISABLED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_NEXT_DISABLED.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_NEXT_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_NEXT_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PLAY_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PAUSE_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PLAY_OFF, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PLAY_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PLAY_DISABLED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PLAY_DISABLED.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PLAY_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PLAY_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PAUSE_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PLAY_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_PAUSE_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_PAUSE_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_STOP_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_STOP_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_STOP_OFF, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_STOP_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_STOP_DISABLED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_STOP_DISABLED.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_STOP_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_STOP_DOWN.pbm", "audio player image" );
#ifdef __MMI_AUDIO_PLAYER_ANIMATION__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_ANIMATION, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_ANIMATION.gif", "audio player image" );
#endif
#ifdef __MMI_AUDIO_PLAYER_SKIN_SHOW_REPEAT_SHUFFLE__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_REPEAT_OFF_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_REPEAT_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_REPEAT_ALL_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_REPEAT_ALL.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_REPEAT_ONE_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_REPEAT_ONE.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_SHUFFLE_OFF_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_SHUFFLE_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_SHUFFLE_ON_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_SHUFFLE_ON.pbm", "audio player image" );
#ifdef __MMI_TOUCH_SCREEN__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_REPEAT_OFF_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_REPEAT_OFF_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_REPEAT_ALL_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_REPEAT_ALL_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_REPEAT_ONE_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_REPEAT_ONE_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_SHUFFLE_OFF_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_SHUFFLE_OFF_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_SHUFFLE_ON_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_SHUFFLE_ON_DOWN.pbm", "audio player image" );
#endif /*__MMI_TOUCH_SCREEN__*/
#endif /*__MMI_AUDIO_PLAYER_SKIN_SHOW_REPEAT_SHUFFLE__*/
#if !defined(__MMI_MAINLCD_128X128__) || !(defined(__MMI_MAINLCD_128X160__) && !defined(__MMI_TOUCH_SCREEN__))
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_VOLUME_INC_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_VOLUME_INC_UP.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_VOLUME_INC_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_VOLUME_INC_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_VOLUME_DEC_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_VOLUME_DEC_UP.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_VOLUME_DEC_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_VOLUME_DEC_DOWN.pbm", "audio player image" );
#endif
#ifdef __MMI_TOUCH_SCREEN__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_SETTING_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_SETTING_UP.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN1_SETTING_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin1\\\\AP_MAIN_SETTING_DOWN.pbm", "audio player image" );
#endif
#ifdef __MMI_RESOURCE_ENFB_SUPPORT__
    ResetENFBAssociatedID();
#endif

#ifndef __MMI_SLIM_AUDIO_PLAYER__
#ifdef __MMI_RESOURCE_ENFB_SUPPORT__
    SetENFBAssociatedID();
#endif
	/* skin 2 */
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_BG, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PLAYLIST_PHONE_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PLAYLIST_PHONE.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PLAYLIST_CARD_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PLAYLIST_CARD.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_VOLUME_INDICATOR, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_VOLUME_IND.pbm", "audio player image" );
  	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PROGRESSBAR, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PROGRESS_FILL.pbm", "audio player image" ); 
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PROGRESSBAR_FAIL, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_PROGRESS_FAIL.pbm", "audio player image" );        
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PREV_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PREV_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PREV_OFF, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PREV_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PREV_DISABLED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PREV_DISABLED.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PREV_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PREV_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_NEXT_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_NEXT_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_NEXT_OFF, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_NEXT_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_NEXT_DISABLED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_NEXT_DISABLED.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_NEXT_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_NEXT_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PLAY_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PAUSE_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PLAY_OFF, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PLAY_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PLAY_DISABLED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PLAY_DISABLED.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PLAY_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PLAY_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PAUSE_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PLAY_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_PAUSE_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_PAUSE_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_STOP_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_STOP_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_STOP_OFF, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_STOP_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_STOP_DISABLED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_STOP_DISABLED.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_STOP_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN2\\\\AP_MAIN_STOP_DOWN.pbm", "audio player image" );
#ifdef __MMI_AUDIO_PLAYER_ANIMATION__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_ANIMATION, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_ANIMATION.gif", "audio player image" );
#endif
#ifdef __MMI_AUDIO_PLAYER_SKIN_SHOW_REPEAT_SHUFFLE__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_REPEAT_OFF_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_REPEAT_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_REPEAT_ALL_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_REPEAT_ALL.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_REPEAT_ONE_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_REPEAT_ONE.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_SHUFFLE_OFF_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_SHUFFLE_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_SHUFFLE_ON_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_SHUFFLE_ON.pbm", "audio player image" );
#ifdef __MMI_TOUCH_SCREEN__
    ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_REPEAT_OFF_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_REPEAT_OFF_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_REPEAT_ALL_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_REPEAT_ALL_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_REPEAT_ONE_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_REPEAT_ONE_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_SHUFFLE_OFF_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_SHUFFLE_OFF_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_SHUFFLE_ON_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_SHUFFLE_ON_DOWN.pbm", "audio player image" );
#endif /*__MMI_TOUCH_SCREEN__*/
#endif /*__MMI_AUDIO_PLAYER_SKIN_SHOW_REPEAT_SHUFFLE__*/
#if !defined(__MMI_MAINLCD_128X128__) || !(defined(__MMI_MAINLCD_128X160__) && !defined(__MMI_TOUCH_SCREEN__))
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_VOLUME_INC_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_VOLUME_INC_UP.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_VOLUME_INC_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_VOLUME_INC_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_VOLUME_DEC_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_VOLUME_DEC_UP.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_VOLUME_DEC_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_VOLUME_DEC_DOWN.pbm", "audio player image" );
#endif
#ifdef __MMI_TOUCH_SCREEN__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_SETTING_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_SETTING_UP.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN2_SETTING_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin2\\\\AP_MAIN_SETTING_DOWN.pbm", "audio player image" );
#endif
#ifdef __MMI_RESOURCE_ENFB_SUPPORT__
    ResetENFBAssociatedID();
#endif
#ifdef __MMI_RESOURCE_ENFB_SUPPORT__
    SetENFBAssociatedID();
#endif
	/* skin 3 */
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_BG, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PLAYLIST_PHONE_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PLAYLIST_PHONE.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PLAYLIST_CARD_ICON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PLAYLIST_CARD.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_VOLUME_INDICATOR, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_VOLUME_IND.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PROGRESSBAR, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PROGRESS_FILL.pbm", "audio player image" ); 
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PROGRESSBAR_FAIL, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_PROGRESS_FAIL.pbm", "audio player image" );        
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PREV_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PREV_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PREV_OFF, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PREV_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PREV_DISABLED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PREV_DISABLED.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PREV_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PREV_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_NEXT_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_NEXT_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_NEXT_OFF, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_NEXT_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_NEXT_DISABLED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_NEXT_DISABLED.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_NEXT_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_NEXT_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PLAY_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PAUSE_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PLAY_OFF, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PLAY_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PLAY_DISABLED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PLAY_DISABLED.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PLAY_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PLAY_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PAUSE_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PLAY_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_PAUSE_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_PAUSE_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_STOP_ON, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_STOP_ON.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_STOP_OFF, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_STOP_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_STOP_DISABLED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_STOP_DISABLED.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_STOP_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\SKIN3\\\\AP_MAIN_STOP_DOWN.pbm", "audio player image" );
#ifdef __MMI_AUDIO_PLAYER_ANIMATION__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_ANIMATION, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_ANIMATION.gif", "audio player image" );
#endif
#ifdef __MMI_AUDIO_PLAYER_SKIN_SHOW_REPEAT_SHUFFLE__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_REPEAT_OFF_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_REPEAT_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_REPEAT_ALL_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_REPEAT_ALL.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_REPEAT_ONE_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_REPEAT_ONE.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_SHUFFLE_OFF_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_SHUFFLE_OFF.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_SHUFFLE_ON_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_SHUFFLE_ON.pbm", "audio player image" );
#ifdef __MMI_TOUCH_SCREEN__
    ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_REPEAT_OFF_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_REPEAT_OFF_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_REPEAT_ALL_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_REPEAT_ALL_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_REPEAT_ONE_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_REPEAT_ONE_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_SHUFFLE_OFF_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_SHUFFLE_OFF_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_SHUFFLE_ON_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_SHUFFLE_ON_DOWN.pbm", "audio player image" );
#endif /*__MMI_TOUCH_SCREEN__*/
#endif /*__MMI_AUDIO_PLAYER_SKIN_SHOW_REPEAT_SHUFFLE__*/
#if !defined(__MMI_MAINLCD_128X128__) || !(defined(__MMI_MAINLCD_128X160__) && !defined(__MMI_TOUCH_SCREEN__))
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_VOLUME_INC_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_VOLUME_INC_UP.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_VOLUME_INC_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_VOLUME_INC_DOWN.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_VOLUME_DEC_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_VOLUME_DEC_UP.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_VOLUME_DEC_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_VOLUME_DEC_DOWN.pbm", "audio player image" );
#endif
#ifdef __MMI_TOUCH_SCREEN__
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_SETTING_UP, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_SETTING_UP.pbm", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_MAIN_SKIN3_SETTING_DOWN, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\Skin3\\\\AP_MAIN_SETTING_DOWN.pbm", "audio player image" );
#endif
#ifdef __MMI_RESOURCE_ENFB_SUPPORT__
    ResetENFBAssociatedID();
#endif
#endif /* __MMI_SLIM_AUDIO_PLAYER__ */


	/*Add time stretch resource*/
#ifdef __MMI_AUDIO_TIME_STRETCH__
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_UNSUPPORTED_SPEED,			"Speed not support",	"Audio Player String" );

	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SPEED,			"Speed",	"Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SPEED_NORMAL,	"Normal",	"Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SPEED_FAST1,	"Fast",		"Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SPEED_FAST2,	"Fastest",	"Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SPEED_SLOW2,	"Slowest",	"Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SPEED_SLOW1,	"Slow",		"Audio Player String" );

	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SETTINGS_SPEED, CUST_IMG_PATH"\\\\MainLCD\\\\AudioPlayer\\\\AP_AUDIO_SPEED.pbm", "audio player image" );
#endif /* __MMI_AUDIO_TIME_STRETCH__ */

#ifdef __MMI_AUDIO_PLAYER_ON_SUBLCD__
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SUB_OPTION_REPEAT_OFF, "Repeat Off", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SUB_OPTION_REPEAT_ONCE, "Repeat Once", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SUB_OPTION_REPEAT_ALL, "Repeat All", "Audio Player String" );
	ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SUB_OPTION_EXIT, "Exit", "Audio Player String" );
       ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SUB_ERROR, "Error", "Audio Player String" );
       ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_SHUFFLE_ON, "Shuffle on", "Audio Player String" );
       ADD_APPLICATION_STRING2( STR_ID_AUDPLY_SETTINGS_SHUFFLE_OFF, "Shuffle off", "Audio Player String" );


	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_BG, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN.gif", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_PLAYLIST_PHONE_ICON, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_PLAYLIST_PHONE.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_PLAYLIST_CARD_ICON, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_PLAYLIST_CARD.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_VOLUME_INDICATOR, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_VOLUME_IND.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_PREV_ON, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_PREV_ON.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_PREV_OFF, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_PREV_OFF.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_PREV_DISABLED, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_PREV_DISABLE.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_PREV_DOWN, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_PREV_DOWN.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_NEXT_ON, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_NEXT_ON.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_NEXT_OFF, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_NEXT_OFF.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_NEXT_DISABLED, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_NEXT_DISABLE.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_NEXT_DOWN, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_NEXT_DOWN.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_PLAY_ON, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_PLAY_ON.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_PLAY_OFF, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_PLAY_OFF.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_PLAY_DISABLED, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_PLAY_DISABLE.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_PLAY_DOWN, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_PLAY_DOWN.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_PAUSE_ON, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_PAUSE_ON.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_PAUSE_DOWN, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_MAIN_PAUSE_DOWN.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_REPEAT_SELECTED, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_SUB_SELECT_IND.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_REPEAT_NOT_SELECTED, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_SUB_NO_SELECT_IND.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_REFRESH_LIST, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_SUB_REFRESH_LIST.bmp", "audio player image" );
	ADD_APPLICATION_IMAGE2( IMG_ID_AUDPLY_SUB_SKIN_ERROR, CUST_IMG_PATH"\\\\SubLCD\\\\Application\\\\AudioPlayer\\\\skin\\\\AP_SUB_ERROR.bmp", "audio player image" );
#endif


#endif /* __MMI_AUDIO_PLAYER__ */
}

#endif


