
   {  /* mms profile 1 - FET */
	      1,
	      0,
	      9201,
	      "FET MMS",
	      "http://mms",
	      CUSTOM_DEFAULT_MMS_PROFILE1,
	      1,
	      210, 241, 199, 199,
	      "",
	      ""
     },
     {  /* mms profile 2 - CHT */
	      1,
	      0,
	      8080,
	      "CHT MMS",
	      "http://mms.emome.net:8002",
	      CUSTOM_DEFAULT_MMS_PROFILE2,
	      1,
	      10, 1, 1, 1,
	      "",
	      ""
      },
     {  /* mms profile 3 - TWN */
	      1,
	      0,
	      80,
	      "Taiwan mobile MMS",
	      "http://mms",
	      CUSTOM_DEFAULT_MMS_PROFILE3,
	      1,
	      10, 1, 1, 1,
	      "",
	      ""
      },
      {  /* mms profile 4 - CHINA MOBILE *///sc.wu mms setting default
	      1,
	      0,
	      80,
	      "China Mobile MMS",
	      "http://mmsc.monternet.com",
	      CUSTOM_DEFAULT_MMS_PROFILE4,
	      1,
	      10, 0, 0, 172,
	      "",
	      ""
	},
	{  /* mms profile 5 - AIS */
	      1,
	      0,
	      8080,
	      "AIS MMS",
	      "http://mms.mobilelife.co.th",
	      CUSTOM_DEFAULT_MMS_PROFILE5,
	      1,
	      203,170,229,034,
	      "",
	      ""
      },
      {  /* mms profile 6 - DTAC */
	      1,
	      0,
	      8080,
	      "DTAC MMS",
	      "http://mms.dtac.co.th:8002",
	      CUSTOM_DEFAULT_MMS_PROFILE6,
	      1,
	      203,155,200,133,
	      "",
	      ""
      },
     {  /* mms profile 7 - TRUE */
	      1,
	      0,
	      8080,
	      "TRUE MMS",
	      "http://mms.trueworld.net:8002",
	      CUSTOM_DEFAULT_MMS_PROFILE7,
	      1,
	      10,4,7,39,
	      "true",
	      "true"
      },      
      {  /* mms profile 8 - Empty */
		1,
		1,
		0,
		"",
		"",
		CUSTOM_DEFAULT_MMS_PROFILE_EMPTY,
		3,
		0, 0, 0, 0,
		"",
		""
	},
	{  /* mms profile 9 - Empty */
		1,
		1,
		0,
		"",
		"",
		CUSTOM_DEFAULT_MMS_PROFILE_EMPTY,
		3,
		0, 0, 0, 0,
		"",
		""
	},
	{  /* mms profile 10 - Empty */
		1,
		1,
		0,
		"",
		"",
		CUSTOM_DEFAULT_MMS_PROFILE_EMPTY,
		3,
		0, 0, 0, 0,
		"",
		""
	},

