  {  /* wap profile 1 - FET */
	      1,
	      0,
	      9201,
	      "FET",
	      "http://mobile.fetnet.net",
	      CUSTOM_DEFAULT_WAP_PROFILE1,
	      1,
	      210, 241, 199, 199,
	      "",
	      ""
     },
     {  /* wap profile 2 - CHT */
		1,
		0,
		8080,
		"CHT",
		"http://wap.emome.net",
		CUSTOM_DEFAULT_WAP_PROFILE2,
		1,
		10, 1, 1, 1,
		"",
		""
    },
    {  /* wap profile 3 - Taiwan mobile */
		1,
		0,
		80,
		"Taiwan mobile",
		"http://ewap",
		CUSTOM_DEFAULT_WAP_PROFILE3,
		1,
		10, 1, 1, 1,
		"",
		""
    },
    {  /* wap profile 4 - CHINA MOBILE */
		1,
		0,
		80,
		"China Mobile",
		"http://wap.monternet.com",
		CUSTOM_DEFAULT_WAP_PROFILE4,
		1,
		10, 0, 0, 172,
		"",
		""
   },	
   {
		/* wap profile 5 - FET */
		1,
		0,
		8080,
		"AIS GPRS",
		"http://wap.mobilelife.co.th",
		CUSTOM_DEFAULT_WAP_PROFILE5,
		1,
		203,170,229,034,
		"",
		""
   },
  {  /* wap profile 6 - CHT */
	      1,
	      0,
		8080,
		"DTAC GPRS",
		"http://wap.djuice.co.th",
		CUSTOM_DEFAULT_WAP_PROFILE6,
		1,
		203,155,200,133,
		"",
		""
  },
  {  /* wap profile 7 - True mobile */
		1,
		0,
		8080,
		"TRUE MOVE GPRS",
		"http://wap.trueworld.net",
		CUSTOM_DEFAULT_WAP_PROFILE7,
		1,
		10,4,4,4,
		"true",
		"true"
  },
  {  /* wap profile 8 - Empty */
	      1,
	      1,
	      0,
	      "",
	      "",
	      CUSTOM_DEFAULT_WAP_PROFILE_EMPTY,
	      3,
	      0, 0, 0, 0,
	      "",
	      ""
    },
    {  /* wap profile 9 - Empty */
		1,
		1,
		0,
		"",
		"",
		CUSTOM_DEFAULT_WAP_PROFILE_EMPTY,
		3,
		0, 0, 0, 0,
		"",
		""
     },
     {  /* wap profile 10 - Empty */
	      1,
	      1,
	      0,
	      "",
	      "",
	      CUSTOM_DEFAULT_WAP_PROFILE_EMPTY,
	      3,
	      0, 0, 0, 0,
	      "",
	      ""
	}
		