/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of MediaTek Inc. (C) 2006
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
*  RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename:
 * ---------
 *   custom_sap.h
 *
 * Project:
 * --------
 *   Maui_Software
 *
 * Description:
 * ------------
 *   This file provide for customization message id
 *
 * Author:
 * -------
 *   system auto generator V0.30
 *
 *============================================================================
 *             HISTORY
 * Below this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *------------------------------------------------------------------------------
 * $Revision$
 * $Modtime$
 * $Log$
 *
 *------------------------------------------------------------------------------
 * Upper this line, this part is controlled by PVCS VM. DO NOT MODIFY!!
 *============================================================================
 ****************************************************************************/

/* Add customization message id here */
MSG_ID_CUSTOM1_CUSTOM2  =  CUSTOM_MSG_CODE_BEGIN,
MSG_ID_CUSTOM2_CUSTOM1,
#ifdef CMS_NEW_APP
MSG_ID_CMS_MMS_STARTUP,
MSG_ID_CMS_WAP_STARTUP,
MSG_ID_CMS_MAP_STARTUP,
MSG_ID_CMS_MMS_SHUTDOWN,
MSG_ID_CMS_WAP_SHUTDOWN,
MSG_ID_CMS_MAP_SHUTDOWN,
MSG_ID_CMS_MAP_TEST,
MSG_ID_CMS_WAP_PARSER,
MSG_ID_CMS_WAP_LAYOUT,
MSG_ID_CMS_WAP_DRAW,
MSG_ID_CMS_WAP_PAGEUP,
MSG_ID_CMS_WAP_PAGEDOWN,
MSG_ID_CMS_WAP_NEWINPUTURL,
MSG_ID_CMS_WAP_EDITBOX,
MSG_ID_CMS_WAP_MAILADDRESS,
MSG_ID_CMS_WAP_CALLREQUEST,
MSG_ID_CMS_WAP_STOREPHONENUM,
MSG_ID_CMS_WAP_NEXTLINKFOCUS,
MSG_ID_CMS_WAP_LASTLINKFOCUS,
MSG_ID_CMS_WAP_RIGHTLINKFOCUS,
MSG_ID_CMS_WAP_LEFTLINKFOCUS,
MSG_ID_CMS_WAP_SOCCLOSESUCCESS,
MSG_ID_CMS_WAP_SOCCLOSEFAIL,
MSG_ID_CMS_WAP_UPPAGE,
MSG_ID_CMS_WAP_DOWNPAGE,
MSG_ID_CMS_WAP_TOUCHPENDOWN,
MSG_ID_CMS_WAP_TOUCHPENUP,
MSG_ID_CMS_WAP_DEVDEACTIVEATE,
MSG_ID_CMS_WAP_PAGEREFRESH,
MSG_ID_CMS_MMS_NOTIFICATION_ARRIVE,
MSG_ID_CMS_MMS_RECV_SUCCESS,
MSG_ID_CMS_MMS_SEND_SUCCESS,
MSG_ID_CMS_MMS_RECV_FAILED,
MSG_ID_CMS_MMS_SEND_FAILED_UNKNOWN,
MSG_ID_CMS_MMS_SEND_MESSAGE,
MSG_ID_CMS_MMS_RECEIVE_MESSAGE,
MSG_ID_CMS_MMS_CONNECT_FAILED,
MSG_ID_CMS_MMS_PLAY_MESSAGE,
MSG_ID_QQ_1,
MSG_ID_QQ_2,
MSG_ID_QQ_3,
MSG_ID_QQ_4,
MSG_ID_QQ_5,
MSG_ID_QQ_6,
#endif
#if defined(G_SENSOR_SUPPORT)
//Huyanwei Add It 
MSG_ID_GSENSOR_OFF,
MSG_ID_GSENSOR_ON,
MSG_ID_GSENSOR_WORK,
MSG_ID_GSENSOR_UP,
MSG_ID_GSENSOR_DOWN,
MSG_ID_GSENSOR_LEFT,
MSG_ID_GSENSOR_RIGHT,
MSG_ID_GSENSOR_FRONT,
MSG_ID_GSENSOR_BACK,
#endif
#if defined(HORSERACE_SUPPORT)
//Huyanwei Add It 
MSG_ID_HORSERACE_OFF,
MSG_ID_HORSERACE_ON,
MSG_ID_HORSERACE_WORK,
#endif

#if defined(DOUBLE_BATTERY_SUPPORT)
//Huyanwei Add It 
MSG_ID_BATTERYII_PLUG_IN,
MSG_ID_BATTERYII_PLUG_OUT,
#endif

/* 2009.05.04 added by hongzhe.liu for m-sensor +  */
 #if defined(__DIRECTION_SENSOR_SUPPORT__)
MSG_ID_MSENSOR_DIRECTION_0,
MSG_ID_MSENSOR_DIRECTION_90,
MSG_ID_MSENSOR_DIRECTION_180,
MSG_ID_MSENSOR_DIRECTION_270,
#endif
/* 2009.05.04 added by hongzhe.liu for m-sensor -  */


